### ISSUE TITLE
add option: delete waypoint

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#10017]
**Is your feature request related to a problem?**
On the map it's easy (long click) to create a waypoint but difficult to delete an existing. You have to click, get the name, go back to list of all waypoints, search the name, long click, delete.
**Describe the solution you'd like**
A trash bin symbol (here orange) should be added to the edit page of a waypoint.
![IMG_20210215_062917](https://user-images.githubusercontent.com/43813636/107910169-21382700-6f5a-11eb-8d29-a7bb85e71177.jpg)

**Comment by bekuno** [comment]
Instead of adding this in the edit menu I suggest to enhance the single waypoint menu.

The menu for a single waypoint is:
![waypoint_menu_list](https://user-images.githubusercontent.com/32555742/108122962-67e66800-70a5-11eb-993d-2c8ba12e1edc.jpg)
and within the cache waypoint list:
![waypoint_menu_single](https://user-images.githubusercontent.com/32555742/108122968-69b02b80-70a5-11eb-81d6-2c9258023a50.jpg)

So we miss the button `Delete` and should it add in the single waypoint menu.
Maybe also the buttons `Copy coordinates`and Clear coordinates` could be helpfull.

Additional the text `Log Visit` and `Visited` should be unified.
Also the order of the menu items could be arranged both in the same way.

**Comment by geocachermgo** [comment]
meanwhile included in context menu
