### ISSUE TITLE
Duplicated GSAK logs on GPX import

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10028]
A user contacted us, that he has a specific problems since some releases (probably starting with 2021.01.10):

- The user handles his caches with GSAK
- Then he exports the desired caches from GSAK into a GPX which he imports to c:geo. This usually also contains caches already stored (from the last import) to refresh them.
- The GSAK GPX contains a special log (as first log) which contains user specific information (selectable by the user)

In former versions this worked perfectly fine (first log is the GSAK special log).
Recently he has the problem, that this special log entry gets duplicated on each new import of a GPX with this special log.

The log part of the GPX looks like this (whole file available upon request):
```
 <groundspeak:logs>
    <groundspeak:log id="-3">
    <groundspeak:date>2021-02-15T08:00:00Z</groundspeak:date>
    <groundspeak:type>Write note</groundspeak:type>
    <groundspeak:finder id="0">GSAK</groundspeak:finder>
    <groundspeak:text encoded="False">Guilford County,  N
    </groundspeak:text>
   </groundspeak:log>
```

IMHO this is related to the recently introduced merge capability on GPX import but should/could be avoided.

**Comment by Lineflyer** [comment]
BTW:
I received the GPX file meanwhile and was **not** able to reproduce this by repeatedly importing the same file. So either its a matter of import date or maybe the log id is changing?

Maybe the implementor of the GPX merge feature can bring more light on this which criteria is evaluated here.

**Comment by Lineflyer** [comment]
Thats an example of how it looks for the user:

![grafik](https://user-images.githubusercontent.com/949669/108096210-feecf900-7080-11eb-9977-34c802069467.png)

**Comment by Lineflyer** [comment]
The difference in consecutive inputs seems to be only the date/time stamp.
The log ID however is the same, can we handle this case to avoid duplication. IMHO we already have some treatment for GSAK logbook entries in the GPX importer.

```
    <groundspeak:log id="-3">
    <groundspeak:date>2021-02-16T08:00:00Z</groundspeak:date>
    <groundspeak:type>Write note</groundspeak:type>
    <groundspeak:finder id="0">GSAK</groundspeak:finder>
    <groundspeak:text encoded="False">Guilford County,  N
    </groundspeak:text>
   </groundspeak:log>
```

**Comment by moving-bits** [comment]
Merging is done on database level by deleting logs matching the following criteria: `DELETE FROM " + dbTableLogs + " WHERE geocode = ? AND date = ? AND type = ? AND author = ?` - so at least one of this criteria seems to be unmatched. Maybe you can forward me the GPX via PM, so that I can test-drive it in the debugger.

**Comment by Lineflyer** [comment]
Sent via mailing list

**Comment by moving-bits** [comment]
Thanks for forwarding. From the analysis it's clear and to be expected behavior, because the log entries actually DO have a different date/time stamp, so they are regarded as distinct log entries:

`<groundspeak:date>2021-02-15T08:00:00Z</groundspeak:date>` vs.
`<groundspeak:date>2021-02-16T08:00:00Z</groundspeak:date>`

Seems that the date of those special log entries are set by GSAK to the export date.

Question is: How to handle this case?

During import we can detect such entries by checking either log id (negative number) or author (0/"GSAK"). Problem is, that we do not store the internal log id on GPX import, so we can only compare against the author, which might give you several hits for a geocode. So one possible solution for this edge case may be:

on importing a bunch of logs (if `removeAllExistingLongs` == false):
- for every log with log id < 1: remember its geocode
- for every found geocode: delete all logs from author "GSAK" for this geocode

and only then continue with today's "merge on import"

**Comment by Lineflyer** [comment]
I somehow remember, that we once (might be long ago) used a logic for GPX imports which actually considered the log id for merging. I also remember having discussed a very similar case for GSAK parts in GPX files long time ago. I will try to browse the issues.

**Comment by Lineflyer** [comment]
First finding dealing with a workaround to replace this "first log" by user dates which would avoid this problem as well and makes use of the personal note instead.
https://github.com/cgeo/cgeo/issues/6484

**Comment by Lineflyer** [comment]
Reading it all again:
I think we do nothing wrong here. The log entry has a new date and (may contain new information). The fact, that the user only expects it to appear once is kind of random. Other users might say: I updated the information and I want to see the info from todays import as well as the info from the last import.

The only thing which objects this is, that GSAK seems to use the very same logID to tell, that it should be treated as the same information..somehow inconsistent if the date changes IMHO.

Whatever:
I suggested the user to check if his use case will work by using the UserDate fields (as mentioned in #6484) instead. Lets wait for feedback before changing anything which might break things on other occasions.

**Comment by Lineflyer** [comment]
Feedback from the user...need to thing about this. Especially I was unaware that not only the GSAK log is doubled, but also other logs (@moving-bits Can you reproduce this, I did not pay attention to the remaining logs).

---

Unfortunately we do NOT create a "fake log" in GSAK to create that log, it is brought in from the County column and the "corrected coords" column.  Sometimes we use the User Date 1 and User Data 2, but the gpx file created in GSAK imports that data as a first log.  GSAK is probably the most widely used database used by geocachers and everyone I know is having this same issue... it is NOT isolated to me.  I noticed that not only are the logs I create being doubled, tripled, etc... ALL logs are being doubled, tripled, etc.  Many people are concerned with this and we can't understand why you would make this drastic change to please an apparent single user at the expense of experienced cachers who have used c:geo for such a long time.  Somehow, c:geo needs to recognize that when I delete or remove a cache from a database (which is what we do before loading a database) we want the hidden logs to disappear.  Or... as another cacher suggested, give us the ability to reverse the recent changes that caused this issue.  Why was a good thing broken for no reason?

---

**Comment by moving-bits** [comment]
> Feedback from the user...need to think about this. Especially I was unaware that not only the GSAK log is doubled, but also other logs (@moving-bits Can you reproduce this, I did not pay attention to the remaining logs).

No, cannot confirm here. I've imported both the "newer" and the "older" file and checked a handful of caches - no logs are doubled (except the GSAK pseudo-logs, which are technically different).

Anyway, a solution to the user's problem could be to prepend a dialog box to GPX import, asking whether to delete ALL existing logs of caches included in the GPX file.

**Comment by Narrat** [comment]
Maybe there is an option hidden in the settings of GSAK? Which does stuff like importing all logs or whatever. It kinda seems there is a specific and possibly not default use-case at work.
But the tone in the message.. fantastic. And kinda reminds me of [this](http://www.xkcd.com/1172)

**Comment by eddiemuc** [comment]
Is there a possibility to talk to some GSAK expert about this? Someone who can bring light into why GSAK sends log entries with same Id but different date/time information?

And for the c:geo side: would it be possible to use the logid **only** (if there is one) to decide whether entries belong to same log and other information (date, user etc) only when there is no logid?
(Rational: if there is a log id it should be the one and only identifier for a single log entry afaik)

**Comment by howc37** [comment]
I think gsak always creates them new, because they include for example the information: "Favourites" which can obviously change from one day to another.  Previously this comment included the text of the attributes which I already turned off. 

maybe you can connect here with GSAK
https://gsak.net/board/index.php?showtopic=7745&st=20&

at least I'm using the GarminExport-Marco. (There are differente ways of exporting gpx-files from GSAK I guess)

**Comment by howc37** [comment]
if you are using garminexport.gsak removing this lines from the macro would remove this logs in general, so you won't get the entry updated either.
![grafik](https://user-images.githubusercontent.com/4988786/112761001-545de380-8ff9-11eb-9419-daef7356cb92.png)

**Comment by moving-bits** [comment]
related to #7090
