### ISSUE TITLE
Meaning of string folder_process_status_currentfile

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10063]
Does it really mean process or rather progress?

**Comment by eddiemuc** [comment]
I used the term "FolderProcess" in code for an abstraction over "processes" done on "folders". (Current implementations are copy, move and synchronize). This is where this comes from.

But I can see that this is confusing because the string is indeed displayed in a progress bar showing the progress of the process.

**Comment by Lineflyer** [comment]
understood. So lets close.
