### ISSUE TITLE
Stuck on cache refresh/delete

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10089]
Short note from field:
Keep having problems with 2021.02.28-NB like this:
- Refresh a list: Progress runs up to 100% but never completes
- Delete some caches from a list, shows "Deleting caches" window forever

Need to check in detail later when home again

**Comment by Lineflyer** [comment]
The mentioned problems occur only relatively short time after starting c:geo.

I fear, this is somehow connected with the background sync of themes blocking something here while its still ongoing...might that be the case?

**Comment by eddiemuc** [comment]
The background sync may eat away the CPU of course and thus block other processes from getting their working time. Other than that I could not imagine any blocker. I used normal asynctask for this.

**Comment by MagpieFourtyTwo** [comment]
> I fear, this is somehow connected with the background sync of themes

Doubt it. Have you already seen the sync toast?  What does it say?  You may have to change the name of a theme file to get it ...
Over here the sync task takes about 550-600 msec - I tried, but was not able to select a list and start the refresh within half a second ... do you?  If so, respect!  ;)

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo 
the sync takes much longer on @Lineflyer s device (well over 10 seconds) in combination with using a SD card as target. This is what we try to analyze in #10075

**Comment by MagpieFourtyTwo** [comment]
> over 10 seconds

Wow. Although he has just a few more themes than me ... really strange.
IIRC @Lineflyer is already using Android 11, right?  If that's where the problem comes from, I'm afraid I can't help, because over here it's still Android 10 (and probably will stay for quite a while, due to some very well-known interventionism policy). Otherwise, feel free to ask.

> we try to analyze in #10075 

Yep, skimmed that a few days ago, but had not enough time to read it entirely. Will look over it again.

**Comment by Lineflyer** [comment]
I am no longer able to reproduce this. I guess fixing of #10075 also fixing this implicitly (as the process is faster now).
