### ISSUE TITLE
Include debug logging into SAF procedures

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10083]
I am not 100% aware of how the logging possibilities are with Android.
However from what I know in the past we have included "debug log messages" at various points in the code to have the possibility - when turning on "Activate debug log" in c:geo Settings - System - to retrieve more information in the system logfiles about internal processes to help with debugging.

I just tried various SAF related operations (such as moving the base folder or setting a new location for GPX, etc.) with debug log activated. I did not see any related "D/cgeo" messages in the log. Wouldn't it be wise to include them at some points (e.g. results of some actions like selecting a folder, copying of files, etc.)?

**Comment by eddiemuc** [comment]
Logging is very important to me :-)

Generally everything you see as a toast wrt SAF is also logged, depending on severity either on info or warning level. Both should be in log in debug mode. This should cover all the "normal" operational cases. 

Also due to the pending performance problems I included various time-measurement routines which will fire logs at verbose level.

And of course there are various error/Info logs in special cases

**Comment by eddiemuc** [comment]
But there can always be more wrt logs imho, so yes I am very open for extensions here

**Comment by eddiemuc** [comment]
Here is an example for a log on INFO level (=included in debug mode) for a normal map folder change:
`
2021-02-27 13:54:54.823 23043-23043/cgeo.geocaching I/cgeo: [main] Folder set to 'OFFLINE_MAPS: /cgeo/maps (User-defined)[/cgeo/maps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::], default: /storage/emulated/0/cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/maps]](content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps)'
`
Here is an example for time-measuring log on VERBOSE level (=only includable via log-properties.txt) on each list() operation on any SAF folder:

`2021-02-27 13:58:19.719 23908-23958/cgeo.geocaching V/cgeo: [AsyncTask #1] ContentStorage.list: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData/shared/MapThemeData[FILE#0:p-file:///storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData/shared/MapThemeData::]:END (4ms)#9(4ms); {ContentStorage.list:216/ContentStorage.list:200/FolderUtils.treeWalk:737/FolderUtils.treeWalk:733/FolderUtils.getAllFiles:78/FolderUtils.synchronizeFolder:185/RenderThemeHelper$MapThemeFolderSyncTask.doInBackground:442/RenderThemeHelper$MapThemeFolderSyncTask.doInBackground:397/AsyncTask$3.call:378/FutureTask.run:266}
`

**Comment by eddiemuc** [comment]
(On a side note: as you can see, a simple list operation on a single folder using SAF takes **4ms**! This is monstrous! )

**Comment by eddiemuc** [comment]
It seems nothing needs to be done here any more. Can this be closed?

**Comment by Lineflyer** [comment]
I think so. Still have to make myself familiar with this verbose logging configuration. I was used to in the past, that with debug mode active I could see such progress messages (indicating whats going on in the background). But seeing time measurements is something even deeper, not needed for simple debug log).

**Comment by eddiemuc** [comment]
@Lineflyer indeed I feel that a general concept of "logging" is somehow missing. To fill this gap, I tend to apply my personal general understanding on how things are logged. This may of course be debatable.

My understanding of logging is this:
* Log files are primarily a tool for developers & production support, so the needs of this should define what needs to be in it or not.
*  A side-requirement is that in "normal" operation log amount should not exceed "reasonable bounds". This is the main purpose of "Log Level" configuration (e.g. logging only certain levels and others not)
* I usually use the Log Levels as follows:
    * ERROR: an error happened from which app can't recover itself (thus most often results in app crash or controlled shutdown etc, at least some serious functional loss)
    * WANR: an error happened for which app has a mitigation strategy and thus can recover itself
    * INFO: informational message wrt normal workflow e.g. important things that happened (imho, the change of a public folder would be such an event)
    * DEBUG: messages specifically introduced ( in conjunction with error/warn/info msg) to analyze potential error situations (since it is hard to predict what kind of errors will happen in the future, placing DEBUG messages is a bit of a "best guess")
    * VERBOSE: messages for deep system analyzation (e.g. timing measurements). VERBOSE should be used instead of DEBUG if it is clear that there will be a huge amount of log messages produced when it is turned on (usually a log file will overflow quickly when VERBOSE is turned on). E.g. usage in tight loops
* My usual understanding is that in "normal" operation, log level is INFO, and specifically to error analysis it is turned to DEBUG or VERBOSE (here, c:geo has a different understanding since normal level is WARN and VERBOSE is not even chooseable via Settings, only by log properties)

Again, this is just my personal "default opinion". This is of course wide open for debate and I am willing to comply to every other agreement reached in past or future as a group.
