### ISSUE TITLE
Unusual amount of users reporting unwanted compact icons

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10097]
I do now have a total of 10 users (which is remarkable for a single issue, given that only a low percentage contacts support usually) contacting support mail with a problem described like this:
"After updating to the current release all cache symbols are only dots, please bring back the old icons!"
First mails came in with 2021.01.16 and now also for 2021.02.14.

The solution was easy: Advise users to disable compact icons in map quick settings.

Question from my side:
Did we change any default for this or migrate in a wrong way at some point?
I would assume this feature is switched off by default on new installs? Correct?

**Comment by moving-bits** [comment]
Strange. Settings' side seems to be ok, code sequence is this:
```
public static int getCompactIconMode() {
    final String prefValue = getString(R.string.pref_compactIconMode, "");
    if (prefValue.equals(getKey(R.string.pref_compacticon_on))) {
        return COMPACTICON_ON;
    } else if (prefValue.equals(getKey(R.string.pref_compacticon_auto))) {
        return COMPACTICON_AUTO;
    }
    return COMPACTICON_OFF;
}
```
Defaults to "off", and has not changed since we introduced the "AUTO" variant last year in June. (Same is true for the constants COMPACTICON_XXX.)

Need to check the map marker creation side yet, though.

**Comment by Lineflyer** [comment]
Might be also users selecting something they don't understand and don't remember it afterwards. You never know...but this might be 1 or 2 users only usually. So with my experience it seems at least suspicious.

**Comment by eddiemuc** [comment]
IIRC this option was not very "prominently" placed in the past while now it is very "highlighted" in the quick settings (due to shere size and the prominent three-button-placement where one button is orange). Also, the label (in german) says "Nutze kompakte Symbole". I am not sure if users understand that "kompakte symbole" are simply dots, they might think that this leads to just "smaller" icons or something. 

Just guessing of course, but maybe this is a source for higher confusion rates than usual

**Comment by Lineflyer** [comment]
No longer appearing.
