### ISSUE TITLE
Restore SAF permissions on settings backup restore

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10105]
Follow-up of #10101:

Right now we assume that existing permissions for persistent folders are lost on app deinstallation / app data reset. This would mean, that if a user reinstalls c:geo and/or restores a settings backup, we will have the following situation:
The (restored) settings contain values for persistable folders which are no longer usable/connected/permitted.

We should first check if the assumption of lost permissions is correct (which is likely).
If the assumption is correct, we should find a suitable solution for such cases, which could IMHO be that we check while restoring settings, if the current URI are equal to the URI contained in the settings backup or not.
If they are the same its most likely, that there are still valid permissions behind, if not (means they are empty or different) we probably need to trigger the wizard or another clever way to let the user decide what to do.

**Comment by MagpieFourtyTwo** [comment]
IMO: In case of config restore the wizard should be triggered in a way to make him ask for *every* SAF folder configured, no matter if necessary or (possibly) not.  Cause this is really critical stuff, thus safety should come first.  Moreover it's a (hopefully) pretty seldom scenario, thus comfort can be set aside.

**Comment by eddiemuc** [comment]
I am absolutely with you.

But please remember that I build in something like this in the beginning and it did not work pretty great. 

To be more precise: in first version I build into the system that c:geo checks at startup for each public folder whether it can currently reach it. If not, it set the folder to its default value (e.g. for OFFLINE-MAPS folder this is folder "maps" underneath the BASE folder). This did not work out pretty well because for some reason c:geo could often not access especially SD-card-folders at startup and thus resetted the folders (I dimly remember that this was a case with @Lineflyer s device).

It might be that if you use the same logic to decide to open the wizard it might open more often than you want - that is if non-reaching-folders-just-at-startup are continuing to be a thing.

**Comment by fm-sys** [comment]
We could add some preference key like `init_needed` and set it to true after restoring a (settings) backup...

**Comment by MagpieFourtyTwo** [comment]
Why reset? The folder was configured, thus (most probably) has been used before, so why should it no longer be accessible?
All I would do is ask for permission, which is a sheer formal act, and that's it ...

**Comment by Lineflyer** [comment]
No one said resetting, but we have to think about different scenarios:
1. User freshly installed c:geo and restores backup incl. settings (he might or might not have completed the wizard, thus base folder or otherer SAF folders might have permission or might not)
2. User has all set up and working and just (for whatever reason) restores a backup incl. settings
3. Any other scenario?

Isn't the solution always the same:
I don't know how those SAF folders and permissions are stored in our settings, but isn't it possible to compare values currently set with values from backup?
In this case it would be (taking the base folder as example but applies possibly to all):
If `current setting <> setting in backup` request SAF permission again during/after the process of restoring. If `current setting == setting in backup` we would most probably already have the permission and should do nothing.
This - of course - would only work if there is no additional magic (e.g. keys or unique IDs) involved in SAF which get overwritten by restoring a backup.

**Comment by eddiemuc** [comment]
@Lineflyer 
Comparing old and new (restored) value will only work inside same c:geo session, e.g. when user reclaims permissions (where necessary) immediately after restore. If user restored and then restarts c:geo the "discrepancy" information will be lost.

I think @fm-sys s idea goes into the right direction: we have to somehow store in the properties which folder settings have been changed, and wizard could be tweaked to ask for re-permission for exactly those folders at startup as long as they are not accessible and have not been set anew. (It is a bit similar to how wizard handles migrated legacy values as of now)

**Comment by fm-sys** [comment]
> we have to somehow store in the properties which folder settings have been changed

I think we don't even need to store which folders where changed, but simple check all folders if they are still accessible after restore. If not, open the wizard and ask for permissions (Of course with the restored path as start dir in the chooser). This would be pretty straightforward and easy, as well for users as also from coding perspective

**Comment by eddiemuc** [comment]
> > we have to somehow store in the properties which folder settings have been changed
> 
> I think we don't even need to store which folders where changed, but simple check all folders if they are still accessible after restore. If not, open the wizard and ask for permissions (Of course with the restored path as start dir in the chooser). This would be pretty straightforward and easy, as well for users as also from coding perspective

Again: this will only work if in case of non-accessibility the user **immediately** (re-)selects the folder. If the user chooses to "skip" the wizard at this point, then he will never be reminded again and the folders stay inaccessible.

**Comment by MagpieFourtyTwo** [comment]
> we have to somehow store in the properties which folder settings have been changed,

Thought this is implicitly clear:  If an SAF setting exists, s/th has been changed ... or am I missing s/th?
While I would still just ask for *all* defined folders, no matter if (seemingly) accessible or not.
And "Skip" should not be an option, IMHO.  If one decides to perform a restore, he is most probably not a DAU and should know what to do. Otherwise he should ask an expert anyway, cause delete/restore is not a trivial thing to play around with. IMO.

**Comment by eddiemuc** [comment]
> > we have to somehow store in the properties which folder settings have been changed,
> 
> Thought this is implicitly clear:  If an SAF setting exists, s/th has been changed ... or am I missing s/th?

If a setting exists, then we know the user has set a user-defined folder. Such a setting will be overriddden with a value from a previously backup'd value on restore. From the existence of a value alone we can't conclude whether it was previously set by restore or simply set by the user via Settings.

**Comment by MagpieFourtyTwo** [comment]
> From the existence of a value alone we can't conclude whether it was previously set by restore or simply set by the user via Settings.

Yes, obviously - but does this really matter?  Why not just ask for all of them, *in one go with the restore procedure* ...?

**Comment by eddiemuc** [comment]
> > From the existence of a value alone we can't conclude whether it was previously set by restore or simply set by the user via Settings.
> 
> Yes, obviously - but does this really matter?  Why not just ask for all of them, *in one go with the restore procedure* ...?

Ah, ok, it took a little longer for me to understand what you mean. I might get old... Sorry for this.

I think you're right, this might be the best solution

**Comment by MagpieFourtyTwo** [comment]
> I might get old... Sorry for this.

Don't think so. Just need to take a look at all the stuff you're working on, most of the times even simultaneously, to be absolutely sure there's a quick and alert young mind at work. ;)

**Comment by moving-bits** [comment]
I would not ask for _every_ SAF folder, only for those which are set in the to-be-restored settings, and which point to a different folder than the currently set ones:

|SAF-setting in to-be-restored settings file|points to same value as current settings|action|
|---|---|---|
|unset/legacy|--|ignore|
|set|same|ignore / no change needed|
|set|different|ask user to select new folder|

---

If we do not want to force the user to answer those questions at the point of restoring settings (because he/she is in the middle of something else and just needs something different from the backup), a strategy could be like this:

step 1: on restoring a settings file:
- for all SAF folders which are defined in the to-be-restored settings file:
  - check whether they differ from the current setting
    - if not: keep the value
    - if yes: prefix the related SAF-preference key by some marker (e. g. "toberenewed://")

(no further user interaction, e. g. selecting of folders, needed at that point in time)


step 2: on every restart:
check SAF-related preference keys for this special marker, and if at least one exists: open the wizard for those. Selection can be skipped.

(This is a way very similar to how legacy to SAF migration works. Procedure is a bit less-intrusive than forcing to renew at the time of restoring a settings file.)

**Comment by eddiemuc** [comment]
My impression is that there's no common agreement whether to implement this in a "simple" way (ask on restore only) or more comprehensive way (store marker for non-accessible, non-reset folders in settings after restore).

**Comment by MagpieFourtyTwo** [comment]
My 2 cent: IMO a restore procedure must be absolutely bullet proof.  Thus, in order to minimize bug probability, implementation should be as simple as possible.  Moreover I would consider it a (hopefully) pretty seldom scenario, therefore one or two clicks more do not really matter over here, and - last but not least - a lot of work to just save these two clicks will not pay out, anyway. So why invest the effort, just to male it more complicated and vulnerable ...?

**Comment by eddiemuc** [comment]
Following idea, in the hope it incorporates all requests while staying as simple as possible 

* Introduce a new Boolean flag in the settings "Check folder access on startup" , defaults to true
* If true, on startup the wizard checks (in addition and integrated into the already existing legacy folder check) whether folders are accessible and displays itself if not.
* After restore and if any folder is not accessible, a dialog pops up "It seems after restore some folders are not accessible any more. Please run wizard to re-set permissions" and options "Not now" and "Start wizard"

(The new setting above is important for cases like @Lineflyer experienced in the past, because for some yet unknown reason some folders seemed not to be accessible at startup but only later on his first test runs)

Opinions?

**Comment by fm-sys** [comment]
> Introduce a new Boolean flag in the settings "Check folder access on startup", defaults to true

Sounds good in total but IMHO this isn't something we should add it to the settings but rather handle it internally. Maybe default it to `false` and automatically set it to `true` after restore. And at the end, change it back to `false` if all folders are successfully migrated?

**Comment by eddiemuc** [comment]
> > Introduce a new Boolean flag in the settings "Check folder access on startup", defaults to true
> 
> Sounds good in total but IMHO this isn't something we should add to the settings but rather handle it internally. Maybe default it to `false` and automatically set it to `true` after restore. And at the end, change it back to `false` if all folders are successfully migrated.

@fm-sys : my idea included also to put this onto a "higher level": not make it specific to "backup restore", but in general to check on startup whether folders are still accessible and open wizard if not. However, it is necessary imho to make this feature off-turnable by the user, because I still don't understand the initial case of @Lineflyer (where on startup folders were not accessible but later they were) and it would be very tedious to the user if he could not turn this off. We can hide this setting somewhere deep but it should be there imho.

I don't like at all systems doing too much background magic but then failing in corner cases. Better keep it simple and provide a "fallback" where user can react when things happen that we haven't foreseen (and this whole SAF topic is imho not foreseeable!)

A real world example which drove me nuts last week: my wife and me wanted to start watching a new season of a series using our favorite streaming provider. Had been a while since the last season so we were happy when a  short wrap-up of the previous season started showing. But accidentally we hit the "back" button just a few seconds into this. And what can I say? The system, in its wisdom, decided that we now don't want to see the wrap-up any more, and we couldn't find any way to see the wrap up again. I would have given much for an extra button in this scenario to overrule the secret system wisdom, but it simply wasn't there. I don't want to have such situations in c:geo

**Comment by MagpieFourtyTwo** [comment]
> I don't like at all systems doing too much background magic but then failing in corner cases. Better keep it simple and provide a "fallback" where user can react when things happen that we haven't foreseen (and this whole SAF topic is imho not foreseeable!)

Took the words right out of my mouth.
