### ISSUE TITLE
Problematic scenarios for SAF folder move/copy

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10124]
After writing #10123 while further thinking about possible problematic scenarios the following came to my mind (I describe the worst case, several other scenarios possible).

- The user selects his internal storage root level as SAF folder (as he is e.g. unsure what to do or he thinks, that all needed data is below that level anyway)
- If he uses it for GPX, base or maps its not a big deal at first (For theme this is already a big problem at this point: See #10123)
- But now the user recognises, that his selection was wrong and selects a better folder
- Unfortunately he selects the default action to "Move all content". 

Did not test it on my device, but I guess this can pretty much make his device unusable and "damage" also data of other apps. 

What could we do to prevent such accidents other than dropping the move/copy options?

**Comment by eddiemuc** [comment]
Dialog already shows the number of files and directories affected by a potential move/copy **before** user selects. I assume those numbers would be pretty high in this case and might warn the user.

But other than that no idea to prevent this other than to drop the option. There is no way known to me how you can detect for sure that e.g. the currently selected folder is some sort of "root folder". (heuristics might be possible)

**Comment by fm-sys** [comment]
Is it much additional effort, to show the total folder size in the dialog, which would be moved? That would be quite helpful for a decision whether to move the files anyway...

**Comment by eddiemuc** [comment]
> Is it much additional effort, to show the total folder size in the dialog, which would be moved? That would be quite helpful for a decision whether to move the files anyway... 

You mean the sum of all file sizes? That would be quite easy to achieve

**Comment by fm-sys** [comment]
> 
> 
> > Is it much additional effort, to show the total folder size in the dialog, which would be moved? That would be quite helpful for a decision whether to move the files anyway...
> 
> You mean the sum of all file sizes? That would be quite easy to achieve

Yep. Exactly!

If I as an average user would see an unusually large file size, that would in any case deter more than just a high number of files (How should I know how many files c:geo has stored? 20 GB in any case not ;-))

**Comment by Lineflyer** [comment]
And we could select "No further action" as default so a user interaction is needed before anything is copied or moved.

**Comment by MagpieFourtyTwo** [comment]
I would still not move nor copy anything at all, cause WRT SAF I see absolutely no need to touch a single file.
AFAIR, the initial motivation of SAF related changes is *not* that things may be or have been stored at a wrong place,
but it's *only* about the way how these places should be addressed in the future.  Please correct me if I'm wrong.
However, the fact that moving stuff may even end in a major chaos, makes the move function even more questionable.

The way I currently see it: All the stuff, the wizard may move (accidentally or on purpose), is stored in the current places for a very good reason, and these places will still be perfectly fine, even when SAF is fully in action. Moreover most users had a hard time to get things running smooth (or to get a supporter to get things up), thus this should not be risked to be destroyed with just a single careless click.

SAF wizard and associated actions should solely concentrate on solving the SAF stuff, i. e. change the folder addressing, but *not* perform any movements, as these have nothing to do with the SAF topic, anyway.

I would even go a step further: If a chosen SAF folder is not the same as the previously configured Legacy folder, I would even completely refuse to accept the change at all. Cause in fact there is no need at all to *change* a folder *within the framework of the wizard.* As there's absolutely no need for - at least I don't see one, in this context.

**Comment by eddiemuc** [comment]
The move/copy option is currently not tied to the SAF wizard, it will present itself on every folder change in the future.

Also I added displaying of total file size that would be moved (as suggested by @fm-sys).

That being said I have to agree with @Lineflyer and @MagpieFourtyTwo that this option, if used wrongly, can produce serious problems on the users device. Of course the same can happen if the user moves/copies files using any file explorer app but maybe a user is more aware of these things in such a context.

In any case, as said before, I will not have the heart to remove this option myself. But I will absolutely accept it if someone else is doing it.

**Comment by MagpieFourtyTwo** [comment]
> The move/copy option (...) will present itself on every folder change in the future.

Which is in fact a really nice thing.

But it should IMO most definitely not be triggered by the SAF wizard,
as this would couple two actions which are not related to each other.
Even more cause the risk of major damage is way to high.

Moreover: If someone wants to change a folder *on purpose,* he is most probably aware of the consequences,
and being assisted in the move or copy process really makes sense.
But if you are *forced(!) by the program* to change nothing but the *address* of a folder *due to internal reasons,*
you in fact most probably do not want anything to be changed at all, anyway.

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo 

At least today there is no separate "folder change" routine in the wizard. It just checks whether a legacy folder is used and triggers the normal folder change routine if this is the case.

Also, maybe c:geo should not force the user too harshly to change the folders. In fact, almost all parts of c:geo will continue to work fine even if folders are no longer accessible. What will not work:
* offline maps/themes (the biggest regression I admit, still c:geo is usable without)
* Backups (but could be offered via intent too, no hard need for a public folder)
* GPX/individual-route/field-note-export (but just because for some reason this is currently bound to a public folder write before user gets the chance to share via intent, this could and maybe should be changed)
* some not-so-prominent things like logfiles and Spoiler-Images.

**Comment by Lineflyer** [comment]
I do agree, that it would be a good compromise to skip move/copy options for the wizard but leave as is for manual changes later on. We have to expect, that some users are not even aware of whats going on...and the more choices you have, the more can go wrong.

People actively changing it in the menu might want to make use of copying/moving and probably know what they are doing.

**Comment by eddiemuc** [comment]
That's funny since the move feature was initially requested specifically for the migration scenario, and I just added it to the normal folder change because I assumed if we have it anyway it might as well be used there (same way I added copy option because it is technically a subset of move anyway).

But yes, it would be easy to skip copy/move option when coming from wizard. Another parameter should do it.

**Comment by fm-sys** [comment]
> I do agree, that it would be a good compromise to skip move/copy options for the wizard but leave as is for manual changes later on. 

I am still convinced that offering the cooy/move is still the right thing to do in the wizard. Users are made aware that they have chosen the wrong folder and can decide if they want to choose a different one, move the file content or ignore it. 

The only good compromise would IMHO be to make "do nothing" the default behavior, so that users have to actively select if they want to move the files. 

![Screenshot_20210313_111251_cgeo geocaching_copy_490x554](https://user-images.githubusercontent.com/64581222/111028084-a47f5800-83f4-11eb-8cd1-855e1279e9e6.png)

**Comment by Lineflyer** [comment]
> I am still convinced that offering the copy/move is still the right thing to do in the wizard. Users are made aware that they have chosen the wrong folder and can decide if they want to choose a different one, move the file content or ignore it.

Isn't it the case for the migration wizard, that the dialog "You selected another folder..." will be shown in any case as the the previous folder is the legacy folder?

**Comment by eddiemuc** [comment]
> > I am still convinced that offering the copy/move is still the right thing to do in the wizard. Users are made aware that they have chosen the wrong folder and can decide if they want to choose a different one, move the file content or ignore it.
> 
> Isn't it the case for the migration wizard, that the dialog "You selected another folder..." will be shown in any case as the the previous folder is the legacy folder? Did not check this yet...

No, there is a logic implemented checking whether the old legacy file path and the new selected SAF path point to the same physical location on device (if you're interested: this is done by creating a dummy file with a random name in the new folder using the newly selected SAF path, and then checking if this file is also in the folder when accessing it via old legacy path. After check the dummy file is deleted again)

**Comment by eddiemuc** [comment]
I created PR #10160 which will, if merged, make the "No further action" the default action for all folder selections (both triggered by wizard/migration and by manual folder selection using settings). In combination with already included folder information this will then look something like following screenshot (example is for Map Themes folder).

This seems to me the current "smallest" thing which the group agrees on. Depending on forther discussion we might or might not remove the "move/copy" selection completely for wizard-triggered migration.

![image](https://user-images.githubusercontent.com/6909759/111062750-2e89f800-84ab-11eb-88fa-022f8d9b43b8.png)

**Comment by Lineflyer** [comment]
I think its now as fail safe as it can be with having it defaulted to "Do nothing", but still allows advanced users to easily move their folder later on.
Additionally for the migration case the dialog will AFAICS only be shown if you choose a folder which is different to the preselected one. 

Lets close and see the beta feedback later on.
Feel free to reopen if you think its not sufficiently solved.

**Comment by eddiemuc** [comment]
> Additionally for the migration case the dialog will AFAICS only be shown if you choose a folder which is different to the preselected one.

This logic is also not unique to migration, it will be executed this way on every folder change
