### ISSUE TITLE
Archive lint results for each CI run

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10168]
While working on #8029 I found, that on the CI results I can see the lint warnings and their trends (fixed/new) but not the errors.

I think it could be helpful to archive the lint reports as artifacts for each build.

Those are generated but I guess there needs to be a post-build action configured to save them.
I tried to include a matching pattern in the PR build job configuration, but Jenkins shows a crash stack trace whenever I try to save it. Maybe I do not have the right user rights.

 > Task :main:lintBasicDebug
21:22:32  Wrote HTML report to file:///home/jenkins/slave/workspace/cgeo%20pull%20request/main/build/reports/lint-results-basicDebug.html
21:22:32  Wrote XML report to file:///home/jenkins/slave/workspace/cgeo%20pull%20request/main/build/reports/lint-results-basicDebug.xml
21:22:32  Lint found 95 warnings (73 errors filtered by baseline lint-baseline.xml)

The two above mentioned files should be archived as artifacts of the build.

**Comment by eddiemuc** [comment]
Since errors will as of now fail the CI build, you will never see a lint error on a green build an more

**Comment by Lineflyer** [comment]
Not even those, which are suppressed by the baseline?
And what if a build fails with a bunch of new errors and I would like to see them (the console output shows only the first 3 of them AFAICS).

**Comment by eddiemuc** [comment]
* Jenkins creates his own lint result report out if the lint reports, it is available via "Lint Result" link on the left side
* The baseline lint errors are not part of this report (only one entry telling you that there were suppressed errors), but those are documented by the lint-baseline.xml file itself inside git

**Comment by Lineflyer** [comment]
Maybe I am not understanding how those lint reports work, but:

I checked the "Lint Issues" on CI, but it seems only to contain those items, which are not "filtered" by the baseline. So if the build e.g. reports "10 errors/warnings were listed in the baseline file (lint-baseline.xml) but not found in the project; perhaps they have been fixed?", how can I find out which 10 errors are fixed in order to remove them from the baseline?

**Comment by eddiemuc** [comment]
Hi @Lineflyer,

* the Jenkins "Lint Issues" will always contain exactly the same lint items as the XML/HTML lint reports you found in the Jenkins console (in your example: file:///home/jenkins/slave/workspace/cgeo%20pull%20request/main/build/reports/lint-results-basicDebug.html and file:///home/jenkins/slave/workspace/cgeo%20pull%20request/main/build/reports/lint-results-basicDebug.xml). Actually I assume that the Jenkins report is created from the xml report.
* Lint filters out all issues in lint-baseline.xml when creating the reports, they won't be present in any of the above reports
* However, lint includes in its reports Informational items (at "Information" level, which Jenkins displays as "Niedrige Priorität")
   * An entry in the format "xx errors were filtered out because they are listed in the baseline file, lint-baseline.xml", this entry references the lint-baseline.xml file -> so you can see these errors there
   * If there are any errors in baseline file which were NOT found in current build, a second entry is generated in the format "xx errors/warnings were listed in the baseline file (lint-baseline.xml) but not found in the project"

**Comment by Lineflyer** [comment]
> If there are any errors in baseline file which were NOT found in current build, a second entry is generated in the format "xx errors/warnings were listed in the baseline file (lint-baseline.xml) but not found in the project"

Thats my point:
How to find out which xx errors/warning are no longer found?

**Comment by bekuno** [comment]
> How to find out which xx errors/warning are no longer found?

You have to recreate the baseline file.
Then you can compare it with the current one.
See our wiki: https://github.com/cgeo/cgeo/wiki/Coding-Conventions#lint and the Android Doku at https://developer.android.com/studio/write/lint#snapshot

* Run lint analysis e.g. using `gradlew lintBasicDebug`
* take created xml report, remove all findings on severity "Warning" and replace `main/lint-baseline.xml` with this file

**Comment by eddiemuc** [comment]
Exactly as @bekuno says. This is a bit of manual work, but it is doable from time to time.

Unfortunately there seems to be no easier way. In the lint info message above there is an additional hint as to which lint category the affected entries have (at the end of the text), but this is in most cases not enough to identify the entries uniquely.

**Comment by Lineflyer** [comment]
Now I got it. Thanks for explanation and your patience. :)
