### ISSUE TITLE
Direction line active while it was deactivate before and can no longer be deactivated

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10187]
From support mail for current beta 2021.03.16-RC1:

- No Brouter installed
- The user had direction line switched off in settings
- After upgrading to the beta version the direction line is shown
- Using map quick settings to deactivate it, is not possible. 
- Side fact: The sys info shows routing type "Walk" 

Something seems wrong in migration of the old setting to the new map quick setting.

I could reproduce at least the fact, that direction line cannot be deactivated anymore if Brouter is not installed.
The migration case needs to be debugged.

**Comment by Lineflyer** [comment]
@moving-bits Did you see this?

**Comment by moving-bits** [comment]
Yes, will try look into this. Fix would be targeted to `release`?

**Comment by Lineflyer** [comment]
Yes, to `release`.

Two issues here:
- If no Brouter is installed user cannot deactive the direction line.
- Migration of Direction line=Deactivated got lost during upgrade

**Comment by moving-bits** [comment]
This is a side-effect of the combination of two PR:

With #9913 we merged the "show direction line" and "routing mode" settings. Now the setting for direction line is derived from the routing mode setting since #9913: If routing mode is set to off, direction line is switched off, otherwise it's switched on. So the user here probably had set routing mode to something other than off (even although not having installed BRouter), which automatically switched on the direction line.

With #9823 we not only added some info regarding BRouter to the map quick settings menu, but also disabled this part of the popup when BRouter is not installed => which is why the user was not able to switch routing mode to off and disable direction line by that.

I'll prepare a PR which removes disabling the routing mode buttons in quick settings popup.

**Comment by Lineflyer** [comment]
> I'll prepare a PR which removes disabling the routing mode buttons in quick settings popup.

AFAICS we only need to remove disabling from off and straight. Because only walk/bike/drive are unavailable without Brouter.

**Comment by fm-sys** [comment]
Fixed with 187fa3a32edca42f554b292d05f11f4357972bd8
