### ISSUE TITLE
Picture title lost when editing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10219]
For 2021.03.16-RC1 from support mail:

- Compose log
- Use icon to add existing picture
- Return to logging view -> Picture thumbnail is shown and titled "Bild 1"
- Click on it to edit scaling
- Click OK to finish editing

Error message:
Picture title is mandatory

Expected:
The existing title ("Bild 1" in this case) should be prefilled on the edit screen

**Comment by Lineflyer** [comment]
Addon:
Just tried to verify but failed first.
After reading the support mail again, I realized it was about a OC cache.
Indeed when trying to log an OC cache the mentioned error toast is shown. When trying a GC cache the title field is also empty but I can select "OK" and on logging view it still has "Bild 1" as title.

Behavior should IMHO be harmonized by prefilling the title according to the title shown in the logging view.

**Comment by eddiemuc** [comment]
The default image title is currently implemented a bit differently than you might think. It is not initally assigned and remains unchanged, but it is dynamically assigned based on image position in the logs image list.

For example, try to create a log and add two images to it using quick select. They will be named (in German) "Bild 1" and "Bild 2". If you now swap image order (use slider on right), then images are renamed according to their new index position. This way, lazy people (who don't want to give titles to their images) will always get correctly indexed image titles even if they change order.

To make this consistent, OC mandatory title check can simply be removed since it is no longer necessary (if user doesn't give a title then the default one will be used). Would that be ok as well?

**Comment by Lineflyer** [comment]
> To make this consistent, OC mandatory title check can simply be removed since it is no longer necessary (if user doesn't give a title then the default one will be used). Would that be ok as well?

Sounds like the best solution, if also an explicitly emptied title will always again be prefilled with "Bild x" before sending.

**Comment by eddiemuc** [comment]
If above solution is acceptable, then PR #10223 is fixing this issue
