### ISSUE TITLE
New Map Quick Filter: Exclude Caches with Offline Found Logs

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#10287]
**Is your feature request related to a problem?**

Caches with offline found logs are de facto already found ones. Only difference to the ones counted as "real" found is, that their (offline stored) logs are not yet uploaded to the server. But this difference does not matter for cacher's real life: An already found cache will not be visited again (in most of the cases ;) ), thus it should be possible to eliminated it from map and search lists, to be able to declutter them more easily (which sometimes is a real issue esp. on longer tours).

**Describe the solution you'd like**
- A setting ``Exclude Caches with Offline Found Logs`` (similar to ``Cache Details`` => ``Exclude Own and Found``).
- A tick box ``Caches with Offline found logs`` in the map's ``Quick settings`` popup.
- These should hide caches with offline found logs in the same way as "real" finds from
  - map
  - search results
  - nearby list
  - ... forgotten s/th?

**Comment by eddiemuc** [comment]
For Cache Lists, this is possible via "Offline Log Filter" using option "is not present"

![image](https://user-images.githubusercontent.com/6909759/118150379-c4da8b80-b412-11eb-96f7-317b650b8f1f.png)

Not possible specifically for "found" logs yet.

And also not possible yet to use it in map viewer

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo there is no "quick setting" for this in the map, but it is now doable via new filtering in search results, offline lists, and now also in the map and in "nearby" list.

The quick map settings I want to remove from settings anyway (so they are only present and used in the map settings)

Would you consider this issue done? Or do you want also a new explicit new quick setting in the map for this?

**Comment by MagpieFourtyTwo** [comment]
To be honest: As the filter provides a possibility, I could live without it.
Nevertheless, would in fact be great to have a quick setting for hiding/showing caches with offline logs,
cause a filter to hide these "kind of found caches" will otherwise be a predefined and really often used one over here ... ;)

**Comment by eddiemuc** [comment]
I changed title of this issue to reflect that a new "map quick filter" is wanted. @MagpieFourtyTwo note that this is then something apart from the overall new filtering system and only usable in map.

This could be implemented in combination with other things wrt to map quick settings.
* Split "Hide own/found" into "hide own" and "hide found"
* Add additionally a "hide cache with offline log"
* On another issue there was a proposal to display these options in 2-column view instead of 1 column
* On yet another issue it was requested to use "switches" instead of "checkboxes" for this kind of thing
* To get that all together I would further divide "cache hide settings" from "waypoint hide settings"

In result this could look e.g. as follows (each selection with a switch)

| Caches to show : | |
| ----------------|------------------|
| Found | own |
| Disabled | archived|
| caches with offline logs | Circles |
| Waypoints to show; | |
| Original | parking | 
| visible | |
| Use compact icons | |
... (unchanged)
