### ISSUE TITLE
c:geo not offered to open GPX with MIME type: application/gpx

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10309]
**Describe the bug:**
Since some months I noticed, that c:geo is no longer offered if I try to open a GPX file I received by mail in my mail client.
Other GPX aware apps are offered though

**To Reproduce:**
1. Receive GPX exported from c:geo from another user
2. Open mail
3. Click the attached GPX

**Actual behavior/state after performing these steps:**
Offers Locus and another routing app 

**Expected behavior/state after performing these steps:**
c:geo should also be offered

**Version of c:geo used:**
2021.04.02-NB

**Is the problem reproducible:**
Yes

**Screenshots:**
This is the intent triggered by my mail client, might be helpful to fix the problem I guess:
![Screenshot_20210402-125016_Intent Intercept](https://user-images.githubusercontent.com/949669/113409924-9056c700-93b2-11eb-99f0-58584e799133.jpg)
![Screenshot_20210402-125025_Intent Intercept](https://user-images.githubusercontent.com/949669/113409930-96e53e80-93b2-11eb-8bbe-cef80a2d0a15.jpg)

**System information:**
Samsung S20, Android 11

**Additional context:**
When I try to open a GPX using my file explorer, the intent has MIME type `application/octet-stream` and c:geo is offered as target app

**Comment by moving-bits** [comment]
Hm, seems to depend on the mail client. K9 does not offer c:geo for the attached GPX file, whereas gmail does offer c:geo.
Can't say, though, which MIME type they apply. 

@Lineflyer 
Where did you get the intent catcher from?

**Comment by Lineflyer** [comment]
> Where did you get the intent catcher from?

Nice, isn't it.
After testing several, this seems to be the most convenient (you can also switch if off, else it catches everything).

https://play.google.com/store/apps/details?id=uk.co.ashtonbrsc.android.intentintercept
https://github.com/intrications/intent-intercept

**Comment by bekuno** [comment]
Currently not availlable on PlayStore

**Comment by bekuno** [comment]
A fork with changes is at https://github.com/k3b/intent-intercept/releases with F-Droid download

**Comment by Lineflyer** [comment]
> No more available on PlayStore and F-Droid

Interesting. I could still install it (maybe as I am existing user).

**Comment by moving-bits** [comment]
Ok, I played a bit with it:

My mail program sent the attached file with MIME type "text/plain", which GMail in the emulator changes to "application/octet-stream", whereas K9 stays with the supplied "text/plain". c:geo does not catch "text/plain", whereas it does catch "application/octet-stream".

So I manipulated the sent email to use "application/gpx" as MIME type for the attachment. Again, c:geo was offered when opened from GMail, as it (again) changed the MIME type to "application/octet-stream"! In contrast to this K9 uses the correct (= supplied) MIME Type, which does not trigger c:geo.

From looking in the source I would say that c:geo never reacted to "application/gpx", at least it's nowhere in the code. When it has opened a file send with that application type, it was probably due to some GMail (or other email program's) quirks.

OTOH it's easy to add "application/gpx", so I'll prepare a PR for this. Locally it correctly offers c:geo for a "application/gpx" marked file opened with K9.

**Comment by moving-bits** [comment]
> A fork with changes is at https://github.com/k3b/intent-intercept/releases with F-Droid download
> https://f-droid.org/en/packages/de.k3b.android.intentintercept/

Thanks for the links. It took me a bit to get FDroid client running in the emulator, but now both FDroid and Intent Interceptor are running fine!
