### ISSUE TITLE
Challenge checker link not working for some caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10303]
Users following our link "Search challenge checker" for GC2V4CP the user is getting an error message on project-gc.com:
```
This checker script is disabled
If you found this link on a acache page you could inform the cache owner of the issues if it persists for more than 24 hours
```

The auto generated link from c:geo is (like for all challenges): https://project-gc.com/Challenges/GC2V4CP
On other challenges its working, but not for this specific cache (and some other as reported by the user)

@magma1447 An issue on PGC, or do we need to change our link constructor as something has changed?

**Comment by magma1447** [comment]
@Lineflyer It's working as intended. The checker scripts are user contributed, the script is disabled and therefore can't be executed/run. There is nothing wrong with the link itself. It shows what it's supposed to.

**Comment by Lineflyer** [comment]
@magma1447 I forgot to mention: There is in fact a checker for that cache and it does not look disabled:

https://project-gc.com/Challenges/GC2V4CP/18322

**Comment by magma1447** [comment]
@Lineflyer Now I see. We'll be releasing a fix for that next week, it's fixed in the development environment now. It's recommended for cache owners to refer to the tag-id and not only the gc-code. I understand that it's not feasible for c:geo though.

The search for gc-code was a bit stupid. It took the first matching checker, regardless of active or not. The new implementation will return a list, unless there is only one active.

**Comment by Lineflyer** [comment]
Perfect, thanks. I could have mentioned it at the first place already to help you understand my point.
I will close here then and inform the user, who sent this ticket.
