### ISSUE TITLE
Max. routing distance wrong for imperial units

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10341]
- 2021.03.28-RC
- Use imperial units (Settings - Appearance)
- Open Settings - Map

For map content - Calculate route (maximum distance) the range is shown from 0.00mi up to 0.62mi.
This looks like a wrong conversion.

**Comment by Lineflyer** [comment]
A similar bug applies to the setting for the proximity notifications:
Both can be set up to 999meters, but for imperial units it show 620,75mi, which is wrong as well.

**Comment by Lineflyer** [comment]
@moving-bits Did you see this?

Probably a fast fix as I suspect a wrong coversion factor only.
Now more reports by users.

**Comment by murggel** [comment]
@Lineflyer , @moving-bits I can have a look at this

**Comment by moving-bits** [comment]
@murggel 

> I can have a look at this

That would be kind. Have a look at `settings/SeekbarPreference` and `settings/ProximityPreference`, the first of which also explains the differences between `progress`, `value` and `shownValue`.

**Comment by murggel** [comment]
Found the conversion error -> PR will follow..

**Comment by murggel** [comment]
But I found some more issues there:
* the first progress steps does not change the distance, it stay at 0 (same for metric units)
![grafik](https://user-images.githubusercontent.com/70113341/116314577-92445800-a7af-11eb-870e-d718cb888ba4.png)
  
* only integer values can be input in the dialog box -> but because of the conversion float-values are shown, so there will be a mismatch between input and shown value 
![grafik](https://user-images.githubusercontent.com/70113341/116314862-f404c200-a7af-11eb-9ca6-079fa31699cd.png)

* mismatch for metric input and shown values, because there is a exponentiell translation from progress to value
![grafik](https://user-images.githubusercontent.com/70113341/116315123-5d84d080-a7b0-11eb-9d35-ae274315a048.png)

* missing unit in input-dialog (I would like to add "ft" / "m" to the min and max-value)

I guess, they are only minor ones, and except the last one, probably not so easy to fix.

**Comment by murggel** [comment]
@moving-bits Did you saw my comments?
What do you think?

**Comment by moving-bits** [comment]
> @moving-bits Have you seen my comments?
> What do you think?

Thanks for the reminder. I've created a new issue for it for a follow-up discussion on those points.
