### ISSUE TITLE
distance from home

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#1039]
Sometimes when I'm on the road, at work or where else, I get a mail notification and load the cache. It then shows me the current distance in the summary screen, but I'm often more interested in the distance from home at that moment to estimate when I will do the cache, into which list to sort it and several other things.

I could solve this by adding a preference for coordinates of "home" and show the distance to home, when clicking on the distance label (like you can click the coordinates and they will iterate several formats).

Does anyone else see any use in a feature like that? Could we add more useful features, assuming we know the home coordinates of the user? Is there a better alternative implementation? Lots of questions... :)

**Comment by fm-sys** [comment]
> It then shows me the current distance in the summary screen, but I'm often more interested in the distance from home at that moment to estimate when I will do the cache

> Could we add more useful features, assuming we know the home coordinates of the user? Is there a better alternative implementation?

As no one seems to be very interested in this feature request since 2012 I will close the issue as "stale". 

A workaround for all who are missing that feature:
If you disable GPS c:geo will already today use the home coordinates for calculating the distance. Basically exactly what this request is about...
