### ISSUE TITLE
GPX files containing multiple tracks are handled incorrectly

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#10432]
## Bug description 

If you load a GPX that contains multiple tracks, c:geo handles them as if they were a single track and glues them together with a connecting line. See screenshot.

![2021-04-21 18 16 02-1](https://user-images.githubusercontent.com/54892606/115587573-1b4e2180-a2ce-11eb-84f4-9e971a0087eb.jpg)

### Expected result 

c:geo should simply draw multiple separate tracks.

**Comment by moving-bits** [comment]
Not sure if that can be implemented in a reasonable way, but let's try...

Can you provide me with one or two test files?

**Comment by dcjkfgdjhd** [comment]
Here is a sample file exported from Garmin Basecamp containing 1 cache and two separate, unconnected tracks. They are drawn by c:geo as connected.
[TEST3.zip](https://github.com/cgeo/cgeo/files/6488927/TEST3.zip)

**Comment by dcjkfgdjhd** [comment]
A less elegant solution would be if c:geo would only draw ONE of the tracks, but allow the user to choose which one. Maybe that would be easier to implement, because it does not require changing the code to draw multiple tracks at the same time.

But of course drawing them all separately, visible at the same time, would be the nicest solution.

**Comment by moving-bits** [comment]
Thanks for providing the test file. I'll try to look into this issue.

**Comment by dcjkfgdjhd** [comment]
Awesome, thank you!

**Comment by moving-bits** [comment]
@dcjkfgdjhd 
It took me quite some time to return to my unfinished work from May, but now we do have a PR... Do you have a chance to test the build in #12087 with some of your files, both multi-track and single-track?

**Comment by dcjkfgdjhd** [comment]
Awesome, thanks a lot!

I am happy to test it with different files. Is there a way to get a ready-to-install APK? I don't currently have an enviroment for building android apps set-up on my computer.

**Comment by bekuno** [comment]
You can take the apk from the PR build:
https://ci.cgeo.org/job/cgeo%20CI%20-%20PR%20build/111/artifact/main/build/outputs/apk/basic/debug/cgeo-debug.apk

**Comment by dcjkfgdjhd** [comment]
> 
> 
> You can take the apk from the PR build: https://ci.cgeo.org/job/cgeo%20CI%20-%20PR%20build/111/artifact/main/build/outputs/apk/basic/debug/cgeo-debug.apk

"There was a problem parsing the package."

**Comment by moving-bits** [comment]
Actually, using that download _should_ work. Hm, strange.
You need to (temporarily) allow installs from different sources, though. For me, I download the file using a browser, then switch to my local file manager app and open the apk file. My app then asks me whether I want to install that apk, and Android asks me, if that's ok for me ("allow install from ...").

What may interfere is if you are currently using a regular build - the debug build may have different signing keys, effectively preventing a "cross-update".

If it's ok for you, you can go the following way:
- create a backup (database + settings) from within c:geo
- uninstall c:geo
- install apk
- skip wizard after having granted basic file permissions and go to settings => restore
- and install the backup (c:geo will ask for some specific file permissions like "base" folder etc.)

This way should work, but you will loose all temporarily stored cache images due to the uninstall.

It this way is no option for you (which would be totally ok), and if you don't have some testing device, then you'll probably have to wait for a beta version including this PR. May take a while, though, as we are currently in the process of finishing our current release (starting with a last beta round today), which does not include this PR yet.

**Comment by Lineflyer** [comment]
Exactly, the problem in parsing the package is causes by another key being used in contrast to the production version. Those can't exist in parallel.

**Comment by dcjkfgdjhd** [comment]
Hi, I tried uninstalling cgeo and rebooting, but the APK still cannot be parsed.

**Comment by moving-bits** [comment]
The build seems to be broken, "green" status a false-positive. See the console log for https://ci.cgeo.org/job/cgeo%20CI%20-%20PR%20build/111/console - there is already a message "java.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/cgeo-debug.apk: Failed to parse /data/local/tmp/cgeo-debug.apk" (for whatever reason). Although the resulting APK was a valid ZIP file, something was still missing.

I've started a new build, let's see if that works.

**Comment by Lineflyer** [comment]
@mucek4 is working on the CI executors right now. At this moment we have quite some fails.

**Comment by moving-bits** [comment]
@dcjkfgdjhd 
The new build does work, have just installed it on my test device. Can you download the new file from https://ci.cgeo.org/job/cgeo%20CI%20-%20PR%20build/138/artifact/main/build/outputs/apk/basic/debug/cgeo-debug.apk and give it a try?

**Comment by bekuno** [comment]
> The build seems to be broken, "green" status a false-positive.

Thanks for the check and rebuild. I was not aware of the failure.

**Comment by dcjkfgdjhd** [comment]
> 
> 
> @dcjkfgdjhd The new build does work, have just installed it on my test device. Can you download the new file from https://ci.cgeo.org/job/cgeo%20CI%20-%20PR%20build/138/artifact/main/build/outputs/apk/basic/debug/cgeo-debug.apk and give it a try?

So I tested this with different GPX scenarios (one or multiple tracks in the file, with or without caches in the file, with or without other non-cache waypoints) and I could not find any problem. The tracks were always correctly and separately drawn. 👍

**Comment by moving-bits** [comment]
Glad to hear that. Thanks @dcjkfgdjhd for that intensive testing! Will merge then...
