### ISSUE TITLE
Owner not parsed

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10454]
Followup or reappearance of #10421 with 201.04.24:

- Open (an unknown/unsaved) caches, e.g. GC352Y3 (tested as Basic member)
- Click on owner name
- Select caches hidden or caches found

Result:
"No username given"

Log:

```
2021-04-24 12:05:14.349 28626-28659/cgeo.geocaching D/cgeo: [OkHttp] GET https://www.geocaching.com/seek/cache_details.aspx?decrypt=y&wp=GC352Y3&log=y&numlogs=0
2021-04-24 12:05:15.002 28626-28659/cgeo.geocaching D/cgeo: [OkHttp] 200 (652 ms) GET https://www.geocaching.com/seek/cache_details.aspx?decrypt=y&wp=GC352Y3&log=y&numlogs=0 (http/1.1) (=> https://www.geocaching.com/geocache/GC352Y3_die-alte-schule?decrypt=y&log=y&numlogs=0)
2021-04-24 12:05:15.115 28626-28751/cgeo.geocaching W/cgeo: [refresh--1] owner not parsed correctly for GC352Y3
[...]
```

**Comment by MagpieFourtyTwo** [comment]
> - Select caches hidden or caches found

... is not even necessary - it's sufficient to check the window title, which just says ``About`` i. e. even the title is already missing the Owner's name.

Most regretfully I was not able to nail a scenario yet. Sometimes it works, sometimes it doesn't, even with the same Owner (name) and with caches, which have been handled in the absolute same way: This morning a bunch of caches have been published, which I opened one after the other via the notification mail link. And while the first one, https://coord.info/GC96WYF, had the owner problem, in the next one, https://coord.info/GC96WWV, the click on ``Owner`` => ``Caches hidden`` worked perfectly fine.

Afterwards I performed some more actions with the first one, but whatever I did, the Owner popup title remained empty and ``Caches hidden`` constantly failed. And it still fails, whatever I do (saving, deleting, opening from lists, open directly via GC code or via map ...), while the other still works like a charm.

I have another one, where the ``Owner`` => ``Caches hidden`` fails, just look at https://coord.info/GC99HF8 - but over there it may be just because of the ampersand ...?

**Comment by MagpieFourtyTwo** [comment]
BTW: [GC352Y3](https://coord.info/GC352Y3) gives me an empty Owner, too.

**Comment by Lineflyer** [comment]
Did you test with newest nightly?

**Comment by Lineflyer** [comment]
IMHO this is fixed and I tested very intense this time :)

**Comment by MagpieFourtyTwo** [comment]
This morning, yes, Tonight, i. e. an hour ago, seemingly not.  ;)
Just got the update notification, did so, and now it is working.
At least after updating the offline saved listing.
And then even you appear again.  ;)

Perfectly fine!  Thx!

**Comment by MagpieFourtyTwo** [comment]
@moving-bits: Beer++  ;)

**Comment by little-fish** [comment]
Is it actually parsing owner's id? It looks like it parses owner's name instead.

**Comment by Lineflyer** [comment]
> Is it actually parsing owner's id? It looks like it parses owner's name instead.

AFAICS its parsing the real owner name, not the displayed name. Not sure about IDs though, why are you asking. If there is a specific problem case, feel free to open a new issue for that.
