### ISSUE TITLE
More compact geocode for Adventure Labs

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10474]
## What function are you missing

The currently used geocode strings is rather long. While there is no classical geocode we should still think about a less space-consuming alternative which might ideally be helpful to also look up the cache somehow.

## Suggested solution

I have seen the "Firebase..." code coming from the API (e.g.: KSQT), which is also used in conjunction to construct a unique web URL (e.g. https://adventurelab.page.link/KSQT ).
Maybe we could use a combination of a fixed prefix (LC) together with this code (e.g. LCKSQT)?

## Alternatives/workarounds

@baiti 
Regarding the public API:
Is there a possibility to retireve information about a specific lab cache by knowing some ID of it?
I mean not a location based search, but like a geocode search for a classical geocode.

Whatever we use as geocode for lab caches at the end: It should allow this search (if this is technically possible).
Meaning:
User 1 says: There is a lab cache with code LCKSQT
User 2: I will search for that geocode in c:geo, then I can see where it is located.

## Additional context

Not sure however about the codewise requirements for a geocode, that has to be judged by someone else

**Comment by baiti** [comment]
the public API has no addresssing concept based on "KSQT" (referencing your example). "KSQT" is only useful for launching "the app" via the Firebase Link". it is of no use for any other purpose. The only true identification of an Adventure Lab Cache is its "Id", a character string which resembles a UUID and because it does this, it happens to look "ugly" and will almost certainly never be used in a communication as the one you outline between "User 1 ... User 2" above.

The current design and implementation of cgeo exclusively uses a "geocode" as arguments on function calls / method invokations. That "geocode" is not a reference to a full blown "cache" object. If a method receives a geocode, it has no way to reference any other properties of the cache object in question. So, just addint an "Id" property to the Geocache object, is of no use unless we make systemwide changes to some of the core interfaces. I will extract examples which show what I have described here. There was a discussion with @fm-sys and @baiti somewhere ... I will find a reference to it and put a link in here

**Comment by baiti** [comment]
Pls read this first: https://github.com/cgeo/cgeo/issues/10387

**Comment by Lineflyer** [comment]
Oh, there is already a issue for that. Sorry. Lets continue over there then.
