### ISSUE TITLE
Follow-up on imperial conversion for seekbars

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10508]
_Originally posted by @murggel in https://github.com/cgeo/cgeo/issues/10341#issuecomment-827945109_

But I found some more issues there:
* the first progress steps does not change the distance, it stay at 0 (same for metric units), probably due to the exponentiell translation from progress to value
![grafik](https://user-images.githubusercontent.com/70113341/116314577-92445800-a7af-11eb-870e-d718cb888ba4.png)
  
* only integer values can be input in the dialog box -> due to the conversion float-values are shown, so there will be a mismatch between input and shown value 
![grafik](https://user-images.githubusercontent.com/70113341/116314862-f404c200-a7af-11eb-9ca6-079fa31699cd.png)
(input of lower box is converted to float value, upper box appear, if you click on the shown value at the end of the seekbar)

* mismatch for metric input and shown values, due to the exponentiell translation from progress to value
![grafik](https://user-images.githubusercontent.com/70113341/116315123-5d84d080-a7b0-11eb-9d35-ae274315a048.png)

* missing unit in input-dialog (I would like to add "ft" / "m" to the min and max-value), but this will produce a longer text, which then causes a linebreak in the title...

I guess, they are only minor ones, and except the last one, probably not so easy to fix.

**Comment by moving-bits** [comment]
I guess the first three are probably due to exponential conversion, which leads to that not every value can be represented.
Allowing a decimal point in 2) should be possible by setting a different input method, but probably would not help wrt to those issues, so I would rather avoid this.

As for the last one: You could create your own layout for the dialog box instead of using a default `EditText` as view. That layout would have to consist of an `EditText` input line and an adjacent text field, in which you could put the unit (so you would have it in the input line instead of the title).

**Comment by moving-bits** [comment]
One idea for the conversion issues - just thinking, not sure if it's technically possible:

Currently the `SeekbarPreference` internally calculates in meters in all places, and only adjust the displayed values.

What we could do instead is to change this to always use the selected unit, and do the conversion on load/store only. So for example a user would see a value like "1.5 mi", and on storing this would be converted to 2414m. On opening the dialog and retrieving the stored value, it would convert the stored 2414m to 1499,99 mi, rounded to 1.5 mi.

Just keep in mind that the stored value should be in meters always, and it's always an integer value, no float.

**Comment by murggel** [comment]
> One idea for the conversion issues - just thinking, not sure if it's technically possible:
> 
> Currently the `SeekbarPreference` internally calculates in meters in all places, and only adjust the displayed values.
> 
> What we could do instead is to change this to always use the selected unit, and do the conversion on load/store only. So for example a user would see a value like "1.5 mi", and on storing this would be converted to 2414m. On opening the dialog and retrieving the stored value, it would convert the stored 2414m to 1499,99 mi, rounded to 1.5 mi.
> 
> Just keep in mind that the stored value should be in meters always, and it's always an integer value, no float.

@moving-bits I am not sure, if I got you right, but I think the problem is the mismatch between integer an float: 
The internal value is integer (progress ticks, not meter) and for the input value also only integer is allowed, but the shown value for imperial unit can / will be float due to the conversion of the max metric (integer) value. Also the metric value could probably be float due to the exponential conversion. Maybe also rounding the imperial value to an integer and not float can solve that problem.
I will give it a try...

**Comment by murggel** [comment]
Hm, seems that on using the value will be interpreted as meter. Have to check it in detail ...

**Comment by moving-bits** [comment]
IIRC those values are stored as int internally. We could change this to float to avoid rounding differences. Calling code would need do be able to process float values instead of int, which should not be a problem, as we are working with distances, which are floats anyway.

But migration of the existing settings will need some work then, as you cannot simply change the type of an existing settings - this would break the program if you try to read some existing setting with int values (e. g. on importing a backup of old settings). You will have to introduce a new preference key for each setting you change the type of.

Normally I do the following in such cases:
- rename the pref variable name (not its value) by prefixing it with "old_" (using Android Studio's refactor => rename function) to make it more visible in the code, that this is an unused pref variable only staying for migration purposes. (see `preference_keys.xml`)
- introduce a new pref variable under the old name but with a new (and similar) value (e. g. `pref_proximityDistanceFarFloat` instead of `pref_proximityDistanceFar`)
- adapt the reading method in Settings to return float instead of int, make it be based on the new preference key, but read the old preference value as default for the new

something like this (haven't tested):

Settings.java:
```
public static float getProximityNotificationThreshold(final boolean farDistance) {
    if (farDistance) {
        return getFloat(R.string.pref_proximityDistanceFar, (float) getInt(R.string.old_pref_proximityDistanceFar, getKeyInt(R.integer.proximitynotification_far_default)));
    } else {
        return getFloat(R.string.pref_proximityDistanceNear, (float) getInt(R.string.old_pref_proximityDistanceNear, getKeyInt(R.integer.proximitynotification_near_default)));
    }
}
```

preference_keys.xml:
```
<string translatable="false" name="old_pref_proximityDistanceFar">pref_proximityDistanceFar</string>
<string translatable="false" name="pref_proximityDistanceFar">proximityDistanceFar</string>
```
(special case here: the value shouldn't have had "pref_" as prefix (that's reserved for the variable name), so for renaming the value we can simply remove the wrong prefix in this case)

**Comment by murggel** [comment]
Ok, I will have a look at storing a float value internally. 
Then probably we can have only integer value on UI-side for imperial as well, as the float value only occurs because of the conversion of an integer metric value for the calling code...


Regarding the only integer input - I was kind of wrong, that only happens, if I switcht the imperial settings and go then directly to the map-settings for the proximity values without restarting the settings activity. 
On restarting the activity all works fine and I can input decimal values.

I will fix that ...

**Comment by murggel** [comment]
> IIRC those values are stored as int internally. We could change this to float to avoid rounding differences. Calling code would need do be able to process float values instead of int, which should not be a problem, as we are working with distances, which are floats anyway.
> 

Maybe this does not work, because the value is based in `seekbarpreference` which could mean we have to change it for all pref-settings.

I will check that this weekend. 

But I would then first go with the fix of the decimals and add the unit and keep the conversion stuff as it is, as long as no user complains...

**Comment by eddiemuc** [comment]
My 50 cents:

This issue seems to be a corner case, I would try to solve it as simple as possible. My proposal would be the following:

* Leave property as int and always store the distance in meters (regardless of unit selected by users)
* If user uses non-metric values, then current value is converted and rounded for display on seekbar and selection of a new value to nearest integer. 
* If user selects a new value, it is converted back to meter, rounded to nearest integer, this value is stored.

There will be rounding error Edge cases, imho those are acceptable. 

If you want to have a very clean solution for this issue despite my 50 cents, my proposal is to store both the value (as integer) and the unit (meter or foot) in the preferences. The getter in Settings for usage in code should then convert the value on-the-fly to meters (rounded to nearest int)

**Comment by murggel** [comment]
> My 50 cents:
> 
> This issue seems to be a corner case, I would try to solve it as simple as possible. 

As I stated before, I will keep the conversion untouched as long as no user complains.
I will add the unit label in the input box and fix the switching unit system.

**Comment by murggel** [comment]
PR #10534
![grafik](https://user-images.githubusercontent.com/70113341/116805478-2d7a5c00-ab27-11eb-8569-58df8fdc8ec8.png)

**Comment by murggel** [comment]
@moving-bits I would suggest to close here. We can reopen, if the exponential translation from progress to value should be improved.

**Comment by moving-bits** [comment]
> @moving-bits I would suggest to close here. We can reopen, if the exponential translation from progress to value should be improved.

Sure. And thanks for your work on it!
