### ISSUE TITLE
Feature request: add Finnish terrain maps to the download offline maps menu

### ISSUE THREAD

**Issue by Vike91** [cgeo/cgeo#10511]
Hello! I would like to get Maastokartat (terrain maps in Finnish) to the list of maps that are offered in the download offline maps menu.

The very accurate and detailed maps are located at https://kartat.hylly.org/ (only in Finnish), and can be used in c:geo.

The maps can be downloaded via the "Android yhteensopiva versio" (Android compatible version) section and then choosing mtk_suomi.map file. Additionally, it needs the theme files, which are conveniently listed in the same section as "peruskartta.zip" (base map) OR "tiekartta.zip" (road emphasized map). The theme files work very well unzipped.

It does feel like this is not hard to implement in the app, but would hugely help the Finnish geocaching community. 

I semi-actively translate the c:geo app and the manual in Finnish.
The automatic map download feature has been requested and asked from me numerous times, but now, as the offline map download is available directly in-app, I see this is the right time to suggest this.

The only downside is the size of the maps (around 4 GB).

The maps work perfectly in c:geo. (see screenshot)

You might also want see the message in the similar issue https://github.com/cgeo/cgeo/issues/6072#issuecomment-320471252.

![Screenshot_20210501-001804_cgeo](https://user-images.githubusercontent.com/69262705/116755379-029ee380-aa13-11eb-9468-23fb3c7dd707.jpg)

**Comment by moving-bits** [comment]
This looks feasible with the instruments we have.

@pailakka As you seem to be the person providing those maps and themes: Would it be ok for you if we include this into c:geo for a direct download? (We would provide a backlink to https://kartat.hylly.org/ from within c:geo's downloader.) 
And am I guessing right, that the date of the last change of the map and/or theme is provided via the folder name in the download link?

**Comment by pailakka** [comment]
Sure thing! You are correct, date in the folder name is the build date of that map ie ~ latest change. I could also provide symlinked/redirected download path like `/latest/mtk_suomi.map` so you don't need to poll main page for download url. "tiekartta.zip" is not currently well maintained so at this point I would suggest using only "peruskartta.zip".

**Comment by moving-bits** [comment]
Thanks @pailakka for your reply and for granting access.

Providing the date as part of the path is just fine, as by this I can check whether there is actually an update available. So no "latest" link needed from our side.

How shall I call that map? (Currently we have Mapsforge, OpenAndromaps and Freizeitkarte)

**Comment by moving-bits** [comment]
@pailakka 
I've just seen that you have special links for Locus and Orux Maps. Would you like to have something similar for c:geo?

Looking at your current HTML source, the link for it would look like this: `<a class="dl" href="mf-v4-map://kartat-dl.hylly.org/2021-04-25/mtk_suomi.map">mtk_suomi.map</a>` (so simply a `mf-v4-map://` instead of `https://`). 

If so I would add your host for our scheme receiver in c:geo.

**Comment by pailakka** [comment]
I can add that, should happen on next (manual) build

**Comment by moving-bits** [comment]
@pailakka 

> I can add that, should happen on next (manual) build

Ah, thanks, but please wait for now - we need to get this PR in the official release first. I just wanted to check whether you would be interested in adding a direct link for c:geo before actually implementing it on the c:geo side.

I'll update this issue here as soon as we have put that into the main release.

**Comment by pailakka** [comment]
Yeah sure, automatic map build is broken atm for some reason and there is no hurry for new build. I'll run it manually once new cgeo main release is made 👍. I would have forgotten otherwise 😅

**Comment by moving-bits** [comment]
> Yeah sure, automatic map build is broken atm for some reason 

Hm, just to make sure: I was talking about those links on your website - not a link from within the map file (so no need for a new map build, AFAICS):

![image](https://user-images.githubusercontent.com/3754370/116824867-be375300-ab8c-11eb-82d8-ffa203946590.png)

Anyway, I will reach out to you via GitHub as soon as we have that feature in our release.

**Comment by moving-bits** [comment]
I'll reopen here as a reminder to myself to send @pailakka a note as soon as this feature got deployed in the next release (not beta/nightly), so that the website can be updated then.

**Comment by Vike91** [comment]
Has this been implemented properly in the latest version? When I try to launch the download, it starts, but does not progress at all.

**Comment by moving-bits** [comment]
It is integrated in today's release and had been working during my tests a few weeks ago.

But it may take quite some time for download, as the maps are rather large. As the downloading happens in the background, you won't see any further notification within c:geo while the download is running. But you should see a system notification, something like "Downloading xxx.map".

What is being displayed if you go to Settings => System => View downloads?

**Comment by Vike91** [comment]
Can now confirm the download to be working when I moved to the high speed 4G network. Download completed successfully, map themes downloaded and the map is working perfectly. Thank you!

**Comment by moving-bits** [comment]
That's good news, thanks for the feedback.

If you like you may now adapt your website to provide direct download links, like you have for Locus and Oruxmaps.

For the map it would look like this:
`<a href="mf-v4-map://kartat-dl.hylly.org/2021-04-25/peruskartta.zip">title</a>`

And for the theme it would look like this:
`<a href="mf-theme://kartat-dl.hylly.org/2021-04-25/tiekartta.zip">title</a>`

(So it's `mf-v4-map://` and `mf-theme://` resp. instead of `https://`)

So if someone browsing your website could tap on the link, and if c:geo is installed on the same machine, c:geo would be triggered by that and starts downloading and installing the file.

**Comment by pailakka** [comment]
Great news! I tested map download and it seems to work. I triggered new map build and it should add these c:geo specific links to site when finished.

**Comment by moving-bits** [comment]
Everything's done here, including the special links on the website, so let's close here

**Comment by Vike91** [comment]
Problem: downloaded huge map file (~4GB) Not deleted from the default downloader folder after copying it from the download folder to the cgeo folder, thus eating 4 GB of space if userbis not aware to delete the downloaded file.

**Comment by Vike91** [comment]
Just a heads up, the internal downloader is returning a 404 error on the Hylly map file.
