### ISSUE TITLE
Make website tests more stable (and allow a break for the mailbox)

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10554]
The website tests are failing rather often (30%). Mostly `"Missing unit test report from category tests"`. Is there something we can do?

I see at least four possibilities:
- just run the test twice if the first run failed
- find the course of the missing unit test report
- don't send an email if the cause of the failing build was "missing unit test report"
- disable the email alerts totally

I would really like to see this issue fixed, as these "false positives" email alerts via the cgeo development mailing list are kind of annoying. To be honest: Is there anyone who reads these daily "build failed" emails? It would be great if we could be sure that something is really wrong with cgeo when we receive such emails...

![grafik](https://user-images.githubusercontent.com/64581222/117461429-d4a72b00-af4d-11eb-9777-1809edd08839.png)
![grafik](https://user-images.githubusercontent.com/64581222/117461519-f1dbf980-af4d-11eb-874c-459cf557c915.png)

**Comment by Lineflyer** [comment]
Not all of the fails are false positives (e.g. opencaching.us was down several days).
Still you are right, that there should not be false positives. I think the missing test report is due to the problem, that the tests did not run as the emulator was not working or something could not be installed.

Sadly my knowledge of Jenkins and those tests is really limited, so I am afraid I cannot help.

**Comment by fm-sys** [comment]
Currently it's quite calm, so let's close this one... 

![Screenshot_20210807_093001_org mozilla firefox](https://user-images.githubusercontent.com/64581222/128592529-cbedc5b3-9633-4a73-ad1b-c22b1ab1d96d.png)
