### ISSUE TITLE
Load more search results not available if ALC active and cache type filtered

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10567]
## Bug description 

Normally users can tap "Load more results" at the end of a search result list. This basically also works if the ALC connector is active. But there seems some bug under the hood which reveals if you additionally set a cache type filter

### Steps to reproduce the problem

- Have gc.com and ALC connectors active
- Perform nearby search
- A certain amount of GC and ALC caches are returned
- You can tap on "Load more" to get more results - OK so far
- Go to main screen and set global cache type filter to "Traditional cache"
- Perform nearby search again

### Actual result after these steps 

 20 traditional caches returned but load more is missing (Shows "No more caches")

### Expected result after these steps 

Should work like without cache type filter

## c:geo version 

2021.05.08-NB

## Reproducible 

Yes

**Comment by eddiemuc** [comment]
Can't look at code right now, but my assumption is that this has to do with with the "Next page" capability which is implemented by some connectors and should handle the "load more caches" thingy.

Just be aware: in context of the wishes for integrating search/filtering also into online searches (see other issues/requests in search/filter project) we might have to rework larger parts of this area anyway. Also if search should switch from "old" GC.com html scraping to Web API I expect larger changes here (we might also rethink the 20 cache limit in this case because there would no longer be a technical reasons for it)

**Comment by Lineflyer** [comment]
Problem now also reported on support and social media.
The "Next page" seems to be broken in conjunction with adventure labs.

**Comment by eddiemuc** [comment]
> Problem now also reported on support and social media.
> The "Next page" seems to be broken in conjunction with adventure labs.

Again, nothing broken here. LC connector simply does not implement the "next page" capacity (like most connectors btw). This is only so "visible" in this case because it is the only connector delivering lab caches.

The capacity could maybe be implemented. However, I want to retire "next page" anyway since this was only invented due to limited search result limit capacities of gc.com (back when website parsing was necessary)

I could however priorize implementation of `ISearchByFilter` for this connector, it this request is really urgent?

**Comment by Lineflyer** [comment]
This issue is not about no "more caches" function for ALC but about the regression that the "more caches" fails for gc.com as soon as ALC is active.

**Comment by eddiemuc** [comment]
Understood. PR #10919 shall fix this

**Comment by eddiemuc** [comment]
PR is merged to `release`
