### ISSUE TITLE
Allow usage of stored filters in other filters (nested filters)

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10581]
Before this can be implemented, storing of individual filters must be enabled in general.

(From @magiepfourtytwo)
Today en extension of the "Personal Filter Set" came to my mind: What if there would not just be a list of saved filters, from which one filter can be restored, but if these would even have a tick box, to en/disable the corresponding filter, allowing an AND (or probably even an OR) combination of the selected filters?

I indeed already thought about a filter to select/deselect saved filters. Few obstacles on the way (e.g. such complex filters are for sure no longer translatable to a web API of the connectors, and what to do if someone deletes a filter which is used in another filter?). But it's on my personal list.

I have to ask for some patience though. Weather is currently far too good for programming

_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/issues/10559#issuecomment-835753643_

**Comment by fm-sys** [comment]
What about opening a sub-filter screen instead of allowing the selection of saved filters?

![Screenshot_20210719_225138_copy_540x671](https://user-images.githubusercontent.com/64581222/126225866-101d7632-9bb5-41f2-aae9-409498349444.jpg)

The user then can just add a "sub-filter" filter and then can do everything with it. Load a saved configuration, create and adopt the sub-filter, etc, etc...

I guess this would be the cleanest and feature richest solution, where most code parts AFAIK even could be reused without much effort.

**Comment by eddiemuc** [comment]
> What about opening a sub-filter screen instead of allowing the selection of saved filters?

interesting idea, but I would rather see this as a replacement for #10582

**Comment by fm-sys** [comment]
> I would rather see this as a replacement for #10582 

Thanks for reminding me about this issue. To be honest, I think that even not a single advanced user will never write a filter confic like `NOT(AND(type:TRADITIONAL:MULTI;OR(terrain:4.0:5.0;difficulty:4.0:5.0)))` manually. But a nice UI nesting possibility would give users unlimited possibilities. 

Although I think the sub-filter feature would be a replacement for this issue here as well. We could give users with the "sub-filter" filter the same possibilities as with the actionbar icon in maps viewer. Short click -> open filter screen | Long click -> stored filter selection.

As loading of stored filters would be possible with the "sub-filter" as well, IMHO we don't need to implement an separate "saved filter" filter. Remember, that both filters would only be used by a very small user group anyway...

**Comment by eddiemuc** [comment]
> As loading of stored filters would be possible with the "sub-filter" as well, IMHO we don't need to implement an separate "saved filter" filter. 

This part I don't understand. The "nested filter" option does allow to build (very complex!) filters, but it does not by itself allow the re-use of a saved filter as part of another one. The later one is what this issue is about, the former one is what #10582 is about.

> Remember, that both filters would only be used by a very small user group anyway...

This is why it is way down on my personal Prio list currently :-) (also, it must not necessarily be me implementing this of course)

**Comment by Lineflyer** [comment]
Nested filters...OMG. ;)
Sounds interesting for really advanced users...

Speaking from testers perspective:
I might not deeply test such nested filters, however I would be happy if this would be developed on `master` in order not to blow up changes for the running beta/next release.

**Comment by eddiemuc** [comment]
Note that this issue is still about usage of stored filters inside other filters.

The idea to "deep-edit" nested filters is a different thing, and should be converted into a separate issue if it should be followed-up

**Comment by fm-sys** [comment]
> Keep in mind: including a stored filter in another filter will also change the result of that filter when the used saved filter is changed elsewhere.

OK, got the difference. Then both filters should go into a new category "advanced", "complex filters", "nested filters" or something like that. 

> I would be happy if this would be developed on `master` in order not to blow up changes for the running beta/next release.

Totally agree 👍

> The idea to "deep-edit" nested filters is a different thing, and should be converted into a separate issue if it should be followed-up

There are very legit use cases for it: e.g. I want to display only traditionals OR caches which are contained in a specific list but what to hide all found ones. A filter which is currently not possible to build.

But I will open a separate issue...

**Comment by murggel** [comment]
@eddiemuc can this be closed as duplicate to #14600 ?

**Comment by eddiemuc** [comment]
> @eddiemuc can this be closed as duplicate to #14600 ?

Yes, good catch!
