### ISSUE TITLE
Gc.com search for attributes not implementable: WebApi proxy v2: cgeo explicitely not authorized?

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#10621]
I found something fishy today when I tried to integrate V2 of gc.coms Web proxy Api.

The following things were all done while logged in as a premium member.

The following Uri is an example for a search of traditional caches (ct=2) with the V2 Proxy WebApi:
https://www.geocaching.com/api/proxy/web/search/v2?ct=2&take=500&skip=0&sort=distance&asc=true&app=cgeo 

When I issue it exactly like this I get an "unauthorized" message:
`{"statusCode":401,"statusMessage":"Unauthorized","errorMessage":"","uri":"http://websearch.groundspeak.biz/web/search/v2?ct=2&take=500&skip=0&sort=distance&asc=true&app=cgeo"}`

When I issue the SAME request with V1, it works:
https://www.geocaching.com/api/proxy/web/search?ct=2&take=500&skip=0&sort=distance&asc=true&app=cgeo 

And now the mean part: when I issue the same request (for V2) with an `app`-parameter-value **other** than `cgeo` or without the `app` parameter, it works too! E.g.:
https://www.geocaching.com/api/proxy/web/search/v2?ct=2&take=500&skip=0&sort=distance&asc=true&app=tumdedum
https://www.geocaching.com/api/proxy/web/search/v2?ct=2&take=500&skip=0&sort=distance&asc=true

Are they really explicitely blocking c:geo from using the V2 Proxy WebApi???

**Comment by eddiemuc** [comment]
I saw my original statement wrt "other app" was a bit confusing. I meant "another value than `cgeo` for the parameter `app`". I edited issue description accordingly.

**Comment by eddiemuc** [comment]
...and this is a problem because some of the filtering options of the online map seem only to be availablein v2, e.g. attribute filtering

**Comment by baiti** [comment]
Just wondering: Is there any documentation around for this API?

Without any doubts, `app=cgeo` is explicitly kept out. But: why do you specify the app parameter at all? Don't you get all you need without specifying it?

**Comment by eddiemuc** [comment]
> Just wondering: Is there any documentation around for this API?

Not that I know of. But it is very easy to reverse engineer it by looking at the requests GC.com sends when using different filter options on their website.

> Without any doubts, `app=cgeo` is explicitly kept out. But: why do you specify the app parameter at all? Don't you get all you need without specifying it?

As @Lineflyer explained, this seems to be some courtesy of us towards Groundspeak so they are able to track what we request.

I experimented some more. It seems they check other things too because if I issue the requests as above to V2 without app=cgeo from within the emulator, then I also get the HTTP 401 response. So leaving out the app parameter alone does not do the trick anyway.

For now, I will restrict implementation of #4977 / #10027 to the things offered by the V1 API. So far, it seems to support most search parameters too (tried name, size, type, difficulty, terrain, distance so far). Only notable downside I found so far are attributes.

**Comment by baiti** [comment]
> As @Lineflyer explained, this seems to be some courtesy of us towards Groundspeak so they are able to track what we request.
> 

Interesting. So using this API is already a result of some sort of negotiation.

> I experimented some more. It seems they check other things too because if I issue the requests as above to V2 without app=cgeo from within the emulator, then I also get the HTTP 401 response. So leaving out the app parameter alone does not do the trick anyway.

That tells me they must be examining certain http headers which tell whether the request comes from a phone. Perhaps the user-agent is already sufficient to do so. You could fake the user-agent or not send one at all...

**Comment by eddiemuc** [comment]
Tried all things which seem important in my opinion from the search page (left out things like "corrected coordinate" and "membership status" so far), it seems the only really important thing missing in V1 is "attributes". For now we have to live without it I fear.

If time permits, me or someone else may investigate deeper on how to enable V2 (apart from leaving out `app=cgeo`), but I will de-prioritize this for now as there is a ton-load more of work to be done for unifying filtering/searching in cgeo anyway...

**Comment by eddiemuc** [comment]
@Lineflyer, and rest of team:  I am somewhat frustrated that we cannot offer attribute search to cgeo users just because of this seemingly meaningless blockage by Groundspeak. Do you think it would be appropriate to politely ask them whether they can lift this ban? Maybe something like the following (rough draft!):

Hello xyz,

as you know, we use your Web Proxy API for c:geo search requests. To make cgeo requests identifiable to you we always send a parameter "app" with value "cgeo". E.g.:
https://www.geocaching.com/api/proxy/web/search?ct=2&take=500&skip=0&sort=distance&asc=true&app=cgeo 

We recently dicsovered that there is a version 2 of this Web Proxy API used by the website, and we discussed switching to this version (specifically because it supports searching caches by attributes). However, we also discovered that this API is not working when the parameter "app" is set specifically to the value "cgeo" is send. As an example:
* Following call works (when logged in): https://www.geocaching.com/api/proxy/web/search/v2?ct=2&take=500&skip=0&sort=distance&asc=true
* Following call works too (when logged in): https://www.geocaching.com/api/proxy/web/search/v2?ct=2&take=500&skip=0&sort=distance&asc=true&app=tumdedum
* but following call does not work (even when logged in): https://www.geocaching.com/api/proxy/web/search/v2?ct=2&take=500&skip=0&sort=distance&asc=true&app=cgeo

This seems intentional. As we realize that the relationship of Groundspeak and cgeo is kind of special we will (and have to) accept of course if Groundspeak explicitely doesn't want us to use the newer WebAPI Proxy. Nevertheless we want to ask kindly if there is any way to lift this restriction? 
* We assume that at some point Groundspeak wants to shut down the older version of the WebAPI proxy. Currently this would break cgeo completely. 
* Also we see the chance to replace the current "legacy advanced search page" parsing with calls to the new WebAPI proxy. Our understanding is that Groundspeak would like to desupport those as well.

**Comment by fm-sys** [comment]
Yes sounds good. Maybe we can emphasize even more clearly the advantages for groundspeak:

- they can shutdown many of their old static pages
- it will dramatically reduce the server load

**Comment by Lineflyer** [comment]
Wo be honest:
I am not sure, whether it has any benefit to ask shown.
From their perspective it will sound like "Hey, we are planning to improve and intensify using other methods than the officially offered way (=Partner API). Can you allow us please?". 

I am pretty sure they will interprete this as a statement to go away from any official solution once again.

Don't get me wrong, I would love to have the advanced possibilities of these filtering....but on the other hand we should really think about, whether it could be better to switch to the partner API instead of implementing more and more methods with a potential to have a high rate of maintenance as they might change or stop working anytime.

I know...there are the bad conditions for BM coming with that still to be solved or improved or just accepted.

Anyhow I think asking such question would somehow make the relation worse again.

**Comment by eddiemuc** [comment]
Hm maybe you are right. Guess then I can close this issue. But it's a damn shame

**Comment by fm-sys** [comment]
> ....but on the other hand we should really think about, whether it could be better to switch to the partner API instead of implementing more and more methods with a potential to have a high rate of maintenance as they might change or stop working anytime.

Do you really think c:geo will ever switch to the partner API? Remember the ALC handling... At the end they even said "yeah, fine. Continue using tthe webApi for the time being"

PartnerAPI would mean:
- no OC, EC, ... Platforms
- for BM only tradis with D/T < 2
- less labcache information 
- ...and probably very much more 

If groundspeak does not suddenly fundamentally change their attitude, c:geo will never use the partnerApi in the future - Just because it would be far too much refactoring for us. 

We are happy to work more closely together, we are IMHO also happy to promote PM-only functions, but we will never can disturb the original c:geo just because we want to switch to the partner API. 

I would say "asking them costs nothing" ;-) 

If they reject everything is still fine. 

They won't just get angry, block all existing functionality and actively exclude all c:geo users. 

We are in a pleasant situation. Over 70% are PM and many of them are only PM's cause c:geo exist. To be honest, I know many Geocacher who would never become a premium member if cgeo would not exist. Cause the BM experience in the official partner apps is that bad that you simply cannot imagine that there's something better. (So it was with me, but luckily I knew c:geo)

**Comment by fm-sys** [comment]
> Anyhow I think asking such question would somehow make the relation worse again.

With attribute filtering we would like to add an explicit PM-only feature to cgeo. Do you really think that this would make the relation worse?

Theoretically we could just change the user argent and everything works. But we show the partnership and want to work with them to incentivize PM-only members in c:geo.

I think GC knows that it will never come to partnerApi, as they know we won't just throw OC away. And they cannot create official advantages for c:geo over other co-apps. Therefore, they should actually be pleased what we at least step away from old static pages.

Maybe we can negotiate something that we highlight features that are available for premium members.


---

In any case, I am convinced that we should politely ask GC about this issue. This is far better than continue playing hide and seek ;-)

**Comment by Lineflyer** [comment]
> I think GC knows that it will never come to partnerApi, as they know we won't just throw OC away. 

That part at least we explicitly asked some years ago in our first discussions, and they answered, that they do not see a problem in our multi platform approach and have been willing to take out this part from the agreement.

Regarding the general topic...I have to think a bit about it over the next days.
At the end its their platform and there are terms of use for users and for partners which you need to follow to use it.
I somehow still think, that at the end of the day we should arrive on something official as I consider "hide and seek" is what we currently do and asking for V2 of hide and seek sounds strange to me.

Before we go this way I would rather try to find good conditions for c:geo on API. If we fail, we can still continue to do what we currently do. Thats why I think its maybe the wrong point in time to ask regarding whats the topic in this issue,

**Comment by fm-sys** [comment]
> Before we go this way I would rather try to find good conditions for c:geo on API. If we fail, we can still continue to do what we currently do.  

What came to my mind right now while reading your post: we all know these BM limitations like type and D/T maximum which is simply not acceptable. But maybe we could agree on something, that we do not display the caches in-app but are allowed to provide a directly accessible "open in browser" action. So users could view all caches but cannot store them offline. Maybe this could be something Groundspeak would accept. It's IMHO fair for BM's as well as for groundspeak.

The argument: Only when users can try "better caches" themselves, they might get convinced of the premium service...

**Comment by baiti** [comment]
The way I look at it, I'd say everything is ok with cgeo the way it is now. cgeo is already partnering with HQ, trying to be good citizen, not eating their cake, in fact providing for them to some extent. There has been active communication with resepct to using the API method in question here, otherwise `&app=cgeo` would not exist. I have a hard time to understand why HQ would deliberately key off  `app=cgeo` and make the request fail. The only explanation I'd have is that this is some sort of a software bug on their side. Every other explanation makes no sense at all. Having said this, I'd say this needs to be resolved, independent from any other decision further down the road. We need to understand what's going on with respect to using that API. The answer could well be ooops we're sorry junior programmer xyz screwed it up .....

If there is more behind it, we need to understand that as well and then once we do, we can factor that into the discussion of formal partnering based on whatever API+ToU that might be in the end, perhaps not the one we all know and love so violently.

**Comment by Narrat** [comment]
> What came to my mind right now while reading your post: we all know these BM limitations like type and D/T maximum which is simply not acceptable. But maybe we could agree on something, that we do not display the caches in-app but are allowed to provide a directly accessible "open in browser" action. So users could view all caches but cannot store them offline. Maybe this could be something Groundspeak would accept. It's IMHO fair for BM's as well as for groundspeak.

Well, what a experience that would be. But it isn't even the restricted offering of caches. As a BM you only get three per day to find. And after you found three there are no cache details for more.

**Comment by Lineflyer** [comment]
Back to the original topic:
I agree, that the current behavior can most probably only be a accidental fault, thus why not fix it on our side (if you understand what I mean?!).

**Comment by baiti** [comment]
Here is another instance of very similar behaviour: https://github.com/cgeo/cgeo/issues/11001. The API was locked down without notice. However, I have to say, it was more or less announced that this might happen in that mail Annie sent a while ago with respect to using the public API vs the newly updated partner API.

It is a cool strategy to leave the public API open as a teaser and once the function is out and the users love it, then lock it down without notice, essentially either forcing us into taking the function out (already happened implicitly as it is no longer working) or jump on the partner API which, even if we did that, will take substantial time to get the functionality back, besides dealing with cans of worms.

I have my doubts whether this will ever lead to a fruitful cooperation.

**Comment by fm-sys** [comment]
I'm afraid that switching to the partner API might even lead to an unilateral partnership with GC. They can tell us that we have to remove features or more advertise their premium services - and we will have no way to reject their wishes...

**Comment by Lineflyer** [comment]
Mail to Groundspeak on its way to ask for guidance/allowance as agreed upon in our dev call.

**Comment by Lineflyer** [comment]
First answer (shortened to the essential):

[...]Thank you for letting me know about this issue.  It is most certainly not intended and I will find out what’s happening and get it fixed immediately.

Second reply from engineering lead:

The main thing I'm noticing here is that they're sending in two different JWT tokens - one via the `jwt` cookie and another in the `Authorization` header. In the ApiProxy, the token in the cookie takes precedence over the header. In the requests I've looked at that failed with 401's, the JWT in the cookie has expired while the JWT in the header is valid.

In the successful requests, the tokens in the cookie and the header are identical.

---

Not sure if thats is our problem here, but I cannot judge...you guys probably can.

**Comment by ztNFny** [comment]
Testing those URLs (https://www.geocaching.com/api/proxy/web/search/v2?ct=2&take=500&skip=0&sort=distance&asc=true&app=notcgeo vs https://www.geocaching.com/api/proxy/web/search/v2?ct=2&take=500&skip=0&sort=distance&asc=true&app=cgeo) in my web browser gives the 401 error. There's no Authorization header sent there. So that's not the problem there.
Please provide "open that URL in your webbrowser" as a testcase to them.

**Comment by Lineflyer** [comment]
Thats pretty straight forward, so I formulated this as a testcase and sent it back. Then we can work from there, once they can reproduce.

**Comment by eddiemuc** [comment]
Hooray, something seems to have changed on Groundspeak side. At least the test link with app=cgeo does work for me now:

https://www.geocaching.com/api/proxy/web/search/v2?ct=2&take=500&skip=0&sort=distance&asc=true&app=cgeo

**Comment by Lineflyer** [comment]
No answer received yet, but seems they got my testcase and worked from there :)

**Comment by Lineflyer** [comment]
We received confirmation by Groundspeak, that the problem is fixed.
