### ISSUE TITLE
String search_filter_info_message contains a failure

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10653]
While translating the string `search_filter_info_message` on Crowdin I stumbled upon "Distance and Terrain". Probably it was meant to say "Difficulty and Terrain"?!

Also a `.` after "inversion" is missing.

**Comment by eddiemuc** [comment]
Yes that's a bug in the text. Well spotted :-)

**Comment by eddiemuc** [comment]
@Lineflyer 
I created PR #10655 for this. 

But before I merge this: this is a very long text, and it might change again during further filter development. Do you think it makes more sense to place this in some sort of FAQ page instead of placing it into `strings.xml` where each change causes a cascade of translation effort?

**Comment by Lineflyer** [comment]
Too late. Already merged. 
Lets keep it in strings for now....but what you said should be considerable in general. Before committing such help texts it makes sense to wait until they are considered final/usable.
