### ISSUE TITLE
Target "List all changes" to commit history

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10662]
There is still a button shown below the changelog "List of all changes", which currently targets the release tags page on Github. This contains only a copy of whats in the changelog, which makes no sense.

It should maybe targeted to show the commit history of branch `release` instead.

_Originally posted by @Lineflyer in https://github.com/cgeo/cgeo/issues/10640#issuecomment-842416417_

**Comment by moving-bits** [comment]
I would rather not link to a commit history. Information in commit history is rather useless for most people, mostly unreadable for them, contains loops (several attempts to fix a certain issue), maybe reverted changes etc.

If we want to shorten our regular (and to be translated) release notes, I see two methods:
- Either we document only the most relevant changes (and translate this file)
- or we distinguish between a short release note with the most relevant changes (and translate this), and put all the other changes into a second file, which does not get translated, and is linked to from within the app (and maybe other places).

As I think documenting all (user-relevant) changes is a good idea, I would vote for method two.
Technically we could put those info into a second file, maybe called `changelog_master_detail.md` or something like this.
In either alternative I would skip all technical-only issues which are not relevant to the user, as well as in-between steps without direct relevance to the user.

**Comment by Lineflyer** [comment]
Puh... I prefer the method with least manual effort, thus it would be option 1.
That's why I suggested to link to the commit history instead for those who want to dive deeper....I don't see any self-maintained alternative at this moment.
And I would really like to minimize the effort. I guess most users would neither read a very long list nor click the button anyway.
Also on Google Play the changelog is limited to a very low amount of chars (500?).

We once tried to use the issue milestones to reflect all closed issues for a certain release and even this failed due to the intense maintenance effort.

**Comment by moving-bits** [comment]
I think the first question is, whether we want to have a "full" changelog or not. From the perspective of a user being relatively deep into c:geo I like having a detailed one, but I understand that our lists can be overwhelming for the average user.

So shortening the official release log could be a solution. This shortened version could also be used for the Play Store description.
We only need to decide on what change is relevant enough to be put into the short version. (This may vary widely depending on user's perspective and individual usage pattern for the app.)


With regard to the "extended" version:

Tracking "all" (user-relevant) changes is ok in terms of work - we do it already currently. This works mainly, because I update the changelog files every couple of days to keep track with current changes. (Here I already filter-out internal changes, loops etc.) Doing so only once a week or even less frequently would make live much harder for this, especially in times with a high commit frequency.

Thinking of maintenance effort maybe the following approach could work:
- Document the most relevant changes in `changelog_master.md` / `changelog_release.md` (version specific, as today)
- Additionally use a `changelog_complete.md` in which you put all changes of all versions.
 
The latter could be the document being linked to from app and website.

When publishing a new version you would have to copy the contents of the current changelog to `changelog_complete.md` as additional step compared to today. Or, if you put in there all the changes already on-the-fly, you would only have to enter the release version here as last step.

Would that be feasible?
