### ISSUE TITLE
Wording and sorting improvement proposals for filter element names

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10672]
It took me a while to find out what some filter elements are used for as they have rather short names which could IMHO be improved.

Proposal:
- Hidden --> Hidden Date (in order not to be confused with hidden by)
- Name --> Cache Name (in order not to be confused with Owner)
- Description --> Cache Description (Don't know why, but it sounds not intuitive to me without cache in it)
- Type --> Cache Type (Don't know why, but it sounds not intuitive to me without cache in it)

Furthermore I think the alphabetic sorting of them is not the most user friendly to quickly find a specific element (if you don't know its exact name).
Maybe it would be useful trying to group them, e.g. (Group names TBD):
- Basic 
  - Cache Type
  - Cache Name
  - Cache Description
  - Owner
  - Hidden Date
  - Status
- Detailed 
  - Size
  - Difficulty
  - Terrain
  - Favorites
  - Attributes
- User specific
  - Personal Note
  - Offline Log
  - Distance

**Comment by eddiemuc** [comment]
In a first step I added/changed the display names as suggested.

The "grouped" view is a good idea but a bit more complicated. Thus I will do it later.

**Comment by MagpieFourtyTwo** [comment]
Sorry for coming late, but wouldn't ``Detailed`` better be ``Detail`` or ``Details``?

**Comment by eddiemuc** [comment]
> Sorry for coming late, but wouldn't ``Detailed`` better be ``Detail`` or ``Details``?

This is very easy to change of course. Apart from that, does the group selection and the group assignment for filters fit?

I was myself a bit irritated that filters "Difficulty/Terrain" are considered "Detailed" (not "Basic") while on the other hand they are part of the "Basic" filter edit mode

**Comment by MagpieFourtyTwo** [comment]
> I was myself a bit irritated that filters "Difficulty/Terrain" are considered "Detailed" (not "Basic") while on the other hand they are part of the "Basic" filter edit mode

This can indeed be irritating ... esp. as D/T is most probably the most frequently used filter anyway.
OTOH I would consider ``Hidden Date`` as a typical ``Detail``.
But in fact, question should be, how this classification is meant, I guess ...
Perhaps @Lineflyer can enlighten us about his motives and explain his structure idea.  ;)

**Comment by fm-sys** [comment]
> I was myself a bit irritated that filters "Difficulty/Terrain" are considered "Detailed" (not "Basic") while on the other hand they are part of the "Basic" filter edit mode

I think these groups should give additional value to the user. "Basic" sounds to me, that it can be applied to caches which are not stored offline. While the other group(s) work only if the cache is stored offline. 

Would this be a logical grouping critical?

**Comment by eddiemuc** [comment]
> Would this be a logical grouping critical?

You mean building groups telling the user something about the "online usability"? 

Not as trivial as it may sound. Since different providers offer different search capabilities, some filters are usable by one connector and not the other (e.g. the famous attributes). And some are usable but only partly (e.g. in Gc.com you can filter "name" only with "contains" and whole words, and for "favorites" you can only Filter minimum absolute numbers)

**Comment by fm-sys** [comment]
> Since different providers offer different search capabilities

I think we can take GC as reference.

As long as we still name the categories "basic" and "detailed" it doesn't need to fit perfectly for every connector. Just as a little help for us to deside which filters should be part of "basic".

**Comment by eddiemuc** [comment]
If gc.com is taken as a reference, here is what they currently offer (screenshot from the info text for "Search by filter", nicely formatted/marked-up by @moving-bits (thanks!)):

![image](https://user-images.githubusercontent.com/6909759/119609108-4fe65900-bdf7-11eb-80fc-5edec2f6e60e.png)

Currently, it contains things from all three categories (e.g. "distance" from the "user-specific" group) Note also that "attributes" are not supported by c:geo but only because they don't offer the API to us - so should this be an aspect of grouping in the filter selection? 

And do the group names "Basic", "Detailled", "User-specific" still make sense if stuff is categorized by "online-availability"?

I might not have enough creativity to come up with revised group names and filter assignments to those groups on my own. But I can easily and will gladly implement any concrete change suggestions made (like e.g. @MagpieFourtyTwo asking for renaming "Details" to "Detailled")
