### ISSUE TITLE
Personal note: changes of coordinates are not recognized in Compass

### ISSUE THREAD

**Issue by baeriwiliwonka** [cgeo/cgeo#10677]
Precondition:
Enter new coordinates in the personal note (A)

Action:
Change the coordinates in the personal note (B) and enter the compass.
Switch the target to personal note.

Behavior:
The coordinates of the first personal note is displayed (A)

Expected:
When the coordinates in the personal note is changed, it should be also updated in the compass target list. New coordinate should be shown (B)

**Comment by murggel** [comment]
I will take a look at it

**Comment by murggel** [comment]
Due to changes for fix parsing of user-defined waypoints with empty coordinates (#9337 / #9338), the name for user-defined waypoints are used as key for finding already existing waypoints.
Unfortunately auto-generated names are not correctly considered, so that changing coordinates in the personal note are not detected correctly as a new waypoint.

I will provide a PR which ignores the auto-generatef waypoint name on extracting waypoints.

Probably as addition (to avoid duplicate waypoint-names and force unique ones), the calculation of the waypoint-name can be enhanced similar to the way it was don for creating new waypoints in the waypoint list. But that would be a new issue.

**Comment by murggel** [comment]
Ah, or I can use the name only, if the coordinates of the already existing waypoint is empty ...

**Comment by murggel** [comment]
Fixed with PR #10747
