### ISSUE TITLE
Use switch style instead of box style to toggle basic/advanced

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10716]
Just a cosmetic question:
Shouldn't we use this nice switch style (as used in the PQ view to enable "Show all")?

So it would be just a disabled switch labeled "Advanced" instead of two boxes with "Basic" and "Advanced"

**Comment by eddiemuc** [comment]
There was a discussion about that in some issue, I believe @fm-sys  argued against it.

I have same opinion as always: we should have a system-wide unique UX handling of similar situations (in this case: how to display a switch). Whatever this unified approach is I will gladly take it over. Is it the PQ switch?

Please note: if the PQ style is the "switch style" to choose I would expect to convert **ALL** "switches" in c:geo to this style. This includes e.g. the "hide" switches in map quick settings, the "GPS sensors used/all sensors used" switch in the compass and the numerous boolean settings in "Settings". We have to stop solving UX problems like that oin a case-to-case-basis if we ever want to get a unified UX experience for c:geo.

So maybe this is the chance to clarify the "switch" UX statement once and for all?

**Comment by eddiemuc** [comment]
I assume this is the one you mean:
![image](https://user-images.githubusercontent.com/6909759/119252486-d65b2a80-bbac-11eb-8358-6886247e2c01.png)

**Comment by fm-sys** [comment]
The switch style is much more modern than a checkbox / toggle button. But IMHO the preferred usage is kind of unambiguous:

---

![Screenshot_20210523_100817_com fmsys settlements](https://user-images.githubusercontent.com/64581222/119252966-3783fd80-bbaf-11eb-9111-5f2cc515a6a2.png)

A toggle button group: Should be used if both/all selection options are equivalent and only one option can be selected. 

---
![Screenshot_20210523_100904_cgeo geocaching](https://user-images.githubusercontent.com/64581222/119252968-38b52a80-bbaf-11eb-979c-2f997110b16f.png)

A switch: For enable/disable situations 

---

![Screenshot_20210523_100951_cgeo geocaching](https://user-images.githubusercontent.com/64581222/119252972-3a7eee00-bbaf-11eb-9fde-a23eb3d9d627.png)

Checkbox: If you can select multiple things for an element which all belong into the same category 

---

To be honest, the first time I used c:geo, I though: Why do they have that many checkboxes but not a single switch?

So I would really like to see some "c:geo design guidelines". We could use our wiki or add a section "design guidelines" to discussion https://github.com/cgeo/cgeo/discussions/10679, which I used as kind of a wiki but with the possibility to comment directly below...

I would prefer if we would use #10679 for it, so that we have one common place for all things which deal with UX refacing.

**Comment by moving-bits** [comment]
From the examples above:
- If I have a single option (e. g. PQ "show all" or unrelated options in settings), I would use a switch
- If I have a multi-select option (e. g. "store in list") I would use checkboxes

**Comment by eddiemuc** [comment]
switch it is.

**Comment by eddiemuc** [comment]
fixed with PR #10723
