### ISSUE TITLE
Filter: Basic/Advanced selection lost on rotation

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10715]
## Bug description 

The selection whether to use basic or advanced filtering is lost on device rotation

### Steps to reproduce the problem

- Open new filter
- Switch from basic to advanced
- Rotate device to landscape

### Actual result after these steps 

Filter is back to basic mode

### Expected result after these steps 

Filter should stay in advanced mode

## c:geo version 

2021.05.22-NB

## Reproducible 

Yes

**Comment by MagpieFourtyTwo** [comment]
Side effect: If you are in [Advanced], then delete all filters using the trash can, and rotate, the [Basic] mode will be shown with no filters nor filter actions at at all. ;)

**Comment by MagpieFourtyTwo** [comment]
The setting is even lost after applying a defined advanced filter to a list and afterwards returning to the filter definition page:
It seems to always starts with [Basic].

**Comment by fm-sys** [comment]
Same applies if you create any "basic compatible" filter in advanced mode -> apply the filter -> reopen the filter. 

I think the advanced/basic switch should be stored permanently in our preferences.

**Comment by eddiemuc** [comment]
The aspect that the switch setting "Advanced" is lost on rotation is a bug which I will fix.

As for the rest: right now the setting "Basic/Advanced" is not stored anywhere. On opening the activity, the given filter is analyzed. If it is displayable in "Basic", then "Basic is chosen, otherwise "Advanced" is chosen. 

I see that this is probably to be discussed :-). I see three possible solutions how to handle the "on open" case:
* Don't store, decide upon filter complexity (Leave as is, but with the rotation bug fixed of course)
* Store on a "per-filter" basis (but choose "Advanced" anyway if filter is too complex to be displayed in "Basic")
* Store on a "system-wide" basis in "Settings" (but if "Basic" is chosen and a filter is too complex to be displayed in "Basic" thenswitch to "Advanced" anyway)

I like simple solutions and thus implemented the first option. @fm-sys suggested the third one. I will wait for more opinions (and fix the rotation bug meanwhile...)

**Comment by eddiemuc** [comment]
Ah btw, if this gets a longer discussion, it should probably go into its own issue

**Comment by fm-sys** [comment]
> Store on a "per-filter" basis

You can only store filters in advanced mode anyway, so it will always be "advanced". You do you mean "lists" vs "map"? Anyway, this would be confusing and too complex...

> Store on a "system-wide" basis in "Settings" (but if "Basic" is chosen and a filter is too complex to be displayed in "Basic" thenswitch to "Advanced" anyway)

Anyway, imagine a pro-user. Won't he be annoyed if he always have to start at "basic" every time?

And you are right, the setting would be a "force-advanced" setting, pointing to true/false. So false does not mean that it needs to be basic, but decides automatically.

**Comment by eddiemuc** [comment]
> Anyway, imagine a pro-user. Won't he be annoyed if he always have to start at "basic" every time?

I don't see this as a selection between "amateur" and "pro". I see it as a selection between "I want to do something simple so I don't need all those extra options" vs "I want to do something complex, so I need the extra options". Even a "pro" might simply want to filter by e.g. cache types from time to time, and he might be glad that he does not have to spend these extra clicks of adding a cache type filter in this case.

**Comment by eddiemuc** [comment]
Original issue is fixed with PR #10715. I suggest to create a new error for discussion on "saving basic/advanced state"

**Comment by MagpieFourtyTwo** [comment]
> I don't see this as a selection between "amateur" and "pro". I see it as a selection between "I want to do something simple so I don't need all those extra options" vs "I want to do something complex, so I need the extra options". 

I see it as an "the GUI is always changing, based on criteria, I don't really see (in advance) and I always have to change it, if I want to add some more elaborated stuff". And chances are, that after opening the dialog something will be added, so in fact the GUI must not just show the current definition, but - to make this perfect - it must be able to predict, what I want to do. And this is simply impossible.

Apart from this: An always changing GUI is not a good idea at all, IMO.

Honestly: Which GUI do you know, that always switches between basic and advanced? I know absolutely none. If I once say "show expert mode", I'll get expert mode. And if I want to do basic stuff, I can even switch it back.

TMALSS: IMHO the only really good solution is a permanent setting.

**Comment by MagpieFourtyTwo** [comment]
Another reason against permanent switching: On (felt) every single switch, the filter seems to automatically add the criteria "cache type" , which has to be deleted manually after switching back to advanced - really annoying, too.

**Comment by eddiemuc** [comment]
> Another reason against permanent switching: On (felt) every single switch, the filter seems to automatically add the criteria "cache type" , which has to be deleted manually after switching back to advanced - really annoying, too. 

That's understood.

But do you want one global setting to open all filter always in advance, or do you want a storage per filter to remember how it was last opened (basic or advanced)?

**Comment by fm-sys** [comment]
One for all IMHO. Please don't make things more complex as they are...

**Comment by eddiemuc** [comment]
> One for all IMHO. Please don't make things more complex as they are... 

While the "one for all" is easier for implementation of course, I think the other solution is more intuitive for the user. Each filter, when opened again, will then simply be in the mode where he last left it ( either basic or advanced).

**Comment by MagpieFourtyTwo** [comment]
I agree with @fm-sys: one for all and that's it.

**Comment by eddiemuc** [comment]
@fm-sys , @MagpieFourtyTwo I will implement the global "enforce advanced opening" switch for you.
But for my own usage I will implement the solution to remember last setting too (will only be used if the global switch is not set). I would find it weird for myself if I close a filter in "basic" but would get it back in "advanced" at reopening (same as the other way around), which is what will happen with the global option.

**Comment by Lineflyer** [comment]
Wait a bit...global switch?
I thought just the setting whether basic or advanced is remembered between all filters.

**Comment by eddiemuc** [comment]
> Wait a bit...global switch?
> I thought just the setting whether basic or advanced is remembered between all filters.

Maybe there's a misunderstanding on my side, but my impression was that the wish was for a global switch to enforce opening of all filters in "advanced mode" always. (Currently, filters are opened in basic mode if possible without removing filter features, and in advanced mode otherwise).

Is my understanding wrong?

**Comment by Lineflyer** [comment]
> Is my understanding wrong?

I thought more, that the meaning was, that if you selected "Advanced" on one of the filter menus it shall be advanced also in all others. I mean: Remember the last used setting (Basic or Advanced) over the whole app.

**Comment by eddiemuc** [comment]
> > Is my understanding wrong?
> 
> I thought more, that the meaning was, that if you selected "Advanced" on one of the filter menus it shall be advanced also in all others. I mean: Remember the last used setting (Basic or Advanced) over the whole app.
> 

Oh. Ok I got that wrong indeed.

But this would be a strange thing to do. Say this setting is currently on "basic" and I open a filter only displayable in "advanced". Would the global remembered last Settings then go to "advanced" or stay with "basic"? And if it stays with "basic", at which point would it switch to "advanced"? When I apply the new filter while still being in "advanced"?

Why not save last setting per filter instead? With this new info it would seem simpler to me in comparison.  

And just to be sure: there is no global switch wanted to force filter opening to "advanced" at all time?

**Comment by MagpieFourtyTwo** [comment]
> I thought more, that the meaning was, that if you selected "Advanced" on one of the filter menus it shall be advanced also in all others. I mean: Remember the last used setting (Basic or Advanced) over the whole app.

Same for me: Once you switch from [Basic] to [Advanced] view, filters should always be opened in [Advanced] mode, no matter if they are basic or advanced. But, to be honest, I don't care, where this switch will be stored, as there are no more changes needed. ;)

What I admittedly did not think about is the foll. scenario, which is the other way round: 
1. [Advanced] has been chosen in order to construct a more complex filter, but ...
2. the user switches back to [Basic] afterwards (for any reason), and [Basic] then stays active for all, until ...
3. he opens the "complex" filter constructed in 1.
... then the GUI must of course switch to [Advanced] automatically, cause otherwise the filter can not be displayed nor edited.

Question is, should this "automatic" fallback to [Advanced] change the global setting ...?
I would say: No. (and @eddiemuc will most probably agree ;) ).
The global setting should stay [Basic] - if possible.

Thus in fact the global setting for filter GUI may be s/th which allows to distinguish two cases:
1. use [Basic] GUI, if possible
2. always use [Advanced], no matter how complex (or simple) a filter may be

Thus I agree with @eddiemuc about the global setting, which in fact would just determine the preferred style.
But additionally the "automatic upgrade" to {Advanced] is needed, if the filter is too complex for [Basic].

**Comment by MagpieFourtyTwo** [comment]
Ok, two guys, one thought ...  ;)

> And just to be sure: there is no global switch wanted to force filter opening to "advanced" at all time?

I in fact don't care how it will be implemented, but I don't want to see the Basic mode at all.
And esp. I don't want to switch from [Basic] to [Advanced] all the time.
I just would like to have a poss. to say "[Advanced] only, please".  ;)

**Comment by Lineflyer** [comment]
> No matter if per global switch or by c:geo simply remembering my last choice (which will be [Advanced] anyway).

Then we are back to: Just remember the last setting and we are fine...are we?

**Comment by MagpieFourtyTwo** [comment]
> Then we are back to: Just remember the last setting and we are fine...are we?

Just for me, this would be perfectly fine, as I wrote: I would like to set it to [Adv] once, and then just forget about it.
But it's different for the guys who want to mainly use [Basic] and just want to (be) switch(ed) to [Adv] if necessary.
For them "use last setting" would not be sufficient, cause after the last filter viewed in [Adv] (because of complexity),
they probably want to go back to [Basic] as default - and they would have to switch manually from [Adv] to [Basic].
At least for these you need global default setting for their default.
Thus why not implement a global setting for the filter default?

> Why not save last setting per filter instead? With this new info it would seem simpler to me in comparison.

Sounds nice, but would IMHO not solve the "problem" of which initial GUI state for a new filter should be shown.
As I already said: I would prefer to *always* and *everywhere* see the same GUI, i. e. *only* see the [Adv] mode.

**Comment by fm-sys** [comment]
> > No matter if per global switch or by c:geo simply remembering my last choice (which will be [Advanced] anyway).
> 
> Then we are back to: Just remember the last setting and we are fine...are we?

That's it. And only change the setting if the user actively toggles the advanced-switch (not on "auto upgrade" because of complexity). That would mean that always this mode is choosen which the user had used the last time anywhere in the app...

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo exactly understood and described the problem a global setting would mean to users who want to switch between basic and advanced sometimes (for whatever reason).

@MagpieFourtyTwo :
If I save the last mode per filter (which, to be honest, I should have probably done right from the start), then this would also mean that users always using advanced mode would always get advanced mode on opening. Only exception: after a fresh install of c:geo when no filters are set at all (but after restoring a backup of Settings this would be gone too). Actually I assume this would be fine for your use case as well?

And as I said before: unfortunately you might have to live through some breaking changes in next week's which might change/delete some existing filter Settings. Because I realized yesterday that the way I put filters to strings (and vice versa) will create problems once we are in production and have to create migration routines on filter changes.

**Comment by fm-sys** [comment]
Ok, then let's implement it as per filter basis (as part of the filter string). 

But still the global `last_selection_preference` is needed. If you delete the filter completely and open the filter UI again without a loaded filter the last global basic/advanced selection should be used as a starting point...

**Comment by MagpieFourtyTwo** [comment]
> [save the last mode per filter]
> I assume this would be fine for your use case as well?

I still don't get how you want to distinguish the default for *new* filters (perhaps with an internal variable? If so, why not even show it in the settings to make it more understandable?), but as long as I *always* get the [Adv] mode, i. e. even on opening the filter dialog while no filter is active, I would of course be fine with it. All I would (strongly) like to avoid is, that users will be confronted with a constantly changing GUI, as this is proven to be a major issue, esp. for non experienced users. And esp. these should not be thrown forth a back, once they have got used to the look of (and what they can safely ignore in) [Adv] mode.

> unfortunately you might have to live through some breaking changes

As I said before: No problem at all, please just don't care for probably existing definitions. This is experimental, and users should be aware of dramatic changes anyway (BTW: swype word recognition first wrote "fantastic" when I wanted to swype "dramatic" - which in fact is way closer to my thoughts WRT the current development :) ).

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo , @Lineflyer you should probably know that there is no such thing as "no filter". If filter is empty, then this is stored as well. So even if you delete/empty a filter (in the GUI), there will be a filter object stored (in the settings) with an empty Filter expression.

The only situation where there is really no filter stored is right after a fresh install without an backups restored.

Much much easier than to handle the new/delete/update stuff explicitly and has the same effect towards the user.

**Comment by MagpieFourtyTwo** [comment]
Ah, understood - fine. Thx for the enlightenment! :)

**Comment by fm-sys** [comment]
Ok, then everything is fine :)

I think we just didn't had enough background information to deside that per-filter is easier to implement and more logical for users. I thought, that per filter would mean that we still have to always switch after resetting the filter.
