### ISSUE TITLE
[BottomSheetDialog] decrease minimum swipe distance

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10720]
> Yes, I know - but there is just one "outside section" left (the one I meant with "the upper end of the screen"), instead of four.
> And esp. the "bottom section", which was clearly preferred by the thumb, is gone.

The problem was that on some devices (e.g. my device) all these four sides were nearly totally obscured by the dialog, so closing via an outside click was nearly impossible. 

But I have struggled with closing the bottom dialog as well (feels a bit like if the dialog wantsq  to stay and always comes back up) 

> Would it be possible to decrease the minimum swipe distance needed to trigger the "close event" ...?

Even though I don't know about it yet, I firmly believe that nothing is impossible... :)

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/10674#issuecomment-846519272_

**Comment by MagpieFourtyTwo** [comment]
> feels a bit like if the dialog wantsq to stay and always comes back up

Yep, that perfectly describes my feeling, until at the end I do a really long (at least felt really long) swipe down to get it closed eventually. 

I'm pretty sure I can get used to it, but it's nevertheless more "effort" than it was before. And things may get "worse" if this type of dialog will replace the popups completely some day. So it would be great if the "close procedure" can be improved in any way (cause otherwise the BottomSheetDialog will bring no advantages over the classic popup at all, but just disadvantages for the bigger screens - apart from a possibly more cool design ;) ).

**Comment by fm-sys** [comment]
Actually, they are supposed to make the UX at large devices easier, as everything inside the dialog can be reached with one hand. 

But you're absolutely right that there is still some space for improvement at the moment (it's still alpha ;-) ), but I'm sure we'll be able to solve these teething troubles...
