### ISSUE TITLE
Material theming: button theming

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10739]
## What function are you missing
One thing yet undecided upon for material theming of c:geo is the look of our buttons. In a first approach implemented with #10643 they are painted in solid accent color, but there are more proposals, and material theming differentiates a bit more granular. So one step further would be to adapt this.

## Suggested solution
For ongoing discussion please see the following comments and links:
- https://github.com/cgeo/cgeo/pull/10643#issuecomment-847096793
- https://material.io/components/buttons
- https://github.com/cgeo/cgeo/pull/10643#issuecomment-847112527

**Comment by fm-sys** [comment]
Just a quick note: material.io suggests to use only one "high emphasis" button max at once. All other should be of a lower level.

I would suggest to set "medium emphasis" as default style for all buttons (AFAIK this is possible via the theme). All situations where we want to have a different button style / emphasis level can be edited manually afterwards (but this will just be the minority of all buttons).

**Comment by moving-bits** [comment]
Is there a way to apply "Outlined Button `style="?attr/materialButtonOutlinedStyle"`" to our style `button` (so that we don't have to rewrite all of our buttons, and so that all the derived button classes can inherit from this?

**Comment by fm-sys** [comment]
I think so, but I can't tell you how - need to try it myself...

**Comment by Lineflyer** [comment]
The current orange buttons (text buttons as well as icon backgrounds) are really too much (or too extensively used).

Posting again the pictures @fm-sys posted in the original issue/PR:

![grafik](https://user-images.githubusercontent.com/949669/119615287-83c57c80-bdff-11eb-8fa3-8a342865977e.png)

1. Text button (low emphasis)
Text buttons are typically used for less important actions.

2. Outlined Button (medium emphasis)
Outlined buttons are used for more emphasis than text buttons due to the stroke.

3. Contained button (high emphasis)
Contained buttons have more emphasis, as they use a color fill and shadow.

4. Toggle button
Toggle buttons group a set of actions using layout and spacing. They’re used less often than other button types.

I think we should rather use type 2 as kind of standard (where we currently use type 3) and only rarely use type 3 if at all.

**Comment by fm-sys** [comment]
Already working on it. PR will follow today or tomorrow...

**Comment by UniQP** [comment]
Can we change the button style of a whole dialog instead of changing the style for every button of the dialog?

**Comment by eddiemuc** [comment]
Is it an option to set the button style for whole app but then set an explicit different style for alert Dialogs? The later might be doable on one central place in our `Dialogs` class.

**Comment by Lineflyer** [comment]
I am wondering if its intentional (or just coincidence) that the button background is same as the background itself. Or are they always transparent with this style?

**Comment by fm-sys** [comment]
"outlined" is really just text and an outline. I think this is ok, but we can adapt it for sure...
