### ISSUE TITLE
Material theming: Cache details - Unify text size

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10759]
The cache details view still has rather small text. I guess it needs to be adapted to make use of the overall defined text size.

Maybe for the list in the first section it might be wise to use different text styles for label (e.g. name, type, size, etc.) and content.

Text color is another thing, but here we should wait until the background is fixed to see how it looks like.
![grafik](https://user-images.githubusercontent.com/949669/119659163-357ba200-be2e-11eb-8f5b-9d3d270eadd7.png)

**Comment by moving-bits** [comment]
Do you mean the text in the upper half of the screenshot ("Name: Endlich Feierabend", "Typ: Traditional Cache" etc.)?

I've set that to the smaller text size variant (`detailsSecondary`) deliberately, because it's very detailed info of secondary importance (IMHO), and it's so much text, which will probably lead to other options further down being moved out of the screen.

But that could be changed easily, for sure.

Regarding "different styles for label and content" - what styles would you prefer? Labels in small, and text somewhat larger? (meaning `detailsSecondary` for the labels and `detailsPrimary` for the text)

**Comment by Lineflyer** [comment]
Yes, I mean the upper half. Thats looks so crowded and we already discussed making the fonts bigger in general (which is already the fact on the lists but not at this screen).
I do consider this information not of secondary importance: These are the details of an geocache, which has same or maybe even more importance as the description.

I am not sure about the text sizes you mention.
My thinking was:
As we do not have any separator (like `:`) we could visually differentiate by different text styles. I thought about label in bold, text not in bold (in my easy thinking).

But feel free to just try your approach. The problem in discussing theming is, that it cacn hardly be decided in theory without seeing the result. So lets try something iterative here...or maybe you can post a selection of possible combinations here and we can decide upon that.

**Comment by moving-bits** [comment]
Would adding a ":" after the label work?
Or placing a thin divider line between labels and content?

With "secondary" I tried to express that this is pretty much (too much) information to be all of same importance. (But I guess, the hard point is that this may vary from user to user and may depend on the specific situation.) So let's increase text size by using the `detailsPrimary` definition. - BTW: You can see what's behind those dimensions if you look at the `value/dimens.xml` file. You'll find a short description and the specific text sizes there.

Additional idea:
As this is quite a bit of info taking up many lines - how about putting that info into a more compact format?
E. g.: put type and size in the same line, coords and distance in the same line etc.

**Comment by moving-bits** [comment]
Using the larger textSize and a colon as divider, the details view could look like this:

![image](https://user-images.githubusercontent.com/3754370/119894556-043dc780-bf3d-11eb-8dff-e805ecf0e3ca.png)

Be aware: I needed to enlarge the label column to avoid truncation of some labels. This reduces the space for content.

**Comment by fm-sys** [comment]
What about using the "|" character or even a vertical separator line?

**Comment by Lineflyer** [comment]
Maybe one more space would be sufficient for a better visual separation?

BTW:
In light theme the text has IMHO less contrast as we seem to use(?) the same text color as on dark theme. It should be darker on light theme if feasible.

**Comment by Lineflyer** [comment]
> Be aware: I needed to enlarge the label column to avoid truncation of some labels. This reduces the space for content.

Thats a valid point. We should also always think about different string lengths in different translations. IMHO whereever possible we should therefore handle this gracefully (e.g. by allowing line breaks). In the past we had some issue of translations not fitting into the view and being truncated with `...`.
Alternatively we can set a maximum length on Crowdin for each string (AFAIK manually) but I consider this a bad working mode as it potentially forces translators to start abbreviating the string making it hard to understand.

**Comment by MagpieFourtyTwo** [comment]
As for me the font size of the ``Details`` page is perfectly fine. Even the horizontal separation between labels and text is IMHO ok. As the Labels are right aligned, the grouping is pretty obvious to me. And the more space in between is wasted, the less info can be displayed.

What bothers me way more is the high count of different font sizes, which make it hard to read, as the eye has always to adapt instead of being able to get used to one size. Gives in fact an inconsistent and untidy feeling.

My opinion (all with theme "dark"):
- ``Main menu``: Font size of icon texts is slightly bigger than in ``Details``,
    but this is pretty ok for me, as the words would get lost with a smaller font
    So let's take the icon texts as reference for now and let's call it "Medium"
- ``Main menu`` => ``Search`` (via magnifying glass): has bigger font - I would prefer a smaller one, maybe the same as the icon texts (=> Medium for the title, Small for the GC code) 
- ``Main menu`` => ``Search`` (via icon): has bigger font - I would prefer Medium for all over here
    (BTW: it's really hard to separate between the different points and to identify the action buttons as buttons)
- ``Main menu`` => Cache list via ``Stored`` or ``NearBy``: WAY bigger font 
    Cache Name should not be bigger than the icon texts (i. e. Med), list of Lists should be Small
- ``Details`` Header: Seems to be fine, I would call it "Big", although it could even be smaller, to fit more text
    visibility will still be given, as it's bold, anyway
- ``Details`` itself: current font size (= "Small") is pretty fine for me, esp. WRT to the info amount
    I would BTW take this (i. e. Small) as reference and adapt it acc. to Android's system settings of font and symbol size)
- ``Details`` => ``Pick Lists``: font is bigger - should be smaller, i. e. Medium (and, BTW, the line spacing is too wide, either)
- ``Details`` => ``Personal Note``: Should be the same font as ``Details`` (because of the amount of text, thus Size 1)
- ``Waypoints``: is WAY bigger than ``Details``, should be Size 2 for WP name and Size 1 for the note
- ``Waypoints`` => ``Add``: Font seems to be ok, but Line spacing is way too wide
- ``Waypoints`` => long click menu: Line spacing is too wide
    BTW: although the popup does not use the general background color (which is perfetly fine for me)
    the contrast is way better over there, this popup is way easier to read than e. g. ``Details`` and ``Description`` page
- ``Logbook``: Owner name should be Size 2 (like the other headings), the log text itself same size as in ``Details``, thus Size 1
- ``Logbook`` => long click menu: Icons are a little bit to big and line spacing too wide
- ``Lists`` => Menu: Line spacing is too wide, but contrast is perfect, I would love to see this contrast in the rest of the app
- ``Lists`` => Menu => ``Sort``: Way too wide line spacing
- ``Lists`` => Menu => ``New filter system``: Way too wide line spacing, either, Header font too big (should be 2, subtexts 1)

In general, font sizes should a) take Android's setting into account and b) not change too much between connected actions. Moreover same stuff should have same size (e. g. all lists the same size, all pick lists same size etc. pp.)

As this the above is just my first impression (and became way more than I expected ;) ), it may not be complete and even be inconsistent in some points, but I hope you got my idea. ;)

**Comment by moving-bits** [comment]
> BTW:
> In light theme the text has IMHO less contrast as we seem to use(?) the same text color as on dark theme. It should be darker on light theme if feasible.

Fixed many of those places in #10785, but there may be more.

**Comment by moving-bits** [comment]
Regarding the font sizes: We are currently using the following set of font sizes throughout the app:
- regular text: 16sp (primary info) / 14sp (secondary info) - called `detailsPrimary` or `detailsSecondary`
- lists: 20sp (primary info) / 16sp (secondary info) - called `listsPrimary` or `listsSecondary`
- headings: 20sp (primary) / 18sp (secondary) - called `headingsPrimary` or `headingsSecondary`
- toolbar: 20sp (if single line) / 18sp/16sp (if two lines) - called `toolbarSingle`, `toolbarPrimary` or `toolbarSecondary`

@MagpieFourtyTwo 
Can you try to assign above's names to your findings?

**Comment by MagpieFourtyTwo** [comment]
Tried to assign the font sizes, but gloriously failed - I can not really see a clear line here ...
E. g. lists are using different font sizes: If you are in a list and open the drop down to change to an other list, their two sizes are most definitely different from the sizes, you see, when selecting a list from the main menu (by long click on [Stored]).
So, I guess, at first the font sizes used inside of the app need to be synchronized.

Nevertheless, *all* of the font sizes are bigger than the font sizes of *all* the other apps. They should get smaller ... *all(!)* of them.
Resp. should take Android's font and symbol size settings into account ...
Just have a look at the list of caches and the details page, compared to the fonts in GCC, which should be pretty well known, too.
Perhaps you get an impression of what I mean ...

The names of the codes in GCC represent the "normal" font size on my phone.
And this is the "standard" size (i. e. Medium) of all apps. c:geo's fonts are kind of striking, compared to these ...

![Font Sizes cgeo List](https://user-images.githubusercontent.com/9889015/120086493-bdd49e00-c0df-11eb-8cd4-c73db24180f7.jpg) ![Font Sizes GCC](https://user-images.githubusercontent.com/9889015/120086498-c4fbac00-c0df-11eb-80fa-27cebde00d3f.jpg) ![Font Sizes cgeo Details](https://user-images.githubusercontent.com/9889015/120086502-c927c980-c0df-11eb-9e67-49c46f97824f.jpg)

**Comment by MagpieFourtyTwo** [comment]
And perhaps a second comparison of the two lists of Lists I mentioned before:

Left: Pick a list from main - right: Pick a list from a list:

![Pick a list - Main](https://user-images.githubusercontent.com/9889015/120086776-32104100-c0e2-11eb-8354-58715cb4e3b7.jpg) ![Pick a list - List](https://user-images.githubusercontent.com/9889015/120086780-36d4f500-c0e2-11eb-9c65-7232c4e89dfb.jpg)

Additionally: While on the right there is no visible separation between entries, the line width in the left is way too wide
And although the left does not use the fine black (like it), I like the grey better for opening menus and popups (this way they are better distinguishable from the rest around resp. behind).

**Comment by Lineflyer** [comment]
The text sizes of many dialogs in c:geo are not yet aligned between each other. Lets please wait until we follow the upcoming design on all screens and dialogs. This is work in progress.

Only after that, you can really judge it and it much more easy to change it as a central change will change it all over the place, as we just define 2-3 default sizes which will be applied at all places.
Furthermore it should already be adaptive to your system font sizes settings (or will be once we are ready).

However there might be a lot of bugs and also a lot of decisions open to choose an appropriate text size for all parts of c:geo. But again, currently only "half of the app" is using the new styles. We need to finish that first.

And please:
Feel free to open dedicated issues for specific new topics rather than commenting on an closed issue for a specific cache detail problem.

Last but not least:
GCC might be a really bad example, as it is even older and more "broken" from style perspective as c:geo ever was.

**Comment by moving-bits** [comment]
Thanks @MagpieFourtyTwo for your reply. Let me give you some additional context information:
- c:geo is a software "grown" over ten years, with changing devs, and not all devs having UX in mind (or experience with it). And you can see the results from this in c:geo's UI. I'm far from judging this, it's simply an observation (and I have been part of it over the last years). 
- So a general overhaul is urgently needed. We've started several approaches in doing so over the last ten years, even came to some wire frames or screenshots, but never got into actual coding for it in broadth and depth needed for it. 
- Currently we started a somewhat lighter approach, both in terms of components and theming. We've made quite a bit of progress over the last months - have a look at the new filter approach, theming for activities or the new about pages, to name a few. But it's still quite some way to go. Especially all dialogs are pretty much untouched yet (we have been very creative in the past regarding dialogs ;-)), which covers some of your experiences described above. The should use same font sizes, same background color etc.
- Regarding the font sizes: c:geo had been using way too small font sizes wrt to today's UX approaches, so it was one goal explicitly, to increase font sizes. Only a bit, e. g. from 12sp to 14sp, but nevertheless. BTW: They should react to Android's font size settings in both current released version and in current nightlies.

Feel free to test and share your observations along the way (much appreciated!), but keep in mind the current state (what's been touched already and what it still work in progress), and please open separate issues for those, to make tracking for us doable. Thanks.

**Comment by MagpieFourtyTwo** [comment]
> The text sizes of many dialogs in c:geo are not yet aligned between each other. Lets please wait until we follow the upcoming design on all screens and dialogs. This is work in progress.

My idea was, if we are talking about text sizes anyway, this can perhaps be done in one go. Most obviously I was wrong.  ;)
And, yes, I am very well aware of "historical growth" and "backpack programming", as these "principles" are in fact two of the biggest problems in my daily work.  :/

> GCC might be a really bad example, as it is even older and more "broken" from style perspective as c:geo ever was.

Sorry, maybe I did not make clear enough what I wanted to show, but in fact you missed the point completely.
This was not meant to be an example for font handling, but just a simple comparison of sizes.

I could have even sent a screenshot of my home screen, too - which in fact would have been even more impressive, as e. g. the font c:geo currently uses for cache lists, is 50 % bigger than the one icons use on Android's home screen - like these, which both have not been resized, they're just cropped:

![SC Homescreen](https://user-images.githubusercontent.com/9889015/120177299-94636180-c208-11eb-874d-72bd312ca7cc.jpg)  ![SC cgeo List](https://user-images.githubusercontent.com/9889015/120177336-a04f2380-c208-11eb-8231-4d11546343bc.jpg)

While Android's "e" is 20 pixels high, the name of the cache (taken from a List of caches) has 30 pixels in height.
And seeing this, you may understand why I was in doubt that c:geo really looks for Android's system settings.
And why I was a bit scared when I read, fonts should grow even more.  ;)

But in fact, c:geo's font sizes seem to be chosen locally (and kind of randomly) at the moment, instead of using a centralized size calculation, which of course makes it way harder to change and synchronize to use proper sizes.

BTW: When inventing a centralized font determination, are there plans to centralize e. g. line spacings, too? As these are (apart from beeing too wide, in the most places, anyway) very different, too.
