### ISSUE TITLE
Improve cache title in map popup

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10750]
## What function are you missing

A user on support mail compared the map popup information between the official app and c:geo and noticed improvement potential as follows:
On longer caches names c:geo tends to cut off the cache title in the map popup. The official app does this better (see screenshots below). This is even more important if you have a series of caches where the number is only mentioned at the end. You are not able to see, whether you selected the correct cache.

c:geo - Cache name truncated:
![grafik](https://user-images.githubusercontent.com/949669/119452236-67114200-bd36-11eb-9971-9f653246f663.png)

Official app - Cache name complete:

![grafik](https://user-images.githubusercontent.com/949669/119452140-4ba63700-bd36-11eb-8d41-ee4bbd33c90c.png)

## Suggested solution

Can potentially be solved during the current redesign (e.g. by using a bottom sheet or another style element)

## Alternatives/workarounds

Resize text (not so good) or make it scrolling (even worse)

## Additional context

Same truncated style in target name on map:
![grafik](https://user-images.githubusercontent.com/949669/119452512-c0797100-bd36-11eb-8c96-05df47c8ee73.png)

**Comment by moving-bits** [comment]
IIRC @jonas-koeritz once had started with a similar implementation, replacing our cache/waypoint popup with some fragment at the map's bottom.

@jonas-koeritz 
Do you remember which issue number this has been? And more important: Do you have plans (and time) to continue that work? I remember it had been looking very promising already... ;-)

FYI: We've modernized a few things around the technical aspects of the GUI lately, e. g. using `AppCompactActivity` and just a handful of well-defined themes based on `MaterialComponents` instead of our grown mix of different activity types, styles and themes. Maybe that's become a better starting place (wrt to technical aspects) compared to the time you'd started working on that aspect.

**Comment by jonas-koeritz** [comment]
I don't know the exact issue of the top off my head right now but i will have a look and reference it here. I could start and do more work into that direction. The main problem has been the rather tight coupling between the cgeo database and nearly every component of the app, which lead to my efforts of refactoring the backend, which have not concluded to this day.

In my opinion we should push towards a clean MVC/MVVC structure to make implementation of new views/fragments easier. Especially the cache details popup is a kind of messy implementation that relies on direct database and network access. It's elegantly done and reuses code from the details page of the cache details activity, but there is room for simplification and decoupling.

I think we should create a 10000ft view of what the data flow and source of truth structure in c:geo should look like and which technologies we want to use, so that everybody can do their part, not just me, aimlessly hacking on a room database. What do you think?

**Comment by moving-bits** [comment]
Hi @jonas-koeritz, thanks for replying so fast, and welcome back!

While I do understand and appreciate your approach for a clean way of storing the data, I fear that might me a too-big task to couple moving data storage to Room together with all the layout-related things like using fragments instead of popups. 

If I look through c:geo issue history, I think there has been something similar: There are a couple of approaches to modernizing the GUI, starting with "a big picture", which has been fine by itself, but too big to being implemented with a small team of developers doing that work in their spare time. That's why we started the most recent approach to our GUI in smaller steps, beginning with unifying the used activity types first, then unifying themes, starting to use new components along the way etc. This makes things easier to handle from a technical perspective, and allows more GUI work being done by the whole team, building upon that base.

Thus I would propose - if technically feasible, which I have no idea of, admittedly - to break things down into smaller parts. From a user's perspective I would start with the GUI related things (like using a fragment at the map's bottom instead of a popup, to start with a specific example), which have a direct benefit for the end-user, and throw in the technical internals along the way as needed.

Or, if some technical fundamentals have to be done first, do them in one block, in maximum compressed time possible, and by the smallest team possible, to reduce dependencies in code, people or PR, the timespan of having things doubled in code, or having to rebase and resolve merge conflicts etc.

**Comment by jonas-koeritz** [comment]
I'm sure I can reuse some of my demo code for a bottom sheet cache popup and just reuse the views from the current implementation to get some kind of redesigned, but not reinvented implementation going.

Creating a ViewController and repository implementation based on the current backend could be feasible as well and may be done in separated steps as well.

**Comment by fm-sys** [comment]
The issue number for cache details BottomSheetPopup was  #3932 / #8057.

**Comment by fm-sys** [comment]
> Especially the cache details popup is a kind of messy implementation that relies on direct database and network access.

I have looked into the code as well, and there are some really wearied network implementations. But could it be that this is just a relict of the past?

The popup had to load online data for GC years ago, before we moved to the new live map API. For GC we definitely don't deen this networking stuff anymore. But is there any other connector using it or can we remove the networking out of the popup? I guess this could simplify the implementation a lot...

**Comment by jonas-koeritz** [comment]
Okay, my main takeaways from the old thread are:

- we need to decide on a way to mark the currently selected cache, as the popup was modal and the bottom sheet won't be blocking the map that much
- we need to decide what the various expansion levels of the bottom sheet should contain, keep in mind that a transition from the bottom sheet to the full blown cache detail activity isn't easily possible (yet), this would be my favorite "target", drag up fully to reveal the complete cache details UI. Leaves us with two / three states to consider first: collapsed (No info at all, should it be visible at all?), Peeking (just basic info/actions), partly expanded (more info / actions)

**Comment by jonas-koeritz** [comment]
> > Especially the cache details popup is a kind of messy implementation that relies on direct database and network access.
> 
> I have looked into the code as well, and there are some really wearied network implementations. But could it be that this is just a relict of the past?
> 
> The popup had to load online data for GC years ago, before we moved to the new live map API. For GC we definitely don't deen this networking stuff anymore. But is there any other connector using it or can we remove the networking out of the popup? I guess this could simplify the implementation a lot...

I'd like to try out the approach I described earlier with this, where I do the ViewModel/ViewController and Repository part of a reworked architecture based on our current backend. While writing that, I will reconsider what we actually need to fetch from which sources.

**Comment by MagpieFourtyTwo** [comment]
Am I wrong or is this already "fixed" resp. changed, at least in the current nightly?
If I click on a map icon, I (additionally) get the full name in the very first row of the cache info (now?) ...

![Screenshot_20210602_113248_cgeo geocaching](https://user-images.githubusercontent.com/9889015/120457115-7deb1080-c396-11eb-9688-f37a62a24932.jpg)

**Comment by Lineflyer** [comment]
Yes, its solved.
