### ISSUE TITLE
Reduce line spacing in map quick settings

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10809]
With these (very welcome) additional entries (thx a lot!) the Quick settings menu got significantly longer ... and now it does not completely open up on first click anymore, so even on large screens an additional swipe up is needed now. Moreover it's kind of hard to reach the uppermost entries.

So, would it be possible do decrease the line spacing?  E. g. like shown below?

Left: State after click on Quick settings icon - Middle: Fully opened after swipe up - Right: Initial state with decreased line spacing

![Quick settings](https://user-images.githubusercontent.com/9889015/120248983-9ca7b500-c279-11eb-9956-e553ff9e5374.jpg)

If this will come with layout overhaul anyway, just forget about my question.  ;)

_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/10784#issuecomment-851718113_

**Comment by eddiemuc** [comment]
In #10287 I also proposed to change layout to a two-column-layout. Only problem is that the logical grouping of options (cache filters vs. waypoint filters vs. "circles") somehow leads to "groups" with "uneven" counts which looks maybe a bit strange in layout. Here is the original proposal:


| Caches to show : | |
| ----------------|------------------|
| Found | own |
| Disabled | archived|
| caches with offline logs | Circles |
| Waypoints to show; | |
| Original | parking | 
| visited | |
| Use compact icons | |
... (unchanged)

Would that be an alternative?

**Comment by Lineflyer** [comment]
Maybe:

| Caches to show : | |
| ----------------|------------------|
| Found | Own |
| Disabled | Archived|
| Caches with offline logs |   |
| Waypoints to show; | |
| Original | Parking | 
| Visited | |
| Other: |  |
| Use compact icons | |
| Show circles  | |
... (unchanged)

**Comment by MagpieFourtyTwo** [comment]
As for me: I'm a friend of two column layout, anyway, already proposed it in the very first discussions about a Quick settings menu.
But IIRC there were concerns because of a potential risk of horizontal scrolling.

OTOH:
- ``[Caches with offline logs]`` is already longer than
- ``[Disabled] _ [Archived]`` anyway.  ;)

IMO longer stuff like ``with offline logs`` (as it would be in the sub category ``Caches`` anyway, the phrase "Caches" can safely be dropped) may go into an own row, like @Lineflyer already suggested.

And perhaps we'll even find some extra room for the two elsewhere mentioned, IMO not vitally important (at least in Quick settings), but even in the new filter system still missing stored states
- ``Show caches stored``
``[offline]`` _ ``[not offline]``

which should reflect "only show if stored" vs. "only show if not stored yet" resp. "show all", if both are activated?

BTW: Did you mean to implement ``Use compact icons`` as toggle too? Would not work IMHO, cause it has three states.

**Comment by eddiemuc** [comment]
Had another idea which would reduce vertical space needs drastically: use two-column layout, place "cache" filters in left column and "waypoint" and "other" in right column. E.g. like this:

| Caches to show: | Waypoints to show: |
| ----------------|------------------|
| Found | Original |
| Own | Parking |
| Disabled | Visited |
| Archived | Other:
| With Offline Logs | Show Circles |
... (rest unchanged, "use compact icons" and "Routing")

**Comment by MagpieFourtyTwo** [comment]
Sounds good, too, although I guess, vertical space is not the major issue anymore, once line spacing is decreased.
And WRT horizontal space: When putting all criteria of one type in one column, the column width is fixed by the longest one.
There's no way to do some creative "column spanning" for the longest entry, like e. g. ``with Offline logs`` and ``Show Circles``.

But, this should be up to the guys with slim displays, they should make their statement first.  ;)

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo 

> ... but even in the new filter system still missing stored states
> 
> * `Show caches stored`
>   `[offline]` _ `[not offline]`
> 
> which should reflect "only show if stored" vs. "only show if not stored yet" resp. "show all", if both are activated?

Am I guessing correctly that you would like to have this in new filter as a third "three-option-toggle" in status filter? (so there would be "All"-"Only not Stored"-"Only Stored" next to "All"-"Only not found"-"Only Found" and "All"-"Only not owned"-"Only owned")?
Would it be ok to open a separate issue for this?

**Comment by eddiemuc** [comment]
> Sounds good, too, although I guess, vertical space is not the major issue anymore, once line spacing is decreased.

Ok let's wait for line space decreasement then. Note that since @moving-bits and @fm-sys are very engaged with the overall parts of the c:geo layout right now, which I guess this is a part of. And I corrently don't want to get "in their way" by playing around with line spacing outside of their valuable work.

**Comment by moving-bits** [comment]
Regarding the line spacing: 

While I understand (and share) the concern of the dialog getting way too long, I would not try to tackle this from the line spacing point. Line spacing has a reason, it's there to make the UI usable in a not too picky way. If it gets too fiddly, the advantage of having quick settings gets lost easily and probably turns into frustration if you hit the wrong setting too frequently. It may be ok for many people, but not all of our users have such fine granular movements (any more).

So I would deeply prefer the two column approach. Whether cache options and waypoint options are arranged vertically or horizontally is mostly a matter of taste, IMHO, as long as it's clear to understand what belongs to what.

**Comment by fm-sys** [comment]
I think the spacing could indeed be reduced not too much for sure but at least a bit. But you're right that we should try to not spam all our layout files with random margin definitions but should rather define such things in the global cgeo theme...

**Comment by moving-bits** [comment]
One additional question, not related to line spacing:

Do we really need to have a "with offline logs" option? I cannot think of any use case where I explicitly want to check for caches having offline logs - on the map. I would see this as one of the many filter options (and maybe use it in cache lists to have a look for caches where the log needs to be uploaded yet).

If this is about "has offline log = is found, and I want to exclude my finds from the map": Why don't we treat found caches and caches with "has offline found log" the same (for the map)? (But this probably has some performance penalty)

Or different approach: Make the map quick settings menu configurable, so that every user can include/exclude the options they like to.

**Comment by Lineflyer** [comment]
> If this is about "has offline log = is found, and I want to exclude my finds from the map": Why don't we treat found caches and caches with "has offline found log" the same (for the map)? (But this probably has some performance penalty)

Thats a good point.
I don't know where the request for "has offline logs" originated from, but I think its a very special case...I could live without that.

We should not treat "has offline log" same as "found" IMHO. This is currently not the case and I think this is quite a reasonable approach as there is still something to do until they are really found.
If I e.g. go out for caching I would like to hide the found caches but while taking my route and offline logging cache its helpful to see which caches I already visited and - at the end - see my "todays work".

Regarding the request for a "stored" filter: Is this really needed. If I just want to see stored caches I can map my list (or disable the live mode).

BTW:
We are again mixing topics. Wasn't this issue originally only about "reducing the line space"?

**Comment by Lineflyer** [comment]
>  Or different approach: Make the map quick settings menu configurable, so that every user can include/exclude the options they like to.

We should IMHO avoid that. We already have too many settings and customization options for such "minor" things.

**Comment by MagpieFourtyTwo** [comment]
> Line spacing has a reason, it's there to make the UI usable in a not too picky way.

Yep, that's clear - but too much space turns usability right into the complete opposite.

Which is most definitely the case, when the large amount of wasted space forces you to scroll, like it is here (and in some other places in the app, too, like in the ``Pick the lists`` popup, where you have to perform additional scrolls due to exaggerated and usability killing line spacing). And it's definitely wasted, as this "safety space" takes two times the height of the text row itself ...

I of course can follow the "usability argument", but, sorry, if you need a row which has *five* times the height of the check box, cause you can not check a box which has e. g. "just" twice the height of the text, you will most probably not be able to use this app (or any other) anyway. Cause then you will e. g. not even be able to hit one of these map icons, which BTW have nearly exactly the size of these check boxes. And these have no "safety spacing" at all. Following your argument, you would have to make these icons at least twice their size ... do you really want to do so? ;)

**Comment by eddiemuc** [comment]
@Lineflyer @moving-bits 

> > If this is about "has offline log = is found, and I want to exclude my finds from the map": Why don't we treat found caches and caches with "has offline found log" the same (for the map)? (But this probably has some performance penalty)
> 
> Thats a good point.
> I don't know where the request for "has offline logs" originated from, but I think its a very special case...I could live without that.

This was requested by @magpiefourtytwo in #10287. There was no protest, and it fitted well in implementing own/found separation.

**Comment by MagpieFourtyTwo** [comment]
Background was, if you're on a longer tour, or even on a power trail (which is in fact not my style of caching, but, hey, the "needs" of these guys should be taken into account too, I guess) it would be great to be able to temporarily hide caches with offline logs, in order to declutter the map.

IMO this wish is a perfectly valid one, as "offline logged" is in fact a third state in between of "not found" and "found".
But currently they are effectively treated as "not found" which is in fact as wrong as to name them "found".
Thus a third state (and appropriate filter) seems to be a reasonable request.

However - as meanwhile we have the great new filter system, this may even be better implemented as a filter, thus it is IMO not an absolute must for the Quick settings (anymore).

Nevertheless, @Lineflyer is of course right: This is a completely different feature request, thus it should go in an extra issue.

**Comment by moving-bits** [comment]
> > If this is about "has offline log = is found, and I want to exclude my finds from the map": Why don't we treat found caches and caches with "has offline found log" the same (for the map)? (But this probably has some performance penalty)
> 
> Thats a good point.
> I don't know where the request for "has offline logs" originated from, but I think its a very special case...I could live without that.
> 
> We should not treat "has offline log" same as "found" IMHO. This is currently not the case and I think this is quite a reasonable approach as there is still something to do until they are really found.

I was only talking about map display for this, as I think the request for this switch came from "I've been there, let's hide this cache to not clutter the map" - and with this target in mind, the could be treated the same as "found" caches on the map.
Cache lists are a different story, though, and I would not mix it there.

OTOH, I agree, that this differentiation may lead to confusion, so maybe it's better to find a good solution where this additional filter fits in well without taking too much space, or to leave it out.

> If I e.g. go out for caching I would like to hide the found caches but while taking my route and offline logging cache its helpful to see which caches I already visited and - at the end - see my "todays work".

I know it's a bit off-topic, just wanted to share my approach for this:
- When I'm out in the field, I do no logging, neither offline nor online, so a "has offline log" would not help me. 
- But I have a "visited" list, which has a symbol assigned to it, and every cache I've visited on my tour gets assigned to this list, and by this gets a visual indicator on the map.
- This also helps when I'm back at home, because I can easily see in my "visited" list, which caches need to be logged yet. After logging they get moved to my "archived" list, so that the "visited" list is empty again.

**Comment by moving-bits** [comment]
see #10822 for a reduced line spacing

**Comment by MagpieFourtyTwo** [comment]
Thx! Look and Handling are *way* better!
Any chance to get the line spacing of ``Pick the list`` (opens via the edit icon in cache details page or cache popup) reduced, too?
If so, I would open a new issue for it ...

**Comment by moving-bits** [comment]
I've finally found a way to reduce line spacing in this list as well, see #10838.

**Comment by MagpieFourtyTwo** [comment]
Looking at [your screenshot](https://user-images.githubusercontent.com/3754370/120710416-660eac00-c4be-11eb-8b9d-b34ce2e4fd72.png) I first wondered where the check boxes had gone ...
Until I noticed that indeed there is a third ``Pick a list`` dialog.  ;)
Now, I'm curious to see if your changes have an effect on these with check boxes as well.  ;)
However - thx a lot for your efforts! UI design has gained quite a lot back since the first "material approach".
And I really hope you keep at it, cause there is still a lot of room for improvement ... :)

**Comment by moving-bits** [comment]
> Now, I'm curious to see if your changes have an effect on these with check boxes as well. ;)

Here are screenshots of the other two "pick a list" occurrences:

![image](https://user-images.githubusercontent.com/3754370/120820987-568e7200-c555-11eb-957c-3055f48832a9.png).
![image](https://user-images.githubusercontent.com/3754370/120821023-6017da00-c555-11eb-8f8e-94c1b0fd1c51.png)

Dialog colors are not yet compliant here, but that's a different story (which has to do with individual layouts put into a dialog, and the material lib seemingly ignoring our global styles in that case - needs to be investigated further).

> However - thx a lot for your efforts! UI design has gained quite a lot back since the first "material approach".
> And I really hope you keep at it, cause there is still a lot of room for improvement ... :)

Our current "material approach" is much about visual consistency (same type of things should look similar) and about upgrading the internal technical details (most of that part not visible in the UI). AFAICS the current state on `master` is quite usable and much more consistent than our current official release, but I may be missing some things. Therefore it would help me a lot, if you could provide screenshots of things you regard as unusable or badly designed (all from a UX perspective) - this would make discussion of whether and how to change this easier. Thx a lot for your constant support in testing things!

**Comment by MagpieFourtyTwo** [comment]
Looks really promising.
Have some places where fonts are still strange,
will post a collection as soon as I'm at home again.
Currently we're out in the wild, for some real life testing ... ;)
