### ISSUE TITLE
Add possibility to clear input in text edit field

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#10885]
## What function are you missing

For some input fields, it would be nice to have an easy possibility to clear the (default) text - e.g. default coordinates in input for plain format in calculator (normally I want to paste the formula from clipboard), default name for new waypoints, ...

## Suggested solution

Would it be possible with the new material-theme to add a clear button?
![20210607_232628.jpg](https://user-images.githubusercontent.com/70113341/121090498-f879bd00-c7e8-11eb-8cc3-3ee5af5f99df.jpg)

**Comment by fm-sys** [comment]
Alternative solution would be to select the whole text when the input fields gets clicked...

**Comment by murggel** [comment]
My hope would be, introducing / using the textInputField #10763 comes probably with a configuration for a clear button.

https://material.io/components/text-fields/android#using-text-fields

But I did not step deeper into it...

**Comment by eddiemuc** [comment]
Material.io do indeed come with a standard clear option, and I think it would be a great idea to use them in c:geo in many places

**Comment by eddiemuc** [comment]
@murggel Material.io supports something like this:
![image](https://user-images.githubusercontent.com/6909759/121130460-b7a49700-c82e-11eb-8029-0888a7c1ea12.png)
(this is not an outlined text input field like I assume we want to use, but it shows the "clear" icon used by material.io).

Is this what you have in mind?

**Comment by murggel** [comment]
> @murggel Material.io supports something like this:
> ![image](https://user-images.githubusercontent.com/6909759/121130460-b7a49700-c82e-11eb-8029-0888a7c1ea12.png)
> (this is not an outlined text input field like I assume we want to use, but it shows the "clear" icon used by material.io).
> 
> Is this what you have in mind?

Exactly. I was looking for something like that.

Do we have to change than all the fields or what do you mean with "this is not an outlined text input field like I assume we want to use"?

**Comment by eddiemuc** [comment]
> Do we have to change than all the fields or what do you mean with "this is not an outlined text input field like I assume we want to use"?

As far as I understand, then in  #10763 we want to change all text input fields to material.io (which uses com.google.android.material.textfield.TextInputLayout and inner EditText views). So I fear we have to exchange all text input fields in c:geo in this issue. But maybe not in a single go but one after the other...

Material.io supports different "text input styles" out-of-the-box, mainly "Filled text fields" and "outlined text fields". The screenshot above is from a "Filled text field", while I concluded from the screenshot used in #10763 that we want to use "Outlined Text fields".

Since I had to change the text input fields for filter searches last days anyway, I already replaced the "Search Text" input fields with a material.io variant. Just now I added the "clear button" to it (PR is running). See screenshot below (this shows not the "Outlined text field" together with a clear button). Works like a charm! Like it :-)

The definition of the material.io text input field is done in layout file `cache_filter_generic_string.xml` if you want to take a look. To get the "clear" button, I simply had to change the `app:endIconMode` from `none` to `clear_text`


![image](https://user-images.githubusercontent.com/6909759/121137722-3ef60880-c837-11eb-974d-7d25908db980.png)

**Comment by fm-sys** [comment]
Yes, the "Outlined text field" version (like you have already used) IMHO is the way to go as it fits way better to the general c:geo style...

**Comment by moving-bits** [comment]
I think we can close this issue. We have added the `clear_text` to our default `TextInputLayout` styles, so when we migrate the remaining input dialogs (which is a different issue) to use `TextInputLayout` this gets added automatically.
