### ISSUE TITLE
Empty cache details view is already shown while downloading cache 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10900]
> And a last quick feedback for today:
> 
>     * Select Nearby
> 
>     * Click on a cache from the result list
> 
> 
> It seems the cache details view is already shown (empty) in the background while the cache is loaded.
> You see some lines and empty elements in the background behind the download progress dialog.

This looks indeed strange, but I can reproduce the issue with our current nightly... 

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/10899#issuecomment-859267898_

**Comment by moving-bits** [comment]
Not sure, but this may be due to migration of cache & trackable pages to viewpager2/material tabs with #10865:

Cache details are not available immediately, so drawing the details page for the first time will give you a near-empty "skeleton", to be replaced on receiving the detailed data. 

Let's see if we can optimize this, maybe by showing an empty page first (no graphical elements except maybe a text "loading data") until the data is received.

**Comment by fm-sys** [comment]
> but this may be due to migration of cache & trackable pages to viewpager2/material tabs with #10865:

Yes, before migration the background of the activity was just black while loading the data
