### ISSUE TITLE
D/T stars no longer red after swiping through a cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10964]
## Bug description 

Sometimes after swiping through a cache and coming back to the details page the red stars from D/T are missing.

### Steps to reproduce the problem

- Open a cache
- Swipe through until logbook
- Swipe back to details

### Actual result after these steps 

![Screenshot_20210619-215214_cgeo](https://user-images.githubusercontent.com/949669/122654032-e2ed8700-d148-11eb-9b62-1ed2a96afa75.jpg)

### Expected result after these steps 

Red stars should be shown

## c:geo version 

2021.06.19-NB

## Reproducible 

Very often

**Comment by Lineflyer** [comment]
It seems (not sure though) this happens if the cache contains a tab "Logbook (Own/Friends)"

**Comment by moving-bits** [comment]
I can reproduce this behavior. It happens when the details view needs to be recreated - which happens if you scroll far enough to the right, e. g. to "Logbook (own/friends)".
Alas, I haven't found why this is happening yet - calls are routed down to `ProgressBar.setProgress()`, and no error is shown. Strange...

**Comment by moving-bits** [comment]
Digged a bit deeper into that issue:

Everything looks fine, AFAICS, except that the stars are not shown. On swiping back the details layout gets recreated:
- `CacheDetailsCreater()` is called
- `details.addRating()` is called and has the correct value for difficulty/terrain
- `getRating()` returns the correct value
- but no stars are shown :-(

**Comment by Lineflyer** [comment]
The values are OK indeed (as you can also see in the screenshot). Its something in the graphics...I would guess.

**Comment by moving-bits** [comment]
> The values are OK indeed (as you can also see in the screenshot). Its something in the graphics...I would guess.

The printed text is ok. What I meant was the rating bar ("the stars" UI element), which is actually sort of a progressbar internally. And even that component returns the correct value after recreation, just does not show the stars accordingly.

**Comment by MagpieFourtyTwo** [comment]
Another scenario which may possibly have the same reason, are images which vanish on changing pages, too: 
- go to a cache with images (e. g.: [🎲Jumanji - Nur ein Spiel?🎲](https://coord.info/GC5QZ0C))
- swipe to the ``Images`` page ... if there are images, fine, refresh by pulling down otherwise ...
- swipe left at least three pages, i. e. to ``Details``, if you have a ``Friends/Own logs`` page, too. (which may make a difference) or even to ``Waypoints``
- swipe back to ``Images`` ...
- result: no images there anymore.

**Comment by Lineflyer** [comment]
@MagpieFourtyTwo 
Good finding! Can reproduce.
While it might have the same reason I will still create a new issue with link to this one.
