### ISSUE TITLE
Material Theming: List of Lists needs reformatting

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#10982]
## Bug description 
When being in a list and opening the drop down list to open another list, this drop down list is hard to read:
- no separator between list entries
- no color differentiation or border, thus hard to separate from the background (dark theme)
- fonts way too big

### Expected result
- List's background may perhaps be same grey as in the ``Pick lists`` dialog popup
- Fonts should be comparable to the ``Pick lists`` dialog popup
- Separator at least like in the lists of caches

**Comment by Lineflyer** [comment]
As things are changing rapidly please kindly always include the nightly build version for such issues (and in general).
But I assume its todays version?

**Comment by Lineflyer** [comment]
While the first two items are to be improved for sure (I like the ideas) I disagree regarding the font size. Now its finally readable and it has IMHO the same size as the title of the current list you are on before dropping down (that makes sense).

**Comment by MagpieFourtyTwo** [comment]
> But I assume its todays version?

yep, it's 2021.06.21-NB-80757d6

**Comment by MagpieFourtyTwo** [comment]
> Now its finally readable 

In fact it is *very* readable, because it's about 3 times bigger than the text in e. g. details page. ;)

> and it has IMHO the same size as the title of the current list you are on before dropping down (that makes sense).

Yes, it is the same size, which in fact is the reason, why it should be smaller. Cause the drop down is just an inventory, a table of contents, and these overviewss are always smaller than e. g. the headlines of the chapters they refer to.

Just compare the size of the list name in the header and the font size in the pick lists dialogue pop-up - following your argumentation, the font in the pop-up would have to be way bigger, in fact the same size as the list's name in the list header - do you really want it this way ...? ;)

**Comment by moving-bits** [comment]
We use the old actionbar and apply a `setNavigationMode` to it, which is deprecated. There's no `Spinner` used currently!
View is created implicitly by a listview, which uses the same view for opened (=list) and unopened (=actionbar display) states. I applied a different background to it, and it's used for both views:

|opened state|closed state|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/123507997-19596380-d66d-11eb-94d5-a18d32625762.png)|![image](https://user-images.githubusercontent.com/3754370/123508002-20807180-d66d-11eb-9767-67eb059a3f4f.png)|

I guess for fixing this we need to change the page's layout to use a `Toolbar` instead of the integrated ActionBar, and apply a toolbar layout including a regular `Spinner`, which we can style then.

**Comment by moving-bits** [comment]
As a first step towards this issue I created #11013 which adjusts background color.

**Comment by fm-sys** [comment]
Maybe using the hint color like done in  #11071  for the number of caches?

**Comment by moving-bits** [comment]
Good idea! Using a different color helps with separating the entries. IMHO we can even remove the additional spacing then:

![image](https://user-images.githubusercontent.com/3754370/124379356-cc057380-dcb6-11eb-97b9-3b3dabc6d412.png).![image](https://user-images.githubusercontent.com/3754370/124379359-d0319100-dcb6-11eb-9a14-5c1fcf18d27d.png)
