### ISSUE TITLE
Optimize "icon buttons"

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#11065]
## What function are you missing
While our new icon buttons looks fine in general, there are still two caveats (IMHO):
- they use more space than the old ones, although the old ones were already relatively large and easy to use (touch target)
- the image itself ("the inner part") is much smaller than with the old buttons, so they are harder to recognize, and there's much unused white space around it

This leads to a third thing, very visible in our cache popup:
The "more details" button does not have a fixed height identical to the icon buttons any longer, which makes this button way smaller, which leads to a strange look of both types are close by. The old look, having same height, was a very straight-forward, clean look, visually stable. But giving the "more details" button the same height as our new icon buttons makes it clumsy and way too big.

![image](https://user-images.githubusercontent.com/3754370/124348914-f7239080-dbec-11eb-9788-92c31f66bc1f.png)
(to the left: new style and two "old" buttons for comparison / to the right: old style)

## Suggested solution
- decrease the icon button size to the same dimensions as the old icon buttons had
- increase the size of the "inner image" to mostly fill the (decreased) dimensions
- adjust "more details" (and any other default button) to have (at least) the same height as the icon buttons

## Alternatives/workarounds
- make "more details" button full width
- find a different placement for the "hint" icon button, maybe by placing "refresh" and "delete" on the same line, and placing "edit list" and "hint" on the second

But that would solve only the third issue.

**Comment by murggel** [comment]
I can tackle the size of the inner icon

**Comment by murggel** [comment]
![image](https://user-images.githubusercontent.com/70113341/124351607-9f405600-dbfb-11eb-98ea-5b741e03b029.png)

I will prepare some more screenshots from other activities...

**Comment by Lineflyer** [comment]
Thanks @murggel for working on this. Don't you think they are now "very massive" e.g. compared to the text size.
The relation between outer border and inner icon size is fine, but now they are rather huge and together with the new solid black look, those icons look somehow oversized for me.

What about rather keep the size of the graphic and have make the outer border smaller? Opinions?

**Comment by murggel** [comment]
Yes, that was my first impression as well... I will play a little bit more with it...

**Comment by murggel** [comment]
Probably using the outlined style instead 🤔

**Comment by murggel** [comment]
outlined:
![image](https://user-images.githubusercontent.com/70113341/124360887-81d7b000-dc2c-11eb-82ee-f76806b0c2ed.png)

**Comment by murggel** [comment]
a little bit smaller:

![image](https://user-images.githubusercontent.com/70113341/124360877-7a180b80-dc2c-11eb-8292-5f9eae05547c.png)

**Comment by murggel** [comment]
little bit smaller button
![image](https://user-images.githubusercontent.com/70113341/124360989-f6125380-dc2c-11eb-8862-196fab43372e.png)

**Comment by Lineflyer** [comment]
Maybe the smaller ones from your above screenshots and I honestly like the outlined more than the plain black ones.
So small and outlined maybe?

BTW:
It should at the end be consistent to the icons on cache details.

**Comment by eddiemuc** [comment]
I would prefer the "little bit smaller buttons" (but I would not insist on it :-)). I am indifferent whether to use outlined or solid icons, but I would imagine that the "outlined" version does not look good if the icon is too small.

Another question: in most images the "hint" button is missing, I only see it in the first screenshot from 30 minutes ago ("outlined"). Will this button stay as can be seen there? (same row as "more details", but higher than the text button)
Because I think this looks really strange. @moving-bits already suggested two solutions (both valid imho), I would add a third one:
* adjust "more details" (and any other default button) to have (at least) the same height as the icon buttons
* find a different placement for the "hint" icon button, maybe by placing "refresh" and "delete" on the same line, and placing "edit list" and "hint" on the second
* remove the "hint" button completely in cache popup, put the ROT13-encoded hint directly into popup, make it decode on click (same optics and behaviour as in the "cache details" page)

**Comment by fm-sys** [comment]
Please stay with the filled icons. At least, I doesn't like the outlined icons at all, as they are IMHO way harder to recognize, because there are holes inside the icons at places, where they don't belong. So I would stay with the inner size and just adapt the outer dimensions... (Cause in the current style, the filled icons definitely doesn't look too massive)

**Comment by moving-bits** [comment]
Thanks @murggel for working on this!

Also like the smaller buttons from "little bit smaller button", and would prefer the solid icons for the reasons already mentioned above.

**Comment by murggel** [comment]
42dp button size, 30dp icon size
![image](https://user-images.githubusercontent.com/70113341/124363286-9f137b00-dc3a-11eb-81c2-83face869e21.png)

**Comment by murggel** [comment]
button same height as icon 
![image](https://user-images.githubusercontent.com/70113341/124364443-efdaa200-dc41-11eb-8acc-f7f855da0d6b.png)

**Comment by murggel** [comment]
Icons for Routing with changed size-dimension:
![image](https://user-images.githubusercontent.com/70113341/124364478-1993c900-dc42-11eb-9a7e-2181ab7033ee.png)

**Comment by murggel** [comment]
Icons in filter-view:
![image](https://user-images.githubusercontent.com/70113341/124364495-2f08f300-dc42-11eb-9c48-0de2bf369ddf.png)

Probably I have to adopt the size for "reorder"-icon

**Comment by Lineflyer** [comment]
The size in general look fine now in your newest screenshots.
Regarding the outline: I think there was a majority for not using it...so it looks good IMHO.

**Comment by murggel** [comment]
Thanks for all your feedback!

**Comment by murggel** [comment]
PR #11070 created

**Comment by Lineflyer** [comment]
IMHO this is completely fixed by #11070.
Feel free to reopen if I missed something here.
