### ISSUE TITLE
set map language not remember

### ISSUE THREAD

**Issue by hakuchi** [cgeo/cgeo#11089]
I use FZK offline map and when i set the language to "de" cgeo not remember my setting if i open the app some days later or if i close cgeo in the system settings.

The language is marked as set to german, but i have to tap again to "de" to become german names shown on map. 

Tested in cgeo from 2021.06.23

**Comment by moving-bits** [comment]
verified on current beta version as well. 

To reproduce
- download OAM Switzerland map
- set location to Geneva
- depending on language you should see either "Geneva" (en), "Genf" (de) or "Genève" (fr) etc.

Now set language to "de" and close c:geo (remove from memory). On restart the menu entry is still set to "de", but the actual map language is the map's default language ("fr" in this case), so "Genève" is being displayed instead of "Genf". If you manually change the maps language, you'll get the correct labels - until you restart c:geo.
