### ISSUE TITLE
Users claim found/disabled/archived caches are not filtered according to setting

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11133]
I got various reports, that something is not working as expected by users. Still trying to find out more details from users.

To me it looks like the problem is, that the (formerly?) global hiding of found/disabled/archived is no longer working when performing various searches. Is it like that intentionally due to our rework of filters?

The main problem seems to be, that users always had set to hide found, disabled, archived and suddenly those caches show up and they don't know what to do or why they now have to apply (advanced) filters for it. 

Either we underestimated the change or there is a bug still in?

I did not find the time (due to vacation) to try the behavior myself... will do that later on.

**Comment by eddiemuc** [comment]
Indeed the usage of these global settings was intentionally removed. They are now only used for map quick settings (and unfortunately for the "found by" search which can't be switched to new filtering system).

But I.forgot to remove the settings. Should I do that? Or should we have another discussion wrt global filter options?

**Comment by Lineflyer** [comment]
I am afraid, that we should rethink it a little bit:
For the map we found a good way to keep those settings and use them almost in the same way. For the list they were also not used before so its not unexpected.
But we forgot that users expected those settings to be also used for searches (as they were until now).

At least we could make them available in the basic filter screen, not requiring users to deep dive into advanced mode.
And maybe we should migrate the legacy global settings into the search result filter (is there such a dedicated filter or do we now only have one filter set) on upgrade?

**Comment by eddiemuc** [comment]
> I am afraid, that we should rethink it a little bit:
> For the map we found a good way to keep those settings and use them almost in the same way. For the list they were also not used before so its not unexpected.
> But we forgot that users expected those settings to be also used for searches (as they were until now).

Always open to rediscuss think. 
But we did really not forget about the searches, there were quite some discussions about this (for example oin #10951 but also in other places) and some users claiming to leave things as is for the searches (I think @magpiefourtytwo was among them).

Well, this is partly what betas are for: to rethink things :-) 

> At least we could make them available in the basic filter screen, not requiring users to deep dive into advanced mode.

The Status filter grew very big by now, many special options in it today, really include it in basic filter?

> And maybe we should migrate the legacy global settings into the search result filter (is there such a dedicated filter or do we now only have one filter set) on upgrade?

There is no dedicated filter for searches, just one global filter setting for everything. No context-specific filters any more.

I guess such a migration is possible. Could you describe its logic more precisely in an own issue? (you have to find a mapping from existing global settings into the new filters)

**Comment by fm-sys** [comment]
> The Status filter grew very big by now, many special options in it today, really include it in basic filter?

What about a more lightweight version, e.g. just 
![Screenshot_20210707_221025_cgeo geocaching](https://user-images.githubusercontent.com/64581222/124822495-3c8ae980-df70-11eb-954e-cfc7b24288b9.png)

**Comment by MagpieFourtyTwo** [comment]
I still don't think it's a particularly good idea to force users to set up filters for such basic decisions like excluding already found and archived stuff from searches and map.

Just imagine you call directory assistance to get some friends' phone numbers - and the lady on the other end starts reciting all the numbers they had since birth ... and you have to tell her every time over and over again that you only want to hear the current one ... what for ...? Gone stuff is gone, this is common sense, IMHO, so give a possibility to store this basic decision and everything is fine ...

And, hey, if it does not comply or even collide with a (too) complex filter, just let c:geo tell the user that it will simplify the filter ... KISS ...

Just my 0.02 $

**Comment by eddiemuc** [comment]
For the actual implementation it would be consequently to remove the found/disabled/archived filter settings from the Settings. I simply forgot to do that (was a bit stressful directly before the beta)

But I feel that mindsets are shifting towards allowing these additional global filters, so I hesitate doing this... still right now the are only used in map viewer (and Found By search for legacy reasons)

So I am undecided what to do here

**Comment by fm-sys** [comment]
I still think that what we are doing is the right thing. We had long threads and agreed on the current behavior. Don't get, why we should change this back again, just because some users are surprised. 

The new behavior is just unexpected for users and they need to change their habits a bit. And we need to better explain this change.

**Comment by MagpieFourtyTwo** [comment]
> agreed on the current behavior.

Not really. It was just "agreed" (but still not unanimously) that we'll just do it, in fact give it a try, and wait what users say. Now first users are unhappy, and the logical and inevitable reaction should be "let's ignore it" ...?

Sorry, but "agreement" looks different, at least in my world. ;)

Moreover:  The currently complaining ones are not even the normal users, but technically more interested ones, who are even willing to fight with a beta - just imagine how pure users will react ...

Still: From the viewpoint of a pure basic user (and I guess most of c:geo's users are pure basic), removing this global decision will for sure be a regression. And these very first reactions should not just be ignored.

**Comment by MagpieFourtyTwo** [comment]
Brainstorm:
IIRC main problem with global settings were possible collisions and increasing complexity in combination with new filter system.

So, what if the global exclude settings just remain the way they are - but will just be used as a default?
As long as no "new", explicitly set filter is active?
And as soon as an explicit filter is activated, the global excludes will not be taken into account anymore?

Admittedly, this may look like a second (hidden) filter system, but can perhaps be implemented as a kind of default filter, which will just be hidden from the user's eyes. And which gets deactivated and re-activated automatically again, depending on the state of an explicitly set "new" filter? IMO this could just be a second filter definition string, which should be looked at, when no explicit filter is active. And which should not be shown to the user.

This way we would still have the possibility of global decisions without collisions with the new filter system.
Moreover this variant creates an easily explainable scenario for basic users as as well as for the more experienced ones.
And it can even be shortly described in the settings' explanation text like ``Exclude caches you have found (if no filter is set)`` or alike ...? Differentiation between this "default filter" and an "explicit filter" will not be a problem at all, IMO, cause the normal user will not even realize that these global settings are in fact nothing else than a hidden filter, working in the background ...

Moreover, it can easily be decided by the program if a filter should be applied or not: The default filter (based on the global excludes) should *never* be activated in offline lists, but in searches and map it should, like it was before (and it should still be influenced by the map's Quick Settings), while an explicitly set filter (if exists) can safely be applied everywhere - and should then of course be shown to the user.

And, most important, IMO: The default behavior which users know and use for years will not change and the results are still like the users expect them to be.

@eddiemuc Would this be possible - with reasonable effort?

**Comment by MagpieFourtyTwo** [comment]
Addition - just in case this last proposal may be a viable path:

The difference resp. switch between such a "default filter" (based on the global settings) and an "explicit filter" must of course have an effect on the map's Quick Settings menu, too, cause when an "explicit filter" is active, the Quick Settings' checkboxes will of course have no effect WRT the currently displayed caches (given that the checkboxes just change the global settings and not the definition of the currently set "explicit filter", which would of course be possible, but would most possibly drive complexity to a new dimension, and as this will most probably be used very rarely anyway, this may not be the way to go).

So, what if the Quick Settings menu gets context sensitive?  As long as no "explicit filter" is active (thus most probably most of the time and for most users), it can offer the ``Show caches`` choices as they are right now (and may still change the global settings) and as soon as an "explicit filter" gets activated, it instead offers a shortcut to the new filter system and to the list of saved filters? Or (as there will be plenty of room anyway) even the current filter definition?

**Comment by eddiemuc** [comment]
My 0,54 cents:

In the last couple of month I dived very deeply into existing search/filter functionality of c:geo, and it was at the same time both unbelievaly feature-rich and also crazily complex.

I tried to contain the feature-richness plus the long list of new feature wishes as best as possible but at the same time put all the craziness into a "box" - which is the new filtering framework. Always hard to find the right balance between "crazily complex" and "feature complete" - well, this was the best I could manage.

Allowing anything filter/search-related outside of this "box" somehow defies my goal of containing it there. I made my peace with the "map quick settings", but I was really glad there's not more outside this box.

Coming from this background, I am not too keen on the idea of adding "outside" complexity again. I think the "inside" complexity of the new filter framework is hard enough to understand for most users.

I realize that there must be some migration effort done for users used to the old ways. But this should IMHO not define any part of this new way. 

So I would suggest the following:
* removing the global Settings for exclude found/own/disabled/archived
* on first start, migrate existing settings into an initial new global "status" filter (too late for the beta users though, but I can make a "best effort" for migration in case they only have an AND filter) (I think @Lineflyer suggested this)
* Add a new "simplified" status filter to the filter framework and make it part of the "basic" filter (I think @fm-sys made a suggestion for that)
* simply **accept** that there may be cases where the map quick settings have no effect (when e.g. "found" is already filtered out in global filter). Alternatively, remove map quick settings completely (leave only "waypoint filters") if this is not acceptable.

All in all, even with these small simplifications, I don't know any app with such richm powerful and flexible filtering capabilitie as c:geo.

**Comment by alan666notb** [comment]
The problem I had was, after playing with the new "Search by filter" function to see what it was capable of, I then went back to the live map to find it wasn't showing any caches around me - I didn't realize that using a search option would result in the filter being applied the live map - and I don't really want it to.

Is it possible to have one filter that applies to the live map and another that is used for just for searches, and the two don't interfere with one another?

**Comment by MagpieFourtyTwo** [comment]
@eddiemuc - don't want to belittle your efforts nor doubt your competence, of course, and I of course don't know the interna, but just still don't get the problem, so please just let me summarize my understanding and please correct me if I'm wrong:
1. The new filter system gets (should be) applied wherever you are
2. Thus any routine which wants to display a set of caches will (resp. should) ask a central routine to get a set of data
3. This central select/filter routine has complete control over the currently defined (or at least over the applied) filter
4. So, why should this routine not be able to apply a default filter (constructed from the global settings on the fly) instead of "nothing", when there is no global filter active? And why should this routine not be able to write an empty string to the text which should be displayed by the app as current filter, just in case nothing but the "default filter" is active ...?

**Comment by eddiemuc** [comment]
> Is it possible to have one filter that applies to the live map and another that is used for just for searches, and the two don't interfere with one another?

Actually in a first version of the filtering, every "context" stored its own filter - there was one stored for the map, one for list view and one for each search.

But it turned out this is also not very intuitive. For example, imagine you have been in the map filtering e.g. for mysteries. Then you leave the map, and an hour later you use an online search for e.g. the caches hidden by a user. Having them in a list, you decide to display it in the map - and suddenly your list is filtered to show only mysteries (which was the last filter used on map).

**Comment by eddiemuc** [comment]
> @eddiemuc - don't want to belittle your efforts nor doubt your competence, of course, and I of course don't know the interna, but just still don't get the problem, so please just let me summarize my understanding and please correct me if I'm wrong:
> 
> 1. The new filter system gets (should be) applied wherever you are
> 2. Thus any routine which wants to display a set of caches will (resp. should) ask a central routine to get a set of data
> 3. This central select/filter routine has complete control over the currently defined (or at least over the applied) filter
> 4. So, why should this routine not be able to apply a default filter (constructed from the global settings on the fly) instead of "nothing", when there is no global filter active? And why should this routine not be able to write an empty string to the text which should be displayed by the app as current filter, just in case nothing but the "default filter" is active ...?

It is implemented exactly as you say. This is not a technical issue and would easily be doable.

But why would I keep and maintain two very different "filter construction" mechanisms in c:geo in parallel for the foreseeable future? The new filter system is capable to construct far more than is available by todays "global settings" - why can't the user use the new system instead?

By the same argumentation I could also keep the legacy global filter for Cache Types (which was removed in current beta).

**Comment by alan666notb** [comment]
> Actually in a first version of the filtering, every "context" stored its own filter - there was one stored for the map, one for list view and one for each search.
> 
> But it turned out this is also not very intuitive. For example, imagine you have been in the map filtering e.g. for mysteries. Then you leave the map, and an hour later you use an online search for e.g. the caches hidden by a user. Having them in a list, you decide to display it in the map - and suddenly your list is filtered to show only mysteries (which was the last filter used on map).

The problem is almost the reverse of that - after doing that online search for the caches hidden by a user, you go back to the live map and that's all you see.

If I'm looking at a list of caches, e.g. from a search result or just one of my lists, and I press the 'map' button on the list, I expect to see that list of caches shown on a map without any further filtering.

But when I go to the **Live map**, I just want the caches filtered by the 'Quick settings' button there, I don't want the Live map to 'remember' the last search that I did.

**Comment by murggel** [comment]
Besides the ongoing discussion
...
how about moving / copying not only a small status filter as suggested from lineflyer, but also the save and edit buttons to the basic filter view.
So it is more obvious and easier for the user to create more than one filter.
And probably the switch between filters can be enhanced as well, no concrete idea, but probably as for the lists a pulldown on long click on the filter icon which opens a list of stored filters and activate the selected one.

**Comment by MagpieFourtyTwo** [comment]
> But why would I keep and maintain two very different "filter construction" mechanisms in c:geo in parallel for the foreseeable future?

C'mon - "very different" ... constructing such a really simple filter out of four binary fields is a one liner.
And applying it instead of an empty string is not even a whole line of code.
The routine must not even tell the world that there's a filter active ...
Two LOC which would not just solve all the current problems but would even massively increase usability and acceptance.
Is this price really too high?  ;)

> The new filter system is capable to construct far more than is available by todays "global settings" - why can't the user use the new system instead?

Because a) for most of the users this filter is way too complex anyway. And b) it's way more comfortable to set a default instead of being forced to apply the very same filter over and over again.

Please keep in mind, this is not about capabilities. Of course the new filter system is *way* more capable than these four settings. It's just and only about usability.  And user friendliness.  And comprehensibility. Especially for basic users. And even for the more experienced ones for their all day's work.

Please don't get me wrong, I really like the new filter system, and I'm really glad you implemented it, as it offers a whole bunch of possibilities. But even me would love to have a simple possibility to get my default covered - without even thinking about it. And of course the new filters open a whole new dimension for finding the stuff one is looking for - but usability should not be sacrificed for it. Please don't forget the basic users - they should still be able to work with c:geo as they did for years.

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo don't get me wrong, I will implement this if community wants it.

In the past we also talked about the possibility to set a (second) global filter in the background which is simply applied everywhere in addition to the other one. How about that?

Also, I am currently working on including a simplified version of the status filter in the basic filter, as @fm-sys suggested.

 (btw it's a bit more than a one-liner because each filter has to be implemented once for in-memory-filtering, once for SQL-based-filtering and once for each connector where the online API supports it. And let's not forget the testing efforts :-)  Still not a big deal if course)

**Comment by eddiemuc** [comment]
PR #11148 includes a simplified status filter into the basic filter

**Comment by Lineflyer** [comment]
I am thinking about this back and forth but still unsure about an optimum solution.

Whatever solution we choose it should be easy to use and able to cover a migration (i.e. take over the users former global settings).

At this moment I think we should add the hiding to the basic filter screen and take over what was set in the old version upon installation. That would avoid having a second hidden set of filters or something alike. 

But two things to think about:
1. As these might be a default setting which is kept by users all the time, it would be wasted space to show the "is filtered" status on the screen all the time.
2. What about the map quick settings in that case. IMHO either keep them but changing there will change the filter in background. Or remove them as they are available via filter anyway. I tend towards the first option as according to earlier feedback users like these quick settings.

**Comment by eddiemuc** [comment]
There's one thing I don't understand.

* On one hand, users claim that the hiding settings for found/owned/disabled/archived are very fundamental, should be set one time globally and then be applied everywhere all the time
* On the other hand, exactly the same filter settings can most prominently be changed all the time in the "map quick settings" - which suggests that users change this very often

This does not fit.together imho. Are those now static settings (set it one time, never change it) or dynamic settings (changed very often, must be placed very prominently)? Somehow it can't be both at the same time.

**Comment by murggel** [comment]
Since I don't use the global filter, I am not so familiar with its behavior,  but could it now be seen / interpreted / implemented as the default  value for a new / empty filter?

**Comment by murggel** [comment]
> 2. What about the map quick settings in that case. IMHO either keep them but changing there will change the filter in background. Or remove them as they are available via filter anyway. I tend towards the first option as according to earlier feedback users like these quick settings.
> 

I am not sure if it should change the filter in background, especially if it is a stored one, because for me it's a temporary setting for the map

(hm - except for the option "show as list", where really only the cache on the map show up in the list, but this is probably a special case)

**Comment by MagpieFourtyTwo** [comment]
[...one time vs. quick setting]
> This does not fit.together imho. Are those now static settings (set it one time, never change it) or dynamic settings (changed very often, must be placed very prominently)? Somehow it can't be both at the same time.

Asked this way, it indeed seems to sounds weird. But in fact it's the question which is weird. We have to look at the use cases: Most of the time no one wants to see already found stuff. It's like a point and shoot camera: Switch on, one click, photo taken, everyone's happy. And this covers 95 % (if not even more) of all photos taken today, thus "Automatic" (with it's very well defined and poss. even persdonally adapted preset) is the default. But once in a while, this beautiful butterfly comes along and suddenly you need super macro. Just imagine you now have to put the camera down, go to the menus, search in the depths of the structure ... just to find this setting ... until you've found it - and have adapted tele, depth of field, white balance, aperture, time - the butterfly will be gone. But thanks god you have this shortcut ... one click, macro activated, butterfly captured, everyone is happy - and then, back to auto.

Same for c:geo: Most of the time people want to go out caching. Nothing more, nothing less. That's it. They want to do one click and see, what they can search and log. They do not want to fiddle around with settings, filters, boolean definitions, or even work through all these settings. So they define an "Automatic" mode: "Show me what I can do". In fact "Nearest". Or caches of just this owner (cause you like his way of hiding or his way to build). And then you don't want to first set up a filter. Or be bothered by boolean algebra. Or whatever. Click & Cache. Period.

Until this friend comes along, who has not yet found this very special one, you already logged years ago. You don't even remember exactly where it was - but thanks god you can look it up easily: Open Map, unset ``Exclude Found`` and there you go. Fried gets GC code,, back to "Auto" (i. e. ``Exclude Found`` - and everyone is happy.

TMALSS: It's not about logic. Users are not logical. They are lazy. Remember: Laziness is one of the main (if not the only) driving force for evolution of mankind. Thus "usability" *must* be the main topic, apps should have in focus. Otherwise they will simoly not survive.

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo all valid. 
But the status filter settings in the new filter can be accessed as quickly and with same amount of clicks from the map viewer as the ones in quick setting:

One tap to open the filter, then immediately change e.g. the status, one more tap to apply. Same amount of taps as with map quick settings. And at the same time far more options.

**Comment by MagpieFourtyTwo** [comment]
Agreed - but a *really* global filter can not be the solution for all cases (which may even bring light to your question): In map you of course just want to see what can be done - at least most of the time (as described above). This applies to [Nearest] and other searches, too. But when looking at an offline list, you of course want to see *all* of the stuff in this list. So a *really* global e. g. ``Exclude Found`` filter is disturbing when you e. g. want to show this really unique found cache to your friends. Or ``Exclude logged offline`` is not good in the list you maintain to do your logs in the evening ...

As we have a *lot* of different use cases, one single global setting will of course never match all places in the app. Consequence is, you have to change the filter all the time ... Which is in fact a really good reason to remove it from global settings. But then, a different mechanism must be found to match all these use cases. And it should *not* be global over the whole app.

Until now these use cases have been covered by the different functions itself. So the context decided if the global setting should be taken into account or not. This has been removed - which is good, seen from the point of software structure. But is bad, seen from the point of usability. Thus a replacing mechanism must be implemented, to keep users happy.

Which is in fact the reason why I suggested to implement list specific filters. Not perfect, but the only way I currently see to handle the different use cases ... but I'm open for alternatives ... which, and this is the main demand, are not a regression to usability.

**Comment by MagpieFourtyTwo** [comment]
Again: I'm not talking about "Quick Settings" vs. "Filter definition", these are just GUIs, which in fact can both influence the same settings/filter, with nothing but a different user interface, but under the hood they are setting the very same stuff - in fact it's the scope, that is disturbing right now. For all the different use cases c:geo covered before, one global filter is not sufficient.

Right now we've moved the responsibility for the right filter to be applied from the program (context sensitive decisions) onto the shoulders of the user - and most of them will be completely overburdened. So we have to give them an *easy* possibility to cope with this new burden. And a default filter, which applies in the same way the global settings did till now, could perhaps be a solution ...

**Comment by eddiemuc** [comment]
I remember seeing a proposal of @murggel to make the feature of "load/save filters" more prominent, meaning:
* Put this function into basic view
* Allow quick-choosing saved filters e.g. by long-tapping thr filter icon (then a popup opens)

How about that? Users then may define their own "contexts" and what filter to use where.

One question wrt "list-specific" filters: if I understand you correctly you request to store a filter per user-defined list. But is such a list not a "filter"/user-selection-of-caches in itself?

**Comment by MagpieFourtyTwo** [comment]
> One question wrt "list-specific" filters: if I understand you correctly you request to store a filter per user-defined list. But is such a list not a "filter"/user-selection-of-caches in itself?

Yes, it is indeed. This is why I am suggesting all the time, that a filter, which has been defined in e. g. the map or in [Nearest] should *not* be applied to a list of offline stored caches, like it is right now. These are two completely different use cases and therefore should *not* be handled with the same filter.

BUT applying a filter (or an individual sort order, which was the initial request) to a list should of course be possible, to be able to see just a subset of this list (like "please just show me caches with ``Wading required`` in my list of ``High Quality caches``, cause it's really hot right now and I would really like to cool down" - which of course will most probably *not* match the criteria you usually use in the map or in nearest search, where you usually want to see the stuff that can be done ...

> - Allow quick-choosing saved filters e.g. by long-tapping thr filter icon (then a popup opens)
>
> How about that? Users then may define their own "contexts" and what filter to use where.

In short: No. Cause this will still force the user to *manually* change filters all the time. Compare this to the old version of c:geo: We had various scenarios, which built up their very special context over time (you will know, as you told you had a hard time, to find and remove them) - and they knew perfectly fine what should be shown. Like ``Exclude Found`` and ``Exclude Archived`` in Map and [Nearest], but show ``Found`` in offline stored lists. These "automatisms" are gone now (which is exactly what users complained about and what this thread is dealing with). And basic users will miss it even more. And, rest assured, they will not like (nicely said, in fact they will hate it) to be forced to manually set and change filters, just to achieve what c:geo did automatically for years.

Maybe it's still not understood: Of course they *would* be able to achieve way more with the new filter system - but most of them *do not even want to know about these possibilities.* And even the ones which will understand the system and may even be able to effectively work with it (like me, if I may say so, without wanting to sound conceited), *don't want to be forced to use it all the time.* Esp. as they/we know, that c:geo was able to do it *for them.* "Automatically". In their eyes, c:geo lost some cleverness. And, I'm sorry, but I have to admit that they are right. At least from their point of view.

**Comment by MagpieFourtyTwo** [comment]
@Lineflyer 
> At this moment I think we should add the hiding to the basic filter screen and take over what was set in the old version upon installation. That would avoid having a second hidden set of filters or something alike.

I fully agree to the first, but the second must be reconsidered - cause there's still the problem that this filter will currently even affect lists with offline stored caches, thus e. g. your ``My finds`` list may be completely empty afterwards, as well as your ``Offline logs`` list, which you filled over the day, to do your logs in the evening. And you don't even see why they are empty, cause the hidden filter will not be shown. This is, why IMO different filters are needed for Map & Searches vs. Offline Lists.

> But two things to think about:
> 
> - As these might be a default setting which is kept by users all the time, it would be wasted space to show the "is filtered" status on the screen all the time.
> - What about the map quick settings in that case. IMHO either keep them but changing there will change the filter in background. Or remove them as they are available via filter anyway. I tend towards the first option as according to earlier feedback users like these quick settings.

Me too (i. e. first option) - which is more or less what I suggested. Apart from applying this filter to offline lists. Which therefore need an own filter ...

So maybe at least two filter definitions can be a solution: One for Searches, Nearest and Map, and one for Offline Lists ...? Which brings me back to list specific filters ... but one step after the other, at least these two separate ones would be a step in the right direction, IMO.

While they must not even be hidden ... showing them would increase clarity ... and solve @fm-sys' "problem" while searching for caches of an owner, and wondering why already found stuff is not shown ...

**Comment by eddiemuc** [comment]
Maybe it was a failure to even touch the old filter system. It seems that everything was better back then.

As a c:geo user, I can accept almost any filter system, even the absence of it. My caching use cases are not that complicated and I consider myself flexible enough to adapt to any new system we might invent.
But as a c:geo developer, I need to have a clear and community-agreed view on what to implement. And I don't have that clear view right now.

**Comment by MagpieFourtyTwo** [comment]
It's most definitely better right now - and you did a really great job!
We just have to find a way to get the "good old" automatisms working again - or at least a possibility to reproduce them.

**Comment by MagpieFourtyTwo** [comment]
> But as a c:geo developer, I need to have a clear and community-agreed view on what to implement. And I don't have that clear view right now.

Will come. In fact we're just back to the brainstorming phase. Pretty normal iteration. ;)

**Comment by fm-sys** [comment]
> > But as a c:geo developer, I need to have a clear and community-agreed view on what to implement. And I don't have that clear view right now.
> 
> Will come. In fact we're just back to the brainstorming phase. Pretty normal iteration. ;)

...and this time (at least it seems to me) we are on a good way to find a better compromise with the best things out of both worlds ;)

Let me try to list our prior main issues we had with the new filter system:
- having a different filter for every context wasn't really intuitive as these contexts aren't really understandable for users. Furthermore, I often had situations where old and outdated filters were applied unexpectedly. 
- Having only one filter for everything, doesn't seem to be very intuitive as well for users (I have made the same experience). 

OTOH, everybody seem to was fine with the old filter framework. So we "just" need to copy the old behavior into the new framework.

So I would say: All places where the quick settings filter was previously applied is one filter context. And the rest (AFAIK only offline lists) should get a different filter. Two different filter is still a number which is manageable and not too complex for users. And "offline lists" are indeed a totally different use case than the "live map". 

> This is, why IMO different filters are needed for Map & Searches vs. Offline Lists.

> So maybe at least two filter definitions can be a solution: One for Searches, Nearest and Map, and one for Offline Lists ...? Which brings me back to list specific filters ... but one step after the other, at least these two separate ones would be a step in the right direction, IMO.

@MagpieFourtyTwo 
I really like the idea of two filter contexts (online and offline). And it seems like you would be fine with it as well (at least you have suggested the same thing). 
Now the big question: With that change, would you be fine with a map-quick-settings-popup which is applied _only_ at the live  map?

**Comment by MagpieFourtyTwo** [comment]
@fm-sys First: Thanks for summarizing - you nailed it.  ;)

> I really like the idea of two filter contexts (online and offline). And it seems like you would be fine with it as well (at least you have suggested the same thing).

Totally agreed.

As it seems to turn out, it may be best to have two different filters - thus, for clarity, we may stay with your terminology "Live filter" (for searches. nearest, live map) vs. "Offline filter" (for lists with offline stored stuff)?   Consent?

> Now the big question: With that change, would you be fine with a map-quick-settings-popup which is applied only at the live map?

This appears to be a bit tricky ... as @eddiemuc already stated, it may get really complex to combine a previously defined filter with the map's Quick Settings. And doing so, may end up in unwanted (and incomprehensible) results, cause two different (and maybe even colliding) filters get active - even worse: the user will perhaps not even know why and what. OTOH it should not be too hard to implement, that a change in the Quick Settings directly change *the currently active filter.* Which will IMO even be the most intuitive way, as the last user action should always be the winning one (cause this is, what he will remember best).

Moreover, when Quick Settings immediately change *the currently active filter*, it will not just increase traceability and transparency, but it even gives full control to the user (last action wins). And last but not least it's most probably even easier to implement, cause otherwise you would additionally need a third filter definition (the combination of the filter which was active when entering the map, with the filter resulting from the changed or even previously set "Quick settings") - which will BTW even be gone on next opening of the map ... or has to be reconstructed on every opening of the map ...

So I would suggest to stay with "just" two filters: "Live" and "Offline" - and the currently active one changes as soon as you change a Quick Settings criterion. And, the settings of the currently active filter should be reflected in the initial setting of the Quick Settings ... which may be a bit tricky, but as there are just five well defined binary settings to be compared, this should not be rocket science, neither.  Which BTW is more or less the same, @Lineflyer already suggested (seems as if we're closer to a consent that thought ;) ).

Nevertheless, there's still one scenario to be aware of: Coming from an "Offline filter" context (i. e. from a stored list) to the map, we are in an offline context, thus "Offline filter" should be applied to *this* map context and the Quick Settings. But as soon as "Live" will be enabled in this map, the "Live filter" should step in (to KISS). Which may be kind of surprising at the very first time, but this behavior can easily be argued and explained to the users, IMO.

**Comment by fm-sys** [comment]
> OTOH it should not be too hard to implement, that a change in the Quick Settings directly change the currently active filter.

Yes, this is still an open discussion, which needs to be solved. You're idea would mean, that the quick settings pop-up would stay/become again global. At the first, a had a strong opinion against it, but as long as it will become part of the filter framework (means the quicksettings "found" filter is _visible _and_ editable_ in other contexts like search via the filter framework) this would be fine for me as well. The more I think about it, it actually might be the cleanest solution to a) fulfill the wishes of our users and b) reduce complexity and throw the quick settings filter backend (partly) over board. 

The only problem in the old implementation  (before redesign/new filter framework) was, that a filter was applied in the background but was not visible to the user.

**Comment by fm-sys** [comment]
Since our two-filter-implementation, it seems to be quite calm. So let's close here...
