### ISSUE TITLE
Specific search returns all caches from oc.nl

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11149]
I have GC, OC.de and OC.nl active in c:geo.
Today I searched for all caches of a specific owner (by long tap on owner name in cache details).

This returns all caches from that owner (OK) but additionally all nearby oc.nl caches (from other owners). Strangely no false caches from oc.de.

**Comment by bekuno** [comment]
I can verify it.

And I got nearby results from OC.de and EC.

**Comment by eddiemuc** [comment]
Strange that EC returned results, it does not even offer Owner search. I have to look into this

**Comment by eddiemuc** [comment]
Oh my, there are unfortunately two mistakes in this:
* Online search results are currently not refiltered locally for the attribute searched online (in this case: whether they are really owned by the claimed owner)
* Filter-supporting connectors are not further divided into singular capacities like e.g. "search by owner"

Both has to be fixed

Still, since oc supports owner search it is strange that wrong results were returned by those connectors. Have to look into that

**Comment by eddiemuc** [comment]
Ok, got the problem: if searching for an owner which is UNKNOWN on oc (e.g. because it is a pure gc.com user) then the oc search executes without an owner id restricting the search - thus returning "everythin" around.

Will be fixed.

**Comment by eddiemuc** [comment]
Hm, it seems the "hidden by" search does not work for opencaching.de on current release?

**Comment by eddiemuc** [comment]
> Hm, it seems the "hidden by" search does not work for opencaching.de on current release?

Fixed as well

**Comment by eddiemuc** [comment]
Fixed with PR #11156
