### ISSUE TITLE
Favorite percentage filter not meaningful for live map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11153]
Some beta users in depth tested the new filters and found something, which we should at least discuss:

You can actually define a favorite percentage filter and try to use it on the live map.
It will however not work as this information is not available for not stored caches.

How could this be handled? Inform the user, disable the filter,... not sure.

**Comment by eddiemuc** [comment]
Well that's a valid question. 

But first: it is not true that the filter is invalid in live map: opencaching.de actually **supports** favorite percentage filters in the live api, they will show up

![image](https://user-images.githubusercontent.com/6909759/125122850-42123c00-e0f6-11eb-996b-a98c3b167bd1.png)

A possible solution which I have constructed for these situations (but apparently not applied yet for the "favorite percentage" case for gc.com) is to mark caches as "inconclusive" in these situations. Using the "include inconclusive" flag (in advanced filter view) then enables/disables . This is currently not the case (I believe, gc.com caches are handled as if their rate is 0%)

![image](https://user-images.githubusercontent.com/6909759/125123013-6ff78080-e0f6-11eb-8a18-ade765a50785.png)


Here is an overview which connector supports which online filters:
https://github.com/cgeo/cgeo/wiki/%22Search-by-Filter%22-support-by-c%3Ageo-Connectors

**Comment by eddiemuc** [comment]
I looked up the code. for gc.com caches, the filter will currently work against the ABSOLUTE fav point - which in conjunction with a PERCENTAGE filter (who filters for a value between 0 and 1) means that gc.com caches with 0 fav points will be included in PERCENTAGE fav point filters with 0% included, and all gc.com caches with 1 or more fav points will be included in PERCENTAGE fac point filters with 100%(+) included.

That's not a really good implementation of course. I have two suggestions:
* mark those as "inconclusive" (as suggested already above)
* since we have the fav count but not the find count, we could use a "dummy" find count to calculate a "virtual" percentage (e.g. 500 finds). Not ideal I know...

**Comment by eddiemuc** [comment]
See PR #11166 for implementation of the first approach (Inconclusive usage)

**Comment by MagpieFourtyTwo** [comment]
Very good! Stumbled upon this just this very morning. Inconclusive +1  ;)
OTOH this will most probably not solve e. g. sorting by Fav Percentage ...?
Thus I would suggest to (additionally) initialize the underlying values (i. e. either Fav Percentage itself, if exists as a value, or Log count) to -1, as long as it is not yet known.

**Comment by Lineflyer** [comment]
I think this is solved for the time being by introducing the inconclusive state. Feel free to reopen if there is something missing.
