### ISSUE TITLE
Filter Button on Main Screen is inoperable

### ISSUE THREAD

**Issue by jakedot** [cgeo/cgeo#11176]
## What function are you missing

The new Filter system should also be opened when clicking the button on the main screen. As of now, there is a popup informing that it can be opened from list and map views. But why should the user have to navigate there instead of directly opening the filter activity from the main screen also (maybe after one time of reading the notice and selecting "okay, understood")?

**Comment by fm-sys** [comment]
This is due to the fact, that in the (hopefully) next big release the main screen will be completely replaced by a bottom navigation (e.g. known from Youtube). Until that point, the filter can only be changed in map and lists. The current behavior is only a temporary solution and intended to get the users used to where the filter can be found as of now... Idea is to explicitly blocking the acces via main screen while nicely explaining how the feature can be accessed in further versions.

**Comment by eddiemuc** [comment]
Also, opening the filter from main screen would only make sense if there's just one global filter setting for everywhere. While it is currently implemented that way, we already got feedback that this should maybe be changed and discussing internally the pros and cons of different options. We should wait for these discussions to come to a common conclusion before deciding about this.

**Comment by Lineflyer** [comment]
In future we will have a live filter (also takes the former global filterings for found/owned/etc.) and an offline filter for lists. Therefore the global filter is no longer used. 
Furthermore as described above the main menu is about to change sooner or later, so the disabling is an interim solution on our way towards the new main menu. No plan to change.
