### ISSUE TITLE
number of filtered caches not refreshed, when count=0

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11195]
## Bug description 
When a filter (on the live map) is active, then the number of caches in the headline is not change when moving the map.

### Steps to reproduce the problem

- open the live map
- use a filter with no result ("Event" :-( )
- result: the numer stays unchanged
- move the map
- result: the numer stays unchanged

## c:geo version 
2021.07.10-RC

## Reproducible 
Yes

**Comment by eddiemuc** [comment]
I assume you mean the cache number in the sub-headline as follows?

![image](https://user-images.githubusercontent.com/6909759/125300185-14153d80-e32a-11eb-8618-83a686e972bc.png)

I can't currently reproduce this. When I move the above scenario into an area with virtual caches the count gets updated:

![image](https://user-images.githubusercontent.com/6909759/125300294-2becc180-e32a-11eb-9714-ffdfd20d9feb.png)

Do you have any more ideas how I can reproduce this?

**Comment by bekuno** [comment]
> I assume you mean the cache number in the sub-headline as follows?

Yes.

You scenario works, my bad.
But - with using event as single criterion and a map area without event caches then the number is unchanged until you find a event cache. 
![Screenshot_20210712-161941_cgeo](https://user-images.githubusercontent.com/32555742/125304565-ff3aa900-e32d-11eb-91a8-82e0ac38da02.jpg)

And - please try the scenario from #11196.
There also moving the map does not change the number of caches (because the filter does not find a cache).

**Comment by eddiemuc** [comment]
Ah, not I get it: you mean if there are caches shown (cache count >0) but then I change the filter such that no more cache is shown (cache count should be 0), then the cache count is NOT changed to 0 in title bar.

I can reproduce this, will be fixed.

**Comment by MagpieFourtyTwo** [comment]
Perhaps there's already a related issue - but can't find one right now, so I just describe it in short here and let you decide whether to open a new issue or put in an appropriate ToDo context (which perhaps is the one over here, that's why I ask here):

You possibly remember that I mentioned to have seen the ``Load more caches`` message, although I have set my list limit to 0.
Now I've seen it again, but after some testing I doubt it's really list related, but perhaps just a simple "filter result misinterpretation". ;)
And perhaps it is s/th that can be fixed (easily) within the scope of this issue here ...

Just try the following:
- Open any offline list (preferably with more than 100 caches, let's say it has 142)
- create a filter with no caches as result (e. g. ``Attributes`` => ``Does *not* need maintenance``)
- => Message ``Load next 100 caches`` will appear, as well as ``Load remaining caches (142/142)``

**Comment by eddiemuc** [comment]
The issue mentioned by @bekuno  and the problem mentioned by @MagpieFourtyTwo were unrelated. Nevertheless, both are fixed in PR #11263
