### ISSUE TITLE
Filter: make displayed filter string fully use available display space

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#11293]
BTW: Can we possibly extend the displayed filter string, if there is plenty of room, anyway?
This ``Status: 3 items`` is feeling a little bit lonely in my header row ...  ;)

_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/11213#issuecomment-884538860_

**Comment by fm-sys** [comment]
This might be solved implicitly, if we split the status filter up as discussed in  #11288

**Comment by moving-bits** [comment]
@MagpieFourtyTwo:
Not sure if this is solvable in a general way. Status filter display switches from showing details to "x items" as soon as you have at least three conditions activated. On today's mobile screens you probably cannot see more than two conditions at the same time anyway (depending on which one you selected, and depending or portrait or landscape mode), and if you combine status filter with other filters, then you would probably want to see a bit of them as well.

What solution do you have in mind? Or shall we close this issue?

**Comment by MagpieFourtyTwo** [comment]
I thought "3 items" hides too much information although there's no need for. But then I realized that even two criteria are too much, sometimes.

I guess only "solution" would be to switch to a two line representation, but this had to be dynamic, otherwise would eat too much space ... OTOH this would perhaps open new possibilies to display the real changes of saved filters instead of just a lonely star. ;)

However, named filters are better anyway ...

TMALSS: If there's no (really) easy way to display 3 or more item filters with line break, let's just close it.

**Comment by moving-bits** [comment]
Thanks for the feedback. I guess we will always come to situations where a one / two / three / ... line representation will not fit, therefore using names for complex filters will be the better solution anyway. So let's close here.
