### ISSUE TITLE
Add filter for rating

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#11301]
### Tell us your idea!

I did not find a possibility to filter caches for specific ratings

### What solution would you suggest?

Range filter like difficulty and terrain 

### Is there an alternative?

No or I did not see it

### Additional Information

2021.07.17-RC2

**Comment by eddiemuc** [comment]
That's a valid and fitting request.

I think this is a good opportunity for others to get to know the new filter framework codewise and thus spread the knowledge across the team. I would therefore explicitly **not** pick this item (but of course support anyone taking it). Would that be ok? @murggel especially for you, since you created it?

**Comment by murggel** [comment]
> I would therefore explicitly **not** pick this item (but of course support anyone taking it). Would that be ok? @murggel especially for you, since you created it?

Would be ok for me, but if e.g. @fm-sys or @moving-bits wants to give it a try, no problem for me

**Comment by moving-bits** [comment]
I'll give it a try. Might take a while, though - currently my hardware (old laptop) and internet reception is pretty slow...

**Comment by moving-bits** [comment]
Ok, I have a first WIP. Start seemed easy enough, but now I'm sort of stuck. Two questions:
- I can select "rating" filter when in advanced mode, but then the filter box closes completely and I'm back in cache list. No errors in logcat, though - what am I missing?
- Is it correct that there will be no results for live searches from GC in `GCMap`, so I can leave the `RATING` block empty?

**Comment by eddiemuc** [comment]
> Ok, I have a first WIP. Start seemed easy enough, but now I'm sort of stuck. Two questions:
> 
> * I can select "rating" filter when in advanced mode, but then the filter box closes completely and I'm back in cache list. No errors in logcat, though - what am I missing?

I will take a look at the code as soon as time allows...

> * Is it correct that there will be no results for live searches from GC in `GCMap`, so I can leave the `RATING` block empty?

Correct, there's no rating (meaning: no gcvote-call) in live map. But I am not sure what you mean by "leaving the RATING block empty"? The rating filter should work perfectly fine for other connectors in live mode e.g. OC (which delivers ratings also in live mode afair)

**Comment by eddiemuc** [comment]
After quick look in the code, both questions are clear:
* you "just" added a filter, but you did not add a "ViewHolder" for the filter (a view defining how the editing of an instance of this filter shall be done). Take a look at class `FilterViewHolderCreator`
* second question: see comments in PR

**Comment by moving-bits** [comment]
Thanks for your pointers. I think I've added everything now, see my updated PR.
Hard to test for me currently, though, as I've stored only two or three votes on my dev laptop, and cannot download more due to my bad internet signal over here (or maybe gc.com server down? cannot login currently, so no cache updates and by that, no vote updates).
