### ISSUE TITLE
Increase max val for Logs count filter

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11355]
While I would increase the max val for Logs count, too - if possible in one go. Cause 1000 is a little bit low ...

_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/11345#issuecomment-888982801_

**Comment by moving-bits** [comment]
Increasing max value would be easy, but then it would be hard to select small values (except when you know you can manually enter values):

![image](https://github.com/cgeo/cgeo/assets/3754370/4636bfea-9d56-4038-abfc-e48e6d7a0b28)

@eddiemuc 
Is there a non-linear variant of range slider?

**Comment by eddiemuc** [comment]
> @eddiemuc 
> Is there a non-linear variant of range slider?

The material sliders I used is linear with hard min/max. But one can give a function to map a linear value to a user-defined value. Also for displayed values. I used this e.g. to create the ">1000" logic. One can surely also integrate another non-linear function this way. Challenge is maybe how to keep this understandable to the user.

**Comment by moving-bits** [comment]
The idea would be to have 0, 1, 10, 100, 1000 and 10000 as labels (exponential scaling).

**Comment by ztNFny** [comment]
I'd like to see some smaller values. 1 5 10 50 100 250 1000 >1000 would make sense imho

**Comment by moving-bits** [comment]
The TO explicitly asks for a higher upper bound than 1000, but we can surely use a different distribution, which allows for smaller steps in the lower range.

**Comment by ztNFny** [comment]
But OP was talking about Logs, you changed it for FPs? FP >1000 is something that only exists in Germany and some parts of US on old caches. The distinction between 1000, 2000, 3000 is irrelevant there imho

**Comment by moving-bits** [comment]
Aarrgh! You are right, it's about logs count, not about favorite count.
Although same mechanics apply and we could make/keep the two similar for sake of consistency.

Maybe labels something like 1, 5, 25, 125, 625 and 3125?

**Comment by ztNFny** [comment]
The times 5 idea results in numbers that feel strange. I'd rather opt for "normal" numbers. And in the low range *5 still seems large, considering that in many places of the world getting 5 FPs is an achievement and 25, let alone 125 is near impossible. That's why i suggested smaller intervals there.

**Comment by ztNFny** [comment]
I'd go with 2-2,5 interval up to 1000
1,5,10,25,50,100,250,500(can even skip that),1000

**Comment by moving-bits** [comment]
I was thinking of a mapping function, which maps all slider positions (not only the predefined ones) to values. Something like 10^x, or 5^x in the last example. 

Regarding maximum: At least for logs, TO asked for a value larger than 1000 for the max position.

Regarding granularity on very small values: As last resort you can always enter values manually (within the predefined min/max range, that is).

So we should find a mapping function for the range of 0 - (eg) 5000, maybe one being a bit flat at the beginning, but steeper towards the end.

**Comment by ztNFny** [comment]
A function would have to return sensible (to a human) world use for each point. Given the place error of sliders and different units I don't think this is something that's achievable. E.g. for days you want like 1,3,7,14,1m,3m,1y and for FPs see above. With all the thoughts that would go into a generic function you can add hundreds of sliders in the same time - and probably still be better because the required values really depend on the specific use case in at least some cases

**Comment by moving-bits** [comment]
Possible misunderstanding, I'm only in the context of number sliders, specifically "log count" (and maybe "favorites count").

**Comment by ztNFny** [comment]
But then it's COMPLETELY not worth the effort imho

**Comment by moving-bits** [comment]
Coming back to the original issue: TO asks to increase the upper limit.

If I increase it to 10000, predefined slider values will be 0, 2000, 4000, 6000, 8000, > 10000.  While this is technically correct, this makes it hard for users to select a small value (except by manually entering it - which may be a valid solution).

If we have some type of exponential scaling, both requests - being able to select small values as well as having large values available - can be fulfilled. That's similar to why we use such scaling in other places as well.

So I see following alternatives:
- a) Turn down TO's request and leave filter "as is".
- b) Keep it simple, increase upper limit to (eg) 10000, and let users enter a value manually, if they want to filter for small values. (This is what we have so far with PR #14383, although for a "favorites filter" instead of "log count filter.)
- c) Introduce some sort of scaling

> But then it's COMPLETELY not worth the effort imho

So you would vote for b)?

**Comment by ztNFny** [comment]
C) kinda
But with manual values, imho coming up with ann algorithm is too much.

I don't see the need to increase max really ... 

Maybe best would be log-like-scaling for small + manual input

**Comment by ztNFny** [comment]
B is a no-go imho. So either a - do nothing or c - do the opposite of the request 😉

**Comment by ztNFny** [comment]
Looking at the original comment the request is solved with todays implementation anyway. The max value was <1000 back then, it's >1000 now.
It was not to increase it to 10000!

**Comment by MagpieFourtyTwo** [comment]
@ztNFny 
> Whether a cache has 1000 or 2000, like 0,0something% of caches, doesn't matter at all imho, so no point in differentiang that.

Agreed. As for me ">1000" is perfectly fine.
As far as I am concerned, the issue can be closed as fixed.
