### ISSUE TITLE
Avoid unnecessary API calls 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11379]
> But using the filtering system [via cache type filter] to get rid of displayed caches is a really bad idea - because e.g. in live map c:geo will still issue requests to the servers

 Does this mean, that GC and OC caches are still requested, even if only Lab Caches are selected as cache type? If so, this should be improved anyway independent of this issue...

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/10963#issuecomment-890403118_

API calls should only be done if at least one of the selected cache types is supported by the connector. 

Another question: Will caches always be requested from all connectors even if the origin filter is set? 

These are just questions, haven't yet looked into these cases myself...

**Comment by eddiemuc** [comment]
@fm-sys 

* Filtering via origin filter will indeed disable requests to the filtered-out origins/servers
* But filtering via cache type will not. The reason is simple: the connectors don't specify which cache types they can provide. So there's no way for the filters to know which connectors to ask for caches.

It would be possible to add methods to connectors specifying e.g. which cache types they support, which difficulty/terrain range the support, which cache sizes they support, which cache states (e.g. archived) the support and so forth.... and then use this information to decide which connectors to ask for caches. But where does the story end, and would this be really worth the effort?

**Comment by fm-sys** [comment]
For the lab connector, it would IMHO definitely make sense to check if ALCs should be shown at all before doing the request (quite some users don't like to see Labs most of the time, so still doing API requests would be bad for GC.com as well as for our users). 

But for GC, OC, etc. I agree, that the chance that at least some caches should be requested is relatively high so it might not be worth the effort. But seeing that a big majority only uses GC, maybe such a cache type check can be implemented for GC only? 

So my opinion: 
For ALC the cache type check if a must have, for GC, it's nice to have, but for all other connectors it's indeed not worth the effort.

**Comment by fm-sys** [comment]
> For ALC the cache type check if a must have, for GC, it's nice to have, but for all other connectors it's indeed not worth the effort.

Cache type filtering was implemented for our AL connector since https://github.com/cgeo/cgeo/commit/2fa875bed122b0e378c62e9795ae3f2afd5cc970

I tried to implement cache type filtering for GC and OC as well, but IMHO the code is quite thirty and got too complex (see 76d159a).  Let's close here...
