### ISSUE TITLE
In "Lists / pocket queries" allow filtering by type

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11458]
### Tell us your idea!

Since the addition of bookmark lists to the PQ download page the list can get very crowded.
When it was only PQs shown here there was (and still is, but now kinda useless) option to show only downloadable PQs vs. showing all of them.

It would be nice to change it to a filter that allows to:
- Show only downloadable PQs
- Show downloadable PQs + Lists
- Show Lists
- Show everything
(I think the other cases, like "show only PQs" are not really relevant)

### What solution would you suggest?

Replace the existing switch with a menu for filtering

**Comment by ztNFny** [comment]
Related to #8513

**Comment by Lineflyer** [comment]
Maybe a spinner with the mentioned "filter" options?

**Comment by DaTechniker** [comment]
If there is thought about a redisign, that would help with usability ( I have lots of PQs regional and from BM and also BM lists) it would also help to additional filter for new PQs/BMs. This would be additional to the ideas of @ztNFny .

So I could see all PQs I did not download. 

Due to time shift from server time in Seattle and local time in Austria, I sometimes create PQs in the morning to use the possible maximum of 10 PQs a day, they are shown in the list as yesterday. And I easily see which PQs are not downloaded.

**Comment by DaTechniker** [comment]
![Screenshot_20210821-075120_cgeo](https://user-images.githubusercontent.com/88573756/130312133-a30b3da3-3b95-456f-b4f7-83b9634e06a8.jpg)

**Comment by moving-bits** [comment]
As the options mentioned above would take quite some precious space in the action bar (or would be hidden in the overflow menu) I would prefer to split this list into two separate menu entries:
- a pocket query list (with the "all" slider) - as we had before adding the bookmark lists
- a list of bookmarked lists (maybe using the slider for "new" vs. "all")
