### ISSUE TITLE
Make NearbySearch cache number configurable or introduce "load more"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11489]
> By the way. How big is the "box" (distance, number of caches) that is used for the search and is it configurable?

That is a relevant question, and recently asked by users.
Somehow users got used to the pagination (20 packs) as a convenient feature to just store those to have the closest, while now it requires some manual selection or filtering to achieve this (or store all 200 caches).
Maybe we could use a clever boxing or alike, will transfer in a new issue.

_Originally posted by @Lineflyer in https://github.com/cgeo/cgeo/issues/11488#issuecomment-900557792_

**Comment by Lineflyer** [comment]
This is a difficult topic and was discussed here several times (in the context of connectors with a low cache density). Not sure, what could be a good solution or if its just good as it is now (no change).

**Comment by Matze2** [comment]
I would prefer to have it configurable as part of the filters if it makes sense. For simplicity, maybe even some predefined soft filters might be ok (min, medium, max).

I see here both use cases:
- you want to have "really nearby" caches (min - almost no filters)
- you look for some special caches by using lots of filters - then you would probably prefer a bigger radius since the percentage of returned caches is quite small (max - lots of filters)

Another topic: basic members cannot filter by "Not Found" caches anymore. If they have found almost all caches in their home zone then almost nothing will be returned if the search distance is small.

**Comment by eddiemuc** [comment]
It is interesting to see how a technical limitation (in this case the restriction to 20 cache results with GC.com) turned into a "feature" for the users :-)

To make the topic transparent: the current search result limit of 200  is used for all online searches (nearby, coordinate, address, keyword etc). If this should get configurable, the filter would be the wrong place for it because it should remain identical for all places (e.g. also live map (where the limit is 500) and stored list filtering). But this could be made configurable e.g. in the settings if wanted.

If the feature request is really about something different, namely to select the "first x caches of a list" (e.g. to store them in an offline list) then the feature should be implemented as such, not as a restriction on the search function. Maybe a new option in the options menu ("select first 50 Caches")

**Comment by eddiemuc** [comment]
> I see here both use cases:
> - you want to have "really nearby" caches (min - almost no filters)
> - you look for some special caches by using lots of filters - then you would probably prefer a bigger radius since the percentage of returned caches is quite small (max - lots of filters)

If a user wants to add a distance restriction to his online search, he can already do so by adding a distance filter to it. There, also a min/max distance value can be set. I see no value in making such a restriction mandatory for online searches. Most connector servers (including oc and GC) support worldwide searches, why not allow users to use this feature?

**Comment by Matze2** [comment]
I never had a look on the new filter before so I was not aware that there is a distance filter which allows to limit the radius.
So the "short distance" case is already solved.

For the "long distance" case it would be nice to have these numbers configurable. 200 could be too small in some cases.
To avoid that "insane" limits stay forever and consume unnecessary bandwidth maybe they should set back to a sane default, e.g.to 200, at app restart, for example.

**Comment by eddiemuc** [comment]
@Matze2 I assume you are talking about the limit of maximum returned caches?
This is currently set per connector, for GC.com and oc it is hard-set to 200 for online searches and 500 for map viewer. 

I guess it could be made configurable at least for those two (and for others too depending on their capabilities). Only one value configurable to be applied for all connectors and both online search and map viewer, or would we need more fine-grained tuning?

I assume values > 500 might create problems in Server Side due to heavier load.

**Comment by moving-bits** [comment]
FYI: Got a ticket on support asking how to reduce the number of finds for nearby search (ticket 237974).

**Comment by moving-bits** [comment]
In #12077 a different approach is proposed: In contrast to introducing yet another config item, use selection mode to specify which caches to download. PR #12139 adds a "select next 20 caches" menu option to help with this process.

Therefore I propose to close this issue here.

**Comment by Lineflyer** [comment]
There are still users left on support mail, who tell me, that the current "workarounds" are still less usable as the old behavior.

The most understandable scenario is probably the following:
Imagine you are in an area with low cache density (like 2 caches next 30km). The user uses the "nearby" function (and is probably unaware of the technical background) and deems it a failure if this returns 200 caches where most of them are to far away to be defined as nearby.

We had similar problems (and probably an issue somewhere here) when it comes to different cache density between different connectors (e.g. many GC.com caches, few OC.de caches), where returning the same amount of results even more leads to this problem.

Is it technically feasible (and meaningful) to have a limit on distance for this specific search only either hardcoded (in request to the server or as when processing the result) or as a "transient, nearby search specific" distance filter applied?

**Comment by eddiemuc** [comment]
It would be shockingly easy to add a hard-nosed distance limit to the nearby search specifically. Reason is that in implementation this search is done by creating a distance filter (currently with unlimited distance) around the current position. We just have to add a distance limit at this place.

Other solutions like e.g. hard-coding a limit of returned results are doable with reasonably small effort.

**Comment by Matze2** [comment]
Please do not hard-code any limits.
For me the current possibility to get 200 and also easily even more caches with "nearby search" AND using dedicated filter criteria is very useful.
It is fine for me to start with a small limit as default value but the current implementation is also very powerful and it would be a pity if this feature gets castrated.

**Comment by eddiemuc** [comment]
I hate to have to suggest this, but what about a setting for this? "Max distance for nearby search" or something like it?

**Comment by Lineflyer** [comment]
Probably it ends up like that to be suitable to cachers around the world with different use cases, caching evnironment, etc.
Well yes a setting seems reasonable and also implicitly solved the imbalance between connectors as it should then be applied on all results, thus it will implicitly fix #4594

**Comment by Lineflyer** [comment]
Also relates to #7279

**Comment by Matze2** [comment]
Looks fine for me as long as the current possibilities can be still configured.
The default value can be also set in a way that users, that don't want to use the "expert" features, don't need to configure anything.

**Comment by eddiemuc** [comment]
This might be a good beginner's issue. Thus I explain a bit what would be to do here.

Starting point is class `cgeo.geocaching.loaders.CoordsGeocacheListLoader`. In method getAdditionalFilterParameter, the max distance (as retrieved from a new-to-create setting) must be set to the created distance filter as max-value.

The class CoordsGeocacheListLoader is used for both the Nearby-Search as the "search by coordinate" (as of today "nearby" is exactly the same as "search by coordinate" with current position). So in the place the loader is instantiated there must be some flag passed to the class to set max distance only for "nearby" search.

**Comment by eddiemuc** [comment]
Forget what I said, I just saw that @moving-bits already took over :-)
