### ISSUE TITLE
Adventure LAB  (AL) Waypoints

### ISSUE THREAD

**Issue by DaTechniker** [cgeo/cgeo#11505]
### Tell us your idea!

I often prepare GC tours with waypoint for AL. This helps me to keep overview especially in regions with lots of Labs, i.e. cities.
At the moment I download the AL (red symbol) then I am adding a UDC somewhere, where there are not so many other caches on the map.

Then I open the AL and extract Stages/Waypoints to the UDC. I also do make notes of the right answers there, if there is no Bonus ( this I will notice in GCBuddy and copy the results in the PN of the bonus cache afterwards). 

When I am finished with all Lab stages, I copy the notes from the UDC to the AL and set them to found offline.
This workaround leads to duplicate WP on the map.

It would also help to reduce UDCs on my map and make the map cleaned up a little bit more.

Because I do not know, how other cachers handle this issue. My suggestions would be:
Make a checkbox/switch to set import of an AL WP to AL in c:geo or UDC

I really like to use this feature of exporting to c:geo, since it helps me to handle doing more htan oneLabs at the same time, especially in some locations, where there are some Labs mixed up. 

### What solution would you suggest?

Because I do not know, how other cachers handle this issue. My suggestions would be:
Make a checkbox/switch to set import of an AL WP to AL in c:geo or UDC

**Comment by Lineflyer** [comment]
Why dont you manually create waypoints for that AL instead of using a UDC for that?

**Comment by DaTechniker** [comment]
Hi,
mainly because there is a simple way to create an UDC und it is not easy to get the coords from the AL App.

1. Open AL
2. Open AL Stage
3. Press Blue Navigate to Arrow/Symbol
4. Select c:geo
5. Select Action for UDC

See screenshots

![Screenshot_20210821-182220_cgeo](https://user-images.githubusercontent.com/88573756/130328496-ce8ea8ba-8e4b-4e83-8a66-6db7374fb92c.jpg)

![Screenshot_20210821-182158_Adventure Lab](https://user-images.githubusercontent.com/88573756/130328489-c23af481-507d-4503-ad74-057e1a637dca.jpg)

**Comment by fm-sys** [comment]
If you set the AL cache as target, you can easily create waypoints from within the map via long click...

![Screenshot_20210821_220543](https://user-images.githubusercontent.com/64581222/130333635-32b7f7fb-df29-40c7-bf06-01959acd7f89.jpg)

**Comment by DaTechniker** [comment]
This will not solve my problem, if I navigate to the header.
I am talking about the LAB Stages.
With my way I see all the stages on the map.
In my example a overview about all Labs in Vienna and with one Lab including stages distributed over half Vienna (1 Stage is behind the UDC symbol.
You may see, that I would miss the stages, when I am near them.

![Screenshot_20210821-221132_cgeo](https://user-images.githubusercontent.com/88573756/130333940-0dd8b57b-9f44-4bc3-8903-f4a136d19dec.jpg)
![Screenshot_20210821-221910_cgeo](https://user-images.githubusercontent.com/88573756/130333943-19d26b77-e2c1-41fd-9ce4-4a364174eefa.jpg)
![Screenshot_20210821-221109_cgeo](https://user-images.githubusercontent.com/88573756/130333944-d1ad2c7f-81b8-4d41-b858-b39bc5ad09f4.jpg)

**Comment by moving-bits** [comment]
You can do a trick, although it's a bit cumbersome:
- create stages in a udc, as you already do
- go to the waypoints page of this udc, and for each waypoint do the following
  - select "duplicate waypoint" by long-tapping on a waypoint
  - go to the lab adventure's waypoint page
  - select "create new waypoint"
  - select "from clipboard"
  - c:geo will create a new waypoint forcthe lab adventure, with all the data from the original waypoint (udc)
  - c:geo will ask whether to delete the original waypoint (which will effectively move the original waypoint instead of copying it)

**Comment by fm-sys** [comment]
BTW, if you don't want to create all stages manually, I recommend using https://gcutils.de/lab2gpx/

You can select "GPX" (every stage a cache) or "GPX with waypoints" (one cache per lab) as export format...

**Comment by DaTechniker** [comment]
It is easier just to create waypoints in PN of UDC and then copy all PN to the AL and import it in the WP there.

I fear, I was not able to clearly describe, what I want to do.

At the moment I create a UDC and create WP for the AL stages like described in the screenshots above.
This works is OK, but a little bit uncomfortable, because I have a UDC and an AL on the map.
Easier it would be, if I could import them directly into the AL object.

I like to do this directly on the mobile, since I can do this, without a PC, directly in c:geo even in a Hotel during a business trip, or in some coffee break.

For me it would just simplify what I do. If it is decided not to be implemented, then it is also OK with me, and I will stay with the UDC and AL copy way, I use at the moment. So I have all WP and a way to document my answers to the AL questions.

**Comment by DaTechniker** [comment]
I think I missed giving you the information, that I document my answers in the PN of the UDC, not in the WP

**Comment by baiti** [comment]
> BTW, if you don't want to create all stages manually, I recommend using https://gcutils.de/lab2gpx/
> 
> You can select "GPX" (every stage a cache) or "GPX with waypoints" (one cache per lab) as export format...

This only works because lab2gpx violates geocaching.com's policies. Technically we could do the same thing and the issue we're discussing here would just not exist. The true solution would be to address this problem to geocaching.com and request a change of policy with respect to what functionality we (as in cgeo) are allowed to provide to our users. (Of course, who are we to "request" something from the gods ...).

Today, no matter how the situation is "circumvented" be it via lab2gpx or with what @DaTechniker does, this is not what geocaching.com wants or endorses by any means. Their position is: Per AL (not per stage of an AL): show a dot on the map but absolutely nothing else. A click on the dot must directly launch the Adventure Lab App.

**Comment by Lineflyer** [comment]
@DaTechniker 
The new release of c:geo does now also load the stages of ALC. So I guess this Feature Request is kind of obsolete. Please feel free to reopen if you think otherwise.
