### ISSUE TITLE
Offline data update check shouldn't prompt so often if canceled

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#11548]
### Describe your problem!

If the user has installed map/bbrouter data using c:geos built-in download feature after some time c:geo prompts the user to update that data on startup with a dialog "Do you want to check for updates of downloaded routing data files?"

That dialog has 2 buttons, OK to check and Cancel to not check. Select "Cancel", then restart c:geo and you'll be prompted again. The only way to not get asked is to accept the update check, otherwise you're prompted on every start.

Suggested solution: If the user doesn't want to check for updates ask again in X days, not right away.

### How to reproduce?

Install map/theme/bbrouter data via c:geo
Wait the update check time
Cancel the update check prompt
Kill c:geo
Start c:geo

### Reproducible

Yes

### c:geo Version

-

**Comment by moving-bits** [comment]
The behavior to ask again on next restart (typically: next day) was by design. Use-case is: I do want to update, just don't have the time right now (or bad internet signal etc.). OTOH I don't want to wait for a full 30 day-cycle.

Proposal: Ask again in 5 days (or the configured timespan, whatever is less).
Instead of "cancel" the button could be labelled "later" or "delay".

**Comment by ztNFny** [comment]
Some delay - and I'm not sure what that "some" should be - would address the problem. Even once a day would be an improvement, but maybe 3 would be a reasonable interval.
I was on vacation and couldn't update, so got like 5 prompts a day for almost 2 weeks.
