### ISSUE TITLE
Missing date and name of the copyright owner in application license 

### ISSUE THREAD

**Issue by jirkavrba** [cgeo/cgeo#11655]
![Screenshot_2021-09-13-14-08-13-605_cgeo.geocaching.jpg](https://user-images.githubusercontent.com/14146321/133081020-a2ef95aa-d61d-4eba-8737-f60965e284e6.jpg)

I believe that the [yyyy] [name of copyright owner] segment is meant to be replaced (maybe by CI, to keep the date updated)

**Comment by SammysHP** [comment]
This must be included in every source file. The screenshot just explains how to apply the license. The year indicates the date of the first copyright claim, thus the year when the file was created or largely modified (e.g. © 2018, 2021 copyright owner). Who is the copyright owner? Hard to say as we don't have a legal entity and too many people involved to list everyone (but only those who have contributed in a significant way to that file).

IIRC we already had an issue about adding the copyright to every file and decided that it's not worth all the effort. It's mostly relevant if we want to claim the copyright in a legal situation, but we don't have the resources and organization to do it anyway.

**Comment by bekuno** [comment]
@jirkavrba @SammysHP 
The described problem is correct.

It has nothing to do with the question if we will adding a copyright in our source code files.

The screenshot shows only part of the license file for the c:geo app.
The problem here is that the complete template of the "Apache License" is used in our LICENSE file including the part `APPENDIX: How to apply the Apache License to your work.`.
Before this we had only the reference part included with owner ("c:geo") and year(s).
See the commit diff https://github.com/cgeo/cgeo/commit/e05ffa94276a7938e85bb5b5b5e2b1229f186770 .

We have to finetune the text(s).
