### ISSUE TITLE
Waypoint calculator changes preset values

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11668]
Quick note from my vacation.
Can einrich wich screenshots and better description later if needed:

- Open a cache
- Swipe to waypoint tab
- Create a new waypoint 
- Tap on cache coordinates (to take them over as base for the calculation as i mostly do)
- Tap on calculate coordinates
- The calculator opens with prefilled coords (as selected in last step)
- Tap all decimal digits to replace them by variables (DD MM.MMM mode) (outcome is e.g.:  N34 56.ABC E123 45.DEF)
- Enter some formulas for A-F
- End the calculator and save the waypoint (to continue later while doing the cache)
- Tap on the prepared waypoint again
- Tap on Calculated coordinates to open the calculator again (e.g. you now want to note down the value you just found)

Result:
The first digits have changed from the previous values (= cache coords) to your current location
(Example: You are currently at N11 11.111  now the calculator shows N11 11.ABC instead of the correct N34 56.ABC as entered before)

Can someone please try to reproduce...that bug extended my todays hike by several kilometers =8-< and I thought I am to stupid to use c:geo

**Comment by ztNFny** [comment]
repoducable in todays nightly

**Comment by ztNFny** [comment]
I think this is happening here: CoordinatesCalculateDialog.java

    public void onCreate(final Bundle savedInstanceState) {
...
        gp = getArguments().getParcelable(GEOPOINT_ARG);
        if (gp == null) {
            gp = Sensors.getInstance().currentGeo().getCoords();
        }

**Comment by pet0etie** [comment]
you can assign this to me

**Comment by pet0etie** [comment]
PR has been created : https://github.com/cgeo/cgeo/pull/11707

**Comment by moving-bits** [comment]
While testing #11707 (thanks @pet0etie for providing the PR) I've stumbled upon a different situation that fails:
- Open a cache
- Swipe to waypoint tab
- Create a new waypoint
- Enter some coordinates (which are very different from the cache's coordinates to make the problem more visible)
- Tap on calculate coordinates

The calculator opens with prefilled with current coords instead of the ones I have entered in the step before.

Not sure if this is some kind of regression as well (in that case the PR provided would only work as a workaround for the specific use case described at the top of this issue), or if this has never worked so far at all.
