### ISSUE TITLE
Map Update uses 21-06 files

### ISSUE THREAD

**Issue by jakedot** [cgeo/cgeo#11817]
### Describe your problem!

When I get an update notification for map files, the update URL seems not to be the current / latest update at all:

remote.page=http://download.freozeitkarte-osm.de/android/2106

### How to reproduce?

- Get Update Notification for a Freizeitkarte Map
- Update
- Look up which URL was actually queried during update in /cgeo/maps/***.map-cgeo.txt.txt

### Actual result after these steps?

2106 Maps are downloaded

### Expected result after these steps?

latest maps are downloaded

### Reproducible

Yes

### c:geo Version

2021.10.08

**Comment by bekuno** [comment]
Now the xml is updated to 2109

**Comment by moving-bits** [comment]
But the links inside still point to 2106 folders, e. g. http://download.freizeitkarte-osm.de/android/2106/freizeitkarte_bayern.map.zip

**Comment by bekuno** [comment]
Sorry, yes. I missread it on the second check.

**Comment by jakedot** [comment]
What are we using as our basis for the downloads and update notifications? That repository XML?

Looks for me to be a problem on their end. We could workaround by replacing the "2106" with "latest" in the links, that seems to be a correct symlink to the current 2109 folder.

**Comment by moving-bits** [comment]
Exactly, we are using the repository URL, as it gives us both, a list of which maps are offered by the server, and links for the downloads. We should not change that, and freizeitkarte-osm should fix the links on their side, IMHO.

**Comment by jakedot** [comment]
Told them on twitter. https://twitter.com/uzuuru/status/1447109964275802118

**Comment by bekuno** [comment]
Maybe we can add a plausibility check in the website test.

**Comment by jakedot** [comment]
@moving-bits yes, those files did exist before the original update and still do. If you look in my original post, you'll notice that they are the reason I found the problem at all.

I think the problem with c:geo not noticing the fixed XML is that the "version string" and the update dates for the individual maps have not changed in the updated XML.

What I did to now get the latest maps was changing the date in the companion files to an earlier one, and then the update dialog is shown again and updates the maps correctly, afterwards the correct directory was listed in the remote.page entry.

**Comment by jakedot** [comment]
> which is probaly work as designed.
This uses up space for the newly duplicated map though. I think the old one should be deleted if name changes on update.

**Comment by moving-bits** [comment]
> Also, it looks to me as if the system download manager is only actively downloading when c:geo is the foreground process, download notification and progress stops quite quickly after switching to other apps...

That should not be the case, as we use the system's download manager for exactly that case - to continue or resume download even if you stop c:geo, shutdown the system, switch off your internet connection etc.

**Comment by bekuno** [comment]
> 
> 
> > The map got a new name (im my case from "Alps_West" to "Alps_West (OAM)"), which is probaly work as designed.
> 
> @bekuno Can it be that you are using the map downloader for FZK "since day one"?
> 
> In the beginning the file name was without suffix, but later on I added the "(FZK)" suffix to easier distinguish between maps with the same name, but coming from different map servers. So an update to an map downloaded in the beginning got the new name, without deleting the orignal file.
> 
> I guess you can simply delete the two files without "(FZK)" in the name.

I tried the downloader some month ago. But this is on my active caching device, so it was at least in a beta release. 
That is why I asumed that the renaming was planned.
I deleted the 2 files without "(OAM)".
For me it is ok that no code change for this problem will be done.

**Comment by jakedot** [comment]
> For me it is ok that no code change for this problem will be done.

I would be asking the question who was in control of the display name change (probably us? If so, we are responsible for cleaning this up and not wasting user's disk space)

**Comment by moving-bits** [comment]
> Seems that we should target the "latest" folder instead of the specified year/month version. I'll have a look at it.

I've created a PR that will always use the "latest" subfolder instead of the specific yymm version, so we'll always get the most recent one.

Regarding the downloading / unpacking error, I'll create a separate issue for easier tracking.

**Comment by jakedot** [comment]
the OAM maps are also updated, and apparently Bernd had one of those installed before they were renamed. Nothing to do with FZK otherwise...

**Comment by moving-bits** [comment]
I propose to close this issue:
- The original issue was opened due to a server-side error (having updated the map files, but still linking to the old folder names in the repository file). => This is something we cannot prevent, but with PR #11876 we replace the "year-month" folder part retrieved from the repo and replace it with "latest", so as long as they link their "latest" folder to the most recent one, we are on the safe side. (And if they don't, then we do not have a real chance to detect this error anyway.)
- A second issue mentioned here was the renaming of OSM map files from "country.map" to "country (OSM).map". => As this was during early development stage, thus affecting early nightly users only, we have decided to not fix this.
- A last issue is the fact, that c:geo does not recognize if a misbehaving repository file gets fixed after a couple of days. => This behavior is intentionally. We have a built-it update check which fires every x days, and only retrieves the repository file when this limit is hit. As we do not want to create additional server traffic, there is no way to detect files changes before reaching the next update interval. => Won't fix.

Therefore let's close this issue. If anything new arises, let's open dedicated issues for it.
