### ISSUE TITLE
What's next about the bottom navigation?

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11841]
In our today's meeting, we have agreed that it's the right time currently to finally merge the new bottom navigation to master (PR #10928).

Let's start with some screenshots, showing the current implementation state:

![grafik](https://user-images.githubusercontent.com/64581222/136713094-4cb4eda6-27d1-489b-a142-5b5f0088fc52.png)

### optional ideas which came up in the last months
- [ ] hide bottom navigation while keyboard is active - see https://stackoverflow.com/questions/43115510/hiding-bottom-navigation-bar-whilst-keyboard-is-present-android
- [ ]  bottom navigation background color (light theme)
- [ ] move initialization code out of main activity (or should we keep it there to not overload the splash activity?)
- [ ] allow selecting the startup screen
- [ ] update/status notification should be covered somewhere else than only in the dashboard 
- [x] blue notification badge besides "more" item if user has status message
- [x] long press function on stored (used to quickly jump to certain list)

### refactor map hierarchy handling (would be pretty cool, but needs to be done by someone who has more knowledge)
- [ ] map should be top-level when showing offline lists (see #11461 for a proposal) 
- [ ] map should be top-level also for other paths (e.g. when map gets opened from compass view or lists) 
- [ ] enable live / remove target when reselecting map menu item
- [ ] potential conflict: "Enable live" is disabled for waypoints #6740

**Comment by fm-sys** [comment]
@ztNFny after using the nightly for some days, does it still feels like it's wasting a lot of space on the map? 

I can only speak for myself, but I got used to it pretty quickly... But if there are more people with that feeling, I'm totally fine with implementing some "hiding mechanism"

**Comment by fm-sys** [comment]
> As it doesn't show on "lists"-map i have hardly seen it 😉 that's one of the issues i have with it.

Yes, that another story. Actually, I wanted to implement it in a different way, so that "show on map" launches the map as top level activity. But that wasn't possible yet in a good way, without much code refactoring.

> but give me till next week please.

I will wait ;-)

**Comment by ztNFny** [comment]
First of all, what's already there looks quite good! I never liked the old dashboard, but of course "something" was needed and there the bottom nav is way better.

That said, I don't like the "simple" transformation of dashboard to bottom bar. As I see it they fulfill different purposes:
- Dashboard is a START page from where you then access different parts of the application. You use it once when starting the app (or at least seldomly)
- Bottom nav is a navigation tool used DURING the usage of the app
The buttons that are currently in there are valid targets when starting into the app, but not so much for switching between them when already using the app. Like looking at the icons that are on dashboard/nav there's "Live map" and "Nearby" which are both a search for caches around you, just the representation is different (map vs list). Having just one of them ("Live") with a switch Map vs list would do the same - and that switch already exists, the "Show on map" button in toolbar

(Personally I never use either Live map nor Nearby, I only use offline lists (when I want to use live map I first open the map, then enable live), so right now 2/5 of the toolbar is taken by something I'll never use. With Dashboard that wasn't an issue as I only saw that shortly during startup, but now it's "wasted" always.)


So I thought, how can the toolbar be made more efficient for "during use" application? cgeo has more or less 4 views today:
- list
- map (2 different maps actually right now, one with and one without toolbar)
- cache details
- search

So let's focus on these, what I come up with a general bottom toolbar and one for cache details (more on that later, only talking about the general one now):
![image](https://user-images.githubusercontent.com/1258173/137629278-13674c46-444a-4e08-bdb1-07e373ecec4c.png)

Search should show a search field on top of the toolbar (like the one on Dashboard today), long click could open the search activity. This would also place the search field at the bottom, making it more accessiable on todays large screens.

The 3 buttons [Live toggle] [Map View] [List view] work together:
If you're on a list [Map view] replaces the current "Show on map" that's available in toolbar, so you can quickly switch between map and list view.
[Live toggle] + [Map view] = the current "Live map"
[Live toggle] + [List view] = the current "Nearby"


Workflow examples. You start c:geo and want ...
- live map: enable live (if not already enabled) + map
- nearby: enable live + list
- list: select list (like today)
- list on map: map


Then for cache view:
I think bottom nav should replace the current tabs there. At first maybe just 1:1 replace them, but I could also think about some improvements and alignments in workflow there: Have a map button like on the "main" nav, then on the map instead of the "List" button show a "cache details" button to go back to the cache view.


@fm-sys Not sure if the above text works to convey what's in my head. We could also have a call to try to explain it better if you're interested.

**Comment by MagpieFourtyTwo** [comment]
I think, the current bottom navigation is a good start - but mainly lacks the possibility to get back to the status antes quo.

For example like described in FR #11926: A route, planned in ``Live map``, will immediately and irretrievable get lost once you chose a different activity. Or even when you just had a quick glance at the dashboard (for whatever reason) ...
Same with ``Stored`` lists: Have a look at a list, change to e. g. ``Live map`` and then back to ``Stored``: The previous position will be lost.
This is completely different to the way c:geo acted in former times, when you always had a possibility to get back ...

This can possibly be solved if the activities would not replace each other and start over from scratch every time the button is clicked, but would live side by side.
I. e.: On change e. g. from ``Live map`` to ``Nearby``, the state of ``Live map`` should be saved and restored after coming back(!) to the ``Live Map``. Which IMO is most probably the behavior, a "normal" user would expect ...

**Comment by MagpieFourtyTwo** [comment]
WRT the ``Search`` button: I agree, and would really like to e. g. see a long click action, which gives the functionality of the magnifying glass in the dashboard (i. e. "Search for GC codes, names etc" and "Cache View History").

**Comment by fm-sys** [comment]
> 
> 
> > > Maybe it could auto-hide on map view?
> > 
> > 
> > This would definitely be possible, and other apps are doing this as well. Although, I'm not sure if this will rather confuse users...
> 
> Seeing that Google Maps as THE most popular map app is doing it it should be ok. Others like Locus also do auto-hide btw.

Coming back to the auto-hide functionality. This could look like this: 

The animation needs to be improved for sure, but is this wanted in general?

![Animation](https://user-images.githubusercontent.com/64581222/140982701-4b0bf46e-15fe-4a89-81b8-0478057f27dd.gif)

**Comment by MagpieFourtyTwo** [comment]
8 would *strongly* vote against (auto) hiding the bottom navigation buttons, cause currently the absence of these buttons are a clear sign for the user that he can safely use the back button to get back to e. g. the caches details.
And the presence of these buttons are the only always visible sign for him that the back button will terminate the program.

Thus hiding this "main activity indicator" will just take clarity away and massively reduce usability of in app navigation. Apart from the fact that it will kill the only advantage of bottom navigation (speed and saving clicks), i. e. will finally render bottom navigation *completely* useless, which should be avoided, esp. as benefits are already now hard to tell anyway.

**Comment by fm-sys** [comment]
> 8 would _strongly_ vote against (auto) hiding the bottom navigation buttons

Fair enough. I'm as well not a fan of apps doing things like this. It had looked quite easy to implement, so I gave it a try - which does not necessarily mean that we need to go this way.

**Comment by fm-sys** [comment]
Seeing that we are ready for the bottom nav release and nearly no negative beta feedback arrived, I guess we can close this general "introduction issue".

Individual aspects should rather be discussed in separate issues...
