### ISSUE TITLE
Beta users are missing the function of big smileys

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11901]
### Describe your problem!

Users of beta version 2021.10.11-RC report, that they formerly used the "big smileys on map" option, but its no longer there and no large smileys are shown.

Indeed I could not find the function anymore...why was it removed?

### How to reproduce?

Open Settings - Map

### Actual result after these steps?

No such option for big smiley icons

### Expected result after these steps?

Feature should be kept
It was in fact introduced to help people easily identify found caches and not rely on the small overlay.

### Reproducible

Yes

### c:geo Version

2021.10.11-RC

**Comment by fm-sys** [comment]
A bit off-topic, what about using the "big emoji" setting for "corrected coordinates" and "visited waypoint" as well?

![Screenshot_20211015_145535_cgeo geocaching](https://user-images.githubusercontent.com/64581222/137490528-7d81f617-3972-4b30-a269-092f087ccc1d.png)



![Screenshot_20211015_145504_cgeo geocaching](https://user-images.githubusercontent.com/64581222/137490534-f0ef5050-0990-4694-be40-77c16d2632e8.png)

![Screenshot_20211015_105523_cgeo geocaching](https://user-images.githubusercontent.com/64581222/137490539-4f9e7f4f-ca0e-4cec-a303-bc9f9c25c727.png)

Not sure through, weather we should invert the check marker on big emoji style, so that we still maintain our "waypoint" style (colored icon, white background).

**Comment by fm-sys** [comment]
> At least for the "corrected coordinates" we got a few feature requests on support already

Just remembered, we even have an extra issue for it: #10924

**Comment by Lineflyer** [comment]
This issue was a misunderstanding it seems...and while checking it I simply overlooked the menu.
Closing here (issue for corrected coords in big already exists).
