### ISSUE TITLE
No possibility to load more caches on search results

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11941]
### Describe your problem!

Not sure whether its a bug or a feature request.
Was reported by users on support mail and reproducible for me.

Since we introduced the "new search" there seems to be no possibility to load more than the 200 results.

### How to reproduce?

Users report the need to do that for e.g. following scenarios:
- Search for hidden by a user which has hidden more than 200 caches and your desired caches is not within the first 200
- Search for a keyword which returns more than 200 results and your expected result is not within the first 200

### Reproducible

Yes

### c:geo Version

2021.10.08

### Additional Information

A bit related to #11489

**Comment by eddiemuc** [comment]
Discussion has run dry here. I will put this issue on my ToDo list to implement as I suggested initially here:
https://github.com/cgeo/cgeo/issues/11941#issuecomment-949291301 

If this is not ok, please move forward. The implementation is kind of complex (need to revise concept of ISearchByNextPage because although it appears to be a connector-abstract-concept, it is in reality hard-bound to gc.com and scraping web pages), so I would appreciate to conclude discussion first before investing the effort

**Comment by eddiemuc** [comment]
PR #12142 is a small-looking but rather deep-changing code change which sets the base to extend the "load next page" functionailty from the sole web-scraping-gc-specific approach to an approach where different next-page-algorithms (two at gc.com, one at oc) can be handled in parallel. I want to get it in before continuing to get the base stable

**Comment by eddiemuc** [comment]
PR #12188 will implement logic suggested above:
- Do paging from all supporting connectors (currently GC and OC)
- Keep initial load size at 200 per connector
- Load another 50 per connector on clicking "more"
- GC legacy connector (for "finder" and "pocket") unfortunately has to stay as-is (because it is tied to what the website can do): load 20 initially, load another 20 for each page.
