### ISSUE TITLE
Repeated update check dialog for routing data

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12153]
### Describe your problem!

I ran into a problem while testing something else on the emulator, did not check yet, whether reproducible.

### How to reproduce?

- Install c:geo normally (completing wizard, logging in)
- Go to Settings - Routing/Navigation and enable auto download of needed routing data, set update interval to 0.
- Go to live map
- Enable a target line to some nearby cache

### Actual result after these steps?

Two issues:
- While routing line is active and mode set to "Walk" still no downloading happens
- When returning from map to home the "Shall I check for updates" dialog is shown. This happens on each startup and each change to the homescreen

### Expected result after these steps?

1. I would expect that auto downloading just takes care to load the missing routing as soon as I first time try to use it. Thats currently not the case (or is it related to the fact, that I declined the auto update check (=Set to 0)).
2. The dialog should only be shown once (if at all as I selected no cyclic update).

### Reproducible

Unclear

### c:geo Version

master of 21.11.2021

### System information

```text
Emulator:

## System information

c:geo version: 2021.11.21-d1dc0c1 developer build

Device:
-------
- Device type: sdk_gphone64_x86_64 (sdk_gphone64_x86_64, google)
- Available processors: 4
- Android version: 12
- Android build: sdk_gphone64_x86_64-userdebug 12 SE1A.211012.001 7818354 dev-keys
- Screen resolution: 1080x2148px (392x750dp)
- Pixel density: 2.75
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 21.24.23 (190800-396046673)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v8, Count:106
- Set language: en_US (system default)
- System date format: M/d/yy
- Time zone: GMT
- Debug mode active: no
- Last backup: never
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Google: Map
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleMapSource
  - Atts: none
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: None ([:inconclusive=false:advanced=false])
- OFFLINE: None ([:inconclusive=false:advanced=false])

Stored Filters (#0):

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
- Geocaching.com date format: yyyy-MM-dd
- Routing: internal / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (4.0 GB free) v3 internal isDir(6 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (4.0 GB free) v3 internal isDir(6 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (4.0 GB free) v3 external non-removable isDir(2 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (4.0 GB free) v3 internal isDir(0 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=6, dirs:>=8, totalFileSize:>=1.1 GB, free space: 4.0 GB, files on device: 393216)
  - OFFLINE_MAPS: /cgeo/maps (Default)[/cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps, Av:true, files:6, dirs:1, totalFileSize:1.1 GB, free space: 4.0 GB, files on device: 393216)
  - OFFLINE_MAP_THEMES: /cgeo/maps/_themes (Default)[/cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps%2F_themes, Av:true, files:2, dirs:0, totalFileSize:468.1 KB, free space: 4.0 GB, files on device: 393216)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 4.0 GB, files on device: 393216)
  - GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 4.0 GB, files on device: 393216)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 4.0 GB, files on device: 393216)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 4.0 GB, files on device: 393216)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 4.0 GB, files on device: 393216)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:83.5 KB, free space: 4.0 GB, files on device: 393216)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 4.0 GB, files on device: 393216)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 4.0 GB, files on device: -1)
- Map render theme path: 
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (Nov 21, 8:55 PM):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v98, Size:200.0 KB) on system internal storage

--- End of system information ---
```

**Comment by moving-bits** [comment]
> Two issues:
> While routing line is active and mode set to "Walk" still no downloading happens
>
> I would expect that auto downloading just takes care to load the missing routing as soon as I first time try to use it. Thats currently not the case (or is it related to the fact, that I declined the auto update check (=Set to 0)).

IIRC (not having the source code at hand currently) I have implemented the check for missing routing data in a way, that it checks only once per session for each missing routing tile. If auto-download is disabled or you declined the download of missing routing data once, you won't be asked again for that routing tile during the same session. (This is regarding the "missing routing data" check in the map.)

> When returning from map to home the "Shall I check for updates" dialog is shown. This happens on each startup and each change to the homescreen
>
> The dialog should only be shown once (if at all as I selected no cyclic update).

Strictly speaking, setting the interval to zero means "check every zero days", effectively meaning "check every time". Disabling the check is done by unchecking the checkbox for automatic download.

If requested I can change the behavior for "0" to be the same as "disabled". 
(We could and maybe even should then remove the checkbox to avoid situations like "I have enabled auto-update, but it's not checking for updates - because interval is set to 0". Or do we have the need to support something like "ask for missing routing tiles, but never ask for updates"?)

**Comment by Lineflyer** [comment]
> Strictly speaking, setting the interval to zero means "check every zero days", effectively meaning "check every time". Disabling the check is done by unchecking the checkbox for automatic download.

Interesting to know.

I regarded "Auto download missing routing data" to be separated from the slider "Update interval", because the first one means whether I want to load data at all while the second one means how to handle updating this data.

> avoid situations like "I have enabled auto-update, 

The checkbox says "Enable auto download" but not "enable auto update"! That's why I misinterpreted its functionality.

IMHO I would like to to be a "Auto download enabler" checkbox and the updating just controlled by the slider, where 0 means no auto update.

**Comment by Lineflyer** [comment]
> IIRC (not having the source code at hand currently) I have implemented the check for missing routing data in a way, that it checks only once per session for each missing routing tile. 

I checked that today:
- The update message shows up when starting c:geo
- I select "Later"
- I go to another activity (e.g. Stored or Map)
- I go to home again
- The update message shows again

**Comment by moving-bits** [comment]
Hm, I have trouble to reproduce those issues in the emulator:

> Two issues:
> While routing line is active and mode set to "Walk" still no downloading happens

The "Do you want to download xxx" dialog should open as soon as some routing calculation is involved (e. g. two caches added to a route, and caches being close enough to each other to trigger routing).
When when you have declined that dialog, c:geo remembers that decision for the session (for the specific tile).

> When returning from map to home the "Shall I check for updates" dialog is shown. This happens on each startup and each change to the homescreen

I don't happen to get that dialog each time I return to the main screen, and even not when switching to a different app in between. I guess you somehow trigger a memory removal of c:geo, so that on reloading c:geo gets again to the point where it checks for updates.

This combined with the "0 = re-check immediately" issue would explain the second part.

Proposal:
- change settings => navigation => update interval to "0 = no update check at all" ("automatic download" does not have to be active to trigger query for update, but update check will only cover tiles downloaded by the automatic download, as only then the required metadata is created)
- change settings => map = >update interval in the same way
- remove "automatic download" checkbox on map page (as its use-case is covered by aforementioned's setting being 0 or non-zero)

**Comment by Lineflyer** [comment]
> I don't happen to get that dialog each time I return to the main screen, and even not when switching to a different app in between. I guess you somehow trigger a memory removal of c:geo, so that on reloading c:geo gets again to the point where it checks for updates.

I don't think this applies. As written today (above) its sufficient to change from Home to Stored and back to Home.
Setting is: Download active, update= 0 days

Maybe 0 days is the problem here?

**Comment by moving-bits** [comment]
Ok, cross-checked against `master` instead of `release` - now I experience the behavior as described, bottom navigation version of dashboard seems to behave different than currently release mainscreen.

But anyway, will be fixed with the code changes that implement my proposal above, have just retested it against.

Need to write a small migration routine for settings, though, as the default value for update check is "30", and if there's no `mapAutoDownloads" setting any longer to stop c:geo from checking, it would suddenly pop-up for many users... (And similar for the routing tile update checker, as I've untangled the connection to "auto tile download" as well.)
