### ISSUE TITLE
"archived" overlay has wrong size

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12173]
![Screenshot_20211123-215424__01](https://user-images.githubusercontent.com/1258173/143634974-ffa23a1c-b49a-48d4-9f5c-584b92bfd92c.jpg)

**Comment by Lineflyer** [comment]
A generic side question to this:
Looking at the comparison between old and new icons on https://manual.cgeo.org/en/cacheicons it looks like while the total icon might have the same size as with old icons the inner icon (not meaning the color circle but the real symbol) got a bit smaller compared to the old icon. Is this only an effect on the manual page (due to different scaling), or is this really the case? Some users mentioned that...

If this is the case, would it be possible to increase the symbol size within the whole icon to increase visibility?

**Comment by ztNFny** [comment]
@Lineflyer The manual page is comparing "just the icon" vs "the composed marker", that's apples and oranges.
