### ISSUE TITLE
Pictures in cache description flickering when opening

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12224]
### Describe your problem!

Reported for release 2021.11.21 but also reproducible on master.
If you open a cache which has a picture in its description the picture flickers (looks like reload/refresh) when initially changing to the description tab.
Does only happen once per opening and happens again if you close and open the cache again.

### How to reproduce?

- Store GC8WEB9 (example with picture on top of listing)
- Leave cache listing (if you opened it for storing)
- Open cache again
- Swipe from details to description tab

### Actual result after these steps?

Pictures vanishes for a short moment (thus text below is moving up) and shows again (thus text below is moving down).
The slower the device the more recognizable is it and can take relevant time and look real ugly.

### Expected result after these steps?

Picture stable

### Reproducible

Yes

### c:geo Version

2021.11.21 and master

### System information

```text
Tested on Android 11
```

**Comment by MagpieFourtyTwo** [comment]
The flickering does appear too, when opening a cache from the magnifier's list:
1. open so called Home screen
2. tap on magnifier in header row
3. tap on any cache listed (BTW: wasn't there an issue why there are just 10 caches displayed, instead of the scrollable list?)
4. the cache list flickers two or three times (if counted right)
5. finally the listing appears

May this be a similar reason or should we open a separate issue for this?

**Comment by fm-sys** [comment]
Isn't that issue a duplicate of  #10985?

**Comment by MagpieFourtyTwo** [comment]
I *knew* that I had heard of such an issue before ... ;)

**Comment by Lineflyer** [comment]
Duplicate of #10985
