### ISSUE TITLE
Settings: Check whether "View settings" is missing entries

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12268]
I just stumbled upon, that the "View Settings" function in Settings - System misses some connector status information.
Might still be due to some changes between `release` and `master`. Not sure.

Left=old Right=new

![image](https://user-images.githubusercontent.com/949669/145096727-b4c4043a-0bd9-4954-9736-697109498f50.png)

**Comment by moving-bits** [comment]
Is the right screenshot coming from a fresh (blank) installation?
Then the difference might be due to the fact that no preference keys are written when the setting screen belonging to it has not been opened yet.

What happens if you open the preference screen for one of the missing settings and change the setting? The preference key should be visible then.

**Comment by Lineflyer** [comment]
Both installation have been clean with running wizard and enabling GC as connector.
Howvver you are partly right.
As soon as I entered the opencaching connector configuration, once enabled, then disabled it again it from now on show up as false in settings.

I just wanted to mention it...but seems no real problem.

**Comment by moving-bits** [comment]
> but seems no real problem.

shouldn't be, as settings not being stored yet resort to some default value (specified in our code).

So I guess we can close here?
