### ISSUE TITLE
enhance log templates

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12293]
> Also the number of templates is fixed now as it's using preferences, 

That doesn't work well, IMHO. There will always be one who needs one more template, and others will call it unnecessary space consumption...

I can try to implement a dynamic solution if this is wanted.

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/6197#issuecomment-991354046_

**Comment by fm-sys** [comment]
Another thing: there shouldn't be an ":" displayed if the template is empty...

![grafik](https://user-images.githubusercontent.com/64581222/145655064-49e5bd98-e126-4019-8119-d914b40d540b.png)

**Comment by ztNFny** [comment]
> Another thing: there shouldn't be an ":" displayed if the template is empty...

Oops, during the last rewrite I dropped the isEmpty from Settings.getLogTemplatePreview and at that stage had all Templates valuated already on my test instance. Just need to check for either key or value there as both are either set or unset.

> others will call it unnecessary space consumption...

I wanted to implement it in a dynamic way but am lacking the knowledge about preferences to do that and noone had any pointers, so the static solution was the next best thing. Only valuated templates are shown in the insert menu, so wasting space shouldn't really be an issue. But of course a dynamic solution is the best way 👍

**Comment by ztNFny** [comment]
If you rewrite this i suggest turning the signature into just another template and adding the ability to mark any template (but only one at a time) for automatic insertion aka signature

**Comment by fm-sys** [comment]
> If you rewrite this i suggest turning the signature into just another template and adding the ability to mark any template (but only one at a time) for automatic insertion aka signature

This is definitely an idea worth to think about. However, I didn't want to revise the whole thing too extensively myself. But if someone else is interested, feel free!

The new "extra log templates" start with `pref_logTemplate1`, so if we want to tread the signature as log template, we can use `pref_logTemplate0` for migrating the signature...

**Comment by MagpieFourtyTwo** [comment]
Is there s/th wrong with my installation or did the manual signature insertion stop to work for some very well known reason?
Remember pretty well that it worked fine a few days ago, but when trying to insert the second or third Signature template this morning, c:geo always inserted the first one ... even re-edited all three of them, but to no avail.

BTW: Would like to see the Signature Title (pref_logTemplate\<N>.Title) in the Section Title (e. g. ``Log Template: DNF`` like in the Log window's ``+`` drop down list) or - if not possible - somewhere else a bit more emphasized, instead of being kind of "hidden" in the same line and even in the very same font as the Sig Text itself, which makes it pretty hard to distinguish between sig title and sig text.

BTW2, as for the wording: The name ``Log Template`` suggests that choosing e. g. ``Template: DNF`` from the ``+`` drop down would replace the entire current sig - which it doesn't do (at least right now - and for very good reasons, I would say, cause otherwise the current Log Text would have to be compared against all the other templates for already done changes, and if changed, replacement should not happen automatically, which is even harder to implement, if placeholders have been substituted ... would most probably need an add. ``ManualChanges`` flag), thus, if these guys will remain to be just text fragments, I would suggest to name them s/th like ``Text module`` or ``Text block`` ...?
