### ISSUE TITLE
[refactor settings] another glitch 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12338]
![Screenshot_20211216_142553](https://user-images.githubusercontent.com/64581222/146380231-b820c85f-8719-4af4-beda-7f3f44b32bfe.png)

Happens on small screens / landscape mode

**Comment by moving-bits** [comment]
Even visible on high-resolution screens.

This is coming from `preference_material.xml`, which is part of `preference-1.1.1` lib:

```
<TextView
    android:id="@android:id/summary"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_below="@android:id/title"
    android:layout_alignLeft="@android:id/title"
    android:layout_alignStart="@android:id/title"
    android:layout_gravity="start"
    android:textAlignment="viewStart"
    android:textColor="?android:attr/textColorSecondary"
    android:maxLines="10"
    style="@style/PreferenceSummaryTextStyle"/>
```

would need a `android:layout_width="match_parent"` instead of `android:layout_width="wrap_content"`.

Is there a way to extend the existing style without having to copy it?
