### ISSUE TITLE
some mipmap/anydpi-v26 files missing

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#12357]
### Describe your problem!

observed when running gradle tasks:

~~~
note: generating mipmap/ic_launcher_nightly_round with config "anydpi-v26" for round icon compatibility.
note: generating mipmap/ic_launcher_nightly_round with config "anydpi-v26" for round icon compatibility.
note: generating mipmap/ic_launcher_rc_round with config "anydpi-v26" for round icon compatibility.
note: generating mipmap/ic_launcher_rc_round with config "anydpi-v26" for round icon compatibility.
~~~

The files does really not exist.

### How to reproduce?

Run some gradle tasks (maybe a `gradle clean` is necessary).

### Reproducible

Yes

### c:geo Version

current master

**Comment by ztNFny** [comment]
Despite the name the mipmap-anydpi-v26/ic_launcher_round file is used only for API 25. It's what Android Studios Asset Studio generates with "Round Icon" option enabled.
API 25 will use legacy icon if round icon isn't present, API 26 will use the adaptive icon.

Imho no need to address this because a) it's only relevant for API 25, b) Android Studio is "intelligent" enough to use mipmap-anydpi-v26/ic_launcher as mipmap-anydpi-v26/ic_launcher_round (the 2 files are usually the same), c) even it AS didn't use mipmap-anydpi-v26/ic_launcher the identical-looking legacy would be used.

**Comment by bekuno** [comment]
We have only `ic_launcher_debug_round.xml` in `mipmap-anydpi-v26`, the other both are missing.
See
![grafik](https://user-images.githubusercontent.com/32555742/146816840-157f94e5-7ff1-419a-8b27-279cb4fe7de0.png)

**Comment by bekuno** [comment]
@moving-bits 
Can you remember - you deleted the both xml in f5eb9321 (fix some lint issues).
Maybe this was too much.
