### ISSUE TITLE
Alternative export path whenever OTG device is attached

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#12394]
### Tell us your idea!

When I am on a bike tour, I sometimes decide to change my mind, and to not follow my pre-planned tour, but instead go a different route (or farther).

In such situations I use c:geo to plan a new route as GPX track and to download caches along the way. I then export all of these data via the export feature and copy them via an OTG cable to my Garmin GPSr.

However, I always have to do the copying manually using the Android file manager.

### What solution would you suggest?

It would be cool, if I could define a secondary export path in the c:geo settings. I would set this alternative path to point to the relevant folder on my Garmin GPSr.

Then, as soon as I open the export feature, c:geo should check whether that path currently exists (because the GPSr is attached via OTG), and if yes, it should use this export path instead of the normal export path.

**Comment by Lineflyer** [comment]
Sounds impossible as we do not have access to the file system anymore since introduction of scoped storage.

Shouldn't it be possible already to use the "Share" feature which is offered after generating the GPX file with c:geo and target your file manager as app, which then offers the storage location (=Your OTG device)?

**Comment by dcjkfgdjhd** [comment]
Hmm, too bad. Is it not possible to grant a permission as we already do for other paths? (Probably the OTG device needs to be attached the first time when you want to grant that permission.) Or does the permission disappear again as soon as the device gets detached?

Interesting idea with the file manager. But I just tested it and at least the default Android file manager (in my case on LinageOS) does not support receiving file paths via the share feature.

**Comment by Lineflyer** [comment]
I just tried with my [favorite file manager](https://play.google.com/store/apps/details?id=com.alphainventor.filemanager) and it works like a charm.

Regarding the permission: 
AFAIK the permission is dropped when removing or it might not even be possible to select OTG devices to grant permission.

Furthermore its encouraged by Android to use the sharing method instead of the scoped storage approach wherever possible and I think we would not want to implement more specific paths with permissions after all. We mainly added the scoped storage to allow sharing of maps with/from other apps, where there is no other good method.

**Comment by dcjkfgdjhd** [comment]
OK, no worries, it would have been a pretty minor convenience improvement in any case! 

Thanks anyway!
