### ISSUE TITLE
New WP calculator - Wrong sequence when filling values

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12404]
### Describe your problem!

Today I used the new waypoint calculator input while doing a mystery.
I totally failed (it showed a far away waypoint) but did not know, what my failure was until carefully trying again.

The problem was, that after entering one value tapping "Weiter" on my keyboard brought me to a wrong input field (out of sequence).

### How to reproduce?

Take this example:
![Screenshot_20211225-173520_cgeo](https://user-images.githubusercontent.com/949669/147389494-0f9eee40-03ab-42a8-b8bd-4c1ada408494.jpg)

Now enter some value for `A=` and press "Weiter"

### Actual result after these steps?

Cursor jumps from A to C

### Expected result after these steps?

Cursor should jump from A to B

### Reproducible

Yes

### c:geo Version

2021.12.25-NB

### System information

```text
Android 11, Samsung S20
```

**Comment by eddiemuc** [comment]
While testing this I saw some more strange effects in the variable listing in the calculator tab too, e.g. in some situations there are "empty spaces" in the table like this:

![image](https://user-images.githubusercontent.com/6909759/147390365-0bd66cf9-a2eb-4970-81a9-aaeb3046c4eb.png)

This table is very very tricky and uses some complex logic behind the scenes due to the "filtering" requirement (only show vars which are used in currently displayed formula, but auto-create and show new vars as user is typing). I clearly have to rework this. Might be a bigger task I am afraid.

**Comment by eddiemuc** [comment]
#12435 fixes the display issue and lays the ground for closing the focus issue (well On was hoping it solves this issue as well but it doesn't). So I reopened here

**Comment by eddiemuc** [comment]
@Lineflyer I noticed that at least in emulator the focus change on tapping "weiter" behaves the same way in old calculator (it moves down instead of left-right-downleft-right...). Was this an issue there as well, or am I missing something here?

**Comment by Lineflyer** [comment]
@eddiemuc 
You are right, in the old WP calc it moves down on "Weiter" and right if you reached the last element of a column. But the variables are sorted exactly in that way on the old WP calc, so it fits.

**Comment by Lineflyer** [comment]
Maybe its the easiest fix (and keeps consistence to the old dialog) to resort the variables like in the old calc?

**Comment by eddiemuc** [comment]
> Maybe its the easiest fix (and keeps consistence to the old dialog) to resort the variables like in the old calc?

No way, I would have to write an own layoutmanager for that :-( Filtering was hard enough to implement

**Comment by fm-sys** [comment]
The layout is perfectly fine. But the focus should move like this:

![Screenshot_20211230_152205](https://user-images.githubusercontent.com/64581222/147760212-159554c2-d564-453f-ae53-a508f6de4a6d.png)


(Note also that the keyboard shows a `-->` instead of a normal return.)

![Screenshot_20211230_152348_cgeo geocaching_copy_123x167](https://user-images.githubusercontent.com/64581222/147760381-942dcfac-7618-4461-89c9-be9e8c7cf84f.png)

**Comment by eddiemuc** [comment]
I have to make myself familiar with focus change options. Anyone knows how to control these things in Android. I will Google this stuff up otherwise...

**Comment by fm-sys** [comment]
No experience myself, but I found the following documentation:

https://developer.android.com/training/keyboard-input/navigation

Also setting this info dynamically seems to be possible: https://stackoverflow.com/a/30591428/13513639

**Comment by eddiemuc** [comment]
Phew, complicated stuff...
PR #12440 should fix this
