### ISSUE TITLE
Improve formula parsing 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12408]
IMHO the current syntax is not 100% intuitive. The situation will become much better, we are more tolerant about using different special characters with the same meaning. E.g.:

|||
-|-
![Screenshot_20211225_021437_cgeo geocaching](https://user-images.githubusercontent.com/64581222/147392390-e62d30a8-8e57-4486-bf21-5733baf47382.png)|![Screenshot_20211225_005048_cgeo geocaching](https://user-images.githubusercontent.com/64581222/147392391-376e9f0c-3918-4e35-a50c-58c1b2bb058f.png)

Furthermore, the multi-char-variables parsing could be improved. If the first character is not defined as variable, take the next characters until the name it is known as valid variable. 

And last but not least: Do variable names really need to be case sensitive? 

![Screenshot_20211225_022144_cgeo geocaching](https://user-images.githubusercontent.com/64581222/147392392-d0e76f9c-0cb6-4975-91fb-146ff855fb9a.png)

**Comment by eddiemuc** [comment]
Allowing `,` as decimal Point and strings with `"` is easy enough to do. Also the error strings can be improved.

Whether vars should be Case-sensitive of not can be discussed in length... I made then Case-sensitive because they are also Case-sensitive today. But I have no strong opinion here.

I have unfortunately to oppose against the idea of making variable parsing depending on which other variables are currently defined in the context of the cache. This would make the parsing of a formula no longer "self-contained" (the same formula string has to be interpreted differently depending on the context it is used in, and it has to be reinterpreted ever time this context changes e.g. a new var is added, removed or changed for the cache), and this will totally break many concepts of formula. Actually I wanted to implement it this way first but gave up after some very long nights trying to get the logic straight and peformant. Since I assume that in 98+% of all cases people will use one-letter-vars only anyway, this is really not worth the effort and the complexity.

**Comment by fm-sys** [comment]
>in 98+% of all cases people will use one-letter-vars only anyway

Variable names like x1, x2, ... are quite popular as well.

Another example:
From time to time I do physics/math mysteries. For instead of using a normal calculator I tried to use the new formula feature. However, I don't want to use a random character but rather use meaningful names for interim results.

Are there really no more intuitive ways? Or in general, how can I currently reference a longer variable name in a formula at all?

**Comment by fm-sys** [comment]
> Are there really no more intuitive ways? Or in general, how can I currently reference a longer variable name in a formula at all?

I would maybe suggest the following:
`hello1` -> h, e, l, l, o, 1
`(hello)1` -> hello, 1
`(hello1)` -> hello1

Do you really think that concatenation should really play such a prominent role as it is currently implemented? What would be the use case for it? Or is it really necessary at all?

**Comment by eddiemuc** [comment]
> > Are there really no more intuitive ways? Or in general, how can I currently reference a longer variable name in a formula at all?
> 
> I would maybe suggest the following:
> `hello1` -> h, e, l, l, o, 1
> `(hello)1` -> hello, 1
> `(hello1)` -> hello1
> 
> Do you really think that concatenation should really play such a prominent role as it is currently implemented? What would be the use case for it? Or is it really necessary at all? 

There was a longer discussion about the same topic already with @moving-bits  some time ago...

Currently variables with more than one digit are references using the $ sign. E.g. 

`$hello * 5 + $hello1A` has two variables hello and A. With hello=1 and A=2 it would evaluate to 1*5+112 = 117

@moving-bits suggested to use some other variable name marker. For example [hello] or <hello>. I am open for this. But we can't use (), they have a different meaning.

Concatenation is used all the time in geocaching especially for coordinates in Multis/mysteries. E.g. something like the following: N41 12.ABC E12 44.A(A+1)(B-5)

**Comment by eddiemuc** [comment]
See e.g. GCBuddy which is doing concatenation the same way

**Comment by fm-sys** [comment]
> Concatenation is used all the time in geocaching especially for coordinates in Multis/mysteries. E.g. something like the following: N41 12.ABC E12 44.A(A+1)(B-5)

That's right for sure. However, concatenation is always used in context of coordinates, but never for individual variables (proof me wrong ;-)). As coordinates can't be stored in a variable anyway but only in the WP calculator instead, it would IMHO be totally consistent to apply concatenation only there...

**Comment by fm-sys** [comment]
But let's continue this discussion in https://github.com/cgeo/cgeo/issues/12417 instead. This issue here was mainly about accepting more common specific characters in our syntax...
