### ISSUE TITLE
View not updated after changing map design style

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12457]
### Describe your problem!

After changing the map style (e.g. from Hiking to City) the change is not reflected on the screen until leaving and reentering.

### How to reproduce?

- Open live map using offline map
- Select Menu - Theme options
- Change the style from the current selected(A) to another style(B)

### Actual result after these steps?

Style A still shown as active

### Expected result after these steps?

Style B shown as active

### Reproducible

Yes

### c:geo Version

2022.01.01-NB

**Comment by MagpieFourtyTwo** [comment]
Same over here - although I don't have to leave the settings dialog, it's "sufficient" to make the selection change a second time to see the new value.

JFTR: If you leave the settings dialog right after changing the setting for the first time (i. e. while you still see the old value displayed), the map will nevertheless be changed to the new (previously not yet shown) value.

**Comment by eddiemuc** [comment]
Does this also happen in release/production?

**Comment by Lineflyer** [comment]
Not sure, but I used that menu quite a lot recently and never seen the problem. So my guess would be it was introduced recently (maybe due to the change with the design legend just below?).

**Comment by moving-bits** [comment]
Design legend (PR #12292) is not yet merged, still WIP

**Comment by Lineflyer** [comment]
> Design legend (PR #12292) is not yet merged, still WIP

No, I mean the prepended "[P], [R], etc. " with the explanatory sentence on top.
This sentence actually flickers shortly after changing the design type....that made me think, that it might be related to this problem here.

**Comment by moving-bits** [comment]
> > Design legend (PR #12292) is not yet merged, still WIP
> 
> No, I mean the prepended "[P], [R], etc. " with the explanatory sentence on top.

Ah, I see. Hm, as this is only adding an empty preference to display some text, I don't think that's the culprit here.

But having scanned the more recent PR I guess it might be PR #12296 (migration of render theme settings from old preferences to AndroidX preference). I'll cross-test...

**Comment by moving-bits** [comment]
Hm, just cycled through the options, and over here it did work. Test environment was:
- emulator
- OAM map for Washington State
- Elevate theme

Cycling through the options for map style: hiking, city, cycling, mountain bike gave me the following maps (without doing anything else than selecting a new style, pressing back button to go to map, then again opening the "theme options" menu:

|hiking|city|cycling|mountain bike|
|---|---|---|---|
|![image](https://user-images.githubusercontent.com/3754370/147884537-4f190d5a-98ab-4b96-8129-deb19bbbf23c.png)|![image](https://user-images.githubusercontent.com/3754370/147884543-eefc97ca-3df8-425a-9c32-bc3b5a62d83e.png)|![image](https://user-images.githubusercontent.com/3754370/147884548-659fb1b6-0593-4ac8-ba96-1968d7949ed3.png)|![image](https://user-images.githubusercontent.com/3754370/147884550-12bbd75a-459c-4757-8e30-58d221830d9e.png)|

Can you describe your proceedings a bit more in detail, so that I can try to reproduce? Thanks.

**Comment by MagpieFourtyTwo** [comment]
> gave me the following maps 

I think there is a misunderstanding: AFAIUnderstood @Lineflyer, he did not mean the change of the map contents (which works perfectly fine over here, too), but the settings dialog itself, as changing the style by selecting a different entry does subsequently not refresh the settings page. Although you switched the setting from e. g. "Hiking" to "City", the settings dialog will still say "Hiking" and show it's settings, although there is already "City" active.

**Comment by Lineflyer** [comment]
Exactly as @MagpieFourtyTwo described. Sorry for being not precise enough in my initial post?!

**Comment by moving-bits** [comment]
Thanks for clarification (and sorry for my misunderstanding). 
PR #12462 should fix the issue.
