### ISSUE TITLE
[Variables] what should be done by "Tidy up"? 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12497]
Currently, variables are listed in the order they where created. IMHO sorting them alphabetically would make more sense...

**Comment by eddiemuc** [comment]
I thought it might make more sense if new created variables are placed on top (so user sees it right away and can edit it). Clicking on "Tidy up" will then (among other things) sort the list alphabetically

**Comment by fm-sys** [comment]
> Clicking on "Tidy up" will then (among other things) sort the list alphabetically

Some weeks ago I had used that button and all variables where gone. I hope this was a temporary bug. But that's why I didn't dare to use the button again until now. But if it works, fine! 

Out of interest: What are these "other things"?

**Comment by eddiemuc** [comment]
> Some weeks ago I had used that button and all variables where gone. 
> ...
> Out of interest: What are these "other things"? 

Button does following things:
* Creates variable entries for all vars needed by any other var which are not yet available
* Deletes all vars with empty formula which are not used by any other formula
* Sorts alphabetically

The second point may be responsible for the deletion of all vars in your case. If not then this is a 🪲 bug.

And the behavior itself can be discussed of course. The removal is meant for cases where one accidentally created too many vars while typing eg in calculated waypoints (due to var auto reaction there)

**Comment by fm-sys** [comment]
My opinion:
Sorting alphabetically is perfect, deletion of (unused) vars with **empty formula** is ok as well.

But we should never ever delete unused vars, when the user has already entered important data. Otherwise this can be _very_ frustrating if something really important gets accidentally deleted and there is no way to undo...

**Comment by fm-sys** [comment]
Reading your post again, it seems it should already be implemented like this. Will retest...

**Comment by eddiemuc** [comment]
> But we should never ever delete unused vars, when the user has already entered important data. 

Same opinion here, and it is implemented this way. Vars with a non-empty formula are never deleted automatically.

(If this happens then this is a clear bug)

**Comment by eddiemuc** [comment]
I like the idea to discuss what should happen on "tidy up", especially whether it even makes sense to "group" different actions this way or whether better to offer them separately (or not at all).

One thought I had was to offer the three actions behind "tidy up" as single selectable actions in a list when one makes a long-tap on the "tidy up" button.

Another idea (as also suggested by @fm-sys earlier) would be to keep the var list alphabetically sorted all the time - hence no need for a sort action

**Comment by eddiemuc** [comment]
@fm-sys I checked and you were right: "tidy up" **does** currently remove all vars in the var list (actually it does not remove themn but just filters them away from the view). This is a bug I introduced when implementing the filtering for the var list in the calculated coordinate dialog. It will be fixed with PR #12500. Sorry for this.

**Comment by eddiemuc** [comment]
Is this issue still relevant?

**Comment by fm-sys** [comment]
> Is this issue still relevant?

I guess all remaining things are tackled in #12535 / #12582, so we can close here...
