### ISSUE TITLE
[Coordinate Parsing] additional measurements to discuss

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#12512]
In context of issue #12511, there were additional measurements discussed which I tried to summarize here for further discussion:

For those additional discussion is needed to decide about implementation. 
* Should the "filling up" with leading 0 also occur for other coordinate parts? (e.g. degree or seconds)? For example, should `N50.A°` with `A=56` become `N50.00056°` or `N50.56°`? 
* Should there also be a rounding of decimal places? For example, should `N50° 00.A'` with `A=1238` become `N50° 00.124'` or `N50° 00.1238'`?
* Should there be cases where **no** leading 0 should be added? For example, should `N50° 00.12'` (no variables here) become `N50° 00.12'` or `N50° 00.012'`? What about e.g. `N50° 00.A2'` with A=1? What about `N50° 00.12*1'`?

**Comment by ztNFny** [comment]
> Should the "filling up" with leading 0 also occur for other coordinate parts? (e.g. degree or seconds)? For example, should N50.A° with A=56 become N50.00056° or N50.56°?

In DD N50.56 is perfectly valid, so I vote for keeping that without any padding.

> Should there also be a rounding of decimal places? For example, should N50° 00.A' with A=1238 become N50° 00.124' or N50° 00.1238'?

Never seen rounding applied in such a way. However what I've seen is this situation where the expected result was then "N50°01.238" - but it's impossible for a calculator to "know" that.
Such a result (1238) is more likely to be caused by wrong variable (or formula) input and will be easily noticed by the cachers brain.exe. Ideally we'd notify the user about unplausible inputs (but it'll not be possible in all cases) - so at least we should show the plain result of the calculation (prominently) to make it easy for brain.exe to discover it.
How about showing the plain calculation result in waypoints list where the waypoint note is shown, right under the "parsed" coordinates?

> Should there be cases where no leading 0 should be added? For example, should N50° 00.12' (no variables here) become N50° 00.12' or N50° 00.012'? What about e.g. N50° 00.A2' with A=1? What about N50° 00.12*1'?

For inputs with a recognized coord format (DMM, DMS) the padding should always be done imho

**Comment by UniQP** [comment]
I searched for caches that don't want the padding (leading zeros) for DMM and the only one I found is [GC8CJ4W](https://coord.info/GC8CJ4W), which explicitly mentions the exception at the end of the listing. So always adding padding seems fine.

**Comment by eddiemuc** [comment]
I believe everything is now implemented as discussed here. So I am closing. Feel free to reopen if I missed something
