### ISSUE TITLE
Hide individual route button not working

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12589]
[...]
BTW: The "Hide Individual route" button seems to do nothing at all, at least over here ... strange.

_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/11896#issuecomment-1019354796_

**Comment by moving-bits** [comment]
@MagpieFourtyTwo

I did a (very short) retest on current `release`, and for me it did work. Do you have some steps on how to reproduce?

**Comment by MagpieFourtyTwo** [comment]
Had the same experience this morning, big surprise cause it suddenly worked ... but after playing around with it for a while it turned out that although it seems to work with OSM, it most definitely does not with GMap and GSat.

Just create an individual route, no matter in which map, and try to hide it in GMap or GSat: on hiding the route nothing happens at all, on un-hide it vanishes for the fraction of a second, then appears again. 

Therefore I first assumed it may be a refresh problem, but if you set the individual route to "hide", then leave ``Live map`` via e. g. tap on Main Activity ``Stored`` and then return to ``Live map``, the setting is reverted to "show". So perhaps it may be related to the show/hide-setting ...?

**Comment by moving-bits** [comment]
Thanks for the additional info. A fix is prepared with #12607.
