### ISSUE TITLE
map state indicator (badge) in bottom navigation map icon

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#12593]
From my user perspective, labeling it just as a 'map' would not be confusing. In my eyes, it is only a live map when updates are activated. (I use it very often just as a map with gc stored offline because of bad internet connection outside) Here you could add a small symbol on the map at some border to indicate the 'live modus' (e.g. red dot). Otherwise, I recognize the live map only by the fact that the bar at the top of the map moves when I look at another map section.

_Originally posted by @andrcoding in https://github.com/cgeo/cgeo/issues/12573#issuecomment-1019284558_

**Comment by fm-sys** [comment]
A badge does only make sense if the meaning is clear. And I doubt, that users will think about live vs offline map, when seeing a dot in the bottom nav.

Btw, Map vs Live map is already indicated in two ways, do we really need a third one? 




![Screenshot_20220123_091621_cgeo geocaching](https://user-images.githubusercontent.com/64581222/150670430-bdb5d5d8-d2d3-45ee-a700-447f106c7bd5.png)|![Screenshot_20220123_091641_cgeo geocaching](https://user-images.githubusercontent.com/64581222/150670431-0afe4971-07dd-4a5d-9e8d-4d2cccb85076.png)
-|-
![Screenshot_20220117_071508_cgeo geocaching](https://user-images.githubusercontent.com/64581222/150670447-873289bc-3ad3-428d-9e5c-bda021479658.png)|![Screenshot_20220123_092251](https://user-images.githubusercontent.com/64581222/150670433-79acb19c-f6d0-4f50-a38a-ea57577037fb.jpg)

IMHO it's better to have one meaningful indicator instead of three which no one understands.

**Comment by bekuno** [comment]
You only see this icon in the standard map mode (with active bottom navigation).
If you are in filtered mode (single cache or from a list) then neither the bottom navigation nor the icons are visible.
With an indication (badge) in the bottom navigation you will see the state also when you are using "Search" or "Nerby".

**Comment by fm-sys** [comment]
But why should I ever be interested in the map state when being at "Search" or "Nerby"?!

**Comment by bekuno** [comment]
> But why should I ever be interested in the map state when being at "Search" or "Nerby"?!

Ok, my bad - this is no general offline switch.
Normally I set the phone in Offline mode, if I will save the data volume (and power :) ).

**Comment by andrcoding** [comment]
My post was just to show my preference that the renaming of the label "live map" to "map" is fine out of my perspective. So far I haven't really looked at the very top label switching its name by switching the modus. I agree that this is enough to indicate the current selected option. The labels "Aktualisierung ausschalten/einschalten" I do not see but I don't miss them so that is fine.

**Comment by fm-sys** [comment]
Reading the conversation, it sounds like we can close here... Correct?
