### ISSUE TITLE
WP Calc - Unexpected result

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12595]
### Describe your problem!

Today I prepared some multi caches for the caching day, entered formulas and tested them by providing some values.
While doing that I stumbled upon the problem below.

It however vanished after upgrading to newest nightly.

@eddiemuc 
Could this be a sporadic problem or do you confirm its solved already within the last few days?

### How to reproduce?

![Screenshot_20220123-121448_cgeo](https://user-images.githubusercontent.com/949669/150675798-c1b8c3fe-b26e-4b3d-946c-f447843f28ea.jpg)

### Actual result after these steps?

See above

### Reproducible

Unclear

### c:geo Version

2022.01.18-NB

### System information

```text
Samsung S20, Android 12
```

**Comment by eddiemuc** [comment]
This was a previous behaviour in implementation. At this time, a calculation like `15.686 + 2*B` was evaluated as a whole (`15.686 + 4 = 19.686`). 

With already created (but not yet merged) PR #12585 the behaviour will change to separate evaluations of the part before and after a digit. So `15.686 + 2*B` will be separated into two formulas `15` and `686 + 2*B` which will be evaluated on their own and then concattenated again (and many many other new rules...). Since `686 + 2*2 = 690` this will then result in `15.690` as follows:

![image](https://user-images.githubusercontent.com/6909759/150676964-a8f58d88-868d-4ad8-a7c6-562c4f5a648e.png)

**Comment by eddiemuc** [comment]
Update: I just checked, the change relevant for this is already on master (this is why the behaviour changed on update). But the PR mentioned above will change the formula parsing behaviour again significantly, so it makes sense to retest after it is merged.

**Comment by Lineflyer** [comment]
OK, so this is already done then :)
