### ISSUE TITLE
Attribute coloring consistence

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12602]
Beta users feedback from our facbook page:
Also it seems that not all attributes have colors logically: not a night cache, no tree climbing required and no team work required are black when positive versions have red background. I'm not entirely sure about the selected colors, especially red as it has a strong association towards the negative version of the attribute instead of belonging to the red group. Other than that the idea of grouping them by similarities is welcomed.

---

I did not check correctness of this statement, so it needs to be checked, if its really as described by the user.

**Comment by moving-bits** [comment]
IIRC there was a discussion about importance of the "tools group" attributes:
- When positive, they should be highlighted, because you probably have to bring a certain tool to be able to do the cache, therefore the red background. 
- But when negative (e. g. "no special tool required") they do not have a special importance, therefore we decided to give them a less flashy background.

So (without having cross-checked the mentioned attributes) I guess "it works as is intended", but we might discuss whether coloring consistency is of higher importance to as than the differentiation described above.

**Comment by ztNFny** [comment]
> not a night cache, no tree climbing required and no team work required are black when positive versions have red background.

Works as designed. Red is intended as eye-catcher to point to special stuff - like you need to bring some equipment - that's important to know. Not needing to bring the equipment is not important as it's the default.

> I'm not entirely sure about the selected colors, especially red as it has a strong association towards the negative version of the attribute instead of belonging to the red group.

Red as chosen as "important" here and the difference between the normal and striked through version is huge, no danger of confusing them.

**Comment by Lineflyer** [comment]
Thanks for clarification, will provide feedback to user.

I also think its "works as designed" thus closing.
