### ISSUE TITLE
Support attribute filtering on live map

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#12736]
### Describe your problem!

If I use the live map and set an attribute filter on, I don't see any caches unless they're stored locally OR I've just opened them (to check their attributes)

### How to reproduce?

1. Open map, have 'Live map' enabled.
2. open filters, set GC 'dog friendly' attribute (For example)
3. save filter (filter says "Cache attributes:dogs_yes")

### Actual result after these steps?

The only caches that are shown are those saved locally or those you've previously opened.

### Expected result after these steps?

All (and only) dog friendly caches should be shown

### Reproducible

Yes

### c:geo Version

2022.01.22-RC

**Comment by Lineflyer** [comment]
That is due to the fact, that the data set for "pure live caches" does not contain attribute information. thus the filter does not apply. Only those caches on the map, which have previously been downloaded/stored will be filtered.

The only thing you can do is to use the advanced filter mode and active to include inconclusive results (= those where c:geo does not have the attribute information yet)...but of course those might be with or without that attribute.

**Comment by alan666notb** [comment]
Err ... don't quite understand that!

What do I say to someone on UK geocaching FB page who reported it?

**Comment by eddiemuc** [comment]
> Err ... don't quite understand that!
> 
> What do I say to someone on UK geocaching FB page who reported it?

The gc.com webapi we use to do our searches does not support filtering by attributes. It also does not provide cache attributes in the search result, so we can't do the filtering on the result on our side. gc.com has a v2 of that webapi which supports attribute filtering but this webapi version is not available to c:geo.

Caches which have been downloaded by c:geo completely before (by scraping the cache detail web page) can be filtered by c:geo because we have the attribute info available. But "pure" online search results can't be filtered.

**Comment by alan666notb** [comment]
Err ... nope, still haven't got it!

Why do we offer the attribute filter if it can't possibly work?

**Comment by eddiemuc** [comment]
> Why do we offer the attribute filter if it can't possibly work?

It works perfectly fine for  stored lists. It does not work currently for live searches (it is unfortunately also not supported by opencaching)

**Comment by alan666notb** [comment]
Well ... this is not great!

The function should either work on the live map, or not be available.

**Comment by fm-sys** [comment]
The feature works very well also on the live map - as long as caches are stored offline.

BTW, we have also discussed this topic internally today. We can't promise anything, but maybe we can find a solution to provide online attribute filtering at sometime in the future...

**Comment by Lineflyer** [comment]
The best we could do for now is either to remove it from the live filter (but that would reduce the feature set...as it works for stored caches on map) or (which would be my favorite) to at least add an FAQ entry for that.

**Comment by alan666notb** [comment]
I think it would be best to remove it from the live filter, we shouldn't offer something we know full well doesn't work.

I suspect very few users would go to the FAQ when they found it didn't work (indeed, the first thing they did was post on FB).

**Comment by fm-sys** [comment]
> I think it would be best to remove it from the live filter, we shouldn't offer something we know full well doesn't work.

I use the feature also on the map. I would have absolutely no understanding why an existing function should simply be taken away.

No one forces you to use the feature. So please let's focus on making the feature perfect instead of spending time for ugly workarounds.

What if a user stores an attribute filter while being in the lists and then loads that filter into the map? Should the attribute filter element be hidden, ignored, removed...? There are too many edge cases which need to be consistent. IMHO not worth it. Never change a running system ;-)

**Comment by Lineflyer** [comment]
Lets give us a few weeks to clarify whether we will have a technical solution to this after consulting Groundspeak.

**Comment by fm-sys** [comment]
> Lets give us a few weeks to clarify whether we will have a technical solution to this after consulting Groundspeak.

I'm totally with you 👍

And even if we do not come to a technical implementation I just had another stupidly simple solution:
Just add a small hint text "caches need to be saved offline" to the attribute filter. This avoids reducing the feature set, takes nearly no space and is enough to explain everything which needs to be said.

**Comment by eddiemuc** [comment]
I agree with @fm-sys . The attribute filter is also useful in "mixed" scenarios where both stored and online caches are shown (e.g. on the live map).

It must be noted though that in case of stored caches the attribute filtering is done of course based on the STORED data, not on the live data. So if the attributation of the cache was changed between storing the caches data offline and the search, this is not reflected in the result.

As of removing attribute filtering from live searches (but keeping it for stored searches): This would be technically rather complex since there's no differentiation in "usable filter criteria" between different search/filter contexts yet. Considering the old AND vs OR filter discussion this is not so easy to do as well. And again, what about mixed scenarios e.g. live map?

TMALSS: I like @fm-sys s idea of adding a hint "caches need to be saved offline" to the filter for now. And maybe we reach an agreement for the v2 webapi and can even enable attribute online search somewhere in the next months.

**Comment by eddiemuc** [comment]
Solution to #10621 will also solve this issue
