### ISSUE TITLE
Start WP calculator in guided mode and/or remember last mode

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12751]
Currently the (new) WP calculator is always started in plain mode.
As the guided mode seems more suitable for "beginners"/"first time calc users" I suggest to start it in guided mode when used the first time.
From then on the last used mode could be preserved as there also might be users preferably using it in plain mode.

**Comment by eddiemuc** [comment]
Understood. However, to implement this some topics need to be clarified.

First topic: should this "start in guided mode" be a setting per waypoint (e.g. first time the calculacted coordinate is entered for a waypoint it is started in guiding mode, afterwards in whatever it was left with) or one setting for whole c:geo?

Second topic: since the guided mode is not capable of displaying incomplete, empty or faulty coordinate formats, we have to decide how to react in case the "normal" input coordinate coordinates such an input at time of switch to calculated coordinate dialog and guided mode:
* If coordinates are filled valid I assume those should be taken over -> correct?
* If coordinate is empty what should be displayed (currently: current user location, but see #12750 about this)?
* If coordinates are filled but invalid (e.g. something like "NSX123" in plain mode) what should be done (currently I think then also current user location is filled which seems strange to be honest)

Third topic: in which guided format should the dialog be opened?
* If in normal coordinate input dialog either DMS, DDD or DMM is selected, it would seem approbiate to open guided mode in this mode too
* BUt which mode should be used if normal coordinate input dialog is set to "plain"? Should it be DMM?

Once these questions are answered, this can be implemented I think.

**Comment by Lineflyer** [comment]
> First topic: should this "start in guided mode" be a setting per waypoint (e.g. first time the calculacted coordinate is entered for a waypoint it is started in guiding mode, afterwards in whatever it was left with) or one setting for whole c:geo?

IMHO global value.

> Second topic: since the guided mode is not capable of displaying incomplete, empty or faulty coordinate formats, we have to decide how to react in case the "normal" input coordinate coordinates such an input at time of switch to calculated coordinate dialog and guided mode:

If the current content cannot be viewed in guided mode but guided mode is the global preference, fall back to standard mode.

> Third topic: [...] But which mode should be used if normal coordinate input dialog is set to "plain"? Should it be DMM?

If the coord input is plain it should also be non-guided mode by default.

**Comment by eddiemuc** [comment]
> If the coord input is plain it should also be non-guided mode by default.

This would then make a setting unnecessary, then it would be sufficient to just open calculated coordinate dialog based on the currently selected coordinate input type. Would be my preferred solution too.

**Comment by eddiemuc** [comment]
> If the current content cannot be viewed in guided mode, fall back to standard mode.

Fine for me, but note that this differs from behavior of old calculated coordinate dialog, which displays current coord in this case. Especially the "empty coordinate" case might be surprising to some users

**Comment by eddiemuc** [comment]
Fixed with PR #12774

**Comment by Lineflyer** [comment]
> Fine for me, but note that this differs from behavior of old calculated coordinate dialog, which displays current coord in this case. Especially the "empty coordinate" case might be surprising to some users

mmh.. lets just try it out and improve from there if needed.

> Fixed with PR https://github.com/cgeo/cgeo/pull/12774

👍🏼
