### ISSUE TITLE
MapActivity is floated by toasts

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12761]
### Tell us your idea!

Currently, the MapActivity is totally floated by toasts which is really annoying. 

Opening Map |Changing GPX visibility 
-|-
![GIF-220216_211338](https://user-images.githubusercontent.com/64581222/154349366-f7d18e5d-9fac-4dd4-a05c-abac24f0ff15.gif)|![GIF-220216_211024](https://user-images.githubusercontent.com/64581222/154348031-d3da4fd3-a5bc-4515-938d-0e35079e5484.gif)

### What solution would you suggest?

Don't show any toasts for loading GPX at all. They don't bring any benefits IMHO. 

### Is there an alternative?

Make them configurable...

**Comment by Lineflyer** [comment]
Partly same as #12509

**Comment by moving-bits** [comment]
> Don't show any toasts for loading GPX at all. They don't bring any benefits IMHO.

Loading a track can take a while. So instead of seemingly doing nothing, c:geo informs you that it has started to load a track, and finally that the track is now available. Toasts are a non modal way to inform the user about the progress.

IMHO problems are currently:
- As tracks are reloaded under certain conditions we can get the toast more than once.
- As we can now load multiple tracks, toasts are multiplied.
- And it looks like even so called "short toasts" are being displayed for quite some time.

A solution to this could be to find some other kind of notification to the user that toasts are loading / have finished loading, maybe a colored progress line at the top of the map, similar to what we have for live update. But whatever we may choose here, users should be able to differentiate between map live update and track/route loading, and we should use it consistently.

**Comment by fm-sys** [comment]
The problem is, that all toasts are queried, and each toast is displayed for two seconds no matter how long the actual loading does take.

Means:
- 10 tracks = 10 * 2 * 2s = 40s toasts 
- maybe 3 seconds actual loading

**Comment by moving-bits** [comment]
Totally understood. One toast for "started loading track file(s) in background" and one for "All tracks loaded" or "9 out of 10 tracks loaded, one error" would be enough. But how to collect those messages?

**Comment by fm-sys** [comment]
Two toasts instead of 20 would be a good step into the right direction, but to be honest I don't see a benefit in these toasts at all. On my device, the GPX tracks are completely loaded within almost no time way before the map tiles get rendered at all. As a user, I don't want to be informed about the progress. I don't want to care about the internal processes at all. It should just work... (Without distracting me every time!)

It's totally enough to show a toast only if something went wrong. "Everything is fine" simply isn't important enough to annoy the user every time.
