### ISSUE TITLE
Don't show the same image twice in gallery

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#13088]
We shouldn't show the same image twice in the gallery, if the large and small version of the  same GC image upload are used in the listing.

Background:
---

**Analysis**

I used https://coord.info/GC1HEBH. This is a typical side using attachment images which are also displayed in the listing. E.g. the image "Fischerprüfung" is also shown in the listing:

![image](https://user-images.githubusercontent.com/6909759/168005616-7c42bcbe-d68c-4e6d-ad73-a28ae07290b2.png)

![image](https://user-images.githubusercontent.com/6909759/168005708-6635b9cc-aea5-4d19-a668-967093076786.png)

In HTML source the two URLs used are only slightly different (attachment references "large" version of image, embedded image does not):
* Image embedded in listing: `<img src="http://img.geocaching.com/cache/18a9e1fc-9d5b-4089-91b3-ffb28699c702.jpg" width="500px" />`
* Image as attachment:  `<a href="https://img.geocaching.com/cache/large/18a9e1fc-9d5b-4089-91b3-ffb28699c702.jpg" rel="lightbox">Fischerprüfung</a>`

In c:geo image gallery the image is displayed two times:

![image](https://user-images.githubusercontent.com/6909759/168006507-9d766572-531b-4e3d-a7e3-4e970aa3e6b7.png)

As of today, the GCConnector does not differentiate between the two, both are delivered as images to c:geo core. THe information whether the image is an attachment or from listing is not passed.

**Solution possibilities**

What we could do:
* We could introduce a new image category LISTING_ATTACHMENT and make the connector(s) differentiate between the two
* For spoiler view we could filter out displayed images by ignoring the "large" in URL comparison
* We could in general (not only for spoiler images) filter out duplicate images in image gallery this way...

_Originally posted by @eddiemuc in https://github.com/cgeo/cgeo/issues/12938#issuecomment-1124582668_

**Comment by eddiemuc** [comment]
Since I posted the info above, I learned a few things from code and have to correct some things from my own statement:
* The gcconnector does not pass images from listing html at all. It just passes the "attached" images (and in the connector architecture, those images are named "spoilers")
* This seems to be same for all connectors, but I haven't checked in detail.
* The images from the HTML listing are filtered out by searching for img tags in html. This logic is the same for all caches. It is not part of connector code but of class Geocache
* Both the "spoiler" images from connector and the img tags filtered from HTML listing are currently part of category "Listing"

The deduplication filter logic proposed is now already effective for showing (real) "spoiler" images in c geo. But not for Image gallery
