### ISSUE TITLE
Individual routes: Simplify removal of waypoints

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13122]
### Describe your problem!

When adding waypoints to an individual route, they sometimes get switched to a "coordinates only" entry somehow. Such waypoints will still be reflected in the drawn route, but can no longer be removed from route by long-press, even if the waypoint originally added to the route is available again. Removal of such entries can only be done by editing the route, which is cumbersome and error-prone.

### How to reproduce?

- Create an individual route
- add waypoints to it (not only caches)

further proceeding is unclear

### Actual result after these steps?

Sometimes waypoint entries of an individual route are switched to a "coordinate only" entry. On editing an individual route, you won't see waypoint name and cache's geocode any longer for such entries, but coordinates only.

### Expected result after these steps?

Reference to the originating cache should be kept, and removing such a waypoint from the route should still be possible by long-tapping on it.

### Reproducible

Unclear

### c:geo Version

2022.06.06 (but not new)

**Comment by fm-sys** [comment]
### Another situation:
There is a Geocache + final Waypoint at the same location. 
For adding an item to the route it is fine to ask whether the cache or waypoint should be added.
For trying to remove the waypoint it however makes no sense to show the selector.

### Potential solution:
When performing a long click at a location where a routing point does exist, remove that point without asking any additional questions (no matter whether it is a geocache, waypoint or coords-only nearby).

**Comment by MagpieFourtyTwo** [comment]
> For trying to remove the waypoint it however makes no sense to show the selector.

Au contraire - in some scenarios, this makes perfect sense.  ;)

I often use this ambiguity - to e. g. close the circle of a Multi (S1=Start, Parking=End) or a round trip with Tradis (duplicate Listing coords of first Tradi to a WP, thus Listing=Start, Sibling-WP=End of route).

Now imagine, another Tradi should be added to the round. Or the Multi-Final. Then I just select the start/end point of the route, from the presented list I remove the end(!) point of my individual route, add the new member, and finally the end again - et voila: The new route is ready.  With just four clicks. And, even more important: absolutely straightforward and comprehensible.

This would be significantly different, if a click on an ambiguous route point would just remove everything nearby:
1. click removes start and end of the route
2. click to re-add the starting cache to the route (which will be added at the end(!) of the route)
3. click to open route context popup
4. click to edit the route
5. click&drag to move the currently last cache to the start of the route
6. click to save the route
7. click to add the new member
8. click to re-add the end point

Which is not only double the number of clicks, but even worse is not really straight forward and moreover needs some deeper understanding of route editing and sorting.

Hence, I would of course be happy with the immediate removal of an ambiguous WP,
*but only* if it's sibling is not a member of the route.

However, it would nevertheless be great to have a possibility to remove route points which do not have a cache/WP displayed, cause sometimes it happens that I log a cache offline or mark a WP as visited - and this way remove it (too early) from sight (given that caches with offline logs and/or visited WPs should not be shown). And in order to get rid of the still existing route point, I first have to change the appropriate setting, which can be a bit annoying ...  ;)

**Comment by fm-sys** [comment]
> However, it would nevertheless be great to have a possibility to remove route points which do not have a cache/WP displayed, cause sometimes it happens that I log a cache offline or mark a WP as visited - and this way remove it (too early) from sight (given that caches with offline logs and/or visited WPs should not be shown). And in order to get rid of the still existing route point, I first have to change the appropriate setting, which can be a bit annoying ... ;)

Totally agree. And probably the main reason why this issue and https://github.com/cgeo/cgeo/issues/13110 do exist.

> Hence, I would of course be happy with the immediate removal of an ambiguous WP,
but only if it's sibling is not a member of the route.

Do I understand the expression correctly? (Pseudo Code) 

```
If (only one route point nearby) {
  // remove! 
} else {
 // multiple points of the current route are contained at the location, thus ask
} 
```

However the question would arise: How would you be able to ever add a second waypoint at the same location if always the removal gets triggered in the first place?

**Comment by MagpieFourtyTwo** [comment]
Following Murphy, it most probably appears to be a little bit more complex ...  ;)

```
If (no points nearby) {
  if (pref_longTapCreateUDC = TRUE) {
    // create user defined cache ( ;) )
  }
  else {
    // do nothing at all ...?  Or perhaps append a "coordinates only point" to the route?
  }
}
elseif (1 point nearby) {
  if (point is member of route) {
    // remove point from route
  }
  else {
    // append point to route
  }
}
else {                // more than one point nearby
  if (all points are member of the route) {
    // ask which one should be removed
  }
  else {              // there are points which are not a member yet
    // ask if he wants to append or remove a point
    if (he wants to remove) {
      // ask which one should be removed
    }
    else {            // he wants to add one of the points nearby *)
      // ask which one should be appended
    }
  }
}
```

*) and to add some more complexity:
&nbsp;&nbsp;&nbsp; just thought about the possibility to add a route point twice ... would make creation of round tours more easy ...  \<eg\>

**Comment by MagpieFourtyTwo** [comment]
Yep - that's why I avoided the phrases "WP" and "Cache", but just said "points". ;)

**Comment by ztNFny** [comment]
For the "circle" scenario wouldn't it be easier to just add a non-cache/wp next to the start point to the route as https://github.com/cgeo/cgeo/pull/13109 will allow? That'd allow to avoid a lot of complexity suggested above and still give almost the same result (but a few meter difference)

**Comment by moving-bits** [comment]
Ok, this discussion got somewhat distracted from the original point - waypoints getting changed into "coords only" type, therefore no longer being able to be deleted except via route sort view. As the other things mentioned here are valid points, though, I'll open a new issue for the original issue.

**Comment by Lineflyer** [comment]
Looks related to #10837 ?!

**Comment by moving-bits** [comment]
To my understanding this issue should be resolved with the recent addition of rendering coordinate-only points of a route and the new context menus, so let's close here. (And if something's still missing, probably better open a new dedicated issue, as the discussion here got somewhat crowded over time.)
