### ISSUE TITLE
Performance issues in cache details related to waypoints

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13160]
Something seems fishy in recent nightlies when it comes to waypoints of caches. 
Typical issues I have:
- After opening cache details of a cache with some waypoints the swipe to the waypoint tab it stuttering
- When tapping on a waypoint to edit it and then tapping the tick sign to accept and close this operation takes 1-2 seconds
- When afterwards trying to scroll through the waypoint the app is hanging or stuttering for several seconds. 

Happens on my device for all caches with waypoi ts.

I am on the road for this long weekend, will provide logs or more details next week if needed.

But maybe someone can try to reproduce.
Example caches follow.

**Comment by Lineflyer** [comment]
Today I played GC7B944 and its waypoint tab is really annoying to handle. All waypoint edit actions lead to unresponsiveness of several seconds.

**Comment by eddiemuc** [comment]
> Today I played GC7B944 and its waypoint tab is really annoying to handle. All waypoint edit actions lead to unresponsiveness of several seconds.

As far as I can tell this occurs because the whole cache details are reloaded on each action leading back to the details. In case of these two caches (and other similars) this leads to re-loading hundrets of images. I would definitely expect this to take part.

I am sure that new image gallery is at least part of the problem here. I created PR #13172 which will allow you to disable image gallery also on nightly builds by creating a boolean setting `feature_new_image_gallery` and set it to `false`. (if the setting does not exist, then the image gallery will be enabled in dev/nightlies and disabled in beta/prod). In my emulator it did not make the problem go away, but it made it less big (waiting time decreased).

Gallery-wise, we need a solution not loading all images at once (as described in #13138). Whether there are other problems to solve here I dont know.

Is this the first time that people are more heavily using caches with many images (>100)?

**Comment by eddiemuc** [comment]
Update: after a second restart of cgeo on the emulator the problem seems near-gone when gallery is deactivated. So for now I reommend to do this if you want to play caches with many pics. Solution will take longer, I have not much spare time available currently I am afraid.

**Comment by Lineflyer** [comment]
Doublechecked the above mentioned caches using 2022.12.28-NB. No performance issues anymore. Seemingly this has been solved by changes / reimplementation of the new image gallery.
