### ISSUE TITLE
create a cgeo-styled map long-tap marker

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#13178]
The red long-tap marker doesn't fit cgeos style, create one that fits better

![This is an image](https://user-images.githubusercontent.com/64581222/174478074-ebc4d9cc-add8-4bfb-9b3e-9fa9574fb885.png)

**Comment by ztNFny** [comment]
suggestion:
![image](https://user-images.githubusercontent.com/1258173/175647774-77586d58-8c84-434b-a161-f4034f2c369a.png)

**Comment by fm-sys** [comment]
a) a real "pin" makes IMHO no sense in the context of a map. The previous used "place" icon is well known and understandable. Furthermore, material.io suggest to use icons with a easy/simplified form. The "place" seems to fulfill these requirements way better than the "pin"
 
b) the color is nearly invisible inside a colorful and crowded map

Long story short, I don't see a real advantage in creating our own icon here...

**Comment by ztNFny** [comment]
> Furthermore, material.io suggest to use icons with a easy/simplified form.

It's an official material.io icon

> the color is nearly invisible inside a colorful and crowded map

A) you don't have to search it in a crowded map, you already know where it is - right where you clicked, next to the huge menu
B) we can tweak the color. I picked the cgeo color because that's the "cgeo color" and no other color already in use seemed appropriate. It's a first suggestion!

> I don't see a real advantage in creating our own icon here...

The current marker doesn't fit with the style of any other icon used in cgeo. It has a gradient, thin border - that doesn't even fit current material.io guidelines. So same reason as for using a common icon style for every other icon: common style.

**Comment by moving-bits** [comment]
Thanks for diving into this. 

Alas, I'm also not that happy with the "push pin" marker symbol. Although it's quite common in the actual world, I've rarely seen it in mobile apps. The "Google Maps" like symbol is like the universally used and known symbol, AFAICS.

If the original GM marker is visually outdated, one could search material.io icons for similar looking, but more modern replacements. If you filter the icons list for eg "place", you get more & different results. One possible marker could be this:

![grafik](https://user-images.githubusercontent.com/3754370/175666337-45cfad88-44aa-4e21-80e9-61bf02891716.png)

If you use "material symbols" instead of "material icons", there's also a variant with a "+" sign, which could be adapted:

![grafik](https://user-images.githubusercontent.com/3754370/175666506-8ea4754a-aa58-482d-8d73-7929aaae5ed2.png)

(no "filled" version available for  "symbols", though)

**Comment by ztNFny** [comment]
Similar looking things are expected to behave similar, but the "long-click" marker is nothing like any other icon that appears on a map.
as such I think a round marker for this temporary thing will be very confusing for users.

**Comment by fm-sys** [comment]
> the function of that marker is not to mark any place

At least not a POI. But for sure it is marking a place... Have you ever tried what will happen if you perform a long-click anywhere in Google Maps?

![Screenshot_20220625_083357_com google android apps maps_copy_431x395](https://user-images.githubusercontent.com/64581222/175761620-93e22764-c2a8-41e4-9983-9c70b06f39df.png)

**Comment by ztNFny** [comment]
Wow, you completely understand that cgeo and GMaps are exactly alike, no difference in functionality there.</sarcasm>

GMaps has exactly 1 style of icons as they all denote places.

But whatever, I don't care, stick to whatever unfitting stuff you want, i don't have to see it.

**Comment by bekuno** [comment]
I personally love the suggested pin much more than the "google marker".
It has a really own design, and suited to the other c:geo symbols. Additionally it uses the c:geo color, which we have also for user defined caches.
