### ISSUE TITLE
Improve variable parsing from personal note

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13180]
### Describe your problem!

Users report, that one some of their caches the variable section is prefilled with "some strange stuff" although they never used it.
Investigation showed, that this is seemingly caused by the fact, that the variable parsing from the personal note does also scan outside of our `{c:geo-start}` and `{c:geo-end}` tags (and even if they are not existing).

### How to reproduce?

- Open cache details
- Enter a personal note containing `A=?` (nothing else)

### Actual result after these steps?

Variable section of the cache shows a variable `A` with value `?`

### Expected result after these steps?

Parsing should only happen between our tags, thus no variable should be generated.

If this was designed on purpose to make usage more convenient, then we should discuss pro/con again.

I will try to get a more problematic example from the reporting user.

### Reproducible

Yes

### c:geo Version

2022.06.06

### Additional Information

Support ticket [548447](https://cgeosupport.droescher.eu/scp/tickets.php?id=4796)

**Comment by eddiemuc** [comment]
This was designed on purpose. Idea is to treat variable parsing same as waypoint parsing, this also happens outside of `{cgeo-start}` and `{cgeo-end}`. I actually use this quite heavily myself, only way I enter variables out in the wild actually (same as with waypoints).

But yes, can be discussed of course. A compromise might be to restrict parsing to certain variable formats. A first suggestion: `A=x` is only parsed if x is a number, for free parsing one has to use the $ format e.g. `$A=B+C`

**Comment by Lineflyer** [comment]
Lets wait for the users example of why its annoying. It was not recognizable from his mails.

**Comment by eddiemuc** [comment]
Oh man...

I see two bugs here, as well as the need to improve the parsing feature:
* Bug 1: the same text is parsed multiple times eg added to different variables
* Bug 2: (unrelated to parsing) the "formula" symbol (the letter f) on the "formula" button is missing / replaced with a crossed-out square

Improvement suggestion:

It is up to discussion of course what a user **should** expect to happen with this user note. I personally would expect to have entries for vars E to M with the claimed numeric value, but no entries for A to D (since their value is "?").

It must be noted though that we can't just cut off parsing at comma separator because a comma can be part of a valid formula (e.g. `P=3,14`). So I suggest the following:
* If a pattern is found where varname starts with $ and separated with `=` then the right side of `=` is parsed as formula until linke break or `|`. This covers the syntax used by c:geo itself to store vars in user note and can be used to store more complex formula. E.g. `$A=3*B+2,5 | $GH=5-A` would be handled fine.
* If a pattern with single letter varname, `=` and integer value is found (without `$`), then this is parsed as var. But nothing more complex. E.g. `A=5` would be parsed, `B=5x` would be parsed as `B=5`, `C=6,3` would be parsed as `C=6` and `D=abc` or `EF=3` would not be parsed at all.

**Comment by murggel** [comment]
Just to give another example:
Having valid coordinates (e.g. N50 53.222 E12 23.444) in the note, creates a variable E=12 and N=53 ...

**Comment by eddiemuc** [comment]
PR #13181 should fix this according to suggestion above and including fix for the behaviour described by @murggel

**Comment by eddiemuc** [comment]
Unless there are other opinions I would merge PR tomorrow.
