### ISSUE TITLE
Background downloader should download multiple caches at once 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#13262]
BTW, as I just stumbled upon this, again (and don't want to open a issue, as it may just be a local problem): Trying to update a list of 2000 caches, which runs in background (can this be deactivated in any way?), but the update is *horribly* slow: After 10 hours just 800 caches are updated, which makes about a minute each - has this to be considered "normal"? I would just call it "unusable" ... :/

_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/13261#issuecomment-1192374397_

**Comment by MagpieFourtyTwo** [comment]
FOA: Thx for opening a dedicated issue!

Additional info:  This is not limited to "screen off" time.

Just switched the screen on, had a look at the notification bar, where c:geo stated "940/2000", i. e. had updated about 140 caches within the last 4 hours.  But although screen was constantly on from now on, the value did not change for about three minutes. Then it suddenly started to increase again, grew up to 950, using about 15 secs per cache ... then it paused again for a minute or so, until it updated 4 more within 15 seconds (i. e. about 3-4 secs each) ... and paused again for a minute until the next one got updated ...

All this, as said, with screen on.  And it does not matter at all, if c:geo is running in foreground or not.

**Comment by MagpieFourtyTwo** [comment]
Just switched the phone on again - and this time the update job was gone completely ... \*grrr*
Doubt that it has been terminated by Android, cause a) c:geo is already excluded from battery optimization and b) the job mentioned above run over night, although with very little success, but without being killed.  But who knows.

However, started it over again (with filter ``NOT(Last details update:--8h)`` set) ... and the first 4 got updated within 15 secs (3 to 5 secs each), not "smiling good", but at least "ok \*sigh*", but then it got stuck again, took about 2 minutes until the 5th was done, to afterwards take another 3 minutes to climb up to 13 (avg=22 secs), just to (seemingly?) freeze again at 27 for 3 minutes ... still counting. Although the job is "fresh" and screen is on all the time.

Apart from solving this issue: Any hint, to get this stuff updated in a more reliable way?  Just to prevent a weekend disaster ...? ;)

**Comment by Lineflyer** [comment]
Just mentioning:
It could be a false finding, as up to my personal experience the server itself has immense performance issue from time to time last weeks.
We should maybe make a test session somewhere in weekdays night time to get a clear view whether there is any performance problem with the downloader.

**Comment by fm-sys** [comment]
> Doubt that it has been terminated by Android, cause a) c:geo is already excluded from battery optimization and b) the job mentioned above run over night, although with very little success, but without being killed. But who knows.

The code which is used for background refresh is more or less the same as it was executed in the foreground.

So if there are any performance differences, is has most likely to do with battery optimization. I would expect that the thread might get freezed for some time under certain circumstances on some devices. 

@MagpieFourtyTwo IIRC you were using a huawei device, right? They are kind of special in terms of battery optimization anyway 😅

As time permits, I can add some debug log statements, so that we can analyze what's going on. Something like this (which would allow us to analyze whats going on exactly):
```
22:38:10 Download GCxxx startet 
22:38:17 Download GCxxx stopped
22:38:17 Download GCyyy startet 
22:38:20 Download GCyyy stopped
```

**Comment by MagpieFourtyTwo** [comment]
> The code which is used for background refresh is more or less the same as it was executed in the foreground.

Nevertheless, foreground refresh is *way* faster than background refresh.  At least all the caches, I randomly picked from the list, were loaded within 3 to 5 seconds. For 2000 caches this would add up to a max of 10.000 secs, resp. 2:45 h - which is not just "slightly less" than the approx. 20(!) hours my update action took now (which BTW equals an avg of 36 secs/cache).

> So if there are any performance differences, is has most likely to do with battery optimization. I would expect that the thread might get freezed for some time under certain circumstances on some devices.

Maybe - in fact, even more likely, as refreshes like this worked perfectly fine a while ago, when they happened in foreground.  Even if c:geo itself was running in background. But - if this is really OS dependent, i. e. w/o a workaround, it should be possible to optionally let the refresh run as foreground task again, cause in bg this function is simply unusable. 

> @MagpieFourtyTwo IIRC you were using a huawei device, right? They are kind of special in terms of battery optimization anyway 😅

Yes, I am very well aware of that. Therefore I have completely excluded c:geo from battery optimization. Ok, at least as far as the OS allows  the user to do so.  ;)

> As time permits, I can add some debug log statements, so that we can analyze what's going on. Something like this (which would allow us to analyze whats going on exactly):
> 
> ```
> 22:38:10 Download GCxxx startet 
> 22:38:17 Download GCxxx stopped
> 22:38:17 Download GCyyy startet 
> 22:38:20 Download GCyyy stopped
> ```

That would be great (although I would tag the end as "completed" ;) ) - and perhaps it might even show a pattern.
BTW: Although I doubt that the thread for real gets suspended (AFAIK suspend was deprecated a while ago, as it was prone to deadlocks) - if s/th like this does really still happen, is it possible for the thread to get some info about his state and perhaps even the duration of his inactivity?
Ah, one more probably interesting thing: My impression is that the more images a listing contains, and especially the more images that do not exist anymore (i. e. result in a 404), the longer it takes to update - so would it be possible to log the number of loaded pics (and perhaps even the number of fails), too?

**Comment by MagpieFourtyTwo** [comment]
@Lineflyer 
> the server itself has immense performance issue from time to time last weeks.
> We should maybe make a test session somewhere in weekdays night time to get a clear view whether there is any performance problem with the downloader.

PDT night time = CEST day time. ;)
My refresh ran from Thursday, 01:00 CEST (=16:00 PDT) to Friday, 22:00 CEST (=13:00 PDT), thus all "west coast night" long.
And I think it's pretty unlikely that server overload lasts all night long.
There should have been at least one slot of a few hours with less load to complete this comparably small request ...

Ah, just had an idea: Performed a refresh on a GSAK db with 2912 caches: Finished within five minutes ... *this* is, what I would consider an acceptable amount of time ...  ;)

**Comment by fm-sys** [comment]
Just had another idea:
The old foreground as well as the background downloader are downloading all caches after each other. What if we schedule let's say always 5 caches at a time?

**Comment by fm-sys** [comment]
> Ah, just had an idea: Performed a refresh on a GSAK db with 2912 caches: Finished within five minutes ...

For completeness, let me say that GSAK is "Powered by the Geocaching API" so they are using faster API calls especially if the web interface is currently slow.

**Comment by SammysHP** [comment]
In the past we had throttled the download, inserting a random delay after some time. It might have been removed over the years, though.

**Comment by Lineflyer** [comment]
> Just had another idea:
> The old foreground as well as the background downloader are downloading all caches after each other. What if we schedule let's say always 5 caches at a time?

AFAIR the foreground downloader had already parallel threads of 4 or 5 caches at once. If the background downloader does not include that, it could explain the longer loading time.
Please check the old code....I am pretty sure we had several threads there.

**Comment by fm-sys** [comment]
The old code can be found at a29c97fabf03e8ea2f5f83eba26193265bf1d91a were it got removed... 

I cannot find any intended delays in the code, however there is indeed a threading algorithm hidden:

```java
final Observable<Geocache> allCaches = Observable.fromIterable(caches);
allCaches.flatMap((Function<Geocache, Observable<Geocache>>) cache -> Observable.create((ObservableOnSubscribe<Geocache>) emitter -> {
    // download and update progress 
}).subscribeOn(AndroidRxUtils.refreshScheduler)).doOnComplete(() -> /* finished */); 
```
The `refreshScheduler` currently handles 3 tasks at a time, we can of course discuss whether we want to increase this value further.

This needs to be implemented for the background service. Sorry that I hadn't seen this while redesigning this area.

**Comment by MagpieFourtyTwo** [comment]
@fm-sys 
> For completeness, let me say that GSAK is "Powered by the Geocaching API" so they are using faster API calls especially if the web interface is currently slow.

Yes, I am aware of this - yet these are the numbers that c:geo is compared to by users in the wild,
so it has to compete with them.  If we like it or not ...

**Comment by MagpieFourtyTwo** [comment]
As for the web interface: Loading caches in the browser was nevertheless faster. Even loading them in c:geo was faster.
At least the ones, I randomly picked from the list.

**Comment by fm-sys** [comment]
PR https://github.com/cgeo/cgeo/pull/13269 will enable multithreading for background downloads

**Comment by fm-sys** [comment]
Update: With today's nightly the download should be at least 3 times faster. 

However, there seem to be a bug causing the downloader progress notification not to be correctly updated. Instead downloads are counted per thread so it shows only 1/3 of the actual progress. The end notification is fine however.

**Comment by MagpieFourtyTwo** [comment]
> However, there seem to be a bug causing the downloader progress notification not to be correctly updated.

Refreshed a list of 28 caches this afternoon, and it correctly counted up one by one all the way up to 27, until it finally changed to "28 caches downloaded". IOW: Either WFM or I have just one thread enabled (how can I check resp. is "just one thread" even possible at all?).

As for the performance: Much better than before. Updating took between one and three seconds per cache, at least until 25, then it paused for about 15 secs (which almost spoiled the good average ;) ), but then it jumped right to the finished message. All in all, it took about 90 secs to perform the update.

Out of curiosity, I did the same refresh again now: Counting was nearly the same again (one by one, just seemed to skip #3 and #14, then, again, paused at #25, to finally jump right to the completion message), performance was slightly better: about 75 secs for the 28 caches, i. e. less then 3 secs/cache.

Then I took a larger list (5375 caches), and started a refresh at 23:55:00 CEST (=14:55 PDT):
23:56:  48 caches
23:57:  89 caches (41 new)
23:58:  130 caches (41 new)
23:59:  169 caches (31 new) - afterwards display off till 00:05, with c:geo still in foreground
00:05:  395 caches (226 new => 37 per minute) - now display off till 00:15
00:15:  756 caches (361 new => 36 per minute) - now display off till 00:30
00:30:  1299 caches (543 new => 36 per minute) - now putting c:geo in background, but keeping the display on till 00:35 ...
00:35:  1502 caches (203 new => 41 per minute) - now display off till 00:45 with c:geo still in background
00:45:  1902 caches (400 new => 40 per minute - now display off till 00:47:30 (i. e. approx. 2000 caches)
00:47:38:  2000 caches in 51:38 min == 38,73 caches/min resp. 1,549 secs/cache
01:14:  3000 caches ... counting ... 2375 left => about 3.680 secs = 61 mins => 02:15 CEST
01:27:  3500 ... 1875 left => about 2.900 secs = 48 mins => 02:15 CEST
01:41:  4000 caches ... counting ... 1375 left => about 2.130 secs = 35 mins => 2:16 CEST
02:05:  4500 (500 new in 24 mins => 21 per minute ... took more than a minute each at #4453, 4463, 4477 and 4479) => 2:27 CEST
02:25:  5000 (stopped for minutes at #4578, 4582, 4612, 4651, 4657, 4680 ...
02:28: task died - 692 caches left (which proves that the counter shows correct values)

02:29: started update task with these 692 not yet updated caches
02:32: 122 caches refreshed => thus about 40 caches/minute again
02:47: 375 caches (253 new => 17 per minute)
02:53: 435 caches (60 new => 10 per minute)
03:01: 600 caches (65 new => 8 per minute)
03:05: 692 caches (92 new => 23 per minute, total: 692 in 36 mins => 19 per minute)

These measurements seem to substantiate:
- Display on/off or background/foreground seem to not make a significant difference anymore - fine!
- Even the counter does his job pretty good - fine, too.
- There may be a memory leak or alike, as refresh becomes way slower after ~4k caches - and finally the task even crashes
- Although a reason for the decreasing performance can even be an increased server load or a server sided throttling,
   cause although the immediately restarted task began with the old performance, it dropped again really fast.
   Another argument for performance loss due to server load could be: 2:55 CEST equals 17:55 PDT,
   which may be a "high load time".

Nevertheless, compared to the disastrous result of the originally mentioned list of 2000 caches, which would have been allowed to take about 2:45 h, but actually even took about 20 hours, this is indeed a *massive* improvement. Of course, it's still not really comparable to an API bulk refresh, but nevertheless, it makes refreshing longer lists usable again.  Thanks a lot!

However, would it still be possible to increase the number of threads even more, to give it an extra kick?
Although, of course, should not be done, if there is a risk to put too much load on the server ...

**Comment by fm-sys** [comment]
> Refreshed a list of 28 caches this afternoon, and it correctly counted up one by one all the way up to 27, until it finally changed to "28 caches downloaded". IOW: Either WFM or I have just one thread enabled (how can I check resp. is "just one thread" even possible at all?).

Maybe counting does indeed work fine. I didn't had much time so I just refreshed a very small list with 5 caches which was counting `1 - 2 - finished` while testing. 

But seeing your massiv performance boost threading has to work properly. 

> list of 2000 caches which would have been allowed to take about 2:45 h, but actually even took about 20 hours, this is indeed a massive improvement.  

I guess there were some network timeouts which had blocked the single-thread-download for several minutes. This could explain the _way longer_ download time. 



> Of course, it's still not really comparable to an API bulk refresh, but nevertheless, it makes refreshing longer lists usable again. Thanks a lot!

Great, nice to hear :)

> However, would it still be possible to increase the number of threads even more, to give it an extra kick?
Although, of course, should not be done, if there is a risk to put too much load on the server ...

I could imagine that 5 threads (instead of 3) might bring an additional kick. However, using significantly more threads might even have the opposite effect.

However, I can't estimate the server load if hundreds of users are refreshing they're lists at the same time...

**Comment by fm-sys** [comment]
> There may be a memory leak or alike, as refresh becomes way slower after ~4k caches - and finally the task even crashes

Out of curiosity: Is there any exception in the log? Otherwise it might likely be that the service is killed by the system (in this case after 2½ hours) which wouldn't be that unexpected either.

**Comment by MagpieFourtyTwo** [comment]
> However, I can't estimate the server load if hundreds of users are refreshing they're lists at the same time...

Which is in fact the main reason, why I voted against "automatic/scheduled lists updates" the other day.
Based on various event small talks I know there are a lot of guys out there, who love to keep all their offline lists up-to-date - even if these contain caches they will never ever have the chance to get to, anyway.

**Comment by MagpieFourtyTwo** [comment]
> Is there any exception in the log?

Interestingly, I have no log entries at all during that time.
Last one yesterday afternoon, long before I started the test: 07-28 17:23:05
Next one this morning: 07-29 10:28:52

```
[...]
07-28 17:23:04.957  5436 24499 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 24499 (pool-11-thread-), pid 5436 (cgeo.geocaching)
07-28 17:23:05.166 24525 24525 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-28 17:23:05.166 24525 24525 F DEBUG   : Build fingerprint: 'HUAWEI/VOG-L29EEA/HWVOG:10/HUAWEIVOG-L29/10.1.0.150C431:user/release-keys'
07-28 17:23:05.166 24525 24525 F DEBUG   : Revision: '0'
07-28 17:23:05.166 24525 24525 F DEBUG   : ABI: 'arm64'
07-28 17:23:05.167 24525 24525 F DEBUG   : Timestamp: 2022-07-28 17:23:05+0200
07-28 17:23:05.167 24525 24525 F DEBUG   : pid: 5436, tid: 24499, name: pool-11-thread-  >>> cgeo.geocaching <<<
07-28 17:23:05.167 24525 24525 F DEBUG   : uid: 10398
07-28 17:23:05.167 24525 24525 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
07-28 17:23:05.167 24525 24525 F DEBUG   : Abort message: 'Error, cannot access an invalid/free'd bitmap here!'
[...]
07-28 17:23:05.446 24525 24525 F DEBUG   :       #33 pc 00000000000cf7c0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: b91c775ccc9b0556e91bc575a2511cd0)
07-28 17:23:05.446 24525 24525 F DEBUG   :       #34 pc 00000000000721a8  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: b91c775ccc9b0556e91bc575a2511cd0)
07-29 10:28:52.552 17542 20442 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 20442 (pool-5-thread-2), pid 17542 (cgeo.geocaching)
07-29 10:28:52.696 20658 20658 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-29 10:28:52.696 20658 20658 F DEBUG   : Build fingerprint: 'HUAWEI/VOG-L29EEA/HWVOG:10/HUAWEIVOG-L29/10.1.0.150C431:user/release-keys'
07-29 10:28:52.696 20658 20658 F DEBUG   : Revision: '0'
07-29 10:28:52.696 20658 20658 F DEBUG   : ABI: 'arm64'
07-29 10:28:52.697 20658 20658 F DEBUG   : Timestamp: 2022-07-29 10:28:52+0200
07-29 10:28:52.697 20658 20658 F DEBUG   : pid: 17542, tid: 20442, name: pool-5-thread-2  >>> cgeo.geocaching <<<
07-29 10:28:52.697 20658 20658 F DEBUG   : uid: 10398
07-29 10:28:52.697 20658 20658 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
07-29 10:28:52.697 20658 20658 F DEBUG   : Abort message: 'Error, cannot access an invalid/free'd bitmap here!'
[...]
```

... and this SIGABRT because of AccessViolation is a "pretty well known" phenomenon, which exists for a looong time already, cause it could not really be nailed down yet, and although it happens quite frequently, it neither is reproducible.

However, as mentioned before, usually processes do not get killed by at least "my" Android. ;)
Best example: The originally mentioned update even ran for about 14 hours until it eventually died.

**Comment by fm-sys** [comment]
The original issue is fixed meanwhile, stuck/failed download are discussed in  #13415
