### ISSUE TITLE
Filtering for "solved mysteries only" seems to be complicated

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13285]
### Describe your problem!

Coming from a user ticket on support I tried to set a list filter for "only show solved mysteries".
Looks straight forward by adding a status filter, leaving every option at its default, but set "solved mystery" to "yes".

But this does not work as expected - it does filter the list somehow, but you will see caches of all sorts, eg. traditional, letterbox, multi etc. - It seems to filter mysteries having no final coords, though. So despite the title "Solved mysteries" it's more of a "hide unsolved mysteries" filter.

You can achieve the original goal by either
- setting "solved mystery" to "no" and negate the filter
- or by setting "solved mystery" to "yes" and additionally set a cache type filter for type=mystery

Is this behavior intended? It seems a bit complicated to me. Or is there any shortcut I've missed?

### How to reproduce?

Have a list of caches, set a fresh filter in advanced mode, type=status, "solved mystery"=yes, leave all other at default

### Actual result after these steps?

unsolved mysteries are excluded

### Expected result after these steps?

display only solved mysteries, leave out any other cache type

### Reproducible

Yes

### c:geo Version

2022.06.06

**Comment by Lineflyer** [comment]
It might not be straigt forward, but it works as designed.
If you tap the (i) next to it, it clearly states: "This filter does only affect mysteries". 

The problem is, that if you include the type=mystery into the same setting it will get impossible to combine it with other filters. 
E.g. my live map filter is:  Hide found, Hide owned, Only show solved mysteries

I think its OK and we should just tell the user to additionally limit the cache type for his use case. 
Maybe we could indeed rename the filter to "Hide unsolved mysteries" to make it even more clear.

**Comment by moving-bits** [comment]
Ok, I had tapped the "i" icon, but obviously did not make the mental connection that I need to add a type filter to exclude all other types. Maybe we should add an info about this after the first sentence, something like "This filter does only affect mysteries. If you want to exclude other cache types as well, please add an appropriate cache type filter." (or similar).

I vaguely remember a discussion about the naming of this entry now. IMHO we should try to find something short, which still triggers the user in the right direction.

I'll change the labels for this issue to "frontend design".

**Comment by eddiemuc** [comment]
Naming the filter "Hide unsolved mysteries" is not a good idea because (like all status filters) it has three states: one where it is disabled ("all"), one where it shows only solved mysteries ("yes") and one where it shows only unsolved mysteries ("no"). In all cases only mysts are affected.

I like @moving-bits s idea of adding some more info to the info field though.

**Comment by Lineflyer** [comment]
> I like @moving-bits s idea of adding some more info to the info field though.

Thumbs up!
