### ISSUE TITLE
Beta release are no "rc" buildTypes

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13327]
### Describe your problem!

The latest beta release `2022.06.06-RC` was not created with buildType `rc`.
Therefore the appIcon is not `@mipmap/ic_launcher_rc"`.

### How to reproduce?

See the app icon after installing the beta.

### Actual result after these steps?

Standard icon is shown.

### Expected result after these steps?

RC icon should be shown.

### Reproducible

Yes

### c:geo Version

2022.06.06

### Additional Information

The job https://ci.cgeo.org/view/All%20jobs/job/cgeo%20release%20candidate/ should be the correct one.

**Comment by moving-bits** [comment]
I will check the links on the Wiki page I had been using, thanks for the notification.

**Comment by moving-bits** [comment]
Ok, links on the Wiki page are fine, seems that I had followed the link in the wrong section :-(

I guess it's not necessary to release another beta only to fix the icon? I would wait then for either new bug fixes to be rolled out in a new beta, or wait for the final release.

**Comment by bekuno** [comment]
> I guess it's not necessary to release another beta only to fix the icon? I would wait then for either new bug fixes to be rolled out in a new beta, or wait for the final release.

When I started this issue, I feared a real bug. Since this is not the case, I would leave it as it is now.

**Comment by Lineflyer** [comment]
There is in fact a problem here:
status.cgeo.org will fail due to the wrong deployment.
Currently all is fine as the "wrong beta" is still under deployment and the version has not been set as active version. However once we set this version as active version also non-beta users will receive a notification to upgrade, while there is nothing to upgrade. 

Nothing urgent, but we have to:
- NOT set the current beta as active version on status.cgeo.org but leave it as it is
- Either push a new correct build if further fixes come up or just continue with next release and only then set this version as active version on our notification system

I'll reopen this as reminder

**Comment by moving-bits** [comment]
Official release version has been released meanwhile, so this can be closed now.
