### ISSUE TITLE
Status filter: filter dnf

### ISSUE THREAD

**Issue by Aslang13** [cgeo/cgeo#13449]
### Tell us your idea!

A way to see and catch up only with
My DNF's or unclutter the map by not showing them

### What solution would you suggest?

Adding the option in the already existing status filter

### Is there an alternative?

Not that I know of 

### Additional Information

Notyet

**Comment by jakedot** [comment]
It's a good idea because the existing "found" setting doesn't provide for filtering out or in DNFs. If I set it to no, I still get DNFs mixed in the rest of unfound caches.

Somehow I think that there already was a setting for this in the Status filter?

At least I have a saved preset called "Found or DNF" with two instances of the status filter in it, one set to "Found=Yes" and the other to "has offline log = yes".

**Comment by eddiemuc** [comment]
Fixed with PR #13468
