### ISSUE TITLE
[new image gallery] Listing/log mage not available when trying from listing/log

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13448]
From field, can provide more details later:

Nightly 2022.09.26

Have bunches of caches stored offline (including images)
Device is offline
When trying to open the listing or log images from their individual icons on listing/logbook tab cgeo fails to show them but shows the "unavaible" placeholder image.

All listing log pictures however show fine from the gallery tab, meaning: They are stored and should be available via both methods.

Side note:
If I put the device online, clicking the link in listing/log will show loading indication, downloads the image and shows it only then.

Almost reproducible for me, however on rare caches it works normal

**Comment by fm-sys** [comment]
Have experienced this as well. When started in "filtered" mode (log/listing images only), the new image gallery seem to always fetch online images even if they are already stored offline.

**Comment by eddiemuc** [comment]
As already pointed out by @fm-sys : the new image gallery is still an experimental function and NOT visible to "normal" c:geo users (only nightly users and those using a hidden flag). I still plan to rework this feature entirely once I find the time. I would not put time in supporting this experimental feature in its current state, it can't be released to the public as is anyway due to fundamental issues (not able to handle caches with large image counts on it).

**Comment by Lineflyer** [comment]
@eddiemuc Thanks for clarification. I was unsure about the current state of the new gallery. It would have said, that it is quite useful already. To what issue numbers do you refer with those fundamental issues to handle large image counts? Would like to test it.

Anyway this particular problem in the experimental gallery should be solved with #13455, therefore closing.

**Comment by eddiemuc** [comment]
> To what issue numbers do you refer with those fundamental issues to handle large image counts? Would like to test it.

That would be #13138. Also I dimly remember some other issue concerning caches with very large number of images in it.
