### ISSUE TITLE
more issues with formulas and waypoint creation

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13459]
From user on support, regarding current beta version:

ich habe bei der Übernahme der Finalformel aus dem Listing des Caches GC91AN9 in den Finalwegpunkt ein paar Ungereimtheiten/Fehler entdeckt.

Die Formel lautet:

N 048° (H-F+1).(C-F) 0 ((G+B+D)-(F+A+D-H))
E 009°  (C+E+F+1). 0 (C+F-E)

Diese unverändert in den Wegpunkt und danach in die PN übernommen:

{c:geo-start}
@Finale (F) {CC|N 048° (H-F+1).(C-F) 0 ((G+B+D)-(F+A+D-H))|E 009°  
(C+E+F+1). 0 (C+F-E)}
$A= | $B= | $C= | $D= | $F= | $G= | $H=
{c:geo-end}

Dabei fällt auf:

1) Die Variable E wird nicht angelegt.

2) Das Tool "Leerzeichen entfernen" in der Koordinatenberechnung löscht nicht alle Leerzeichen. Das Leerzeichen hinter "E009°" bleibt stehen.

3) Ich habe dann die Variable E manuell angelegt (siehe erster Screenshot), und testweise alle Variablen mit dem Wert 1 versehen. In der Koordinatenberechnung taucht E aber nicht auf, siehe zweiter Screenshot. Erst wenn ich das Leerzeichen hinter "E009°", siehe Punkt 2, manuell lösche, wird dann auch E angezeigt, siehe dritter Screenshot

![image](https://user-images.githubusercontent.com/3754370/193522923-e35df39e-60e6-46dc-be31-991aa7d3d62f.png).![image](https://user-images.githubusercontent.com/3754370/193522999-8ed8eb12-4cec-495b-81f7-33a6ff1650b9.png).![image](https://user-images.githubusercontent.com/3754370/193523081-d4c5ca82-8359-47ee-8e78-139143ccd519.png)

**Comment by eddiemuc** [comment]
Variable E is not created because the parser was unable to interpret the MM-part of the east coordinate (which is the only place where E is used as variable). This can be seen in second screenshot where the whole section is red.

Why parser couldn't interpret this is to be analyzed, this looks like a bug.

**Comment by eddiemuc** [comment]
I have reason to believe that the issue here is that the "Space" in question is not actually a "Space" (but maybe a tab or some other whitespace char instead) and that this is not handled correctly by the parser.

@moving-bits : I am guessing that this issue as well as #13460 is actually from the same user (and has the same cause). Is this correct?

**Comment by moving-bits** [comment]
yes, all four recent issues regarding formulas (and formulas in conjunction with PCN) are from the same user

**Comment by eddiemuc** [comment]
Fixed with PR #13463
