### ISSUE TITLE
Non working found state information for ALC

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13481]
### Describe your problem!

I open this as a bug as in first implementation this feature used to work:

For an unknown reason the ALC-API stopped returning the found state for adventure lab caches during the first implementation and test phase. Therefore the starting implementation for ALC in cgeo was released without that feature.

As this is however a major issue for users and was working initially we should clarify the reason and enable that feature if possible.
I will address this to the API owner.

@baiti 
I could need something like a technical two-liner describing how it initially worked and what has changed without prior notice (e.g. requests and responses OK/NOK).

### How to reproduce?

View ALC caches on map or perform coordinate/address search
 

### Actual result after these steps?

The ALC returned might contain ALC already found by the user but not marked as found in c:geo.

### Expected result after these steps?

Found ALC should be marked as found in search results/map

### Reproducible

Yes

### c:geo Version

2022.09.04

**Comment by baiti** [comment]
a two-liner won't be sufficient, however let me try to be as brief as possible:

The API we're using is referred to as "the public API" (as opposed to "the partner API"). The public API has a variety of endpoints, some of which can be called without any authorization, some require a prior authorization. Authorized requests require a `consumer_key` which identifies the application (e.g. cgeo) making the request. The `consumer_key` has properties attached to it, which define what functionality is allowed to be used and what is not allowed to be used. A very important function is to use the `login` method of the API. By doing so, the subsequent requests are not only made with a `consumer_key` (which identifies the tool), but also with an `access_token` that identifies the individual users If we want to get the true found state of a lab cache's stages, we must tell the other side for which user we're making the request, which is only possible after we have successfully obtained an `access_token` by using the `login` method with a capable `consumer_key`.

The `consumer_key` that was assigned to cgeo initially supported the `login` method so we could acquire an `access_token` per individual user in order to obtain the "true found state". During the initial implementation and debug phase, even in the first release we made, we were able to fetch the true found state but after a short period of time, this functionality ceased to work. We could no longer use the `login` method so a specific capability must have been removed from the properties of our `consumer_key`.

I believe we have discussed that with the party who provided us the key but the capability was never enabled again. Rationale being that the public API is an unsupported API and we should use the partner API instead, which initially didn't support anything for Lab caches but learned how to do so at about just the time we had the discussions.

**Comment by fm-sys** [comment]
I don't see a real chance for it. The answer will be "use the partner API which supports the logged state". Which brings me to the point that it would be good to use a mixture of public and partner API. Public API for stages and stuff, partner API for the found state. They had explicitly allowed us to continue using scraping and partner API in parallel. 

I suggest to not contact them and just do what we are able to do at our side. Otherwise, we just risk that our "temporary" public API key gets revoked. 

Do we ever have received partner API keys? IIRC @moving-bits had started some experiments long time ago.

**Comment by Lineflyer** [comment]
I guess I could just address this paragraph 

> The consumer_key that was assigned to cgeo initially supported the login method so we could acquire an access_token per individual user in order to obtain the "true found state". During the initial implementation and debug phase, even in the first release we made, we were able to fetch the true found state but after a short period of time, this functionality ceased to work. We could no longer use the login method so a specific capability must have been removed from the properties of our consumer_key.

to the API owner and ask whether they can restore that functionality.
It might be, that they won't but refer to the partner API, but that's where we are now.

> I suggest to not contact them and just do what we are able to do at our side. Otherwise, we just risk that our "temporary" public API key gets revoked.

I don't think this is likely, other team member opinions?
If a detailed discussion is needed I would like to direct you to the internal forum instead.

**Comment by fm-sys** [comment]
> > suggest to not contact them and just do what we are able to do at our side. Otherwise, we just risk that our "temporary" public API key gets revoked.
> 
> I don't think this is likely, other team member opinions?

I don't see a high chance for success while the worst case isn't likely either. So no strong opinion from my side. If you want to ask, feel free to go ahead...

**Comment by baiti** [comment]
I have only vague memories on the subject but could it be that we already asked and got a no-response? At any rate, it is so long ago that we might as well ask again.
