### ISSUE TITLE
Unified map: combined doesn't work 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#13594]
When using "combined" mode, the screen stays grey.

Cgeo version: 2022.11.01

![Screenshot_20221101_222653_cgeo geocaching](https://user-images.githubusercontent.com/64581222/199347218-f75b26e8-a6d2-41f9-96da-191fe1ec270d.jpg)

**Comment by Lineflyer** [comment]
I would like to join testing the unified map.
AFAIR I need to set `useUnifiedMap` to `true`, which I did.

I can however not see any difference (which might be a good sign) but I think I am not yet really using the new map implementation...e.g. combined map also works and I don`t see map rotation on OSM.

What else is needed to enable it in nightlies?

**Comment by fm-sys** [comment]
`useUnifiedMap` is used for launching the map from cache details, but there is another key which needs to be enabled: `showUnifiedMap` will add an additional quick tile to cgeos main screen. 

https://github.com/cgeo/cgeo/wiki/UnifiedMap

**Comment by moving-bits** [comment]
It should actually work by setting just `useUnifiedMap`, but I have to admit that I'm running it with both keys set to `true` for quite some time now and haven't tested otherwise recently. 

Integration is supported for starting navigation from cache details page, cache popup, cache list and search results. Bottom navigation "map" still points to the "old" map implementation to have a "last resort" or for comparison purposes.

Two easily spottable differences to check whether you are in `UnifiedMap`:
- tap on marker cluster in Google Maps - a selction popup opens when in `UnifiedMap`
- map rotation for OSM (if map rotation enabled in system settings)

With `UnifiedMap` you can also disable (hide) some of the built-in tileproviders (see settings => map), which would be another notable difference.

**Comment by moving-bits** [comment]
And thanks to all that start testing `UnifiedMap` 👍 , highly appreciated!
