### ISSUE TITLE
Black screen /Solid screen  instead of wallpaper in main-menu

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#1361]
From facebook (don't know if it is worth to implement it):

> Is it possible to put a black (maybe selectable option) background on the apps main screen? I would prefer that instead of seeing my homescreen wallpaper. 

I can understand somehow e.g. if you are using a quite contrast-less wallpaper.

**Comment by bailey293** [comment]
I only noticed (and opened the other issue) because I just changed my phone wallpaper from all black. I'm all for leaving the option in and allowing it to be an "appearance" setting. That way individuals that want it can keep it. That does increase the complexity though. I can try to take a stab at this.

**Comment by moving-bits** [comment]
@bailey293  Thanks, I'm already preparing a PR for this.

**Comment by bailey293** [comment]
@moving-bits oh cool! Thanks!

**Comment by Korb** [comment]
> I can understand somehow e.g. if you are using a quite contrast-less wallpaper.

This word has never been mentioned here, but I assume we are talking about **widget** here.

**Comment by SammysHP** [comment]
> This word has never been mentioned here, but I assume we are talking about **widget** here.

No, we were talking about the c:geo main screen that uses the phone's wallpaper as its background image.

**Comment by Korb** [comment]
@SammysHP, thank you, I didn’t know about this feature of it, because my desktop has always been solid black.
