### ISSUE TITLE
Lint: PrivateApi

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13641]
### Describe your problem!

lint warning for the main project:

CgeoApplication.java:105,           PrivateApi, Priority: Normal

Accessing internal APIs via reflection is not supported and may not work on all devices or in the future<p>Using  reflection to access hidden/private Android APIs is not safe; it will  often not work on devices from other vendors, and it may suddenly stop  working (if the API is removed) or crash spectacularly (if the API  behavior changes, since there are no guarantees for  compatibility).<div style='color:#d00'><b><pre>             final Field menuKeyField =  ViewConfiguration.class.getDeclaredField(&quot;sHasPermanentMenuKey&quot;);                                         </pre></b></div></p>

### How to reproduce?

see https://ci.cgeo.org/job/cgeo-CI_PR-build/3352/androidLintResult/new/type.117384631/

### Reproducible

Yes

### c:geo Version

CI PR-build 3352

**Comment by fm-sys** [comment]
I agree, in the specific case of `sHasPermanentMenuKey` the reflection is no longer needed and won't work anyway.

https://www.androidpolice.com/2019/11/13/the-menu-navigation-button-has-finally-been-retired-in-android-10/
> A bug report was filed a few months ago for Android 10, where someone noticed the menu button no longer appeared for legacy apps. Google recently closed the bug, stating, "this was intentionally removed as the API has been deprecated for several releases now."

The menu button has technically been deprecated since Android 3.0 Honeycomb, so I guess we can remove functionality related to it :)
