### ISSUE TITLE
Spoiler images get duplicated on refresh

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#13674]
### Describe your problem!

If you refresh an (OpenCaching?) cache, spoiler images get duplicated every time.

### How to reproduce?

1. Open for example OC175EB
2. Refresh a few times

### Actual result after these steps?

Each times the number of images increases, adding duplicated images.

### Expected result after these steps?

No change in images.

### Reproducible

Yes

### c:geo Version

2022.11.11-NB

**Comment by eddiemuc** [comment]
Does this also happen for Gc.com caches?

**Comment by SammysHP** [comment]
I was not able to reproduce it with geocaching.com.

**Comment by Lineflyer** [comment]
Confirmed for the mentioned OC example.

**Comment by eddiemuc** [comment]
I have no access to my c:geo coding infrastructure this week, so I can't fix this immediately

**Comment by eddiemuc** [comment]
Fixed with PR #13691.

Turns out this bug has nothing to do with new image gallery but with a wrong handling of spoiler images in OC connector in general (and also in GC and SU connector): on refresh, the new spoilers are just added to offline stored cache without removing the existing spoilers first
