### ISSUE TITLE
Filtering of cache size "not chosen" versus "other"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13795]
### Describe your problem!

Reported by a user on support mail:

The filter in the map shows caches with the size "not chosen" even if I only filter on "other".

Many challenges does not equal "not chosen" and "other", so that could cause problems if I would find one of the wrong kind.

### How to reproduce?

For example https://coord.info/GC25KQD, a "not chosen" that still shows up with filter with only "other".
That same cache shows up if I only filter on "not chosen" too.

### Reproducible

Yes

### c:geo Version

2022.12.21

### Additional Information

Support ticket 484323

**Comment by ztNFny** [comment]
"Not chosen" (size 1) can no longer be selected at GC - it was available for all caches and the only value for EC, virtual, Webcam until 2012. Since then those types are using "Other" (size 6).

I have a PR ready to add this differentiation in c:geo, but not sure it's a good idea to differentiate those. Opionions?

On GC.com it's not possible to search for "Not chosen" size btw. The UI has checkboxes only for the current sizes, it's missing "not chosen". But by manipulating the URL (set cs=1) it's still possible to search for it, e.g.
https://www.geocaching.com/play/map?lat=54.1946&lng=11.7609&zoom=7&asc=true&sort=distance&cs=1&st=N+54%C2%B0+11.675%27+E+11%C2%B0+45.652%27&ot=coords

**Comment by Lineflyer** [comment]
I have no strong opinion on this one but tend to say, that we might not rely on an "undocumented" cache size in our query URL just to support that very specific issue.

**Comment by ztNFny** [comment]
> I have no strong opinion on this one but tend to say, that we might not rely on an "undocumented" cache size in our query URL just to support that very specific issue.

The size is well-documented: https://api.groundspeak.com/documentation#geocache-sizes

Just the current search GUI doesn't have a corresponding checkbox (as apparently GC doesn't care about grandfathered stuff - they don't show APE as cache type either.
