### ISSUE TITLE
DownloaderTest > testMapsforge > FAILED

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13853]
### Describe your problem!

Besides other failure - there is this testMapsforge failure:
~~~
19:11:51  cgeo.geocaching.downloader.DownloaderTest > testMapsforge[android-30(AVD) - 11] [31mFAILED [0m
19:11:51  	java.lang.AssertionError:
19:11:51  	Expecting:
19:12:13  Tests on android-30(AVD) - 11 failed: There was 1 failure(s).
~~~

It happend also on the commit build https://ci.cgeo.org/job/cgeo-CI_commit-build/1048/console - so maybe an real problem.

### How to reproduce?

see https://ci.cgeo.org/job/cgeo-CI_commit-build/1048/console (or other failing builds).

### Reproducible

Yes

### c:geo Version

CI  Commit Build 1048

**Comment by bekuno** [comment]
Same problem do we have of cause also for release.

**Comment by eddiemuc** [comment]
I advise not to change anything on release right now unless absolutely necessary due to production bugs! 

Reason: I assume that every change on release as of now will produce a conflict when release will.be forwarded to master (because of directory structure change). And in turn, commits on release will most likely not be appliable to master any more for same reason.

Unless I underestimate git. I would be really impressed if it could handle this conflict -free

**Comment by Lineflyer** [comment]
I agree to @eddiemuc 

I dont expect git to handle this.

**Comment by bekuno** [comment]
Lets close here and hope that we do not need the current release.
