### ISSUE TITLE
Filtering for archived caches not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13891]
### Describe your problem!

Reported by a user and reproducible for me on current `master` as well.

### How to reproduce?

1. Search for caches by owner Lineflyer
2. Note, that the result contains some archived caches and events
3. Apply a status filter to the search result with only Status=Archived 

### Actual result after these steps?

For a split second the filtered result is visible, but then an empty list is shown

### Expected result after these steps?

Archived caches to be shown

### Reproducible

Yes

### c:geo Version

2022.12.21

**Comment by ztNFny** [comment]
related to https://github.com/cgeo/cgeo/pull/13744 ?

**Comment by eddiemuc** [comment]
Since we are talking about online search, I assume that GC.com does not support a combination of the two filters "owner" and "status=archived" and returns an empty result for it. Behavior of Gc.com for archived caches is strange anyway.

Probably any status filter must be removed from GC.com online query whenever owner is set as a filter to "solve" this (status filtering is then done on retrieved result on client side).

**Comment by Lineflyer** [comment]
Could be...mmh...I wasn't aware that filtering a search result(!) leads to a new search rather than just filtering what is there.

**Comment by eddiemuc** [comment]
> Could be...mmh...I wasn't aware that filtering a search result(!) leads to a new search rather than just filtering what is there.

Back in the days, a unified approach for searching and filtering offline and online was requested - and delivered :-)

For offline searches, the db is requeried on filtering, for online searches the server is requeried. Some things wouldn't work otherwise, e.g. if you do an online search around a coordinate/address and then filter this by attributes (because the online search result doesn't contain attributes).

**Comment by eddiemuc** [comment]
Fixed by PR #13913
