### ISSUE TITLE
Disappearing waypoints on OSM map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14053]
### Describe your problem!

Reported by users of 2023.02.12 and 2023.02.25 and now also reproducible for me:
When mapping a list (not sure of other contexts) some of the caches waypoints might vanish from the map when opening and closing the popup for a cache.

### How to reproduce?

- Waypoint limit for map is set to 30 caches
- Using Openandromaps offline map file
- I have a list with 13 caches of a trail
- On one of the caches I added 3 parking waypoints
- I map the list
- I repeatedly tap on that cache and close the popup

### Actual result after these steps?

Look at the three parking waypoints in north, west, south of the shown map disappear and reappear seemingly randomly:

https://user-images.githubusercontent.com/949669/222897653-fe631b75-5962-43b2-bfa5-8a93e04f741d.mp4

### Expected result after these steps?

All waypoints should be shown all the time

### Reproducible

Yes

### c:geo Version

2023.03.04-NB

### System information

```text
Android 13, Samsung S20
```

**Comment by Lineflyer** [comment]
Related to #13675 ?

**Comment by moving-bits** [comment]
IIRC we had some trouble in the past with waypoints of same geocache not having distinct prefixes, which leads to random effects on OSM. Do you have access to your database and can check in table `cg_waypoints`, column `prefix` for your three newly created parking waypoints whether they have the same or distinct prefix values?

**Comment by Lineflyer** [comment]
You are right:
All three created waypoints have no prefix:
![image](https://user-images.githubusercontent.com/949669/222916414-53086c39-41bf-462d-b517-9a8593f98af0.png)

AFAIR I created them by mapping the cache and long tap on the map.

**Comment by moving-bits** [comment]
IIRC `NewMap` uses Geocode + prefix to distinguish waypoints from each other. If multiple waypoint have the same signature, the (randomly) last one will win. As the map gets updated pretty frequently currently, this changes a lot over time.
We can either try to make sure, that every waypoint gets its distinct signature, or it may be solved implicitly with the the great work going on on geoitem layer (#13980), as soon as it starts being used for waypoints as well.

**Comment by eddiemuc** [comment]
> We can either try to make sure, that every waypoint gets its distinct signature, or it may be solved implicitly with the the great work going on on geoitem layer (#13980), as soon as it starts being used for waypoints as well

Even the new geoitemlayer will require us to have a distinct key for each item placed on the map. There's no way around it I am afraid...

**Comment by moving-bits** [comment]
How does today's GMv2 handle this? We don't have the "vanishing waypoints problem" there.

**Comment by Lineflyer** [comment]
Another interesting fact. Today I can no longer reproduce the problem on the mentioned stored caches list.
I have not changed anything besides upgrading to newest nightly and waiting one day (DB cleaning?).

Now it looks like this:
![image](https://user-images.githubusercontent.com/949669/222953725-d20d4f51-352c-4f2b-a491-b9e560884f30.png)

**Comment by moving-bits** [comment]
Oh, had forgotten about this method: `makeWaypointPrefixesUnique()` is being called during database cleanup. This got introduced with fix #13395

**Comment by Lineflyer** [comment]
I don't understand why we create user defined waypoints without any prefix in the first place. IMHO this should be avoided/solved.

**Comment by Lineflyer** [comment]
Another aspect:
I am not sure what happened, but it could have the same origin:
For another cache I created three user defined waypoints yesterday. Two parking waypoint and a final waypoint including a coordinate calculation.
After doing this cache I synced the variables and the user defined waypoints to my personal note, which looked kind of normal (without in detail checking it).
Today I noticed after correcting some variables and syncing to personal note again (not sure if the problem was there before the new sync), that waypoints have been mixed up:
The final waypoint had the name "Parking" and contained the calculation. Another parking waypoint was also still named "Parking" but also had the same calculation in it. So one parking waypoint was totally lost, the other got the coords of the final.

**Comment by moving-bits** [comment]
> I don't understand why we create user defined waypoints without any prefix in the first place. IMHO this should be avoided/solved.

I've found one culprit, see PR #14057. Adding waypoints to active cache on map will now assign unique prefixes, and therefore make newly created waypoints appear even on OSM map.

**Comment by Lineflyer** [comment]
That could be the complete solution, couldn't it?

**Comment by moving-bits** [comment]
I've tried to dig a bit deeper into this today and _may_ have some finding:

Test case:
- Filter map to display AL caches only (two or three of them should be enough)
- Download AL caches to have their waypoints available
- Display them and check for completeness

`mapsforge/v6/caches/WaypointsOverlay` has a method `showWaypoints` which tries to load and filter the waypoints available in the current viewport. For this it (indirectly) calls `DataStore.loadWaypoints(getViewport())`, which retrieves the waypoints. This list seems to be complete (contains all waypoints of the AL caches).

Next step is to check whether some of the loaded waypoints are already being displayed (and thus should be replaced), and which are new. The comparison is done based on the identifier built by `waypoint.getGpxId()` - and this _may_ be the culprit, as this ID only contains the waypoint prefix, but not its gc code. So if you have several caches with waypoints, and some of them share their prefix, too many waypoints will be removed.

Maybe someone can cross-check this assumption?


(In the past, waypoints of AL caches did not get a prefix at all => problems with display, partly fixed with the PR mentioned above. But as soon as there are multiple AL caches, they share their prefixes, as we assign 1, 2, 3 etc. to each AL. It does not happen that frequently to other cache types, which may be due to owners assigning more varied prefixes to their waypoints. So this would still fit into current observations so far.)

**Comment by moving-bits** [comment]
@Lineflyer 
Can you cross-check if your scenario still happens? (Proposed fix is in both release 2023.05.15 and in the nightlies.)

**Comment by Lineflyer** [comment]
Assigned myself to try next days

**Comment by moving-bits** [comment]
@Lineflyer 
There haven't been any issues on support about missing waypoints on OSM for quite some time now (AFAIK) - can we close this issue, #13675 and #12999?

**Comment by Lineflyer** [comment]
I was not using c:geo recently, but some weekends ago I did some lab + multi combination and did not run into this issue. So lets close for now. I will pay attention, whether it shows up again.
Thanks for fixing!
