### ISSUE TITLE
Split "map" settings into multiple pages

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14103]
All our settings pages are (on my phone) 1-2 pages long which is ok to find a setting. And then there's map settings which is 6 pages, making it the 3*larger and hard to navigate.

I propose to split this up into multiple pages for better accessibility.

Proposal:
- Map Sources (sources, offline maps, offline themes, offline hillshading, multithreaded osm)
- Map content (waypoints, map conent)
- Map behaviour (map behavior, proximity notifications)
- Map colors (map lines)

**Comment by moving-bits** [comment]
Good idea! 

One could put "Map content" and "Map behavior" into same page. Would give a relatively even distribution and keep the initial settings screen a bit shorter:
- Map Sources & Themes - 3 pages (including UnifiedMap and OSM multithreading settings)
- Map Content & Behavior - slightly more than 2 pages
- Map Colors - a bit less than 2 pages

**Comment by MagpieFourtyTwo** [comment]
> I propose to split this up into multiple pages for better accessibility.

Seconded.

What about hierarchy? Although I know that menu hierarchies should be kept as flat as possible,
I would still keep ``Settings`` => ``Map`` and put the new pages as "sub pages" into the current ``Map`` page.
Otherwise, the ``Settings`` page will get somewhat flooded with map elements ... IMHO.

WRT the naming: ``Map content`` sounds a bit irritating to me, as it is not really about e. g. the content of OSM, but just the stuff, c:geo adds. But, most regretfully, I currently don't have a better term ...  :/

Same applies to ``Map colors``, which does not handle colors of the map, but of the lines, c:geo *adds* to the map.
Therefore e. g. ``Track/Route line colors`` (or the like) may perhaps be more appropriate ...?

**Comment by ztNFny** [comment]
"Map sources" is pretty clear, no need for discussion there.

How about moving "map lines" not to a new "Map colors" page but to the existing and sparely used "Appearance" (keeping it as a sub-section there)? That way we'd end up with 3 more or less equal pages.
