### ISSUE TITLE
Map not centered

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14161]
BTW: I just noticed, that the position marker does not even get centered on the map!
It's in fact centered relative to the entire display, "wasting" a lot of space while heading north.
In fact over here the position marker ends up about 7 mm (resp. ~14 %) too high - which I would consider a *real* issue.

IOW: Even in the one and only scenario, where hiding the nav bar would give add. 9 mm of map space (i. e. driving north, exactly), we would achieve nearly the same map info gain by just correcting the centered position to the "map center".
This, BTW, is the same in landscape mode, where it of cause is even worse, as there are just about 18 mm of free space between centered map position and header bar, anyway.

_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/14066#issuecomment-1482954746_

**Comment by fm-sys** [comment]
A picture tells more than a thousand words:

![grafik](https://user-images.githubusercontent.com/64581222/229361426-9238de38-d4a6-4b15-93eb-7c9166436baa.png)

**Comment by MagpieFourtyTwo** [comment]
Same applies to portrait mode, of course.

**Comment by fm-sys** [comment]
> Same applies to portrait mode, of course.

Sure, thanks for mentioning it explicitly. I did chose landscape to make the problem even more visible ;-)

**Comment by Lineflyer** [comment]
Indeed...I never explicitly noticed. Maybe the bug was introduced some year(s) ago when we renovated all the action bar stuff.
For north bound map it should be centered, for rotating maps we could think about a 2/3 approach to allow more map visible in moving direction.

**Comment by moving-bits** [comment]
> Maybe the bug was introduced some year(s) ago when we renovated all the action bar stuff. 

It's a side-effect on the new "tap hides action bar" functionality. To avoid the map "hopping around" (resizing, recentering, and therefore changing position) the map needs to be sized to the maximum size required. Action bar etc. will lay on top of parts of the map until when in use and not hidden.

Therefore we will calculate a new map position which will fit the default (action bar shown) in both portrait and landscape modes.

**Comment by MagpieFourtyTwo** [comment]
>Therefore we will calculate a new map position which will fit the default (action bar shown) in both portrait and landscape modes.

IMHO, one can live just fine with this solution. Although it may not be perfect, it's already way better than the current implementation, cause after comparing the two "worst cases" (landscape mode, non rotating map), as is ...
- driving north with the "old" centered position (left cross in @fm-sys' screenshot) vs.
- driving south with the "new" centered position (right cross),
it turns out that the "new" one's distance to the map border is about 1.5 times longer than the "old" one's.

OTOH, I wouldn't really mind if the map would "bounce around". On the contrary, I was even surprised that it didn't ... ;)

**Comment by Lineflyer** [comment]
> OTOH, I wouldn't really mind if the map would "bounce around". On the contrary, I was even surprised that it didn't ... ;)

This would IMHO look quite disturbing...currently this fading out of the action bar is really nice.

**Comment by MagpieFourtyTwo** [comment]
Just imagine: The action bar fades out and in the same go the map center moves up, step by step.
I would say, this would look even nicer. And more professional.  ;)
And WRT resources and stuff: As even rotation of the map in heading direction is in discussion already,
this little up and down of the map would hardly be noticeable in terms of performance, I guess.
But, as already said: Moving the static map center position down is already a good step forward.

**Comment by moving-bits** [comment]
@MagpieFourtyTwo: Here's some update on current state of this issue:

Work on "hiding action bar" is based on a draft by @fm-sys, which had the map moving on hiding action bar (and bottom navigation, BTW), as the available space for the map increased/decreased. He also provided a video showing the default animations, see https://github.com/cgeo/cgeo/issues/13315#issuecomment-1237277572. Those default animations look quite bumpy, which is why I looked for an alternative. Making the map position static seemed to be the smoothest approach to me, as it avoids all map movements at all, providing a very stable and clean look. This in conjunction with the smooth transitions of action bar and filter bar added by @fm-sys later results in a very professional look, IMHO.

Sadly this comes at the cost of position marker / map center no longer being in the actual visible center of the map anymore, which is a no-go, especially in landscape mode with its small visible area.
So far I've found no easy way for re-centering a map. One would probably have to apply an offset to the map center, which gets calculated in pixel converted to a coordinate offset. A bit ugly, IMHO, and I'm not sure if there are other drawbacks to this approach. (Haven't tried yet.)

A possible workaround could be to extend the map at the bottom as well and adjust positioning of all elements in a way that they stay above the bottom navigation bar. As action bar and bottom navigation have the same size (*), map gets recentered "for free" with this approach. I've dived into this today and made some progress, but there is a "BUT" here as well: It will only work in portrait mode, as bottom navigation is available in portrait mode only (in landscape mode we use a navigation rail, being displayed at the left). And (*) it's not guaranteed, that both elements will stay the same size forever.

Thus it might be that we need to revert to the original approach of having separate and (layout-wise) fixed elements, and map moving around on hiding/unhiding the action bar. Then we would need to look into a somewhat smoother transition of the map than we had in the original approach.

**Comment by fm-sys** [comment]
Moving the map around is a no-go IMHO, as hiding the map gets accidentally triggered quite frequently (for me). Using Pixel distance converted to a coordinate offset would still be the best solution IMHO. If map doesn't support such calculation natively, we can easily calculate a distance-per-pixel factor by taking the size of the view and the coordinate viewbox.

**Comment by eddiemuc** [comment]
> Using Pixel distance converted to a coordinate offset would still be the best solution IMHO. If map doesn't support such calculation natively...

Not sure what you have in mind here. But whenever you think about hand-made solutions to convert coordinates into pixels and vice versa, consider also that at least Google and VTM can be rotated and can also be used in 3D mode.

All maps support projection methods to convert coordinates to pixels. You can look into my geoitem layer implementations for the three map types to see how the work (method is ",getprojection" or something like this)

**Comment by fm-sys** [comment]
> consider also that at least Google and VTM can be rotated and can also be used in 3D mode.

Woops, you are right. This makes it complicated :-/

**Comment by ztNFny** [comment]
> as hiding the map gets accidentally triggered quite frequently (for me).

It's another topic - but didn't we want to disable that by default?

**Comment by fm-sys** [comment]
You are right, indeed it is disabled by default. Just had forgotten that I had enabled it for testing purposes...

**Comment by moving-bits** [comment]
As the map size increases it also re-centers its contents, moving things around, and looking quite bumpy additionally (see example in https://github.com/cgeo/cgeo/issues/13315#issuecomment-1237277572). The latter may be solved by applying some sort of animation, but still contents would move.
What we are currently looking for is for map just expanding, but keeping current position of "center", so not moving things around.

**Comment by MagpieFourtyTwo** [comment]
> see example in #13315 (comment)). 

This example does indeed not look very nice, but - it's maybe not representative for the current case anymore. Or at least it may not look quite as bad now. Because in the example not only the header action bar was hidden, but also the quick navigation bar - which creates a bi(!)directional movement, making the map jump up and down and up again. But if - like IMHO consented - only the header action bar is hidden, the map only has to move in *one* direction, which might make this look much more "logical" ...?

**Comment by moving-bits** [comment]
I'd started pursuing a similar approach (it's not yet finished): Let the map extend under the bottom navigation, making actual center and visual center the same (in portrait mode). Other map elements need to have adjusted positions to stay above of bottom navigation (I'm working on this part, using a similar "spacer" approach as for the action bar). Works generally, but is portrait mode only. - Need to check whether a screen element can extend beyond screen dimensions...

**Comment by ztNFny** [comment]
But then map center will be lower than "visible part of map" center, right? Imho we should aim for visible center. And if toolbar is hidden pretend it isn't.

**Comment by moving-bits** [comment]
That's why the extra part at the bottom should have the same size as action bar height (which is a parametrized value), to keep it visually centered.
In current material guidelines bottom navigation seems to have same height in portrait mode. (But I haven't found a formal parameter for this yet.)

**Comment by moving-bits** [comment]
I'm not sure I understand your proposal. You mean you would translate the map view a bit to the screen's bottom for the center being a bit further down?

But wouldn't you then still have to extend the map (at the upper end, in this case, and even further then today) to fill the space when action bar is hidden? And still need to move up some map elements at the map's bottom (credits, scale bar, quick settings and zoom buttons) so that they are not hidden beneath the bottom navigation?

**Comment by MagpieFourtyTwo** [comment]
One more thing struck me today that might irritate users if the map is extended (even further) beyond the visible boundaries: 
The cache counter in the action header bar. It seems to be "out of sync" already now from time to time ... this will get even worse in certain situations ... nevertheless, I would not consider this as a deal breaker ...

**Comment by moving-bits** [comment]
> I'd started pursuing a similar approach (it's not yet finished): Let the map extend under the bottom navigation, making actual center and visual center the same (in portrait mode). Other map elements need to have adjusted positions to stay above of bottom navigation (I'm working on this part, using a similar "spacer" approach as for the action bar). Works generally, but is portrait mode only. - Need to check whether a screen element can extend beyond screen dimensions...

This is how this approach looks in OSM portrait mode:

![image](https://user-images.githubusercontent.com/3754370/231877965-c1b7a306-b485-4d3c-9f91-3b2737604b2b.png).![image](https://user-images.githubusercontent.com/3754370/231877994-f090d451-da0a-4296-8955-479da79ee3a0.png)

But not in portrait mode:

![image](https://user-images.githubusercontent.com/3754370/231878164-ce3e4df2-e316-4711-bab9-c9493f5ef7a5.png)

(Have not found a way yet to let the map extend beyond the visible screen at the bottom.)

**Comment by fm-sys** [comment]
Things seem to get more and more complicated, and I'm not sure anymore whether it is worth all the effort at all...

What about not fixing this issue for now, but instead don't expand the map under the action bar if "actionbar hiding" is disabled (which is the default)?

**Comment by MagpieFourtyTwo** [comment]
Seconded. As already said [two weeks ago](https://github.com/cgeo/cgeo/issues/14161#issuecomment-1493427617), I would just leave the things as they are and simply place the center (hardcoded) a bit lower, like the right position @fm-sys showed in the screenshot in [1493367108](https://github.com/cgeo/cgeo/issues/14161#issuecomment-1493367108). This will already make things *a lot* better, esp. in landscape mode (in portrait mode as well, but over there in fact just "nice to have"). And as "do not hide" is default anyway, most of the users will not even notify the slightly "off center" in "header hidden" mode.

Esp. as there are far more annoying and therefore more important bugs than this optical glitch (like for example  #12225, which really annoys me every single day anew. ;) )

Just my 0.02 $.

**Comment by moving-bits** [comment]
> and simply place the center (hardcoded) a bit lower

it's not that easy, sadly, at least I've found no way to say the map (all three map types, actually), to put their center a bit lower. Only thing found so far is giving the map a different coordinate as map center, but that would cause problems with map rotation etc. - That's why we tried virtually enlarging the map, so that the map center stays the same as before introducing hiding of action bar.

I guess I'll try to pursue @fm-sys's proposal next:

> What about not fixing this issue for now, but instead don't expand the map under the action bar if "actionbar hiding" is disabled (which is the default)?

**Comment by moving-bits** [comment]
Ok, proposed workaround is implemented:
- if "tap to hide action bar" is disabled, map centering is same as before (visually, at least)
- if "tap to hide action bar" is enabled, map reaches beneath action bar, so map is off-center by the height of the action bar as long as action bar is visible

(nb: map is off center in both cases when filter bar is visible, as the filter bar is "on top" of the map. this is something that could be discussed as well, as filter bar is probably visible 99% of the time for most users)

**Comment by MagpieFourtyTwo** [comment]
Way better - thx a lot!  :)

WRT "map is off center (because of) filter bar" - IMO this can safely be ignored cause the "off" is *really* small.

@fm-sys as for me, the issue can be closed now.
