### ISSUE TITLE
Add client-side filtering for OC attributes

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14254]
Edit: Changed this to a feature request to support client-side filtering for OC attributes, see https://github.com/cgeo/cgeo/issues/14254#issuecomment-1537356879

### Describe your problem!

Report on support: A user wants to filter for "OC only" caches in a search.

As suggested he added an extended filter for cache attributes "ON only", which does work for displaying the caches.
But on moving the map, new new caches are displayed.

### How to reproduce?

- add opencaching.de as a service and authorize c:geo
- go to live map and download a couple of OC caches, store them locally
- go to filter settings and add a cache attribute filter to include "OC only" caches
- move map far enough to trigger a update for listed caches

### Actual result after these steps?

downloaded caches get filtered for OC only caches, but no new OC only caches are being displayed

### Expected result after these steps?

on moving the map far enough, new OC only caches should be downloaded and displayed

### Reproducible

Yes

### c:geo Version

2023.04.11

### Additional Information

ticket 178976

**Comment by Lineflyer** [comment]
This is probably as we do not request attributes for (not yet loaded) caches on the map from the OC-server....same as GC.

**Comment by eddiemuc** [comment]
Filtering for attributes of OC caches will only work for offline stored caches because the Okapi API does not support online attribute search. See https://www.opencaching.de/okapi/services/caches/search/all.html for all supported online search options.

For more details I maintain a cgeo wiki page listing all the online search/filter capabilities per connector: https://github.com/cgeo/cgeo/wiki/%22Search-by-Filter%22-support-by-c:geo-Connectors 

Unfortunately nothing we can do about this

**Comment by moving-bits** [comment]
Ok, that's what I told the user as possible cause, thanks for confirming. So the workaround for the user is to store OC caches first, then apply the attribute filter.

**Comment by eddiemuc** [comment]
Update on this: I further scanned the okapi, and we might be able to implement this with Client-Side filtering. Means: filter on the cache data retrieved on-the-fly on client side. This should be possible because okapi seems to allow download of attributes directly with their search-and-retrieve-API (unlike GC.com). That would be a new feature though

**Comment by moving-bits** [comment]
Changed this to a feature request and reopened issue
