### ISSUE TITLE
New option for store offline caches should ask for list for unsaved caches

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#14274]
### Tell us your idea!

If there are already saved and unsaved caches on the map / in a list, the new option "refresh and keep current list assignement" (#14190 ) only refresh the saved caches, but do not ask for a list to store the unsaved caches.
So the new caches will not be stored offline.

It would be nice, if also unsaved caches can be stored offline with this option.

### What solution would you suggest?

* Show option to select list for unsaved caches
* Unsaved caches will be stored in the selected list
* Offline caches will only be refreshed, but not stored in the selected list

### Is there an alternative?

Leave it as it is

**Comment by moving-bits** [comment]
Good catch, thanks. I've prepared a fix for it with PR #14275

**Comment by ztNFny** [comment]
Isn't this by design? We have "do nothing" to ignore caches already stored and "refresh and keep" to ignore noon-stored caches.
That letter to me means "refresh only came that are already stored and visible" - e.g.. Part of a big list but today I'm going to do a small part of it and want to refresh only that. Unstored caches should be ignored in that.

If you also want me caches then
1. "Do nothing" to store new caches
2. "Refresh and keep" to refresh old ones

**Comment by murggel** [comment]
But then I would expect it as a separate option "refresh caches" and not under the submenu "store offline"

**Comment by ztNFny** [comment]
Half the options in that dialog are "refreshs" as is .. Wording could be improved

**Comment by murggel** [comment]
> Half the options in that dialog are "refreshs" as is .. Wording could be improved

But the menu says "store offline" - and this is my intention for the unsaved caches with the enhancement of refresh already offline caches

**Comment by murggel** [comment]
I would be fine with an additional entry for only refreshing caches
