### ISSUE TITLE
Values sliders behave weird

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#14288]
### Describe your problem!

Some things are a bit strange with the value sliders. 
My examples below refer to ``Map Content & Behavior`` => ``History track max. length``,
but the other sliders behave more or less the same:

### How to reproduce?

1.  **value does not change**
     - make sure that the ``History track max. length` is set to a value greater than 100 (e. g. 500)
     - slide the slider to the very left => value (on the right) changes to 100
     - leave the settings page and re-enter it
     - the value of ``History track max. length`` will be 500 (resp. your previous value) again ...
     - BTW: if you enter the value if 100 manually, the slider will not be on the very left (i. e. at it's minimum),
       but a few pixels more to the right

2.  **sliding to the very left does not always set the value to it's specified minimum:**
     - slide the slider to the very left => value (on the right) changes to ``100``
     - grab the slider, slide it somewhere in the middle of the scale and back to the very left (without lifting your finger)
     - in one of three tries, the value will now be 200 ... on next try, it may show 300 ... on next try 100 again ...
     - remark: you may have to perform the sliding action several times to see the described/unexpected result

3.   **unexpected increments on manual input**
     - remember your current value (which should be higher than the specified minimum)
     - click the value on the very right (in order to manually enter a value)
     - the input popup will open
     - have a look are the value in the input box: in most cases, the value will be increased
       (I would expect the value in the input box to be the same of the value I just clicked)

### Reproducible

Yes

### c:geo Version

2023.05.22-NB-2f3d3e4

**Comment by moving-bits** [comment]
If I'm not mistaken, the first observation is due to the following code fragments in `SeekbarPreference`:

When moving the slider, the following function gets called:
```
public void onStopTrackingTouch(final SeekBar seekBar) {
    if (atLeastMin(seekBar, applyStepSizeAndLogScaling(seekBar.getProgress()))) {
        saveSetting(applyStepSizeAndLogScaling(seekBar.getProgress()));
    }
}
```

So storing the new value is only being performed, when `atLeastMin()` returns true.

A step size and log scaling functions gets applied to the raw slider value before it is compared against the minimum (= `100`):

```
private int applyStepSizeAndLogScaling(final int rawValue) {
    final int scaledValue = useLogScaling ? (int) (((long) rawValue * rawValue) / maxProgress) : rawValue; // Approximate an exponential curve with x^2 or use linear curve x
    if (stepSize > 0) {
        return scaledValue / stepSize * stepSize;
    }
    return scaledValue;
}
```

`rawValue` is `100`, when the slider is moved to the left, leading to a `scaledValue` of `0` (since `maxProgress` is 60000).

Since the value returned from `applyStepSizeAndLogScaling` (= `0`) is less than the defined minimum (= `100`), `saveSetting` does not get called.

---

Observation 2 is probably related to this: On moving the slider from right to left, the above functions get called several times. As soon as it hits the lower possible limit, no new value gets stored, but the slider remains at the last visible position. So it depends on how fast you move the slider from right to left which value will be displayed last.

---

Observation 3 is probably related as well: The internal slider progress value seems to be displayed, not the one after scaling function being applied.

---

So I guess currently log scaling and minimum value > 0 do not work in conjunction. It should take minimum values > 0 into account on calculating and comparing values, and after checking `atLeastMin` it should store the calculated minimum value, if `atLeastMin` returns `false`.

@fm-sys 
According to Git you had introduced log scaling parameters etc. - can you have a look at this issue?

FYI: `ProximityPreference` uses `progressToValue()` and `valueToProgressHelper()` to convert the raw slider value (`progress`) to actual value (`value`). Maybe the log scaling function could be built upon this?
(Either by creating a subclass `LogScalingSeekbar` (or something like this), or by applying log-scaling `progressToValue()` and `valueToProgressHelper()` functions automatically, if parameter `logScaling` is set to `true`).

**Comment by fm-sys** [comment]
> @fm-sys
> According to Git you had introduced log scaling parameters etc. - can you have a look at this issue?

True. Unfortunately, I'm quite busy currently. Nearly no spare time for coding. I've assigned myself, but I probably won't work on it in the near future. If someone else wants to take a look, this would be highly appreciated.

**Comment by moving-bits** [comment]
Ok, understood. I can give it a try over the weekend.
