### ISSUE TITLE
unconfigured DT filter not doing anything

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14334]
View live map
Add a "Difficulty / Terrain" filter
Set any value
make sure "include caches without D/T" is OFF

Expected Result:
No labs

Actual results:
Labs are shown

**Comment by ztNFny** [comment]
In fact this happens when a D/T filter is added but no value is set (i.e. both min=1 and max=5). In this case the filter is not actually used (as can be seen by it not being mentioned in the filter toolbar and in filter logic the values are null (instead of 1/5).
As a user I'd actually expected it to still work - after all I added the filter.

Opinions?

**Comment by fm-sys** [comment]
The reason for this was that there are geocaching services allowing T ratings over 5. Therefore it was decided to define borders as <=1 / >=5

**Comment by eddiemuc** [comment]
It was a general design decision that unconfigured filters don't filter anything, this is true for every filter. To put it differently: if a user adds a filter to his list, it shall be added with settings such that the filter doesn't filter anything. From this point on forward the user ma configure what to filter.

To make this possible for D/T filter, one simply has to extend the bar with values e.g. "<1" and ">5" and select them too in "unconfigured" state. IIRC this was discussed but revoked because almost all users would be confused by this (they don't care for such special cases).

The other thing: if adding this filter and immediately apply filtering 1-5 then caches w/o D/T (e.g. Labs) will immediately be filtered out. It this really wanted?

**Comment by ztNFny** [comment]
This issue was originally mentioned to me by a user during an event, I'll check again with him what exactly the scenario was. Maybe i got something wrong in my trying to reproduce his issue.

Not applying am unconfigured filter sounds kinda right.

**Comment by ztNFny** [comment]
User doesn't remember his scenario anymore ... Closing
