### ISSUE TITLE
UnifiedMap: Compass rose not displayed initially after map rotation

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14349]
### Describe your problem!

Compass rose (as indicator that map is currently not northbound) is not drawn on `UnifiedMap` after first rotation. It only appears after hiding the action bar (and stays there after unhiding).

(tested against VTM / Mapsforge offline map)

### How to reproduce?

- go to Unified Map
- rotate map

### Actual result after these steps?

map is rotated, but no compass rose is being displayed. It appears only after hiding the action bar

### Expected result after these steps?

compass rose should be displayed even after initial rotation

### Reproducible

Yes

### c:geo Version

current master

**Comment by fm-sys** [comment]
For GMap this should be fixed with https://github.com/cgeo/cgeo/pull/14341, however I had problems with the initial compass placing for VTM...

(Side note: IMHO the actionbar hiding feature starts to cause way too much development effort and additional complexity for not really much benefit... I don't think it's really worth it at all.)
