### ISSUE TITLE
(Sometimes) treat "x" as "*" in formulas

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#14461]
### Tell us your idea!

It is very common to encouter coordinate formulas like these ones:

`N48°14.BxE+C+D+2xA E011°34.E+D+2xB+3xA`

Here obviously "x" stands for "*". Of course this is stricly speaking an error on the cache creator's part, but it is so common, that it would be nice if c:geo would correctly interpret such formulas.

### What solution would you suggest?

If "x" is between _capital_ letters or parantheses, treat it like "*".

If "x" is between mathematical operators, treat it like a variable.

**Comment by eddiemuc** [comment]
Problem here is that c:geo also supports "variable concatenation" by common request: imagine that in this cache the variables `B`, `x` and `E `are defined, say they are set to `A=1`, `x=3` and `E=5`. Then to what should the expression `Bx`E evaluate? As of today it would evaluate to `135`. This supports things like e.g. `N48°14.BxE`

While here things may seem obvious to humans, what about we use different vars and lowercase ones. E.g. instead of `BxE` we have `wxy`. Would `x` be interpreted here as a var or as a multiplier symbol? What about mixed things like `2xa`?

As of now I haven't found a good solution to handle all cases. One idea would be to forbid lowercase `x` as a variable at all except when prefixed with `$` (e.g. `$x` is the variable `x`, but `x` is a multiplier symbol). Another idea was to interpret x as multiplier symbol when it is surrounded by whitespace (e.g. in `BxA` it is a var, but in `B x A` it is a multiplier symbol), but that was disregarded by the team.

**Comment by dcjkfgdjhd** [comment]
Yes, I understand the issue. There is no "correct" way to do it, one can just aim to use an interpretation that is more often correct than not.

My suggestion, as writen above, would be to interpret "BxE" as "B*E". Similarly "Bx(A+E)" as "B*(A+E)" and "(A+B)x(C+D)" as "(A+B)*(C+D)".

Lowercase variables are quite rare already, but I don't think I have _ever_ seen a cache that concatenates upper and lower case in a single formula. Thus I believe that my suggestion would treat many more cases correctly than the current setup does.

On the other hand, in "A*x+5" it is clear that x must be a variable, and this can easily be recognized by the operators "*" and "+".

**Comment by eddiemuc** [comment]
To move forward with this and to have a checkable approach, I suggest that someone provides a regular expression (or regular-expression-like description) to select exactly those x'es in a formula which shall be replaced by *. Note that such an expression is needed both for the simple formula case and for coordinates with formulas inside (e.g. `Nx8 13.Ax(x+1) Ex^2-5 2x.2x2A`)

**Comment by Lineflyer** [comment]
I doubt there would be any "fail safe" regex for such approach...but proof me wrong.
I personally think we should stick with `x` being treated as variable and `*` being treated as multiplication sign.

**Comment by Lineflyer** [comment]
Second thought:
We could think about having a new function in the "magic wand menu" like "Interpret x as multiplication" to on demand auto search and replace all occurences of `x` bx `*` in a formula, which has been entered. Would that be a feasible compromise for such scenarios?

**Comment by moving-bits** [comment]
> Second thought: We could think about having a new function in the "magic wand menu" like "Interpret x as multiplication" to on demand auto search and replace all occurences of `x` bx `*` in a formula, which has been entered. Would that be a feasible compromise for such scenarios?

This sounds like a very viable solution. For this special case probably no automatism will fit for all circumstances, so let "biological intelligence" step in and let the user decide when to fire a "x = *" solution.

**Comment by moving-bits** [comment]
@dcjkfgdjhd 
For reference: We had a longer discussion in the past about how to handle the "x=*" scenario, see #13844 for reference (and #13876 for a possible implementation).

**Comment by dcjkfgdjhd** [comment]
> Second thought: We could think about having a new function in the "magic wand menu" like "Interpret x as multiplication" to on demand auto search and replace all occurences of `x` bx `*` in a formula, which has been entered. Would that be a feasible compromise for such scenarios?

Maybe this could be a toggle option. In my region "x" as a variable basically does not occur, so I would like to keep that option permanently on.

**Comment by ztNFny** [comment]
this issue is a dup of #13844 and should be closed, no point in having 2 issues for the same topic.

As for the content I still stand by "Input must always be interpreted as entered. Shit in, shit out". Any improvement should be implemented in the formula scanner / improver part and not the calculation.

**Comment by eddiemuc** [comment]
> this issue is a dup of #13844 and should be closed, no point in having 2 issues for the same topic.
  
Agree

> As for the content I still stand by "Input must always be interpreted as entered. Shit in, shit out". Any improvement should be implemented in the formula scanner / improver part and not the calculation.

I agree to the "shit in shit out" Mantra in general. However, I feel this issue is more about what to consider "shitty" and what not. E.g. is the interpretation of a formula `3 x 4` as `3 times 4` shitty or not.

I also think that this issue is first not about whether to implement something in scanner or calculator. Regardless of where this is finally put, a rule for Interpretation of `x`-symbols in the formula has to be agreed upon. It is about the finding of this rule. As of now rule is `always interpret x as variable`.

If someone could offer e.g. a Regex (or other formal ruleset,) identifying all `x`'s in the formula which should be interpreted as `multiplier` then we could still decide whether to use this Regex in the scanner (and in which one, there is a scanner for formulas in listing, a scanner for calculated coordinates in listing and the "wizard" inside calculated coordinate dialog) or the calculator.

**Comment by dcjkfgdjhd** [comment]
> I agree to the "shit in shit out" Mantra in general. However, I feel this issue is more about what to consider "shitty" and what not. E.g. is the interpretation of a formula `3 x 4` as `3 times 4` shitty or not.

Completely agreed.

> (or other formal ruleset,)

As I already said, my rather simple ruleset would be: 

```
Ignoring spaces, if x is enclosed by capital letters and/or parantheses, replace it by `*`.
(Here the N/S and E/W in the relevant places of coordinates are not considered capital letters.)

Otherwise, treat it as a variable.
```

Not very advanced, but already this simple rule handles a lot more caches correctly than the current one.

**Comment by ztNFny** [comment]
Lets continue in #13844 to avoid further fragmentation of this discussion. I'll add a summary of the points from this issue there in a moment.
