### ISSUE TITLE
UnifiedMap: Heading indiciator needs to take map rotation into account

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14479]
Found a bug while playing a bit with UnifiedMap during my vacation:

If you rotate OSM map, heading indicator will point in direction of travel and adjust accordingly, but only as long as your map is heading northwards. If you rotate your map, heading indicator will still point into the same direction, although it should adjust according to the rotated map.

(Switching to UM / Google Maps made c:geo crash, so I could not check whether it's related to OSM only.)

Version is release 2023.06.18

**Comment by fm-sys** [comment]
Affects google unified / VTM. Cannot be implemented currently, as GeoItemLayer doesn't provide the necessary styling methods.

In VTM this can easily be fixed by setting `billboard=false` while creating the `MarkerSymbol`, gmap most likely provides a similar method with different name (haven't looked it up). However, as it is not the expected behavior for all marker types, the solution should be to introduce a styling attribute inside `GeoIcon`. 


billboard=true | billboard=false
-|-
[Screen_recording_20231208_002132.webm](https://github.com/cgeo/cgeo/assets/64581222/0d279239-d223-4c48-8425-64690882139c)|[Screen_recording_20231208_001835.webm](https://github.com/cgeo/cgeo/assets/64581222/8b713575-5348-4a23-aeab-ababcb633042)
(default state) This should be used for cache markers, etc | this should be used for rotation dependent markers => heading indicator

I've added two videos explaining the two rotation types
