### ISSUE TITLE
Default image name - as setting under logging

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#14516]
### Tell us your idea!

Currently each image added to a log entry is named (captioned) "Image", with multiple images numbered sequentially from 2 upwards. 

It would be useful to be able to set the default naming rule for images.

### What solution would you suggest?

I suggest a setting group under "Logging" as follows: 
checkbox "Default image caption"
- unchecked = use filename
- checked = use custom text defined by user, including the use of placeholders (same as log text)

### Is there an alternative?

No at this time.

**Comment by eddiemuc** [comment]
I vote for allowing to set a custom (fixed) Prefix to overwrite the system-assigned one ("Image"). The other aspects are not feasible imho:
* "filename" is not useful is practice since most log images are camera-images, and the filenames are system-generated ones
* Implementing a "placeholder" system for log image captions would be too complex for this use case

**Comment by eddiemuc** [comment]
Fixed with PR #14548
