### ISSUE TITLE
Adding a filter-possibility into the list selection

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#14602]
### Tell us your idea!

Adding a better filter into the list selection might also help...

_Originally posted by @wolverine007 in https://github.com/cgeo/cgeo/issues/14463#issuecomment-1672793299_

Having a bunch of lists, it is not easy to select the correct ones. 

### What solution would you suggest?

Having a "search/filter"-option / field in the select-dialog, the stored lists can be limited to the desired ones.

Something like this (but also for multiselection...)

![59cqH](https://github.com/cgeo/cgeo/assets/70113341/15bd4891-8919-4c84-ab18-542327953e88)

**Comment by ztNFny** [comment]
like https://github.com/abumoallim/Android-Multi-Select-Dialog ?

**Comment by bekuno** [comment]
> like https://github.com/abumoallim/Android-Multi-Select-Dialog ?

No development since 5 years :-(

**Comment by ztNFny** [comment]
The screenshots in OP are waaay older ;-) My question was whether this is what @murggel is asking for with this request.

Also - some stuff is just finished, no further dev needed. The implementation looks very trivial, could use some updates to the latest libs, but codewise there isn't much.

**Comment by murggel** [comment]
> The screenshots in OP are waaay older ;-) My question was whether this is what @murggel is asking for with this request.
> 
> Also - some stuff is just finished, no further dev needed. The implementation looks very trivial, could use some updates to the latest libs, but codewise there isn't much.

The  screenshot was just a quick example for the functionality, of course not for look&feel...

**Comment by murggel** [comment]
And of course should this be possible for the option of single select a list ;-)

**Comment by moving-bits** [comment]
We should not introduce yet another software dependency for something trivial like a list filter. (But I guess linking to the project was just meant to show an example, not necessarily to include this library.)

If we add a search filter to our list selector, it should be added as a feature to our default dialog components (if feasible), IMHO, so that it adheres to c:geo look&feel, and so that we can reuse it.

**Comment by moving-bits** [comment]
For multi-select lists see PR #14675.

For single select lists (specifically the grouped ones) I have additional questions:
- How to handle group headings?
  - Should filtering also apply to group headings? (If so, then see follow-up question below)
  - Or shall all group headings always be visible?
  - Or just those which have matching entries?
  - Or shall group heading become invisible when filtering?
- If a group heading matches to the filter string, shall all entries of this group be displayed?

Implementation-wise simply turning off group headings (= not displaying them) when filtering would be the easiest, but I'm not sure if this would be an acceptable behavior for all use-cases we have currently (function selection in variable list view and several `TextSpinner` contexts).

**Comment by eddiemuc** [comment]
Ah the grouping....

I would leave all the grouping headers visible in which there are filter findings. But other opinions probably exist :-)

**Comment by eddiemuc** [comment]
@moving-bits I am thinking about redesigning the SimpleDialog class for some time now already. I don't like the way that certain method parameter list have grown in size again and that certain combinations of attributes are still not possible (e.g. displaying tetxt message AND have an item selection). If you want to move away from this topic I could gladly take over, including the filtering + grouping thingies

**Comment by moving-bits** [comment]
@eddiemuc Please go ahead. I could finish filtering for single choice first, and you start from there, or you could take over from current PR for multi selection or from current `master` as well - either would be fine for me.

**Comment by eddiemuc** [comment]
> @eddiemuc Please go ahead. I could finish filtering for single choice first, and you start from there, or you could take over from current PR for multi selection or from current `master` as well - either would be fine for me.

Please finish/merge your PR first. I can't code today anyway 😄

**Comment by moving-bits** [comment]
> > @eddiemuc Please go ahead. I could finish filtering for single choice first, and you start from there, or you could take over from current PR for multi selection or from current `master` as well - either would be fine for me.
> 
> Please finish/merge your PR first. I can't code today anyway 😄

multi selection only, or single selection as well? (haven't started the latter yet)

Multi selection is nightly-ready. There's a small mostly cosmetic thing with the "select all" state in combination with filtering (reset its state when filtering changes amount of elements visible), but that can be fixed when the new structure is implemented.

**Comment by eddiemuc** [comment]
> > > @eddiemuc Please go ahead. I could finish filtering for single choice first, and you start from there, or you could take over from current PR for multi selection or from current `master` as well - either would be fine for me.
> > 
> > 
> > Please finish/merge your PR first. I can't code today anyway 😄
> 
> multi selection only, or single selection as well? (haven't started the latter yet)

multi selection only

**Comment by moving-bits** [comment]
> multi selection only

done

**Comment by MagpieFourtyTwo** [comment]
Really nice stuff - but ... the font is way bigger now and the line height wastes a lot of precious space ... like it already did in all menus and the map selection list before ... has this happened while implementing the filter or is this a general UI issue (which then of course needs a dedicated issue)?

**Comment by moving-bits** [comment]
This one seems to be hard to tackle. Not sure why it uses a different formatting at all although I'm using the original material style formatting template they use internally. Trying to fix the appearance (without copying and adapting the template), font size injection was the easy part, but I could not get the exact item spacing we had before - it seems to be neither default material style (48dp) nor our defined internal preferred height (32dp), but something in-between. Or some other factor (like margins) is stepping in, have not found out yet. Current state (see PR #14691) will be like this:

|old|current|new|
|---|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/bd32361e-09a0-4c43-a7fb-db01cec6472b)|![image](https://github.com/cgeo/cgeo/assets/3754370/8c1f436b-dd98-4fff-b5fe-7947804a5918)|![image](https://github.com/cgeo/cgeo/assets/3754370/68123d9d-885e-4940-8b6d-867deb05c633)|

Font size in "new" is similar to "old", but the list is even more dense than in "old" 🤔

**Comment by ztNFny** [comment]
The button size/spacing also seems to be smaller?

**Comment by moving-bits** [comment]
> The button size/spacing also seems to be smaller?

Do you mean the checkbox size or the last line with "last selection" / "ok" buttons? The latter has identical height in all three variants, whereas the checkbox size depends on font size, so the middle one is larger than the two others.

**Comment by ztNFny** [comment]
> Do you mean the checkbox size or the last line with "last selection" / "ok" buttons? The latter has identical height in all three variants

the last line. it's definitly different in screenshots 1 vs 2/3
![image](https://github.com/cgeo/cgeo/assets/1258173/7d66f4e9-7272-4875-8a5b-6a17e0485e43)

**Comment by moving-bits** [comment]
The space reserved for the buttons ("Last selection" and "Ok") is identical (I compared the three original screenshots side by side pixel-wise):
![image](https://github.com/cgeo/cgeo/assets/3754370/41585ad2-7fb0-41fa-a753-36e356485f1d)

Visual difference comes from the last (partially) visual item ("United Kingdom" resp. "Test A") being cut-off in different places due to the item heights being different in the three variants.

**Comment by ztNFny** [comment]
your screenshots have different heights, sorry, didn't notice that.

**Comment by MagpieFourtyTwo** [comment]
Same problem exists in all menus (which is not as bad, because the menus are not so long anyway), but as well as e. g. in the map selection list and the ``Pick a list`` popup you get after a long click on the bottom menu item ``Stored`` (which BTW might be another place where the filtering should be implemented, at least to be consistent).

However, as for me the variant "new" would already be "acceptable", although the font still seems to be significantly larger than e. g. the font of the ``Details`` page, which makes no real sense to me.  I would use the same (smaller) font for the list selection (and for e. g. the map selection list, too, plus a smaller line height, of course) ...

**Comment by moving-bits** [comment]
> your screenshots have different heights, sorry, didn't notice that.

yeah, that's a bug (IMHO) in GitHub: If you have a couple images of same size side by side in a table, and view this with different widths (resizing, or desktop vs. mobile etc.), it's very likely that those images are presented in different sizes in the same view. For example: If I make this window here smaller, my table above looks like this for me at some stage: 

![image](https://github.com/cgeo/cgeo/assets/3754370/fe153408-ead3-4b44-b054-33cda098dbf6)

Three different sizes, although all three got uploaded in the same size. My guess it that it depends on the length of the table header in each column.

**Comment by moving-bits** [comment]
> Same problem exists in all menus (which is not as bad, because the menus are not so long anyway)

Menus probably use the default Material components font sizes (haven't looked up).

IIRC we had a discussion about item spacing for the list selection dialogs when we did the UI overhaul in 2021 (?) and decided to make it a bit more dense and a bit smaller in text size, compared to regular lists / menus. Normally we use 18 sp for lists (placeholder `listsPrimary`). Instead of this, we decided to use our default text size for longer texts (placeholder `detailsPrimary`) (16 sp), which BTW is the same font size we use for the cache description.

There are a couple of places, though, where we use the even smaller `detailsSecondary` (14 sp), eg on cache details page for attributes' description. This size is used for texts we considered less important than the main text, thus info of "secondary importance".

> but as well as e. g. in the map selection list and the `Pick a list` popup you get after a long click on the bottom menu item `Stored` (which BTW might be another place where the filtering should be implemented, at least to be consistent).

This list selection is a single-selection, for which filtering is not yet implemented, although this selection is using our internal default component meanwhile. (This is the reason why this issue is still open, as single selection lists-filtering is yet TBD.)

**Comment by eddiemuc** [comment]
Rough implementation idea:
- create new view component to visualize selection lists. Includes options for single vs multi, grouping and filtering
- split from simple dialog a new `Simple ItemsDialog<T>` class for Dialogs containing item list. This prevents having to type simple dialogs w/o lists
- change alertdialog usage to customized view. This allows for e.g. using message and items in one dialog

**Comment by moving-bits** [comment]
Finalized with #14778, so let's close here
