### ISSUE TITLE
Possibility to use a saved filter as a nested filter

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#14600]
### Tell us your idea!

Sometimes there are complex sub-queries, which I want to reuse in different filter as nested filter.
At the moment I have to create it again for each filter, I want to use it in.

### What solution would you suggest?

Reuse an existing already saved filter as a nested sub-filter.

open questions:
- avoiding recursive nested filter
- original filter-settings changed
-> use the changed filter
- original filter was deleted
-> warn before deletion?
-> remove nested filter?
- ...

**Comment by eddiemuc** [comment]
Spontaneous idea how to implement:

Create a new filter "Named Filter" under category "special filters". User can there:
- select an existing stored named filter
- checkbox "include all when loop-nested": if filter is recursively nested then don't evaluate but return true/false depending on this checkbox
- checkbox "include all if filter is deleted": if filter doesn't exist (any more) return true/false depending on this checkbox

This solves recursion/deletion Problem in a neat way w/o having to check any filter interdependencies on edit time. Since this is clearly an expert expert filter it seems valid to assume the user understands

Alternatively to the checkboxes, filter may silently return false on mentioned situations (filter deleted or nested recursively). Would be my personality preferred solution

**Comment by murggel** [comment]
> Alternatively to the checkboxes, filter may silently return false on mentioned situations (filter deleted or nested recursively). Would be my personality preferred solution 

This would be my preferred solution as well

**Comment by fm-sys** [comment]
> checkbox "include all when loop-nested": if filter is recursively nested then don't evaluate but return true/false depending on this checkbox

There is no use case for such a checkbox yet, cause we don't have a if-cause filter + conditions (and probably never will have)

Only situation I can think of is an OR filter with "short circuit evaluation". But that's definitely an edge case.

Just silently retuning false together with a big warning is the way to go IMHO. The warning should IMHO be placed at the top of the filter dialog (+ maybe in the filter bar as well)

**Comment by eddiemuc** [comment]
I plan to work on this issue after migration of filter config to json

**Comment by eddiemuc** [comment]
PR #14677
