### ISSUE TITLE
Don't use  `textVisiblePassword`

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14732]
Using `textVisiblePassword` is a really bad workaround!

In fact the behavior is highly dependent on the keyboard you are using.

One my device (using SwiftKey keyboard) e.g. the clipboard feature is missing when using `textVisiblePassword`. Which is IMHO way worse than a missing number row. BTW, you can choose whether to always show the number row at least for some keyboard apps. IMHO it's not up to c:geo to "optimize" the keyboard in such a hacky way. 

Normally | with textVisiblePassword
-|-
![Screenshot_20231011_230033_cgeo geocaching](https://github.com/cgeo/cgeo/assets/64581222/f3a2671a-42f4-4f38-85fc-f2ea7f796692)|![Screenshot_20231011_230050_cgeo geocaching](https://github.com/cgeo/cgeo/assets/64581222/1c725688-cc96-475e-b90d-f151f7c74d42)

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/14711#issuecomment-1758544946_

**Comment by moving-bits** [comment]
An alternative approach is described here: https://github.com/cgeo/cgeo/pull/14711#discussion_r1355121135.
This supports auto-cap for letters, and allows numbers to be entered as well.

In emulated Pixel mobiles numbers are accessible via long-press, no need to switch keyboard views (but other keyboards may behave differently).

Android seems to have no _predefined_ combination for showing both letters and numbers at the same time, so this combination may be as close as we get to the original feature request (#7149) in a _defined_ way.

**Comment by Lineflyer** [comment]
> Android seems to have no predefined combination for showing both letters and numbers at the same time, so this combination may be as close as we get to the original feature request (https://github.com/cgeo/cgeo/pull/7149) in a defined way.

I tested on several Samsung, ZTE, Huawei and some emulators using their default keyboards.
The `textvisiblePassword` was the only method I found to have the convenience of both numbers and letters. Also on the net you will mostly find this advice. 
@fm-sys Are you sure you can't paste anything into that field (e.g. via long-press)?

**Comment by fm-sys** [comment]
For sure I can paste things via long click and we even have the "automated paste" functionality... Still it's a bad experience compared with what the keyboard could offer... (accessing multiple clipboard entries at once, cross-device clipboard, etc) 

|||
|-|-|
![Screenshot_20231015_234233_cgeo geocaching](https://github.com/cgeo/cgeo/assets/64581222/901e561f-431c-4d65-b5fb-ddcad68af7f4)|![Screenshot_20231015_234204_cgeo geocaching](https://github.com/cgeo/cgeo/assets/64581222/ee85679b-c494-4e51-ba33-651b26169015)

**Comment by eddiemuc** [comment]
I am undecided on this one.

On one hand I am fully with @fm-sys : it is not up to an app trying to hack android's text input type system to accommodate for inappropriate keyboard apps or settings of the user for her system. There are many great keyboards available for Android and at least the one I know (GBoard) allows for forced numeric value display on qwertz keyboard.

On the other hand, if this is indeed a widely used hack then one could argue that users are used to this "hacky" experience and probably accept it.

Question for me is therefore: which other apps (common ones or geocaching ones) are using this hack? If it is widely used we should leave it in. Otherwise we shouldn't.

A compromise could be to introduce a setting for this. I know we have too many already, but with recent differentiation of "basic" and "advanced" settings this might not be too critical any more.

**Comment by ztNFny** [comment]
I vote against a setting as no normal user would have the chance of understanding what it does, especially as it seems to depend on the keyboard.

I wonder why we should change anything. The current workaround seems to work for most/many keyboards. Never change a running system.

**Comment by Lineflyer** [comment]
And the visiblepassword type is in there since a long time.
I recently only added the autofill=no to avoid triggering password managers on this field.

**Comment by Lineflyer** [comment]
I guess we have no clear majority on removing this and its in there since longer time. 
I suggest to close this issue for now until someone comes up with a better solution without drawbacks.

Feel free to reopen if you think its worth it.
