### ISSUE TITLE
Position of elevation info on map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14756]
> If we really don't want to have it close to the other numbers in top right position, an alternative approach could be to put it as default info at the bottom of the long press popup menu.

Its an option, the user actively needs to turn on, isnt it?
Then I dont see a problem showing it next to the position icon then. The user is interested in it and he can also easily move the map if something is covered below. 

The top right is IMHO not at all the right position for an information not related to a route. 

Shall we take this to a new issue?

_Originally posted by @Lineflyer in https://github.com/cgeo/cgeo/issues/14744#issuecomment-1774210148_

**Comment by ztNFny** [comment]
> As mentioned by @ztNFny in [#14757 (comment)](https://github.com/cgeo/cgeo/issues/14757#issuecomment-1778063046), I also vote for elevation info of map center instead of current location.
> 
> Reason: As a user I have no benefit from knowing "oh, I'm on 900m" but a great benefit from knowing "the next cache is on 1500m, so I'll have to take 600 hight meters to get there"

As I understand it this issue is about where (top right vs middle) to show the info, not which info (current position vs map center)

**Comment by fm-sys** [comment]
Should I open a fourth issue for somehow one and the same topic, or what would be the place where this suggestion fits best?

**Comment by fm-sys** [comment]
I think which and where are highly coupled, as we can only find a good and understandable position as soon as we have agreed on what we actually want to show.

**Comment by ztNFny** [comment]
We first need a statement from whoever implemented it on what it shows and what's the usecase for that - can't find that documented

**Comment by Lineflyer** [comment]
> Should I open a fourth issue for somehow one and the same topic, or what would be the place where this suggestion fits best?

I think what info to show can be discussed in #14757 as the feature of showing the map center elevation would lead to a decision to accept, that we show different information between home screen and map.

**Comment by fm-sys** [comment]
![Unbenannt](https://github.com/cgeo/cgeo/assets/64581222/de90606f-0cc7-4278-9cd3-ce3424614156)

Thanks for the highly valuable feedback, which greatly helps me to post suggestions in the right place! How bad that not everyone understands irony, or I just didn't make it clear enough... It should read as "please tell me where" instead of "not here".

I totally agree that this topic is already split way too much.

(BTW, thumbs down reactions on GitHub and especially in the c:geo project are generally considered quite rude, while they don't bring value. It's always better to explain why you don't like a specific idea/feature request. While you most probably have good reasons to downvote a specific post, no one can look into your head. In other words, an idea/feature will more likely be declined when good arguments against it are posted in the thread.)

**Comment by ztNFny** [comment]
> While you most probably have good reasons to downvote a specific post, no one can look into your head. In other words, an idea/feature will more likely be declined when good arguments against it are posted in the thread.

Like the comment right below yours?!

> thumbs down reactions on GitHub and especially in the c:geo project are generally considered quite rude,

Sorry if YOU *interpret* it that way - I don't

**Comment by Lineflyer** [comment]
I want to draw back the attention to thus issue:
IMHO showing the elevation info on top right together with route stuff is really not well chosen. Also I already mixed it up when looking for route distances.

I would still favor to shown the elevation next to the position icon if the option is turned on.
This give a clear hint about what this figures is and to what position it relates.

**Comment by moving-bits** [comment]
Proposal for new position of (current position) elevation info: Put it into a small text line before the position indicator:

![image](https://github.com/cgeo/cgeo/assets/3754370/24e6dece-7d17-4561-a87a-4c119d3aee30)
