### ISSUE TITLE
big icon for visited waypoints 

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#14853]
### Tell us your idea!

In the mode "big icons" use on found caches for existing waypoints the state icon (ok hook) as maximized icon and the type icon as icon on the right lower corner. This means that the two symbols should be swapped. 
 
Current symbols for waypoint and cache:
![Screenshot_20231119-203346_cgeo](https://github.com/cgeo/cgeo/assets/32555742/8bed5a46-0b6a-4c7a-b5ed-1ec636b4fb88)

### What solution would you suggest?

For waypoints of found caches swap the two symbols of cache type and state. 

### Is there an alternative?

Let it as is.

**Comment by fm-sys** [comment]
⇒ it should be visible whether the cache a waypoint belongs to is already found.

@ztNFny do you have an opinion?

**Comment by ztNFny** [comment]
> For waypoints of found caches swap the two symbols of cache type and state.

I don't understand this suggestion. Why should the icons be in different places if the cache is found vs unfound?!

> ⇒ it should be visible whether the cache a waypoint belongs to is already found.

Like for a found caches WPs instead of the type icon display a smiley? Would be confusing imho. Why do people display waypoints of found caches anyway?

**Comment by ztNFny** [comment]
And what does this have to do with big icon mode? That setting has no influence on waypoint markers.

**Comment by fm-sys** [comment]
> Like for a found caches WPs instead of the type icon display a smiley? Would be confusing imho. Why do people display waypoints of found caches anyway?

/irony Hm, why do we show found caches on the map at all? I would strongly vote to hide them forever without a possibility to make them ever visible again. /ironyoff

Because there are valid use cases for it.

As a user, I don't want to know whether the waypoint belongs to a multi or mystery if the cache is already found.
For me, "found" can be considered as additional cache type somehow.

Imagine you see a parking way point on the map:
- tradi symbol in the top left => I can directly search it
- mysteries => I need to solve the clue before I can find the cache
- muliti => => it'll take several steps until I reach the final
- **found => I don't need to care about it at all**

==> It makes a huge difference whether a cache is found or not, so this information should be made visible in the waypoint icon. 
The best place I can find for it is the top left instead of the cache type icon, which would even be 100% consistent compared to _cache markers with big icon enable_

**Comment by MagpieFourtyTwo** [comment]
> Like for a found caches WPs instead of the type icon display a smiley? Would be confusing imho. Why do people display waypoints of found caches anyway?

Cause I want do this cache a second time - with a fellow who is going for this cache for the first time ...?
Or because I really liked it and just want to do it again, for my own pleasure?
Not all cachers are statistics-driven, some of them just do it for fun.  ;)

Therefore, if I decide to see a (found) cache (and it's visited WPs) on the map, the difference between found and unfound representation should not be too big.  So I can just do the cache a second time, w/o being forced to disable big icons, because they hide to much information (like they do right now already).

**Comment by ztNFny** [comment]
(irony)thanks for your very detailed explanations of what you want changed, that really helps(/irony)

> w/o being forced to disable big icons, because they hide to much information (like they do right now already).

Waypoint icons don't inplement big icon mode at all, so what you're saying doesn't make any sense at all.

Also for caches - unlike before with the old icons - all info available in normal mode is now also visible in big icon mode.

**Comment by ztNFny** [comment]
> The best place I can find for it is the top left instead of the cache type icon, which would even be 100% consistent compared to _cache markers with big icon enable_ 

What does this have to do with the visited marker OP is talking about????

**Comment by MagpieFourtyTwo** [comment]
You're welcome.  ;)

As I understood, OP wants to implement Big Icons for WPs, too.
Maybe I missed the point - if so, sorry for wasting your precious time.

**Comment by ztNFny** [comment]
> > Like for a found caches WPs instead of the type icon display a smiley? Would be confusing imho. Why do people display waypoints of found caches anyway?
> 
> /irony Hm, why do we show found caches on the map at all? I would strongly vote to hide them forever without a possibility to make them ever visible again. /ironyoff

You explicitly asked for my opinion. When that opinion apparently didn't match yours you go on a long rant - sorry, I refuse to communicate this way and this will not respond to further communication.

**Comment by fm-sys** [comment]
It's pretty normal that requirements and implementation details may change over time until a feature finally gets implemented. If you aren't interested in a topic, no one forces you to participate. However, we should always stay friendly and follow the [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).



Coming back to the discussing:

While I also dislike the idea of replacing the waypoint icon, my suggestion would be to show the found indicator not enlarged but instead of the cache type icon. 

This would make found / unfound WPs distinguishable, but without the mayor issues described above.

![grafik](https://github.com/cgeo/cgeo/assets/64581222/22a76b2d-bc3b-4a6f-880f-b9e70ca038e6)

**Comment by bekuno** [comment]
Sorry to have confused everyone. 

We don't have an option to hide waypoints for found caches on the map. That would be another feature request.

I didn't suggest drawing a big smiley for a waypoint of a cache - that would be confusing of course.

But there are situations where it would be beneficial to be able to more easily recognise the visited state of a waypoint on the map.

My idea was to use this - please compare with the original image.
![grafik](https://github.com/cgeo/cgeo/assets/32555742/dd9a6c3c-c4db-43ee-b0b7-96d515506457)

And, as drawn by @fm-sys in https://github.com/cgeo/cgeo/issues/14853#issuecomment-1819128959, it would be very nice to see the find status of the cache on the waypoint. It could replace the cache type icon or be added in a free corner.

**Comment by ztNFny** [comment]
> Sorry to have confused everyone. 

The description was unclear to me and i asked for details - nothing to apologize for!

> We don't have an option to hide waypoints for found caches on the map. That would be another feature request.

I will create a PR to integrate that with "hide visited WPs"

> My idea was to use this - please compare with the original image.
> ![grafik](https://github.com/cgeo/cgeo/assets/32555742/dd9a6c3c-c4db-43ee-b0b7-96d515506457)

I understand your request now. But _imho_ it's not worth the effort as implementation effort is high and gain is low.

first two conditions have to come together:
- big smiley mode enabled - it's not a default seeing
- user using the "visit waypoint" feature - which i guess not too many people are
Then the WP type icon would be very small (see cache icons, they mostly work by their color, not the icon).
-> low gain
And to enable that all the WP type icons would have to be recreated in small size (reusing the big ones sadly isn't possible) -> big effort

If someone else wants to take this on go ahead, the PR adding cache type icons to big smiley mode shows what needs to be done.

**Comment by ztNFny** [comment]
> But _imho_ it's not worth the effort as implementation effort is high and gain is low.

That said - if you prefer to have the "visited" large icon without the waypoint type marker that can be easily done (basically what we had for cache icons until the recent cache type marker introduction)

**Comment by bekuno** [comment]
> That said - if you prefer to have the "visited" large icon without the waypoint type marker that can be easily done (basically what we had for cache icons until the recent cache type marker introduction)

Would be fine for _me_.

**Comment by fm-sys** [comment]
BTW, just noticed that this issue did already exist in #12136. Let's close as duplicate.
