### ISSUE TITLE
UnifiedMap: Applying text/icon scaling behaves erratic

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15059]
_Based upon discussion in #15035:_

> > > ...except that text/symbol scale factors seems not to be applied yet. But that could be a yet-missing feature of c:geo's VTM implementation
> > 
> > 
> > They are working but you need to restart cgeo to apply them. There actually should be a third one, however it was causing problems. You can read more about it here: #13593
> 
> Restart did not do anything. I applied a text scale of 450% but text sizes are still pretty "normal". (using openandromaps with velocity theme). I didn't try any other maps/themes. Probably there is a bug hidden here?

Did a few more tests and was able to get scaling with all themes installed in this emulator (Default, Elevate/Elements, FZK and Velocity/Voluntary), although the behavior was NOT consistent: I had to restart the map sometimes, and/or open and close theme options menu (without changing anything in between).

Additionally changes to text size / icon size settings in theme options do not necessarily get applied immediately on closing the theme options menu.

Setting "Prio: Low" as I regard this a minor issue - probably one would not change this option that frequently, but set it once, and then forget about it.

**Comment by MagpieFourtyTwo** [comment]
Stumbled upon this problem today and wanted to open an issue - don't need to. Fine.  ;)
So just let me share my observations:
- theme option "Map Scale Factor" is missing completely (and I badly miss it)
- changes to text or icon scale are applied only after closing and reopening the map
- after restarting c:geo (incl. removing from recent apps) map scale is at 100 %,
  until I close the map and reopen it at least once.
- maybe it's because of missing "Map Scale Factor", but in UM fonts/symbols are *way* smaller than in "classic" map

BTW: Swyping through the map is way slower with UM, is this correct or just a local problem?

**Comment by fm-sys** [comment]
We had rendering problems which could only be solved by removing the map scale feature completely. See #13593.

We actually had discussed to remove text or icon scale as well as they are not working properly and wait if users will complain.

A solution which may work as well, instead of removing the features completely, make these settings global. UM isn't able to handle these scalings if the map is running before applying the scale. The other way around it should (hopefully) work. 

Do you definitely need these scaling settings and would making them global be fine for you?

> BTW: Swyping through the map is way slower with UM, is this correct or just a local problem?

I'm also experiencing this, but many others are reporting that UM is actually faster.

The difference between the old and Unified Map is that Map rendering is performed on GPU instead of CPU which can therefore differ based on your hardware. 

Are you still using your huawei phone like in 2020?

**Comment by MagpieFourtyTwo** [comment]
> Do you definitely need these scaling settings and would making them global be fine for you?

Global would be perfectly fine.  And, yes, I "need" them, currently even using ...
- Map Scale Factor of 140
- plus Text Scale 140
- and Symbol Scale of 120 percent.

Main reason is that I use c:geo as navigation system in car and on MTB, i. e. with a) a viewing distance of approx. 50 to 70 cm, and b) usually only with a brief sideways glance from the corner of my eyes - which makes e. g. reading street names kind of hard if scale is just 100 %.

> Are you still using your huawei phone like in 2020?

Yep, still exactly this beloved P30Pro, still in mint condition.  And still competitive, esp. WRT photography.  ;)

**Comment by devemux86** [comment]
If map scale means (global) user scale on everything, then need re-creation of map view (or app restart).

Text and symbol scaling is possible in real time with reload of the map source.
(like map size settings in Cruiser)

---

> BTW: Swyping through the map is way slower with UM, is this correct or just a local problem?

Complicated elements of some maps might have performance issues in small zooms on some GPU.
Vegetation in dense forests, water in Netherlands, probably because of map's default simplification.

Can try the `Parameters.SIMPLIFICATION_TOLERANCE = 4` to simplify polygons in small zoom levels (default < 12).
(like performance / quality rendering in Cruiser)

**Comment by devemux86** [comment]
To better read the map screen it is usually simpler to just change the the text / icon sizes.

> Moreover it feels a bit ... sluggish.

Rendering performance depends on the map content, themes, zoom, device, etc.
That's why can try the extra simplification in small zoom levels, where detail is not needed.

Map animations allow to define the duration and the easing type, so can customize them.

**Comment by fm-sys** [comment]
> Map animations allow to define the duration and the easing type, so can customize them.

This sounds really interesting! Could you give a small hint where/how to do this?

**Comment by devemux86** [comment]
@fm-sys 

Check the `Map.animator()` methods. You probably already use them to animate to map locations.

**Comment by fm-sys** [comment]
Sorry, probably there was a misunderstanding. We indeed already use the animator methods.

I think @MagpieFourtyTwo was talking about manual input gestures. The distance how far the map is scrolling after performing a fling gesture feels shorter in VTM compared to classic mapsforge.

Or did I get it wrong?

**Comment by MagpieFourtyTwo** [comment]
@fm-sys Yes, that's what I meant. Thx 4 clarifying.

**Comment by devemux86** [comment]
Important: Mapsforge and VTM are different map engines,
they are not supposed to work exactly the same way. :slightly_smiling_face: 

About the map gestures, cannot remember if there are methods to change their behavior.
Unless changing VTM code _and as option_, as current code is already public in several apps.

You can try the `Parameters.ANIMATOR2` (default true) to test the previous animations.

**Comment by devemux86** [comment]
Also comparisons should be make with "similar" force in the gestures.

Distance / speed of map movement depends on the force applied to the scroll gesture.
Larger map scroll distance / speed requires more powerful scroll gesture.

**Comment by moving-bits** [comment]
Did a few tests with `CanvasAdapter.userScale = x` with ranges from x=0.5f to x=5.0f:

|x=1.0f|x=5.0f|x=0.5f|
|---|---|---|
|![image](https://github.com/cgeo/cgeo/assets/3754370/0cd2ae31-e19f-4063-afee-60efbbba461f)|![image](https://github.com/cgeo/cgeo/assets/3754370/c05a3b76-b194-40c6-a586-a8bd6a7829c7)|![image](https://github.com/cgeo/cgeo/assets/3754370/64bd6010-160a-4c58-8393-757bf01570df)|

The only thing that seems to change visually is the scale bar at the bottom.

Either we are missing here something, or I propose to skip "user scale" for VTM (and stay with text scale / icon scale).

**Comment by devemux86** [comment]
> Either we are missing here something

Please see my comment above:
- https://github.com/cgeo/cgeo/issues/15059#issuecomment-1953675434

> I propose to skip "user scale" for VTM (and stay with text scale / icon scale).

:+1:

**Comment by moving-bits** [comment]
> > Either we are missing here something
> 
> @moving-bits please see my comment above:
> [...]

For testing, I had changed the value in code, then rebuild and restarted the app, so `MapView` was definitively fresh for each run :-)

**Comment by fm-sys** [comment]
> > > Either we are missing here something
> > 
> > 
> > @moving-bits please see my comment above:
> > [...]
> 
> For testing, I had changed the value in code, then rebuild and restarted the app, so `MapView` was definitively fresh for each run :-)

Have you applied the value inside `CgeoApplication` so that it is initialized before the map activity starts?

**Comment by moving-bits** [comment]
> Have you applied the value inside `CgeoApplication` so that it is initialized before the map activity starts?

Ok, this falls into the "have I missed something?" category... 🙈 Thanks for the hint, will investigate further...

**Comment by moving-bits** [comment]
Regarding the text & symbol scale options for VTM:

Would it be ok to make them global as well (as #15409 does for user scale; then moving them to system settings would be sufficient), or do they need to be theme-specific (then we would need to add some map recreation on changing those)?

**Comment by fm-sys** [comment]
Let's just make them all global IMHO, last but not least to avoid other unforseen side effects. We will see if someone complains about the feature loss.

**Comment by MagpieFourtyTwo** [comment]
For me at least, global values would be even more convenient, as I use the same values for all themes anyway. And the users, for whom I used to change the sizes in the theme files via script, did the same.

**Comment by moving-bits** [comment]
PR #15409 will reintroduce map scaling for VTM and make text/symbol scaling global for VTM.
