### ISSUE TITLE
geojson parsing broken for polygons with holes

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#15074]
### Describe your problem!

Geojson with holes can no longer be loaded.
Example file: [Netherlands_regions_all.geojson.txt](https://github.com/cgeo/cgeo/files/13756562/Netherlands_regions_all.geojson.txt)

Caused by https://github.com/cgeo/cgeo/commit/d51ded0c45e347a0426adcaae4c3f88329270280

### How to reproduce?

-

### Reproducible

Yes

### c:geo Version

2023.12.21

**Comment by eddiemuc** [comment]
This is caused by invalid data in the GeoJson file. For example the above file contains this invalid polyline definition (4 identical points):

```
          [
            [
              [4.930693263132631, 51.43716353893539],
              [4.930693263132631, 51.43716353893539],
              [4.930693263132631, 51.43716353893539],
              [4.930693263132631, 51.43716353893539]
            ]
          ],
```

https://github.com/cgeo/cgeo/commit/d51ded0c45e347a0426adcaae4c3f88329270280 "discovered" this problem because it removes duplicate conjecutive points in polylines (because VTM doesn't handle those very well), leaving the above polyine empty and thus invalid. c:geo then treated the whole GeoJson file as invalid. This kind of handling is of course far too unrelaxed  :-)

PR #15079 will relax the way c:geo handles the parsing of geojson files to display also invalid data as best as possible (for example the above part of the geojson will not be displayed any more isntead of generating an error)
