### ISSUE TITLE
Download POI/lopoints together with the map itself (OAM)

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#15113]
### Tell us your idea!

I've just discovered the possibility to download maps directly from c:geo (well, I knew this existed, but always was doing "the old way" downloading files myself). And it actually looks awesome!

The only thing is that I'm using Locus as well as c:geo and it would be great to have the  POI file downloaded as well as `.map` file (talking about OpenAndroMaps now, not sure about other sources)

### What solution would you suggest?

Download not only `.map` file, but also `.poi` and `.db`

### Additional Information

Actually it seems the both files are anyway already present in the zip archive downloaded from OAM, so maybe just add option to keep them?

Probably some modifications around here https://github.com/cgeo/cgeo/blob/master/main/src/main/java/cgeo/geocaching/downloader/ReceiveDownload.java#L81

**Comment by devemux86** [comment]
Probably related to:
- https://github.com/cgeo/cgeo/issues/14266

**Comment by eddiemuc** [comment]
> Probably related to:
> - https://github.com/cgeo/cgeo/issues/14266

The linked issue would be about using the poi file in c:geo for offline searches.

Here, the user just requests it's download (or rather: not deleting it after extraction).

**Comment by moving-bits** [comment]
@okainov 
Would it be ok for you if we simply don't delete the downloaded zip file (on request), so that you could extract the POI file yourself?

As long as we are not using the POI file in c:geo (which we currently can't, due to POI API not being SAF-compatible), I would prefer to avoid having to add extra POI file handling in c:geo like 
- extracting the file from ZIP (but only for map sources supporting this, maybe even add special handling for map sources delivering POI files as separate files)
- deleting POI files when deleting a downloaded map
- etc.

**Comment by okainov** [comment]
@moving-bits in general it should be fine (if there is some info/notification, where was the archive downloaded), in this case I'd still need to do also the renamings myself (as cgeo renames the map files)б but anyway this should be easier than re-downloading completely...

**Comment by moving-bits** [comment]
Implementation is ready code-wise, but... stumbled upon blocking #15148 which I have found no solution for so far
