### ISSUE TITLE
Geojson display different between NewMap and UnifiedMap

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#15333]
Geojsons are drawn very different on UnifiedMap. Is this by intention? I find the "old" display style to be better suited than the old. But it's not really a bug, more of a question - if it's as designed.
@moving-bits 

![ResizedImage_2024-02-14_21-07-56_2.jpg](https://github.com/cgeo/cgeo/assets/1258173/b3ddcfa7-4b9a-44e6-b4e1-31ac51766191)

![ResizedImage_2024-02-14_21-07-56_1.jpg](https://github.com/cgeo/cgeo/assets/1258173/0e51bf58-c903-471d-953d-4ae4643d5a80)

[de.geojson.txt](https://github.com/cgeo/cgeo/files/14285709/de.geojson.txt)

**Comment by moving-bits** [comment]
Probably no intended difference. If it's VTM, you could have a look at the VTMGeoItemLayer (don't have the exact name at hand currently), or similar for UnifiedMap GoogleMaps

**Comment by eddiemuc** [comment]
Definitely not intended.

The underlying problem is that VTM is not as mature as other frameworks used to play "things" on the map compared to e.g. mapsforge or Google Maps. Reason is that those frameworks at one point or another will use Android SDK methods to draw things (e.g. drawLine and the like) while VTM builds up even these basic drawing forms itself using OpenGL.

The problem should be tackled by playing with the Style settings set in class `cgeo.geocaching.unifiedmap.geoitemlayer.MapsforgeVtmGeoItemLayer` , method `add`. Probably playing around with the dropDistance parameter may help. Note however that this was introduced to solve the problems in #15029, so when modifying those one has to double-check the impact on this.

https://github.com/cgeo/cgeo/blob/6f828f54f15aa4c800cd84b1785e81d43a8e92ad/main/src/main/java/cgeo/geocaching/unifiedmap/geoitemlayer/MapsforgeVtmGeoItemLayer.java#L128-L136

**Comment by ztNFny** [comment]
> Probably playing around with the dropDistance parameter may help.

If I understand it right that parameter controls how detailed the line is drawn? While I think it should be a bit more detailed than it's now my main issue is with the display properties: Line width, color and fill of the polygons (those are explicitly given in the geojson input, so I'd expect them to be applied the same).
I'll try taking a looking at that method/class, see whether I can find something.

**Comment by eddiemuc** [comment]
> > Probably playing around with the dropDistance parameter may help.
> 
> If I understand it right that parameter controls how detailed the line is drawn? 

Correct. This is done by removing points from the line which are "close together".


> ... my main issue is with the display properties: Line width, color and fill of the polygons (those are explicitly given in the geojson input, so I'd expect them to be applied the same). I'll try taking a looking at that method/class, see whether I can find something.

Ok this was a misunderstanding on my side (sorry for that). This has to be solved on anothr place most likely. Maybe the factor applied to line width read from geojson needs to be adjusted.

**Comment by ztNFny** [comment]
Just realized the issue is OSM-only:
![image](https://github.com/cgeo/cgeo/assets/1258173/01e7d583-b837-4130-b2e7-3247512a827c)
vs Google Maps:
![image](https://github.com/cgeo/cgeo/assets/1258173/e8125d52-20ab-404c-9434-8cceef48a29c)
