### ISSUE TITLE
"Recommend" OC caches no longer possible

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15387]
We have users for Opencaching (seemingly both OC.PL) that claim "recommending a cache" (= equivalent to GCC's giving a favorite point) is no longer possible for OC caches. One user is using the 2024.01.24 RC version, the other one I would need to ask.

Could it be that this functionality got lost when reworking the log (log edit) feature?

tickets 863114, 659930

**Comment by eddiemuc** [comment]
Are we talking about adding a recommendation when writing a FOUND log?

**Comment by moving-bits** [comment]
Here is a screenshot from one of the users, apparently from an older version of c:geo:

![image](https://github.com/cgeo/cgeo/assets/3754370/0e94922d-e3e8-4d58-bf83-4dddcbd9c18d)

("znaleziono" translates to "found")

**Comment by eddiemuc** [comment]
Thanks. In look into it as time permits

**Comment by eddiemuc** [comment]
I found a bug which leads to the "recommendation" line no longer being visible:

![image](https://github.com/cgeo/cgeo/assets/6909759/8e6c56ad-d94c-4cce-bf69-65f39880395f)

I fixed this with PR #15405

I assume this is what the user meant when entering the issue?
I can't really test whether a sent recommendation is really applied on opencaching.de, because I fail to grasp how and where the website displays for a cache whether I recommended it or not...

**Comment by moving-bits** [comment]
I've notified both users on support and asked them if they could cross-check. At least one of them was using the beta version (other one unknown to me), so we might get a feedback soon after releasing a new beta.
