### ISSUE TITLE
UnifiedMap: Mapping filtered list loads all caches

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#15414]
There's a design flaw in Unified map that makes it *significantly* less performant than old maps. It seems that UnifiedMap always loads all the caches of a list and only then applies a filter.

To reproduce:
- Load a list with many caches (20k in my case)
- Apply a filter to the list that leaves only a few caches (~50)
- Map the list

Result:
- Old maps: Map is displayed pretty much instantly
- Unified map: Before https://github.com/cgeo/cgeo/pull/15395 there was a ANR, now the map just sits there for ages, c:geo is unresponsive. After a very long time caches will show up on the map but any further actions have very bad performance.

**Comment by moving-bits** [comment]
This is due to the different way old maps and UnifiedMap handle mapping cache lists:
- The old maps did not have a concept of cache lists. On mapping a (filtered) cache list, they just got a bundle of caches and displayed them. This could lead to buffer overruns on large lists, and also it did not support switching between lists.
- UnifiedMap works different: On mapping a cache list, it just sends the list id and the appropriate filter context. Loading and filtering caches is applied by UnifiedMap. This allows for switching lists and for a fast transfer of larger sets, but has the observed side-effects on loading small subsets of very large lists.

So what you probably would want to have is a mix of both worlds: For small result sets (< 100?) send a prefiltered list of caches along with the list id, and skip filtering by map in that case.

**Comment by ztNFny** [comment]
> So what you probably would want to have is a mix of both worlds: For small result sets (< 100?) send a prefiltered list of caches along with the list id, and skip filtering by map in that case.

That seems like an ugly workaround.

Imho the real question is: Why is loading (not displaying!) many caches on unified map so slow? 
Loading the list in listview and filtering it is very fast, so it seems UnifiedMap is doing a lot more than the listview with the cache data - stuff that doesn't need to be done, at least not for this specific case (which isn't too exotic I guess)
