### ISSUE TITLE
UnifiedMap: Switching from OSM to Google jumps to coords 0,0 first

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#15496]
When switching from OSM to Google (in my case it's usually Google Satellite) the map displays the desert (I presume this is coords 0,0) for a moment before the map jumps to the correct location.

I guess this is because viewport is set daleyed after loading caches. When switching between maps the viewport should initially be set to the old one.

**Comment by moving-bits** [comment]
I guess this comes from this code fragment:
```
if (mapState != null) {
    ActivityMixin.postDelayed(() -> {
        mapFragment.setCenter(mapState.center);
        mapFragment.setZoom(mapState.zoomLevel);
    }, 1000);
}
```

This got introduced some time ago to preserve position/zoom on rotation and not changed since then.
BUT: To be honest, I'm not sure why I used a `postDelayed` with a 1s delay back then. I'll create a PR to remove this delay, so that we can test this in the nightlies for possible side-effects.

**Comment by moving-bits** [comment]
See PR #15507
