### ISSUE TITLE
Strange personal note coordinate parsing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15503]
### Describe your problem!

A user stated, that c:geo automatically generates an unwanted/incorrect waypoint from his personal note.
While analyzing the rather long note I stripped it down to the following reproducible scenario.

Support ticket 414375

### How to reproduce?

- Open a cache in c:geo
- Enter `48.816 34.147` into the personal note
- Store the personal note 

### Actual result after these steps?

c:geo creates a waypoint from the personal note with coordinates `N48° 48.960 E034° 00.527`

### Expected result after these steps?

Probably nothing should be parsed as valid coordinate from that input string. 

### Reproducible

Yes

### c:geo Version

2024.03.19

**Comment by eddiemuc** [comment]
Reproducavle, removing "unverified"

C:geo parses `48.816 34.147` simply as decimal lat/lon coordinate. `N48° 48.960 E034° 00.527` is just the `DD MM.MMM` formatted version of this.

I would not see this as a bug since c:geo can parse decimal lat/lon for a long time now. We can discuss if this feature should be removed of course.

**Comment by eddiemuc** [comment]
Reproducavle, removing "unverified"

C:geo parses `48.816 34.147` simply as decimal lat/lon coordinate. `N48° 48.960 E034° 00.527` is just the `DD MM.MMM` formatted version of this.

I would not see this as a bug since c:geo can parse decimal lat/lon for a long time now. We can discuss if this feature should be removed of course.

![Screenshot_2024-03-23-11-38-21-31_a916ceb0c8a82619faeb76fe6b8ae997.jpg](https://github.com/cgeo/cgeo/assets/6909759/275674c3-898d-456f-b084-d663943e1617)

![Screenshot_2024-03-23-11-38-37-27_a916ceb0c8a82619faeb76fe6b8ae997.jpg](https://github.com/cgeo/cgeo/assets/6909759/a0c93762-662e-4349-8f5d-ad3256d2afb8)

**Comment by Lineflyer** [comment]
Ah, did not come to the idea it could be Decimal Degrees.
IMHO its not a bug then.
If those coords were meant as MinDec coordinates, they are simply invalid.

So lets close here and I provide feedback to the user.
