### ISSUE TITLE
Users missing the stars for D/T on the map sheet

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15505]
I discussed with a bunch of users, which are a bit disappointed regarding the change from popup to bottom sheet.
While at first they claimed a smaller font (which turned out not to be the case) later it turned out, what they were really missing is the better readability of D/T represented by stars.

Some users now instead use the D/T-icons on the map, but its still not the same for them.

I have to somewhat agree, that it easier/faster to recognize D- and T-values if they are presented graphically. 
Not sure if we want and can find a solution which is more graphical for D/T but still compact for the bottom sheet.

**Comment by moving-bits** [comment]
How about putting it in the same line, eg: `D 5.0 ***** (separator) T 2.0 **`
This would keep it compact, and if the screen is too small, the textual "T 2.0" should still be visible. (to be tested)

**Comment by ztNFny** [comment]
> How about putting it in the same line, eg: `D 5.0 ***** (separator) T 2.0 **` This would keep it compact, and if the screen is too small, the textual "T 2.0" should still be visible. (to be tested)

how about "D 5.0 / T 2.0 - ***** / **"? That way it's easier to handle overflow and it also ensures that texts are always in the same position (where the user expects them to be).

Or maybe show the marker in line with the rating instead of the stars?

My personal vote would be for not re-adding the stars, I also removed them in DetailsActivity in my builds - but I have my own builds, so I don't have any strong opinion on this ;-)

**Comment by bekuno** [comment]
Instrad to use stars I propose to use a colored background in the colors already used for the cache D/T info, eg.
![grafik](https://github.com/cgeo/cgeo/assets/32555742/cb288ddd-f5e3-46a7-97ec-9ee5ffcea477)
Perhaps we could use only part of it instead of the full colouring, analogous to the circle representation. But then we have to be aware of the theme colour.

**Comment by Lineflyer** [comment]
> Instead to use stars I propose to use a colored background in the colors already used for the cache D/T info, eg.

Sounds like a good space saving ideas and would allow to visualize D/T at first sight.
Only the styling needs to be well done to be readable on white/black theme (as you said).

**Comment by ztNFny** [comment]
A quick stab at adding the circle marker to popup:
![image](https://github.com/cgeo/cgeo/assets/1258173/156650a8-05bd-4c8e-af9c-0d200960a352)

**Comment by MagpieFourtyTwo** [comment]
If you are considering coloring, please keep in mind that nearly 10 in 100 men are colorblind or have at least a color vision deficiency, which makes it at least pretty hard to distinguish esp. between green, brown and red. 

With the map's D/T icons that's no big deal, cause there is additionally the different "fill level", but with completely filled rectangles, which just differ in color, they will gain nothing.

Therefore I would suggest a similar solution like with the 5+5 stars, which are either filled or just outlined. And if stars are not possible for whatever reason (what about [UTF-8](https://dev.to/link2twenty/star-rating-using-unicode-stars-3np2)?), then maybe just 5+5 squares, either full, half, or not at all filled.

**Comment by MagpieFourtyTwo** [comment]
What about forcing the font for this string?

**Comment by MagpieFourtyTwo** [comment]
> we should stay with our icons for now.

Thought these are not possible in the bottom sheeet ... \*wonder*
If I misunderstood, so why not just do it the same way it is in the listing's detail page?

**Comment by moving-bits** [comment]
> so why not just do it the same way it is in the listing's detail page?

this would consume two lines of precious space, for an information that's already there, though just in textual form

I played a bit with putting D/T stars into a single line:

![image](https://github.com/cgeo/cgeo/assets/3754370/ff9b00c4-3f5e-4b3c-938b-502da6ae1de5)

But this probably wraps on most devices (smaller screen and/or larger fonts), then taking up same space as on cache details page, but being less readable in that case:

![image](https://github.com/cgeo/cgeo/assets/3754370/b42d2c24-c697-40f2-884d-2b66df855149)

(Sure, one could make wrap the text together with its accompanying rating stars, but it still consumes too much space then, IMHO.)

Thus I would say, pursue one of the following variants:
- Leave it as is (text only on cache info sheet)
- Use colored boxes, as suggested in https://github.com/cgeo/cgeo/issues/15505#issuecomment-2016784459 (but stay away from colors not distinguishable for color-blind people)
- Use D/T marker from map, as suggested in #15518, but slightly increase it in size for better readability (but stay within a single line, not increasing line spacing)

**Comment by ztNFny** [comment]
My vote goes to circle marker. Small but has all the info at a glance, it's a familiar element and compatible with colour blind.

**Comment by MagpieFourtyTwo** [comment]
I don't really agree that space is such an issue for the bottom sheet, IMO there's plenty of map room left above it, so one line more or less should not be a big problem. And although I admittedly don't know how the bottom sheet behaves on smaller displays (6.8" over here, but are there really still displays out there with less than, let's say 4"?), thus there should always be enough space above the bottom sheet to click in the map (in order to close the bottom sheet again). And for much more than that even I don't use the map space above it - and over here the map space is even bigger than the space the bottom sheet occupies right now.

Thus I still favor the two-lines-with-text-plus-stars solution for three reasons:
1. info can easily be seen and understood, even at a glance
2. users are used to it from the listing page
3. their reaction seems to show that they really *want* these stars, so why not?  ;)

But if the general opinion is that space is nonetheless a problem, then I would also opt for the circle marking.
Because both, values and stars, in one line are even more difficult to read than just the plain values.
