### ISSUE TITLE
Incorrect zoom level when mapping filtered subset of list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15500]
### Describe your problem!

If you have a larger list of caches, then use the filter to only show a subset, opening the map for that filtered list will still set the zoom level to cover all caches (also the ones filtered out).

### How to reproduce?

- Have a list of caches spread over a rather large area (e.g. whole Germany).
- Filter the list in a way, that only caches within a small area are shown on the list (e.g. Filter one cache by its name)
- Map the resulting filtered list

### Actual result after these steps?

The unified map openes with a zoom level set to cover all caches of the list

### Expected result after these steps?

Zoom level should be fitted to the filtered list instead.

Comment:
Working on old map, problem only on unifed map

### Reproducible

Yes

### c:geo Version

2024.03.19

**Comment by moving-bits** [comment]
Have tested with current state of `release` (which should be equivalent to 2024.03.19):
- have a list with caches in two countries
- map this list

=> map zooms out to show both countries

- go back to the list and filter it in a way that only a single cache is shown (in my case by setting a filter to cache type "adventure lab")
- map this list

=> map zooms in to show only this cache

So works in my test case. I would have expected the described behavior before PR #15454, but no longer after it, as the viewport gets set from the search result since then, and if the filter is already applied before returning the search result, there should be no filtered-out cache in the result anymore.

Are you sure that there is no far away waypoint for one of the included caches?

**Comment by Lineflyer** [comment]
> So works in my test case. I would have expected the described behavior before PR https://github.com/cgeo/cgeo/pull/15454, but no longer after it,

Indeed I made a mistaken reporting the problem.
I used my second device, which was still on 2024.03.12-NB not 2024.03.19-NB.

With the latest nightly the bug is gone.
