### ISSUE TITLE
Search results for a location no longer sorted by distance to target location 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#15618]
### Discussed in https://github.com/cgeo/cgeo/discussions/15616

<div type='discussions-op-text'>

<sup>Originally posted by **Lineflyer** April 16, 2024</sup>
We got a ticket on support, claiming that sorting a location search result by distance to that location does **no longer** work but the results are shown with distance to your current position.
</div>

<br>

We indeed had that feature (PR #11691) so this is clearly a regression and should be fixed.

**Comment by murggel** [comment]
@fm-sys  do you remember, was only the distance to target used for sorting or also for display?

I am not sure whether we should show also the distance and direction to target instead to current position in the list view....

**Comment by fm-sys** [comment]
> @fm-sys do you remember, was only the distance to target used for sorting or also for display?
> 
> I am not sure whether we should show also the distance and direction to target instead to current position in the list view....

It was only the sorting back then. The distance indicator had still displayed the distance to your current location, IIRC.

**Comment by murggel** [comment]
Would it be ok to show in that case the distance and direction to the target coords instead of to the current location?

What distance-value does the user expects? The one to the searched location or to the current location? 
I would prefer the distance to the target coords, because that is the interesting value for me, not the distance from my current location and it would make the sorting distance "visible".
