### ISSUE TITLE
Show date for events in the cache-select pop-up instead of D/T

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#15704]
### Tell us your idea!

I was looking for some geocaching events recently and realized it's quite impossible to quickly see *when* the events are taking place. Sure you can click to see details, but when there are dozens, it would be way more convenient to see the date instantly.

I'd say both geocode and DT ratings are useless there, especially for events. Would be great to have the date there instead.

See screenshot:

![Screenshot_20240507-103616](https://github.com/cgeo/cgeo/assets/918446/8dff495c-a80e-4cc0-8cad-1151d391495f)

**Comment by ztNFny** [comment]
I like the idea of showing the date - what I don't like is hiding the T-rating as that can still differ (apparently not in Houston though 🤣).

Proposal 1: Add date as third item in the line
Proposal 2: For GC events only hide the D-rating as it's hardcoded to 1 (at least for the last few years, we can probably safely ignore old events). Disadvantage: GC events will look different than non-GC events and caches, making the list harder to read.

**Comment by MagpieFourtyTwo** [comment]
+1 for P1 

Although ...
1) I have never ever seen *that* many events before, with (nearly) the same coordinates, resulting in such a long select list,
    thus I guess most of the people will never ever see this list anyway, but will immediately get the bottom sheet instead,
    which already contains the date.
2) it is nevertheless pretty easy to get the event dates:
    Simply use ``Show as list`` and there they are (if you configured your list info lines accordingly ;) ).

That said, I wouldn't even remove the D-rating because a) fixed D1 appears to be a (pretty arbitrary) specialty of gc.com that can change back again at any time without notice, as was the case in 2018 (IIRC), b) it would make the list look inconsistent if there are events from other services, too, and c) for these services this wouldn't solve the potential "space problem" either.

**Comment by okainov** [comment]
I see more than one event (causing the list to be shown like on the screenshot) quite often. It might be either multiple events, or event next to the cache, or events next to some big events (a couple of meetups before/after some MEGA event or GIFF)

I mean, my proposal is to see dates :) How exactly - feel free to discuss. I said DT because I personally couldn't care less about them (also for regular caches). Sometimes I see some D5 caches requiring special equipment, but this happens way more seldom than I see events, honestly. However I understand it might be important for someone, so whatever, if you think it worth keeping for events - no problem :) As you see from my screenshot, there is even space for just some extra info, so it can be even just added in addition.

The date might be also part of the name, not sure how good idea is that, like `[11.05] Wonderful geo-event name`

>Simply use Show as list and there they are (if you configured your list info lines accordingly ;) ).

When I'm zoomed out across multiple cities it doesn't really work that well. Also when I have not set event-only filter and there are many other caches around...

**Comment by MagpieFourtyTwo** [comment]
> When I'm zoomed out across multiple cities it doesn't really work that well.

Maybe - but, TBH, how common is this? Or do you prefer to do event hopping?  ;)
However, displaying the date even in the select list should not be a real problem, so why not.

> Also when I have not set event-only filter and there are many other caches around...

Just create a saved filter like ``type:Event`` and you're there with only two clicks.  ;)
BTW: You have to do so anyway, cause otherwise you will see these "many other caches" in the select popup, too.
So, in fact, the ``Show as list`` will show exactly what you see in the select list popup.  Check.  ;)
