### ISSUE TITLE
Clean up Unified Map control element locations

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#15762]
### Tell us your idea!

![2024-06-04 11 46 34](https://github.com/cgeo/cgeo/assets/54892606/44a4ff53-7e54-4dec-a88e-c554c89c1e6f)

In the top left corner, the "filter bar" covers up the compass (and the "unified map badge", but I assume that is soon disappearing anyway).

The button in the bottom center would be nicer if they were in line with the zoom buttons to make one clean line of control buttons.

**Comment by moving-bits** [comment]
The two quick settings buttons have been placed at the bottom of the map for a reason, as today's typical displays have much more vertical space than horizontal space (in portrait mode, at least, which is why those two buttons get placed at the left when switching to landscape mode). I'd vote for "leave as is" in this case.

Placing of compass rose needs to be fixed, though.

**Comment by dcjkfgdjhd** [comment]
In this case, maybe the +/- buttons could be moved to the bottom as well. Maybe as one horizontal line at the bottom and aligned to the right hand screen side.

**Comment by murggel** [comment]
For me the current layout of the 4 buttons is optimal for the one-hand-accessibility. If all buttons would be in one row, I guess, I will hit most of the time the wrong one 😞 
So I'd vote for "leave as is"

**Comment by moving-bits** [comment]
Positioning of compass rose got fixed meanwhile, and replacing the quick settings buttons got voted against, so let's close here for now.
