### ISSUE TITLE
Default trackable status isn't being respected

### ISSUE THREAD

**Issue by B2Pi** [cgeo/cgeo#15817]
### Describe your problem!

TBs are not 'visited' when logging

### How to reproduce?

1. From main Home Screen
    1. Select Menu
    2. Settings
    3. Logging
1. Ensure check box next to 'Visit TBs' is click on

### Actual result after these steps?

TBs are not logged as visited

### Expected result after these steps?

TBs should be logged as visited

### Reproducible

Yes

### c:geo Version

2024.06.02

**Comment by Lineflyer** [comment]
I happen to have logged many caches on the last weekend using nightly builds and all my TBs visited correctly.

Question:

> Ensure check box next to 'Visit TBs' is click on

What click box are you reffering to?
AFAIK it should be a dropdown selection where you select the option "Visit" for each TB.

**Comment by Lineflyer** [comment]
I have to correct myself.
Now I know which click box you are referring to as you explained initially.

When you finally actually log a cache:
What is shown for the respective trackables in your logging view (scroll down below the log text field).

If you carry trackables in your inventory which have previously been set to "Not visited" c:geo might (despite the setting you changed) still remember this as your preference for certain trackables and the setting will only be applied to trackable coming into your inventory at a later point of time.
If my assumption is correct, you just need to set those trackables already existing in your inventory to "Visited" manually once.

**Comment by eddiemuc** [comment]
Since we introduced that we remember last log action for each inventory trackable individually, users might get confused on what the setting "visit TBs" really means.

The setting means: if a cache log is created and the trackable is in the inventory for the first time, then the serting determines whether it is set to "visible" or "do nothing". After first log is created, c:geo stores an individual last action for the trackable, the setting is then no longer relevant for determining the default state of the trackable.

Should we maybe remove the setting? It's value is rather limited these days.

**Comment by B2Pi** [comment]
Forgive the delay in responding. One of the difficulties of the android meta-architecture is that there is no documentation. I had no idea that trackable logging had changed.

Now that I understand, I suppose that this issue can be closed, but

1. Yes, I would get rid of the setting that confused me
2. It might be nice to have a setup where, say, default trackable status is visited for finds, and nothing for DNF's or notes. However, that can't even be considered a suggestion for a feature, as I can't spec it any better than that.
