### ISSUE TITLE
Allow correction of GPS elevation info by constant value via user setting 

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15838]
From support ticket 841205:

A user notified us that the GPS elevation shown by c:geo is always a nearly constant value too high (in his case around 45m). He asks for a setting to enter manually a constant correction factor for displayed elevation information. An app providing such a setting is eg GPS Info.

**Comment by SammysHP** [comment]
Where does the height come from? Which datum is used for its calculation?

**Comment by eddiemuc** [comment]
> Where does the height come from? Which datum is used for its calculation?

GPS elevation

**Comment by SammysHP** [comment]
> GPS elevation

Which is not enough to describe the elevation. It needs a geodetic datum with a reference ellipsoid. Otherwise it can deviate from other values given with another datum. We also have to take into account the actual MSL or MSL over the geoid or ellipsoid used in our datum (probably some version of WGS84).

**Comment by eddiemuc** [comment]
> > GPS elevation
> 
> Which is not enough to describe the elevation. It needs a geodetic datum with a reference. Otherwise it can deviate from other values given with another datum. We also have to take into account the actual MSL or MSL over the geoid or ellipsoid used in our datum (probably some version of WGS84).

This is all correct, but as far as I understand goes way beyond the user's request. My understanding is that he simply wants to configure a constant value which is then added to the elevation info displayed today.

**Comment by devemux86** [comment]
From Android 14 there is [Location.getMslAltitudeMeters](https://developer.android.com/reference/android/location/Location#getMslAltitudeMeters()).

**Comment by rhodo-dendron** [comment]
Probably use Location.getMslAltitudeMeters() instead of whatever you are using now. And please always display heights in Meters, never in Kilometers. No decimals required as far as I'm concerned.

**Comment by SonnyLidarDTM** [comment]
Using _Location.getMslAltitudeMeters()_ is a good idea.
If this is not possible due to older Android versions, there are public Geoid-correction tables, which add/substract a certain value of the WGS84-altitude (got with the phone's GPS receiver) deping on a certain coordinate  to finally calculate the altitude about sea-level at this coordinate.

There's also an API to check correction values, where "EGM2008" is the latest correction table: 
https://geographiclib.sourceforge.io/cgi-bin/GeoidEval

On the other hand correcting the WGS84-value by constant value like suggested here is better than do nothing, but not as ideal as correcting by Geoid-tables. Since the correction value is not a constant but depends on location's coordinates.

**Comment by fm-sys** [comment]
IMHO it's fine to fix that issue for Android >=14 only (in a first implementation). That would reduce the feature request from a whole evening task to a 5-10 minute thing. 

Way better than nothing, and as time passes by, more and more users will be able to get the correct altitude :)

https://developer.android.com/reference/android/location/altitude/AltitudeConverter

**Comment by ztNFny** [comment]
> Every fricking GPS Status app can do this correctly since the beginning of time. How hard can it be to fix it here? Anyway, please do not require internet access for GPS height.

Please go ahead and submit a PR to implement it.

**Comment by moving-bits** [comment]
PR #15898 implements using MSL altitude for Android 14+ devices (if info is available), thus I propose to close this issue.
