### ISSUE TITLE
Solid black (optional) for background

### ISSUE THREAD

**Issue by Korb** [cgeo/cgeo#15864]
### Tell us your idea!

 c:geo currently uses the non-black color `#141414` as its dark theme background. Here's how application developers argue for using `#000` as a background color:

Google Android 14:

> Dark Theme Screen / On some screens, Dark theme will use a solid black background which will help extend your battery life. After scheduling, Dark theme will be enabled when your screen is off.

Catima:

> Pure black background for dark theme (reduces battery usage on OLED displays).

F-Droid:

> Use pure black background in dark theme. Recommended only for OLED screens.

Upd. In addition, the more contrasting the color of the text and background, the more readable the text is outdoors in good weather (if the screen is not bright enough). And vice versa, the easier it is to read in the dark, when any background fill is blinding.

**Comment by moving-bits** [comment]
This is the visual difference between #141414 and #000000:

|#141414|#000000|
|---|---|
|![Screenshot_1721576243](https://github.com/user-attachments/assets/5a8411a0-7a8c-4377-a7fa-ae66d6f6274b)|![Screenshot_1721576214](https://github.com/user-attachments/assets/6880df30-a6e4-417c-8e4e-41e38fee5cb1)|

(separator lines would need some update to be visible enough again in the black version)

**Comment by SammysHP** [comment]
As a side note I recently discovered that even the Google apps (like Gmail, Notes, Wallet etc.) don't use a pure black background, but some color derived from the wallpaper (["Material You"](https://source.android.com/docs/core/display/material)).

**Comment by Korb** [comment]
> As a side note I recently discovered that even the Google apps (like Gmail, Notes, Wallet etc.) don't use a pure black background

Google doesn't stick to one standard dark color theme in its apps. In most cases it uses `#121317`: Calendar, Contacts, Digital Wellbeing, Docs, Drive, GMail, Keep, Sheets, Slides, and Translate. But in some cases, Google uses `#0d0d0d` (Home), `#181c1f` (Phone) and `#131313` (Play).

**Comment by SammysHP** [comment]
When I change my wallpaper, these colors change as well.

**Comment by moving-bits** [comment]
PR #15928 set background color to solid black in dark mode.
Reason for strange divider color in screenshot above is found as well: Cache list view did not set c:geo's divider color, so it was using the built-in one. The PR fixes this as well.

**Comment by Lineflyer** [comment]
Wasn't is the case - back in the days where we finetuned the new themes - that we explicitly refrained from using pure black. I don't remember the reason though...maybe because of the high contrast? 
Anyway I am no theme expert....we can try how black looks in daily use.

Also I cannot imagine that power consumption on OLED makes a big difference for normal c:geo usecases (except mabye people constantly using lists and reading cache listings on a big display device/tablet.

**Comment by SammysHP** [comment]
We should prefer to use the system's dark theme / material you to be more consistent with other apps.

**Comment by fm-sys** [comment]
> > We should prefer to use the system's dark theme
> 
> Is that something we can make use of?

Yes, but only when using material  3 #14570

**Comment by moving-bits** [comment]
We've made some experiences with Material 3 in the past (and reverted at some point of our implementation). If I remember correctly, the changes included into Material 3 fall into one of three categories:
- Some changes for accessibility reasons (like larger touch areas)
- Many changes, which are mostly a matter of taste, like roundish buttons, new color scheme etc.
- as well as more technical changes like changed / new / removed components.

Probably the most promoted part back at that time (at least as I remember it) was the "Material You" part: Apps' colors adjust to the background image you have installed on your device.

_personal opinion on_
Material 3 may be discussed (but is no prerequisite for this issue), BUT: Please skip Material You!
Why should anyone want to have their apps change colors just because of a different background image?
And, even more importantly: Why should any app provider (like us) want to have their carefully chosen brand / app colors change on the users' devices just because of their fancy background image?
To me it looks like something having been implemented "because we can" (or because of having too many developers at their hands). Google's design decisions are strange, sometimes, and consistency is not one of their strengths, IMHO.
_personal opinion off_

Having said that, a solid black background is a pretty common choice for OLED/AMOLED devices and can be implemented with a single line change.

**Comment by fm-sys** [comment]
> Why should anyone want to have their apps change colors just because of a different background image?


I'm using stock android on a Google Pixel. And honestly, I love the idea that I can set the color of system components based on my background image or a manually choosen color I like. The fact that quick tiles, volume slider, and my third party keyboard app use the same color scheme looks just awesome. 

I definitely don't want the keyboard app forcing their branding. And it's pretty cool that calculator, telephone app, and clock all use the same color based on the preference I can specify. Material you is an excellent design concept for apps which don't want or should not have their own branding. 

**However all of this doesn't fit to c:geo. c:geo _is_ a brand and ever will be.**

**Comment by SammysHP** [comment]
There are apps like [LWP+](https://play.google.com/store/apps/details?id=com.lb.lwp_plus) that allow you to change the colors used by Material You. Basically it is implemented as a live wallpaper, which can use functions to set the accent colors (because otherwise it would be hard to get these colors from a dynamic wallpaper).

**Comment by Lineflyer** [comment]
> And, even more importantly: Why should any app provider (like us) want to have their carefully chosen brand / app colors change on the users' devices just because of their fancy background image?

I agree on that.
Based stay with "our brand" and just decide whether we want full black in dark mode or stay with our slight grey.

**Comment by moving-bits** [comment]
The proposed change is for technical reasons (power saving), the visual difference is pretty small, see https://github.com/cgeo/cgeo/issues/15864#issuecomment-2241687804, and PR #15928 also fixes the divider color (which is actually unrelated to changing the background color but an already existing bug which only becomes more visible with a solid black background).
