### ISSUE TITLE
UnifiedMap: Make Mapsforge default, VTM "on demand"

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#16214]
As discussed in today's dev meeting:

- swap defaults: make Mapsforge the default for UnifiedMap and VTM only visible "on demand"
- check for missing Mapsforge map types (eg: combined map?)

**Comment by fm-sys** [comment]
Features (potentially) missing in Mapsforge: 7ffd55603277dde31d800a877e5f063d56f693a3 6b43cbbfa02d4e35400f31b720b5367dcebb29c2 acbe6d610e78aac721163699e1f1638e6946e623 2343b705fd7b79e3793c2534b5f33accaa15bc05

**Comment by ztNFny** [comment]
During my tests of Unified Mapsforge I've experienced it to be very slow in comparison to both old Mapsforge and VTM. In fact in emulator it never successfully loaded Germany (OAM) whereas the other 2 implementations have no issue with that.

**Comment by MagpieFourtyTwo** [comment]
With Map Source set to Mapsforge, "Combined (offline)" got lost from the map selection drop down in map view this morning, most probably after updating to latest Nightly - why that?

In System Setting "Map Sources" => "Hide Map Sources" it was still present (when Source is set to Mapsforge), but (of course) not ticked - but after a serving restart of c:geo it disappeared over there, too.

If I change Map Source to VTM, everything is fine, it appears in the drop down, and in the list of "Hide Map Sources" (although the latter requires a restart of c:geo, otherwise it will not show up in hideable sources).

Has "Combined (offline)" been removed on purpose for Mapsforge or just accidentally? (I hope it's the later, cause this would be a real showstopper for us)

**Comment by ztNFny** [comment]
> Has "Combined (offline)" been removed on purpose for Mapsforge or just accidentally? (I hope it's the later, cause this would be a real showstopper for us)

https://github.com/cgeo/cgeo/pull/16235

**Comment by MagpieFourtyTwo** [comment]
Aaah - thx for the hint!
