### ISSUE TITLE
Wherigo Player: Buttons / Info suggestions

### ISSUE THREAD

**Issue by rouroni1** [cgeo/cgeo#16266]
### Tell us your idea!

1. The new "pause" solution takes to much space in the Input Menu's of the cartridges. Before there where no title "Wherigo Player" and no aditional button. Both of them take at least 10 to 15% of the screen.

2. The info button should be on the top, next to the cartridge name

3. Cartridge info (after pressing the info button) shoundn't have the options "Play" and "Delete", only "Close"

### What solution would you suggest?

1. Input's Suggestion
![InputSugestion](https://github.com/user-attachments/assets/8873de05-b20c-4442-8eb0-ac444bcc3b59)

2. Info button Suggestion
![InfoButtonSugestion](https://github.com/user-attachments/assets/315b3a56-15bf-419c-a8f2-5e634999e899)

3. Info Menu Suggestion
![InfoButtonCartridge](https://github.com/user-attachments/assets/07ecd973-e7b4-493c-9126-7641471c605e)

**Comment by eddiemuc** [comment]
>Before there where no title "Wherigo Player"

This was added as a result of the discussion in [#16250](https://github.com/cgeo/cgeo/issues/16250). It was asked that Wherigo Screens all either "look like dialogs" (means: no fullscreen, background color of dialogs eg darkgray in "dark mode") or "look like activities" (means: full screen, background color of activities eg black in "dark mode", action-bar-like header) but nothing inbetween. 
First draft was to make them look like activities which requires an action bar with some content. The discussion though whether wherigo screens shall look like dialogs or activities is still open. Once it is resolved I will implement the decision for all wherigo screens. But also dialogs in c:geo usually have a header/title.

**Comment by fm-sys** [comment]
My two cents: The pause button should be replaced by a back button inside the action bar.

**Comment by eddiemuc** [comment]
> My two cents: The pause button should be replaced by a back button inside the action bar. 

This would give the wrong impression that such Dialogs can be cancelled like "normal" dialogs. In case of wherigo, a dialog can be temporarily "abandoned" (paused), but the user actively has to re-open it then later - otherwise the wherigo game may behave weirdly and will to some degree stop working (depends on how cartridge is programmed)

**Comment by fm-sys** [comment]
> This would give the wrong impression that such Dialogs can be cancelled like "normal" dialogs. In case of wherigo, a dialog can be temporarily "abandoned" (paused), but the user actively has to re-open it then later - otherwise the wherigo game may behave weirdly and will to some degree stop working (depends on how cartridge is programmed)

Totally get your point, however, a pause button IMHO doesn't do any better. It's not really clear to the user what gets paused and what's the effect of it. Additionally "canceling" via the device back key/gesture does "seem" to work as well which gives an inconsistent look and feel.

Most importantly, an actionbar without back button implies that it's a top-level activity and back would leave c:geo which simply isn't the case here.

Thus I would suggest adding the back indicator to the actionbar and when pressing that button or back key, better show a dialog like "This will pause the cardridge. Continue?"

**Comment by eddiemuc** [comment]
> Thus I would suggest adding the back indicator to the actionbar and when pressing that button or back key, maybe show a confirmation dialog...

To be honest having a visual back button in the wherigo screens feels super-weird in general. I get your point that an activity-like screen should have one, but this doesn't fit the wherigo flow at all. If this is mandatory, then maybe this is the tipping point for making all wherigo screens Dialog-like. Though I dislike wasting so much space because dialogs have to be smaller than full-screen. 

I checked with WhereYouGo. They "solve" the problem by not letting the user escape an input dialog (no "back" or "cancel" button, using system "back" button is handled as if user made an empty input). You have no chance to even stop/restart a game other than killing the app. That would be the "easy way out" in terms of implementation, but I don't like it.

I like your idea with the confirmation dialog though. Maybe just name the button "cancel" (not "pause"), then show a dialog "screen was paused, resume on wherigo activity"

**Comment by fm-sys** [comment]
> Maybe just name the button "cancel" (not "pause")

It still stays a non common UI component for a common action, which is always a bad idea.

**Comment by eddiemuc** [comment]
Fixed with PR #16273, including "back arrows" in Action Bar as requested
