### ISSUE TITLE
Wherigo: Optimize Bug-Info

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#16321]
### Tell us your idea!

Corrently the WIG-Buginfo lokks like
![grafik](https://github.com/user-attachments/assets/bd63baa6-d6de-4ffd-b9b8-b5a40c674a4e)

The text and shown address reference is outdated.

### What solution would you suggest?

I suggest to change to something like "Error in the c:geo WIG engine. PLease report it to the developer at github or by mail."

**Comment by eddiemuc** [comment]
I reworked the dialog as part of PR #16322. Is this more what you would expect?
![image](https://github.com/user-attachments/assets/0b084c34-38c9-4711-8a9a-6df0ff48802c)

**Comment by bekuno** [comment]
Yes, but 
- without "OpenWIG error:" 
   We are in the c:geo codebase, not openWIG. 
- without "stack trace" part:
  The user can report directly per mail (with the stack trace, I assume), so stack trace here is not necessary
![grafik](https://github.com/user-attachments/assets/fdb4f532-4da3-4b49-b093-02aced78a6f7)

**Comment by eddiemuc** [comment]
> Yes, but 
> - without "OpenWIG error:" 
>    We are in the c:geo codebase, not openWIG. 
> - without "stack trace" part:
>   The user can report directly per mail (with the stack trace, I assume), so stack trace here is not necessary
> ![grafik](https://github.com/user-attachments/assets/fdb4f532-4da3-4b49-b093-02aced78a6f7)

What is displayed here is an error string.as it is reported directly from the OpenWIG engine used underneath. It's not an exception where we can decide on how to display it, it is really a string. apparently OpenWIG decides to put such information into strings to display to a user. There is really nothing else (or more user friendly) available here :-(

The only thing I am currently doing to the OpenWIG output is removing the prefix "you hit a bug. Please report it at xy and I will fix it for you" (yes, that's also coming as part of the string out of the engine for user display....) because this seemed totally misleading to me.

If I remove the exception as well then I can only display something like "OpenWIG engine reported an error" w/o any more information. There is really none unfortunately.

**Comment by eddiemuc** [comment]
For comparison: here is how WhereYouGo displays the very same error:

![Screenshot_2024-11-03-22-22-43-39_ee809e1ac73fae7cd6c0f967c7bcbd23.jpg](https://github.com/user-attachments/assets/6b8eda5a-3d70-4a4c-888e-2537460bfb70)

 WhereYouGo just copies the string error message given by OpenWIG 1:1 into a dialog, without adding anything before or after. The complete text you see in the dialog comes as one string in OpenWIGs `showError` routine. Implementation instruction on the interface is to show such error to end user.

Should we copy this behavior to c:geo

**Comment by eddiemuc** [comment]
For comparison: here is how WhereYouGo displays the very same error:

![Screenshot_2024-11-03-22-22-43-39_ee809e1ac73fae7cd6c0f967c7bcbd23.jpg](https://github.com/user-attachments/assets/6b8eda5a-3d70-4a4c-888e-2537460bfb70)

 WhereYouGo just copies the string error message given by OpenWIG 1:1 into a dialog, without adding anything before or after. The complete text you see in the dialog comes as one string in OpenWIGs `showError` routine. Implementation instruction on the interface is to show such error to end user.

Should we copy this behavior to c:geo?

Update: I tried out Er another player (Geeoh Go). The have an interesting approach: they simply don't show the error to the end user at all. Should we maybe do that?
(The error is still happening, because it makes the music stop playing in this player just like in the others).

**Comment by bekuno** [comment]
Do we get the error via Google app store developer console?
If yes, then we do not need the report from the user.
Maybe show such a message in debug mode or so.

**Comment by fm-sys** [comment]
Stack traces are only tracked at Google play if the whole app crashes, which is not the case if we catch the exception properly.

**Comment by eddiemuc** [comment]
> Do we get the error via Google app store developer console? If yes, then we do not need the report from the user. Maybe show such a message in debug mode or so.

No.

In order for OpenWIG to work we need to implement the interface `cz.matejcik.openwig.platform.UI`. This contains methods called by the OpenWIG engine whenever it requests that we interact with the user e.g. show a screen or a dialog. Among these methods is also `showError(final String msg)`. That's the one where we get the error message shown above:

![Image](https://github.com/user-attachments/assets/e9ac82cd-48a0-40a7-8323-4faa00cd9a2c)

As can be seen we get a `String` (and not an `Exception` or `Throwable`), and the IF requests us to show it to the user as error message. We can of course ignore this (like Geeoh Go apparently does)

**Comment by eddiemuc** [comment]
Apparently OpenWIG sends us an Exception's `toString()` in this case though

**Comment by bekuno** [comment]
OpenWIG is now a c:geo project.
We can of course edit there.

Beside this, your suggestion sound fine, imho.

**Comment by eddiemuc** [comment]
> OpenWIG is now a c:geo project.
> We can of course edit there.

some version of the OpenWIGs source code is hosted in the cgeo GitHub organization, that's true. 

But much like WhereYouGo it has no active developer community and no regular releases. No one tracks or fixes bugs in it.

I am not sure if it has Unit Test coverage which would be necessary to check if any code change causes regression somewher3. I don't know if it has a regular CI pipeline for normal development. Heck I don't even know how to build the lib :-)

I can't even be sure that the OpenWIG build I use was made from the same source resting in the cgeo repo or if it has differences. (I just copies the build reference from WhereYouGo gradle).

For all of these reasons I wouldn't dare touching any code there :-)
