### ISSUE TITLE
Button "change login settings" next to "manual login" button on main activity (in case of login failure)

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16331]
Since we introduced the "manual login" functionality (which was meant as a last-resort for users with permanent login problems eg due to captcha problem), we receive support tickets from users claiming that they always have to log in manually these days. It turns out that many of them simply have a wrong username/password combination stored in c:geo settings, thus the login fails, thus c:geo displays the "manual login" button and they use this to log in. Users can't easily understand that this type of login can't update their user/password stored in settings, and thus next time they start c:geo the same thing happens again.

My proposal: in case "manual login" is shown, put a second button right next to it saying "change username/pwd stored in c:geo". This one leads to the authorization settings dialog.

Opinions or other suggestions?

**Comment by ztNFny** [comment]
Shouldn't we be able to detect the kind of issue encountered to decide whether to show the Manual button? It should be shown if the login page has the captcha only?

**Comment by moving-bits** [comment]
Slightly off-topic: We should not show the "manual login" button while the login process is still ongoing, but only after having received a login error from gc connector (even better: only after getting a "captcha required", as suggested above)

To come back to the opening question: Instead of a "manual login" button we could show the suggested "change username/password" button, if we have detected a "wrong username/password" error from gc connector.
