### ISSUE TITLE
Add special event filter

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#16376]
User request on Play Store feedback:

User requests to add filters for missing cache types, especially for those more specific event types.
(CCE, Megeevent, Gigaevent, Block Party, APE, GPS Maze)

There had been no real need for this in the past, but with next year's anniversary and its special event types, I guess this request is valid.

If we do not want to pollute the regular cache type filter with those specific event types, we could add a "Cache type (extended)" filter that includes those types.

**Comment by eddiemuc** [comment]
> If we do not want to pollute the regular cache type filter with those specific event types, we could add a "Cache type (extended)" filter that includes those types.

There would be room in top left corner of the cache type filter to add a switch button "Extended" or something similar

**Comment by ztNFny** [comment]
Dup of https://github.com/cgeo/cgeo/issues/11923

**Comment by ztNFny** [comment]
how about just 1 additional entry for "special events" which could cover Mega, Giga, CCE, Block Party, Maze (all of which are covered by event filter right now)? There's so few of them that that should work for 99% of usecases without adding too much clutter to the filter UI.
As we have 2 columns in that cache type filter UI we could also add a "other cache types" box then to cover APE and "other cache types from other platforms that don't match the existing types" (safari?)

**Comment by eddiemuc** [comment]
For reference here is how cache types are "grouped" right now:
* Selecting "Traditional" will also find GCHQ and Project-Ape
* Selecting "Event" will also find GIGA, MEGA, Community-Celebration, GCHQ-Celebration, GPS-Exhibit and Block-Party
* Selecting "Virtual" will also find "locationless"
* Selecting "User-Defined" will also find "Unknown"

We do not have cache type "Maze" in c:geo yet as far as I can see.

I assume CCE is same as "Community-Celebration"? or GCHQ-Celebration?

Also noteworthy: one can select CITO explicitely in c:geo. This decision was only made to have an even number of selectable types (because of the two-column style of selection dialog). This entry could be replaced by a "special event" category as suggested by @ztNFny. That would be a very easy codechange :-)

**Comment by ztNFny** [comment]
See PR ;-)

> We do not have cache type "Maze" in c:geo yet as far as I can see.

Maze = GPS_EXHIBIT
CCE = COMMUN_CELEBRATION

> Also noteworthy: one can select CITO explicitely in c:geo

I like having CITO as a seperate category. They are way more frequent than the other event types.
