### ISSUE TITLE
Provide calculator in edit waypoint activity

### ISSUE THREAD

**Issue by triakcz** [cgeo/cgeo#2038]
Hi,

when solving multis, it is sometimes to needed to calculate coordinates, so I put cgeo into background, launch calculator, then remember counted number and then open cgeo back ... I'm proposing special button ... which will launch calculator (if it is possible to do it this way, I will check). And after pressing OK there, It could return number back to cgeo focused field.

**Comment by Hadatko** [comment]
Hi,
how its going with this feature? I saw many issues related to this but i am not sure if is any progress on it. If not, i could do it for us ;)

**Comment by SammysHP** [comment]
There are calculators that can be put on top of an app, e.g. the one in Cyanogenmod.

**Comment by Hadatko** [comment]
I was thinking about the MultiSolver thing.

**Comment by S-Bartfast** [comment]
Hello, I have used c:geo for many years but am just now getting into Android programming and have been thinking about this feature a lot.  As an exercise I decided to start working to a design to do exactly this.  I have no idea if I will be able to produce anything of value to the community at large but I thought I would let you all know I am at least having a go at things here.

At present I am thinking to add an extra button to the Coordinate Input Dialogue which will open a new dialogue with simple tools for calculating waypoints for miltis:
![coordinateinputdialogue](https://cloud.githubusercontent.com/assets/6573522/22402004/1d58ab10-e637-11e6-930f-8672c7f6ef68.png)

Here is a mockup of what I am thinking the calculator itself could look like:
![geocalc](https://cloud.githubusercontent.com/assets/6573522/22402005/249a9640-e637-11e6-8f60-89221ca98ace.png)

There are ofcourse many details still to be worked out but this it the general direction of how I am thinking.

Could someone please post an image of what HandyGeocaching waypoint calculator looks like?  I've had a search but can't seem to find it.

**Comment by Lineflyer** [comment]
I somehow like it, but problems may arise in the detail:
- In a typical multi cache you wont have all values initially. So you could only use the function at the very end to calculate the final, or you need the ability to store it wihout filling all variables and editing it later on.
- A simple variable per digit does not always fulfill the calculation requirement. I know many caches which use something like N51 2(A-1).(B+4)(C)(D/2) ...

**Comment by S-Bartfast** [comment]
Thanks for those points Lineflyer.

I have thought about both your points but haven't as of yet decided on a solution.

In terms of your first point:
>* In a typical multi cache you wont have all values initially. So you could only use the function at the very end to calculate the final, or you need the ability to store it without filling all variables and editing it later on.

The intention is to simply fill in the values as you learn them.

Here is an example of the format of the typical multi-caches I encounter:
[GC16K1Q](https://www.geocaching.com/geocache/GC16K1Q_who-is-this)

For this example the geocacher would simply enter the format of the coordinates of the cache at the top of the page as:
>N 37° 25.ABC'
>W 122° 05.DEF'

And paste the critical information from the description of the cache in the Notes section:
>A = the number of letters in the 1st word of the 1st line
>B = the first number on the last line
>C = the number of letters in the largest-print word
>D = the number of letters in the 2nd word of the 1st line
>E = the number of letters in the 1st month - the number of letters in the second month
>F = the last number on the last line.

And simply head to the plaque and enter the values as you work them out.  The intent is to offer simple arithmetic here such that you can enter the two numbers required to calculate the value of '**E**' rather than do the sum yourself.  If for any reason you needed to leave the "Calculate Coordinates" page part way through the page would save the values entered and re-display them when you return, just as a good form should ;)

Admittedly this is only performing a simple substitution, one that any of us could easily do with a pencil and paper without ever thinking really but the intention is to ease the switching of apps and so forth when paperless caching.

Your second point is a little step further:
>* A simple variable per digit does not always fulfil the calculation requirement. I know many caches which use something like N51 2(A-1).(B+4)(C)(D/2) ...

I have thought about this too.
In your particular example the coordinates would simply be represented as
> N 51° 2A.BCD'

And once known the value for a would simply be entered as:
> A = ? - 1
> B = ? + 4
> C = ?
> D = ? / 2

Where the values of the '?' are simply entered according to the instructions in the description.

I think what you were getting at though would be a more complicated example such as [GC57XNZ](https://www.geocaching.com/geocache/GC57XNZ_life-in-the-underground) which represents the coordinates as:
> N 37° 24.JKL

Then lists the digits of 'J', 'K' and 'L' as:
> J = A + F
> K = D - F
> L = A - B

Where the values '**A**' through '**F**' are potentially used multiple times in the description of the equations that represent the values of '**J**' - '**O**'.  One could easily make this work by simply entering the value for '**A**' multiple times but in doing so we are kind of getting back to the "it's easy on paper" idea we are trying to free ourselves from in the first place.

One solution to this "next level" problem would be to allow equations to be entered into the buttons that represent the digits, which for this example would look something like:
> N 37° 24 . [A+F] [D-F] [A-B]
Then simply enter the values for **A** - **F** as the are discovered as before.

While this seems a nice solution I'm afraid space is at a premium with this layout and trying to jam anything more than a single character into those cells simply won't go.  While it would be an option to investigate a different layout the "next level" proposal I am considering is to still have the same simple substitution for the digits in the coordinates as proposed originally but allow the equations that describe those digits to use variables, then have the values of the variables entered else ware.  It's a little hard to describe only using words but I am thinking to have the coordinate digits represented with capital letters and the variables represented with lower case letters.

So the example being discussed here would be represented as:
> N 37° 24.JKL

The equations for the digits would be described as:
> J = a + f
> K = d - f
> L = a - b

And finally the values of the variables **a** through **f** would be entered on a separate table, possibly by swiping the "Capital Letter" section in the middle of the main page to the right to swap in the "Lowercase" section.  One should be able to freely swipe the middle section between the "Capital Letter" (coordinate values) and the "Lowercase" (variable values) section without affecting the rest of the page.  I hope that makes sense :S

Another format that has been pointed out to me is multi-digit values, suck as [GC1PZC0](https://www.geocaching.com/geocache/GC1PZC0_mt-pleasant-fort) which gives the coordinated as
> North 39 32.AAA
and describes 
> AAA = Marker Number + 464

Anyway, it's still early days in the design of this feature but please do share any thoughts or ideas you have as they will be greatly appreciated.

**Comment by Lineflyer** [comment]
I dont know [this app](https://play.google.com/store/apps/details?id=de.tektom.geoformel) but it seems to provide something like that (there is also a free lite version available).
How is the UI handled by them?

**Comment by S-Bartfast** [comment]
Well, after a considerable effort I finally have an implementation of this feature and it has turned out most faithful to the concept image posted above:

![screenshot_1499930202](https://user-images.githubusercontent.com/6573522/28154827-e445a608-67ea-11e7-86ed-0b51267ef7c0.png)

And here is a simple 5 minute video demonstrating the feature:
https://youtu.be/eN2y5mvJul4

**Comment by Lineflyer** [comment]
Thanks for this showing this really nice implementation and for the demonstration video.

I think you implemented it in a very good way into the existing UI. Users not interessted in using it will not be overwhelmed by a large new menu or changed appearance. Those wanting to use it might very easily understand it without need of an extensive manual.

You don't explicitly point out, whether it is possible to store those variables and equations (or just the resulting waypoint coords). But based on our previous discussion I assume that you implemented this as well?!

From my point of view, you should consider submitting a corresponding PR if you want to contribute it, so that the core developers can have a review.

**Comment by pstorch** [comment]
I like it, looks promising.

**Comment by SammysHP** [comment]
Looks really great and nice video, too! If the code is fine, this should be merged, but I have some suggestions:

- It would be handy to store the calculation with the waypoint so that you can come back later and change variables.
- Sometimes calculations are in the form of `A.(B+C)` where a number can be greater than 9. In this case A can have one to three digits and the sum of B and C probably has three digits. I've also seen something like `A.B(C+D)` several times. Do you have any idea how to implement this?

**Comment by S-Bartfast** [comment]
Thanks guys.

> You don't explicitly point out, whether it is possible to store those variables and equations (or just the resulting waypoint coords). But based on our previous discussion I assume that you implemented this as well?!

Yes, the calculator's state is preserved between sessions.  In particular, when one closes the calculator 'page' (or fragment as it is known in Android) the calculators state is saved in memory and will be re-displayed if the "Calculate Coordinates" button is pressed again.  When one 'saves' the waypoint itself (by clicking the tick button in the bar at the top) the calculators state is saved along with the waypoint information and will be restored from then on whenever the calculator for that particular waypoint is opened again.  At present this information is bundled into the waypoint as what is known as a "byte array bundle".  This may or may not be an acceptable way to do things in the c:geo ethos but when it comes time to integrate into the 'main branch' I'm sure we'll find an acceptable way.

>you should consider submitting a corresponding PR...

Indeed.  I have every intention of creating a Pull Request for inclusion into the core repository but I'm wanting to iron out as many issues as possible before doing so, but yes, I will open a Pull Request soon.  In the mean time anyone with the wherewithal to give it a poke is welcome to have a gander at things here: https://github.com/S-Bartfast/cgeo

>It would be handy to store the calculation with the waypoint so that you can come back later and change variables.

Indeed it would be and, better yet, it's been done ;)

>Sometimes calculations are in the form of A.(B+C) where a number can be greater than 9...

This has actually been implemented as well (along with a few more tweaks).  I did make a video showing more of these little features but the video was getting a bit long and I was concerned it would probably be a little boring for those not deeply invested in the feature.  It is my intention however to make another video demonstrating the use of this calculator on 3 real-world caches, the third of which does indeed use multi-digit variables.

I'm not 100% clear on what you mean by the examples ` A.(B+C)` and `A.B(C+D)` but I'm pretty confident the current implementation will cater for it.  To be precise the 'name' of each "equation" (as I refer to them) are all represented by a single upper case (or CAPITAL) letter and the "expression" can contain 0 or more lower-case variables.  So if one had a representation in decimal-degrees format (DDD.DDDDD°) of `38.A`, then specified 'A' to be `A = 42^3` (42 cubed) the result would be `038.740881`:
![74088](https://user-images.githubusercontent.com/6573522/28194175-aa833524-6881-11e7-81f7-836ed1dbebe6.png)

Note the "parser" requires that all multiplications be represented by an '*'.

If you meant the dot in the middle to represent a decimal-point the coordinates could be represented as `A.B` withe the equation for a being `A = a ` and 'B' being `B = b * (c+d)`.  I'll try to create those additional demonstration videos today to show you how it works.

**Comment by S-Bartfast** [comment]
By the way, if anyone is interested the full set of operations supported by the parser are:
`'+'` (both unary and binary: as in "+42" and "40 + 2")
`'-'` (both unary and binary: as in "-42" and "40 - 2")
`'*'` (multiplication: 6*9)
`'/'` (division: a/b)
`'^'` (Power notation)
`'%'` (modules - remainder after division)

**Comment by S-Bartfast** [comment]
Okay, I'm starting to get the hang of making these videos.

And here are videos demonstrating the three caches I mentioned above.
1. Three Rifles Monument: https://youtu.be/6_BALG5192A
2. Subdivide: https://youtu.be/F-ZNAKbLCJ0
3. Origami Rocks: https://youtu.be/NlW2BfF-tu0

**Comment by SammysHP** [comment]
> I'm not 100% clear on what you mean by the examples `A.(B+C)` and `A.B(C+D)`

A=35 B=9 C=102 D=-20

A.(B+C) = 35.111
A.B(C+D) = 35.982

**Comment by S-Bartfast** [comment]
Oh, I see.

Yeah, that works fine.  You need to give each 'part' of the formulation a unique name (identified by CAPITAL LETTERS) but you can define any (lower-case) variables you pleas and combine them in any manor to 'fill' those 'parts':

![sammyshp](https://user-images.githubusercontent.com/6573522/28200755-15c24034-68ad-11e7-817e-e039093c01b6.png)

**Comment by SammysHP** [comment]
If this works for DD MM.MMM as well, this would be amazing! Please open a pull request for review!

PS: I really like your videos and the last screenshot.

**Comment by S-Bartfast** [comment]
Why thank you :)

And yes, it will work for DDD° MM.MMM' (and DDD° MM' SS.SSS", and not to mention 'Plain' [text entry] as well).

I haven't shown any images of the 'Plain' format yet but it pretty much works like you would expect.  Basically you just type in the values the same way you do when entering coordinates in 'Plain' format for the regular coordinate entries, however any UPPER CASE characters you type in will have corresponding entries created for them automatically in the 'Equations' table.  You then fill out these 'Equations' in just the same way as is done for the other formats.

Here's an image of what the same formulation looks like in 'Plain' format (with a bonus 42° for good measure) on a Nexus 10 in landscape mode:

![n10](https://user-images.githubusercontent.com/6573522/28223884-3c8a06fc-690c-11e7-964e-80d0d22f2444.png)

**Comment by S-Bartfast** [comment]
Okay, I have just created a Pull Request.

Enjoy (:

**Comment by Lineflyer** [comment]
@S-Bartfast Is it ok for you if I link your youtube video to a user group on Facbook? I would like to get some more peoples feedback about usabilty and improvement proposals (if any).

**Comment by S-Bartfast** [comment]
You're most welcome to use the video's in any way you please.

Enjoy :)
