### ISSUE TITLE
Make field notes export more accessible

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#2756]
It would be great to have the possibility, from the home screen, to export into a file or to geocaching.com all the stored field notes. There should be no need to go into a list to export them.

(discussion started in #2751)

**Comment by pstorch** [comment]
I just stumbled upon a field note upload issue and was thinking about how to solve it. My suggestion would be to have a global export field notes function like suggested here.

My problem is related to the multilist feature: if I have an offline log for a cache which is on multiple lists and I use the export / field notes on each individual list, then either the one cache is not transfered at all (when checking for "only since last export") or it is uploaded twice. This problem wouldn't exist if used globally (or on the "all" list).

So I was searching and found this related feature request.

I would prefer a new menu entry below pocketqueries on the main activity.

**Comment by Lineflyer** [comment]
Lets take #12151 as successor of this rather old issue.
