### ISSUE TITLE
Use new alpha/beta testing feature on Play Store to distribute RC-versions

### ISSUE THREAD

**Issue by Pitel** [cgeo/cgeo#2788]
Just an idea. See more about it here http://android-developers.blogspot.cz/2013/05/new-ways-to-optimize-your-business-in.html

**Comment by Pitel** [comment]
Any progress with this? I noticed you are publishing nightlies to F-Droid.

**Comment by SammysHP** [comment]
@Pitel Nightlies are published to "our" own F-Droid repository automatically from the build server. There is no such mechanism AFAIK. It would also require us to manage the beta group AFAIK.

**Comment by Bananeweizen** [comment]
We could meanwhile use this gradle plugin to automatically push nightlies as alpha and similar things: https://github.com/Triple-T/gradle-play-publisher. However, that requires that @mucek4 creates a service account for doing so.

**Comment by samueltardieu** [comment]
Why not use the Jenkins plugin?

**Comment by Bananeweizen** [comment]
With a gradle script we can run and test that everywhere, and every developer can improve the script. Even though I'm a big fan of Jenkins, I meanwhile prefer using it just for the automation, triggering, statistics and so on. This way we also have the build process versioned together with the code and can easily reproduce old versions and switch between branches on the build machine.

Independent of that, the service account is needed in both cases.

**Comment by rsudev** [comment]
Besides the technicalities, we should also have an idea (and communicate that), what we want to do with this alpha version. For example we need to decide how the onbording should work and whether we want to get/discuss feedback there. Of course it could be an easier way for people to just stay on the latest nightlies, but we need to be clear about what we actually 'offer'.

**Comment by Bananeweizen** [comment]
I do have a very simple demand for alphas: Right now I have to click the update banner every time when I want to run the current nightly on my (non development) tablet. That becomes fully automated. So at least for developers and regular testers of nightlies from the user base we should enable alpha builds, probably with a selective onboarding.

**Comment by rsudev** [comment]
That I can buy in to :)

**Comment by samueltardieu** [comment]
> With a gradle script we can run and test that everywhere, and every developer can improve the script. Even though I'm a big fan of Jenkins, I meanwhile prefer using it just for the automation, triggering, statistics and so on. This way we also have the build process versioned together with the code and can easily reproduce old versions and switch between branches on the build machine.

That's exactly why I would advise against a gradle task for uploading to the Play Store: this does not belong to the *build* process. For example, it would make no sense to try to use an ancient API for uploading apks even when trying to re-upload an old build (new fields could have become mandatory for example). Build and deployment are different beasts, and only the former should be versioned IMO.

**Comment by Lineflyer** [comment]
Meanwhile the alpha/beta channels at Google Play do also support adding user by simply providing them a link (no need to subscribe them to a GoogleGroup or G+ page before).
If we want to get it running I suggest to use alpa for our nightlies and limit them to cgeo-dev@googlegroups.com for the time being. I am not sure how GooglePlay manages to distinguish between alpha and release version (as these might be not compatible to each other).

For beta testing we could share the link to our users and let them subscribe to get RC versions. From RC to release we have a clear versioning, so it is a straight forward solution:
Users subscribed to the beta channesl will receive the RC and later on receive the release version and can upgrade without a problem.

**Comment by Lineflyer** [comment]
Addition:
For the open beta testing Google needs to have the following information:
- Max amount of users (min. 1000)
- Feedback channel (mail or URL)

What do you think about the user limit and which way of feedback do we prefer?
IMHO the amount of users is not so important (start with 1000 and lets see) and the feedback channel should better be Github issue link but not our support address.

**Comment by Lineflyer** [comment]
After posting to FB regarding the RC-version a user suggested to better use the beta feature.
I will try to see if I can give it a try unless someone stops me, saying that the use of this beta channel is not wise for some reason.

In a first step I might upload the RC and it should be invisible for everyone until we share the opt-in link with users.

**Comment by samueltardieu** [comment]
I was going to suggest that.

We could share the enrolling link on our site, or even in the description on the Play Store (as is done for Google Maps).

**Comment by Lineflyer** [comment]
I did now upload the current RC to the beta channel and have following things to clarify:- For some reason the console already reports 261 testers although we never shared the link- The console offers to publish the current beta into production. That is not the way we want to go...so I need to check if there is any influence on publishing in production and how to depublish the beta. Maybe its not even necessary to remove it if Google Play takes the version codes into consideration.
-------- Ursprüngliche Nachricht --------Von: Samuel Tardieu <notifications@github.com> Datum: 04.08.16  13:26  (GMT+01:00) An: cgeo/cgeo <cgeo@noreply.github.com> Cc: Lars <gc@droescher.eu>, State change <state_change@noreply.github.com> Betreff: Re: [cgeo/cgeo] Use new alpha/beta testing feature on Play Store to distribute RC-versions (#2788) 
I was going to suggest that.

We could share the enrolling link on our site, or even in the description on the Play Store (as is done for Google Maps).

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@samueltardieu in #2788: I was going to suggest that.\r\n\r\nWe could share the enrolling link on our site, or even in the description on the Play Store (as is done for Google Maps)."}],"action":{"name":"View Issue","url":"https://github.com/cgeo/cgeo/issues/2788#issuecomment-237526658"}}}

**Comment by Lineflyer** [comment]
Thats how it looks:
![screenshot_20160804-190105](https://cloud.githubusercontent.com/assets/949669/17417274/c547cd00-5a92-11e6-98ac-728259e39994.png)
![screenshot_20160804-190116](https://cloud.githubusercontent.com/assets/949669/17417276/c548cbec-5a92-11e6-86ed-1bb23c0b06ef.png)
![screenshot_20160804-190002](https://cloud.githubusercontent.com/assets/949669/17417275/c547f7ee-5a92-11e6-906d-2df4fb6357d2.png)


And on Google Play:
![beta_console](https://cloud.githubusercontent.com/assets/949669/17417291/cf687532-5a92-11e6-8a05-50c09a2b93ef.jpg)

**Comment by Lineflyer** [comment]
Where shall we publish the link? 
I suggest social networks and in our PlayStore description.

**Comment by Lineflyer** [comment]
I think our version coding is fine for RC and production releases.
According to https://support.google.com/googleplay/android-developer/answer/3131213 the beta apk will be automatically removed once a version with hiher version code is uploaded to the production version.

(Same method applies for alpha testing which will not work if we would use that for nightlies).

**Comment by Lineflyer** [comment]
I have made the link public now, so the beta channel is now officially open:
```
We did now implement an easy method for you to help us testing new c:geo versions!

If you are interested you can become a beta tester on GooglePlay by just a single click on the following page:

https://play.google.com/apps/testing/cgeo.geocaching

As a beta tester you will automatically receive the official beta versions (release candidates) of c:geo via GooglePlay update and have the possibility to send us your comments and problems also via GooglePlay.

As we are only a small team with few testers your help is highly appreciated to make c:geo even more reliable and stable with less bugs!

Feel free to share this post to interested users.

Thanks,
your c:geo team
```

**Comment by Lineflyer** [comment]
I did now also update the Google Play description (first row in change log) with a short link to the beta testing opt-in page.
Furthermore I included info about beta testing on the website.

I think we can close here.
Using the alpha channel for nightlies does not look like the way to go for the moment.
Beta testing is enabled and will be used for RC-versions from now on.
