### ISSUE TITLE
Selecting "remark" on an Event cache ended in "Needs archive"

### ISSUE THREAD

**Issue by pilhuhn** [cgeo/cgeo#2916]
I've selected "Remark" on an event cache. When sending off I got a "needs archive" log entry, which is bad

c.geo 2013.6.5, German locale

(on top of this issue itself, I am not sure if "needs archive" is really something users should post on the go with a handset app. )

**Comment by akkatracker** [comment]
Is this still the case? I'll have a look at it if so.

**Comment by Lineflyer** [comment]
I tested with 2017.05.21-NB and could not reproduce the faulty behaviour (but maybe it is also a timing issue).
I tested to start loggging without data connection, selected log type "Write note". I stored the offline log, and started logging again with data connection. Still the log type "Write note" is active.
But this way of testing is maybe something totally different than a "slow network" as I saved the offline log during the process.

Anyway as we since a while have a warning before submitting NA logs I think it is not worth to investigate or fix this anymore.
