### ISSUE TITLE
Have trail on live map more permanent

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#2958]
From FB:
When one exits the map and enter the cachedescription for logging and then enters the map afterwards the trace is gone.

Request: Track on map log. Would like a track log that shows the track even if one have closed the map and opened it once again. Just like a track log on a real GPS.

Reasson: Have been some places where mapcoverage isn't good and would like the possibilities to "backtrace" ones footsteps.
## 

Also when leaving the live map by using the back key the trail is lost.
It would be could to keep it running/saved as long as c:geo is active with a menu option on the map menu to clear it.

**Comment by Lineflyer** [comment]
Meanwhile the trail has been disabled by default and there was no other user demand. Therefore closing for the time being.

**Comment by mjarmstr** [comment]
How do we show user demand?  I use the trail quite often and if I hit back on too many times, I loose it.  I find the trail very useful for keeping track of the path I've taken to approach a cache.

**Comment by LeXeRLV** [comment]
I use trail all the time and it is really needed, especially when you are
in surroundings, where is no roads and houses...
I'm surprised, why still in c:geo is no imported function to track your
walking or driving by bike and so in, or just tracking  like ir t is on
Locus PRO,don't need something like Endomondo or Sports Tracker..

-- 
Best regards,
LeXeR

**Comment by rsudev** [comment]
For me (and I think I speak here for the whole 'team') c:geo ist 'just' a geocaching app and not a general purpose Map/GPS-App with geocaching functionality (like Locus).
I personally use the tandem of OruxMaps and c:geo in the event I also need tracking and orientation functions while geocaching.
So the trail never was meant for or designed as a tracking facility in general (highlighted by the fact that it happily stops recording your position when the phone is locked - in exchange for reduced power consumption). Nevertheless wouldn't it hurt IMO, to have it outlive the accidental back to the main screen from the map. That said I currently deem other topics much more relevant (like being able to make the shift to the current map apis).
Regarding user demand - as Lineflyer highlighted did we switch off the 'default on' trail more than a year ago, without complaints. And while there ar other long-standing topics open, they receive the occasional duplicate or comment from some user, clearly documenting a higher demand (even though there is no bullet-proof coupling it definitely shows a tendency)

**Comment by Bananeweizen** [comment]
Same opionion as @rsudev here. A very basic design principle in Android is to not reinvent the wheel all the time. That's why if your app needs to send a mail, it will invoke the mail intent, thereby starting the mail creation in the current default mail app. And other non-mail apps don't have to implement this themselfes.

Because of this, I would also rather suggest an alternative. We could try to automatically invoke another app for tracking. That way, our effort would be reduced, and people could do all kinds of things with the track afterwards (depending on the ability of the tracking app, like Locus, Oruxmaps, or whatever...)

**Comment by djtooley** [comment]
I visited this site today specifically to see if there was talk about the tracking feature.

A friend showed me his tracker (another app) and the data it gave was really nice. I especially liked the graph of altitude over time. And having the more detailed trail was attractive.

I use the trail feature all the time. It's especially useful when you can't find a cache... it gives you an indication of what area you've been searching, which may cause you to realize which areas that you have not been searching.  I've also occasionally posted the "look I searched a LOT" humorous screen capture.

I suggest, instead, upgrading the feature to have full and strong tracking ability. I recognize that this is a battery drain, and I'd frequently not want that. But if it's a capability that I could turn on, I would certainly use it frequently.  (and I've been known to carry a spare battery with me...)

I anticipated the "keep to the core functionality" response. I agree with that concept. But I've found that having the current tracking available is a strong feature that I use all the time. Tracking pretty much needs to be visible to be able to use it for active geocaching, otherwise you're just storing where you've been, and there are lots of apps that can do that.

Don't think of it as a generic tracker tacked on to the app, think of it as a "geocaching tracker", specifically suited to our needs.

**Comment by Lineflyer** [comment]
In contrary to the comments above I do see the proposals of @moving-bits as bugfixes rather than new features. So let me reopen this for now in case someone is interested to fix things like storing the trail.

However I also do still thing, that we should not introduce new features on top of it.

**Comment by moving-bits** [comment]
Hm, a fix was merged with #7244 - don't know why this issue has not been closed automatically - closing manually.
