### ISSUE TITLE
Send to c:geo - Google store

### ISSUE THREAD

**Issue by Cu8eR** [cgeo/cgeo#3130]
Add send to c:geo script to Google store and Mozilla store.

It would be nice to add this script to these stores... it would be update automatically, users could write their reviewes, etc... mainly no problem with installing

for example GC little help is in the Google store too

**Comment by Lineflyer** [comment]
This needs to become more urgent due to new restrictions in Chrome. From support mail:

I would like to ask you for one thing for improvement. 
I had tried to install plugin send2cgeo into my Chrome browser and it was working well but only until first restart of my browser. After that Chrome automatically blocked all plugins which are not from official chrome store with explanation that it is not allowed to install plugins out of chrome official store. 
It is standard chrome security setting in last versions. 
Would be possible to add your plugin into the Chrome store?

**Comment by Lineflyer** [comment]
This issue was moved to cgeo/send2cgeo#7
