### ISSUE TITLE
Whitespace is inserted for signature placeholders

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3199]
Everytime I edit my signature and use the "Insert placeholder" feature a whitespace is added in front of it.

Example:
I have written `Cache count:` and select to insert [NUMBER] this will result it `Cache count: [NUMBER]` instead of `Cache count:[NUMBER]`

**Comment by tinokorth** [comment]
Hello @Bananeweizen,

I do not agree with yout intention to prevent the people to make mistakes. Keyboard apps have the pissibility to disable the whitespace function - in *my* opinion its a very uncomfortable function because we've got lot of words that are easy combined.

The function that a whitespace is inserted before a placeholder is not a comfortable function - no user would expect a whitespace. Normal software solutions are also not whitespacing placeholders (Outlook, Word, other Clients). Why do you think this could be comfortable?
It's not so easy to go to the start of the word and remove the whitespace. It sounds easy, but it's really annoying.

So I'd like to ask you to think about not beeing a god of typographic and be a friend of your users.
If they want to have a whitespace they'd insert it manually. ;-)

Regards

Tino

**Comment by Lineflyer** [comment]
I guess one main difference is also, whether one uses the placeholder from the dropdown while typing his logs or he uses them in his signature.
At least when used in the signature thr user would expect the signature to be inserted as he defined it, not adding whitspaces for the placeholders. He could easily do this in the signature template if required.

**Comment by Lineflyer** [comment]
> At least when used in the signature thr user would expect the signature to be inserted as he defined it, not adding whitspaces for the placeholders. He could easily do this in the signature template if required.

Just checked and it is not the case that when using placeholders in the signature there will be no whitespaces added. Therefore closing again as "wont change".

**Comment by bekuno** [comment]
> 
> 
> > At least when used in the signature thr user would expect the signature to be inserted as he defined it, not adding whitspaces for the placeholders. He could easily do this in the signature template if required.
> 
> Just checked and it is not the case that when using placeholders in the signature there will be no whitespaces added. Therefore closing again as "wont change".

The signature is inserted at point 0. Therefore it works (`if (start > 0 && ...`)

The original point was to insert something from the droppdown templates (+-sign or smileys) not at position 0.
Then the space is inserted before the new text.
The situation described in https://github.com/cgeo/cgeo/issues/3199#issuecomment-467035752 would normally not be here.

@Lineflyer So the "comfort function" should stay?

**Comment by Lineflyer** [comment]
Yes, IMHO it can stay. No other user complaints from users.
