### ISSUE TITLE
Twitter placeholder [NUMBER] adds finds plus 1

### ISSUE THREAD

**Issue by msebald** [cgeo/cgeo#3392]
It seems that the number of found caches is one too high for the Twitter placeholder while it works perfect for the log template itself.

**Comment by Natureshadow** [comment]
I looked through the current code and found that there is no way of finding out directly whether the template engine is called for logging or for Twitter.

Any hints on how to solve that? I am not a Java expert, but my two ideas are:

 * Find the caller by getting a stacktrace or reflections
 * Use an optional parameter
 * Use another tag

I'd prefer the first option, because the second seems to flatten the way for far too many special code paths in the future and the third is a mess from a user point of view.

Any comments?

**Comment by samueltardieu** [comment]
Fixed in `master`, let me know if you want this on `release` after testing.

**Comment by msebald** [comment]
Works for me now. :-) Thank you!

**Comment by Lineflyer** [comment]
@msebald You tested with a nightly build?

**Comment by msebald** [comment]
Yes, the latest when I posted it on March 29th.

**Comment by Lineflyer** [comment]
@msebald Thanks.
@samueltardieu  I trust on that result. Please merge to release.
