### ISSUE TITLE
Return from a PQ list should still show all PQ lists

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#3525]
Currently, when you open a certain PQ list and back out again, then you are back at the main screen instead of at the overview of all PQ lists. This is not typical Android navigation.

Probably we should convert the alert dialog for choosing a list into an activity with a real list view to better navigate the PQs.

**Comment by Lineflyer** [comment]
This issue came back to me while testing the new PQ features. It is really inconvenient to return to the main screen when closing the PQ list. Now it got even worse because if e.g. a user might want first to take a look at the PQ before downloading it, so he would expect to return to the selection "List / Download" when closing the list, or not?

**Comment by Bananeweizen** [comment]
This is fixed with the new list.

**Comment by Lineflyer** [comment]
Working perfectly. Thanks @Bananeweizen

**Comment by Lineflyer** [comment]
This seems no longer working for me with the latest changes to that PQ dialogs.
Reopening.

2016.01.21-NB

**Comment by Bananeweizen** [comment]
I have no idea what you mean. Going back from either download or list preview shows the PQ list again for me. Also there were no changes in that area, as far as I'm aware.
