### ISSUE TITLE
Data handed over to Radar app

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3581]
After implementing the fix for #3567 I have seen, that our recommended radar app "GPS Status" now also behaves different, i.e. the cache name is shown as target if the radar is called for the main cache coords. It is great, that we can hand over additional information here.

However it could still be improved IMO:
1. If I call the radar for a waypoint of a cache it seems nothing is handed over. I expected to see the waypoint name here, which could be helpful to verify, that you are navigating to the desired location.
2 Instead of the name of the cache it would be more helpful to have additional information at first place to be handed over (as I probably know the name but not necessarily other important info for finding the cache such as D/T/Size). Therefore it would be appreciated if a string consisting of D-rating/T-rating/Size could be set as primary information. It could read like `D1.5/T2/Large`. That would also make it consistent to the information we show in our own compass.

**Comment by Lineflyer** [comment]
Feedback was not sufficient for this being implemented.
Additionally the radar app does not support additional fields for handing over the information.

**Comment by MrYaz** [comment]
Too bad this has been closed!
I totally agree with @Lineflyer on this one!

I have always missed to be able to see the D/T/Size directly in the Radar app.
With a very short term memory as myself I have to exit the app to see what D-rating it has, only to exit the app 20 seconds later to see what the T-rating is, and exiting again a few seconds later to refresh my memory what D-rating it has. And what was the cache size now again?

It would be really great if the string at the waypoint should read "Cachename (D5.0/T5.0/Large)"

Especially as the c:geo compass, which is an navigation app as well, shows a lot of extra info in the same view.

One data field or separate data fields? The end user does not care, as long as the info is visible.

@Bananeweizen 
Even if Radar is not a Geocaching app by design, in this context it surely is!
I think this change should make the Geocaching user experience with c:geo even better.

I hope that this issue can be reopened for reconcideration?
