### ISSUE TITLE
Improve Tablet preview

### ISSUE THREAD

**Issue by marco-dev** [cgeo/cgeo#4072]
As mentioned in #3967 the preview static map is too small on tablets and less in detail due to zoom factor.

**Comment by Lineflyer** [comment]
@marco-dev 
Although we did not have the chance to test the static maps on different hdpi tablet devices in Munich I do also think that a higher zoom on tablet is still desireable.

Right now on my tablet with 2560 x 1600 Pixel resolution it looks like in the first picture in this thread.
I do also think that that the lower zoom with a larger map looks more nice on high resolution devices.

**Comment by marco-dev** [comment]
This is a really long time ago. Should I put my change to master?

**Comment by marco-dev** [comment]
So this large size but more zoomed in which I would say is a higher zoom factor?

**Comment by Lineflyer** [comment]
Yes, really long time ago..I just found it while browsing.
It is difficult to interprete the different pictures on this thread.
IMO the detail level is enough, it just needs to be a larger image to be more readable....so this would mean same (or lower zoom) with bigger picture.
Isn't it what @mucek4 also suggested above?

I am sure this might need some finetuning after implementation.
So, if you are interested to provide a PR you should make those thing "customizable" (e.g. the dpi limit to user larger images, etc.). 
I can offer to test this after merge on different devices (at least those I own) and provide feedback.

**Comment by marco-dev** [comment]
That is what I also got. Same zoom like on smaller devices but larger part of the map.

**Comment by marco-dev** [comment]
The image can only grow up to 1024 x 1024, because that is the maximum the maps api provides (with scale = 2, width = 640 height = 640). Now we have to decide if it's better to zoom out one step (on all devices) or to keep the current preview zoom.

https://github.com/cgeo/cgeo/issues/4072#issuecomment-49972831  top or bottom image?

**Comment by marco-dev** [comment]
Sorry, I mean my comment:
https://github.com/cgeo/cgeo/issues/4072#issuecomment-49264512

**Comment by Lineflyer** [comment]
> Sorry, I meant my comment:
#4072 (comment)

Top image with the lower zoom is better, because you might get the chance to identify the area by the surrounding map (e.g. city name). The higher zoom in the example seems only to cover some streets around and if e.g. the coords are in the middle of the woods you would only see "green".

But I do not understand why we need to change it on all devices...wasn't it the idea only to zoom out on highres devices (because on low res, zooming out could result in e.g. street names not being readable anymore).
However this is really difficult to discuss in theory. I suggest to have some more screenshots with a highres and a lowres device with the proposed new implementation to judge how it looks in real life.

**Comment by Lineflyer** [comment]
Will test this.

**Comment by Lineflyer** [comment]
@marco-dev  If I read your commit correct you just changed that the map heigth * width ratio: Before the change the images have been x*x with x being the smaller side of the display, so it was square. Now we request x*y  (being the display x and y size of the device).

Consequently it now returns a restangle map instead of a square map on my tablet with the same zoom. It looks somehow more smooth fitting into the deisgn but in fact we lost information due to the left-out size on y axis.

Don't know if we have any other options, but the current change is only a design change rather than a better information in the preview. What other options could we have with the zoom level (if any)?

Before:
![screenshot_2015-01-28-21-31-54](https://cloud.githubusercontent.com/assets/949669/5946440/01cd4500-a736-11e4-8268-f190dffdb1f5.png)

After:
![screenshot_2015-01-28-21-32-14](https://cloud.githubusercontent.com/assets/949669/5946444/074786d0-a736-11e4-8774-ccd65087161c.png)

**Comment by marco-dev** [comment]
Sorry, but google limits the image size to 640x640 doubled, resulting in 1280x1280. This is already the max size. Correct me if I'm wrong. So: back to square if you have higher res?

**Comment by Lineflyer** [comment]
Ok, understood.
In this case we will not have a benefit on highres but only the drawback to see "only" a rectangle. So IMO we should go back to square with the 'Math.min' calculation.

**Comment by SammysHP** [comment]
This is only a problem as long as we have no special layout for large displays. Maybe we should invest the time to redesign the detail activity and add layouts for different screen sizes.

**Comment by Lineflyer** [comment]
@SammysHP Yes. There is nothing else we can do right now. So lets get back to the old version and wait until our UI has new possibilities.

**Comment by Lineflyer** [comment]
Closing this one.
Any functionality change here requires a overall UI improvement (covered by a lot of other issues)
