### ISSUE TITLE
Marker clustering

### ISSUE THREAD

**Issue by krzema12** [cgeo/cgeo#4098]
There are cases when there may be a huge amount of markers visible in the "Live map" view. Half of them are hardly visible (hidden behind the others), and it also greatly slows down the device while moving around the map - it seems like "one marker per one cache" implementation. I thought that the marker clustering would be a neat way of displaying the map in a more readable way.

What I have in mind, in a nutshell: for a given zoom level, a certain set of markers which are close to each other would be replaced by one marker, with a number of replaced markers. A good example of a working algorithm can be seen here: http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/examples/simple_example.html - try zooming in and out near the markers.

I'd love to contribute to the project and code it myself, but as I can see in the Google Play release note, a bigger release of the app is coming. Because of that, I assume that it's not the best time to fork, am I right? On the other hand, I could fork from the branch where the new version is being prepared. Please tell me what you think about the idea itself and if/when I could implement it.

**Comment by moving-bits** [comment]
IMHO there are two issued mentioned by the thread opener:
a) too many icons
b) icons too large

To resolve a), switching to "combined markers" (like geocaching.com does) may be a good solution. 

For b) I suggest (feature request) switchable icon sizes. Add a menu entry in map view to switch between "large" icons (today's icon size, default) and "small" icons (eg a quarter of the size of today's icons).

Today's large icons make it close to impossible to do planning on a map - either the visible part is to small for useful route planning, or there is too many space occupied by icons, if you're viewing a larger part of the map.

**Comment by Lineflyer** [comment]
@moving-bits 
> To resolve a), switching to "combined markers" (like geocaching.com does) may be a good solution. 
What do you mean by "combined markers" and how could that help (assuming that you only mean less different types)

**Comment by moving-bits** [comment]
With "Combined markers" I'm thinking of the following: If there are several caches nearby, geocaching.com shows only one marker. If you click on the marker, the typical info window pops up, in which you can navigate through the different caches by clicking on the arrow (<, >) symbols. It looks like geocaching com only shows up to a specific number of markers per screen space. If there are more caches to be shown, it switches to "combined markers". Which will happen more frequently if you are zooming to a larger part of the map.

**Comment by moving-bits** [comment]
As of the recent changes on geocaching.com there may be another approach: show small colored dots on higher zoom levels instead of the detailed (and large) specific icons. This would make it much easier to plan a trip.
Even better would be to make it switchable directly in the map by the "dots menu".
(So the reference to #5599 could be a little misleading. It's not about showing only the map, but showing map + caches + still be able to see enough of the map to get some orientation.)

This might be easier to implement since it's probably just supporting a second, smaller, set of icons (without any specific overlays for notes etc.), instead of having to rewrite the whole logic to support "combined markers" or something similar.

**Comment by rsudev** [comment]
@moving-bits:
The map get's its icons through MapUtils.getCacheMarker resp. MapUtils.getWaypointMarker, so there you have the opportunity to deliver something new easily based on a setting. And there the markers are composed from base and overlay icons, so there you can also skip adding the overlays.
Waypoints are probably disabled in such situations already through the waypoint threshold, otherwise in the places where the waypoint threshold is used it is necessary to check this as well.
The map menu is built in NewMap.onCreateOptionsMenu. This method partially inflates a menu resource and partiall adds some items dynamically, depending on map 'type'. So you need to dive in there and look where you want to infuse the new setting.

**Comment by moving-bits** [comment]
@rsudev: Thanks for the reply. Do you have time to chat?

I've added menu and settings handling already => works :-)

I also tried changing the icons by 
- replacing the original icons with my smaller "dot icons" (created new resources + changed enumerations/CacheType) and 
- changing AbstractCachesOverlay.getCacheItem method: instead of calling MapUtils.getCacheMarker method I called some drawable method (don't remember the name) with the marker id directly
Problem was: I got no icons, but only the white round background overlays :-(
And those overlays still had the large size (36px, IIRC) instead of my smaller "dot icons".

**Comment by Lineflyer** [comment]
Just one pointer to consider:
The new map still has some regressions compared to the old offline map implementation (see issues with label "New map"). Maybe its more reasonable to tackle those issues first before setting new features on top? Just thinking...

**Comment by moving-bits** [comment]
> Just one pointer to consider:
> The new map still has some regressions compared to the old offline map implementation (see issues with label "New map"). Maybe its more reasonable to tackle those issues first before setting new features on top? Just thinking...

Generally I agree with this. But my knowledge of Android programming is not good enough to dive into deep debugging sessions... On the other hand the "dot icons" feature is a feature I'm longing for for a long time - it makes planning an ad hoc cache trip much easier on a mobile device - so I'm trying to bring this one a little step further.

**Comment by moving-bits** [comment]
@rsudev 
I've managed to bring the "dot" icons on the map (either cache or waypoint, different colors etc.) by creating `MapUtils:createCacheDotMarker()` and `MapUtils:createWaypointDotMarker()` respectively + extending `CacheElement` and `WaypointElement` classes for the new resource ids.

![image](https://user-images.githubusercontent.com/3754370/50725955-5977a500-1106-11e9-8201-d413ce06825a.png)

Now: What would be the best way to activate those functions - currently I have that hardcoded in `AbstractCacheOverlay:getCacheItem()` and `AbstractOverlay:getWaypointItem()` - ok for developing purposes but in no way feasible for production.

I would like to make this dependent on either current map zoom setting or on using a preference setting (the latter of which I have currently implemented). But how do I get to know the current setting in either of the above mentioned functions if not by calling `Setting.getXXX()` for each cache? When / where should I acquire this information and how to temporarily save it?

Second question: The icons I'm using are directly created from resources. Should I still use the overlay cache for it, although there are no overlays?

**Comment by SammysHP** [comment]
I'd switch between both versions depending either on zoom level or average cache density.

**Comment by rsudev** [comment]
@moving-bits: As discussed yesterday, perhaps the 'invalidateAll' i prepared here (https://gist.github.com/rsudev/c013984060f350ba2dccfac2b9c04bf9) could do the trick. If you link your current WIP, I can also try it out on my end.

**Comment by moving-bits** [comment]
Thanks for exploring into this and creating the gist. I integrated it in my current WIP - and have good news and bad news:
- good news is: it works - after switching the menu setting, all icons vanish instantly and get redrawn after a while
- bad news is: there is a significant delay of a couple of seconds (maybe 5s or so in the emulator) between icons vanishing and icons being redrawn; this delay is longer than it takes to close and reopen the map (which is app. 1-2s in the emulator). Nothing visible happens during this delay.

**Comment by githubber2222** [comment]
Does this improve the speed of the map? I am having trouble when I have a list of 2000 caches and I zoom out to show them all things basically die on me. Even on a modern Galaxy S9 things are slow.
Will this feature make it faster? Or does it ONLY draw a smaller icon?

**Comment by rsudev** [comment]
Likely not in principle, as it is only a smaller icon that will be drawn (which might be a bit faster, but not substantially).
I would be interested to understand which map type you are talking about here (google map, old mapsforge online or offline, new mapsforge online or offline) and what 'slow' means for you (a rough description) and please also state the c:geo version you are using (main menu - about c:geo).

**Comment by moving-bits** [comment]
> Does this improve the speed of the map? I am having trouble when I have a list of 2000 caches and I zoom out to show them all things basically die on me. Even on a modern Galaxy S9 things are slow.
> Will this feature make it faster? Or does it ONLY draw a smaller icon?

As rsudev said: probably not, although those dot icons are smaller and don't have insets/overlays. But: This issue (#4098) is not about speed, it's about readability for areas with a high cache density.

But I'm curious anyway, why c:geo seems to be slow on your device. I'm currently using a mid range device which, according to benchmarks, is about 2-5 times slower than an S9. On this device c:geo does not break any speed records, but it's reasonably fast to be a good geocaching companion.

**Comment by rsudev** [comment]
Interesting. In my emulator, the switch is almost instantaneous, for sure much less than a second. But when playing around with it (on live maps with high number of caches), I could also experience the horrendous effects of the data-races in my map implementation...

**Comment by moving-bits** [comment]
My test case was about 130 caches. I will test with a higher number of caches as well as on a physical device.

**Comment by moving-bits** [comment]
Test results with Note 3 physical device, 1100 caches, system freshly booted, Lineage OS API level 25 (Android 7.1.2).

At first I just estimated the test times, but as I couldn't really believe the times, I started all over, this time with a timer for measurement... Here are the results:

preparation:
- started c:geo, opened list with 1100 caches, jumped to map, zoom level is 10km
- cache markers took app. 4s to display, map tiles app. 15s (first time load of 1.8 GB offline Germany mapsforge map)

round 1:
- activated dot mode
- cache markers vanish instantaneously (< 1s)
- but then: it takes 105s until the first dot appears!!! (measured with timer), and about 2-3s until the last one comes up

round 2:
- activated regular mode
- dots vanish instantaneously
- this time it takes more than 150s to load the cache markers!

round 3:
- back to dot mode
- cache markers vanish instantaneously
- dots take 105s (again) - so dots seem to be a little faster than the regular cache markers :-)

What's going on here...?

**Comment by moving-bits** [comment]
Test using an emulated Nexus 5X API 26 (Android 8) with different GPX file (1650 caches, zoom level 2000km):

- similar behaviour
- first switch to dot mode: 40s
- switch to cache marker mode: 145s - so more than three times the time as for the dots in this setting

(and similar times in a second run directly after the first, without leaving the map in between)

Otherwise, both devices behave reasonable, not lagging significantly while using c:geo.

Is there anything I could check or measure for you?

**Comment by githubber2222** [comment]
I guess these numbers answer your questions... and the 1650 caches would be a small number for me.
Have you ever loaded 5000 caches? Using ANY map?
Anything that takes over 1s to display is starting to make things unusable. Shouldn't one be able to pan around on the map and NOT wait seconds for things to show?

**Comment by moving-bits** [comment]
Not really, as the first loading of the map is relatively fast, considering the amount of caches.
The significant delay happens when switching between two different icon representations, a feature which is in testing stage and not even in the nightlies yet, so this cannot be the problem you are suffering from.
We should give rsudev a chance to investigate further.

**Comment by rsudev** [comment]
@githubber2222 I suggest to keep a generalised performance discussion out of this issue. If you want to raise specific performance issues, please open a new issue with sufficient precise information.
@moving-bits I tried your updated branch on various emulators (api 17 and 26) and my (very similar) branch even on my physical device and couldn't reproduce your results. The switch is slower on my physical device (xperia z5), but still within a second.

**Comment by moving-bits** [comment]
@rsudev: Those times would be sufficient.
Hm, what could be the cause of those differences? My branch is based on current c:geo master, compiled with Android Studio 3.2 (so not upgraded yet). Do you have any other changes / improvements in code or configuration?

**Comment by rsudev** [comment]
I used your branch without any changes to cross-check in my emulator and achieved the reported timings. I have upgraded As and the sdk to the latest version, though. That might be the difference.

**Comment by moving-bits** [comment]
> I used your branch without any changes to cross-check in my emulator and achieved the reported timings.

strange...
Did you use the debug versions or a non-debug build?
(Mine were made with the debug build AS automatically installs.)

> I have upgraded As and the sdk to the latest version, though.

So it's safe to upgrade to recent versions of studio, gradle etc. as suggested by AS? (I've purposely avoided this so far - "never change a running system"...) Do I have to change any config settings after the upgrade or watch out for any pitfalls?

Will re-do my tests with a new build made with AS 3.3 then after upgrading (but will be Thursday, probably).
