### ISSUE TITLE
1st impression in application is bad

### ISSUE THREAD

**Issue by mucek4** [cgeo/cgeo#4263]
Ok. Many people install c:geo to test it. They go to settings with toast they can't login. In past 2 days I had 2 people on support saying they couldn't find a way out of settigns as you need to press BACK button.

We need to make some more "user friendly 1st impression".

**Comment by andrixnet** [comment]
+1

**Comment by andrixnet** [comment]
Also regarding 1st impressions: when accessing the map for the 1st time, the user is presented with a warning that caches shown but not yet stored locally / offline do not have accurate location. 
Is this a general thing or only specifically related (requested by?) geocaching.com? 

If it is strictly related to geocaching.com, then this warning should only be displayed when the user accesses the live map for the 1st time AFTER configuring and activating the account on geocaching.com.

**Comment by andrixnet** [comment]
Also I must underline what is described in https://github.com/cgeo/cgeo/issues/6539 that such introduction should not push `geocaching.com` service as the **apparently** only cache listing service.

**Comment by andrixnet** [comment]
I have the following suggestions: 

1. first time opening c:geo should show a welcome screen with a few introductory information.
2. from here on, you might continue with a wizard style configurator, similar to that which any Android device gives you the very first time you start it (or factory reset it)
- inform the user he/she must first configure a cache listing service. 
- offer the choice of cache listing services to configure
(see Android settings, Accounts section for inspiration. assume your device and installed apps show more then a google account choice there)
- once a service is selected, offer using an existing account, or creating a new account
- once a service is configured, return to services choice. Offer the choose another service or to go to the next step (at least one service is required)
- offer to configure additional services (such as geokrety. gcvote, send2cgeo). This step should be skippable
- offer to install offline maps. This step should be skippable.
See https://github.com/cgeo/cgeo/issues/6072 and OSMAND application
- show main screen with first-time usage guidelines.

**Comment by Lineflyer** [comment]
Update to this one:
After our move to targetSDK =26 with the need to implement permission handlers, we do now have no first start guidance at all. While in the past we at least opened up the gc.com credential page in c:geo we do now AFAICS with the main screen being not authenticated to any connector.

While this can be seen in the status bar at the bottom, I can still see on support channels that users just start using the app without being authenticated and due to our historic implementation they will still be able to see something (but nothing meaningful....e.g. totally wrong gc.com caches on live map).

At this point we should at least reimplement to start up the app in Settings - Services in case no service is activated.
Even better would - of course - be a real guidance or option to open the relevant section of the online user guide.

**Comment by andrixnet** [comment]
I just got feedback from a former iphone user switching from cachly  (iphone) to c:geo (android). 
At least regarding the offline maps part, this user complained about the manual steps required to be done, while he did the same in few clicks inside the app on cachly. 
Nominating "cachly" because the user did, not intending to make any other comparison except regarding the user experience on the offline maps issue.
