### ISSUE TITLE
have Jenkins job for restarting emulator

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4311]
We should have a Jenkins job which executes a shell script to restart the emulator. That way every developer could handle the case of a broken test environment, not only @mucek4 .

**Comment by kumy** [comment]
`sudo`?

**Comment by kumy** [comment]
With the new build executors @samueltardieu implemented, `adb` still randomly can't connect to emulator.

I have activated the "`Run an Android emulator during build`" option. So emulator is automatically started before each build.

As a counterpart, jobs will fail to build on @mucek4 executor, because of missing configuration.

- [ ] @mucek4 can you please create (or rename) an emulator called exactly **emulator**. It must be owned by user **jenkins**. You can also kill the actual running emulator.

- [ ] Docker images should be updated to not automatically start the emulator.

**Comment by mucek4** [comment]
I can rename emulator, but it will fail to start. Currently emulator is started as force-32bit cause server is (still) 32bit. Probably long standing issue to move to 64 awaits me.

**Comment by Lineflyer** [comment]
@mucek4 I think this is outdated, is it? at least I do not see any major problem for restarting emulators, since they are now fresh set up on each build.

**Comment by mucek4** [comment]
true. Master is without an emulator.
