### ISSUE TITLE
Put invocations to "loadWaypoint" into background thread?

### ISSUE THREAD

**Issue by yulin2** [cgeo/cgeo#4418]
Dear developers of cgeo,

I'm a Ph.D. student and I'm doing research on improving performance 
for Android apps.

In cgeo, I find sometimes "DataStore.loadWaypoint" is invoked in
background thread but sometimes still in UI thread. It's better put it
into background thread because it access database.

In EditWaypointActivity.java, you invoke "loadWaypoint" in a
background thread at line 278. However, at line 92 in
CompassActivity.java, it's called by "onCreate" method in UI
thread. Also, "WaypointPopupFragment.init" calls it at line 62 and
it's eventually called by "AbstractDialogFragment.onResume".

Why don't you also put all invocations to "DataStore.loadWaypoint" into background
thread? Is there any specific reason?

Thanks,
Yu

**Comment by Lineflyer** [comment]
Can anyone say, if this old issue is still relevant?

**Comment by fm-sys** [comment]
The behavior has not been changed over the years, anyway we have database accesses via the UI tread also at other places in our code. In my opinion, this is not too bad, as long as no negative delays are noticeable for the user. Since there has been no feedback on this topic for the last 6 years, I assume that we currently have much more important things to do.

If someone disagrees, feel free to reopen...
