### ISSUE TITLE
No GPS in some views

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#4575]
- Google Play Services disabled
- Powersave mode disabled

High precision is only used in some views like map, list, cache details but not in cache description, logs, etc. That is bad e.g. when you are deep in the woods and waiting for a GPS fix.

**Comment by samueltardieu** [comment]
This looks more like a feature request than a bug. Precise location is not needed in cache description and logs, and what you are asking is a way of always keeping the GPS on.

**Comment by SammysHP** [comment]
I thought that this behavior is coupled with the powersave mode.

**Comment by Lineflyer** [comment]
I mentioned that on IRC quite some time ago.
It was AFAIR introduced by @samueltardieu some time ago....independently of the power save setting.

IMHO we could couple that with the powersave setting (e.g. instead of another setting "Keep GPS always on")

**Comment by vinceo** [comment]
Hello, I'm experiencing this problem too and I'd like to add some observations to help on the subject.
I noticed this behaviour of the app in the last couple of months and if not a bug it is still a problem in my opinion. While caching, I often have to open the description to read the hint, browse previous logs or see the spoiler picture. Back on the map screen, the phone has to get a gps fix again which can take several minutes in some situations. This is annoying because it obviously happens when I'm near the cache site and when I need precision the most. That's even worse when I have entered a narrow valley or a tree covered area in the meantime, places where I really don't want to lose gps signal.
I am absolutely sure that in previous versions of the app, the gps signal was only lost when opening the pictures in full screen mode (either those from the description or from the logs), which is totally understandable.
Is there such a thing as "Keep GPS always on" setting ? That would permanently solve that problem.
Thanks a lot !

**Comment by Lineflyer** [comment]
@vinceo 
I am also in favor of such kind of a setting, however I was told by others in the past here that it is some effort to implement it.
You could try this app or a similar one to solve your problem for now: 
https://play.google.com/store/apps/details?id=uk.co.kissandriod.keepmygpsalive
(Not tested)

**Comment by Lineflyer** [comment]
We keep getting requests like this on support. So having a feature to "keep GPS on" would be highly appreciated as there seem to be devices out there which are not really good in re-obtaining a GPS fix.

---
 
Hi,
 
I love c:geo and it is much better than official app.
 
I am missing only one feature: to save battery I switch off screen as often as possible and this will always deactivate GPS. When I switch screen on again, c:geo needs some time to reactivate GPS and to get a stable signal.
 
In other apps (for example: Locus Map) there is an option not to deactivate GPS, when app is minimized or screen switched off.
 
Is there a similar option in c:geo? If no is there a chance to get it in future releases?
 
Thanks for your good app.
 
Regards
xxx

---

**Comment by SammysHP** [comment]
I think this is another issue: Keeping GPS on while in standby. This issue is about having GPS enabled in every screen in c:geo.

**Comment by Lineflyer** [comment]
Then let me suggest the following (similar to what was already mentioned above).

1. Use the existing "Power Saving Mode" setting and couplee it with the switch off of GPS in some windows, i.e. if "Power Saving" is not active GPS should stay on as long as the app is active on all screens

2. Introduce a new setting to keep GPS running as long as c:geo is active also if the screen is locked.

That would be a clear and understandable solution IMO.

**Comment by samueltardieu** [comment]
I like solution 1.

**Comment by samueltardieu** [comment]
@Lineflyer Please test if it does what you want. If needed, this can be retrofitted easily onto release as it was developed on top of it.

**Comment by Lineflyer** [comment]
Sure. But I think it should stay on master to allow as it is no bugfix. Anyway I will test if it works as expected.

By the way:
I did not see both items listed in my posting as different proposals but to have both.
However the second option is another issue (which we might have listed already somewhere...will take a look). So we can consider this issue done after testing.

**Comment by Lineflyer** [comment]
Tested and OK with 2015.04.11-NB and 2015.04.12-NB.
I suggest to leave it on master to give more time for testing.

**Comment by kirchwitz** [comment]
Just came across this bug, and maybe the proper solution is to have some kind of timer. There's no point in having GPS always on as this drains the battery very quickly. But neither does it make sense to turn off GPS very aggressively because this wastes a lot of energy (and time) to wait for a GPS fix again. It's the wrong way to do it, both of them.

Best thing would be a timer (duration can be configured by the user) to keep the GPS on after he has left the map. This way it won't hurt to have a quick look at the hint, but if somebody spends several minutes reading the description and logs he surely doesn't need GPS. (Same thing if the user leaves the app. Chances are high that he just comes back in a couple of seconds.)
