### ISSUE TITLE
Sort order lost if negative sorting is active

### ISSUE THREAD

**Issue by adamchater** [cgeo/cgeo#4580]
When viewing my list of stored caches, if I select to sort by "Date stored on device" this works, and shows the oldest stored cache at the top of the list.

If I then choose the menu option again to sort by "Date stored on device" the list is reversed, so that the most recently stored cache as as the top of the list (which I find more useful).

However, if I then drop a cache from this list, the sort order is lost - specifically, the caches are sorted again with the oldest stored cache at the top of the list.

Please allow my preference of having the most recently stored cache at the top of the list to be remembered.

**Comment by Lineflyer** [comment]
Confirmed with 2015.01.06-RC1.
Interestingly (as described in the original post) the sorting is not reset to default (which would be "Sort by Distance") but just goes back one iteration ("Sort by stored date - oldest cache first"),

If the sorting has only one iteration the sorting remains as it should, i.e. it only happens on "negated" sortings.

**Comment by Lineflyer** [comment]
Assigning for Test

**Comment by Lineflyer** [comment]
This bug seems still existing with 2015.05.26-NB-f67a78d. 
@kumy: Your fix does not seem to work.

Scenario:
- Open list
- Select Sort - Save date
- Select Sort - Save date again 
- Remember the sorting of the list (newest saved date on top)
- Open a cache on the list
- Delete it
- Return to the list by pressing back

Result:
- List is sorted by oldest date on top (first iteration of sorting) but not as before

**Comment by kumy** [comment]
Ok, I was able to reproduce...
