### ISSUE TITLE
New splash

### ISSUE THREAD

**Issue by tomerengel** [cgeo/cgeo#4597]
Hey, playing with new UI as we discussed few weeks ago, this is a new splash screen (new Icons, new white template, all big icons) - what do you all think?

![splash](https://cloud.githubusercontent.com/assets/9966732/5653959/b505ef06-9673-11e4-8b29-b61838994113.JPG)

**Comment by Lineflyer** [comment]
From IRC:
```
[23:04] <Lineflyer> My personal opinion: I don't think a white background looks nice here...except we adopt all other styles as well.   The icons are too big for my personal preference and redesigning this part would offer also the possiblity to have new menu items at the same time....So the screen should be in a way that more icons fit.  
[23:04] <Lineflyer> But dont consider this to be rude...just a first impression
```

**Comment by tomerengel** [comment]
Sure, this is a first iteration , ;let's hear people out and see what they think. I think that the existing style should be replaced( with the black colors al together), quite a lot of work , I know, but we can start playing,no?

**Comment by tomerengel** [comment]
Now with lines to seperate the buttons, clearer now
![spash2](https://cloud.githubusercontent.com/assets/9966732/5654329/e0d29c26-9676-11e4-8462-68204e21ddbc.JPG)

**Comment by TravelingGeek** [comment]
I like the white, but they do seem pretty big.  Do they scale to the size
of the screen? That would be crazy big on tablets.

For what it's worth, I've always found filter icon and phrase 'all caches'
to be ackward.    If you don't know what the icon is representing, it is
not intuitive what 'all caches' mean.   Although admittedly overused, I
think a funnel icon would serve better here... or something else perhaps.

+1 for the lines.

**Comment by tomerengel** [comment]
Few points
1. Didn't think of tablets, I have 5.5" and the sizes are ok. Thinking of tablets - the current screen now looks too tiny in my opinion on a 8"+ screen. I need to look at other apps on tablets to see what they did. 
2. I would agree with removing the texts , I like clean UI which is self explanatory. 
3. In the next iteration ill replace this with a filter and remove the text - see how those play out.

**Comment by SammysHP** [comment]
Some quick remarks from phone:

- style of icons doesn't match each other
- icons too big
- too few colors
- not enough other GUI elements
- action bar?
- Login status?

My proposal: What does the user expect to see on start? I'd try a short summary and important functions and the navigation to all functions in a drawer menu on the left side (what's the name of this thing again?).

**Comment by tomerengel** [comment]
hey all;
good comments so far, and I see a pattern - so let me clarifyI
I didnt drew up a concept for the entire screen or app only the main screen to play around with new style of colors ,new style of icons and new style of experience. I wanted to "port" the existing screen into a different one.

So before ill continue to play with it, lets decide on a direction I should follow and there are two 
1. Draw down a general all-app concept and run it by you all - general app concept is how will the new app look and feel (colors, menus etc) - but no details
2. take a single screen and completely work it - to include everything until we agree

I chose 2 as it was the most intuitive to me, although  usually we should have started with the app-concept.

what do you think should be our next steps? I would gladly run with them

**Comment by Lineflyer** [comment]
While to me approach 2 sounds more likely to be practical (because of limited ressources) we should invest at least invest a little time to have an agreement about the general goal (e.g. what design guideline to follow, colors, etc.).
SammysHP is right:
The action bar is missing and we once discussed that this sidebar (also forgot the name) is useful.

**Comment by SammysHP** [comment]
https://dl.dropboxusercontent.com/u/44720989/Neues%20Dokument%202_1.jpg

**Comment by samueltardieu** [comment]
I like @SammysHP proposal (with cards and burger menu).

**Comment by SammysHP** [comment]
Maybe we should place some often used shortcuts like Live Map, nearby caches and stored caches in an own card at the top (burger menu – is it still called so? – is an additional action for the user and on smaller screens status cards would fill the whole screen).

**Comment by ludoo0d0a** [comment]
In my opinion, dashboard is the best UI pattern !
The better user experience is "ready to play", and as I remember the first time I opened cgeo, I asked me : 4 icons, ok, BUT where should I first click to start ??

If you look evolutions of "guideline apps" suche google io app (or facebook), dashboard has been removed with evolution.
I think Material design should be implemented (and so a navigation drawer would help to switch activites)

2010
![2010](https://1.bp.blogspot.com/_uJSd5DrlOrg/TTxV5N4c1lI/AAAAAAAABOE/e85UBbLGlN4/s1600/io1.png)

2011
![2011](https://2.bp.blogspot.com/-9QFsHml9Nmo/TelCaI0LlwI/AAAAAAAABlU/m2s2gnILN68/s1600/io_phone.png)


Finally no more dashboard in 2014
https://play.google.com/store/apps/details?id=com.google.samples.apps.iosched

![2014](https://raw.githubusercontent.com/google/iosched/master/art/hero.png)

**Comment by Bananeweizen** [comment]
I'm rather sceptical about both suggestions (the big icons from the first post as well as the card based UI of @SammysHP). I'm a strong believer of "form follows function", which means that the user interaction and usability should strongly be favoured over "pure design". And that's why I would like to see an improvement in _productivity_ and _ease of use_ with a redesign, not just a different layout of the existing UI controls.

Simple example: Currently we do not use the empty space below our icons. I'm confident that most people would be happy if this showed the nearest caches, the last opened caches or something similar (as we discussed in other issues).

Regarding card based UI: This pattern doesn't fit here. Card based UIs are meant to present _different_ cards based on context (date, time, location, previous searches) and cards are meant to be a temporary part of the UI (and can easily be removed by the user).

The navigation drawer behind the burger menu is independent of card UIs, and I also favor this one very much, as it allows faster navigation between very different nesting levels of the activity tree.

**Comment by tomerengel** [comment]
Hey, would like to bring this discussion back to life

@Bananeweizen has a point to increase productivity. for me as a user 90% of the useage is using the *Live Map* function. I am getting into a new place, my daghuter or me think to do some geocaching and I open the live map. IF I was lucky enough I cached some caches when I had a cell phone signal/wifi.

How about a "small" change tilting toards usability and more modern Android design is to open the CGeo on livemap and have a sidebar with the rest of the operations
Attached a very quick sketch
![14286170859120](https://cloud.githubusercontent.com/assets/9966732/7077957/de6169b8-dec9-11e4-8014-12280b1b2501.jpg)

Another option is to do a survery on Facebook to ask what is the most used activity to be the first one, but using the same design.

What do you all think?

**Comment by tomerengel** [comment]
Second iteration on the main design - now with search (and by this we eliminate the search activity).
![14286174819411](https://cloud.githubusercontent.com/assets/9966732/7078073/d513ee3e-deca-11e4-8a69-3c4f7d139f62.jpg)

**Comment by tomerengel** [comment]
Main screen:
![mainscreen](https://cloud.githubusercontent.com/assets/9966732/7078491/6db5671e-dece-11e4-8f3e-3495feacfa8a.jpg)

Menu:
![menu](https://cloud.githubusercontent.com/assets/9966732/7078501/8627c936-dece-11e4-8278-7e5c315a53d7.jpg)

**Comment by tomerengel** [comment]
And this is the search
![search](https://cloud.githubusercontent.com/assets/9966732/7079432/0e5ddb42-ded9-11e4-8494-aae8796c3f03.jpg)

**Comment by tomerengel** [comment]
One more note (last one :) ). We can do this in an iterative manner, first do the search (replace the search activity/intent with the newer search. then continue on.

**Comment by Lineflyer** [comment]
>  for me as a user 90% of the useage is using the Live Map function. I am getting into a new place, my daghuter or me think to do some geocaching and I open the live map. IF I was lucky enough I cached some caches when I had a cell phone signal/wifi.

I wouldn't go with starting directly at the live map.
E.g. my usecase is 90% saved lists and nearby search, I rarely use the live map.

I would rather suggest to start with the same menu items of the main menu we currently have but just give them a new design for the start. Also the list of active connectors and their status should not be missing.
Changes on that level should not be so drastic, that users won't find what they are used to.

We could for example start with this side bar (how was this think called) as suggested by @SammysHP before.

**Comment by tomerengel** [comment]
@Lineflyer  - fair enough with the first screen, Maybe I am the 10% (and everyone else is using the saved lists or nearby) - maybe we can have a FB survey for that?

Also, @SammysHP design has the search on-top and side-bar on the left --> we could start from those indeed.

**Comment by ultrafez** [comment]
Perhaps the user should be able to choose which screen they would like to see first when they start the app - I personally 95% of the time use the Live Map, and so for me that would be my default. The results of a survey on Facebook would allow a sensible default first page to be chosen.

**Comment by SammysHP** [comment]
Today I asked myself: What do I need most often? What do I want to see after starting c:geo?

We already discussed to (kind of) remove the home screen (dashboard) of c:geo and right start into an activity (with all activities on the same level, switching via burger menu). While I still like that approach, it might not include the details or functions I want to see.

Here is another sketch:

![cgeo-startscreen](https://cloud.githubusercontent.com/assets/922874/16411240/610f1be2-3d26-11e6-8811-c708b483a885.jpg)

It has buttons (in the design of small cards) for the most used functions: nearby search and stored caches. On the bottom are similar small cards, one for each enabled connector with some stats and the possibility to shortcut into the preferences (replaces the status lines in our current design).

But the big change is a half-screen tile with a reduced version of a live map. The user cannot move or zoom the map (to be discussed), it is always centered at the current position. It includes a (maybe reduced) map menu and a button to open the full-sized live map.
This approach offers a better visualization of the current position and accuracy (currently both in our status line as text). The user *sees* where he is instead of reading numbers or letters (the name of a street usually is no help in an unknown area). It also provides quick access to the nearest cache (see #242).

What is missing: goto, full search, filter settings (are replaced in the future anyway). But that can be added easily.

**Comment by Lineflyer** [comment]
I can imagine a lot of options for a new design and I like the proposal above as well as a starting point. The most important question: Do we have someone onboard who is able and willing to start with such a redesign? If not: Should we ask the community if someone is able and willing to help us with UI changes?

**Comment by pribeiro42** [comment]
Just a quick question about @SammysHP sketch (which i very much like), how would the "50% screen-sized live map" function when on off-line mode (a mode i personally use if i'm in a remote / week signal / foreign country location) ?

**Comment by SammysHP** [comment]
It would show the data that is available: An offline map (or if not available: nothing) and stored caches. Same behavior as the current live map.

**Comment by fm-sys** [comment]
I would like to bring this rather old issue up again, in the context of a c:geo redesign. In the past (this thread) there was the idea of implementing a navigation drawer:
![grafik](https://user-images.githubusercontent.com/64581222/118525466-7f35ff80-b73f-11eb-8046-11cbd5a615ac.png)

But IMHO this is rather "old school" (e.g. Google is already removing the navigation drawer from their apps again) and needs at least two clicks for switching between the activities.

**Anyway, the worst thing at our current UI is IMHO the main activity. Do you know any other successful app which uses some kind of a "sub-launcher" like we do?** 

Nowadays, there is a bottom navigation bar component which is much more suitable (see YouTube or the official Geocaching app for example):

![grafik](https://user-images.githubusercontent.com/64581222/118525243-3f6f1800-b73f-11eb-83bb-37fd4aa66c5a.png)
They become more and more popular, as our mobile screens become larger and screen size isn't a problem anymore.

However, it can hold only **5 elements max**.

These would IMHO be:
- map
- lists
- ?
- ?
- more

This would require us to heavily light up our UI:
- trow away our global cache type filter (see #10637)
- notification system? Maybe as "real" Android notification?
- everything which we want to keep could be moved into the "more" screen...

@cgeo/team I think these are very important decisions which we need to do for our future. I think it doesn't really make sense to discuss all these things in an issue thread. Would this be something for our next dev meeting?
