### ISSUE TITLE
Mails returning to support address

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4623]
As I did not reach @mucek4 via IRC I post this here:

Currently a lot of mails are returned with "Relay access denied".
See inbox for details.

**Comment by mucek4** [comment]
For some reason my ISP no longer allows forwarding emails that are not from their domain. And cgeo.org is not. I have solved this problem now by setting my own server to forward emails. 
Google bloks all emails from my IP addres due to beeing marked as "dynamic" from my ISP. However it's dynamically assigned static ip.
