### ISSUE TITLE
Create release from release branch

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4696]
Due to #4693 and #4691 we should create a new release from the release branch, rather quickly. (And afterwards we should schedule a release from master for beginning of March).

**Comment by Lineflyer** [comment]
I can not help with testing and release this time as I am on vacation right now.
However releasing from release branch should be fine, as also current master looks stable to me.






Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: Bananeweizen <notifications@github.com> 
Datum:22.02.2015  18:27  (GMT+01:00) 
An: cgeo/cgeo <cgeo@noreply.github.com> 
Betreff: [cgeo] Create release from release branch (#4696) 

Due to #4693 and #4691 we should create a new release from the release branch, rather quickly. (And afterwards we should schedule a release from master for beginning of March).

**Comment by rsudev** [comment]
Today? Tomorrow? First an RC?

**Comment by Bananeweizen** [comment]
I'm fine with releasing as is. I might be unavailable big parts of this week, as I have an external consultant over at work and want to maximize the available time for that.

**Comment by samueltardieu** [comment]
I am on vacation this week, but I can create a release tonight if needed.

**Comment by rsudev** [comment]
New release built, smoke tested and uploaded.

**Comment by samueltardieu** [comment]
\o/

Thanks @rsudev.

**Comment by rsudev** [comment]
Notification sent, version tagged, closing here.
