### ISSUE TITLE
Sort by name automatically

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4707]
We are already have a mechanism which will sort lists containing only events by date automatically instead of by distance. I was wondering if we could similarly detect that all caches have a common prefix (i.e. belong to a series) and in that case sort by name by default.

Does anyone see a problem with that? If not, I may try implementing this.

**Comment by samueltardieu** [comment]
That's a good idea. What would define a common prefix? A minimum number of characters in common?

**Comment by Bananeweizen** [comment]
Yes. I'd go with at least 3 caches and at least 3 common characters using http://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#getCommonPrefix%28java.lang.String...%29. Experimentation may then change the number, but 3 characters would include typical abbreviations also, while being sufficiently large to not have random results, and 3 caches seems the smallest useful series.

**Comment by speedy-1702** [comment]
I would prefer to set the sort order per list and let c:geo store this per-list-setting.

**Comment by Bananeweizen** [comment]
Why so? I don't see any benefit for having a specific order on _every_ list. I rather imagine people being confused switching between their lists, as the default sorting by distance for every list except those containing only events is quite accepted.

**Comment by alan666notb** [comment]
I'd like to have a default sort setting that is initially applied to any list,
I prefer to see them sorted by name but have to select it every time I open a list.

**Comment by Lineflyer** [comment]
> I prefer to see them sorted by name but have to select it every time I open a list.

That is strange as your setting should be kept as long as c:geo is running. Can you check again please?

**Comment by alan666notb** [comment]
Yes, you're right, I just checked...
Once I set the sort type to "Name", it sticks if I change list or even exit cgeo and restart it.
But this is strange - it must revert at some point as I know I often have to reset the sort type to 'name', it always seems to be set to something else (Distance, I think) when I look.

--------------
Completely off topic: I've had cgeo stop working on me a few times since the last update. Last time it happened I quickly grabbed a catlog (phone is rooted) and posted it to the support Email but got no reply. Should I post it here, or what?
