### ISSUE TITLE
Toast when saving on back

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4792]
I like the new design of the edit waypoint activity. But I think some users may be confused if waypoints change, when using back (or up navigation). We should show a toast about the change, if the activity is not left using the explicit okay or cancel buttons.

**Comment by Lineflyer** [comment]
The question is if we should rather not save the changes if the back key is used. In the old design it was like that and I assume that this may lead to problems as users (like myself) are used to the back key for dropping the change instead of saving it.
Another possibility would be to ask the user whether he wants to cancel or save.

BTW:
Wouldn't this new control elemtens in the title bar be good for another showcase.

**Comment by rsudev** [comment]
My main driver for the change was to adapt to the behaviour of many other apps that I use with a similar interaction concept - save on back. Save what you did is IMO just the default expectation (and I can't count the number of times I had to enter stuff twice because I forgot how awkward c:geo behaves in this context).
Having a toast on save would be ok for me, but I wouldn't like a confirmation - it would IMO feel just another unecessary step.
WRT: showcase - yes definitely!

**Comment by SammysHP** [comment]
And changing coordinates by accident?

- Back and no changes: go back, don't store (of course), no toast
- Back and changes: Ask whether to store or discard the modifications

**Comment by rsudev** [comment]
How would you change coordinates 'by accident'? You have to call a dedicated dialog and do something there.
The showcase would IMO mainly be for existing users that know the previous behaviour. I think, new users would understand the new implementation directly.

**Comment by Lineflyer** [comment]
I accidently opened a new issue #4985 for that. Lets continue there.
