### ISSUE TITLE
Should GK lookup be active by default?

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#4796]
As discussed on IRC, should we activate GK lookup feature by default ?

"Question: Would it be better to switch "Geokrety" off by default to
1. avoid a state where requests are done but no login is stored
2. avoid additional network requests which the user might not want to have?
[...]"

"Looking at the fact that a huge percentage of users are in US (Where geokrets might be not so well known/used)..."
"speaking of the traffic: Typical weekend case is 15k up to 20k of users online."
"lookup of geokreties will work without that [feature] being active"

**Comment by SammysHP** [comment]
Disable it by default. AFAIK all services are disabled by default until you enable them and input your credentials. An exception might by gc.com, but c:geo tries to notify the user that he should configure the service.

**Comment by Bananeweizen** [comment]
Voting for disabled, exactly because of the reasons mentioned by @SammysHP .

**Comment by kumy** [comment]
I'll include that with #4778 :)

**Comment by Lineflyer** [comment]
Idea for this:
Looking at #4779 we currently have a wrong strategy of server communication at this point, so a rework is needed and planned anyway.
Couldn't we disable the feature by default but still do a request but not when the user opens a gc cache but as soon as he opens the inventory of the gc-cache so that the GKs in this cache will also be shown?

Doing so could make users aware of that new feature!

If they try using it they will get the (already implemented) message, that the service needs to be configured before it can be used.

**Comment by samueltardieu** [comment]
The inventory page is there only when a cache has trackables. We know that it has trackables because we have this information. Chicken and egg problem.

I don't think the extra request is a problem, as long as it is done in parallel with others, we should not notice any significant delay.

**Comment by kumy** [comment]
If I understand correctly, lookup would be always done (in parallel mode ; RxJava;)), so cache show GK.
When the user want to log a GK, it'll be redirected to the configuration page to enter his credentials, like for GC on first application launch ?

**Comment by samueltardieu** [comment]
That could do the job.
