### ISSUE TITLE
excludeMine parameter is always false

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4818]
Analysis by IntelliJ IDEA shows that the `excludeMine` parameter in `SearchResult#filterSearchResults` is always `false`.

This is likely a bug. If this is not, the parameter can be removed and the code can be simplified.

**Comment by Bananeweizen** [comment]
I believe this is actually correct. I've looked at callers of Settings.isExcludeMyCaches(). That's used when constructing the URLs for text based searches and for map based searches, so it seems filtering the result of the requests really is not necessary.
And the live map seems to do its own things with collections of caches, instead of using SearchResult.

**Comment by Lineflyer** [comment]
Can this be in any conjunction with the issue, that waypoints of owned caches are never hidden on the map?
