### ISSUE TITLE
Tweet does not contain coordinates

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4819]
It appears that `Twitter.postTweet` gets always called with a `coords` parameter as `null` (no coordinates posted with the tweet).

This is likely to be consistent with our privacy policy and our recently obtained ratings on Google Play Store.

If there are no objections, I propose to keep the situation as-is and remove the useless `coords` parameter rather than implement the location-aware Twitter posting.

**Comment by SammysHP** [comment]
The reason for using Twitter is to notify other people of your current activity. We should not use the current location, but the cache coordinates of course (someone might log later or near the final location).

**Comment by samueltardieu** [comment]
So is that an objection to making the code right and a will to replace it by a feature request?

Also, what coordinates would you post for a mystery cache? Or a premium-member only cache?

**Comment by SammysHP** [comment]
I don't really care as I do not use this. But IMHO users who share their finds via Twitter might like to share the location of the cache or their own location as well. The latter is not easy because we don't know when and where the user logs his find (so it might be at home) or it discloses the final coordinates.

I think a good approach without too much effort would be to include the listing coordinates of the cache. Too be safe (premium member only, corrected coordinates) this should exclude unknown, multi and pmo caches.

**Comment by samueltardieu** [comment]
On the other hand, the coordinates will be listed as soon as readers follow the cache link, and we would not have to try to guess if and where users want us to post their location.

**Comment by Lineflyer** [comment]
I would not send any coordinates for tweets neither current one, nor cache corrds.
I suggest to leave it like it is now.
