### ISSUE TITLE
Warn when sending log and same log text exists

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4831]
When sending a log there should be a confirmation if another log with the same text exists for the cache. I just posted a duplicate log, where my other log existed locally.

**Comment by rsudev** [comment]
I must admit that I do not fully get the use case from your description...

**Comment by Lineflyer** [comment]
You mean a warning in the case the cache already has the status FOUND and you try to send a found log ?

**Comment by samueltardieu** [comment]
I second @bananeweizen proposal. Since log posting is somewhat unreliable
on flaky networks, we get complaints regularly.

**Comment by Bananeweizen** [comment]
Use case is: Store log offline yesterday. Send log today. Refresh. Don't notice your log was added (but somewhere below, because it is from yesterday). Send log again. :(

**Comment by Lineflyer** [comment]
So it is like I posted above... when the status if found just ask the user in case he wants to to send another found log (should not be done for other log types)

Just to mention it:
It wont help on the situation we had recently due to the website change....maybe this i
is another issue:
As you know the login failed due to site changes...but hundreds of users still tried to send a log which was reported as failed in c:geo but it was posted in fact. So users tried again and again and ...

While browsing caches today I have seen quite some of these double posted logs most probably from c:geo.
Mabe we should investigate the reason for this separately and try to solve it somehow.

**Comment by rsudev** [comment]
@Lineflyer I think @Bananeweizen meant it slightly different - really prevent accidental double posting, regardless of logtype (it can be as embarrassing for 'needs maintenance' as for 'found').
If this can help to prevent the situation you describe, or issues with flaky networks, is another story.

**Comment by Lineflyer** [comment]
What I wanted to express: A confirmation for a note or a NM for a cache which I already found should need no confirmation.

**Comment by Bananeweizen** [comment]
@Lineflyer That is totally not meant here. I really talk about sending _the exact same text_ again, that already exists in another locally stored log of the current user.

However, your suggestion of generally confirming a second _found_ log on the same cache also sounds reasonable to me, as most cachers really don't log a find again (although this is possible, and I already did that once).

**Comment by Lineflyer** [comment]
As in the meantime duplicate found logs are disallowed and also trying to do so will result in a warning or error (i.e. "Logtype was changed" toast) this requested feature seems obsolete.
