### ISSUE TITLE
`GeoKretyConnector` status should be displayed on main activity?

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#4840]
What do you think about showing the status of the `GeoKretyConnector` in the main Activity?

It could be displayed when the user has enabled _and_ 'authorized' c:geo with geokrety.org.

```
geocaching.com . <user> (<#cache>) . Login _status_
geokrety.org . <user> . Login _status_
```

**Comment by SammysHP** [comment]
And Twitter? And GCvote? And…

**Comment by Lineflyer** [comment]
I would suggest to limit the main screen display only for connectors to caching platforms but not for additional services like GK, GCVote, etc.

**Comment by Bananeweizen** [comment]
What is the benefit for the user? When discussing possible features, one should always talk about the benefit and the problem to be solved. Otherwise developers will add "cool stuff" all the time that no user actually requested and that only increases the complexity and risk of failures.

"As a <role>, I want <goal/desire> so that <benefit>"

see http://en.wikipedia.org/wiki/User_story

**Comment by Lineflyer** [comment]
So we should leave the main screen for showing the status of the geocaching platform connectors.
Some idea like this could be realized in a new main menu item dedicated for trackables like suggested in #420 and #4841
