### ISSUE TITLE
Optionally keep GPS always on

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4879]
Recently the disabling of GPS in some views was modified to be applied only in "Low power mode" to allow users to keep a GPS fix as long as c:geo is running (as it might take some time depending on the device to re-fix GPS).

Still quite some users ask for keeping the GPS also if:
1. Screen is locked
2. c:geo is active in the background

So this is feature request (I checked but did not find a matching issue) to "keep the GPS-lights on while c:geo is started" as an additional option in the System settings.

**Comment by samueltardieu** [comment]
I'd rather have the user use a dedicated application that keeps the GPS always on rather than have cgeo do this. This is not an appropriate way to manage resources, and we will face complaints from people who turned this on by mistake just to satisfy a few of them with low-end devices.

Moreover, "active in the background" has little meaning in the Android world, and users won't necessarily define it the same way.

Why not add a pointer to an application such as https://play.google.com/store/apps/details?id=com.silentlexx.gpslock in the FAQ?

**Comment by Lineflyer** [comment]
Yes, that is a good compromise IMO.
I will add a FAQ entry on the new page.

**Comment by Bananeweizen** [comment]
should we also put it into the helpers activity?
