### ISSUE TITLE
Remove trail feature

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4886]
I suggest that we remove the trail feature due to severe limitations:
- It doesn't work correctly, if the screen is off.
- It has a restricted buffer size (so it cannot track multiple hours).
- It looses the trail when reopening the map.

There are many more explicit tracking apps. E.g. I have Endomondo tracking my geocaching walkings through the forest.

**Comment by Lineflyer** [comment]
Despite the limitations I would not remove that long existing feature. I personally deem it useful to see where I came from.
If we remove that I guess we will get many complaints (and loose a feature other geocaching apps have).

**Comment by rsudev** [comment]
I am also in favour of keeping it. Of course is it no replacement for a real tracking app (luckily, so it doesn't require as much power), but still a helper for quicker orientation when doing multies or letterboxes (for me).

**Comment by mucek4** [comment]
I also suggest keep it. It's annoying but when you need it it's there. We could write into buffer even when it's off. So when you enable it it shows history already.
And maybe wiite it dotted when screen was off.

**Comment by yellowduck** [comment]
I also vote to keep it, as I find it very useful. Even better would be the ability to save it.

**Comment by SammysHP** [comment]
An easy solution would be to store the track in a GPX in real time and read the last n points when starting the map activity. Also the user would be able to "export" the track (simply take the GPX) or clear it (delete the GPX).

**Comment by djtooley** [comment]
I visited this site today specifically to see if there was talk about the tracking feature.

A friend showed me his tracker (another app) and the data it gave was really nice. I especially liked the graph of altitude over time.

I use the trail feature all the time. It's especially useful when you can't find a cache... it gives you an indication of what area you've been searching, which may cause you to realize which areas that you have not been searching.  I've also occasionally posted the "look I searched a LOT" humorous screen capture.

I suggest, instead, upgrading the feature to have full and strong tracking ability. I recognize that this is a battery drain, and I'd frequently not want that. But if it's a capability that I could turn on, I would certainly use it frequently.  (and I've been known to carry a spare battery with me...)

**Comment by SammysHP** [comment]
Please vote thumbs up or down on the first post.

**Comment by Lineflyer** [comment]
CrossCopy from #6558 

My personal opinion on tracking features in c:geo:
Since a year I am out for geocaching more often by hiking a long trail or a bike tour.
For this I personally missed the possibilty of c:geo to basically support tracks. A significant number of hiking/biking (multi)caches provide users a GPX track as assistance.
I had to use another app for the track but in parallel contantly switch to c:geo to look for the next stage onroad or even for other caches along the track.

So in my case the trail feature is not so important but importing and showing a track would be.
However if we would support showing imported tracks (which I would really like) it may make sense also showing the way the user already made.

**Comment by yellowduck** [comment]
I stand by my original comment. I find this a useful feature.

**Comment by SammysHP** [comment]
There is a majority who wants to keep this feature, thus closing.
