### ISSUE TITLE
Problem GPS Coordinates

### ISSUE THREAD

**Issue by BraconneCharente** [cgeo/cgeo#4918]
The GPS coordinates in the details pages is note good. In the description is the right one but when you try to navigate or look on google map, with the GPS coordinates you had locked, it's wrong.

This problem happened in the geocaching place made by Braconne Charente in the web site https://www.geocaching.com/

Can you fixe it?

Thank you

**Comment by rsudev** [comment]
Hi, could you please give more details to what your issue is about?
* What geocache are you talking about (please name the gc-code)?
* Do I get it correctly, that the coordinates you see in c:geo on the details of this cache are different than the ones on the website, or are you just seeing them placed wrongly on the map? If the first is true, could you provide a screenshot?
* Which version of c:geo are you using, which version of Android and which device (you can get that information easily inside c:geo from the main screen: Menu - about c:geo - swipe to the system tab - copy the information - paste it here.

**Comment by Lineflyer** [comment]
Please also make sure that:
- You are logged in with c:geo
- You dont try to navigate to a cache shown with orange circle directly from the live map

**Comment by Lineflyer** [comment]
Closing due to lack of feedback.

@BraconneCharente 
Is it possible that you used an external navigation app (e.g. Radar) and noticed slightly different coordinates as target coordinates?
If this is the case please refer to here to get the reason for it: https://github.com/cgeo/cgeo/issues/542

**Comment by BraconneCharente** [comment]
Hi, 

I am really sorry, I don't give you the feedback and answer. I forget to response at your mail, excuse me. 
I made a doc for give you the good coordonates and the coord of reference in the website geocaching.com. 
I hope it is not to late. 

Really sorry 

Kind regards 

Braconne et Charente 
----- Mail original -----

De: "Lars" <notifications@github.com> 
À: "cgeo/cgeo" <cgeo@noreply.github.com> 
Cc: "BraconneCharente" <geocaching@braconne-charente.fr> 
Envoyé: Lundi 18 Mai 2015 11:26:11 
Objet: Re: [cgeo] Problem GPS Coordinates (#4918) 



Closed #4918 .

**Comment by SammysHP** [comment]
It's not possible to attach files via mail. Please upload the file somewhere else and share the link.
