### ISSUE TITLE
Separate DB file Directory from Cache Directory

### ISSUE THREAD

**Issue by marco-dev** [cgeo/cgeo#4964]
In order to start over with #4957 we have to separate db file path from cache path.

**Comment by SammysHP** [comment]
Can you explain why it is not separated currently? The database is in `/data/data/cgeo.geocaching/database`, cache directory is `/sdcard/.cgeo`.

**Comment by rsudev** [comment]
It is not separated in the case you use the database on sdcard feature.
I am not sure if this separation is really a precondition for #4957, but could make the implementation easier and less risky.

**Comment by Lineflyer** [comment]
We could here just remove that option to store th DB on SD with the next release and just move the DB back to  `/data/data/cgeo.geocaching/database`.

As @rsudev mentioned this would make all subsequent steps easier and less risky.
There is however a risk that moving the DB back might fail for some users (if the internal storage is full). 

I can also imagine another approach here:
If the user has selected to store the DB on SD we could just migrate/move it to the target folder (i.e. the real SD instead of `/sdcard/.cgeo` in a first step. How about that?=

**Comment by marco-dev** [comment]
I would suggest:
* if DB is at /data/data/cgeo.geocaching/database keep it there
* if DB is at (external dir)/.cgeo move it to (external dir)/cgeo/database

Just to make it for sure: should this change to "cgeo" subdir without a leading dot?

**Comment by SammysHP** [comment]
> There is however a risk that moving the DB back might fail for some users (if the internal storage is full).

Usually people enable that option for a reason…

**Comment by Lineflyer** [comment]
As we just releases we could now get going with this.

Despite the comments IMHO there might be no other easy way as to remove the option to have the DB on SD with the next version to have clear starting conditions.

My opinion:
While the DB might be big for users with a lot of caches stored, still the `/.cgeo` will be even bigger and thats what we want to solve.


Another comment:

> if DB is at (external dir)/.cgeo move it to (external dir)/cgeo/database

That I would not deem meaningful. I would get it back to `/data/data/cgeo.geocaching/database` in any case so that for all users the DB is at the same location and will always stay there for the future.

**Comment by rsudev** [comment]
I tend to strongly disagree here. I don't really see a need to remove this feature, which makes c:geo also usable for a number of people (and I am not sure if the number overall is that much smaller than those in *need* of the external sd-card feature).
I think the suggestion by @marco-dev is valid and can be implemented at least as robust as the move back to appdatastorage.

**Comment by marco-dev** [comment]
I also disagree. We are able to handle this:

**Status Quo:**
- db in appstorage /data/data/cgeo.geocaching/database (default)
- db on external <externalDir>/.cgeo

**Suggestion:**
- db in appstorage /data/data/cgeo.geocaching/database (default)
- db on external <externalDir>/**cgeo/database**

I would choose a cgeo dir without leading dot to make it visible.
**Any votes against using a directory without dot?**

**Update**
if dbOnSd is true
 - close db file (is it already open at update time?)
 - copy db file to new location
 - open db file
 - remove db file from old location

**Anything I forgot?**

**Comment by Lineflyer** [comment]
According to what @rsudev wrote it seems to make sense to still have the option to kepp the 'dbOnSd' function itself.  So your proposal is very good.

And yes: Without dot... as our target design might be, that those files stored there should be accessible by the user without a problem lateron.
(e.g. /cgeo/gpxexport , cgeo/gpximport, ...)

**Comment by marco-dev** [comment]
I would like to simplify this directory stuff and hide it in LocalStorage class.

- LocalStorage.getCacheDirectory()
- LocalStorage.getBackupDirectory()
- LocalStorage.getDbDirectory()

No other class should invest time on handle with external directories.
Also choices (of external dirs for cache) or defaults should be defined here.

**Comment by marco-dev** [comment]
- LocalStorage.getCacheDirectoryChoice()
- LocalStorage.getCacheDirectoryDefault()
- LocalStorage.getDbDirectoryDefault()
- LocalStorage.getDbDirectoryOnSd()

**Comment by Cappa-d** [comment]
Any news in this area? Was just recently facing the memory problem with internal vs. external SD Card again so I went checking here...

**Comment by marco-dev** [comment]
I owned a smartphone with Android 5.1 so I should be able to test things now.

I also know now that sd card usage is not transparent at all. My new phone has sdcard0 and sdcard1 both handled the same way.

Hopefully I will have some more time next week.

**Comment by Cappa-d** [comment]
If you need any testing support feel free to contact me. Still some time until I upgrade my phone but currently running Samsung S4 mini with Android 4.4.2 installed...

**Comment by mrummuka** [comment]
First, apologies, if this is a wrong forum to post my concerns/problems, but I think I found a new and yet unnoted 'feature' related to cgeo db location with A5.1. 

I suspect that w/ Android 5.1 the cgeo default location is no longer the best option as I believe it cannot be accessed any longer to enable e.g. backing up database file to PC manually.

What happened to me was since Xperia Z1c 5.1.x update, my phone was getting slower and slower so I decided to do a factory reset. Before this I backed up everything I could either manually (via USB) or by using apps built-in features. After f/w reset and reinstalling apps, I noted that I can no longer find .cgeo directory from anywhere. Even if I do a database backup from cgeo (first store one cache, then create a backup), cgeo shows me the default location (/storage/emulated/0/.cgeo (default)) and informs it succesfully backed up its database,but the location cannot be seen neither through USB/PC nor using Filecommander. This puts me into a difficult position of not being able to restore a cgeo database backed up from my device before factory reset. 

My guess of what could have happened, is that since the Z1c came originally w/ Android 4.x and I've made upgrade w/o ever resetting the phone so far, perhaps the Android hardened the security inbetween the versions, but with upgrades it never decreased the permissions of the directories created by applications in previous version to avoid problems. Could someone with brand new A5.1 device verify are they able to access the location where c:geo puts its DB after backing it up either through USB or through Android file manager? As if not, then IMO cgeo really needs an option for backing up/restoring the DB from cloud services (or at least I need a method to get my old backup contents back to cgeo somehow). Another option is that I'm totally chasing ghosts here and there is something really simple that I'm just missing..

**Comment by rsudev** [comment]
This is the right place to report issues with c:geo even though it is not a forum :)
The problem you are likely facing is, that folders startign with a '.' are considered 'hidden' under most unix-like operating systems (a class to which Android belongs as well. Therefore file managers normally hide those folders. Regarding the missing visibilty in MTP (when connecting the phone through USB) I also was not yet able to find out, which folders are visible and which not (and there has been inconsistencies at least on all Sony Xperia devices I had in hand even on older Android versions and these inconsistencies were also visible on unsuspicious folders without dots or spaces or any other special characters).
For my file-managing needs I use Ghost Commander, which showed me and accessed the .cgeo folder on all devices I had in hand, which also were a Z1c, first with 4.4.4 and (just today) upgraded to 5.1.
Please report back whether this works for you.

**Comment by mrummuka** [comment]
Hmm. Yep, I thought directories beginning with "." where the cause for this problem, but previously they had been visible both using the file commander and the MTP/USB. 
Interestingly, despite the fact that FileCommander is preinstalled in Sony (and at least to me seems to have higher privileges as it can write to whole SD card) and it did work previously, now it cannot see the directories beginning with "." (as in .cgeo), while the Ghost Commander that you mentioned (which cannot write to all directories in SD card), *is* able to see ".cgeo" directory on internal memory. Therefore, now with GC, I managed to copy the backed up cgeo DB back to the location cgeo expects it and succesfully restore the database. Therefore, thank you very much for the help, it seems this was a user issue after all.

**Comment by Lineflyer** [comment]
@marco-dev 
> I owned a smartphone with Android 5.1 so I should be able to test things now.
I also know now that sd card usage is not transparent at all. My new phone has sdcard0 and sdcard1 both handled the same way.

So it splits the external SD into two paths or is the external SD yet another directory?
Which device is it?

Did you already check what dirs are returned if you request the internal and external storage paths in programming?

**Comment by marco-dev** [comment]
Sorry for delay. I have a Mlais MX Base now. 

The strange configuration is:
  /storage/sdcard0 = /mnt/sdcard = external sdcard (with cgeo)
 / storage/sdcard1 = /mnt/sdcard2 = emulated sdcard

Somehow it seems like Android mixed up the mounts. Cool thing: if the /mnt/sdcard is full I can copy the content to a different, bigger one and go on. However, the performance will be bad. If it breaks, all .cgeo data will be lost including the backups.

So however we think about sdcard - internal or external - on Lollipop we have to think different.

We should be able to choose the

**Comment by rsudev** [comment]
This looks like a pecularity of the specific device, as my Xperia Z1 (Android 5.1 currently) has the more expected pattern of matching /storage/sdcard to the internal and /storage/sdcard1 to the external memory.
Regarding the write capabilities, I have the impression that with Lollipop the landscape is very fragmented. Some devices/manufacturers choose to restore write capabilities to the external sdcard, while other stuck to the Kitkat model.
TitaniumBackup (as another sample app that allows selection of a data directory) has the semantics, that you can select any (readable) directory and if you select one, it is checked for the possibility to write there before taking this selection as the new target directory. This relieves from the necessity to always check all directories up-front for write-ability.

**Comment by Lineflyer** [comment]
For the Samsung Galaxy S4 on Lollipop it looks like:

/storage/emulated/0/  -> internal SD (where `/.cgeo/` is located)
/storage/extSDcard -> the real external SD

However if we would manage to stick to <Context.getExternalCacheDirs()>/ for optionally saving cache data on external card we should be on the save side.
See: https://github.com/cgeo/cgeo/wiki/Target-disk-usage-structure

**Comment by pstorch** [comment]
This is obsolete now
