### ISSUE TITLE
Waypoints of disabled caches not shown as disabled on map

### ISSUE THREAD

**Issue by koem** [cgeo/cgeo#5008]
When a cache is disabled (grey backgnd in map) then the either

a) waypoints should have a grey background, too. Or
b) should not be displayed at all

What do you think? a) or b)?

Related to that: if you click on a waypoint of a disabled cache, then the little window with the waypoint short details & cache short details appears. Here the title of the cache should be striked thru but isn't (see screenshot).

K

![screenshot_2015-06-05-13-00-04](https://cloud.githubusercontent.com/assets/922495/8000316/9289ba2e-0b8b-11e5-8944-a4c97a12fa95.png)

**Comment by samueltardieu** [comment]
I'd be in favor of (b) unless the cache is the one explicitly shown on the map in which case I could prefer (a).

**Comment by Lineflyer** [comment]
Same as @samueltardieu wrote.

**Comment by SamuelPlentz** [comment]
IMO it should be related to issue #2558.

**Comment by Lineflyer** [comment]
@SamuelPlentz 
No, not really.
This one is about the fact that waypoints of disabled caches do not give the information that the parent cache is disabled (but it is shown intentionally on the map) whereas the other issues deals with hidden caches where their waypoints are still being displayed.

**Comment by SamuelPlentz** [comment]
I once looked into implementation details of #2558. IMO they should be technically related. The problem for both issues is that a waypoint has no direct access to the according cache. (AFAIR)

**Comment by moving-bits** [comment]
I would prefer option a, as frequently a disabled cache is still accessible. (And not displaying disabled or archived caches at all can be easily done using the map quick settings popup.)

Regarding the cache info not being available: Since the addition of map markers being shown also on waypoints, the cache info is available.

I'll create a PR for it, but wait for merging of #9799 first, to be able to apply the different background for archived caches to their waypoints as well.

**Comment by Lineflyer** [comment]
Definitely a)

**Comment by eddiemuc** [comment]
> Definitely a) 

So you changed your mind compared to 6 years ago? :-)

Never mind, I would also prefer (a)

**Comment by Lineflyer** [comment]
Yes, because there was no (quick) possibility to hide deactivated caches at that time :)
