### ISSUE TITLE
Add option to encode non-encoded logs.

### ISSUE THREAD

**Issue by PhorkYou** [cgeo/cgeo#5013]
People sometimes log spoilers that are not encoded. Encoding all non-encoded logs as they're fetched would allow users to check the recent logs to see if it has recent finds without accidentally having the cache spoiled.

**Comment by SammysHP** [comment]
I'm not sure this makes sense. First of all, we cannot detect whether a log is "encrypted" (better call it something like "rot13 coded" because it's not really an encryption). So it would only be possible to switch all logs. Bad for those who contained rot13 coded text.

Secondly most users should be able to not read the log text if they don't want.

With respect to code complexity I'm voting for "won't fix".

**Comment by Lineflyer** [comment]
This will only be useful in quite exceptional usecases.
Also on the website and in every other geocaching app I am not aware of such a feature.

I don't think it is worth the effort of programming this might have.
