### ISSUE TITLE
Keep same zoom level when switching between map and list

### ISSUE THREAD

**Issue by TofLaBeuze** [cgeo/cgeo#5087]
Hi c:geo team,
when managing an offline list, I display it on a map (with "earth map" button), zoom one or several times, then I go back to the list (by mistake by touching "back" or by purpose - maybe filter), then back again on a map : Unfortunately, the last zoom level has been lost.
It could be an option, as each people could have his preference.
Thanks for considering this.

**Comment by Lineflyer** [comment]
This map function does what it is intended to do, i.e. showing all the caches on a map and adjust the zoom level accordingly. We already remember the last zoom for some cases, this however is not one of them intentionally. I suggest you split your lists into matching geographical areas...c:geo can support a nearly unlimited number of lists.

I am against an options for that, because:
- More complicated handling
- How to handle this setting (e.g. you map a list of 5 caches close to eath other, the map will have a high zoom. Afterwards you open another list with 100 caches not so close to each other, the map will still be on a too high zoom and therefore be useless or the user might miss caches).

**Comment by TofLaBeuze** [comment]
Thanks for your feedback, Lars.
Could you please explain why it is intentional in this case to not remember the last zoom, and to remember it in other cases ? (why this use case is different)
The option I suggested could maybe related only to last list used (last map-last zoom level-last list consistency).

**Comment by haarspalter** [comment]
ok, at least I am not the only one with that particicular use case. Using the live map might be a possible solution for me, need to check that.

**Comment by moving-bits** [comment]
Proposal to distinguish between the two situations:
- normal click on "world map" icon: open map for this list and adjust zoom level accordingly (=> as today)
- long click on "world map" icon: open map for this list, but don't adjust zoom level
(to make it easier to toggle between the two views)

What do you think?

**Comment by Lineflyer** [comment]
I think its unnecessary to be honest (and would lead to another hard to find feature).

**Comment by edgarbriggs** [comment]
I agree with the thread starter. If I open a list, and then go to the map, it's okay to set the zoom to show all caches in the list. But if I zoom in, go back to the list and then reopen the map, I would be very happy to have my last zoom restored.

**Comment by Lineflyer** [comment]
Meanwhile things have changed IMHO and an easy workaround is possible:
- Start on list
- Use "Show on map"
- Zoom in or move as desired
- Press back to return to list
- Now simply use the bottom navigation "Map" item to reopen the map --> It will reopen as left before (zoom/location)
- To go to the list, simply click on bottom navigation "Stored" again

So the "Show on map" can retain its original function (i.e. show all the list on the map) while there is a perfect possibility to swap both. Only drawback is, that not only caches from the list are shown by doing it this way, but all other caches as well. That could be mitigated by e.g. using a custom list marker icon using the existing feature for that.
