### ISSUE TITLE
OC Cachelist import

### ISSUE THREAD

**Issue by MacGyver-NRW** [cgeo/cgeo#5094]
I request a new feature wich can import cachelist from opencaching.de
It would be great to import GPX on my c:geo.
Cachelists may be available by OKAPI.
Save my own list or public listings on c:geo.
Thanks!
You will find any support at OC you need ;)

**Comment by rsudev** [comment]
@MacGyver-NRW GPX-import should work for any gpx, regardless of the source.
Do I understand correctly, that you would like to select a cache list you created on oc.de directly and download that into c:geo?
Can you give a hint, which OKAPI-method allows to access those cache lists?
Another question (to the broader audience) would be, whether to implement this sided with the gc.com PQ feature or in  a different fashion, so that gc.com cache lists could be later integrated there as well (or do we support those already?)

**Comment by Lineflyer** [comment]
We do not support the gc.com bookmark lists up to now (only indirectly if a PM creates a PQ for one of his lists. So for the way of implemenation it would need a new UI (which I agree could be used later on for lists from other sources as well).

**Comment by MacGyver-NRW** [comment]
You can add it on Import Process... 
"Import ->"
"-> Importiere aus GPX Datei"
"-> Aus dem Internet importieren"
"-> Import von Android"
"-> Import aus OC.de Cacheliste"
For method, i'm going to ask "following" as the developer on this feature.

**Comment by Bananeweizen** [comment]
There is no OKAPI method to get cache lists. And we surely will not start spidering the OC websites for this. Feel free to reopen, once OKAPI supports this.

**Comment by Lineflyer** [comment]
@Bananeweizen 
I think @MacGyver-NRW is not requesting for web spidering  but asking if we would support it in c:geo as soon as the OKAPI supports it as he has the direct connection to OC.de developers.

**Comment by Natureshadow** [comment]
+1 once OKAPI supports it. Of course, -1 to spidering.

**Comment by MacGyver-NRW** [comment]
Absolute right. As i spoke with "following5" as our developer on "cachelist" feature, he thought about implementing this in OKAPI. But the high level on coding needs a lot of time to develop this. I think we can reopen this request an soon as OKAPI supports "cachelist".
