### ISSUE TITLE
No offline data when importing gpx

### ISSUE THREAD

**Issue by nagisml** [cgeo/cgeo#5126]
Precondition: Activate all offline setting in the options. E.g Pictures, Log pictures, static maps

When a gpx file is imported (e.g. standard export from gsak) the cache details are available offline but no pictures are downloaded and stored during the import.
Meaning a refresh of the same caches needs to be done after the import to make the picture etc available offline.

**Comment by SammysHP** [comment]
That is by design. The import of a GPX file should not access the internet. Also there not all pictures (spoiler and log pictures) can be loaded as the link is not contained in the GPX.

**Comment by Lineflyer** [comment]
@nagisml 
If you import a GPX you just import the data in that GPX file. After that we (optionally) load static maps for the cache locations. 
We have some feature request for selective loading of data (e.g. GCVote), so this would be just another feature request then. But as @SammysHP mentioned the URL of spoiler pictures might not be included in the GPX thus it is not possible for c:geo to selectively load the spoiler pictures.

**Comment by nagisml** [comment]
Thanks for the feedback. I fully understand that loading additional data which is not in the gpx file is not possible. 
But as there are links to some images in gpx files the import should download at least the linked images. Of course only if offline storing of images is activated in the options.

As cgeo does not know what did generate the gpx file their could be any image links included. So additionally the recognition of gsak specific image tag links would be appreciated e.g. <gsak:CacheImages>. Possible this should be a separate feature request.

**Comment by Lineflyer** [comment]
As written above the missing images, etc. after importing a GPX is "by design" as GPX do not contain additional binary files.

As this issue is stale and we have a feature request around for loading missing information after GPX import (images, favorite points, etc.) lets close here.

Additionally the most used workaround is of course to refresh the caches in c:geo after importing them via GPX to get a complete offline available set of information.
