### ISSUE TITLE
Waypoints are not being updated correctly

### ISSUE THREAD

**Issue by holmwood** [cgeo/cgeo#5232]
I have just published a cache.  When I view the waypoints in CGEO they are jumbled up and are not being displayed correctly.  
The same waypoints are displayed correctly in the geocaching.com app, on the geocaching.com website and on my Garmin GPS unit.  Just not correctly on CGEO.

This is the cache:  Le Chemin Secret  GC64J9E

To see the problem, first look at the cache on geocaching.com on a PC.  Look at the second waypoint puzzle:  Les Fenêtres .  In the French part of the waypoint description, the coded waypoint is displayed correctly on the PC as :  N 44° 05.2E1 E 005° 59.CDE.   CGEO displays the same waypoint jumbled and incorrect as :  N44°E005°05.2DD59.CD5

There is a similar problem with the remaining waypoints.  Interestingly, the English waypoint description displays the waypoints correctly.  

This seems to be a big problem.  Please advise!

Thanks, Chris

**Comment by Lineflyer** [comment]
This sounds like a known bug where waypoints are not correctly updated after the owner changed them.

Please verify that it looks OK in this view (as in this case the problem is only locally on your installation):
![screenshot_2015-10-10-13-44-17](https://cloud.githubusercontent.com/assets/949669/10410981/1b0fba1a-6f55-11e5-818a-a31f1aeeae73.png)

If everything looks OK here, you can only solve this by deleting the cache on your device, wait for three days and load it again.

The known bug is listed here: #3650

**Comment by Lineflyer** [comment]
Please ignorhe the messenger icon in the screenshot :)

**Comment by holmwood** [comment]
Three observations :
1) Thank you so much for your quick and comprehensive reply.
2) Your screen-shot looks perfect, confirming other geocachers will not have a problem as the coded waypoints are being displayed correctly.
3) Disappointed to see the bug was first identified over a year and a half ago and it has not been fixed.

Thank you so much for you help !  My mind is at ease !

Chris

**Comment by SammysHP** [comment]
First of all, "URGENT" would be something like "c:geo crashes on all devices" or "earth is a cube". So I'll remove it from the title.

Second, c:geo is made in our free time. We don't get money, we don't get anything. We are working on it because we have fun to do so. And of course, c:geo is open source, so everybody can contribute. There are much more serious issues than this one and we are not able to fix all of them.

**Comment by holmwood** [comment]
Sammy,
First: It was URGENT for me, because I thought my life was not worth living any more, if no one could do my cache!  Of course I take your point. 
Second: I was forgetting the app was free, so sorry for my comment about being disappointed. We always use C:GEO, including the script for directly downloading caches.  I can't immediately think of any features I would like you to add, so it must be good!

Regards,  Chris
