### ISSUE TITLE
GGZ import fails or is slow

### ISSUE THREAD

**Issue by Willabee** [cgeo/cgeo#5233]
Tried the new GGZ format and it takes forever to load into c:geo. It cycled through 0-100% numerous times. It loads into my Oregon super quick, so is there an issue? Currently, I will revert to a GPX format for c:geo as I can only see a disadvantage.

**Comment by Lineflyer** [comment]
Can you provide an example file which has this problems?

**Comment by Willabee** [comment]
Here's one that takes forever.


It says it is to big to upload. Let's put a filter on it and try again, 3605 records out of 19855. This is considerably smaller than the one I want to use but is still slow.

Now it is saying the file type is not supported. Suggestions please.

**Comment by Lineflyer** [comment]
@Willabee 
It is not possible to send attachments via mail reply to this issue. You have to manually attach them on the Github website or send to us via mail (support (at) cgeo.org) with reference to this issue.

**Comment by Willabee** [comment]
Smaller file sent to support

**Comment by samueltardieu** [comment]
I think the multiple 0-100% display happens because the file size is used even for a compressed file. We should either first uncompress the file to get the right length, or use a progress without percentage.

I have not looked at the other problems.

**Comment by Lineflyer** [comment]
@samueltardieu 
So would you judge this as a bug in the feature or just a UI problem?
Maybe you can adapt the issue title accordingly and set labels...had no time to test it myself.

**Comment by Bananeweizen** [comment]
@Willabee Just to comment on the speed of the import: It is nearly the same for GPX and GGZ files. The overhead for unzipping is neglectable in comparison to the time needed for a fully validated XML parsing (which has helped numerous times to find bugs in our parser and in the GPX engines of other software outside cgeo). Your device might be faster since it probably does simple text matching.

**Comment by Bananeweizen** [comment]
I've now tested this on multiple devices. The import is the same speed in both variants (either GGZ or unzipped GPX). Makes sense, since the unzipping is done rather transparently by the ZipStream we are operating on. If your app shows crashes for the GGZ file, I would expect it to crash for the GPX file, too.

I feel like we cannot really fix something here.

**Comment by Willabee** [comment]
Loading a GGZ file does not crash the app. It takes the same time overall as loading a GPX file. The only difference is that the GGZ option cycles 0-100 a number of times (as has been highlighted due to gpx files it contains. This is probably because I use the GGZ export option from GSAK).
It would be better, IMO, to show only one 0-100 dialog if this is possible.
Is there any advantage of the GGZ option over GPX once the app has finished loading them into a list?

**Comment by Bananeweizen** [comment]
From the viewpoint of the app, there is no advantage, as both formats contain exactly the same content. For you as a user the GGZ might have benefits in case you need to download it via mobile data.

**Comment by Lineflyer** [comment]
Can we close this?

**Comment by Lineflyer** [comment]
Closing due to lack of feedback.
