### ISSUE TITLE
Cgeo link to groundspeak messaging system

### ISSUE THREAD

**Issue by SweeneyToddlers** [cgeo/cgeo#5352]
I think this question has been asked before but I thought I'd try again. Currently cgeo links to the 'send message (email)' system through a browser link. The trouble is that a picture cannot be attached. Would it be possible for cgeo to have a link to the (newish) groundspeak messaging system. People are using it more and more and it does have advantages over email including the ability to send pictures directly to CO's in case of maintenance issues etc. It would be the current 'send message' feature but linking to the message centre in a browser instead of sending an email through your browser......

This feature would be extremely useful. Please, please, please.......

**Comment by rsudev** [comment]
Seems to be not so easy as it looks. All 'direct' Iinks I could find require the user guid, a piece of information we currently do not have (for the eMail based messaging system there exists the possibility to just use the user name).
If we find a way to directly address the target user with the information we have, I'd say we can consider adding this kind of direct access as well.

**Comment by kumy** [comment]
From what I found, the user UID could be retrieved using a GET request to 
`curl -H "Accept: application/json" -H "Authorization: bearer <bearer>" https://communication-service.geocaching.com/api/accountsummary?usernameStartsWith=<username>`

The `bearer` need to be retrieved before using:
`curl -X POST -H "Accept: application/json" -H "X-Verification-Token: <verification_token>" https://www.geocaching.com/account/messagecenter/home/getaccesstoken`

The `verification_token` has to be retrieved from a GET request to:
`https://www.geocaching.com/account/messagecenter` ; `verification_token` is located in variable `reqToken` from the javascript variable `serverParams`

So this lead to 3 distinct requests to obtain the user UID...

While searching if other parameter than `usernameStartsWith` exists, I've found another project on github who implemented such calls, see https://github.com/Christian-X/geocaching/blob/master/api.py#L97-L103

**Comment by rsudev** [comment]
Then it might be cheaper still to retrieve the target users profile page and get the message link from there...

**Comment by Lineflyer** [comment]
My few cents:
A link to the Message center would be a good compromise instead of a (impossible) full integration of the message center functionality. I appreciate this feature request.

**Comment by fm-sys** [comment]
I would like to implement this.

It will work like this:
1. get source of `https://www.geocaching.com/p/default.aspx?u=[username]`
2. then search for id `ctl00_ProfileHead_ProfileHeader_lnkSendMessage` and open the `href="/account/messagecenter?recipientId=` link in browser

this would be added to GCParser.java (am I right?)

But where is the owner onclick context menu defined so I could link this function?

**Comment by moving-bits** [comment]
Have a look in `res/values/strings.xml` to look for the strings being displayed in that context menu
```
<string name="user_menu_title">About</string>
<string name="user_menu_view_hidden">Caches hidden</string>
<string name="user_menu_view_found">Caches found</string>
<string name="user_menu_open_browser">Open profile in browser</string>
<string name="user_menu_send_message">Send message</string>
<string name="user_menu_open_contact">Open contact card</string>
<string name="user_unknown">Unknown user</string>
```
then let Android Studio show you where those strings are being used, you'll find `connector/GCConnector.java` with the `getUserActions` method (among other places).

**Comment by fm-sys** [comment]
Otherwise, we could easily parser the user guid while downloading the cache description without additional traffic. Are we willing to spend a new column in `cg_caches` for this? Or even a new `cg_users` table?

**Comment by fm-sys** [comment]
The user guid is needed everywhere, where we have the user context menu popup: Cache owner, cache logs and the same of course for trackables (which are however not stored in our database). 

There are two options on how the guid could be stored: 
-  a new column in `cg_caches` and `cg_logs`
- a new table for linking the usernames with the user specific guid

The first one is easier to implement, but leads to slightly higher memory consumption when there are multiple caches/logs by one user. @eddiemuc @moving-bits you have made changes to the database structure in the recent past. Which variant would you prefer?

**Comment by eddiemuc** [comment]
The way c:geo's use cases are designed right now I would store it in cg_caches and cg_logs.

The reason: I would look at this not primary from db point of view but from domain model point of view: would you create an own, persistent class "User" for the c:geo system as things are right now? Probably not because currently we have no use cases where "User" plays a primary role (like e.g. storing leadership lists etc - and contact handling c:geo delegates to external app). So since "User" is not a "primary object" in c:geo but only a "secondary attribute" to other entities, I would not spend an own db table for it. I am a buig fan of db models matching an apps domain model.
Also, you have to handle the "non-persistent" case anyway (message system linking shalöl probably work also in caches/logs which are not stored offline). DB structure will not help you here.
From a practical point of view this safes you synchronizing the cases where caches/logs are removed from db and you have to check back whether now you can delete certain users in the user table (because now no one references them any more) while others need to remain (because they are also used on other logs/caches)
 
I don't think that the additional storage space is a big issue.

**Comment by fm-sys** [comment]
Ok, thanks for your explanation! That was also my first and still preferred way...

**Comment by moving-bits** [comment]
Nothing to add to @eddiemuc's detailed explanation... :-)
Sometimes denormalization is the way to go.
