### ISSUE TITLE
The improved dialog for PQ import is less intuitive

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5415]
2016.01.21-NB

This is for sure a subjective impression, but for me the previous implementation with showing a dialog after clicking on a PQ name was ¨failsafe¨ and intuitive. WIth the new implementation users might miss to understand that clicking on the name and clicking on the icon triggers different things.
I don't know why Ihave this feeling, maybe because the icon does not really look clickable. I would honestly prefer the old implementation.
Opinions on that?

**Comment by Bananeweizen** [comment]
You might be right with this not being intuitive enough. Nevertheless I surely don't want to go back to a list selection dialog instead of a list activity. That fits way better into the normal UI (e.g. back button navigation works, screen is used completely etc.).

But I also envision that we may want to create a button with the download icon on every downloadable list entry instead of just displaying the icon.
