### ISSUE TITLE
Pocket Query list: show last generated and remaining days

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#5431]
The PQ list on gc.com has a column with "last generated" and "remaining days".

(https://geoclub.de/forum/viewtopic.php?p=1243198#p1243198)

**Comment by pstorch** [comment]
I was looking into this a bit. But I'm not sure if "remaining days" is that usefull. 
It has a special case for the last day, as seen in the screenshot:
![selection_001](https://cloud.githubusercontent.com/assets/5598124/12795789/0555290e-cabc-11e5-85da-7b9eb60725d0.png)
We could translate "last" of course, but I don't know if this is a good idea. Calculating the remaining days ourself would be better, but is not possible, because we don't have the exact time when the last generation happend and it's dependent on the "Server Time" (above the table). 
Maybe the "File Size" is more usefull to know.

**Comment by SammysHP** [comment]
> We could translate "last" of course

Oh, I meant that we should parse the date and remaining days and format it with the user's locale.

**Comment by pstorch** [comment]
I try to parse it

**Comment by SammysHP** [comment]
We parse dates a lot, maybe there's already a helper for that.

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by Lineflyer** [comment]
Tested and working with 2016.02.22-NB.
Only some translations missing, maybe @rsudev can upload strings to Crowdin.
