### ISSUE TITLE
Show geotagged log or listing images on the map

### ISSUE THREAD

**Issue by UniQP** [cgeo/cgeo#5483]
Garmin devices have a nice feature for images that provide GPS coordinates via Exif: They place a picture icon on the map that shows a thumbnail of the image when activated. I found this feature very helpful and would therefore propose to add a similar feature to c:geo.

**Comment by SammysHP** [comment]
Which pictures should be shown on the map?

**Comment by rsudev** [comment]
From my perspective this sounds more like a feature for a general purpose gps/map app like Locus or OruxMaps, something c:geo decidedly does not want to be.
But if there is a caching context (we e.g. discussed already to display gpx-tracks associated with some multi-caches, but not showing tracks in general) it might be worthwhile to discuss further.

**Comment by UniQP** [comment]
@SammysHP I'm thinking of images that are stored for offline usage.

@rsudev For instance, I appreciated the feature during the outdoor part of GC5R6FD. To get the final coordinates, you need to go to the tree shown in the image (with GPS coordinates) at bottom, and read some numbers (not shown on the picture). Seeing that image on the map was very convenient when navigating to these coordinates.

I can also imagine that the feature could be useful for tourist caches (but I have no particular example for this case).

**Comment by Lineflyer** [comment]
I do think this could be more a feature for a dedicated app as I consider it way to special

**Comment by samueltardieu** [comment]
Instead of showing a thumbnail on the map, we could use some symbol near a picture to show that we have its location, and allow navigation to this location. It would help sometimes to be able to stand where the photographer was, and look for the very same view.

**Comment by Lineflyer** [comment]
@samueltardieu 
You mean for the pictures attached to logs or listing pictures? Indeed for this your implementation proposal looks nice.

I did understand this request more general for all pictures on a device which I think would be too special (as written above).

**Comment by UniQP** [comment]
Oh, it seems that my description/answers were misleading, sorry for that. I was talking about pictures that occur in the listing or image gallery of geocaches, not of arbitrary pictures on a device.

**Comment by Lineflyer** [comment]
Adapted title accordingly.

**Comment by LeXeRLV** [comment]
This idea is super!
I started to use this function and it helps very well.
Usually some pictures stored for offline use have some spoilers for the
cache, also in my country there is big series (LV Boarder Caches by
LV_Patriots) of mystery caches, where lot of caches have final place hidden
in the image included in description.
Now I don't need to save on PC these pictures, and see if these pics have
GPS information or not :)
Really useful thing in c:geo!

I would like to see it little bit more advanced. Will try to explain - like
user can Enable/Disable showing own/found caches (the same is for showing
disabled caches), I think it could be useful if user can enable/disable
showing waypoints of the stages for multicaches, traditional caches parking
places and thailheads e.g.
And additionally for this function with showing stored images GPS location,
there could be also posibility to enable/disable showing icons on the map
with some kind of picture-looklike symbol - when pressing on this icon user
can see to which cache it belongs.

I don't think there will be a lot of picture icons on the map, if this
function enabled, because not all images are stored on device, only fresh
one and owner added to the description.

How c:geo developers thik about it? :)

Best regards, LeXeR

And sorry for my bad English skills :)

**Comment by pstorch** [comment]
I don't know if showing all Image Coordinates is a good thing, but what about an "Add as waypoint" item in the Image context menu?

**Comment by Bananeweizen** [comment]
That sounds quite reasonable to me, since it does not introduce random new complexity but still fulfills a big part of this use case.

**Comment by pstorch** [comment]
I kind of have a working solution. But either added waypoints are not shown right away (need reopening of CacheDetails) or I call `notifyDataSetChanged()` which causes also all images to be reloaded.
Before opening a Pull request I try to solve this usability issue (partially update the waypoints tab).
