### ISSUE TITLE
long pause before updating all caches

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5533]
###### Detailed steps causing the problem:
- Open a list with 500 caches and refresh all
- Confirm the download

###### Actual behaviour after performing these steps:
Some seconds of unresponsiveness with the okay button being pressed. afterwards the download starts as normal. There is potential for ANR here.

**Comment by Lineflyer** [comment]
`Master`?

**Comment by Bananeweizen** [comment]
I've traced this down to the filtering of caches with and without static maps.
```
            for (final Geocache cache : caches) {
                if (cache.hasStaticMap()) {
                    withStaticMaps.add(cache);
                } else {
                    withoutStaticMaps.add(cache);
                }
            }
```
Since that needs disk access, it easily leads to blocking the application. If we were using Java streams, I would probably write something like
```
Streams.concat(Stream.of(caches).filter(hasStaticMap), Stream.of(caches).filter(!hasStaticMap))
```
However, since that is used with observables from ReactiveX, I'm not sure if there is a similar transition.

**Comment by Bananeweizen** [comment]
@samueltardieu Missed the question above?

**Comment by samueltardieu** [comment]
Yes, I did. I recall reading something about Java streams in my mail, have you changed your comment?

What you wrote looks fine, but doubles the number of disk accesses which is why it was done the other way. Maybe it would be better to first build an observable of `ImmutablePair<Observable, Boolean>` where the `Boolean` would represent the presence of static maps, `cache` it and use the double and concatenated `filter` to build the final observable (there might be a simpler way).

Where does the blocking occur? The `refreshScheduler` itself will depend on the network accesses, we might starve somewhere if some caches are long to refresh.

I'll try to have a look at it.

**Comment by samueltardieu** [comment]
Using `concat` on the result of `groupBy` might give us a workable solution too.

**Comment by samueltardieu** [comment]
I'll setup a PR so that you can try it.

**Comment by samueltardieu** [comment]
With the proposed PR, I can't see any delay when refreshing a list of 500 caches (and looking at the logcat at the same time), neither at the beginning, in the middle, or at the end.

**Comment by samueltardieu** [comment]
Note that in case all caches already have static maps, you still have to go through them all before deciding that there is no "priority" cache (one without static maps).

I'll have to think more about it, but with Akka streams I know how I would do it:

```
           No static maps
        +---------------------> Buffer(5)+
        |                                |
Caches  |                                +---------> Merge preferred +--> Refresh
        |                                        |
        |                                        |
        +---------------------> Buffer(unbounded)+
            Has static maps
```

The back pressure would have made `Refresh` request caches to refresh as it can handle them (network slot available). Propagation of the back pressure would have made `Merge preferred` request contents from the read-ahead buffer of 5 caches without static maps, and if none were available would have requested them from the unbounded buffer of caches with already present static maps.

This way, the caches scanning would advance as long as we don't have 5 caches without static maps buffered (so that we can rapidly answer the `Merge preferred` request), and any caches with a static map would be buffered for later. However, if for any reason many caches already have static maps and we fall behind the refresh rate, some elements would be taken from the bottom buffer as to fulfill the requests slots, no time lost.

Modeling this with RxJava is probably a bit less straightforward.

**Comment by Bananeweizen** [comment]
Thanks a lot for the detailed explanation. Got my head around some basic concepts now, since I naively took some assumptions from Java streams.
