### ISSUE TITLE
Pull Requests automatic code analysis

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5624]
Do you know about tools for Java like [Hound](houndci.com)?
Or [Coverity](http://go.coverity.com/Product-Coverity.html#).

Could we get benefit by activating such hooks for our PR?

**Comment by kumy** [comment]
https://www.sideci.com/
https://www.codacy.com/features

**Comment by Bananeweizen** [comment]
The Ant based build had Findbugs, Lint, Jacoco code coverage and Simian duplicated code detection, see http://ci.cgeo.org/view/cgeo%20deprecated/job/c-geo/ However, it was quite hard to actually get those running, and I haven't yet taken time for that with the gradle build.

If possible, I would like to see a solution where some essential tools are part of the gradle build script, not of the Jenkins job. Otherwise developers will always complain that this is reported afterwards, but not while they are developing locally. Also, it would not be sufficient to do this for pull requests, it needs to be active at the continuous integration build, too.

For existing "ready to hook" solutions, browse the integrations directory of github: https://github.com/integrations. I have not yet experimented with any of those.

**Comment by samueltardieu** [comment]
There exists the CheckStyle plugin: https://docs.gradle.org/current/userguide/checkstyle_plugin.html

**Comment by kumy** [comment]
Should we connect https://reviewable.io/repositories so that all PRs get linked to reviews?

**Comment by kumy** [comment]
Added https://www.codacy.com/app/github_57/cgeo/dashboard and corresponding Badge

**Comment by kumy** [comment]
May I enable Codacy to comment commits?

**Comment by samueltardieu** [comment]
> May I enable Codacy to comment commits? And activate the Post-Commit Hook to get the analysis run immediately after each commit?

Sure, let's try this. We might need to tweak some of the checks it does though.

**Comment by samueltardieu** [comment]
> Should we connect https://reviewable.io/repositories so that all PRs get linked to reviews?

Let's try this as well :-) We can always remove it if this does not work well for us.

**Comment by kumy** [comment]
Both tools are now connected with our git repository

* https://www.codacy.com/app/cgeo/cgeo/dashboard
* https://reviewable.io/reviews/cgeo/cgeo#-

**Comment by kumy** [comment]
I have just disabled the "Reviewable hook" as most of us doesn't really like it.

**Comment by kumy** [comment]
I'll try to setup checkstyle with our coding convention.

**Comment by rsudev** [comment]
I'd think this item is covered in the meantime, by the various activities WRT to build and external tools, right?
