### ISSUE TITLE
Locus cannot be selected in "share cache"

### ISSUE THREAD

**Issue by haarspalter** [cgeo/cgeo#5644]
##### Detailed steps causing the problem:

Might be related to #5643
- open details of a cache
- select "share cache"
##### Actual behavior after performing these steps:
- neither in the short list, nor in "view all", Locus can be selected as target
##### Expected behavior after performing these steps:
- Locus pro should be available as a target for sharing a cache, e.g. to use the Formula solver there
##### Version of c:geo used:

2016.04.07-NB-8b891da
##### Is the problem reproducible for you?

Yes/No
##### System information:

Device: D6503 (D6503, Sony)
Android version: 5.1.1
Android build: 23.4.A.1.264
Cgeo version: 2016.04.07-NB-8b891da
Google Play services: enabled
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present Direction sensor used: rotation vector Hide own/found: true Map strategy: auto HW acceleration: enabled (default state) System language: de_DE Geocaching sites enabled:

geocaching.com: logged in (Login OK) / PREMIUM Installed cgeo plugins: calendar
##### Other comments and remarks:

As the issue described in #5643 opens Locus, this seems to be possible somehow. Not sure if Locus can be added to the list of share targets. If not, it maybe there could be a specific menu item.
With the current version, I have to export the Cache as GPX, and import it again in Locus.

**Comment by akkatracker** [comment]
Something strange is happening. 

I can get Locus to show up in the share but when I select it it is broken (doesn't import cache)

Here is a video of what's happening: https://www.youtube.com/watch?v=8u2efvfwTis

**Comment by akkatracker** [comment]
Scrap that, I was running an old build. I get the same bug as you

**Comment by Lineflyer** [comment]
@haarspalter How at all can you verify the content of the "View all" if as seen in #5643 it opens Locus immdeiately?

**Comment by akkatracker** [comment]
http://imgur.com/utFAUbT

I am unsure if all options are listed there but there is no locus in the options shown for a flash.

**Comment by haarspalter** [comment]
"View all" opens Locus, and then pressing the back shows the the full list in c:geo

**Comment by haarspalter** [comment]
With the latest nightly, I can confirm the behavior described about, Locus showing the address search screen

**Comment by pstorch** [comment]
I researched a little bit. 
This generic "Share" function (`Intent.ACTION_SEND`) of Android with `text/plain` as type is not very standardized. Some Apps (like Locus) read only the `Intent.EXTRA_TEXT` String. Others read also the `Intent.EXTRA_SUBJECT` and concatenate both.
If Locus finds Coordinates in the `EXTRA_TEXT` field, then it opens the Map at this location and shows a waypoint. If it reads other text it shows the Address search dialog. In our case we currently set the Cache URL which Locus ignores completely and shows an empty Address search dialog.
So for Locus the best we can do with this Share Action is to put Coordinates into that field. But for other Apps the URL might be better. It depends on the Intent receiving app, what it is using.
It's impossible to find a "one text fits all" solution.
I can send the fix for Locus, but this might break sharing with other apps.

**Comment by rsudev** [comment]
Sending the url when sharing a cache sounds totally appropriate for me, whether the receiving application can handle that correctly or not - that's up to the user to decide if it makes sense for him.
For interacting with Locus, we have specific navigation options, which send the coordinates with more information alongside. So that should be the route for users that want Locus to interact with the location of the cache.

**Comment by pstorch** [comment]
That was also my thought. So let's keep the Share Intent as it is today with the url.

**Comment by pstorch** [comment]
Should we close this with "won't fix"?
