### ISSUE TITLE
Copy all modified waypoints to notes

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5688]
We should have a button to copy all user modified waypoints into the notes. I learned there are quite some people who want to store more than one modified coordinate at the website and this would make that easier.

**Comment by pstorch** [comment]
I saw this feature requested recently in the c:geo FB fan group and heard about it in [OC Talk 48](https://blog.opencaching.de/podcast/oc-talk-048/). 

When I think about it, I see some challenges:
- what if the personal note already contains some content? Just append?
- what if this action is executed several times? Overwrite last waypoints? How to detect? Have some marker? Or just append? 
- what if the allowed characters are used up?

This action should be applicable to a single cache and to a list of caches.

**Comment by Lineflyer** [comment]
Append is a good way.

We should store them in a format that is reverse detected as WPs while parsing the note (so its kind of a self restoring backup).
That leads to another problem...we will have all WPs doubled just after copying to the note.

**Comment by pstorch** [comment]
I think we have a duplication detection in the "import waypoints from personal notes" feature. 

What about the user notes from the waypoints? I guess users expect to have them exported to the personal notes, too. Might contain important information (variables, etc.). But the import feature doesn't import user notes (yet).

**Comment by Lineflyer** [comment]
This has IMHO become the most asked for feature in the last months.
Also my personal "would like to have" favorite. So if someone is bored ;)

**Comment by Lineflyer** [comment]
Again +many from support channels..

**Comment by eddiemuc** [comment]
I am looking for a starting point to contribute to c:geo, and after looking into c:geo code this feature request seems like a good one. I propose implementing this as follows:
* add a new button "add user waypoints" next to the Edit/Update buttons in "personal note" in "Description" tab
* clicking it will add a list of textual representations of all user-defined waypoints, format would be something like "<name> (<waypointType>) <coord>\n[<description>]"
* personal note waypoint parsing function will be extended to recognize this format for "backup restoration"
* if adding text leads to "too long personal node", then following measurements will be taken in this order until max length is reached: shorten description to first x characters, leave out description, leave out waypoint name, only sync first x waypoints

Would that be ok?

**Comment by Lineflyer** [comment]
Contributions are always welcome and this would IMHO be a very nice feature.
Wouldn't it be sufficient to store the waypoints in a way they can be restored by the current waypoint parsing already? The parser should have all what is needed.

This would minimize required changes and would keep it consistent to other user coord notes.

**Comment by eddiemuc** [comment]
Hi Lineflyer,
current waypoint parsing is only able to parse coordinate and waypoint type. Name and Description cannot be parsed. The format suggested by me above would ALSO be recognized by the existing parser, but it would only restore coordinate and waypoint type. This is why I suggest the enhancement of the parser as well.

**Comment by Lineflyer** [comment]
You are right. I did not think of the addional fields. In that case we should probably enhance the parsing accordingly but reuse the existing whenever possible. Feel free to start with your contribution, looking forward to it.

**Comment by eddiemuc** [comment]
I am in the middle of implementation and created for now the following "Waypoint text pattern" (for both creating and parding):
@name (type) coordinate\n"user note"

Example:
@My Waypoint (puzzle) N48 10.123 E11 05.456 
"My User Note"

Additional notes:
* Regarding the @: if no @ is found during parse then no name is created from text (default name applies). If there would not be a name marker, then coords parsed from within text might get very strange names...
* Type: 
  * type will also be recognized when NOT in () like today, but will then additionally be part of the name. E.g. "@Parking Spot N48 10.123 E11 05.456" will become waypoint of type "Parking" with name "Parking spot". Type in () will be filtered out in name creation.
  * for easier typing I created one-char-shortcuts for each waypoint type: F=final, P=parking, X=puzzle,... E.g. "@The End (F) N48 10.123 E11 05.456" will be parsed as Final waypoint
* User note: " can be used optionally because user note can be multilined. Escaped " in user note (\") are recognized. " to start note can be placed both on same line (after coord) and on next line. If no " is found after coord, then "user note" is filled from coord until next linebreak. 

I tried to find a good compromise to keep things simple, short (due to restricted user note space), backward-compatible and also manually readable/editable.
For this reason, among other things, I decided against a "json-like" pattern for now ("name:My Waypoint, Coord:...").

I am, however, open for discussion, comments, suggestions.

**Comment by Lineflyer** [comment]
Looking at your description,  I understood that you keep the backward compatability by adding the @ for this new backup/restore and keep the "legacy" parsing in place if there is no @ found?

**Comment by eddiemuc** [comment]
Hi @Lineflyer , that's correct. If no @ is found the legacy mechanism for naming the waypointt applies (which is an internationalized Version of "Personal Note" Witz appended index

**Comment by eddiemuc** [comment]
Pull Request #8608 is now ready for review IMHO.
I am really not familiar with the (formal or informal) conventions for this project, so I am a bit unsure on how to proceed. Should I just wait for feedback now?

**Comment by Lineflyer** [comment]
Fix has been merged. Thanks to @eddiemuc for this really nice contribution.
