### ISSUE TITLE
Replace Move/Copy by Manage on lists

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5711]
- Long press cache in the list
- The menu shows move and cooy as actions

To make it consistent with the multi list feature this should be replaced by "Manage" opening the checkbox based selection.

**Comment by Bananeweizen** [comment]
-1. The "manage lists" button is suited for _one_ cache, while these operations work perfectly for _many_ selected caches. I.e. the copy menu really just adds a new list to all selected caches, the move menu really removes all selected caches from the _current_ list (only) and adds them to another.

Both these operations for multiple caches are simply not possible with the manage lists feature, as that removes all current lists and then sets all newly selected lists. Just imagine to select 2 caches from list A, where one of them is also in list B, and then copy/move them to list C. That is not possible with the manage list feature, since they would both vanish from A _and_ B.

**Comment by Lineflyer** [comment]
I was not refering to the management of multiple selected caches but the longpress menu of a single cache.
Or can this technically not be separated?

**Comment by pstorch** [comment]
OMG these long press actions are really hidden features. I never saw this menu ;)
At the moment this context menu triggers the same functions as the normal menu for all or selected caches. But I guess these can be replaced by a "Manage Lists" button for this single cache.

**Comment by Natureshadow** [comment]
Ever used Windows Mobile? Long press used to be the standard touchscreen equivalent to right click ;).

**Comment by rsudev** [comment]
The long press had the same place in the Android interaction concepts, until the 'context menu' was replaced by the 'context action bar'

**Comment by pstorch** [comment]
I've never used Windows Mobile, but I know long press for context menu in other Android Apps. 
I'm more wondering about myself,  why I haven't tried it with cgeo before.

**Comment by SammysHP** [comment]
Yes, you can long press almost everywhere in c:geo. ;)

**Comment by Bananeweizen** [comment]
I'm quite used to using these operations either from the context or options menu. I would not like them to vanish. And as long as we still call everything "list", the operations move and copy make perfect sense to me. If we finally start calling lists tags, then operations called "add tag" (=copy) and "remove tag" (=delete from this list) would be be more natural terms, but these operations should still be there.

The current list management dialog can basically cover all 3 of the above operations, but it is not as simple to use, since it provides the operations set and unset. The user has to mentally map his intention (move) onto those atomic operations (unset one, set another). And that is not optimum user experience. Besides that, there are always different kinds of users, which are suited to different ways of work. And for that reason alone we should typically provide multiple ways to reach the same goal (trivial example: I expect that most of us slide between the cache detail pages. But I know for sure that my father will never do that, he always clicks the titles).

**Comment by pstorch** [comment]
;) 
https://geoclub.de/forum/viewtopic.php?p=1249224#p1249224

**Comment by Lineflyer** [comment]
After rereading all the comments I have to admit, that my usecase (add a specific cache to a new list) is already covered in the current implementation (=Copy). So its perfectly right, that all needed options are already there. Sorry for that.
