### ISSUE TITLE
Spoilers not recognized

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5718]
Seems like they are now delivered by https.

**Comment by Bananeweizen** [comment]
This one is a good candidate for an immediate bugfix release, since the change was rather trivial, but basically all users will be affected.

**Comment by Lineflyer** [comment]
Go ahead...dont count on me. Will only be available on Sunday evening.
I did not even see the problen until now.


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Michael Keppler <notifications@github.com> 
Datum: 05.05.2016  10:15  (GMT+01:00) 
An: cgeo/cgeo <cgeo@noreply.github.com> 
Betreff: Re: [cgeo/cgeo] Spoilers not recognized (#5718) 

This one is a good candidate for an immediate bugfix release, since the change was rather trivial, but basically all users will be affected.

**Comment by Lineflyer** [comment]
Note:
Verified by testing non availability of spoiler images using 2016.04.12 and testing the same after upgrading to 2016.05.08-RC (Tested with GC3M1JX)
