### ISSUE TITLE
Filtering by Status=disabled also shows archived

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#5734]
##### Detailed steps causing the problem:
- have a list o caches imported from a GPX generated by GSAK based on geocaching.com data
- filter, select by status = disabled

##### Actual behavior after performing these steps:
disabled and archived caches are shown

##### Expected behavior after performing these steps:
only disabled caches to be shown.

##### Version of c:geo used:
2016-05-09

##### Is the problem reproducible for you?
Yes

##### System information:
```
Android 4.2.1
HW acceleration:disabled
```

##### Other comments and remarks:
If I filter by status=archived, only archived are shown.

**Comment by UniQP** [comment]
I added a PR that should fix the issue.

**Comment by UniQP** [comment]
@andrixnet I was not able to reproduce the issue. Can you provide a corresponding GPX file?

**Comment by andrixnet** [comment]
This file was exported from GSAK. Data in GSAK was downloaded from geocaching.com using native geocaching API (by GSAK) and a premium account.

[_ours.zip](https://github.com/cgeo/cgeo/files/262716/_ours.zip)

After running a "refresh all" from c:geo, the problem dissapeared.

**Comment by UniQP** [comment]
The combination `available="False" archived="True"` surely triggers the problem (the cache is "disabled" and archived at the same time). I guess after the refresh the flags get somehow overridden.

**Comment by andrixnet** [comment]
I've retested with GSAK-8.6.0 (mine was 8.5.1.x previously), same problem.

**Comment by andrixnet** [comment]
I have further investigated the problem, based on the combination above. 
I visited one of my caches, archived: http://coord.info/GC10KZ5
I exported this cache as GPX directly from the webpage.
[GC10KZ5.zip](https://github.com/cgeo/cgeo/files/262900/GC10KZ5.zip)
`<groundspeak:cache id="531595" available="False" archived="True" xmlns:groundspeak="http://www.groundspeak.com/cache/1/0/1">
`
Based on this, **GSAK behaviour is NOT a bug**.

I have checked the situation of an archived cache exported by c:geo. **It is correct:**
`<groundspeak:cache id="531595" available="False" archived="True">`

**Comment by Bananeweizen** [comment]
The cache you mentioned as example is both archived and disabled, so showing it in the disabled filter is perfectly fine.

You are simply confused by our generation of labels in the UI. If a cache is archived, then we show it as state "archived" on the details page, and do NOT add any more labels for disabled (since that doesn't give the user any additional benefit, it just confuses users). Therefore the "scientifically correct" label to be shown in the details would be "disabled, archived", but we simply never show this.

I'm okay with excluding archived caches from the disabled filter for now, since probably most users assume that those 2 are mutually exclusive (and we would basically adopt our filter model to this expectation). However, we have to remember this for the filter UI rework, since combinations of filters might then simply lead to wrong results.

**Comment by andrixnet** [comment]
I would agree semantically that an archived cache is by default not active, thus not enabled, thus disabled. 
While the filter label "disabled, archived" would illustrate properly the current behaviour, from user and usage perspective, it is useful to filter by individual status meaning. 
That is: disabled: show only disabled. Arvhiced: show only archived. 

If multiple filters are to be applied (future filter UI rework), or some other combination, each criteria should be designed to be atomic and , where applicable, mutually exclusive. It would leave much less room for errors.
