### ISSUE TITLE
Feature Request: Add name of adopter to cache description 

### ISSUE THREAD

**Issue by caigner** [cgeo/cgeo#5742]
I recently adopted a cache and when I open the listing in cgeo I still see the original creator of the cache as owner. 

It would be nice if you could change this to something like this:

Created by (or Creator): name of original owner
Owner (only necessary if different from above): name of current owner

Thanks! 
Christian

**Comment by SammysHP** [comment]
Can you please tell us the GC code?

**Comment by caigner** [comment]
Yes, this is it: GC3RKDN

**Comment by UniQP** [comment]
@caigner c:geo shows the name of the original creator because the geocaching.com website also does. You can modify it by editing the cache and put the appropriate name in the "Placed By" field.

I need to check in detail, but I believe that as soon as you adopted the cache, we have no reliable possibility to find out who the creator of the cache was.

**Comment by SammysHP** [comment]
There are always two different owner names: The one that is shown in the listing and the real name of the owner (as the label of the link). c:geo parses and stores both of them. One is shown on the detail page, the other is visible in the context menu of the user. We decided to implement it in this way, because it matches the behavior of gc.com.

**Comment by Bananeweizen** [comment]
Also from the data it is never clear what two different names really mean. It might be a case of someone adopting a cache, but it might also be something totally different like the owner adding a second person to the label, who was involved in the cache creation (e.g. "Jon Doe and friends" shown for owner "Jon Doe").

Additionally, one of the fields is a real user id, the other is plain text. So even if we could see the previous owner of an adopted cache, it would not be possible to invoke any actions on that user name (like you can at all other places, where a user name is shown).

Taking that all together, showing both would lead to more trouble than benefit.
