### ISSUE TITLE
Z order of waypoints and caches

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5755]
I missed a cache today. Reason was that a waypoint of another cache was at the exact same position and the z order on the map was such that the waypoint was topmost. I suggest we add explicit sorting to have caches above waypoints.

**Comment by Lineflyer** [comment]
Remark:
With the new map implementation by @rsudev a popup is offered after clicking offering all different targets for the user to choose...still having a cache over a waypoint on the map is also my preference.

**Comment by Matze2** [comment]
Bringing this two year old issue up again.

Yesterday I was looking for a certain solved mystery on the live map.
After some time I realized that the New Map shows the Final waypoint icon (the red flag) over the Cache icon with the corrected coordinates.

I enabled "Old Mapsforge V3" and the cache icon is shown on the top (as it should be in my opinion).

Verified with the latest nightly 2018.08.06-NB.

**Comment by Lineflyer** [comment]
To my experience the z order is kind of random (possibly due to order of loading the data) and changes on move/zoom every now and then. 

As noted above we have at least the popup when clicking on the layered icons on the new mapsforge. Needs to be done for a possible new Google map as well.
Another topic (and covered in another issue) is, that we could show icon clusters (for zooming out as well as for overlaying icons) to make the user aware, that there are several markers at the same area.

**Comment by Matze2** [comment]
What I want to say is that I never saw this with the old map. For me it was quite irritating to not see any cache icon but only one final flag and a red circle for the original coordinates.

**Comment by Matze2** [comment]
Two pictures show more then 100 words :grin: 

With old map:

![screenshot_2018-08-06-23-53-52](https://user-images.githubusercontent.com/12542802/43743012-708ba34e-99d4-11e8-8c85-d2d126ef5139.png)

With new map:

![screenshot_2018-08-06-23-53-19](https://user-images.githubusercontent.com/12542802/43743022-7ea797da-99d4-11e8-89c8-ace348e4d56d.png)

**Comment by rsudev** [comment]
Has been fixed by 42fb7c167694541e4074c806afa0482e584c3e52
