### ISSUE TITLE
French translations too long with same beginning cannot be distinguished

### ISSUE THREAD

**Issue by TofLaBeuze** [cgeo/cgeo#5785]
Hi c:geo team,

##### Detailed steps causing the problem:
- Go in Parameters -> Maps 
- For french translation, the same text appear on 2 lines "Dossier contenant les cartes ho" (not adapted to mobile width) cause translation too long. The rest of text is not written on the following line.

##### Actual behavior after performing these steps:
Cannot distinguish which line is for offline maps folder (yes, I know now that it's the first one by rotating the screen, but you don't know at the first time...)

##### Expected behavior after performing these steps:
Reduce french translations in cgeo/main/res/values-fr/strings.xml (not sure I have the right...)
1/ Offline maps folder : "Dossier cartes hors-ligne"
2/ Offline map themes : "Dossier thèmes cartes hors-ligne"

##### Version of c:geo used:
last

##### Is the problem reproducible for you?
Yes

Thanks, geo-regards,
Tof

**Comment by Lineflyer** [comment]
I do understand your problem, however it is dependent on the resolution of your device.
If you have a suggestion for a shorter phrase, please feeel free to contribute to the french translation directly on our crowd translation page: https://crowdin.com/project/cgeo

I am closing this issue here as all translations are handled on the crowdin page.
