### ISSUE TITLE
Maps.me is not in "Utility programs"

### ISSUE THREAD

**Issue by R3gi** [cgeo/cgeo#5805]
Maps.me is supported by c:geo, but it's not present in the Main menu → Menu → "Utility programs" category.

I think it should be added, Locus is there too.

**Comment by SammysHP** [comment]
Many apps are "supported" by c:geo. That section is a list of recommendations that should be kept short.

**Comment by R3gi** [comment]
I understand, but why e.g. Locus is listed and Maps.me not? For example personally I would recommend using Maps.me than Locus… It's promoting certain apps at the expense of others.

**Comment by SammysHP** [comment]
Locus has a backlink to c:geo. ;)

But you're right: We are promoting apps that we use often and that we like. This is a personal and subjective selection. We never got money for adding an app! Locus is there as long as c:geo exists and the other apps were added because we thought that they are helpful (and back then there were no alternatives).

**Comment by rsudev** [comment]
Thinking of it, Orux is missing as well. We have dedicated support for like Locus or Maps.me and I currently use it primarily as my mapping application.

**Comment by Lineflyer** [comment]
AFAIR we include maps.me as navigation target even if it is not installed, which then opens a dialog offering to install it. 
Anyway I think the general feedback was, that we keep this list of useful apps to a minimum added after vote from the team.
