### ISSUE TITLE
Saving offline dialog dismissed on rotation

### ISSUE THREAD

**Issue by thepetas** [cgeo/cgeo#5814]
##### Detailed steps causing the problem:
- During downloading details of cache the dialog with progress doesn't show after configuration change (rotation display).

However, cache details were downloading in the background. It's only visual detail(bug).
##### Version of c:geo used:

2016.06.09
##### Is the problem reproducible for you?

Yes
##### System information

Device: ALE-L21 (ALE-L21, Huawei)
Android version: 5.0.1
Android build: ALE-L21C432B170
Cgeo version: 2016.06.09
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: absent
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: cs_CZ
Geocaching sites enabled:
- geocaching.com: logged in (Přihlášení bylo úspěšné) / BASIC
  Installed cgeo plugins:  none

Thank you.

**Comment by Lineflyer** [comment]
Related or same as #2424 (and AFAIR we had exactly this issue already...but I can't find it now).
Did not try to reproduce yet.

**Comment by fm-sys** [comment]
I would like to tackle this issue...

We currently have two different styles in c:geo:

![Screenshot_20200926_183302_cgeo geocaching (Phone)](https://user-images.githubusercontent.com/64581222/94345655-d6a82380-0027-11eb-8a6c-102845187c05.jpg) ![Screenshot_20200926_183238_cgeo geocaching (Phone)](https://user-images.githubusercontent.com/64581222/94345662-dc056e00-0027-11eb-8228-b46fdb3a0367.jpg)

Moreover, the download dialog is coded 6 times from scratch. I would like to exclude this parts into a separate function/class (don't know jet), to make future editing more easy. Which of the two UI styles above is preferred?

By the way the first one gets not dismissed on rotation in the current implementation... 

But the best would be if can avoid this progress dialog totally as already suggested in #330, #5819, #6695...

**Comment by Lineflyer** [comment]
IMHO the left one/first one.

**Comment by fm-sys** [comment]
Android restarts activities on device rotation unless otherwise specified in the manifest. As I'm not sure if changing this will result into new bugs, so I would rather like to try tackling this in a lager context as described in #330. 

@triakcz had done some great work in 2012 but it wasn't finished/merged for some reason. To keep a download service simple I would like to show the download progress in a notification without a special download activity or something like that. In my understanding, this shouldn't be too complicated. I only hope that updating the database from a background service does work without major problems...
