### ISSUE TITLE
Cache doubled after refresh

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5879]
New beta feedback (will translate later)

Hallo. Ich habe einen Cache in 2 Listen gespeichert. Anschließend habe ich ihn in Liste A aktualisiert mit der Folge, dass er in Liste B zwei Mal erscheint. Einmal mit Speicherzeit und einmal mit der Zeit der Aktualisierung.

**Comment by Lineflyer** [comment]
System information:
```

Gerät

Gerät
    ZenFone 5 (ASUS_T00J)
Hersteller
    Asus
Gerätetyp
    Smartphone
Sprache des Geräts
    Deutsch

CPU-Marke
    Intel
CPU-Modell
    Z2560
Native Plattform
    x86, armeabi-v7a, armeabi
RAM (MB)
    1024

Bildschirmgröße
    720 × 1280
Bildschirmdichte (dpi)
    320
OpenGL ES-Version
    2.0
Betriebssystem
    Android 4.4

```

**Comment by pstorch** [comment]
Tried to reproduce it, but couldn't. Anyone else tried it?

**Comment by Lineflyer** [comment]
I can also not reproduce.. might be connected to a special condition (e.g. the only cache on list A or B?!)

**Comment by Bananeweizen** [comment]
I have a hard time getting any clue how this could happen. Looking at the references of dbTableCachesLists in our code, I only see 2 prepared statements actually dealing with updating that table. ADD_TO_LIST should not be able to create 2 identical rows, since the tuple of updated values is also the primary key. MOVE_TO_STANDARD_LIST would have to update the list_id to the standard list for creating duplicate entries, except that this is not possible because of the latter part of the statement.

And generally: Since list_id and geocode are the primary key of the cg_caches_lists table, there _cannot_ be the same geocode twice on one list, right?

**Comment by pstorch** [comment]
I doubt that this is possible in the DB.   Any possibility of a UI glitch? List adapter not refreshing properly? Can we ask the user if it is still the case? Maybe a restart solves it. Even if this is not a satisfying explanation.

**Comment by Bananeweizen** [comment]
I'm also thinking this can only be caused by something wrong in the loader, adapter, or view holder.

**Comment by Lineflyer** [comment]
No more reports like this and no further feedback from beta user.
