### ISSUE TITLE
Coords not sendable to mapy.cz

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5899]
From support mail:

> I would like to describe you a small problem with sending coordinates to external applications (in this case mapy.cz). The problem is that when you send those coordinates, mapy.cz will only show a label (picture) without a pin with exact position (picture). And I would like to point out that it has to work offline as well. It would really make user experience better not only for me, but for many Czech geocachers. Keep up the good work! Thanks.

 2016.06.09

**Comment by Lineflyer** [comment]
Steps:
1) Cache details
2) tap on a map
3) "Other external maps" from the menu -> Mapy.cz app
4) problem described below.

**Comment by Bananeweizen** [comment]
I don't understand where the bug shall be in this case. If you open mapy from cgeo, it points to the exact coordinates (by extending the label with a triangle shape). That is exactly the same behaviour as for all other positions that I can tap on the map. I only get a pin when I start the navigation inside mapy.cz. 

Since I've never used that app before, I cannot be certain, but I guess this is the intended behaviour. If this shall be changed, then there must be a specific mapy API for that, while this functionality uses the generic geo intent of google maps.

**Comment by Lineflyer** [comment]
Closing due to lack of feedback from user on support mail
