### ISSUE TITLE
Map tiles flickering when moving

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5951]
##### Detailed steps causing the problem:
- Use beta map (In my case with germany.map from Openandromaps.org)
- Happens indepdently of used theme
- Open map
- Activate follow me
- Start moving (walking or cycling)
##### Actual behavior after performing these steps:

When the map is updated (due to movement) some tiles are flickering (i.e. short time diappearing and reappering) randomly
##### Expected behavior after performing these steps:

No flickering
##### Version of c:geo used:

2016.09.12-NB
##### Is the problem reproducible for you?

Yes 
##### System information:

Samsung Galaxy S7
Android 6.0.1

**Comment by bfankd** [comment]
Hi, same issue here.
I'm using openandromaps + elevate4 on a Sony Xperia Z5c.
Moving the livemap slightly the caches are disappearing and showing up again after a short while.
Also opening the caches directly from the map takes long. The first one is fast, all the others takes long.. And only when using Mapforce Beta.

**Comment by rsudev** [comment]
@bfankd From @Lineflyer s description I would have said that rather the map tiles themselves flicker, not the caches, so this would be a new/different issue. I checked after your description and could not reproduce it right away. Could you describe perhaps in more detail? Are the flickering caches stored or not? Do you move the map or are you moving and the map is in follow mode? Which version are you using (c:geo - about - systeminfo)?
Regarding the slow popup opening - here we load information from the server if not cached, so opening the same cache twice is not re-doing the same thing. Can you please cross-check that the behaviour is inconsistent between different caches on mapsforge beta and also inconsistent with the standard map (because the popup is running the same code...)?

**Comment by bfankd** [comment]
Hi
I'm doing the following:
- Having some caches saved in a list
- open the list and open the map (Beta defined as standard in Settings + Elevate4)
- Activate "Enable live"
- new caches appearing
- moving the map or touching a unsaved cache - unsaved caches are vanishing and reappearing
- also unsaved caches become "very touch resistant" - means, do not react properly when touching to open.
- the problem does not show, when not using Mapsforge Beta

settings in short:
- Openandromap Alps-West, Elevate4 + Elevate or Elevate2 + Elevate_Hiking.
- Hardware acceleration enabled
- Hardware acceleration disabled creates problem when scolling the list.

**Comment by Lineflyer** [comment]
@rsudev I did not see this happening for a long time...did not even remember this issue. I will close here, feel free to reopen if you remember that its not solved.
