### ISSUE TITLE
Rename "spoiler image"

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#5952]
We got a complaint from a user who expected a spoiler image at the end of the cache description. Actually even gc.com does not write "spoiler images" anymore above the list of attached images.

**Comment by Lineflyer** [comment]
Renaming to "Attached images" would be the correct wording IMHO.
Still I would keep it in the section "Hint" of the cache description tab as users are used to finding it there.

**Comment by akkatracker** [comment]
I agree with @Lineflyer . All that needs to be done is a simple reword of the string.

**Comment by Bananeweizen** [comment]
I must admit I neither get the original complaint (posted by @SammysHP) nor do I understand why you want to rename stuff. [Spoiler](https://en.wikipedia.org/wiki/Spoiler_(media)) is a long established term (not only in geocaching) which indicates that this really gives you a clue and you should not read it/look at it, if you want to solve the riddle on your own. "Attached images" could be anything, i.e. a spoiler image or a harmless (no spoiler) image.

Can anyone tell me what I'm missing or overlooking, since everyone else agreed?

**Comment by Lineflyer** [comment]
It is the fact that this item does not only contain spoilers but maybe also other needed images from the listing....simply everything what is attached to the listing by the owner.

**Comment by pstorch** [comment]
Geocaching.com doesn't distinguish between Spoiler and "normal" images. So from this point of view they are just images.
But opencaching does distinguish them: e.g. https://www.opencaching.de/viewcache.php?wp=OC1EE5
So we could handle them differently here.

Some GC geocache owner name real spoiler images something with "spoiler", but I don't know if this is good enough for c:geo to "guess" it.

**Comment by Lineflyer** [comment]
As there was no clear consent / no clear preference, I will close here unchanged.
