### ISSUE TITLE
Route to waypoints

### ISSUE THREAD

**Issue by lukeIam** [cgeo/cgeo#5958]
## Idea
Use streets and paths to draw a route to the destination waypoint instead of drawing a straight line.
It would be useful in cities as well as in rough terrain.

## What I've done so far
I'm using [BRouter](https://play.google.com/store/apps/details?id=btools.routingapp&hl=de) for offline navigation in Locus and OruxMaps - I thought: why not using it in c:geo, too?

I've implemented a simple prototype using BRouter calculated route for the line to the destination waypoint (BRouter app have to be installed and must have downloaded the routing data for the area):
https://github.com/lukeIam/cgeo/tree/brouter

## Example:
![broutermap](https://cloud.githubusercontent.com/assets/5115160/18482822/fff0470c-79e1-11e6-91e1-9b72ff8c7410.png)

## Next steps
- Are you interested is such a feature at all?
- Better embedding in c:geo: e.g. I just used the MainActivity to initialize the connection to BRouter
- Cache the route and recalculate it only if needed (atm I'm recalculating on every drawDirection()-call)
- Some information how to do it the best way and maybe a bit support (this is my first Android project)

**Comment by SammysHP** [comment]
Interesting idea. Otherwise we decided to make our map not too complex.

If you're working on this, please keep in mind that we are working on the new Mapsforge 0.6 implementation that is in an early stage and will change. You can help us (or better: help @rsudev) and afterwards work on the routing for the new map implementation.

**Comment by samueltardieu** [comment]
In particular, the route computation must not depend on any particular map, so that we can use it with every map implementation (existing or future).

**Comment by rsudev** [comment]
Initially I was a little reluctant, as we already have a huge load of features which makes it sometimes hard to understand and maintain everything.
OTOH can this be very welcome in some cases and the implementation surface is really small and nicely separated. Putting this into a 'routing' layer on the new map as well should be a snap.
I'd say if we can keep this to short-distance routing and still delegate driving to the parking spot to external navigation it is a benefit.

**Comment by lukeIam** [comment]
> In particular, the route computation must not depend on any particular map, so that we can use it with every map implementation (existing or future).

My code is independent from the map type. The most of it is used for accessing the service from BRouter app.

BRouter basically takes start and destination coordinates and returns a list of coordinates for the route.
The only thing a map system must support is drawing the lines between those points.

**Comment by Bananeweizen** [comment]
Basically I've seen everyone here agreeing, reluctantly. Since I wanted to play around more with the new github boards, I've created one just for the routing integration: https://github.com/cgeo/cgeo/projects/3

Feel free to add more tasks, reorder etc. All the _notes_ can be converted to real issues using their chevron menu, to actually have an assignee etc.

**Comment by lukeIam** [comment]
I can't comment or edit the the tasks in the project...

- "Derive from DefaultHandler instead of ContentHandler in the XML parsing" -> https://github.com/lukeIam/cgeo/commit/8d5bfba24f0c30189568ebed1b46fb42e4ea1bdc
- "initialize BRouter on demand only (not in main activity)" -> https://github.com/lukeIam/cgeo/commit/60e32b74bd702eb4a258912ba67ef74a04e01ae2
(Haven't used `MapActivity` as it seems to be destroyed right after lunching a subactivity - using AbstractMap instead)
- "find a way to reduce re-calculation (currently on every drawing)" -> https://github.com/lukeIam/cgeo/commit/dbe19ebd3d722ec85088ddacad198e833412b127
- Added a radius limit for routing -> https://github.com/lukeIam/cgeo/commit/918023013154d514fd4ab109ffb33f963fe43444

Some addition:
- "provide a menu item to select which of the 6 modes (car, bike, walk - fast, short)": There is also a 7th option: using a custom profile (passed as string)

**Comment by Bananeweizen** [comment]
Looks quite good to me. Can you create a pull request from your branch?

**Comment by Bananeweizen** [comment]
I added the necessary menu items and reworked the code quite a bit. For me it is working fine locally. The only missing thing is the porting this to the new map, and describing the usage in the FAQ.

**Comment by lukeIam** [comment]
I used my debug build for a quick cache tour yesterday and I found a problem:
If the destination (or the start point) is not on a road the line is starting on the next road and there is no connection to/from the destination (start).

This could be fixed by always adding the start point at the beginning and the destination point at the end of the calculated route.

But there is maybe an other problem: what happens if there is no street near start and destination?
I haven't tested but I could image something like this:
![image](https://cloud.githubusercontent.com/assets/5115160/18915652/0c5c07c2-8592-11e6-9820-f34c8f94c638.png)

Maybe we can detect such a situation by comparing the distances (just an idea):
```
|| dest - start || < || dest - route.last || + || start - route.first ||
```
and use a straight line instead.

**Comment by Bananeweizen** [comment]
I've just added the missing 2 segments in another fix. I'm not convinced yet, that what you show actually qualifies as a problem or bug. In the images shown above, you _can_ take the direct route, although no routing data is available to prove that. But you can also imagine to stand in front of a house, the cache is at the back of the house and there _really_ is no other way than walking/driving 100 meters to the left, using a side street, turning and going back all the way. That would look very similar to your picture and would really be the shortest solution. That's why I would not change anything here, although intuitively I came to the same conclusion like your first formula, when reading the text.

To my mind the only real solution here is to have the user decide. That means by adding a 4th routing menu option "no routing" we would give him a straight line as before. It would then depend on the choice of the user whether he accepts the routing around the corner or not.

BTW: Please open separate issues for new unrelated issues.

**Comment by Bananeweizen** [comment]
I'm going to close this issue, since all open points have been clarified (and the new map is getting routing right this minute). Feel free to open additional issues.

**Comment by Lineflyer** [comment]
Just a question from my side:
I would call myself a rather experienced c:geo and Android user, but up to now I did not manage to get this running.
I installed the needed app, downloaded what it told me, opened a cache in c:geo and selected Navigate -> Map.
It shows a straight line only.

I think this is not really selfexplanatory...can someone write a draft HowTo which we can later host somewhere for our users?

**Comment by Bananeweizen** [comment]
Currently the distance is limited to 5 kilometers. I completely forgot to lift that limit, now that the path rendering is working without bitmap out of memory.

**Comment by rsudev** [comment]
@Lineflyer Are you sure all the files were downloaded successfully? I had to do it three times to have them finally downloaded and recognized within brouter. After that it worked right away like a charm (I tested with below 5km though)

**Comment by Lineflyer** [comment]
5km might have been the issue. Currently I am mostly offline as I am in Scandinavia. Will give it another try once back home in a week.
Still I am unsure about what exactly I have to prepare in brouter itself to get it working. It does not have a very good UI IMHO.

**Comment by Bananeweizen** [comment]
I also had to download 2 of the 4 German tiles twice. The color seems to indicate the download state, but there is no legend for the colors, so I'm also a bit clueless. I find it helps to re-open the brouter app after a download to see which squares are really checked now.
