### ISSUE TITLE
Remember last list selection

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#5975]
Sometimes I store caches one by one from the live map. Every time I have to select the same list(s) again and again.

Previously we had the "ask for list" option, now I suggest to add an option to remember the last list selection for storing a cache.

This is somehow related to the requested long-press in #5839 as it removes the additional work for selecting a list.

**Comment by Lineflyer** [comment]
But how to change the desired list once you activated the option?

**Comment by rsudev** [comment]
What i could imagine is to perhaps list the last used one at the top - so you can quickly use but als easily switch to another one.

**Comment by SammysHP** [comment]
No, no. The list dialog should be shown, but the ckeckboxes should remember their states. For the second cache it would be just a press on OK.

**Comment by pstorch** [comment]
But only for new caches (not on any list yet). And what if the last cache was stored on more than one list? Preselect all of them?

**Comment by Bananeweizen** [comment]
+1, since I just wanted to suggest the same feature, without knowing this issue exists. However, I would change the implementation:
* Do not have any new option.
* Remember the selected lists only for "the session".

However, there is no real session for apps in Android, so we might need to fall back to something like a simple timeout.

So for me it would be: If the "Select lists" dialog is opened again (for a non stored cache) in less than X minutes after the last time (storing a new cache), all the same checkboxes are pre-selected like they were chosen last time."

**Comment by Bananeweizen** [comment]
Reopening. For me this produces lots of falsely stored caches. E.g. I just stored 2 new event caches which came in via mail. Only some minutes afterwards I noticed that both caches were additionally stored on a list I used several days ago. My hypothesis why it does not work for me: When I store events (or other caches), I already know the list name I'm looking for, and I just scan somewhere in the bottom half area of the selection dialog for "Events". I totally don't notice that there is _an additional_ checked entry at the very top, since I don't even read that part.

I can't imagine that I'm the only user who mistakenly stores caches on multiple lists now. I really suggest to use my previous implementation suggestion that couples the stored list selection to a timeout of some minutes, since after a longer period the remembered list doesn't have any correlation to the current user actions anymore.

**Comment by Lineflyer** [comment]
Yup. This also happend to me.
Either it is only a point, that the user has just to get aware of this new mechanism or we find a more clever approach. 
Maybe the remember last list should be transient (i.e. only be saved for the current session).

**Comment by rsudev** [comment]
Even if I didn't yet accidentally assigned caches to the wrong lists I fully agree that the useful time-frame of this pre-selection is relatively short (even though it IS very useful in just this time frame).
As Android (still) has no real notion of a 'session', I'd say a timeout of ~ three minutes after last usage should cut it nicely.

**Comment by SammysHP** [comment]
The timer should start if the previous action has finished. For example storing many caches with bad internet connection takes some time. If it is finished and I store another cache within a few minutes the selection of lists should be remembered.

Three minutes seems to be a bit short. Maybe 5 or 10 minutes?

**Comment by pstorch** [comment]
Interesting how one feature can benefit one user and be a pitfall for another.
So the discussion is about the right timeframe?
I'm just thinking: what about if it is possible/usefull to distinguish by source. For example as long as using the map, then remember the list selection. When opening the Cache details from a Maillink for example, then don't do it, or remember the selection differently.

**Comment by Bananeweizen** [comment]
> I'm just thinking: what about if it is possible/usefull to distinguish by source.
No. If I opened the map a week ago, and then again today, chances are high that whatever I'm doing right now has nothing to do with what I did a week before. Therefore the app should simply forget about it.

I'll add a 10 minutes timeout and then we see, how that affects users of both factions.

**Comment by pstorch** [comment]
The discussion continued in #6189. 
Should we close this or the other to have the discussion in one issue?
At the moment I'm in favor of the long press option to have the preselection.

**Comment by Lineflyer** [comment]
I think so @pstorch 
This part was fixed sufficiently by adding the 10 minutes timeout.
Further improvement goes into #6189 or any other to be created issue.
