### ISSUE TITLE
cgeo on devices without GPS

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5980]
Starting October 15th, application with no explicit `android.hardware.location.gps` use in the manifest and requiring high precision location will be able to get installed on devices without a GPS.

It means that cgeo will be installable on devices where only network-derived location is available. Do we want this, or do we want to restrict (as I believe it is right now) cgeo to platforms with a GPS to ensure a good user experience?

**Comment by Lineflyer** [comment]
AFAIR we had this discussion in the past already where we introduced the explicit requirement.

From the support point of view I strongly vote for limiting the availability to GPS enabled devices due to:
1. In the past we always had users on support claiming c:geo not working, where it finally turned out, that the device did not have GPS. In addition we had quite a bunch of bad ratings on Google Play due to this. This has stopped finally after the change.
2. Now we have from time to time some users writing us, that they still want c:geo although they are aware that their device does not have GPS. I do link them to our direct APK download. Those users are aware of what they are doing.

**Comment by mucek4** [comment]
+1 to lineflyer's comment

**Comment by samueltardieu** [comment]
> +1 to lineflyer's comment

Not using "reactions" is so 2015 :-)
