### ISSUE TITLE
Export OC caches in field notes

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6014]
Currently the field notes feature is tested on opencaching.de and will be released soon. c:geo does not export logs of OC caches.

**Comment by MacGyver-NRW** [comment]
Remark: There is no OKAPI Support for our Field-Notes Section. This feature is our first one - based on Symfony.

**Comment by Bananeweizen** [comment]
I must admit I totally don't care what underlying technology you use to implement field notes support. I _do_ care about splitting your API of the opencaching websites into multiple, unrelated, and incompatible partial APIs, as long as there is no compelling argument for that.

**Comment by rsudev** [comment]
Should we export a field-notes file per connector? Or go back to the initial implementation, put everything into one file and let the target site pick the ones that belong to it?

**Comment by Bananeweizen** [comment]
If I remember the comments from the OC forum right, they also accept a "mixed" file, like GC. And that probably makes sense for every website, since many dedicated GPS devices probably can't do more than generating such a complete file.

We probably need to change our implementation to care for the fact that the file needs to be uploaded to multiple sites then.

**Comment by SammysHP** [comment]
The OKAPI does not support field notes. So we would need to find a way to authenticate to opencaching.de. For the beginning it should be enough to export all logs, but do not implement the upload to OC.

**Comment by rsudev** [comment]
Just exporting the field notes for all connectors that support it would be a good start IMO as well (we did that back then, and the oc.pl users were not too happy when we removed it...)
If uploading support comes to OKAPI, we than can directly tap into that.

**Comment by SammysHP** [comment]
> we did that back then, and the oc.pl users were not too happy when we removed it...

So why did we remove it then?

**Comment by kyelbek** [comment]
When I started my adventure with geocaching about 2 years ago I downloaded GeoBeagle app first. I could use GC and OC.pl here, and mixed field notes works well on both sites. It's really pain to enter all logs manually. Some time ago I did app backup with TB and changed ROM on my phone. But... I forgot to change one c:geo setting so I lost all my offline logs (about 100 caches). If you are using dedicated GPS device and multiple sites, you'll also get mixed notes, so you shouldn't try to make separate files and play with API's. IMHO solution is simple. Let the others worry if thier sites doesn't support "mixed" files...

**Comment by Lineflyer** [comment]
To come back to this:
As far as we know (and I tested in the past) geocaching.com will ignore field notes for OC caches contained in the export file. 
Meanwhile at least opencaching.pl (since some time) and now opencaching.de (rather new) support field notes in the very same format.
From opencaching.de it was also confirmed that they will ignore contained GC-caches.

So as a quick feature win we should just also export OC offline logs into field notes by just removing the filtering. Can someone implement this on short term?

**Comment by Lineflyer** [comment]
@Bananeweizen If I understand #3771 correct, you filtered the field note file output some longer time ago. Can you revert that?
