### ISSUE TITLE
Create groundspeak contact mail-in

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6035]
As discussed on [IRC](http://irclogs.cgeo.org/?year=2016&month=10&day=16) it would be good to have a contact address where Groundspeak can contact us in case of need.
@mucek4 Could you create e.g. groundspeak@... and make it forward all to cgeo-dev@.... and my gc@... mail address?
@SammysHP Can you allow this mail address to post to cgeo-dev@...

**Comment by SammysHP** [comment]
As I already said in the IRC, groundspeak@ suggests that you can reach groundspeak with that address. Better use something else.

**Comment by Lineflyer** [comment]
How about groundspeak-link@... or gs-link@... ?

**Comment by Bananeweizen** [comment]
I think what @SammysHP is trying to say is that the name should relate to _us_. Like team AT cgeo ORG, since that could be used for contact with other parties than groundspeak and really addresses us as a group. Calling it groundspeak AT cgeo ORG will not make it any more easy for groundspeak to actually remember this for the seldom case it might be used.

**Comment by pstorch** [comment]
team@ sounds good to me

**Comment by Lineflyer** [comment]
ok. team@... sounds reasonable.

**Comment by Lineflyer** [comment]
@mucek4 Are you alive?

**Comment by mucek4** [comment]
ok. team@ and contact@ are created and forwarded. I'll try them now. Sorry for being "not alive".

**Comment by Lineflyer** [comment]
Thanks @mucek4

**Comment by Lineflyer** [comment]
FYA: 
I sent out the mail now as drated on cgeo-dev mailing list. The dev team should have received a copy of that.

**Comment by SammysHP** [comment]
FYI: I obfuscated the addresses in the comments to reduce the risk of spam and users finding the "wrong" support address.
