### ISSUE TITLE
Slow caches download

### ISSUE THREAD

**Issue by GodfatherThe** [cgeo/cgeo#6073]
I observe that storing caches (actually, both SU and COM) takes really long time and also time prediction is horribly wrong - it says "3 minutes left" and downloads for 15 minutes actually.
I suggest to take a look to optimization of the downloading. Maybe use multi-threading, maybe use bulk download API (if possible), or just check for bottlenecks

##### Version of c:geo used:

2016.10.30-NB-057d341

##### Is the problem reproducible for you?
Y

**Comment by Bananeweizen** [comment]
I can download more than 1000 caches in 15 minutes from GC (and 10 times more from OC.DE). If your figures are lower, than you depend on some other external service, which is slow to react. Out of my mind good candidates are gcvote, static maps.

If you are downloading a mixture of caches from different websites together, then the time prediction can easily be wrong and cannot be improved without tremendous effort. Caches are downloaded in parallel, from multiple websites, in the order they appear in your list. If you have more non-GC caches in the first part of the list, the time will be estimated to low, since the GC caches will make the remaining part slower.

**Comment by GodfatherThe** [comment]
Checked the settings and did the following:
- Disabled GCVote in services
- Disabled static maps in offline data settings (btw what is static maps? The picture from googlemap which is being shown in description?)
- Disabled images from logs saving in offline data settings

Now it seems to be a little faster, but still not so fast as I can imagine - ~5 sec per .com cache (varies from 2 to 15 seconds per cache).

**Comment by SammysHP** [comment]
> btw what is static maps? The picture from googlemap which is being shown in description?

Yes.

> ~5 sec per .com cache (varies from 2 to 15 seconds per cache

Which is absolutely fine. We cannot change the speed of gc.com.

**Comment by Lineflyer** [comment]
There are to many factors influencing your test results. The remaining time is calculated based on the mean value of the caches already loaded. If it really takes much longer as displayed in the middle of the process I guess the servers performance is very flaky. That matches also my personal experience of the last weeks.
The only means to get a clear view what is happening would be a debug log where we can probably see if we wait for data or hang on any internal process (which I doubt).
Feel free to come back to us with more clues or a logfile so that we can investigate. Until then please let me close this issue.
