### ISSUE TITLE
Unable to execute dex: method ID not in [0, 0xffff]: 65536

### ISSUE THREAD

**Issue by AndersBillLinden** [cgeo/cgeo#6104]
##### Detailed steps causing the problem:
- Install eclipse and the cgeo project per the instructions.
- Debug it by selecting the project node thats named cgeo (under the folder cgeo) and press F11.

##### Actual behavior after performing these steps:

Error message:
```
[2016-11-08 20:03:54 - Dex Loader] Unable to execute dex: method ID not in [0, 0xffff]: 65536
[2016-11-08 20:03:54 - cgeo] Conversion to Dalvik format failed: Unable to execute dex: method ID not in [0, 0xffff]: 65536
[2016-11-08 20:04:10 - Dex Loader] Unable to execute dex: method ID not in [0, 0xffff]: 65536
[2016-11-08 20:04:10 - cgeo] Conversion to Dalvik format failed: Unable to execute dex: method ID not in [0, 0xffff]: 65536


```
##### Expected behavior after performing these steps:

The project should run in debug mode.

##### Version of c:geo used:

[Version](https://github.com/cgeo/cgeo/commit/20b6fc20c25f7105766fd1e05f933214f2ecb9a5)

##### Is the problem reproducible for you?
Yes

##### System information:
```
Windows 10 Pro 64-bit
eclipse Version: Neon.1a Release (4.6.1) Build id: 20161007-1200
JDK compliance 1.8
```

**Comment by rsudev** [comment]
This is due to a principle limitation in the Android tooling (if you google the error, you will find several places were the background is discussed in all details).
This problem can be mitigated by applying proguard also on debug builds, something Eclipse unfortunately cannot handle on its own. But you can use gradle in conjunction with Eclipse to achieve that. @Bananeweizen can give you more details and feedback on this likely.

**Comment by Bananeweizen** [comment]
That's one of the parts where you can see that ADT has been abandoned by Google. As @rsudev said, it's really not possible to debug from Eclipse anymore since quite a while, given the amount of methods our app has due to its many libraries. You can easily execute all the normal gradle goals by either using one of the pre-defined launch configurations or by using the command line in parallel.

I personally use Eclipse and Android Studio in parallel on Eclipse workspace. I develop in Eclipse and only for actual debugging I switch to AS.
