### ISSUE TITLE
raise min sdk to 14

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6174]
I'd like to raise the min SDK to 14 in the near future. This is somewhat triggered by https://android-developers.blogspot.de/2016/11/google-play-services-and-firebase-for-android-will-support-api-level-14-at-minimum.html.

Technical debt due to old versions has become one of our biggest pain point. And at the same time this gives a benefit only to a tiny number of our users. Therefore let's cut this similar like Google itself (and many other apps out there). This should make life easier for us again when looking for third party components (which are very often only available starting at 14).

If we can reach an agreement on this, then we should add this to the release changes (as a kind of announcement) and also have a facebook post, such that people can still get a new device for xmas. :)

**Comment by SammysHP** [comment]
API 14 = Android 4.0

**Comment by blafoo** [comment]
About ~1.4% of the users would be affected: https://developer.android.com/about/dashboards/index.html#Platform

**Comment by Lineflyer** [comment]
We could proceed like we did last time:Generate a legacs version and maintain it for a limited time and showing a endofsupport message in it.


Von meinem Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: "M@®k" <notifications@github.com> Datum: 03.12.16  12:59  (GMT+01:00) An: cgeo/cgeo <cgeo@noreply.github.com> Betreff: Re: [cgeo/cgeo] raise min sdk to 14 (#6174) 
About ~1.4% of the users would be affected: https://developer.android.com/about/dashboards/index.html#Platform

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@blafoo in #6174: About ~1.4% of the users would be affected: https://developer.android.com/about/dashboards/index.html#Platform"}],"action":{"name":"View Issue","url":"https://github.com/cgeo/cgeo/issues/6174#issuecomment-264635046"}}}

**Comment by rsudev** [comment]
Looking at the stats, cutting a legacy version from the current (ongoing) release sounds like a feasible approach.

**Comment by Lineflyer** [comment]
So all we have to do is merge `release` to `legacy` just before releasing, raise min sdk on `release` and enable a phase out warning on `legacy` for sdk <14. Then we can release two version with that code level.

**Comment by Lineflyer** [comment]
Question to this:
Looking at #6182 I do see a lot of code change while raising the minsdk.
Is this only removal/adaption of no longer needed code (e.g. exceptions for <API 14) or also functional changes going along? Does this need testing?

**Comment by samueltardieu** [comment]
Only removal or adaptation of code (-450 lines), but it will probably need testing to be on the safe side. No functionality change has been done on purpose.

**Comment by Lineflyer** [comment]
So it might be more wise to have a two step approach:
First release when needed fixes are in, then raise the mindsk, test and release again (split into legacy and "normal").

**Comment by samueltardieu** [comment]
Yes.

**Comment by Lineflyer** [comment]
As we have now release 2016.12.28 I suggest to wait 1-2 weeks for possible urgent bugfixes. After that time we could start the procedure by copying 'release' to the 'legacy' branch to freeze it there.

**Comment by samueltardieu** [comment]
This does not prevent us from merging the SDK raise into `master` though.

**Comment by samueltardieu** [comment]
The `master` branch now supports only SDK 14 and above.

**Comment by Bananeweizen** [comment]
Does anyone have a copy of the older changelogs of Android at hand? The official site only goes back to level 16 by now: https://developer.android.com/about/versions/android-4.1.html. I generally liked to go through these and apply all the suggested API changes to our code, so I would like to read those for level 10 to 14 again...

**Comment by Bananeweizen** [comment]
Anyone with a clear understanding of themes? We still want to remove/merge values-v11/themes.xml into the values/themes.xml

**Comment by Lineflyer** [comment]
From IRC of today (sdk versions corrected):
```
[22:07] <Lineflyer> We could now start with branching to cgeo-legacy and set maxsdk=13 there. Maybe we should save the current status of cgeo-legacy to some other archive branch at the same time.
[22:08] <Lineflyer> But others might better now how to do that...
[22:08] <Lineflyer> now=know
[22:08] <Lineflyer> My approach would be to use "cgeo-legacy" branch for rolling out the last version for sdk<14 as CI build tools are prepared to handle it.
```

**Comment by samueltardieu** [comment]
I'll update the closeout message and check on the release branch and proceed to branching it to cgeo-legacy.

**Comment by samueltardieu** [comment]
`cgeo-legacy` is now on par with `release`. I have preserved the previous content into an `old-cgeo-legacy` branch.

When we want to merge `master` into `release`, we should update `cgeo-legacy` from `release` just upfront so that `cgeo-legacy` gets the latest fixes that we made available to SDK < 14.

**Comment by Lineflyer** [comment]
@rsudev Can you upload strings to Crowdin if time permits? @samueltardieu has updated the closeout warning and it needs to be retranslated. Alternatively we could do it by hand as we only need to replace `2.3` by `4.0` in all languages.

**Comment by rsudev** [comment]
update on crowdin done

**Comment by Lineflyer** [comment]
Upgrading the working environment to SDK>=14 has been done.
Urgent fixes for older SDK can be done on `cgeo-legacy`.
