### ISSUE TITLE
History cannot be emptied

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6186]
##### Detailed steps causing the problem:
- Start with empty database
- Save some caches to your lists
- Enter list, open a cache and write an offline log for one of the saved caches
- Offline log status is visible in lists 
- Cache is shown in history
- Open history and select "Clear history"

##### Actual behavior after performing these steps:
Nothing happens

##### Expected behavior after performing these steps:
Hsistory is emptied

##### Version of c:geo used:
2016.12.11-RC (including ded3fb7c41093590b2586ae7e4d756291c9ee3db)

##### Is the problem reproducible for you?
Yes

##### Comment:
Related to #6181

**Comment by pstorch** [comment]
@Lineflyer for deleting caches with offline logs there is an extra menu entry. "clear offline logs". This is the reason why I think they should be separated.

**Comment by Lineflyer** [comment]
Yes, that has become quite unintuitive. 

For deleting offline logs I would expect the cache to stay in history but only have the logs deleted  (did not check that yet).
For emptying history I would expect to remove them from history but keep the associated log.
Otherwise we should simply remove that emptying of history?!

**Comment by pstorch** [comment]
We had the discussion somewhere, that we must prevent a user from accidentally deleting the offline logs. That's why it is the other way around.  When you clear history, the ones with offline logs stay. But if you by purpose choose to clear offline logs, then the history for those is deleted (resetted), too.

**Comment by pstorch** [comment]
Anyway, it's confusing both ways.

**Comment by rsudev** [comment]
For me the history is much less useful with the current semantics as it was before. I guess the changes were mainly introduced as the behaviour was unclear due to some quirks and bugs.
Previously (in theory), every cache that was logged in c:geo (online or offline, regardless of the log type, maybe not for WA) was shown on the history. It stayed there, until the history was cleared manually. You could upload field-note from there and refresh all or a selection of the caches in the history. And you could delete all offline logs (e.g. after uploading field-notes, logging in the browser and refreshing the caches in question).
To me, that behaviour was useful, as I could easily reference from there to caches I recently visited, and as it was a virtual list, it didn't require additional storage.
I think it would be good to go back to the drawing board and define an overall view how the history should work, before continuing to address the current quirks,

**Comment by pstorch** [comment]
I think it just seamed to be clear in the past, but it was as mixed up as it is now. It was just not visible.
At least the offline logs were not always visible (not if `visiteddate=0`, because you could clear history). But they were there and could not be seen nor deleted and were preventing c:geo from cleaning up the DB and the `.cgeo` directory.
Now they stay visible as long as the offline log is there and now we see the misconception. 

When I first read `History` in c:geo I thought it was a similar feature to the recently viewed caches on GC.com: https://www.geocaching.com/my/recentlyviewedcaches.aspx. But it wasn't. 

Yes, let's go back to the drawing board. Let's first define what we understand about `History`, `Offline Logs`, `Latest Logs`, ... and what we want to achieve.

The option with splitting History into Tabs would also not 100% solve the confusion: e.g. when saving an offline found log this cache would appear in two lists (`History` and `Offline Logs`). Then you would have to remove it from both lists.

**Comment by pstorch** [comment]
Here #5124 is also some valuable discussion about offline logs, history and dropping of caches.

**Comment by pstorch** [comment]
@rsudev here https://github.com/cgeo/cgeo/issues/5124#issuecomment-227880647 is a comment from you which shows what I meant with that it was mixed up before, too. It was possible to delete caches with offline logs. They were then gone from all lists, but c:geo didn't physically delete it, because it still had this offline log. And it was not possible to clear the offline log, because you couldn't see this cache anywhere anymore. Now these offline logs are visible in History and it is possible to clear them. But yes, it is not intuitive.

**Comment by Lineflyer** [comment]
@pstorch With the newest nightly I can confirm that your modifications work as intended:
- I had 5 caches with offline log and one cache with status "Found" in my history

Selecting "Delete history" removed the found but kept the caches with offline logs.

Coming back to the discussion:
From the current working mode of our history I think it would be better when "Delete history" is selected also to clear all offline logs in the same step. Even more: The menu item "Delete Offlinelogs" does exactly that....so these two menu items are kind of redundant.
So finally intuitive would be for me:
- "Delete History" would implicitly delete offline logs as well
- "Delete Offline logs" would only clear those caches from history which have an offline log

**Comment by pstorch** [comment]
I also think that those to delete menu items are kind of redundant, at least overlapping. What about combining them into one (or get rid of the extra "Delete Offlinelogs") and ask the user if she wants to delete them, too, if present. 
I know we want to reduce the the extra dialogs, but in this case we would trade an extra (ambiguous) menu item for an extra dialog (sometimes), which would make it clear what happens.

**Comment by Lineflyer** [comment]
@pstorch 
Can you explain that behaviour (from support mail):

>[...]Import eine Homezone-PQ mit 1000 Caches[...]
> Soweit so gut. Beim anschließenden nächsten Cachen gab es absolut keine Probleme, bis ich auf den Cache-Verlauf aufmerksam wurde. Dort waren auf einmal 1065 Caches gelistet.
>"Alles löschen" brachte überhaupt nichts, nur die letzten Caches der aktuellen Tour, waren alles OC-Caches, konnten gelöscht werden, der Rest blieb. Dann kam ich auf die Idee, die Offline-Logs zu löschen, jetzt sieht das Bild so aus:
> Im Verlauf steht eine Anzahl von 1055 Caches, anzeigbar als Liste ist dagegen kein einziger Cache mehr.

**Comment by pstorch** [comment]
Strange. Can't explain right now. Difficult without access to the DB. Do we have more information?

**Comment by pstorch** [comment]
@Lineflyer I'm a little bit curios about the "Alles löschen" he/she performed. This is not a function of the "History". I guess the user tried to delete all caches from his offline list. This doesn't remove the caches directly from the DB (you know this 3 day delay). If these caches have been logged (visiteddate>0) then they still show up in History (even if they are not on any list anymore). The user should try to clear the history and the offline logs.

**Comment by pstorch** [comment]
I just tested a bit more. There is a difference when removing an individual Cache in the CacheDetailsActivity (e.g. via the Trashcan icon) or via "Remove all" in the CacheListActivity. 
The first removes the Cache from all lists and also resets the `visiteddate` (thus removing it from History). The second option only removes the Caches from the current list (thus they are still counted and visible on History). Waiting 3 days for the clean up. To fix the second case we would also have to check if these caches are not on any other lists before also resetting the `visiteddate`.

**Comment by Lineflyer** [comment]
I can remember this from some other issue, where this difference was discussed (cant find it right now).
In order to have a consistent behaviour it would be good to check as you suggested.

But one question:
If I have a cache with offline log stored on my list and delete it. Will the offline log still be shown in both cases you described above?

**Comment by Lineflyer** [comment]
> @Lineflyer I'm a little bit curios about the "Alles löschen" he/she performed.

I asked the user.

**Comment by pstorch** [comment]
@Lineflyer 
> But one question:
> If I have a cache with offline log stored on my list and delete it. Will the offline log still be shown in both cases you described above?

Yes, in both cases the offline logs stay and the caches are shown in history.

**Comment by Lineflyer** [comment]
I requested a DB backup form the user. That should allow us to see what happend I guess.

**Comment by gcPhil** [comment]
@pstorch 
> for deleting caches with offline logs there is an extra menu entry. "clear offline logs". This is the reason why I think they should be separated.

I don't want to annoy, but just like to remember that this is actually not "deleting" the caches. The offline logs gets deleted and the caches is cleared from history - but if they were stored in any other List they remain there and because of the deleted log it is barely possible to filter them for deletion. In my eyes it would be better if "clear offline logs" would really also delete the affected caches from all lists (or maybe ask if it shouldn't do this).

**Comment by rsudev** [comment]
As I have a different usage scenario, such a change would render much of the list ahndling useless for me.
I keep all found caches on my phone and want to continue doing so.
I ususally upload my offline logs as field notes, log online and refresh the stored caches, thereafter deleting the offline logs.
I never want this action to delete these caches from anywhere, I would even prefer to keep them in the history untill I decide to clean it (i.e. I don't like really like the current implementation).

**Comment by pstorch** [comment]
Ok where is our drawing board? :)

I repeat what I understood, please correct me if I'm wrong.

@gcPhil uses the History to find the caches he already logged to be able to delete them without knowing on which list they actually are. He wants to physically remove them from the device, regardless if they have offline logs or not, regardless on which list(s) they are.

@rsudev want's to keep all finds in History and only delete the offline logs, but not the caches them self.
What is your current main pain point with the history?

**Comment by Lineflyer** [comment]
@pstorch I received the DB backup of the user with 1000+ caches on history but non visible. How can I send a link to you....in case you are interested to take a look.

btw: Two other users with wrong count on FB/support mail

**Comment by pstorch** [comment]
@Lineflyer I'll send my eMail to the dev-list

**Comment by pstorch** [comment]
@Lineflyer ok, got it. As far as I can see there are 1054 offline Logs. But none of the geocodes in the `cg_logs_offline` table can be found in the `cg_caches` table. That's why they can't be displayed. I'm not sure how this can happen. When we physically delete the geocache, we also delete the offline log.

Further investigation shows that there is data left for these geocodes in some other tables, e.g. `cg_attributes`, `cg_logs` and others.
Searching for delete on the `cg_caches` table shows one suspicious statement in `DataStore.onUpgrade()` which does `db.execSQL("DELETE FROM " + dbTableCaches + " WHERE reason = 0");`.
This `reason = 0` is an relic from the single list version indicating that the cache is not on a list. And deletes it on DB Version upgrade. Unfortunately doing this in a dirty way (not deleting the related records in the child tables).
I don't know why this DELETE statement is there and I think it should be removed. It doesn't cleanup caches correctly.
We should also extend the `DataStore.cleanIfNeeded()` function to find and delete orphaned database entries like these.

**Comment by gcPhil** [comment]
@pstorch In my eyes your summary is correct. Here is my suggestion that would work for both handlings:

1) Change "Clear offline logs" so that it only deletes the logs and no longer clear the history list at the same time +
2) recreate the missing possibility to delete a selection (selection node) of caches from History and all other lists at the same time. 
Option 2a) caches with offline-logs would stay in history for not creating lost data, but they could get deleted from all other lists with that command. Maybe they could be marked somehow so that people understand why they don't get deleted
Option 2B which I prefer) caches with offline-logs get deleted from everywhere with that delete command and their offline log gets deleted at the same time.

**Comment by pstorch** [comment]
@gcPhil thanks for the clarification. Make sense. 

1) ack (this is @rsudev 's usecase) 

2) ack, I think it is a good thing to have the delete back. 
2a) vs. 2b) what is other people's opinion? 

And what about function 3?
3a) clear history including offline logs
3b) as it is now: keep the ones with offline logs. 
3c) ask if offline logs are present, if they should be deleted, too. 

Maybe it is not that critical to warn/prevent users from accidentally deleting offline logs for 2a) and 3a) because they are marked with a orange bar left to them. From this point of view I'm for the "a" options.

**Comment by pstorch** [comment]
@Lineflyer #6228 fixes the wrong count in the history caused by the orphaned offline logs. I've created a new issue #6226 for that, so that we can continue here with the main discussion about the functionality of the History itself.

**Comment by Lineflyer** [comment]
Regarding the options posted by @gcPhil above:

1) ack!
2a) Definetely better than 2b) because quite some users usecase is, that they expect all the caches they have done (either online logged or offline logged) to appear there (and stay there up to the point they delete them from history). This would also fit into the idea to split history later on into different tabs (looked at, online logged, offline logged)

**Comment by Lineflyer** [comment]
@pstorch 
Just a side note for this issue (its another "problem") regarding `visiteddate`

AFAIR saving already found caches will add all of them to the history as well.
Just try it by opening a found cache and saving it.
Reason is probably that we store the found date of the user found in the logs into the very same `datevisited` and it is therefore catched by the history. 
I might be wrong, as my "test" of this was a longer time ago and code changed.

**Comment by Lineflyer** [comment]
Ah yes, forgot function 3:
3a of course.

**Comment by pstorch** [comment]
> Just a side note for this issue (its another "problem") regarding visiteddate
> AFAIR saving already found caches will add all of them to the history as well.

Yes, that's still the case. Should it not be that way?

**Comment by Lineflyer** [comment]
> Yes, that's still the case. Should it not be that way?

Yes and no. But that is not for this issue.
People think, that they see what they recently logged and suddenly old things pop up. For us it is quite explainable, but people either think it is a local history of c:geo or it is an overall history (like on the website). At that point it mixes up and confuses users.

**Comment by pstorch** [comment]
> > Yes, that's still the case. Should it not be that way?
>
> Yes and no. But that is not for this issue.
Sure, let's keep it separate.


To summarize this issue, the proposal is to have these three functions:
1.) Clear offline logs (and just this, don't touch `visiteddate`)
2.b) Drop caches from all lists including offline logs
3.a) Clear history including offline logs

Comparing the 2b) function with the "Remove all" menu item from concrete lists, it's slightly different and should have a different wording. The "Remove all" in concrete lists only removes all (or selected) caches from the current list. The 2b) function in the History should be called something like "Drop all".
Unfortunately "Remove all" has a wrong translation in german as "Alle löschen" which is not correct. It's more a "Alle entfernen" (still a bit confusing).

I don't want to overly stretch the discussion about this issue, but I want to avoid the next confusion.

**Comment by gcPhil** [comment]
I like this 1+2b+3a solution.  (Don't know when people should like to use 3a with keeping caches in other lists and loosing it's logged status but I don't have to use it, so I don't mind.) 

I agree that the wording is difficult (in each language) because of the complexity and rare place for texts.

What do you think of:
1) clear offline logs - Offline logs löschen
2b) delete everywhere - Überall löschen
3a) clear history - Verlauf leeren

**Comment by pstorch** [comment]
Maybe we just try it with the same wording and test the response.

Would it be ok to have the same "remove all" behaviour in the "All" list and the temporary list?

**Comment by pstorch** [comment]
Current status of PR #6229:

- `Clear offline logs` doesn't reset the `visiteddate`, thus keeping those caches in the history.
- `Clear history` also deletes offline logs if present
- `Remove all` removes the caches from all lists, reset the `visiteddate` and deletes the offline logs if present.

The `Remove all` function is the same as in the `All` list. The `Remove all` in concrete lists only remove from that concrete list and doesn't touch the `visiteddate` nor the offline logs. If wanted I could check if this was the last list and do the same cleanup as in `History` and `All`.

Regarding undo: the `Remove all` function has an undo possibility. But this only reassigns the caches to the lists they were on before. The undo doesn't restore the `visiteddate` nor the offline logs. It's already broken on the `All` list with the `visiteddate`. Doing a full restore would need some more effort.

I would like to have a confirmation, that this behavior is acceptable and if we should keep the menu names.


Additionally: the history counter doesn't count orphaned offline logs anymore. Cleanup will be done in #6226.

**Comment by pstorch** [comment]
Hmm, now the usecase with only offline logs feels a bit clumsy. 
Save an offline log for an unfound cache. Go to History and clear the offline log right away. The offline log gets removed but the cache stays on History because we keep the visiteddate. But in fact I never logged it. 
Maybe we should not set the visiteddate when saving an offline log.

**Comment by Lineflyer** [comment]
> Maybe we should not set the visiteddate when saving an offline log.
IMHO we should keep it like it is. The user interacted with the cache (saving an offline log). Possibly he deleted the offline log as he logged via the website and might want in the next step to refresh the cache to reflect the found state.
So the user is able to still have a "correct" history of last finds.

**Comment by pstorch** [comment]
OK, let's keep the offline log incl. the visiteddate. 

Any objection/opinion about the "Remove all" function to be the same on History and the All list?

**Comment by Lineflyer** [comment]
> Any objection/opinion about the "Remove all" function to be the same on History and the All list?

mmh....Let me summarize:
If I remember the above correctly, this would mean "Remove all" would implictly clear the offline log also when performed on the "All" list?
I am a little unsure about this: How is it done if you use "Remove all" on a dedicated list but the deleted caches are only on this very list (i.e. they will be deleted not only removed from a list)? Does this clear offline logs with your change? In the current release it doesn't.

I can imagine quite some users with the following usecase:
1. Load caches to a list 
2. Go caching, make offline logs
3. Delete list when caching is done
4. Check offline logs and export or log

Therefore 3. should not delete the offline logs.
If now a user (which is not aware or not using different lists or multi lists at all) accidentally uses the all list instead of the default list, he might then experience a different/unwanted behaviour when "Removing all".

**Comment by Lineflyer** [comment]
If you think your PR is mergeable, feel free to merge to `release`. So I could test it a bit. This might be easier for me to play around with different scenario to see if the bahviour matches users expectations.

**Comment by pstorch** [comment]
Do you think someone would first delete the list with all caches and then check for offline logs to export them?
Maybe, there are so many ways of working. Ideally these would be documented in automated integration tests and run by CI. Yes, let me dream a bit.
As you suggested, it's better to actually try it out and see. I'll merge it to release.

**Comment by gcPhil** [comment]
I am not shure if I understood all correct. On the "All" List there is the command "Remove all", but the offline-logs will not be deleted, right? Will the Cache stay in the history then until the offline log gets manually dropped there? (If not, you may create lost data again.)

**Comment by Lineflyer** [comment]
@gcPhil Are you beta user or even using the nightlies? Maybe in that case you can help to test and provide feedback. Regarding your question: I leave it to @pstorch to answer before I am going to confuse anyone as I don't knwo the change 100%.

**Comment by pstorch** [comment]
@gcPhil @Lineflyer the current solution is that the "Remove all" function works the same on "History" and the "All" list. I didn't want to introduce a third version of "Remove all". There are already so many path through the application. It's so easy to change one and break another.

But I'll reopen this issue. The discussion is not finalized in my eyes. And we want to have more feedback from RC.

**Comment by gcPhil** [comment]
I like the actual change but I also agree that the scenario lineflyer discribed is easily possible. If you want to prevent that you should use different actions for "remove all":
- history: deleting cache+ log everywhere 
- "All" list: delete cache from all lists except history and keep log 
- other lists: delete cache from current list and keep log

I know different acting for the same command is not nice and can be very irritating. I event think different acting for "All" and other lists can be irritating. Alternative could be a different name for the command. But I also understand if you don't like to invent new command names every view releases.

@Lineflyer I am beta-user, the last Beta I got over the Play Store is 2017.01.02-RC. Where can I get a newer version to test the latest changes?

**Comment by Lineflyer** [comment]
@gcPhil Newer beta should now be available via Play including the discussed changes.

**Comment by Lineflyer** [comment]
@pstorch 
IMHO we should close this issue and maybe open new followup issues in case of need of more discussion or remaining bugs found in the RC.
My experience tell, that otherwise such issue tend to become longer and longer and one needs to read the whol history to understand what is the remaining issues here as it is no longer reflected by the initial posting. Additionally you can browse the change history and milestones more easy to find out why certain changes have been done.
