### ISSUE TITLE
The Log Date Format in System Information does not always provide the intended information

### ISSUE THREAD

**Issue by mortenvf** [cgeo/cgeo#6284]
Problem:
The Log Date Format actually displays the current date formatted with the date format in use. On some dates, it will not be possible to infer the date format in use. On, say, February 2, the Log Date Format could be displayed as 02/02/2017, but it is not possible to infer which of the formats DD/MM/YYYY or MM/DD/YYYY was actually used.

This feature was implemented in commit 8ad942f

Solution:
Display the actual format string, like DD/MM/YYYY, or, if that is not feasible, use a fixed example date which makes it possible to infer the date format, like December 14 2013.

**Comment by pstorch** [comment]
I'm not sure what the `Log date format` is, but it's just the current date formatted according to the locale of the Android system. Maybe it should be renamed to `Log date` as when this system information was created.

I guess the date format you are looking for is the `Geocaching.com date format`, which is printed a few lines below.
Code is here:
https://github.com/cgeo/cgeo/blob/d8ba3c5704eaa3538c8246e38de03eba7fd4ee08/main/src/cgeo/geocaching/utils/SystemInformation.java#L75

**Comment by SammysHP** [comment]
The problem is that it is shown as an example and something like 10/10/2017 if ambiguous.

**Comment by pstorch** [comment]
Yes, I understood the problem, but I didn't know why we need the `Log date format` from a support perspective. Because I only knew about the GC date format issue we had. 
If we change it, do we loose information about when the system information was created?

Anyway: the current date format pattern is a bit hidden in Android. We could cast to `SimpleDateFormat` and call `toPattern()`, but I don't know if we can rely on that we always get this subclass. 
Another idea would be to use the last day of the current month as the example date, then it's always clear.
