### ISSUE TITLE
[dev] local variable hidden in Android Studio

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#6340]
When in debug mode, editor doesn't show most variables content from functions, this is not easy to track bugs... `Watched` variables also don't display.

It is described here https://code.google.com/p/android/issues/detail?id=93730

**Is this just me or everyone?**

I remember to already have seen this last time I've used Idea.

As a workaround, building without defining `testCoverageEnabled` in `main/build.gradle` solved my problem.

See commit PR.  https://github.com/cgeo/cgeo/pull/6341

**Comment by pstorch** [comment]
I have to disable test coverage, too.

**Comment by Bananeweizen** [comment]
can you try upgrading your android-gradle tools to the most recent version locally, to see if that issue is potentially fixed? E.g. use com.android.tools.build.gradle:2.3.0-rc1 in the build file. You probably need to disable the alpha-version test starting in https://github.com/cgeo/cgeo/blob/master/build.gradle#L105 to make that work, since we normally forbid non release dependencies.
