### ISSUE TITLE
Add option to copy user name

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6359]
##### Detailed steps causing the problem:
- Open detail page of a cache
- Click on owner name

##### Actual behavior after performing these steps:
A menu with many options is shown, however simply copy the user name is missing

##### Expected behavior after performing these steps:
Add an menu entry to copy the owner name

##### Version of c:geo used:
2017.02.23-NB1

##### Is the problem reproducible for you?
Yes/No

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
Same for all other menus, where the user can click on a users name (e.g. logbook)

**Comment by FreddieSanchez** [comment]
I can work on this one.

**Comment by pstorch** [comment]
@FreddieSanchez you are welcome

**Comment by Lineflyer** [comment]
@pstorch Setting you as stand-in assignee (AFAIR thats the way we did it in the past).

**Comment by AlphaDeltaIndigo** [comment]
Same issue in logbook. 
Detailed steps causing the problem:
Open logbook page of a cache
Click on log username

Actual behavior after performing these steps:
A menu with many options is shown, however simply copy the log username is missing

Expected behavior after performing these steps:
Add an menu entry to copy the log username

**Comment by FreddieSanchez** [comment]
@AlphaDeltaIndigo This fix has not yet been incorporated into the release branch yet.
