### ISSUE TITLE
Non-localized export of coords to clipboard needed

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6368]
##### Detailed steps causing the problem:
- Long click on coordinates (e.g. cache coordinates in cache details)
- Select to copy them to the clipboard

##### Actual behavior after performing these steps:
The coordinates are exported as displayed, i.e. they are localized.
Due to this localization (comma as decimal separator) they are useless in many other apps (e.g. Google maps) as they expect the default notation (dot as a decimal separator).
While we have intents for quite a bunch of target apps, there are still users needing to C&P them manually (user on support mail came in with this problem).

##### Expected behavior after performing these steps:
Export non localized coordinates

##### Version of c:geo used:
2017.02.23-NB1

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Reference to #573 where we decided to **display** them localized and #819 where we decided to still **export** them non-localized.

**Comment by pstorch** [comment]
From my perspective the `Geopoint.toString()` and the `GeopointFormatSwitcher` should use the formats ending with `RAW`, these are the non localized ones.

**Comment by samueltardieu** [comment]
I've checked how some sites (localized in French) print coordinates. gc.com, opencaching, Wikipedia, all use "." as a decimal separator in coordinates (while regular French numbers use ",").

I would be in favor of always using "." as coordinates, as they are not meant to be numbers on which you do mathematical operations (they are not a quantity), but of course we should continue to accept "," as input.

**Comment by Lineflyer** [comment]
> I've checked how some sites (localized in French) print coordinates. gc.com, opencaching, Wikipedia, all use "." as a decimal separator in coordinates (while regular French numbers use ",").

I personally agree but this would bring us back to exact the same discussion as in #573 where the outcome was to keep localized...maybe the opinion of others have changed meanwhile?

**Comment by pstorch** [comment]
I would vote for the non-localized format. I guess even None-English speaking users know this coordinate format and it doesn't make any problems when sending to other applications.

**Comment by Bananeweizen** [comment]
In #573 the discussion was mostly about personal preferences. However, actual _consequences_ of either alternatives were merely missing. And since we know about the consequences by now, I'm clearly in favor of your suggestion (display localized, copy/export raw).

Or to rephrase: To me it does not matter, what the most used format is on any German/English/French website is, it matters more how easily and good the coordinates can be used on the device.

**Comment by samueltardieu** [comment]
The most used format discussion was about what to *display*. I think everybody is ok to copy and export the raw (dot) format.

**Comment by Lineflyer** [comment]
OK: So consens of displaying localized (no change) but export non-localized/raw (issue),

**Comment by pstorch** [comment]
I first thought it's an easy fix, but then I stumbled upon my own quickhack `GeopointFormatter.reformatForClipboard(clickedItemText)` and ended up in bigger refactoring. I even thought about implementing a special subclass of TextView with a built in `CoordinatesFormatSwitcher` which would offer the corresponding raw value for export. But then I felt this might be overdose.

I stepped back and thought about a simpler solution: what about if we just switch through (localized and non-localized) formats and copy exactly the one which is visible right now? That would be the functionality of least surprise (what you see is what you get). Otherwise we would copy a different value than what is visible.

At the moment the `CoordinatesFormatSwitcher` only uses a subset of formats from `GeopointFormatter`:

```
        LAT_LON_DECMINUTE /** Example: "N 10° 12,345 · W 5° 12,345" */
        LAT_LON_DECSECOND /** Example: "N 10° 12' 34" W 5° 12' 34" */
        LAT_LON_DECDEGREE /** Example: "10,123456 -0,123456" */
        UTM /** Example: "32U E 549996 N 5600860" */
```

If we just add these two unlocalized formats:
```
 LAT_LON_DECMINUTE_RAW /** Example: "N 10° 12.345 W 5° 12.345"  (unlocalized, no middle dot) */
 LAT_LON_DECDEGREE_COMMA  /** Example: "10.123456,-0.123456" (unlocalized) */
```

Then we could get rid of my older hack and offer localized and non-localized formats for display and copy & paste. 

The only downside is that a user has to skip through two more formats where some are very similar to each other.

What do you think?

**Comment by Lineflyer** [comment]
I don't think adding non localized formats is meaningful:
- The typical non-heavy user of c:geo may not even know that he is able to click to switch formats
- Other users won't understand why some formats appear "twice"

As you describe the fix as too complicated, I think it may be wise to just switch to non-localized completely for display and export...however just my opinion and different to what was decided some time ago.

**Comment by pstorch** [comment]
Actually it can be achieved quite simple by searching for comma and replacing by dot. I already did similar hack with removing the middle dot before copying to the clipboard. But I don't feel good with that.

**Comment by Bananeweizen** [comment]
I'm in favor of the hacky solution here, since it has the least side effects (no additional formats to switch) and just works (for the user).
