### ISSUE TITLE
Map opens for search result without coordinates

### ISSUE THREAD

**Issue by Jorgixhallo** [cgeo/cgeo#6394]
##### Detailed steps causing the problem:
- Step 1
Filter By Type on initial menu: Letterbox
- Step 2
Search location and retrieve caches (in my case "Lisbon")
- Step 3
Click Map Icon

##### Actual behavior after performing these steps:
Shows empty map
If I click a cache on list, and click map again it shows the one I clicked.

##### Expected behavior after performing these steps:
Showing All caches that were listed on map

##### Version of c:geo used:
Beta (2017.02.28-RC)

##### Is the problem reproducible for you?
Yes. With other filters (wherigo caches) it shows more caches on map, but still not shows all of them.

##### System information:
```
--- System information ---
Device: SM-J320FN (j3xnltexx, samsung)
Android version: 5.1.1
Android build: LMY47V.J320FNXXU0APH1
Cgeo version: 2017.02.28-RC
Google Play services: enabled - 10.2.98 (236-146496160)
Low power mode: inactive
Compass capabilities: no
Rotation vector sensor: absent
Orientation sensor: absent
Magnetometer & Accelerometer sensor: absent
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: pt_PT (cgeo forced to English)
System date format: M/d/y
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: MM/dd/yyyy
Installed cgeo plugins:  none
--- End of system information ---
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by SammysHP** [comment]
You are a basic member, so search results do not include coordinates. IIRC it should be only possible to open the map from a list if at least one of the caches has coordinates. Can you try to disable all filters, search in a region where you never opened any cache and then try to go to the map?

@Lineflyer Maybe you can test this with a basic member account.

**Comment by Lineflyer** [comment]
There is an open issue to prevent mapping a list of caches without coords. Right now this is not prevented.There is only a FAQ entry about this to make basic members aware of that.


Von Samsung-Tablet gesendet

-------- Ursprüngliche Nachricht --------
Von: SammysHP <notifications@github.com> 
Datum: 09.03.2017  16:40  (GMT+01:00) 
An: cgeo/cgeo <cgeo@noreply.github.com> 
Cc: Lars <gc@droescher.eu>, Mention <mention@noreply.github.com> 
Betreff: Re: [cgeo/cgeo] Caches on List not showing when I click (#6394) 

You are a basic member, so search results do not include coordinates. IIRC it should be only possible to open the map from a list if at least one of the caches has coordinates. Can you try to disable all filters, search in a region where you never opened any cache and then try to go to the map?
@Lineflyer Maybe you can test this with a basic member account.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SammysHP in #6394: You are a basic member, so search results do not include coordinates. IIRC it should be only possible to open the map from a list if at least one of the caches has coordinates. Can you try to disable all filters, search in a region where you never opened any cache and then try to go to the map?\r\n\r\n@Lineflyer Maybe you can test this with a basic member account."}],"action":{"name":"View Issue","url":"https://github.com/cgeo/cgeo/issues/6394#issuecomment-285386819"}}}

**Comment by Jorgixhallo** [comment]
@SammysHP Can confirm that the search on the new place doesn't retrieve any cache on the map.

Assuming that we have the GC of each cache on the list, shouldn't it be theoretically possible to retrieve the coordinates (individually) and show them on the map? The only problem with this "vision" is the time that it could take to retrieve each one individually.

**Comment by rsudev** [comment]
Of course it is, but as you mentioned, this would require quite some time and data to download. You can decide to do that, by using the 'store offline' menu item and after that show them on the map.

**Comment by Jorgixhallo** [comment]
Thank you. I will mark this as close as it is not an real issue.

Thanks for the answers.

**Comment by SammysHP** [comment]
Just an additional note: Until some months ago it was possible to get the coordinates by entering a captcha for each search result. This was removed because of the bad user experience, reliability issues and code complexity.

**Comment by Jorgixhallo** [comment]
I think that, when searching by address, when you click on the map icon it should show the coordinates of the point (location/town) so you can live search it then... There's no ability to "jump" to that location (approximate) on map, am I correct?

Lets say I search for "Berlim" caches. Even if they don't show any cache on map, it should jump to the map and allow me to perform live search after.
