### ISSUE TITLE
Let CI check all commits of a pull request

### ISSUE THREAD

**Issue by UniQP** [cgeo/cgeo#6497]
For pull requests with multiple commits, the CI currently only checks the last commit. It would be nice if it checks all commits (starting with the last one, stopping on failure?) to ensure that each commit passes all tests. Commits that doesn't pass the tests may become annoying when searching a bad commit via `git bisect`.

**Comment by Bananeweizen** [comment]
The recent merge strategy discussion (some weeks ago) said to squash PRs with multiple commits. Assuming we do that, such a thing is not necessary, since there will not be any intermediate commits afterwards. :)

**Comment by samueltardieu** [comment]
Which I still think is not a good idea. There is no one-size-feets-all approach to merging. For example, the PR from @UniQP I merged recently had two separate commits with very different purposes (but the first one needed the second one), and it would have made no sense to squash them. Sometimes, it is indeed better to squash commits when they are successive refinements.

Also, some of us use PR to get the CI to test our code and let people comment on it, and we want our code to be either merged or rebased afterwards.

I'm not reopening the squash/rebase/merge discussion, merely presenting arguments to get individual commits checked.

**Comment by UniQP** [comment]
@Bananeweizen Which discussion are you referring to? In https://github.com/cgeo/cgeo/issues/5617 we decided against squashing and in https://github.com/cgeo/cgeo/issues/5995 we decided for rebasing. I currently can't remember any other discussion.

**Comment by Bananeweizen** [comment]
@UniQP Maybe I remembered it wrong because of the PR from Lineflyer.

But coming back to the topic, I'm not aware of any option to make the pull request builder plugin check each commit as such. I only know it to check versions of pull requests. So if the initial PR contains more than one commit already, I see no way to check these separately. Only if you start the PR with one commit and _then_ add more commits to it.

I've checked the documentation, the Jenkins job settings, and the webhook settings. I believe the webhooks don't even contain this information (they just point the most recent commit), and we would have to manually find the commits between upstream head and PR via some script to trigger multiple Jenkins builds.

**Comment by UniQP** [comment]
I opened an issue: https://github.com/jenkinsci/ghprb-plugin/issues/511.

**Comment by Lineflyer** [comment]
> I've checked the documentation, the Jenkins job settings, and the webhook settings. I believe the webhooks don't even contain this information (they just point the most recent commit), and we would have to manually find the commits between upstream head and PR via some script to trigger multiple Jenkins builds.

I agree and we also use to squash to one commit as best-practice, whereas we do not have the need to test each commit of the PR as it usually contains only one commit.

Additionally the issue opened by@uniqp has been closed without changes (see link above).
So lets close here.
