### ISSUE TITLE
Backup not found

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#6505]
##### Detailed steps causing the problem:
- Created backup using 2017-03-29 developer version.
- Uninstalled the app.
- Installed developer version of today.

##### Actual behavior after performing these steps:
Backup not found. File /.cgeo/cgeo.sqlite exists.

##### Expected behavior after performing these steps:
Backups from both old and new locations should be found, since this is a rather normal migration use case.

**Comment by Bananeweizen** [comment]
@pstorch I've added a redirection to the deprecated location for restoring a backup, to get my application running again. Please have a look whether this fits your concept.

**Comment by pstorch** [comment]
@Bananeweizen I think this is not the "normal" migration use case. 
You have done the backup with the new version? Then the backup should have been in the new directory. 

"Normally" you would have done a backup in the old version and on migration (update to the new version) the backup file would have been moved to the new location. While writing this, I think about the process of uninstalling the old version manually and later installing the new one. Does c:geo recognize that a migration has to be done? 

But otherwise looking additionally at the legacy directory doesn't hurt either.

**Comment by Bananeweizen** [comment]
I've done the backup with the old version (I'm rather sure it did not contain any of the new directory logic, independent of the exact build date, since I wanted to avoid that code before travelling to Asia a month ago), then uninstalled manually and installed the new version. I'm not sure if cgeo recognized to migrate anything, I have not seen any UI indicating a migration. I'm fine with closing this.

**Comment by pstorch** [comment]
I'm curious. I'll test it again this evening with normal upgrade and uninstall/reinstall.

**Comment by pstorch** [comment]
Verified it: 
- if upgraded c:geo properly moves the backup to the new location. 
- if uninstall old and install new, then c:geo doesn't recognize the legacy directories and doesn't move anything. 

The migration is recognized at the shared preferences version. And I guess these are deleted on uninstall, so c:geo thinks it is a fresh install.
