### ISSUE TITLE
Add ISO 8601 preference

### ISSUE THREAD

**Issue by mirabilos** [cgeo/cgeo#6526]
Similar to how the user can choose to use the English UI no matter the Android system language, please add a preference for ISO 8601 dates (YYYY-MM-DD) to c:geo.

My Groundspeak preferences already use this format, so c:geo displaying unparseable dates (“01/02/2017”) is not a service provider issue. At OC.DE, one cannot even set this…

**Comment by samueltardieu** [comment]
The date should be in a familiar format as we generate it using the system preference. You should petition Google to include ISO 8601 dates in Android as a user preference.

Note that your analogy to choosing English over the system language does not hold. This choice is not meant to set cgeo in a different language than the other applications, it is meant to have a safe fallback in case the application is only partially translated or is mistranslated.

However, I think this request is reasonable, and myself would probably use it if someone was to implement it.

**Comment by Bananeweizen** [comment]
The format selected in the groundspeak preferences is used for parsing only. The format from your Android locale setting is used for displaying, so at least everything should be consistent when being displayed on your device.

**Comment by mirabilos** [comment]
Michael Keppler dixit:

>only. The format from your Android locale setting is used for

Unfortunately, I have yet to find a place in Android’s settings
where I can set the date format ☹ (yes, c:geo isn’t to blame for
this particularity).

But this makes me think that no such “Android locale setting” exists.

**Comment by Lineflyer** [comment]
> Unfortunately, I have yet to find a place in Android’s settings where I can set the date format ☹ (yes, c:geo isn’t to blame for this particularity).

Indeed. At the time we analyzed some date format issue I have read some long thread at least where users confirm for at least all the Samsung S series not having a setting for this.
There once was a problem, that English(UK) users have been forced to use the "american notation" due to a missetting in Samsung firmware.

However from my user/testers perspective I am totally fine with following the system defaults. That is probably what the user expects and also sees in other apps.

BTW: If you force c:geo to English (in settings) it will also force the date format to "american notation".

**Comment by mirabilos** [comment]
Lars dixit:

>BTW: If you force c:geo to English (in settings) it will also force
>the date format to "american notation".

... which is even worse, and supports my point of adding a switch
to force ISO 8601 date format to c:geo's settings.

Why should the date format be hard-coupled to the language, anyway?

**Comment by mirabilos** [comment]
Oh, this is funny… on my Android 4.4 device I can change it in the Date & Time settings to yyyy/mm/dd which is still wrong but better. This *does* show up in c:geo logs, but the cache details have "d mmmm yyyy" format (which is also only _close_ to DIN 5008’s long/alphabetical format, but not quite there).

So a c:geo-specific ISO 8601 date setting would still be preferable — especially for newer Android devices which lack the format selection altogether.

**Comment by Lineflyer** [comment]
@mirabilos Can you check up whether this is still of relevance in current Android versions in conjunction with recent c:geo versions?

**Comment by mirabilos** [comment]
2021.06.23 (Google Playstore) is still affected, at the very least.

**Comment by eddiemuc** [comment]
My 5 cents:

since now you can even choose every language in c:geo settings (and also choose between metric/imperial length units), it would seem logical to me to offer a date format choosing as well.

![image](https://user-images.githubusercontent.com/6909759/125175564-6c82f880-e1cd-11eb-8ce6-be3f6926b48d.png)
