### ISSUE TITLE
Please, provide a possibility to get some statistics of the current list

### ISSUE THREAD

**Issue by FUSSEL4** [cgeo/cgeo#6541]
##### Detailed steps causing the problem:
- open a list in c:geo
- after a long day of geocaching one wants to know what the average difficulty or average terrain value of the found caches is.

##### Actual behavior after performing these steps:
- there is no easy way to calculate those statistical data right in the app.

##### Expected behavior after performing these steps:
- one-click, and there is a statistic dialog with the desired data

##### Version of c:geo used:
2017.04.27-RC

##### Is the problem reproducible for you?
Yes. No really a problem but time-consuming.

##### Other comments and remarks:
Just a feature for those of us who's interested in statistics.

**Comment by SammysHP** [comment]
IMHO there are enough tools to get statistics after you've logged the caches.

**Comment by FUSSEL4** [comment]
@SammysHP You are right what concerns statistics for logged caches. But my idea is to have a little info about the caches in a certain list in c:geo no matter whether they are logged or not.

**Comment by Bananeweizen** [comment]
This is a feature for just a handful of users, since it is completely arbitrary and does not fit any _common_ use case of the majority of users. To me this is as reasonable as showing the time of sun rise somewhere in the app, since I then know when I can start geocaching in the morning.

Sorry, but no, this just doesn't fit into the app. I would rather look at the stastics of project-gc.com or check the scripting features of GSAK to get your desired data.
