### ISSUE TITLE
Proposed restructuring of the cache list menu

### ISSUE THREAD

**Issue by FUSSEL4** [cgeo/cgeo#6546]
##### Detailed description of the problem:
Adding new functions to the cache list causes a growing of the menu.
Issue [#6528](https://github.com/cgeo/cgeo/issues/6528) asks for a new functionality which adds an additional menu item. In that issue I suggested a restructuring of the main cache list menu.

##### Actual behaviour:
A lot of menu items...

##### Suggestion:
Restructuring of the menu like this:
* Show on map
* Filter
* Sort
* Switch select mode
* Invert select mode
* Manage cashes 
** Refresh all / selected
** Move all / selected
** Copy all / selected
** Remove all / selected 
** Delete offline-logs
** Delete past events
* Manage lists
** Create new list
** Remove current list
** Rename current list
** Make list unique
* Import
** Import GPX
** Import from send2cgeo
** Import from Android
* Export
** Export GPX
** Field notes
** Personal notes
* Remove from history

**Comment by Lineflyer** [comment]
Thanks for listing it as dedicated issue. So other core team members can also provide their feedback here.
I will have a look into it next days and also comment here.

**Comment by FUSSEL4** [comment]
I'm currently working on the implementation...

**Comment by SammysHP** [comment]
Some entries are missing in your draft, e.g. "show on map", import and export submenus. Also please compare with the history where a lot of entries are missing. Your proposal would introduce a lot of submenus which makes it more complicated to use.

**Comment by Lineflyer** [comment]
Here is my feedback.
General:
On one hand of course more submenus will make it more complicated to find and use all items, on the other hand I am a friend of clear tree structures instead of long lists as it might be even faster for the user to find the right menu item if they are better structured instead of reading through a long list of items.

Detail:

>    Sort
>   Select mode
>   Caches

I suggest naming it "Manage Caches"

>    ** Show on map

This could remain on the top level as 
- it is not about dealing with caches as the other items in that submenu
- It contains another submenu

>   Lists

I suggest naming it "Manage Lists"

>    I/O
>    ** Import
>    ** Export

Here I suggest to keep Import and Export on the main level (as they also contain another submenu) and the I/O would only have two items anyhow.

For the history list (as also mentioned by @SammysHP) the "Empty history" function is missing in your proposal. This should be kept on main level IMHO.

**Comment by FUSSEL4** [comment]
I completed the menu, and I did some re-ordering like suggested by @Lineflyer and @SammysHP.

**Comment by Lineflyer** [comment]
Any other votes pro or con?
IMHO this (see PR #6551) looks like a good structure for users to still find all items. If there is no objection maybe someone can check the PR codewise and merge it for testing. Corrections can be done afterwards if needed.

**Comment by pstorch** [comment]
I like the new menu, it grew to big anyway.

**Comment by Cappa-d** [comment]
For me it looks good -- go ahead ;)

**Comment by SammysHP** [comment]
With a shorter menu we could also think about disabling menu items instead of hiding them. It's easier to use a GUI if elements are always at the same place. What do you think about that? @Lineflyer @FUSSEL4 @pstorch

**Comment by pstorch** [comment]
@SammysHP +1. Disabling is better than hiding. I would also suggest to have the "one click offline log" visible all the time.

**Comment by Lineflyer** [comment]
+1 for disabling instead of hiding.

**Comment by pstorch** [comment]
Do we want to continue the "disable vs. hide" discussion here or open a new issue for it?

**Comment by Lineflyer** [comment]
New issue.
