### ISSUE TITLE
Disable menu items instead of hiding them

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6578]
Follow up of #6546:

@SammysHP wrote:
> With a shorter menu we could also think about disabling menu items instead of hiding them. It's easier to use a GUI if elements are always at the same place. What do you think about that? @Lineflyer @FUSSEL4 @pstorch

I think we have +3 so far for this proposal looking at the replies in #6546 and reactions on the posting.

**Comment by mirabilos** [comment]
SammysHP dixit:

>that feature request is accepted. As I explained, it should be quite
>obvious that there is "something" behind the menu items. It might take

Probably, but without any visual hint I’d expect it to switch to
some complicated “management UI”, not just open a sub-menu.

>a while for long-time users to adapt to the new menu, but I think that

(Not actually that long-time here…)

>is is more structured and easier to use than the previous endless
>list.

**Perhaps.**

On the other hand, *casual* users will be *much* less able to
discern what the software can do and how by just looking at the
menu items and/or visually searching for things.

Imagine you cannot remember how something was named and don’t
even want to think about into what category the developer of
the software may have put a particular functionality. In those
cases, scanning a linear list, even if it’s 1¼ screen pages long,
will win.

Case in point: you thinking that “Clear history” was in the
other of the two.

Small suggestion (although I don’t know if / how much this
would actually improve the nested menu situation): make there
be only *one* menu point with a submenu, instead of multiple.

Consider websites where users often react allergic to submenus
as well (although probably for different reasons…).

Thanks!

**Comment by Lineflyer** [comment]
> Imagine you cannot remember how something was named and don’t
even want to think about into what category the developer of
the software may have put a particular functionality. In those
cases, scanning a linear list, even if it’s 1¼ screen pages long,
will win.

I can't imagine one advanced app having only one long menu instead of a structure.
Think about apps you know or even desktop apps...what if Excel would have all options in one menu list instead of a structure. Sure, somtimes it helps finding a less used option but most of the times it should provide a guide to the user.

I agree, that non advanced users should have no disadvantage....but I guess they don't have as the basic things are at other places. People using the "Manage caches" or "Manage lists" are probably advanced users, while basic users are just using stored list and adding or removing single caches from/to it.

**Comment by mirabilos** [comment]
Lars dixit:

>People using the "Manage caches" or "Manage lists" are probably
>advanced users, while basic users are just using stored list and
>adding or removing single caches from/to it.

I strongly believe this to be a fallacy. Cachewolf was so good
*because* of its strong cache management facilities, which were
in fact used by users.

**Comment by pstorch** [comment]
I looked at it a bit. Just disabling instead of hiding gets a bit messy. Maybe we need to think about the one or the other item and make it more consistent. Some submenus get very empty depending on the list type.

Some examples.

A normal list shows now the "Invert selection" and an unnamed item for the "Cache List App":
![screenshot_20170606-220618](https://user-images.githubusercontent.com/5598124/26849694-78ab0cd2-4b05-11e7-99d7-da9fa9fd266d.png)

The "Manage caches" now shows the "Clear history" which is usefull only in the History list:
![screenshot_20170606-220634](https://user-images.githubusercontent.com/5598124/26849917-146e1344-4b06-11e7-93d3-67cefb6508d9.png)

The "All caches" menu (you can import GPXe here, but they get stored in "Stored"):
![screenshot_20170606-222426](https://user-images.githubusercontent.com/5598124/26850231-1429ab54-4b07-11e7-8d7c-9832607ca361.png)

The "All caches" submenu "Manage lists":
![screenshot_20170606-220720](https://user-images.githubusercontent.com/5598124/26849956-2ea07fcc-4b06-11e7-813e-7ec2a4da2c71.png)

The "Stored" submenu "Manage caches"
![screenshot_20170606-220903](https://user-images.githubusercontent.com/5598124/26850014-64dd259a-4b06-11e7-993c-91584ebbf4f2.png)

The "Stored" submenu "Manage lists":
![screenshot_20170606-220927](https://user-images.githubusercontent.com/5598124/26850082-9c1aa726-4b06-11e7-8535-03fdadcbabd8.png)

The "Nearby" menu:
![screenshot_20170606-221007](https://user-images.githubusercontent.com/5598124/26850105-aeb59788-4b06-11e7-87d4-bfeec4c22131.png)

The "Nearby" submenu "Manage caches":
![screenshot_20170606-221033](https://user-images.githubusercontent.com/5598124/26850143-cb9d6470-4b06-11e7-9958-36157fcb728d.png)

**Comment by Lineflyer** [comment]
Indeed, the disable instead of hiding has some traps.
From looking at the screenshots I would suggest to still hide items on the main level instead disabling.
This would keep the first view cleaned up.

Within the submenus we can have them disabled...but what are the cases where submenus have only disabled entries?

**Comment by mirabilos** [comment]
The current NB anyway has submenu entries that just don’t do anything (probably because they are empty), and I still **really** wish there were some way to get those arrows on Android 4.4

**Comment by pstorch** [comment]
Ok, let's decide to do it differently for toplevel menu entries versus submenu entries.
Toplevel items: hidden (as before)
Submenu items: disabled

That would mean hide toplevel items, if it is a submenu with only disabled entries.

The way Android calls the `onPrepareOptionsMenu()` with each individual item, it is not easy to check if all submenu entries are disabled.
I'll look into it.
