### ISSUE TITLE
StringUtils.join: java.lang.NoClassDefFoundError: java.util.Objects on API Level 16

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6607]
While working on #6605 I stumbled upon this error which happens in an Emulator with API Level 16:
```
06-20 22:13:40.997 3738-3738/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
                                                               java.lang.NoClassDefFoundError: java.util.Objects
                                                                   at org.apache.commons.lang3.StringUtils.join(StringUtils.java:4659)
                                                                   at org.apache.commons.lang3.StringUtils.join(StringUtils.java:4720)
                                                                   at cgeo.geocaching.log.CacheLogsViewCreator.addLogCountsHeader(CacheLogsViewCreator.java:87)
```

**Comment by pstorch** [comment]
Here https://stackoverflow.com/questions/37778644/java-lang-noclassdeffounderror-java-util-objects they say the static methods in `java.util.Objects ` are available above API 19 (Android 4.4.+).
But we have successfully tested c:geo on some lower level API devices, right?

**Comment by Bananeweizen** [comment]
Actually, the Android platform is mostly identical with the Java 6 platform in terms of API. We do have additional Java 7 language features (diamond operator etc), but not generally the complete Java 7 API. You must differentiate these 2 (which objects to program against and how to write your code). Additional Java 7 API has been backported on different Android API levels, but to my knowledge that is not complete.

The problem is our usage of libraries which have been developed with pure Java in mind only. Those easily use Java API, which is not part of the Android platform, and the build process for those is completely fine (since only Java compiler etc. are involved, no Android tooling). Some of those libraries are meanwhile specified against Android too (e.g. AssertJ has an Android compatible Java6 branch), but most don't care. Generally, we see those issues with Proguard in our build, but we might be a bit to fast in masking out the warnings: https://github.com/cgeo/cgeo/blob/master/main/proguard-project.txt#L58

Therefore it might be useful to find the last commons.lang version not including any Java 7 API on its own, and then prohibiting further upgrades in our top level gradle build file. I'll check if I can find something by removing related Proguard rules and including lower versions.

**Comment by Bananeweizen** [comment]
So this was only buggy for the last 3 days, since the commons-lang update. However, I was not able to get Proguard to warn me about this, I basically checked the sources of StringUtils instead. So this might happen with other libraries in the future, too.

**Comment by pstorch** [comment]
Thanks for the insights and the fix :+1: 
I'm not very familiar with Proguard and its configuration.
