### ISSUE TITLE
Add PQ list to import menu

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6658]
The import menu should contain an option to open a list with all downloadable PQ. The selected PQ should be imported to the active list (or open the dialog with the active list pre-selected).

**Comment by pstorch** [comment]
Good idea, I've missed the PQ download in the import menu, too.

**Comment by pstorch** [comment]
The dialog with the list of PQs has two functions:
1. show a temporary list of geocaches loading 20 at a time
2. download a complete PQ and store in a list

The second is only possible if the PQ is downloadable. 
For this feature it only makes sense to show the downloadable PQs, because the intention is to download the PQ into the current list. Not open another temporary list.

In my proposed solution I filter this dialog to only show the downloadable PQs, if opened via this new import menu of an existing list.

**Comment by Bananeweizen** [comment]
#3291. :)
@pstorch Your proposed solution seems very reasonable.
