### ISSUE TITLE
Coordinate calculator wrongly assumes all variables are digits

### ISSUE THREAD

**Issue by Natureshadow** [cgeo/cgeo#6665]
The coordinate calculator assumes that the result of every calculation is a single digit for a single place in the coordinates.

In fact, today, when I first tried it in the field, I had only one calculation for the whole decimal part of the minutes, and it proved to be useless… I think the feature is great, but it needs to be more flexible to not cause agony.

**Comment by pstorch** [comment]
Only use the first digit of the decimal part. Long click of the second and third digit and enter a blank.
Now you can use a 3digit result for the first variable and fill the whole decimal part.
It's not self explanatory, that's why @Lineflyer proposed #6664

**Comment by S-Bartfast** [comment]
> The coordinate calculator assumes that the result of every calculation is a single digit for a single place in the coordinates.

That definitely shouldn't be the case.  Could I get you to provide more details on how you found yourself restricted?

As pstorch has pointed out it is indeed possible to 'blank-out' digits, but even without using the blanking-out feature it should still be possible to use multi-digit calculations.  It would get somewhat cumbersome (which is why the 'blanking' was introduced as a feature) but at the very least you should be able to 'zero-pad' the leading buttons of the minutes, then use the last as a multi-digit button.  It wouldn't be pretty, but it should work ;)

Rather than 'zero-pad' though the intended solution would be to 'blank-out' the digits as demonstrated in this video:
https://youtu.be/NlW2BfF-tu0

Although the video is some 9 minutes in length the critical information is intentionally demonstrated toward the beginning and you should only need watch the first 2 minutes to understand the feature.

If that doesn't satisfy your concern please do let us know and I'll do my best to extend the feature in some way.  And likewise if you have a better idea as to how to achieve the same result please do let us know about that too.  I'm wanting to make this feature both as capable and as easy to use as possible so any suggestions or improvements will be most welcomed.

Cheers.

**Comment by Natureshadow** [comment]
Well, blanking out in fact works. But as pointed out above, noone can possibly guess how to do that.

**Comment by Lineflyer** [comment]
So this is most likely a not a bug or missing feature but should make us think of how to explain the functionality within the UI.
As mentioned by @pstorch above we could try to put it into the captions suggested in #6664 if it soes not get too long or complicated.

Else I think we could take over some of the videos @S-Bartfast made into the cgeo youtube channel and link to it if @S-Bartfast is fine with that. I will open another issue for this.

**Comment by Lineflyer** [comment]
I think we can continue/include this topic  in #6664.
