### ISSUE TITLE
Multi digit solutions in WP Calc do not support decimals

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6699]
##### Detailed steps causing the problem:
- Today I performed GC28M8N
- This is a multi cache where you have given stages (A to J) and only need to calculate for the final as follows ( in DDD° MM.MMM' format):
```
N51°(23522+A+C+E+G+I)
E06°(45973+B+D+F+H+J)
```

I tried to enter this as follows in the WP calc:
First I assigned the first decimal digit of lat/lon as A/B in DDD° MM.MMM' format:
```
N051° A 
E006° B
``` 
For A and B I entered:
```
A=23522+a+c+e+g+i
B=45973+b+d+f+h+j
```

##### Actual behavior after performing these steps:
Two problems:
- After entering a-j I get a result which is the correct sum but summed up before the decimal digit only.
- When trying to save the app crashes (debug mode active)

##### Expected behavior after performing these steps:
It should be possible to use such multi digit solutions independently of the decimal separator.

##### Version of c:geo used:
2017.08.19-NB

##### Is the problem reproducible for you?
Yes

**Comment by S-Bartfast** [comment]
As it is the calculator intentionally only works with integers.

I thought about trying to handle decimal expansion results while working on it but ultimately decided against implementing it partly to reduce confusion to the user but mainly because it was too hard to think how to handle all the cases sensibly.  I figured multi's requiring decimal calculations were rare and in virtually all cases there would be a way to make do.

Not being able to read the language I find it difficult to follow exactly what the cache is asking but would it be possible to represent `N51°(23522+A+C+E+G+I)` as `N51°A.B` and define 'A' and 'B' as follows:
`A: (23522+a+c+e+g+i)/1000`
`B: (23522+a+c+e+g+i)%1000`

I acknowledge this isn't as neat as it could be but it should get you through.

**Comment by Lineflyer** [comment]
From reading the calculation I think it would work in this situation, but I dont expect any user to easily find this solution.
I am also thinking about what could be a better solution, but I agree with you that this will not be easy to handle (on top of that it needs also different handling depending on the coordinate format the user selected). So lets keep this open until we have a good idea.

Will change the title in a second.

**Comment by geocachermgo** [comment]
I would also like to have a solution. If float is not wanted maybe a special treatment of __.__A or A_.___ is an option?
Just like the first N is not treated as a variable.
Or maybe it could be added in the coordinates recognition. That N49° A with A> 999 is recognized as A/1000.A%1000.

**Comment by geocachermgo** [comment]
Plausibär (https://www.guballa.de/plausibaer) is using xx.xxx as notation of a number x that is covering several digits.

**Comment by murggel** [comment]
I would also like to have a solution, I did not find the solution with the modulo :-(
But if it is not so easy yet, probably the solution with N xx (A/1000).(A%1000) can be added as an example to the manual page of the waypoint calculator.

**Comment by moving-bits** [comment]
With the revamp of calculated coordinates you can now simply write `N51 (23522+a+c+e+g+i)/1000` and you're all set, so let's close here.
