### ISSUE TITLE
Search for user not working if name contains "+"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6726]
- Search for caches hidden by user "DiMaSh+"
- Search returns no result

In fact this user has hidden caches. 
I assume the special character in the user name is causing this problem.

**Comment by pstorch** [comment]
I can confirm this bug.
When searching via the Website, the plus is encoded as `%252b`. Which is a double encoding of the + sign.

**Comment by UniQP** [comment]
I wonder whether that also affects some other characters.

**Comment by pstorch** [comment]
@UniQP any other character in mind?

This can easily be tested. Look for a user profile with special characters in it on geocaching.com and click on his owned or found caches. Then you see how they encode the username in the URL.

I think the `+` sign is bit special. Because it is basically allowed in the URL, but represents a space normally. But there is some controversial discussion about it and you can also find non-standard implementations. I had to deal with such problems some time ago.

**Comment by UniQP** [comment]
I checked `␣ !  " # $ % & ' () * + , - .  / : ; < = > ?  @ [ \ ] { | }` and found two more exceptions:

```
+ %2B exception: %252B
< %3C exception: %253C
> %3E exception: %253E
```

**Comment by pstorch** [comment]
@UniQP cool. Do you have usernames with < and > at hand for testing?

**Comment by UniQP** [comment]
@pstorch Try "`<Seb>`".

**Comment by pstorch** [comment]
@UniQP but "<Seb>" is working without double escaping.

**Comment by UniQP** [comment]
@pstorch Ok, I just checked whether it is double-escaped for the found/owned caches list you mentioned. I think, then it's ok to just double-escape `+` in this context.

Interestingly, searching for caches hidden by `<Seb>` with geocaching.com→Filters results in a server error.
