### ISSUE TITLE
Calculator strings

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#6796]
After importing the latest strings to Crowdin for translation, I have some suggestions:
- I would move the placeholder/hint entries to not translatable (a + b, 2 + 2, _, *, N D°....)
- I'd suggest to change the coordinate pattern to the more common N D° MM.SSS'

comments?

**Comment by Lineflyer** [comment]
> I would move the placeholder/hint entries to not translatable (a + b, 2 + 2, _, *, N D°....)

Agree.

> I'd suggest to change the coordinate pattern to the more common N D° MM.SSS'

I would stick with the same patterns we also use for the waypoint coordinate format selection (also outside of the calculator). 
Where are these pattern strings used which you refer to?

**Comment by S-Bartfast** [comment]
> I'd suggest to change the coordinate pattern to the more common N D° MM.SSS'

What exactly do you mean here?

I would have thought the most common coordinate format would be `H DDD° MM.PPP'`
That is single letter for hemisphere ('N', 'S', 'E' or 'W'), zero extended degree field ('042°'), zero extended minutes field with three decimal digits (09.087'), which would be represented as `N 042° 09.078'`.

What exactly are you proposing by `N D° MM.SSS'` and how should it be used?  Do you mean the leading zeros should be dropped from the degree field (as in `N 42° 09.078'`).  Surely you don't mean the decimal portion of the minutes should be replaced by the second values do you?  That would be most misleading.

**Comment by Lineflyer** [comment]
> What exactly are you proposing by N D° MM.SSS' and how should it be used

I agree to @S-Bartfast. The format is using decimal minutes (MinDec) and therefore SSS is misleading here.
Please also refer to this section I added to the FAQ some time ago:
http://www.cgeo.org/faq#coords-format

So I think everything is perfectly fine as it was and still is in c:geo.

**Comment by rsudev** [comment]
Sorry for creating confusion, I already had formulated a correction in the comment box and never sent it because I was distracted.
I was drawing the pattern from memory (wrongly) and I wanted exactly to propose `H DDD° MM.MMM'`, but in the strings there was `H DDD° MM.PPP'`which I found confusing.
Was it now changed to conform to 'standard' format?
And in addtion I would suggest to move these from the normal translatable strings to the non-translated strings (or should these be localizable?)

**Comment by S-Bartfast** [comment]
> but in the strings there was H DDD° MM.PPP' which I found confusing.

Yeah, sorry about that.  In the source code of the calculator itself I'm actually representing the decimal point digits as 'P's because the same buttons are used across multiple formats and I momentarily used the same notation here but corrected it to MM.MMM shortly after.  I also made up the 'hemisphere character' representation ('H') myself, but at least that one is a little more intuitive ;)

But regardless of all that, I'm still unclear on what you are suggesting be changed about the coordinate pattern.  As in, when your suggesting changing the coordinate pattern how is it currently and how do you think it could be improved?

**Comment by S-Bartfast** [comment]
Oh, I see now.

You're referring to the 'string literals' in the "string.xml" file.
Yeah, those "lat_point_min_format" and "lon_point_min_format" strings can probably go all together.  I didn't even realise they were there actually.

**Comment by S-Bartfast** [comment]
Done!
(:

**Comment by S-Bartfast** [comment]
Hay, yay!

Check it out, I'm finally listed as a contributor:
![image](https://user-images.githubusercontent.com/6573522/32136063-72d864dc-bc50-11e7-89ad-258dfbbaa87f.png)

**Comment by pstorch** [comment]
@S-Bartfast unfortunately you have done some commits as `Slartibartfast` which are not correctly associated with your account.

**Comment by S-Bartfast** [comment]
Yeah, I realised that.

In fact all of my commits up until that last one used the email address ".gmail.com" (instead of "@gmail.com).  I tried to add the ".gmail.com" address to my account but it wouldn't let me, so unfortunately none of the work done over the last three months will be attributed to me.
