### ISSUE TITLE
Allow higher limit of waypoints shown on map

### ISSUE THREAD

**Issue by Pentatops** [cgeo/cgeo#6810]
##### Detailed steps causing the problem:
In the "Settings" menue, sub menue "Map", parameter "Show Waypoints": Actual limit is 50.
When using a large high resolution screen, e.g. on a 10 inch tablet, a higher limit would be needed. Suggestion: limit of 200, pre setting after installation should be 40.

##### Actual behavior after performing these steps:
Difficult to get a good overview about an area and a possible walking path if a number of final location have already been entered: If the zoom level fits for the area, the finals are no longer shown.

##### Expected behavior after performing these steps:
Just a better ovrview.

##### Version of c:geo used:
2017.10.23

##### Is the problem reproducible for you?
Yes, it's not a bug, it's a nice feature

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by Lineflyer** [comment]
While it was originally restricted to 50 because of map cluttering, I agree that in case of a highres screen it would be good to raise this limit (if technically feasible).
Regarding the default setting, I am not sure if this needs changes. One can still change it in case of need, and c:geo is typically still used on handheld devices with a possibly lower resultion.

**Comment by Pentatops** [comment]
Thanks for having a look on this!

**Comment by moving-bits** [comment]
current status: done, as PR 7224
