### ISSUE TITLE
Compass rose incorrect when using "upside down" portrait mode

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6829]
I did not even know, that this exists, but some phones seem to support a 180° display flip if you turn the phone upside down in portrait mode.
c:geo seems to follow this, but of course the compass rose bitmap is then wrong as it needs to be counting the degress counter-clockwise in this case.

Alternatively we should disable the usage of this upside down mode at all.

Device used (reported via support mail):
```
--- System information ---
Device: EVA-L09 (EVA-L09, HUAWEI)
Android version: 7.0
Android build: EVA-L09C432B391
c:geo version: 2017.10.23
Google Play services: enabled - 11.7.44 (448-173432861)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (17,1 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (17,1 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (17,1 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (204,0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: dd.MM.yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment]
@eddiemuc 
Any idea whether this might be implicitly fixed with your recently implemented upright detection?

**Comment by fm-sys** [comment]
Still reproducible for me...

**Comment by fm-sys** [comment]
I used the app "smart rotate" for testing. 
Same for landscape while the device is forced to normal portrait mode. It seems to be that Z axis rotation is ignored totally (which should not be the case)... 


Btw, the compass rose is also wrong when screen  points to the ground.

**Comment by eddiemuc** [comment]
> @eddiemuc
> Any idea whether this might be implicitly fixed with your recently implemented upright detection?

I am afraid I don't understand what is meant by the issue description... When I am in portrait mode and I turn my phone by 180° - then I am again in portrait mode - or not? Why should the compass rose be reversed in this case? Sorry for my slow understanding...

I never tested screen pointing to the ground

**Comment by Lineflyer** [comment]
> When I am in portrait mode and I turn my phone by 180° - then I am again in portrait mode - or not?

The initially mentioned device supports upside down portrait mode, meaning if you put your phone upside down in portrait mode, the screen content is shown upright, but our compass rose still acts like in 180° reverse mode thinking the phone is upright.

Remark:
I only took this from the user issue. As my phone does not support such mode, I could not test it. I guess its also a rare use case.

**Comment by fm-sys** [comment]
@eddiemuc 
>It seems to be that Z axis rotation is ignored totally (which should not be the case)...

When I turn my phone to landscape the compass rose points to the wrong direction. Same for turning the phone other angles at the Z axis. The compass points always to the same relative position (same phone border). Looks like we have a quite important bug here... Could you please check this?

**Comment by eddiemuc** [comment]
> When I turn my phone to landscape the compass rose points to the wrong direction. Same for turning the phone other angles at the Z axis. The compass points always to the same relative position (same phone border). Looks like we have a quite important bug here... Could you please check this?

I just introduction the following change:
- when device orientation is "flat" ( either via Auto or by fixing it), the compass behaves exactly as before (including all bugs that may have existed)
- when device orientation is "upright", c:geo assumes that phone is held upright with display facing the user

@fm-sys when in landscape, is your phone flat or upright?

**Comment by fm-sys** [comment]
> @fm-sys when in landscape, is your phone flat or upright?

The bug exists in both cases (see also the attached gif)

[![20201001-205416339.gif](https://i.postimg.cc/R0DqFw01/You-Cut-20201001-205416339.gif)](https://i.postimg.cc/R0DqFw01/You-Cut-20201001-205416339.gif) - As written before: The Z axis rotation is ignored completely

**Comment by eddiemuc** [comment]
The GIF is very helpful!

As far as I can see the "device orientation" stays about the same when you rotate into landscape and back (gif is a bit bumpy here, can you confirm that?)

Also, do you experience the same behaviour on current "life" version of c:geo?

I noticed when starting to work in this area that the compass rose seems to adjust very slowly to device orientation changes. Don't know why, but I thought this might be by design.

Not easy for me to work in this area, I need to rely on emulator and I never ever use compass myself. But yes, I can put this on my Todo list if no one else is available. Might take a while though.

**Comment by fm-sys** [comment]
>  "device heading" stays about the same when you rotate into landscape and back, can you confirm that?

Yes
> Also, do you experience the same behaviour on current "life" version of c:geo? 

Yes


If you could tell me where the compass orientation is calculated and if there is something I have to be aware of I probably can also debug into it myself... Thanks for your help!

**Comment by Lineflyer** [comment]
@fm-sys 
Can you post the sensor information from your system information in c:geo?

For me its working normal in portrait and landscape (Compass turns and always targets cache).

**Comment by eddiemuc** [comment]
> > "device heading" stays about the same when you rotate into landscape and back, can you confirm that?
> 
> Yes

OK, this means that this issue is probably unrelated to actual heading calculation but more to how this is displayed. When you change to landscape and WAIT a while -> does then the compass slowly change to expected heading?

If this is a display problem:
the entry point would be class `CompassActivity`.  For displaying the compass, someone implemented a self-made view whichi is `cgeo.geocaching.ui.CompassView`. Maybe this view implements some sort of "throttling logic" so view does adapt itself only slowly on heading changes?

If you want to check the "orientation calculation" part:
entry point would be method `cgeo.geocaching.sensors.Sensors.setupDirectionObservable`. There, the member `directionDataObservable` is initilialized depending on many settings (whether to use gps only, wheter to use deprecated orientation sensor, whether to use google play service ,....), and depending on this uses different provider-classes in same package. Assuming the user uses the defaults and the device is not too old, the used provider is most commonly the `RotationProvider`. In the end the different providers use different Android Sensors to calculate the rotationMatrix (`RotationProvider `uses `SensorManager.getRotationMatrixFromVector`)
The calculated rotationMatrix is then passed to `DirectionDataCalculator`, where it is used to calculate both device orientation and device heading. (This is also where the magic is happening of re-mapping the coordinates in case device is upright and not flat)

The whole orientation sensor support of Android is nicely explained here: https://developer.android.com/guide/topics/sensors/sensors_position

**Comment by geocachermgo** [comment]
I checked on my device, back camera pointing to cache (south) for all 4 pictures:
Portrait:
![Screenshot_2020-10-12-17-04-48-452_cgeo geocaching](https://user-images.githubusercontent.com/43813636/95762166-a0b4a180-0cad-11eb-9e8a-7433c0bd39f8.jpg)
Turing counter clockwise (left 90°) gives
![Screenshot_2020-10-12-17-05-31-727_cgeo geocaching](https://user-images.githubusercontent.com/43813636/95762269-c641ab00-0cad-11eb-8bfb-27545dc65e3d.jpg)
Turning further 90° so that phone held uspide down (no flip of display orientation) und
![Screenshot_2020-10-12-17-05-54-969_cgeo geocaching](https://user-images.githubusercontent.com/43813636/95762425-fc7f2a80-0cad-11eb-9411-ff5a21cc49bd.jpg)
Turning further 90°:
![Screenshot_2020-10-12-17-06-19-600_cgeo geocaching](https://user-images.githubusercontent.com/43813636/95762632-423bf300-0cae-11eb-8182-43dbec43c0d0.jpg)
I would expect the the arrow should always point "up" defined by the orientation of the letters.

**Comment by fm-sys** [comment]
@geocachermgo Same as for me. But I hadn't time to debug into it though...

**Comment by geocachermgo** [comment]
Remider to myself: Test display issue in all 5 orientations!

**Comment by fm-sys** [comment]
OK, I think I've found the reason. The bearing calculation for upright is absolute, which is absolutly OK and leads to that voice output is correct every time, but the Z axis rotation is not explicitly offset while displaying, here we need a relative calculation. I will try to fix this...

**Comment by fm-sys** [comment]
OK, I didn't manage it to calculate the Z axis rotation out of the orientation data (but have spent over 4 hours into trying to understand the rotation matrix - thank you, Euler!) 

But I noticed that there is an even simpler solution. Hopefully it works on all devices... :-/
