### ISSUE TITLE
Allow use of Brackets for the calculator while in 'Plain' format

### ISSUE THREAD

**Issue by S-Bartfast** [cgeo/cgeo#6835]
As discussed in the original proposal for the calculator only single character 'labels' fit on the buttons requiring intermediary 'names' to be used:
![image](https://user-images.githubusercontent.com/6573522/32602517-3adc12f0-c596-11e7-85dc-7f993ea984f3.png)

However, in 'Plain' format we do not have such size restrictions, so allowing direct entering of bracketed expressions should be possable:
![image](https://user-images.githubusercontent.com/6573522/32602770-5427a6c4-c597-11e7-9d9e-6303b6bdbf16.png)

**Comment by Matze2** [comment]
While looking through some multi examples I sometimes found that owners omit the parenthesis when there is no real formula but only the variable.

For example,
S48 51.(C-A)**B**(C+D)

Is this supported with this issue?

**Comment by S-Bartfast** [comment]
It is.

**Comment by S-Bartfast** [comment]
So is the use of square brackets "[...]", and braces "{...}.

And Nested Brackets "(A * (B + 2))", however the "internal" brackets must be round as apposed to square or curly.

Their are however parsing concerns with additional spaces.  This is not a an issue with the bracketing itself but rather an issue with how the final result is parsed (hence the reference to #6835 in the 'release' thread)

**Comment by Matze2** [comment]
About the additional spaces: Can't we just ignore/remove all spaces after the first "." in the input area.
With all known formats we know that they don't make sense.

**Comment by Matze2** [comment]
I tried a few multi formulas. It is amazing how good this "Plain" formula parsing works. 
After having started with "Plain" mode (because the buttons didn't work for me) and using the button modes in between I probably go back again to "Plain" mode because it is so much faster to enter the formulas.
Here I see the trailing zeros as a problem that should be fixed.
I still do not agree to use leading zeros everywhere. But as an intermediate step I would at least apply it this rule for "Plain" too.
Long term I would prefer that the "Plain" mode detects the format first and **then**applies the rules for that format.

**Comment by Matze2** [comment]
To summarize my wish list regarding that feature and beyond:
Short term:
- this issue should be merged and considered for release
- leading zero rule should be applied for "Plain" mode, too

Medium term:
- better detection of invalid input (see below) and visualizing it

Long term:
- apply leading/trailing zero rules of the detected format and not strictly to "leading"

Invalid input can happen easily with long formulas and instead of silently creating a coordinate which is in 99% of the cases nonsense we should indicate that something is wrong. Invalid input means:
- Problems in the formula like unmatched brackets or invalid expressions
- Negative results for single placeholders
- Too big results once we know the format itself, e.g. more than three digits for MinDec
- Missing input for formula variables

**Comment by S-Bartfast** [comment]
>Can't we just ignore/remove all spaces after the first "." in the input area.
With all known formats we know that they don't make sense.

We certainly can do that, and in this case it will be relatively easy but I fear it will wind up being a case of playing 'Whack-A-Mole (tm)".

While it makes sense that the intended formulation if `N 12 34.(C - 1) (D - 2) (E - 3)` is `N 12 34.(C - 1)(D - 2)(E - 3)` it is not so clear for spaces before the decimal point, as in `N 12 (A + 2) (B + 1) . (C - 1) (D - 2) (E - 3)`.  At present this will be understood to be "(A + 2)" degrees and "(B + 1)" Minutes –which I'm sure you already know.

The real problem here is that there are too many "groups" for the parser to know how to handle correctly and rather than returning the result as "erroneous" it does it's best to interpret the result anyhow, which in my opinion is a mistake.  If the input is not in an acceptable format it would be far better to simply inform the user that the input is not in an acceptable format than try to guess at what the user intended.  Sure, in the "spaces after the decimal point" case it is pretty clear what _was_ intended but as a general philosophy I would be more in favour of presenting such errors to the user than attempting to guess at their intention as there will undoubtedly be instances were such 'guesses' are not so obvious.

As stated above this particular error is an issue with the parsing of the 'GeoPoint' itself rather than an issue with the calculator as such, so care will need to be taken to ensure we adopt a solution that will be unilaterally acceptable.

**Comment by S-Bartfast** [comment]
>Invalid input means:
>* Problems in the formula like unmatched brackets or invalid expressions
>* Negative results for single placeholders
>* Too big results once we know the format itself, e.g. more than three digits for MinDec
>* Missing input for formula variables

Let us continue this part of the discussion in #6802.
(:

**Comment by S-Bartfast** [comment]
>Invalid input means:
>* Problems in the formula like unmatched brackets or invalid expressions
>* Negative results for single placeholders
>* Too big results once we know the format itself, e.g. more than three digits for MinDec
>* Missing input for formula variables

Let us continue this part of the discussion in #6802.
(:
