### ISSUE TITLE
Target API Level 26 until November 2018

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6905]
Yes, still plenty of time, but at the moment we are targeting API Level 22.

From November 2018 we need to target API Level 26 to be able to push any updates to the Playstore.

https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html?m=1

**Comment by Matze2** [comment]
Wow! This means they force everybody to android 8 by end of the year? :facepunch:

**Comment by SammysHP** [comment]
No, just the target level so that users with modern Android can benefit from some improvements.

**Comment by pstorch** [comment]
Yes, the minSdkLevel can still be much lower.

**Comment by Lineflyer** [comment]
Does somehow have an overview, what this means for us?
 I guess it is more work required than only setting the targetSDK correspondingly?!

**Comment by Bananeweizen** [comment]
I believe the main reason behind this policy change is that it requires all apps to use the new permission system instead of the old installation-time-permissions.

**Comment by Lineflyer** [comment]
I just would like to remind everyone on this topic...because Google Play now reminds me each time we publish an update.

Whatever needs to be done here, we should probably start early as we will otherwise not be able to publish updates after end of October.

**Comment by rsudev** [comment]
I just compiled it with 'targetsdk 26' without any further changes and it seems to work.
Not sure if this would suffice for publishing on Play.

**Comment by ControlTheBit** [comment]
@Lineflyer this is true.

I migrated all the apps in our company to the new permission system and you basically need to make sure that you handle all permissions correctly during runtime. This means you will need to ask the user for a permission each time (if the permission was not granted already) and then do something else in the app because the request is asynchronous. Good introduction to the topic here: https://www.youtube.com/watch?v=C8lUdPVSzDk

So e.g. you need to ask the user for his location permission for the maps and while the user has not decided, you just need to show the map (or do something else). As soon as the user decides, you get an event and need to see if the user accepted or declined the permission and handle those two cases accordingly. This must also be done if the user minimizes the app and comes back to it, because the user could have rejected the location permission while the app was minimized. And thank God, you only need to do all this stuff for the [dangerous permissions](https://developer.android.com/guide/topics/permissions/overview#permission-groups).

And as a second note: If you increase the targetSdk, make sure that you lint your app carefully after that. It will tell you which api requires different handling now or which api has been deprecated since the previous api level.

Please let me know if I can help you further with this or if you want a "helping hand" in the code :-)

**Comment by rsudev** [comment]
@Lineflyer I assumed that much (as I read the relevant docs when that SDK was published), but couldn't see any issues in the emulator, so I thought we might get away with a cheap but suboptimal solution short term.
@ControlTheBit You are more than welcome to lend a hand :)
We have three problem areas to take into account, AFAICS. TargetSDK, compilesdk and AppCompat version. Regarding the second I had the impression that we would loose GMaps v1 if we increase that (but perhaps they are just published differently, didn't dig deeper), which I think would be a real issue (maybe we can keep that as it is). When changing the AppCompat version, we need to adapt the base of our themes and probably extract and supply locally three or so icon resources we use from there, which do no longer exists in subsequent versions.

**Comment by ControlTheBit** [comment]
@rsudev Cool, I will have a look what I can do. I also had and issue with firebase in all our projects and the only fix was to go to targetSdk 27 to be able to use the build tools for 27. :-)

Do we already have a branch for this migration? If not, I will just checkout the whole repository and create a branch locally and start there.

**Comment by rsudev** [comment]
We don't have a separate branch for that. As usually only one person works on features, we maintain and publish such branches in our own forks and announce them for others to try or take a look, even before sending a PR.

**Comment by Lineflyer** [comment]
@ControlTheBit I agree to @rsudev. Help is always more than welcome.
Especially as this issue is kind of time critical. Looking forward to it, let us know if you need help.

**Comment by ControlTheBit** [comment]
@Lineflyer & @rsudev I already updated my fork of the repo and tried to get the project set up on my machine, but the import in android studio did not work as expected. It only recognized the root module and none of the child modules. I guess I will try this again tomorrow (I didn't have a lot of time today) and will let you know how things are going :)

**Comment by ControlTheBit** [comment]
Alright guys, I figured out how to get the build running and set the targetSdk to 27 (26 only gave me more issues...). I fixed all resulting local build issues that popped up and upgraded the libraries as needed. I would appreciate some help in handling all the permission stuff. I didn't have a closer look yet, but according to the analysis of Android Studio, there are only 6 places where we need to add additional permisions checks. I will have a deeper look this week. If you want to help/contribute, let me know and I'll add you as contributor to my fork.

https://github.com/ControlTheBit/cgeo/tree/target-sdk-26

**Comment by rsudev** [comment]
I took a first look at your branch today (but didn't get around to play with it yet). If it builds in that shape I am quite happy already.
Regarding the modules: IIRC they are partially externally provided API modules, partially do they provide libraries available through Gradle also for Eclipse (but I am not sure).
I think it is best to look first at the main application module (because this is the main distribution unit) and second at the contacts plugin, and to to leave the other stuff aside until issues show up.

**Comment by ControlTheBit** [comment]
Please assign this issue to me as I have already spent some time on this.

Here is the branch where I am working in: https://github.com/ControlTheBit/cgeo/tree/target-sdk-26

**Comment by rsudev** [comment]
@ControlTheBit Issues can only be assigned to team members directly. Therefore I assigned it to me as stand-in and added the label 'Assigned-non-collab' to mark it as being addressed by an 'external' developer.

**Comment by rsudev** [comment]
I gave the version from yesterday evening a short spin and it worked for me (on emulator with sdk 22 and 26). I'll play around a little with also denying access to see how it behaves.
In general I would say, if we don't have storage access, c:geo should not start at all, and if we don't have GPS, than you can use it only 'postionless' (looking up cache description, taking notes, potentially logging etc.).

**Comment by ControlTheBit** [comment]
> if we don't have GPS, than you can use it only 'postionless' (looking up cache description, taking notes, potentially logging etc.).

I see it the same way. Closing the app if the user does not want to give location permission was just the simplest solution to go for right now. We will need a way to start all sensors and initialize everything in some kind of "positionless" mode, where all locations are just mocked/hardcoded locations. I think implementing this will be a lot of work, but I can't say for sure right now. I will keep you posted.

**Comment by SammysHP** [comment]
c:geo can already be used with devices that have no GPS. In that case the Network location is used.

AFAIK we already use an internal abstraction for the location. It should be easy to add the permission check there and return mocked coordinates if the permission was denied.

**Comment by Lineflyer** [comment]
Back from vacation I wanted to ask about the status of this one.

@ControlTheBit 
I am mainly dealing with testing and support in this project. If I can help by testing some of your changes, feel free to provide an APK to me.

**Comment by ControlTheBit** [comment]
@SammysHP the difficult part with those permissions is that you cannot react right away if the permissions were denied or not, because the request for permissions is asynchronous. So if we want to access the location for the first time, we have to give back dummy coordinates anyway, because we have to ask for permission first. I will have a look if there is a easy way to put all the sensors into "dummy" mode, because we would also need permission to access the network location. Location in general is considered a "dangerous permission", so we need to ask for it - independent of the source.

@Lineflyer I'm a bit busy right now with a new project that I got at work. I can't promise if I can get this done until the 1st of Nov. Also the guys need to review my changes and everything before that... :) The current implementation asks the user for location permission. If the user denies the access, we display a popup where he can decide to be asked again for permission or close the app. There is no "dummy location" mode right now, so you have to either give access or close the app. Not a nice solution right now, but that's what I have right now. I will try to spend a few more hours on this next weekend and see if I can get it also working without location permissions.

**Comment by Lineflyer** [comment]
> If the user denies the access, we display a popup where he can decide to be asked again for permission or close the app.

Thats sounds sufficient for a first implementation. We are talking about a Geocaching app. So usage without location permission makes no sense and dummy locations will make most part of the app display meaningless information (e.g. distances, etc.).

**Comment by Lomanic** [comment]
I'm a user of the "dummy location" mode, to keep battery usage low for example or when I'm simply planning my next caches hunt at home. Currently, the location is set to the home as defined on GC.com, I would appreciate to keep using the app when the GPS is disabled.

**Comment by Lineflyer** [comment]
@Lomanic That should not be a problem. The discussion is about giving the permission to c:geo to access the location. If you later switch off GPS our normal mechanisms (i.e. using home location) will still work.
The only thing you still need to do is to give the permission to use location information.

**Comment by Lomanic** [comment]
Thanks for this explanation @Lineflyer. I agree with the intent then.

**Comment by Lineflyer** [comment]
This has been completed :)
