### ISSUE TITLE
Handling of legacy versions

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6908]
Edit: Topic of the issue changed due to discussion further below

---

Can someone confirm my thoughts:

Based on the last minSDK raise we limited the calendar plugin to be available for API 9-13 (see #6413).
Now that we depubslihed the legacy version (decided not to fix and support any longer) we are on minSDK=14, which means we can also depusblish the calendar plugin.

Correct?

**Comment by pstorch** [comment]
I don't see a reason to keep it.

**Comment by Bananeweizen** [comment]
In that case we can also remove the legacy status from the StatusUpdater, right?
https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/network/StatusUpdater.java#L35

**Comment by Lineflyer** [comment]
Theoretically we could, but we will for sure have a new legacy version as soon as we raise the minSDK next time. So I sugget to leave the code, the status page and the build architecture ready for serving a "new" legacy at some point of time.

**Comment by Bananeweizen** [comment]
I'm in favor of not having a legacy version anymore. If we followed the pattern that was used up to now we would have to release a "last version" before every min sdk raise, that basically just increased the hardcoded number in the client. That seems quite complicated, since we could just have that version number be part of the server side, and just give the client the closeout status from the server. That way there is no need for actually publishing a new release every time we drop a version.

**Comment by Lineflyer** [comment]
Let me think about that.....
The problem could be, that this needs adaptions to the status notifications. Right now AFAIK the version is compared and if a newer version is available the notification system will show, that an update is available. In this context legacy versions have been treated more or less as a seperate app, with its own notification logic. 
That seems to be the only reason why a dedicated version handling for legacy is necessary.
@samueltardieu Is this correct?

**Comment by samueltardieu** [comment]
The server knows:

- how to recognize the flavour (release, rc, nightly, legacy) from the version name;
- what the latest version name and version code are for a given flavour.

It also knows that an old release upgrades to a newer release, an old rc to a newer rc or to a newer release, an old nightly to a new nightly and an old legacy to a newer legacy.

Maybe the logic could be extended so that the min sdk version is part of the checks as well. That would introduce some kind of release "generation", and legacy would no longer be needed as-is.

**Comment by Lineflyer** [comment]
I will rename this issue to reflect the ongoing discussion.
The original question addressed here (to depublish the calendar plugin) was clarified: I will depublish it today.

**Comment by kumy** [comment]
Should we also consider removing it from our fdroid repo?

On January 9, 2018 12:29:36 PM GMT+01:00, Lars <notifications@github.com> wrote:
>I will rename this issue to reflect the ongoing discussion.
>The original question addressed here (to depublish the calendar plugin)
>was clarified: I will depublish it today.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6908#issuecomment-356258385

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Lineflyer** [comment]
@kumy I think we can close this issue here. The only open questions is whether the calendar plugin was removed from the fdroid repo already?!

**Comment by kumy** [comment]
Let's assign to me for the removal from fdroid, then close.

**Comment by kumy** [comment]
`cgeo-calendar` plugin removed from our fdroid repo.
