### ISSUE TITLE
Waypoint usernote not part of GPX file ex- and imports

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6914]
While checking the question on the dev mailinglist about handling of waypoints without coordinates I stumbled upon that usernotes of waypoints are not exported to the GPX file.
There is the `cmt` element in the waypoint which holds the note. We should write both notes concatenated into this field. When importing, we should check if the waypoint is userdefined and import the `cmt` field either in `notes` or in `userNotes` accordingly.

Or should we define a c:geo extension for it? The calculator state is missing, too.

**Comment by Matze2** [comment]
Our GPX also makes use of GSAK extensions. There are various string fields in that extension like UserData, User2, User3, User4.
Maybe these can be used to store user notes and calculator state.

**Comment by Confectrician** [comment]
Hi,

I just found this one while i wanted to open an issue for the missing comments.

I am using the c:geo gpx export to update caches in gsak after logging.
If you tell me what you need (for example which (user) fields should be filled), i can prepare an example gpx export and share it with you here.

BR
Jerome

**Comment by murggel** [comment]
I just found this issue, while I tried to export my user-note from the sub-waypoints.
Like Confectrician / Jerome I use c:geo and GSAK to synchronize my caches on the phone and offline.

I looked at your code and I think I have a solution for this. Should I post it here or ...

BR 
Sonja

**Comment by moving-bits** [comment]
Thanks for looking into this!

> I looked at your code and I think I have a solution for this. Should I post it here or ...

Best solution would be if you apply the codes changes you have in mind and to prepare a pull request.
If that's currently not possible for you, please share your findings here in this issue, so that other devs can pick up and try to implement it (as time permits). Thanks!

**Comment by murggel** [comment]
Ok, I will try to prepare a pull request, I will leave a comment here, when I am ready...

**Comment by murggel** [comment]
GSAK has only one note-field for waypoints, the `cmt`.
So I don't know if an extension of c:geo makes sense, because c:geo already has separate fields for note and user-note.

We can import the note according of userdefined waypoint into note or usernote. 
In addition for not-userdefined waypoints we can concatenate the note and the user note as done with the PersonalNote for exporting and split it up again for importing.

**Comment by murggel** [comment]
I just created a draft for a PullRequest, since I am not sure to merge into master or release

**Comment by moving-bits** [comment]
> I just created a draft for a PullRequest, since I am not sure to merge into master or release

@murggel 
Thanks for your contribution. Regular development goes to `master` branch.

**Comment by murggel** [comment]
Is that done with #5688 ? 
But then only for Premium Member.

**Comment by fm-sys** [comment]
Fixed with PR #8964
