### ISSUE TITLE
Refactor NewMap packages and classes

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6951]
There is quite some confusion now because we have two Mapsforge libraries. 

The new API is placed in `cgeo.geocaching.maps.mapsforge.v6`, but it is already version 0.9. The old implementation is in `cgeo.geocaching.maps.mapsforge`. As the new implemenentation is the default now, we should switch it. Have the new one in `cgeo.geocaching.maps.mapsforge` and the old in `cgeo.geocaching.maps.mapsforge.v3` or `cgeo.geocaching.maps.mapsforge.legacy`. Also the `NewMap` class should be named `MapsforgeMap` and the old one `MapsforgeLegacyMap` or similar.

Then we have some classes which have dependencies to both API versions. Maybe we can't avoid it as long as we support both versions.

**Comment by pstorch** [comment]
We can also skip this to the point, when we remove mapsforge v3. I was just thinking about it yesterday, because every fix/improvement we want to make at the moment is more complicated because we have two implementations. So we should keep the time short.

**Comment by Lineflyer** [comment]
I would target to keep the old libraries only in for one feature release cycle to have a fallback in case we overlooked a major shortcoming/bug.

**Comment by Bananeweizen** [comment]
Go ahead and refactor packages as you like. I'm also thinking of moving everything related to the coordinate calculator into an own package. I have done such package refactorings before to group related functionality, and not to group similar implementation classes. However, I have typically done this slowly, since huge refactorings give a hard time for syncing between release and master.
