### ISSUE TITLE
PNG file not selectable for photo uploads

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6955]
While trying to upload a log photo for OC (same at GC?) I was not able to select a *.png file. It was greyed out in the file selector.

No idea whether this is a phone problem, whether its supported on OKAPI, but uploading this PNG via browser on the OC website worked fine afterwards.

**Comment by pstorch** [comment]
I could select a .png file on my phone. Maybe it's an issue of the file selecting app?

**Comment by Bananeweizen** [comment]
I also think we are not presenting the list of images ourselves, right? We only show the selected image after it has been selected, when the user can still scale it and so on...

**Comment by Lineflyer** [comment]
Well. The remarkable thing is, that selecting a picture with c:geo and selecting a picture in my mobile browser opens the same selector.
When opened via c:geo it shows every file except *.jpg greyed out, via browser several image file types are selectable.

That made me think we apply a filter or preselection when calling the file browser.

**Comment by pstorch** [comment]
Interesting, actually we do: https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/ImageSelectActivity.java#L242

We should use `image/*`

**Comment by mucek4** [comment]
PNGs on my phone are screenshots, automatically downloaded backgroungs, and other stuff I would not upload to GC's page. Also gifs, icons and other files are not really recommended.
And on GC.com they say: "File upload supports the following formats: jpg, gif, and png."

**Comment by Bananeweizen** [comment]
I'm also in favor of image/*. This is a place where I would not try to "educate" users about the right file format during file selection already. I would rather add one more check after the file selection to verify it is an allowed file type (similar to the file size check). This is basically already necessary since the file chooser app may wrongly ignore the file type we put into the intent, such that we have to potentially deal with wrong file types anyway.

**Comment by Lineflyer** [comment]
@mucek4 
Exactly. I made a screenshot of my browser for a webcam cache and could not upload. Thats how I found out about this issue.
