### ISSUE TITLE
Create ordered list

### ISSUE THREAD

**Issue by KoalaBear84** [cgeo/cgeo#6971]
I would like to be able to create a (stored) list of Geocaches in a particular order by drag and drop.

This way you can plan a day of Geocaching with c:geo. Now it is very hard to do Geocaches on a particular order, keeping your own list on paper I guess and search them one by one.

Yes, I know there is something like Sort > "Vote (Own Rating)", maybe that is some way of workaround, but it's very hard I guess and not intuitive. Thanks!

**Comment by Lineflyer** [comment]
A good idea.
Most of the time the sorting by distance will do the job, however when planning a certain tour it might be helpful (still I personally would rather use the map then sort my list).

**Comment by moving-bits** [comment]
@KoalaBear84 
With the introduction of "individual routes" in version 2020-04-25 and the upcoming feature to sort this list manually (see #8569, coming with the next release): Is everything of your use case covered by this?

**Comment by KoalaBear84** [comment]
@moving-bits Yes, that would be great! Thanks!

**Comment by moving-bits** [comment]
FYI: Creating an individual route (= an ordered list of waypoints and/or caches) is already included in c:geo since version 2020-04-25. You have to activate "long press on map" in settings => map, then you can add/remove waypoints and/or caches by long tapping on them on the map.

The upcoming release adds a view (reachable via map => individual route => sort route) in which you can rearrange the items.

Closing this issue then. If you miss something regarding individual routes, feel free to open a new issue for that.

**Comment by KoalaBear84** [comment]
Thanks for being so helpful, all clear 👍
