### ISSUE TITLE
Batch upload modified cache coords to the website

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7028]
Feature request:

c:geo has a nice feature to upload corrected coordinates to geocaching.com website. I frequently have the wish to do this for multiple caches at once (eg: after solving a complete trail's puzzles on my mobile device or after importing a gpx file into c:geo). This function would then upload the corrected coordinates cache by cache.

A good place for this function would be (IMHO): stored - dot menu - manage caches and then maybe "upload coordinates".

This could be implemented for personal notes as well. (This is the place where I put information on how I have solved the puzzle.)

**Comment by Lineflyer** [comment]
@moving-bits 
What is your usecase scenario for this?
Do you save the corrected coords but only set them locally and later want to batch upload them to the website? That would for sure be possible as you suggest.
However in this case you could also directly select to set the corrected coords locally and on server...

If you just solve some cache and add some abitrary waypoints to them, how should c:geo judge which of them is the final? That could work out on easy caches and if the user follows some rules (e.g. set the waypoint type to "Final" and make sure it is the only waypoint of this type) but is also not likely to work out for all caches.

**Comment by moving-bits** [comment]
I have two different use cases for this:

a) I solve some mysteries and save the calculated coordinates in c:geo while I'm in offline mode (or the signal is too weak for uploading)
b) I import a gpx file with caches into c:geo (eg some route I've prepared using PC programs)

In both cases I would like having a function in c:geo to batch upload the current coordinates to the website for all selected caches (which would be basically the upload function we have now for a single waypoint, but called for all selected caches in sequence). As for the waypoints: Just use the caches' current coordinates, so no specific waypoints or waypoint guessing.

**Comment by Lineflyer** [comment]
> As for the waypoints: Just use the caches' current coordinates, so no specific waypoints or waypoint guessing.

In that case it would be wise to check if the current coords are modified or not, else such a batch job would also unnecessarily upload all unchanged coords. Doing so, the batch job could also be started for all caches of a list without any harm.

**Comment by Obilivion** [comment]
This long awaited new feature seems to have a bug. Upload no modified coordinates are uploaded, unless you press "Set as cache coordinates in c:geo and on website" for each and any cache.

To reproduce: Import GPX with modified coordinates to c:geo. 
When selecting "Manage caches" --> Upload modified coords (german: "Geänderte Koordinaten hochladen"), even if caches are selected previously, c:geo reports successful upload, but no changes on the gc.com are performed.

I tried to use this new feature with 3 different GPX files:
1. GPX file where cache coordinates contain the final coordinates and GPX has no Final nor Original Coordinates waypoints.
2. GPX file containing Final and Original Coordinates waypoints with cache coordinates as original coordinates.
3. GPX file containing Final and Original Coordinates waypoints with cache coordinates as final coordinates.
Nothing works.

I guess that the reason is that the option “Set as cache coordinates in c:geo and on website” cannot be set by the GPX import. 

I think the correct way to handle this is:
Set Option “Set as cache coordinates in c:geo and on website” to true, when
- Waypoint Original Coordinates and Waypoint Final Coordinates are different in the GPX, or
- Cache coordinates are different from Waypoint "Original Coordinates" (then treat cache coordinates as changed/final coordinates), or
- Waypoint Final Coordinates exist in GPX/c:geo and are different from cache coordinates, or
- Cache is selected in the list and has no Final Coordinates nor Original Coordinates Waypoints. In this case treat caches coordinates in GPX/c:geo as changed coordinates.

The minimum implementation would be to force upload of modified coordinates from an existing Final Waypoint for all caches selected in a list.

Since this is a very important function for us, we would donate 100 € if you could make working at least the minimum implementation by 3th of September.

Thank you
[testfinal.gpx.txt](https://github.com/cgeo/cgeo/files/3503830/testfinal.gpx.txt)

**Comment by SammysHP** [comment]
This should work since 05d0c96c93162ed6a4570c74b4862413c0f2c45c. Your sample GPX file does not include the GSAK extension which we check for modified coordinates. Maybe something has changed.

We won't guess based on the name of a waypoint. The original Groundspeak extension of GPX is not able to tag modified coordinates, so we have to rely on third party extensions or special markers.

Anyway, please open a new issue with your problem.

> Since this is a very important function for us, we would donate 100 € if you could make working at least the minimum implementation by 3th of September.

c:geo is an open source project without paid developers. Your payment would not reach a specific developer and we cannot guarantee that your problem will be solved until that date. Of course you can hire a software developer who creates a pull request with the necessary changes. But we can also not guarantee that the change is merged in time nor that we release a new version of c:geo including the fix before your deadline.

On the other hand, we would be happy to receive a donation to support our build server and other expenses for development.

**Comment by Obilivion** [comment]
Hi SammysHP, 

that was very helpful. Thanks for your answer. I scanned the gsak.xsd but did not find the element responsible for holding or marking modified coordinates.
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.gsak.net/xmlv1/6" elementFormDefault="qualified" xmlns="http://www.gsak.net/xmlv1/6" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation><xsd:documentation>
  This schema defines the GSAK extensions to be used with the GPX schema.
  The root elements defined by this schema are intended to be used as child
  elements of the "extensions" elements in the GPX schema. The GPX
  schema is available at http://www.topografix.com/GPX/1/0/gpx.xsd.
  </xsd:documentation></xsd:annotation>

  <xsd:element name="wptExtension" type="wptExtension_t"/>

  <xsd:complexType name="wptExtension_t">
    <xsd:annotation><xsd:documentation>
    This type contains data fields available in GSAK waypoints that cannot
    be represented in waypoints in GPX instances.
    </xsd:documentation></xsd:annotation>
    <xsd:sequence>
      <xsd:element name="UserFlag" type="xsd:boolean" minOccurs="0"/>
      <xsd:element name="Lock" type="xsd:boolean" minOccurs="0"/>
      <xsd:element name="DNF" type="xsd:boolean" minOccurs="0"/>
      <xsd:element name="Watch" type="xsd:boolean" minOccurs="0"/>
      <xsd:element name="UserData" type="xsd:string" minOccurs="0"/>
      <xsd:element name="UserFound" type="xsd:string" minOccurs="0"/>
	  <xsd:element name="DNFDate" type="xsd:string" minOccurs="0"/>
      <xsd:element name="LatBeforeCorrect" type="xsd:string" minOccurs="0"/>	  
	  <xsd:element name="LonBeforeCorrect" type="xsd:string" minOccurs="0"/>
	  <xsd:element name="StateBeforeCorrect" type="xsd:string" minOccurs="0"/>
	  <xsd:element name="CountyBeforeCorrect" type="xsd:string" minOccurs="0"/>
	  <xsd:element name="FirstToFind" type="xsd:boolean" minOccurs="0"/>
	  <xsd:element name="User2" type="xsd:string" minOccurs="0"/>
	  <xsd:element name="User3" type="xsd:string" minOccurs="0"/>
	  <xsd:element name="User4" type="xsd:string" minOccurs="0"/>
	  <xsd:element name="County" type="xsd:string" minOccurs="0"/>	  
	  <xsd:element name="Parent" type="xsd:string" minOccurs="0"/>
	  <xsd:element name="Child_ByGSAK" type="xsd:boolean" minOccurs="0"/>
	  <xsd:element name="Child_Flag" type="xsd:boolean" minOccurs="0"/>
	  <xsd:element name="UserSort" type="xsd:integer" minOccurs="0"/>
	  <xsd:element name="SmartName" type="xsd:string" minOccurs="0"/>
	  <xsd:element name="LastGpxDate" type="xsd:string" minOccurs="0"/>
	  <xsd:element name="Code" type="xsd:string" minOccurs="0"/>
	  <xsd:element name="Resolution" type="xsd:string" minOccurs="0"/>
	  <xsd:element name="IsPremium" type="xsd:boolean" minOccurs="0"/>
	  <xsd:element name="FavPoints" type="xsd:integer" minOccurs="0"/>
	  <xsd:element name="GcNote" type="xsd:string" minOccurs="0"/>
	  <xsd:element name="Guid" type="xsd:string" minOccurs="0"/>
	  <xsd:element name="CacheImages" minOccurs="0" maxOccurs="unbounded">
	  	<xsd:complexType>
	  		<xsd:sequence>
	  			<xsd:element name="CacheImage" nillable="true" minOccurs="0" maxOccurs="unbounded">
	  				<xsd:complexType>
	  					<xsd:sequence>
	  						<xsd:element name="iname" type="xsd:string" minOccurs="0"/>
	  						<xsd:element name="idescription" type="xsd:string" minOccurs="0"/>
	  						<xsd:element name="iguid" type="xsd:string" minOccurs="0"/>
	  						<xsd:element name="iimage" type="xsd:string" minOccurs="0"/>
	  				  </xsd:sequence>
	  				</xsd:complexType>
	  			</xsd:element>
	  		</xsd:sequence>
	  	</xsd:complexType>
	  </xsd:element>	
	  
	  <xsd:element name="LogImages" minOccurs="0" maxOccurs="unbounded">
	  	<xsd:complexType>
	  		<xsd:sequence>
	  			<xsd:element name="LogImage" nillable="true" minOccurs="0" maxOccurs="unbounded">
	  				<xsd:complexType>
	  					<xsd:sequence>
	  						<xsd:element name="ilogid" type="xsd:string" minOccurs="0"/>
	  						<xsd:element name="iname" type="xsd:string" minOccurs="0"/>
	  						<xsd:element name="idescription" type="xsd:string" minOccurs="0"/>
	  						<xsd:element name="iguid" type="xsd:string" minOccurs="0"/>
	  						<xsd:element name="iimage" type="xsd:string" minOccurs="0"/>
	  				  </xsd:sequence>
	  				</xsd:complexType>
	  			</xsd:element>
	  		</xsd:sequence>
	  	</xsd:complexType>
	  </xsd:element>	
	  <xsd:element name="CustomData" type="xsd:string" minOccurs="0"/>	  	
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

Which is it? 

Concerning donation: If it helps the development of c:geo it is always a good investment and I will stick to my promise. Already donated a part of it.

**Comment by moving-bits** [comment]
> This should work since [05d0c96](https://github.com/cgeo/cgeo/commit/05d0c96c93162ed6a4570c74b4862413c0f2c45c). Your sample GPX file does not include the GSAK extension which we check for modified coordinates. Maybe something has changed.

The PR implementing this issue (7028) relies on the internal flag in c:geo whether a cache has modified coords, and does not do further manual checks.
(This flag gets set in the way SammyHP has described above.)

> We won't guess based on the name of a waypoint. The original Groundspeak extension of GPX is not able to tag modified coordinates, so we have to rely on third party extensions or special markers.

Besides having filled the according GSAK extensions (which would be the preferred, but not always available, way) I can imagine use cases for which a different solution could be useful:

_Add a function to upload the coordinates for all / all checked caches to the website [without checking the c:geo internal "has modified coordinates" flag]._

Then the workflow for importing any GPX file with changed coordinates could be to import this GPX into a new list, upload the coordinates for those caches (without c:geo internally checking a "modified coordinates" flag), and then (optionally) moving those caches to the list(s) they should belong to.

This would be a generalized approach for the use case Obilivion mentioned as well as others.
