### ISSUE TITLE
Dates broken in logs

### ISSUE THREAD

**Issue by akkatracker** [cgeo/cgeo#7040]
![](https://i.imgur.com/dguB71G.jpg)

Log dates are showing up in the future. Has shown up on the latest beta release and previous release.

**Comment by Lineflyer** [comment]
This seems to be a login issue causing this problem.
Either your login informaiton is wrong, so that c:geo cannot loging or it could also be in rare cases caused by being logged out while c:geo is running (e.g. due to a website downtime).

Please check if your Login is OK (restart c:geo and see if it logs in) and refresh the affected caches.
Does this solve the problem?

If not, please kindly provide your system information (Menu - About c:geo - System) here.

**Comment by akkatracker** [comment]
Refreshing login worked. Thanks. Closing
