### ISSUE TITLE
Move /sdcard/.cgeo to /sdcard/Android/data/cgeo.geocaching

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#706]
I have a lot of directories on my sd-card and sometimes it's really annoying. I suggest to move ```/sdcard/.cgeo``` to ```/sdcard/Android/data/cgeo.geocaching```.

See:
http://developer.android.com/guide/topics/data/data-storage.html#AccessingExtFiles
http://developer.android.com/guide/topics/data/data-storage.html#ExternalCache

Maybe we have to add a new compatibility-class or we're using the "old" methods with a directory-name in any case:

>If you're using API Level 8 or greater, use ```getExternalFilesDir()``` to open a File that represents the external storage directory where you should save your files. [...]
>
>If you're using API Level 7 or lower, use ```getExternalStorageDirectory()```, to open a File representing the root of the external storage. You should then write your data in the following directory: ```/Android/data/<package_name>/files/```

So e.g. all the GC***-directories are in ```/sdcard/Android/data/cgeo.geocaching/cache/```.

The only problem, that I see, is:

> If the user's device is running API Level 8 or greater and they uninstall your application, this directory and all its contents will be deleted.

**Comment by Lineflyer** [comment]
I would like to put all of these discussions (#3950, #706 and others) into a new issue dealing with the overall file structure of c:geo. We surely have to find a solution for the offline cache (/.cgeo) but IMO as well include those random dirs we are using (e.g. /field-notes / GPX) into that discussion.

A lot of the discussion in those issues was about the right strategy and -even more important- about a migration strategy from the current to a possible new strategy.

Independently of whether there is someone willing to implement this, I would like to ask if you agree with starting from scratch and at first outlining the current situation and our target and afterwards define the ways towards it in a new issue.
The example from Locus posted in https://github.com/cgeo/cgeo/issues/3950#issuecomment-67784999 seems like a very good option also for c:geo.

Feedback?

**Comment by Hadatko** [comment]
Hello since lollippop we can move apps to sdcard. But this app still use internal instead of external. (I read the reasons). But what about this? I tried it and it works: http://help.sygic.com/hc/en-us/articles/206657887-How-To-Move-Sygic-To-SD-Card-Android-

They found a way...

**Comment by IByte** [comment]
Is there any word on getting data directory storage on the actual SD card to work for Samsung users? Marco-dev's build cgeo-pr-4034.apk worked wonderfully for me for quite a while, but now it doesn't properly communicate with geocaching.com any more. I am currently trying to hack it in there myself, but it would of course be preferable if this weren't necessary and a proper solution for this was included in the main c:geo build.

I'm using a Samsung Galaxy S5 mini, currently on Android 6 (which changed path names around a bit once more).

(One way of solving this (and exactly what marco-dev's mod does) would be to allow the user to manually specify a storage directory somewhere deep in the settings. Some of us have actual computer science degrees and would prefer to be granted the ability to shoot ourselves in the foot with entries that may or may not be correct. Or take a look at the code of OsmAnd, they seem to have a selection menu that has this figured out:

![screenshot_2017-04-12-17-21-01](https://cloud.githubusercontent.com/assets/708282/24967113/58ea207c-1fa9-11e7-884e-c0e0e12223a0.png)

)

**Comment by IByte** [comment]
As mentioned, this code seems to offer some indication as to how to get all possible storage directories:

https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/download/ui/DataStoragePlaceDialogFragment.java

**Comment by Lineflyer** [comment]
Well its meanwhile implemented in our Nightly builds. Feel free to test

**Comment by IByte** [comment]
Ah, that sounds like good news, thanks. I'll test it soon.

**Comment by IByte** [comment]
I installed today's nightly (2017.04.13-NB-6940e60), and it seems to work really well. After restoring the database backup and moving the image files to the new location (I have a lot (i.e. gigabytes), which is why the external SD feature is so essential to me), it is fully operational again. Thanks!

(Good thing, too, as Android Studio and Emulator are slow as molasses on my system, which wasn't making me a happy developer. And apologies if I sounded a little harsh earlier, but it's just been a bit of a long wait for this feature. I am really quite pleased.)

Any idea when this might land in the stable build?

**Comment by pstorch** [comment]
@IByte thanks for testing. Can you tell me how long it took to move the files and what size your GeocacheData directory has? Would be good for us to have an indication. 
The release is planned but there are still a few issues to address.

**Comment by Cappa-d** [comment]
@pstorch I will install the NB as well and test it. is there any c:geo internal statistic I could trigger to get your needed data? like the system information or so?

**Comment by pstorch** [comment]
@Cappa-d it's just the amount of data, which is visible in the directory chooser dialog. And the time it takes, which needs to be stopped with a stopwatch. 
As I think about it the make and model and the available directories in the dialog would be interesting, too.

**Comment by IByte** [comment]
@pstorch I didn't make c:geo copy the files, I did it myself. Android refused to install the nightly build directly over the marco-dev build (PR4034) (and presumably not over the stable build either), so I uninstalled that and did a clean install. Then I moved a database backup into place and performed a restore. After changing the geocache data directory in the c:geo settings to the external SD card, I put the SD card into my laptop and moved the image files from a backup (which I suppose is a faster way to do it. A move by c:geo wouldn't have worked anyway, as the path names/directory structure have changed since that build). Afterwards, c:geo indicated the data directory size as 3.2GB, which took a while to compute, perhaps a couple of minutes.

The "Select geocache data directory" command was greyed out in Emulator, by the way, perhaps because there was no alternative location available. I had to test it on my actual Samsung device.

Here are some screenshots of the device running the nightly build:

![2017-04-13 22 11 40](https://cloud.githubusercontent.com/assets/708282/25042242/b5b3cdda-2116-11e7-8848-048de7593840.png)

![2017-04-14 10 42 55](https://cloud.githubusercontent.com/assets/708282/25042255/d3d2f6f6-2116-11e7-9ea3-659a922e2c5c.png)

**Comment by Cappa-d** [comment]
@pstorch Tested it with the following results:

Installed c:geo Version : 2017.04.14-NB-6940e60
Device Samsung S7 Edge SM-G935F
Android: 7.0

Entries to Move: 3529
Time to move: 37 min 20.33 sec

Result report failure

However I did a move back to the internal storage which was complete in half of the time and was successful.

I will rerun the move as I really need to free the space on my internal storage and get back to you.

**Comment by pstorch** [comment]
Thanks. Good to have more testers on this. 
Especially with this amount of data. 
The 2 to 5 minutes of disk usage calculation makes me think a bit. Do we have to do something about it?
If there is only one choice the option is grayed out, yes.

**Comment by Cappa-d** [comment]
Run 2:

Entries to move: 3530
Size of DIR: 3.5 GB
Time to move; 34 min 21.33 sec

Result:

Faster analysis time before folders could be selected.

Move was partially successful. trying to migrate the missing data manually now.

Ok only one directory was missing in the files section. Moved this manually on the phone successfully.

**Open questions after the test -- which might lead to new issues**

- Setting to store the Database on the external SD is activated -- still the database is located on the internal drive (Phone\Android\data\cgeo.geocaching\files\databases)
- Backup of the database as well on the internal drive -- separate folder (Phone\cgeo\backup)
- Impossible to create import or export folders for GPX

**Comment by pstorch** [comment]
Actually this is an older issue. We had our main discussion in #4957 and the resulting specification was https://github.com/cgeo/cgeo/wiki/Target-disk-usage-structure. 
So we decided not to have the DB on a real external probably removable storage.

**Comment by Cappa-d** [comment]
ok got it, but just my 2 copper here: I create a new Backup and honestly what sense does it make to have a backup on the same drive as the original file? In case of a broken phone it won't help me to have a backup or not.. 

Would it be possible to have a selection dialogue while creating the backup as well? Was this discussed?

**Comment by SammysHP** [comment]
The backup helps if your main database is corrupted.

**Comment by Cappa-d** [comment]
@SammysHP I do not question the need for a backup don't get me wrong. I just have issues with the storage path of the backup. I am fine that you need to put it on the phone when there is no sd card present (personal choice of an user). I just have an issue with the storage on the phone when there is an SD card. 

I had a complete phone crash in december and there was no way to recover any data from the internal drive. Even having a backup left me helpless as I was not able to access my phone. If the backup would have been on the sd card like I have the cache data with the NB now this would not have been an issue at all for me. 

So I am absolutely pro backup and would even love to have an option to have an automatically triggered backup every other week or with an definable option for the time setting. Just the place seems strange due to personal bad luck.
