### ISSUE TITLE
Batch storing of huge areas?

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7106]
Is there some recommended way to store offline caches from the areas with really high density? Usually if there are more than 300-500 caches on the map screen, it becomes slow and each map movement can take some time. 
In the same time for big cities it could be 1000s of caches in the city. Is there a reliable way to store all of them? 

Current workaround: use closer zoom level and save caches from each "tile".

**Comment by Lineflyer** [comment]
What I mean is, that c:geo is not designed for "batch saving thousands of caches for a huge area". Sure you can do it, but its time consuming and not comfortable. As you also load much more data than what you actually will need at the end, its only logical to find a more efficient way.

**Comment by okainov** [comment]
Nowadays in any average city in Europe or US there are thousands of gc.com caches (+OC and others if used). So I would say it's very common scenario....

**Comment by pstorch** [comment]
The common scenario is to use pocket queries to download huge amount of caches, isn't it?

**Comment by okainov** [comment]
@pstorch if (1) you're talking about gc.com (yeah, I can imagine that it's the most pupular service, but I'm sure you have some amount of active OC users as well) and (2) you're Premium member.

I'm not Premium and I have no plans to get it.

**Comment by SammysHP** [comment]
There is no elegant way to download so many caches from geocaching.com at once. If you have a list of all caches, the download will take some time. You should also keep in mind that mass downloading of caches is not allowed by Groundspeak. That's why c:geo behaves like a browser. I'm sure that you don't open 1000+ caches at once in your browser.

You are right that the handling of multiple providers is not mature. I suggest to disable GC in c:geo, download OC caches directly from the live map and import GC caches from a pocket query. This required a premium membership, of course. But that is expected if you want to use all features of GC.
