### ISSUE TITLE
Don't process color tags in cache description

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7153]
##### Detailed steps causing the problem:
- Open some cache with color formatting (i.e. MS20692)
- Check description
- Make sure colors are being rendered by c:geo which results into mostly non-readable text (blue text on black background

Please either disable colors at all (so far I haven't seen any cache where colors were important) or at least add option "don't render colors"

**Comment by SammysHP** [comment]
We already use some "algorithms" to mitigate this problem (basically using a lighter background if dark colors are detected). The heuristics are not perfect. In this case a saturated blue (`#0000ff`) is not detected as "dark", although it is seen rather dark.

The problem is mostly caused by the fact that c:geo uses kind of inverted colors (dark background, white text). This works fine for uncolored text, but fails in other cases. We could either always use a white background like the website (but what if the website decides to use a different background color?) or use it only if necessary or we could disable all colors.

Disabling all colors is a bad idea because many caches require colors (see below). Our current approach solves the issue for many caches, but not all. The first way would destroy our "design".

_Maybe we should add another menu option to switch between normal design, light background or colorless text just for the cache description._ In that case I suggest to use our heuristics to enable the second method (which is currently just a dark gray background, but we should make it white and the text black).

There is already an issue about opening the cache description in a proper webview/browser with full html/css support.

For the time being you can use the light colorscheme in c:geo which should fix this issue.

> so far I haven't seen any cache where colors were important

I have seen hundreds of such caches. ;) It is often used to highlight objects to find, sometimes using colors to group items (e.g. for longitude/latitude).

**Comment by okainov** [comment]
>We already use some "algorithms" to mitigate this problem (basically using a lighter background if dark colors are detected). The heuristics are not perfect. In this case a saturated blue (#0000ff) is not detected as "dark", although it is seen rather dark.

Checked the code - "algorithm" and "heuristics" were definitely big words for this part of the code :) SO I allowed myself to include real "heuristic" here, see corresponding PR

**Comment by UniQP** [comment]
Does anyone knows a GC cache that has this problem?

**Comment by UniQP** [comment]
For further discussion, I like to use GC2PAEP to compare the current implementation ("old") with the changes proposed in #7172 ("new"):

old |                               new
:-------------------------:|:-------------------------:
![old](https://user-images.githubusercontent.com/1321557/48300835-0b6a6a80-e4e4-11e8-803a-35fb4adcc8c9.png) | ![new](https://user-images.githubusercontent.com/1321557/48300830-07d6e380-e4e4-11e8-970b-0ddc51338665.png)

I like to discuss two points:

1. Do we want to use the same background color for the whole description (as done by "old" but not by "new")?
2. If we detect that the contrast between font color and background color isn't high enough, should we change the font color, the background color, or both?

**Comment by okainov** [comment]
For 1 - I think we definetely should not replace the whole background if we find only one sentence with bad contrast. That's why I replace only style for "bad" sentences.
For 2 - it's discussible, but during implementation I had several points in mind:
- Keep it close to existing "old" behavior, thus using the very same gray background.
- make string readable. Saying this, I cannot keep existing foreground color of the string, because there is no background which will fit all.
- Make it clear for users that this like was somehow "processed", so if the color was really important, user should be able see it and go to the website.

So currently for low-contast string I remove foreground and set gray background.

**Comment by Lineflyer** [comment]
Thanks for the example.
My personal preference:
1. IMHO the new implementation is better. Why changing the whole description if only part of it is unreadable.
2. I think it might be needed to change both. In the example I can see the change of text and background in the last section of the description. It looks good.

Another question:
Can the implementation handle c:geo set on light theme?

**Comment by SammysHP** [comment]
I don't like that the last two paragraphs are not blue as the cache owner intended (the explicitly black text might be a mistake).

I'm fine with selective background color changes.

**Comment by okainov** [comment]
>I don't like that the last two paragraphs are not blue as the cache owner intended (the explicitly black text might be a mistake).

I still think that text color is not important in majority of caches. You should be able to get all the information from text only.

Can you suggest an algorithm for selecting background color then? Because keeping foreground and setting gray background won't improve anything if foreground was... gray, for example. Do you want to have several background options and select the one which has the most contrast with the given foreground?

**Comment by SammysHP** [comment]
Usually there is a reason why the cache owner has chosen a specific color. It might not make sense in many cases, but we should respect the decision of the owner.

These issue exists only because we use a different background color than the website. Some caches even use white text on white background to "hide" the text. We cannot handle every situation with the inverted background and default text color, but we can improve the situation for at least most cases.

Gray text should not trigger a background color change (except in combination with other colors in the same paragraph, one of the few cases where this method does not work). I suggest to always keep the text color and change the background color if necessary.

Note that this "hack" should not be necessary with the light theme at all because it already uses dark text on light background.

**Comment by okainov** [comment]
>Note that this "hack" should not be necessary with the light theme at all because it already uses dark text on light background.

This is not true. Just as couple of potentially many examples - https://coord.info/GC1YRN1 and https://coord.info/GC1JG80 (yes, they're using unsupported tables so `Html.fromHtml` skips actual formatting, but it could be done with span as well). You could imagine that the text there may have light-gray font (so far wasn't able to find real example), which doesn't have enough contrast for both white background of light theme and "gray" highlight. 

Since some of geocaching services allow wide possibilities for appearance customization, c:geo should be able to handle it correctly.

**Comment by SammysHP** [comment]
> This is not true. Just as couple of potentially many examples - https://coord.info/GC1YRN1 and https://coord.info/GC1JG80

Hmm… I would expect a black background even in the light theme. It's really a question whether we want to render the description like a full webview or just simple text. With so many special cases I tend to prefer a reduced version as default (similar to the current implementation, no tables, no colors, adjustable font size (in the future) etc) with an easy to reach option to show the original formatting in another view (or some kind of toggle that switches the description view, maybe even with a default configurable in the preferences).

**Comment by Lineflyer** [comment]
> I don't like that the last two paragraphs are not blue as the cache owner intended (the explicitly black text might be a mistake).

Thats true. At least this would keep a little bit of the style the owner desired. I would also be fine with manipulating the background only....in fact, the black c:geo background is the reason why we do it....so changing the background only has some logic.

**Comment by okainov** [comment]
Done.

Dark theme | Light theme
------------ | -------------
![2018-11-10 21 57 11](https://user-images.githubusercontent.com/918446/48306031-0e417b80-e535-11e8-989a-ebcf4680dc70.jpg) | ![2018-11-10 21 56 23](https://user-images.githubusercontent.com/918446/48306032-0e417b80-e535-11e8-9cfc-839d6ca4f2c9.jpg)

**Comment by SammysHP** [comment]
The dark theme looks fine.

But I don't know why it's necessary to add a black background for "ACHTUNG" in the light theme. On the website it is like this:

![20181110_221405](https://user-images.githubusercontent.com/922874/48306102-1f3ebc80-e536-11e8-8180-4a2c49401e8c.png)

**Comment by okainov** [comment]
>But I don't know why it's necessary to add a black background for "ACHTUNG" in the light theme. On the website it is like this:

Achtung is in #FF6600 color which doesn't have enough contrast on white (even bold and even big font, actually), only 2.94, see [W3 checker](https://webaim.org/resources/contrastchecker/?fcolor=FF6600&bcolor=FFFFFF)

On black, from the other side, it has 7.15 contrast which is much better.

**Comment by Lineflyer** [comment]
Looks fine. Once the working mode is agreed the fine tuning can be made by adjusting the contrast ratio limit later on after testing...correct?

**Comment by SammysHP** [comment]
What I mean: The cache owner decided to use a "low contrast" color, why should we fix this?

**Comment by okainov** [comment]
Because we don't know (and we cannot know) was it "owner decided" or "owner made a mistake" or "c:geo skipped some part of formatting" or "gc service website had inserted some extra useless markup".
From c:geo point of view, there is zero difference between orange "achtung" and black text on black. Both are barely readable.
You never know. I see "make cache description readable" as the main priority goal here. I don't really want to care about any crazy ideas of cache owners even not thinking about how their text will be displayed somewhere except GC.com. 
We make text readable. That's it. If you want I can add extra notice similar to the one about tables "This cache contains some color markup which may be displayed differently. Please check original cache page if needed"
