### ISSUE TITLE
Revoke authorization is hardcoded for OC only

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7184]
##### Detailed steps causing the problem:
- Enable some non-OC OAuth service in settings (i.e. Twitter or Gc.su)
- Authorize c:geo
- On Service settings page long tap on "Authorize c:geo again"

##### Actual behavior after performing these steps:
Nothing happens
`cgeo\main\src\cgeo\geocaching\settings\AbstractClickablePreference.java` line 65, in `onLongClick` `isAuthorized` returns false, because in `D:\Projects\cgeo\main\src\cgeo\geocaching\settings\OAuthPreference.java` `isAuthorized` checks only hardcoded OC services..

##### Expected behavior after performing these steps:
Authorization should be revoked, Authorization keys should be deleted

##### Version of c:geo used:
master

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
It's super confusing to have revoke functionality on long tap without any hints, would be much better to at least add some hint message

**Comment by okainov** [comment]
Should I push this commit as separated PR?

For further improvements it will definitely make sense to refactor OCPreferenceKeys and make it more generic than just OC.

**Comment by Lineflyer** [comment]
I would prefer seperate PR for seperate issues....I guess this also helps to keep each PR as less complex as possible.Von Samsung-Tablet gesendet
-------- Ursprüngliche Nachricht --------Von: Oleg Kainov <notifications@github.com> Datum: 11.11.18  14:55  (GMT+01:00) An: cgeo/cgeo <cgeo@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [cgeo/cgeo] Revoke authorization is hardcoded for OC only (#7184) Should I push this commit as separated PR?
For further improvements it will definitely make sense to refactor OCPreferenceKeys and make it more generic than just OC.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@okainov in #7184: Should I push this commit as separated PR?\r\n\r\nFor further improvements it will definitely make sense to refactor OCPreferenceKeys and make it more generic than just OC."}],"action":{"name":"View Issue","url":"https://github.com/cgeo/cgeo/issues/7184#issuecomment-437672137"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cgeo/cgeo/issues/7184#issuecomment-437672137",
"url": "https://github.com/cgeo/cgeo/issues/7184#issuecomment-437672137",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [cgeo/cgeo] Revoke authorization is hardcoded for OC only (#7184)",
"sections": [
{
"text": "",
"activityTitle": "**Oleg Kainov**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@okainov",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"cgeo/cgeo\",\n\"issueId\": 7184,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"cgeo/cgeo\",\n\"issueId\": 7184\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/cgeo/cgeo/issues/7184#issuecomment-437672137"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 409060777\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by okainov** [comment]
@Lineflyer done, but since I need those fixes in my main PR #7170, I keep them there as well.

**Comment by okainov** [comment]
@Lineflyer it's not only refactoring, it's a bug, because you cannot revoke Twitter authorization, for example :)

**Comment by Lineflyer** [comment]
Ok, thanks. Changed.
