### ISSUE TITLE
Include current elevation in compass view

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7196]
From support mail:

It would be helpful for some caches (e.g. typically earth caches with related questions) if the c:geo compass could provide the current elevation information as provided by the GPS on the compass view next to the current coordinates (bottom row).

**Comment by moving-bits** [comment]
How can I receive the altitude values needed for this?

Testing with `Location.getAltitude()` always returns 0.0 in the emulator, and grossly wrong values on a real device (24m instead of 120m for the place where I tested this).
Others suggest to use `locationManager.addNmeaListener(...)`, but I cannot get this to run.
Any other ideas or hints?
