### ISSUE TITLE
Three dot icon replaced by new icon on cache popup

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7251]
##### Detailed steps causing the problem:
- Open map
- Click on a cache on the map to open the popup

##### Actual behavior after performing these steps:
The popup "action bar" now contains a new icon instead of the three-dot icon

##### Expected behavior after performing these steps:
Actually the new icon is pretty same style as the other icons.
So instead of havin the three-dot back here, I could also imagine to keep it but then maybe make it consistent in other activities.

##### Version of c:geo used:
2019.01.23-NB

##### Is the problem reproducible for you?
Yes

##### System information:
Android 8.0

##### Other comments and remarks:
Picture from @okainov 
![2019-01-09 19 01 08](https://user-images.githubusercontent.com/918446/50918608-015fdc00-1441-11e9-8ede-c4f6c8607a86.jpg)

**Comment by bekuno** [comment]
This was changed in the commit
https://github.com/cgeo/cgeo/commit/3110366ca0550474b27dbd09109f31956501582d#diff-5b2bc0d53d8e8da983507f564430c94e

in  main/res/layout/actionbar_popup.xml
from
       android:src="@drawable/abc_ic_menu_moreoverflow_normal_holo_dark" />
to
        android:src="@android:drawable/ic_menu_more" />

**Comment by bekuno** [comment]
There are more changes in the commit from own cgeo icons to android standard icons
(in main/res/layout/pocketquery_item.xml,  main/res/menu/main_activity_options.xml)
and from AppCompat.Base to DeviceDefault (in main/res/values/themes.xml)

**Comment by rsudev** [comment]
Even though it looks like a resource form c:geo, has it been one from the AppCompat (if I am not mistaken), which doesn't exist any more in the new AppCompat version (or under a different name, which I couldn't find).
The changes from AppCompat.Base to device default cover mostly areas, were we cannot inherit from 'AppCompat' (like GoogleMapActivity and MapsforgeMapActivity) and therefore need a different layout in order to have an ActionBar in the first place.
I there are other means to achieve that, any idea or piece of information which can be found is welcome! (In my opinion is the themes, styles and resources topic horrendously underdocumented, to put it mildly...)

**Comment by bekuno** [comment]
For the actionbar_popup icon (3dot) I think we can use the ressources from 
https://developer.android.com/design/downloads/
which brings us to
https://material.io/tools/icons/?icon=more_vert&style=baseline
and this data structure
![grafik](https://user-images.githubusercontent.com/32555742/52375262-839ee880-2a5f-11e9-99cf-e42adf8bdc22.png)

**Comment by rsudev** [comment]
Perfect :)
They are available under an Apache 2.0 license, so no issue to integrate.

**Comment by bekuno** [comment]
While implementing the tree_dot_icons I see two discussion points.
At first: Do we want further use greyed icon as described in the wiki (https://github.com/cgeo/cgeo/wiki/How-to-create-custom-icons#convert-to-action-bar-icon)? This conflicts now to the system menu button which is white.
And second: should I better now implement it as vector drawable (https://android-developers.googleblog.com/2016/02/android-support-library-232.html) because we will switch to support library 24.2.1?

**Comment by moving-bits** [comment]
tested with today's branch from @bekuno:
(same (emulated) device, different API versions)

API 26
![image](https://user-images.githubusercontent.com/3754370/53516975-dce1c100-3acd-11e9-9771-f9e6dec108a2.png)

API 22
![image](https://user-images.githubusercontent.com/3754370/53517047-04d12480-3ace-11e9-80ee-468ee2861194.png)

API 19
![image](https://user-images.githubusercontent.com/3754370/53517018-f420ae80-3acd-11e9-9aba-b6e13ed2c8bd.png)

**Comment by bekuno** [comment]
@moving-bits Thanks a lot. :)
