### ISSUE TITLE
Arrow icon indicating submenu no longer shown

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7257]
##### Detailed steps causing the problem:
- Open cache details
- Open overflow menu 

##### Actual behavior after performing these steps:
The menu items "Manage caches", "Manage lists", "Import", "Export" used to show a small right pointing arrow aligned on the right to indicate, that there is a sub menu behind. These are no longer shown

##### Expected behavior after performing these steps:
Show arrows

##### Version of c:geo used:
2019.01.23-NB

##### Is the problem reproducible for you?
Yes

##### System information:
Android 8.0

**Comment by bekuno** [comment]
Because the code uses here the appcompat library I tested the next major version (24.2.1).
It builds and now the submenu indicators are back.
This was tested only on my dev device (S6) mit Android 7.0.

**Comment by rsudev** [comment]
A quick cross-check on an Api 17 emulator was also successful. Will check a few other versions in the next days.

**Comment by rsudev** [comment]
Api 22 and 23 ok as well - I guess we can assume this will solve the issue. Thank you very much for digging this out @bekuno .
Do you plan to provide a PR?

**Comment by bekuno** [comment]
I will do it.

**Comment by rsudev** [comment]
Triggered by your idea I looked a bit further and it seems that we can even go up to compilesdk 24 and appcompat 25.4.0 (As past compilesdk 24 google maps v1 vanish, we likely can not go further than that). Perhaps something to check out.

**Comment by moving-bits** [comment]
Maybe this will correct some inconsistencies with the ActionBar as well... (* *dreaming* *)
I will wait for your PR until I dig deeper into the ActionBar issues like missing blue line, wrong height, etc. and others, maybe related issues, like wrong font sizes, or wrong dialog stylings.

**Comment by bekuno** [comment]
To use google maps v1 we have to set compileSdkVersion with the old syntax. This works until max API 24.
This means 
    compileSdkVersion "Google Inc.:Google APIs:24"
is ok, but
    compileSdkVersion 24
not. And the old syntax does not work with API 25.

The targetSdkVersion should normally not higher then compileSdkVersion.
But we have to set targetSdkVersion to minimal 26 for the play store requironments.
Currently we have set it to 27. Cgeo buils also with version 28.  
I will test a little bit with this version and check some of the visual inconsistencies.

**Comment by bekuno** [comment]
I did not seen any changes to the visual inconsistencies with targetSdkVersion 28.
And I have no emulator or device with Android 9.
So I deceided not to set this in the PR and leave for later.

**Comment by moving-bits** [comment]
Ok, and thanks for testing anyway.

As for the visual inconsistencies coming with targetSDK26: It's pretty frustrating IMHO. I've spent days of research and trying out things according to (my understanding of) the docs, but there are still a couple of layout issues I wasn't able to fix. This is mostly due to a lack of knowledge on my side, for sure, but part of it may also be related to c:geo having grown over the years (with Android layout concepts evolving over time), as well as inconsistencies in Android layout management.
For a future version of c:geo I would like to restart with a layout configuration "from scratch", even in the case that we don't change the general program structure, to get (regain) a clear and consistent base for layout configuration, which also follows the recent Android material design guidelines.
But that's probably a thing to discuss in a separate issue...

**Comment by Lineflyer** [comment]
> For a future version of c:geo I would like to restart with a layout configuration "from scratch", even in the case that we don't change the general program structure, to get (regain) a clear and consistent base for layout configuration, which also follows the recent Android material design guidelines.
But that's probably a thing to discuss in a separate issue...

Highly appreciated! This UI inconsistencies have grown over the years and we never had a consistent style or guideline when implementing new dialogs, etc.

**Comment by bekuno** [comment]
@UniQP Please close the issue manual.
