### ISSUE TITLE
c:geo allows a 'write note' on an unpublished cache.

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#7280]
A great feature of cgeo is it's ability to load a user's own unpublished caches and view/test them out.

However, we just found a problem - cgeo allows you to log a 'write note' on an unpublished cache, this is not allowed on the website, the only options there are "Post Reviewer Note" and "Archive"

We found this out when accidentally adding the solution to a puzzle cache as a 'Write note' instead of a 'Reviewer note', when the cache was published the solution was there for all to see. D'OH!

I realise this will be a low priority issue, but it'd be nice to have the option to accidentally spoil your puzzles removed.

##### Detailed steps causing the problem:
- create an unpublished cache
- load it into c:geo
- 'log a visit'

##### Actual behavior after performing these steps:
Options available are 'Review note', 'Write note' and 'Archive', and  'Write note' is the default!

##### Expected behavior after performing these steps:
Only  'Review note', and 'Archive' should be available. 'Review note' should be the default.

##### Version of c:geo used:
2018.10.13

##### Is the problem reproducible for you?
Yes

**Comment by Lineflyer** [comment]
Write note is a valid log type for unpublished caches.
Just checked it on the website....it has been bit hidden for some reason since few months ago:
- Select "Post review note"
- Change log type to "Write note"

Actually our implementation reads the log types available and uses them. So the available log types should always be identical.
