### ISSUE TITLE
Remove test data for 'cgeo.geocaching.connector.gc.TrackablesTest.testParseSpeedManagerCompressedTrackable'

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#7298]
The trackable parsing fix after the latest website change invalidates the mentioned test. New offline test data needs to be provided by someone with access to the 'speedmanager'.
Test disabled meanwhile.

**Comment by Lineflyer** [comment]
What is the "speedmanager"?

**Comment by Lineflyer** [comment]
Now I remember:
This test was added with the fix for #3118 long time ago.
I am not even sure, if these kind of proxies are still in use. Anyway I do not have access to such kind of compressed pages, thus we can never update these mocked pages. 
My suggestion would be to either remove the test or (if meaningful in this case) to manually add the change of the website to the mocked compressed page.

**Comment by fm-sys** [comment]
I did a bit of research, and it seems the Telecom/Vodafone proxies (which tried to optimize the HTML and delete some empty DIVs and not used styles) are no longer in use while we are talking about 3G, LTE or even 5G, so the currently commented out test case should be removed.

https://github.com/cgeo/cgeo/blob/9abb5b7c5e90eabbc3a6f87da54370ad81f86f70/tests/src-android/cgeo/geocaching/connector/gc/TrackablesTest.java#L89-L95
