### ISSUE TITLE
Cache description still missing for caches with gc.com checker

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7305]
##### Detailed steps causing the problem:
- Open GC834YY (as an example)

##### Actual behavior after performing these steps:
No cache description shown

##### Expected behavior after performing these steps:
Cache description shown

##### Version of c:geo used:
2019.02.17-NB

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Related to #7291 
@bekuno

**Comment by yoursunny** [comment]
I think the ultimate solution for these issues is moving away from regular expressions. Instead, parse the webpage as an XML or DOM tree, and run XPath query or CSS selector on the tree structure.
Also, to avoid rushed release during to website change, the RegExp/XPath/CSS queries can be placed on `cgeo.org` and downloaded upon application launch.

**Comment by yoursunny** [comment]
Immediate solution is removing `hints` at the end of this regexp:

https://github.com/cgeo/cgeo/blob/b730743365ead69e73e41604b24e218db1db6758/main/src/cgeo/geocaching/connector/gc/GCConstants.java#L38

**Comment by Lineflyer** [comment]
@yoursunny Thanks for your feedback. AFAIR we had similar ideas in the past but due to lack of resource it was never realized. So in case you are interested in drafting such an approach your help is always welcome.

Thanks also for the immediate solution. Will doublecheck (or if you want you can provide a PR yourself).

**Comment by rsudev** [comment]
There are already some parts which use tagsoup to parse the page. This only helps partly with website changes, as we need to change the selectors as well than.
Having  a server ready to download those expression on app start could be a bit demanding for our user base, not sure.
ATM the biggest issue is the missing readiness due to the target sdk change, otherwise would the fixed version be already out of the door probably...

**Comment by Lineflyer** [comment]
@rsudev Do you agree with the suggested regex change? I can push this if OK.

**Comment by rsudev** [comment]
PR posted
