### ISSUE TITLE
Buttons to save caches to list not correct aligned

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7342]
##### Detailed steps causing the problem:
- open live map
- Show caches as list
- Save offline
- The buttons (OK, break, last) are one above the other

![20190303_121228](https://user-images.githubusercontent.com/32555742/53698790-ae235d80-3de1-11e9-8a9d-61f61f90fa78.jpg)

##### Actual behavior after performing these steps:
The buttons are one above the other

##### Expected behavior after performing these steps:
The buttons are side by side

##### Version of c:geo used:
2019.02.23

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
reported by Spooky155 on IRC

**Comment by Lineflyer** [comment]
Also reported by other users on support:
![grafik](https://user-images.githubusercontent.com/949669/53736775-02cee300-3e8b-11e9-87c6-15c07fe2c491.png)
```
--- System information ---
Device: SM-G950U (dreamqltesq, samsung)
Android version: 8.0.0
Android build: R16NW.G950USQU5CSA4
c:geo version: 2019.02.23
Google Play services: enabled - 15.0.90 (040408-231259764)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: fast
HW acceleration: enabled (default state)
System language: en (c:geo forced to English)
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (21.3 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (21.3 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (21.3 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (33.8 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: MMM/dd/yyyy
Installed c:geo plugins: contacts
--- End of system information ---
```

**Comment by moving-bits** [comment]
Hm, doesn't seem to hit all versions / devices. I can reproduce this on my physical mobile, but not in an emulated API 26 device:

![image](https://user-images.githubusercontent.com/3754370/53758760-f3698d00-3ebe-11e9-9798-876ace7cb6c8.png)

Will investigate further...

**Comment by Lineflyer** [comment]
@moving-bits What your physical device?

**Comment by moving-bits** [comment]
Samsung A5(2016), running on Android 7

**Comment by Lineflyer** [comment]
Might be depending on resolution (some kind of automatic line break if the screen width is not enough)?

**Comment by moving-bits** [comment]
I've tried changing language settings to English, and now everything is back onto one line on my physical device. => Will retest with setting language to German in the emulator.

**Comment by moving-bits** [comment]
Hm, still a one-liner in the emulator (API 26, language settings switched to German).

**Comment by moving-bits** [comment]
After some tweaking I got c:geo to either display the buttons in a single line (if they fit) or expand the lower part of the dialog, so that you don't have to scroll the button part of the dialog.

a) with font size "extra large":

![image](https://user-images.githubusercontent.com/3754370/53762515-98d52e80-3ec8-11e9-886e-98e8ccfba0a4.png)

b) with font size "standard":

![image](https://user-images.githubusercontent.com/3754370/53762649-e3ef4180-3ec8-11e9-87db-307f1c1d9edd.png)

---

(and, as a side effect, it brings back the cyan/grey buttons we had earlier)

**Comment by Lineflyer** [comment]
> After some tweaking I got c:geo to either display the buttons in a single line (if they fit) or expand the lower part of the dialog, so that you don't have to scroll the button part of the dialog.

That is basically the same what is happening to the initial author of this issue. Only that he needs to scroll due to the amount of lists shown and/or the smaller screen or something else, I guess.

That makes me think, such kind of issues need to wait to have a global rework of the design.

> (and, as a side effect, it brings back the cyan/grey buttons we had earlier)

WTF....

**Comment by moving-bits** [comment]
> That is basically the same what is happening to the initial author of this issue. Only that he needs to scroll due to the amount of lists shown and/or the smaller screen or something else, I guess.

I don't think so. An AlertDialog consists of three logical parts: a title section, a content section, and the button section. Content section and button sections can be scrollable independently of each other. The initial error showed a scrollable button section, even for lists with just a couple of entries, whereas the current approach expands the button section if needed - at least in the emulator I had tested this.

**Comment by bekuno** [comment]
My favorite is the one row solution. Then we have more lists selectable.
Scrolling the button area is not really good.
Also we could suggest to the translators to shorten the text , if this is somehow possible.

**Comment by moving-bits** [comment]
My favorite would be one row as well, but when the text is too wide, Android skips to multi row display. For whatever reason the targetSDK26 change triggered a somewhat wider display of the button texts, so that for some resolutions and font sizes the text gets too wide and the buttons get stacked, which leads to the scrolling button area as it has a fixed height.

The PR I could create would at least avoid scrolling the button area in those cases, but instead automatically make it larger, if needed.

Making the translations shorter would help, as well. (eg: For German it could be changed from "Letzte Auswahl" to "Letzte". But I have cross checked: The text for this button has not changed during the last year, so it has to be a different reason that triggered the changed display.)

**Comment by bekuno** [comment]
Here is a screenshot with this dialog in version 2018.10.13.
The button text is much smaler than the list text.
![20190306_091512](https://user-images.githubusercontent.com/32555742/53866100-09776a80-3ff1-11e9-89c0-1b36e0f19735.png)

**Comment by Lineflyer** [comment]
Can we just define the button text a little smaller, so that the possible percentage of users affected by line breaks gets smaller?

**Comment by moving-bits** [comment]
see screenshots attached to PR7348

**Comment by Lineflyer** [comment]
@moving-bits 
I just compiled a new RC-version based on `release` branch and thus including your change 099e20e 

I can see a visual difference in other menus to the worse on my test device Samsung S4 running Android 5.0.1. Not 100% sure, if your change is causing it, it might also be some other change on release since 2019.02.23. But I think yours could likely cause such change?!

Release version 2019.02.23:
![Screenshot_2019-03-10-22-23-18](https://user-images.githubusercontent.com/949669/54091744-df70d000-4383-11e9-8e44-6107204fbb54.png)


Release candidate, a.k.a. `release` branch as of today:
![Screenshot_2019-03-10-22-24-18](https://user-images.githubusercontent.com/949669/54091751-f3b4cd00-4383-11e9-8866-f1aeef2471aa.png)


As you might see, the boxes around the action triggering buttons disappeared, which does no longer imply, that they are buttons and not only text.

**Comment by Lineflyer** [comment]
I can also open a dedicated issue if required and better for tracking this.

**Comment by moving-bits** [comment]
Hm, this might be caused by my PR, as I had a hard time to get rid of the surrounding lines for the buttons in the "save list" dialog. Maybe I killed a few lines too many...

Do you want to revert this PR or should I create a new one to fix this problem? (But won't be before tomorrow.)
