### ISSUE TITLE
Background of "Cancel" button is ugly gray

### ISSUE THREAD

**Issue by okainov** [cgeo/cgeo#7362]
(targetsdk regression)

##### Detailed steps causing the problem:
- On some pop=up dialogs where "Cancel" button is present, it's super ugly
![2019-03-12 17 35 28](https://user-images.githubusercontent.com/918446/54224084-187e8100-44f9-11e9-962d-9772953615f7.jpg)

##### Version of c:geo used:
master+su

##### System information:
Android 8

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by moving-bits** [comment]
Best thing I've discovered so far brings us to this:

![image](https://user-images.githubusercontent.com/3754370/54476290-d8224a00-47fb-11e9-840f-d239703f88b2.png)

The button itself has a black background and no margins, but I have found no way to change the background color of the button panel part of the dialog (which is the remaining grey part).

**Comment by okainov** [comment]
@moving-bita as for me it still looks ugly. How are the other apps are making such a dialogs normally?

**Comment by moving-bits** [comment]
> @moving-bita as for me it still looks ugly.

Yes, for me as well. That's why I haven't created a PR for this yet.

>How are the other apps are making such a dialogs normally?

They use a consistent styling throughout the app. (Ideally)
Styling in c:geo has evolved and mixed up over a course of nearly ten years. Android has developed as well, over this time, fixing bugs and introducing new things (layout wise). The grey background seen above is one of those artifacts, a side effect of changing the target SDK to a more recent version.

To get all styling in c:geo nice and consistent again, we need a complete redo for c:geo styling IMHO - everything else is just bugfixing right now. But this is quite a bit task, and we're currently only a couple of active developers.
