### ISSUE TITLE
remove or deprecate support for Eclipse IDE

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7381]
Currently nobody works with Eclipse IDE anymore.
So I suggest to remove the folder main\libs\. With AS, the required jar-files are obtained automatically.
Alternatively, there would be an info file in the folder, in which the historical, unmaintained status is pointed out.
The removal or adaptation of the corresponding lines in global README.md would also be necessary.

**Comment by bekuno** [comment]
Also the gradle tasl "main:downloadLibs" does not work anymore.
It throws:
Build file 'C:\StudioProjects\cgeo\main\build.gradle' line: 616

* What went wrong:
Execution failed for task ':main:downloadLibs'.
> Resolving configuration 'implementation' directly is not allowed

**Comment by bekuno** [comment]
As in PR #7316 a lib file was deleted when updating the configuration for this lib I asume that we no more need this libs.
Therfore I will prepare a PR to remove this.

**Comment by Bananeweizen** [comment]
I actually use Eclipse for cgeo development. However, I can live with the libs folder and the documentation being removed, since I typically work on a "manipulated" branch anyway (e.g. I have libs\assertj.jar restored on my development branch). Please do not delete eclipse specific .prefs and .project files, otherwise my workspace management get's completely confused.

**Comment by bekuno** [comment]
solved by commit 8726f290315428bbc65b1f5a8f0096fa12d8f90b
