### ISSUE TITLE
Duplikaterkennung wär schön

### ISSUE THREAD

**Issue by Beiri22** [cgeo/cgeo#7599]
Wenn ein Nutzer auf Geocaching.com und Opencaching.de angemeldet ist, dann werden doppelte Caches einfach übereinander angezeigt. Das ist nicht so schön. Vielleicht könnte man einen Algorithmus zur Duplikaterkennung einfügen, sodass solche Dupletten dann nur als ein Symbol gezeigt werden (Allein durch die Koordinaten sollte das schon möglich sein...), und in der Detailansicht, stehen dann beide Codes (GCXXXXX, OCXXXXX). Dann könnte beim Loggen in beiden Systemen ein Eintrag erstellt werden... Wenn das läuft, könnte man auch einen Übertragungsmodus für bereits gefundene Caches machen. Einfach mit dem gleichen Algorithmus die gefundenen  Caches der Systeme miteinander abgleichen, ggf. nachholen.

**Comment by SammysHP** [comment]
I think this is a duplicate of #2349 which is also about handling of caches that are listed on multiple platforms.

Just one more comment: Using the same detail view for both listings won't work because they can be different (and the features of the platforms are not equal like OC supports multiple languages and different attributes).

**Comment by SammysHP** [comment]
Just a short summary in German:

Dieser Issue ist ein Duplikat, daher habe ich ihn geschlossen. Da sich der Inhalt der Beschreibungen unterscheiden kann, lässt sich nicht die gleiche Detailansicht für mehrere Plattformen gleichzeitig verwenden.
