### ISSUE TITLE
Hint button doesn not do what is explained in the user guide

### ISSUE THREAD

**Issue by Linsty** [cgeo/cgeo#7691]
**Describe the bug:**
I'm translating the user guide of c:geo to dutch and to check if wat I'm translating I follow the steps on my devices to make sure I translate everything correct.
According to the userguide (Hint/Note section in Live map)  this should happen:

> If you clicked the hint button in the cache information section of the popup window, the owners hint and/or your personal note will be shown at the bottom of the popup window. In case of a long text you can scroll this part of the popup window.

The output only shows the hint of the owner, but personal notes aren't displayed.
Tested this on my LG G5 smartphone and my Lenovo Tablet TB-X705L

**To Reproduce:**
1. Go to Live map (doesn't matter if live is switched on or off)
2. Click on hint icon
3. Look at the lowest section of the popup screen

**Actual behavior/state after performing these steps:**
Cache owners hint

**Expected behavior/state after performing these steps:**
Cache owners hint + personal note

**Version of c:geo used:**
2019.06.06

**Is the problem reproducible:**
Yes

**Screenshots:**
Image shows the cache description with the hint and the personal note within cache details:
![cache details](https://user-images.githubusercontent.com/51774787/59902674-306e7680-93ff-11e9-94b4-7f43264d5aef.png)
The hint is shown on the popup screen but the personal note isn't:
![popup screen](https://user-images.githubusercontent.com/51774787/59902675-306e7680-93ff-11e9-96c8-bf3e1d7af505.png)

**System information:**
```
 --- System information ---
Device: LG-H850 (h1_global_com, lge)
Android version: 8.0.0
Android build: OPR1.170623.032
c:geo version: 2019.06.06
Google Play services: disabled - 17.7.84 (040400-252519124)
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide own/found: false
HW acceleration: enabled (default state)
System language: nl_NL
System date format: dd-MM-yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (8,1 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (8,1 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (8,1 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (4,7 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Ingelogd) / PREMIUM
opencaching.nl: Logged in (Ingelogd)
Geocaching.com date format: d.M.yyyy
Installed c:geo plugins: none
--- End of system information ---
```

**Additional context:**

**Comment by SammysHP** [comment]
It would help if you describe your problem. It also helps to fill in the template completely.

**Comment by bekuno** [comment]
Maybe you mean the problem #7634?

**Comment by Linsty** [comment]
Apperently Github wasn't stable when I added this. The template was filled completely. I reqrote it again and hope the text will stay visible.

**Comment by bekuno** [comment]
The "note" part is not yet in the relese 2019.06.06.
Please test with the latest nightly.

**Comment by moving-bits** [comment]
@Linsty  Thank you for carefully cross-checking implementation and documentation! 🚀

Adding the personal note to the hint button was done with PR #7654, which is already merged to master, but has not been released yet. See #7665 for release state.

**Comment by Linsty** [comment]
Ok thanks, I didn't know the user manual is related to a future release. Maybe it's a good idea to put a little disclaimer on the user guide or on the website that the user guide is based on a different version than the current public stable release?
I will download the latest nightly builds when I translate so I don't make this mistake anymore and don't have to bother you for this :)

**Comment by Lineflyer** [comment]
Well I made life easy for me when updating the english pages some days ago and included both functions.

Its not generally the case, that the manual is not based on available features. Mainly I wanted to avoid forgetting to update it again in some weeks. :)

**Comment by Linsty** [comment]
I completely understand but with a little disclaimer something like this below you are always covered with that. It's just an idea not a demand to make your life easier :)

To improve your geocaching experience, a large team of people is working on new functionalities and other improvements for c:geo.
Of course we try to connect the user manual with the current stable version of c: geo. But occasionally it may occur that the user manual is slightly ahead or behind the version you use on your Android device.

**Comment by Lineflyer** [comment]
Part of the suggested text is already at the end of the start page :)Feel free to extend that english text accordinglyVon meinem Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Linsty <notifications@github.com> Datum: 21.06.19  21:42  (GMT+01:00) An: cgeo/cgeo <cgeo@noreply.github.com> Cc: Lars <gc@droescher.eu>, Comment <comment@noreply.github.com> Betreff: Re: [cgeo/cgeo] Hint button doesn not do what is explained in the
  user guide (#7691) I completely understand but with a little disclaimer something like this below you are always covered with that. It's just an idea not a demand to make your life easier :)
To improve your geocaching experience, a large team of people is working on new functionalities and other improvements for c:geo.
Of course we try to connect the user manual with the current stable version of c: geo. But occasionally it may occur that the user manual is slightly ahead or behind the version you use on your Android device.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cgeo/cgeo/issues/7691?email_source=notifications\u0026email_token=AAHH3JK6T7DEJSHIWPKN7H3P3UVKZA5CNFSM4H2CZLCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYJNFHA#issuecomment-504550044",
"url": "https://github.com/cgeo/cgeo/issues/7691?email_source=notifications\u0026email_token=AAHH3JK6T7DEJSHIWPKN7H3P3UVKZA5CNFSM4H2CZLCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYJNFHA#issuecomment-504550044",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
