### ISSUE TITLE
Proximity notification follow up

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7699]
Just a few unsorted and unjudged test results from today (using current nightly build incl. the new proximity notification):

I only tested it on new mapsforge offline map for the moment

- It seems(!), that the generic notification is also issued if the set threshold is crossed from smaller to higher
- The generic notification is repeated as soon as I resume the map after e.g. leaving it to look at popup, cache details or put my device to standby
- It does not work for me when the screen is off (might be depending on android powersaving (in case it should work at all under this condition))
- While the generic notification is easy to understand and use, I had to look up the PR description to understand the specific notification (and found out I never used it during my test). I don't really get the sense of it...maybe this will change if I only use the specific but not the generic.
- However I could imagine also using two thresholds for the generic notification. As far as I understood and tested the generic has only one threshold, but somehow I expected also hearing two different tones depending on the set thresholds in that mode
- On my device (Samsung S10, Android 9) the sound was not as loud as I would have expected it despite my device being set to highest volume (maybe I made a mistake in terms of what type of volume setting to adjust)

These comments are not meant to trigger any changes to the feature at first place, but just - first of all - to discuss the experiences I made while testing.

**Comment by moving-bits** [comment]
Hi Lineflyer,

thanks for testing and the extensive feedback.

> It seems(!), that the generic notification is also issued if the set threshold is crossed from smaller to higher

Hm, will have to retest this. At least this would not be intended for general notification.

> The generic notification is repeated as soon as I resume the map after e.g. leaving it to look at popup, cache details or put my device to standby

This is explainable, as I've put instantiation into `onResume` to avoid some issues with Android forcing activities out of memory. `onResume` gets called after closing a sub window (among other situations). But the question is whether this "restart" (or acoustic reminder?) would be the expected behavior.
(Maybe I can add a check whether it's still in memory and refresh only when necessary.)

> It does not work for me when the screen is off (might be depending on android powersaving (in case it should work at all under this condition))

Yep, power saving, as GPS is turned off then. Same as for GPS-dependent tts.

> While the generic notification is easy to understand and use, I had to look up the PR description to understand the specific notification (and found out I never used it during my test). I don't really get the sense of it...maybe this will change if I only use the specific but not the generic.

It depends on how you're out caching - you'll probably use either general or specific notification, but not both. My regular use case is that I'm looking for a specific cache, open cache popup on map to see some detail information as well as distance and hint. Normally I leave the popup window open. This is where specific notification jumps in (if enabled). (It would also work for compass view.)
General notification in contrast is unspecific. You stay in map view, and c:geo signals you when any of the visible caches or waypoints is within the configured range.

Another difference between the two is, that general notification only beeps once (side effects of the `onResume` thing left aside), whereas the specific notification repeats its signalling every couple of seconds, as long as you're within the set ranges.

General and specific notification can be enabled/disabled separately from each other. They share one distance setting (the "far" distance / distance 1).

> However I could imagine also using two thresholds for the generic notification. As far as I understood and tested the generic has only one threshold, but somehow I expected also hearing two different tones depending on the set thresholds in that mode

This should be easy to implement - by setting one parameter to `true` and adjust some descriptive text :-)

> On my device (Samsung S10, Android 9) the sound was not as loud as I would have expected it despite my device being set to highest volume (maybe I made a mistake in terms of what type of volume setting to adjust)

Volume parameter is set to max in source, but I'll look up which type of volume I'm using.

> These comments are not meant to trigger any changes to the feature at first place, but just - first of all - to discuss the experiences I made while testing.

Your feedback is very welcome, looking forward to bring this long standing issue on the road :-)

**Comment by moving-bits** [comment]
I did a first code-wise followup today (see PR 7708):

> It seems(!), that the generic notification is also issued if the set threshold is crossed from smaller to higher

I could not reproduce this behavior. I think what you experienced is related to the next point.

> The generic notification is repeated as soon as I resume the map after e.g. leaving it to look at popup, cache details or put my device to standby

This was due to a strange behavior of NewMap: After closing the popup the cache for which the popup was opened is unavailable for a short amount of time, thus the proximity calculation has a somewhat higher closest distance. After that instance the cache is back again, and so is the distance calculation. For the proximity algorithm this was a sequence of having moved away from the cache far enough to leave the signalling radius, and then being close enough again, so a tone was emitted.

I've tackled this scenario by ignoring up to three consecutive enlarging distance values. We need to check whether a fixed amount of ignored signals is fine, or if I should remember a timestamp.

> However I could imagine also using two thresholds for the generic notification. As far as I understood and tested the generic has only one threshold, but somehow I expected also hearing two different tones depending on the set thresholds in that mode

I've activated two tones for general proximity notification as well. (This is for testing purposes, have not yet changed the related settings entries.)

@Lineflyer  If you find time to retest this in the wild, feedback would be highly appreciated.

**Comment by Lineflyer** [comment]
I merged and will test on nightly. Tomorrow i might do some caches but in the field with my bike...another use case ;)

**Comment by Lineflyer** [comment]
Here is a little bit of test results from today nightly 2019.06.30-NB including the latest adaptions to the proximity notifcations:

I simply all the time used the new map (offline file) on live map and enabled the notification with distance1=100m and distance2= 20m .

My unsorted experiences:
- The two different thresholds do now work in plain live mode (not having any cache selected). This is a very convenient feature IMHO.
- No more doubled notifications (only when completely leaving and reentering the map while within the threshold(s). This looks fine to me, as when I start the map I want to get notified if something is near
- I had some caches saved and thus waypoints of them being shown. However the notification is not triggered for any of those waypoints, which I have tested. Working always for caches, but never for other waypoints shown on map
- I am unsure about the tone itself. Its enough for me to draw my attention to the mobile display, while on my bike, which is fine. The volume however is not as high as I would expect despite using the max volume on all volume channels. So if its in my pocket or there is more noise around it might be not loud enough. Maybe it is not a thing of volume, but of tone frequency and length. Maybe it could be tuned to a bit higher frequency and double length?
- From the description of the second step notification (at the moment named "specific notification") I would have expected a different tone than the generic notification. It is however not different but only doubled...am I right? In most cases that's fine, but could be confused with two nearby waypoints coming into range short after each other.  I am undecided, whether it could be better touse more of the same tones in shorter interval (e.g. 4 tones with very short length and fast interval).

Thanks @moving-bits for implementing so far!!

**Comment by moving-bits** [comment]
@Lineflyer  Thank you for taking the time to test. I'll try to dive into the issues the next days.

AFAIU it's currently
- waypoints not being recognized (should work on NewMap, unsure about CGeoMap)
- tones: right now I use two predefined tones ("single beep" and "double beep") for both general notification and specific notification - single beep for distance1, double beep for distance2 (for both notification types, as the message is basically the same "cache within x meter range")
- volume

(besides maybe other issues from your first test)

**Comment by Lineflyer** [comment]
> tones: right now I use two predefined tones ("single beep" and "double beep") for both general notification and specific notification - single beep for distance1, double beep for distance2 (for both notification types, as the message is basically the same "cache within x meter range")

I am fine with same tonew in generic and specific. I just confused the wording here...with specific I meant the double tone. 
We should rephrase/resort the menu entries to match the current implementaion, then my confusion will be solved. ;)

**Comment by moving-bits** [comment]
> I am fine with same tonew in generic and specific. I just confused the wording here...with specific I meant the double tone.
> We should rephrase/resort the menu entries to match the current implementaion, then my confusion will be solved. ;)

To resolve your confusion see PR 7716 ;)

**Comment by moving-bits** [comment]
I've implemented some adjustments in PR #7718:

> I am unsure about the tone itself. Its enough for me to draw my attention to the mobile display, while on my bike, which is fine. The volume however is not as high as I would expect despite using the max volume on all volume channels. So if its in my pocket or there is more noise around it might be not loud enough. Maybe it is not a thing of volume, but of tone frequency and length. Maybe it could be tuned to a bit higher frequency and double length?

As a first try I've set the output channel from STREAM_ALARM to STREAM_MUSIC - maybe this is more configurable. (If this does not work, then self creating a set of tones instead of using the predefined ones may be necessary.)

> From the description of the second step notification (at the moment named "specific notification") I would have expected a different tone than the generic notification. It is however not different but only doubled...am I right? In most cases that's fine, but could be confused with two nearby waypoints coming into range short after each other.  I am undecided, whether it could be better touse more of the same tones in shorter interval (e.g. 4 tones with very short length and fast interval).

I've doubled the signalling for TONE_NEAR, resulting in four tones played. Does this work for you?

**Comment by Lineflyer** [comment]
I will merge, test and feedback next days.Thanks for your effortVon Samsung-Tablet gesendet
null

**Comment by moving-bits** [comment]
> I had some caches saved and thus waypoints of them being shown. However the notification is not triggered for any of those waypoints, which I have tested. Working always for caches, but never for other waypoints shown on map

Should be fixed for NewMap with PR #7719.

**Comment by Lineflyer** [comment]
I tested the notification during my bike tour the last days using the newest nightly:

- I think it works reliable so far
- The volume can now be adjusted using the media volume on my device
- The triple tone for the second notification is much better as it can no longer be confused with the first notification

The repetition of tones when leaving/reentering the map is still somehow confusing me, but better this way than missing a notification.

Further improvements (will open dedicated issues for that tomorrow) could be:
- Find a way to temporary disable the tone or make it follow device global settings(I walked into a church, set my phone to silent mode but still the tone came up)
- Allow a user defined audio file (e.g. from installed ringtones)
- Sliders for distance setting are tricky to set to the desired value. We could additionally make the distance itself clickable and allow setting a value via keyboard

@moving-bits 
One last question for clarification of functionality:
Is there now still a specific notification for a single cache (as implemented in your first version) or is it now only a generic one with two distance levels? 
Reason for my question is, that notifications are played each time when I open a popup of a waypoint while being close to it.

**Comment by Lineflyer** [comment]
> I've doubled the signalling for TONE_NEAR, resulting in four tones played. Does this work for you?

I could swear its three tones, not four. But whatever: It is OK like this.

**Comment by Lineflyer** [comment]
> @moving-bits
> One last question for clarification of functionality:
> Is there now still a specific notification for a single cache (as implemented in your first version) or is it now only a generic one with two distance levels?

After reading the menu settings again I think I finally understand it now.
But what actions make a cache being a selected cache for the notification. The popup being opened is one trigger, is there another one?

**Comment by moving-bits** [comment]
> But what actions make a cache being a selected cache for the notification. The popup being opened is one trigger, is there another one?

There are three trigger points for specific proximity notification:
- open cache details popup from map view
- open waypoint details popup from map view
- start compass navigation

If you have "specific proximity notification" enabled in settings and the two distances are set, no further action besides the above mentioned trigger is necessary to start the specific proximity notification check.

**Comment by Lineflyer** [comment]
Thanks @moving-bits for explanation and implementation.
Lets close here and open dedicated issue for the potenial mentioned improvements
