### ISSUE TITLE
Sliders in settings might are hard to set to distinct value

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7726]
The sliders using in c:geo setting for proximity notification setting as well as some other settings (e.g. waypoint visibiltiy) are tricky to be set to the desired value using the sliding function.
We could additionally make the distance itself clickable and allow setting a value via keyboard

**Comment by moving-bits** [comment]
I see two things which need to be tackled:

a) Some settings have a wide range of allowed values, but only so much screen space to select it with the touch glider. => Here manually entering the desired value can help.

b) There is a design glitch in current implementation of AbstractSeekbar, as it stores the current internal slider value, which may or may not be the value you seen on screen (due to either translating between km and miles or the seekbar working on a exponential scale to get a finer resolution for small values). Current exp based sliders only have an internal value range from 0 to 75, so only 76 different values are possible. If you manually enter a different value, it gets rounded to the nearest possible one.

I created PR #7747 for a), but need to extend it for use case b)

Ideally both is done before releasing the next release, but I'm currently not able to build a version, so if time runs out we can release either "as is", or with a) only, and release the fix for b) later.

**Comment by moving-bits** [comment]
> Ideally both is done before releasing the next release, but I'm currently not able to build a version, so if time runs out we can release either "as is", or with a) only, and release the fix for b) later.

Both done / PR 7747 updated accordingly. Currently this PR is targeted to master - shall I retarget it to release branch?

**Comment by Lineflyer** [comment]
Lets keep it on `master`. So we have no risk for any side effects and already a new feature improvement for next feature release :)

Thanks @moving-bits
