### ISSUE TITLE
map not supported by current library (error message)

### ISSUE THREAD

**Issue by andrixnet** [cgeo/cgeo#7801]
Assume my map is now showing OSM offline file of v4 type. 
I go to settings and check "use old mapsforge v3".
When I return to map, I briefly see an overlay popup error message that quickly dissapeared. Possibly also due to taps I was making. 

Trying to make it happen again I managed to read something about current map not supported.

IMO this error message should not be an overlay popup, but a modal box with OK button so the user is clearly informed why the map is empty.

**Comment by Lineflyer** [comment]
IMHO we should remove the old mapsforge rather soon.
We do only have some minor regressions (e.g. distance circles) to be fixed on the new map.

So I would not invest too much effort into error handling for unsopported files in V3.

**Comment by rsudev** [comment]
Circles implementation is almost ready (hopefully hits master in August)

**Comment by andrixnet** [comment]
That's fine. 
Might I suggest, however, that the principle behind this issue be applied to new map api?
(I mean, if the new API throws an error such as this, be displayed as modal dialog, if does not already do so. thank you.)

**Comment by moving-bits** [comment]
Generally an exception handling for unsupported map file versions is already in place and should work for future map versions as well. Sadly the Mapsforge API does not export the min and max file version numbers supported, but simply throws an general exception when something's wrong, so the error message is a bit unspecific.

I'll create a PR to
- make the error message a bit clearer and
- make it a dialog instead of a toast message.
