### ISSUE TITLE
Cache waypoints vanish from map when closing popup

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7812]
**Describe the bug:**
Not sure what change caused this behaviour, but I do now see the problem, that waypoint suddenly get hidden on the map.

**To Reproduce:**
1. Have a stored cache with several waypoints (some in state visited, some not - if that makes any difference)
2. Open the map for this stored caches
3. Click on a waypoint to open the popup for it
4. Close the popup again

**Actual behavior/state after performing these steps:**
The cache icon is still shown, however all waypoints get hidden

**Expected behavior/state after performing these steps:**
Cache and waypoints shoudl be shown same as after step 2

**Version of c:geo used:**
2019.08.26-NB1

**Is the problem reproducible:**
Yes

**Comment by Lineflyer** [comment]
@moving-bits I think this one could be related to the commits in #7809

**Comment by moving-bits** [comment]
@rsudev / as discussed on IRC:
I provided current state branch issue_7812 in my repo.

Current state on this branch is:
- repainting overlays does work for both live map and map opened from single cache details menu
  - when opening a waypoint popup from the map
  - and either changing nothing or only the visited state directly from the popup
- but does not work (for both maps)
  - when using the waypoint editor

although the latter does seem to work when opened the first time, but on no subsequent calls.

Additionally (although I don't know if it's related): After having opened the waypoint editor from either the map's waypoint popup or from the cache detail's waypoint page, an error occurs in LogCat several times: `"E/SpellCheckerSession: ignoring processOrEnqueueTask due to unexpected mState=TASK_CLOSE scp.mWhat=TASK_CLOSE"`

**Comment by moving-bits** [comment]
@rsudev 

I updated my branch to make NewMap listening to the broadcast sent by `EditWaypointActivity` and invalidating cache & waypoint after that, but even with this cache and waypoint either do not get updated or they do not recognize the changes made in `EditWaypointActivity`.

Can you have a look at it and give me a hint what's going wrong? Thanks!

**Comment by moving-bits** [comment]
I created a PR to fix this one. But problem described above remains, so I reopen #7695, as it is fixed only partially.
