### ISSUE TITLE
Remove old mapsforge v3

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7836]
Looking at the remaining [open issues dealing with the new mapsforge implementation](https://github.com/cgeo/cgeo/issues?q=is%3Aopen+is%3Aissue+label%3A%22New+Map+OSM%22) it might be time to decide upon retirement of the old mapsforge implementation rather soon.
Although there is no urgent need at this moment, it is also a matter of testing and maintaining. Not sure e.g. how the old mapforge library will work when raising or compile and target SDK. 

IMHO all real critical regressions are fixed by now. What do you think?

**Comment by mirabilos** [comment]
Objecton: the new implementation is much too slow on some devices, and it reverses the order in which caches and map tiles are rendered, respectively, making using c:geo for navigation much harder than it should be.

Please retain the Mapsforge V3 implementation.

**Comment by Lineflyer** [comment]
> Objecton: the new implementation is much too slow on some devices, and it reverses the order in which caches and map tiles are rendered, respectively, making using c:geo for navigation much harder than it should be.

Please kindly open dedicated issues for the described problems (unless they exist already) with the new mf.

**Comment by mirabilos** [comment]
Lars dixit:

>Please kindly open dedicated issues for the described problems (unless
>they exist already) with the new mf.

It’s not as you could help the fact that it is too slow…

**Comment by andrixnet** [comment]
In principle I do agree with a move such as this.
However, in this situation I am not keen on supporting in, on the contrary. 
I have several open issues regarding differences in behaviour between Mapsforge library versions.
- Mapsforge Beta - render performance #6279
- Less map data on mapsforge beta #6069
- related: Offer alternate map themes #6071
- related: map not supported by current library (error message) #7801

**Comment by Lineflyer** [comment]
@andrixnet Regarding #6069 please kindly check my latest comment there.

**Comment by moving-bits** [comment]
Regarding
> * related: Offer alternate map themes #6071

This is not specific to whether Mfv3 is still supported or not. Both Mf implementations support themeing (although themes are map- and version-specific), and both Mf implementations come with a built-in standard theme when using the default map from mapsforge.org.

Also
> * related: map not supported by current library (error message) #7801

is only relevant as soon as there are new map versions which are not supported by our current Mf implementation. (And someone needs to check first whether we can do anything at all about that message, or if it's coming from within the library we're using.)

To my understanding the only possibly blocking issue mentioned here is the one about render performance (#6279). ("possibly" insofar as we have to balance the extra workload for supporting two different Mf implementations against the user- / device-base we reach additionally by supporting the faster and more lightweight v3 implementation.)

So a solution could be to add a warning message marking v3 implementation as deprecated (as suggested by @jonas-koeritz), leaving v3 implementation "as is" otherwise, but not actually removing it for now, keeping it for as long as "it does not hurt". If a new SDK level etc. would imply relevant extra work to keep v3, we could remove v3 then.

**Comment by mirabilos** [comment]
moving-bits dixit:

>leaving v3 implementation "as is" otherwise, but not actually removing
>it for now, keeping it for as long as "it does not hurt".

Thanks.

>If a new SDK level etc. would imply relevant extra work to keep v3, we
>could remove v3 then.

These most likely would remove support for running c:geo on kitkat
altogether, so by then it’d be moot for me.

I wonder whether it’s possible to do a fork of c:geo that’s otherwise
kept up to date but targets older SDK (possible because it would not
be uploaded to Google Play Store), drops the various Google APIs, uses
older OC connector (to unbreak OC.DE) and keeps Mapsforge v3 working.
I’ve got experience running OSS projects, but not Android. I’d start
by trying to compile it at all, then reverting individual commits, and
then merging c:geo master all the time, but I’m sure I’d need help, at
the _very_ least the c:geo upstream devs conscious of that and making
changes in a way that’s friendly to keep a reversion patch around (git
deals with diffs in whole lines and related blocks)… just wondering at
the current point in time, but if c:geo is forced by Google Play Store
to drop support for my device I might be forced to do that (although I
already have too many projects on my plate).

**Comment by jonas-koeritz** [comment]
Stock Android KitKat is so outdated that some TLS connections fail because the CA certificates on the device have expired. I can understand that there might be users running KitKat in 2019 but even the Google Play Services have already dropped support for it.

**Comment by mirabilos** [comment]
Jonas Köritz dixit:

>Stock Android KitKat

Thankfully it’s far from stock ☻

>but even the Google Play Services have already dropped support for it.

No, they work (on a second identical device I recently acquired),
but they make the entire system so slow it’s basically unusable.

Good thing we have microG ☺

**Comment by jonas-koeritz** [comment]
May I ask on what kind of device you're required to still run KitKat?

**Comment by andrixnet** [comment]
Regarding #7801 
Note that mapsforge download now offers maps for three different library versions. (v3, v4 and v5). 
Since at any one time more then one library version exists and more then one map version exists, the possibility exists for any user to get the wrong map file, in which case he/she should be presented with a proper error message.

Regarding a possible c:geo fork, it may still continue to be available via cgeo website and possible alternate stores such as Aptoide (?).

**Comment by mirabilos** [comment]
Jonas Köritz dixit:

>May I ask on what kind of device you're required to still run KitKat?

HTC Desire and Note 3. I downgraded the latter to kitkat because
the Android 5 UI differs completely, and the aftermarket ROM I
use is available for both. But the HTC Desire is my primary device,
for my values of primary (i.e. GPS-based games, mostly… I use a
regular cell phone as phone, and a laptop for anything else).
Also, the HTC has way better GPS than anything Samsung.

**Comment by bekuno** [comment]
Please reduce this version discussion.
We use minSdkVersion 16, which means "Jelly Bean" (Andriod 4.1), KitKat is Andriod 4.4, API 19.
I currently see no need to change this value. Maybe we need an update if this is necessary for reasons that are not the responsibility of c:geo. (Google (play store), outdated external libraries). Android does not plan changes in his support library (https://developer.android.com/topic/libraries/support-library)
The last change in c:geo was in PR #7360. (minSdk 14 to 16)
If an older version is needed, it can be obtained from GitHub (https://github.com/cgeo/cgeo/releases).

@mirabilos Instead of thinking of a fork from c:geo, a participation in the further development would be more target-oriented.

**Comment by mirabilos** [comment]
Bernd dixit:

>@mirabilos Instead of thinking of a fork from c:geo, a participation in
>@the further development would be more target-oriented.

I’m not interested in adding Android development to the already crazy
amount of things on my pile. I’m a c:geo u̲s̲e̲r̲. What I was doing is
wondering about continuing to use c:geo when it won’t work on my GPSr
any more.

**Comment by Lineflyer** [comment]
Regarding the support of older Android versions in general:

In the past we already implemented the method to handle a legacy version once we change the minSDK. The last used legacy version is retired meanwhile, but our version management system should still be capable of this.
However this method is always only a temporary solution: We will try to do our best to keep such legacy version working (i.e. backport needed fixes for server changes, but nothing else) but at a certain point of time we will retire it anyway. So it only provides a bit more time and flexibility to users running rather old SDK combined with a big fat warning, that support will end soon.

For those which are rather new to the project:
- Branch `legacy` was used for it and CI and version control are able to handle this second release version. 
- Via Android manifest we can define a maxsdk to be able to upload different versions via Google Play, which is used in this context.

But - as also said by others - we should only go this way if we are forced to.

**Comment by mirabilos** [comment]
Lars dixit:

>different versions via Google Play, which is used in this context.

Does this mean these would be only available via Google Play Store?

>But - as also said by others - we should only go this way if we are
>forced to.

Thanks.

**Comment by Lineflyer** [comment]
> Does this mean these would be only available via Google Play Store?

No, the APK file could for sure be made available on other channels (website, fdroid) as well.

**Comment by moving-bits** [comment]
> Regarding #7801
> Note that mapsforge download now offers maps for three different library versions. (v3, v4 and v5).
> Since at any one time more then one library version exists and more then one map version exists, the possibility exists for any user to get the wrong map file, in which case he/she should be presented with a proper error message.

At least for now c:geo is able to display all three formats with the NewMap implementation, whereas v3 implementation can only display v3 format (as expected). I don't know how frequently new file formats with breaking changes are to be expected, but for now we are on the safe side.

NewMap is enabled by default. If someone deliberately activates v3 implementation she/he knows what she/he is doing.

**Comment by Lineflyer** [comment]
I would like to stress this topic again.
IMHO there is no real need for V3 library anymore (unless I overlooked something).

Wouldn't it be better (for maintenance purposes, and due to people still accidentally using it and claiming missing features on support) to remove it?

**Comment by mirabilos** [comment]
Lars dixit:

>I would like to stress this topic again.
>IMHO there is no real need for V3 library anymore (unless I overlooked something).

The newer library performs really bad on some of the legacy
devices, especially it draws caches first and then, minutes
later, map tiles; the v3 library draws map tiles first most
of the time and doesn’t take that long.

Please keep it at least in the legacy release.

Thanks,
//mirabilos
-- 
15:39⎜«mika:#grml» mira|AO: "mit XFree86® wär’ das nicht passiert" - muhaha
15:48⎜<thkoehler:#grml> also warum machen die xorg Jungs eigentlich alles
kaputt? :)    15:49⎜<novoid:#grml> thkoehler: weil sie als Kinder nie den
gebauten Turm selber umschmeissen durften?	-- ~/.Xmodmap wonders…

**Comment by Lineflyer** [comment]
> Please keep it at least in the legacy release.

Sure, the legacy will be kept untouched when it comes to adding/removing features.

**Comment by moving-bits** [comment]
I can start working on it.

Without having dived into it yet, there are a couple of tasks to it that come to my mind:
- remove MF0.3 settings
- remove MF0.3 implementation for CGeoMap etc.
- remove MF0.3 code which is referenced even by NewMap
- (optional) remove GMv2 dependency on CGeoMap and remove CGeoMap completely
- (and maybe for some distant future: bring GMv2 and NewMap on top of the same base, but that's a different issue)

**Comment by bekuno** [comment]
I would do it in multiple steps.
At first in the next release notes as a deprecation warning that we will remove.
In the following release I would only remove the user visibility. So we could go back fast it it is necessary.
And only when we have no problems then we should remove the old code.

**Comment by moving-bits** [comment]
I agree with having a removal notice in upcoming release, but would merge the actual removal to master after branching. This gives us a whole release cycle for testing.

The NewMap code is untouched except the `MapgeneratorInternal` enum, which had been used from MF0.3 - I created a new enum class for it.

**Comment by fm-sys** [comment]
I wouldn't make a fuss in our release notice, that we removed/will remove this feature. Just a small note that it was outdated and it is fully replaced by the new map should be enough imho.

I would deactivate it hardcoded for our current new beta and remove it from master afterwards...

**Comment by moving-bits** [comment]
Ok, I've prepared a PR as intermediate step:
- remove settings for MF0.3
- querying the "use old MF map" switch always returns false

By this old Mapsforge map is hidden without actually removing its code.

**Comment by Lineflyer** [comment]
One side note: 
I just remembered some discussion some months ago:
A reason for keeping V3 would be, that WhereYouGo is not compatible with higher versions, thus requiring different map versions for both apps once we removed it.
BUT:  I still think removing from c:geo is OK...we should not use the minimum approach here but better also enable WhereYouGo to use newer mapsforge versions.

**Comment by moving-bits** [comment]
> A reason for keeping V3 would be, that WhereYouGo is not compatible with higher versions, thus requiring different map versions for both apps once we removed it.

We need to distinguish between the map library version (e.g. 0.3 is "old mapsforge", we are currently using 0.14) and the map file version (3 to 5). We are currently removing the old library version only. 

The current library version is still able read old map files, so you have the choice to only use v3 map files for both WhereYouGo and c:geo, or to use v4+ map files for c:geo and v3 map files for WhereYouGo, depending on personal preferences and available storage space.
