### ISSUE TITLE
[NUMBER] in offline maintenance log was +1 actual

### ISSUE THREAD

**Issue by githubber42** [cgeo/cgeo#7839]
**Describe the bug:**
Finds count is 3141. Logged maintenance. Log signature showed 3142.

**To Reproduce:**
1. Go to GC68BBM
2. Click on Offline log, maintenance; then offline log, log visit; type log and save/upload; 
3. Refresh cache; see log Number is +1 actual.

**Actual behavior/state after performing these steps:**
Count shows 3142 in log

**Expected behavior/state after performing these steps:**
Describe what you expected to happen instead.
Count should show 3141 in log.

**Version of c:geo used:**
You will find the c:geo version in c:geo Menu -> About c:geo

2019.09.12-NB-4eb49ed

**Is the problem reproducible:**
TBD

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**System information:**
```
--- System information ---
Device: Nexus 6 (shamu, google)
Android version: 9
Android build: lineage_shamu-userdebug 9 PQ3A.190801.002 71d6a9a87e
c:geo version: 2019.09.12-NB-4eb49ed
Google Play services: unavailable
Low power mode: active
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (11.2 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (11.2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (11.2 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (561.9 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
   opencaching.us: Logged in (Login OK)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---

```

**Additional context:**
e.g. Reference to other issues, projects, sources, etc.

**Comment by ithink314** [comment]
For what it's worth, the same was seen for a will attend log, and for a note log. Apparently, cgeo adds one to find count for more than just find logs.

**Comment by Lineflyer** [comment]
I would vote for not fixing it.

**Comment by fm-sys** [comment]
I had another look and saw that this issue is about self owned caches. Here the logtype should never be found (or something equivalent) so this could be fixed...

**Comment by Lineflyer** [comment]
Maybe it also for "Needs maintenance" log instead of only "Owner maintenance". The second case is more diffcult.

**Comment by fm-sys** [comment]
For this case a manual refresh of this value would be needed if the log text is already changed.
Otherwise it will work like this:
> A different idea for the "change logtype / auto inserted param" problem: If the log content still equals the auto inserted content, then it could be updated automatically on changing logtype. This should cover most use cases

**Comment by MagpieFourtyTwo** [comment]
> A different idea for the "change logtype / auto inserted param" problem: If the log content still equals the auto inserted content, then it could be updated automatically on changing logtype. This should cover most use cases

Hmm ... doubt it: 
- the [NUMBER] macro is IMHO (attention,. wild guess) mostly used to display the found number of this very cache
   (except perhaps one who writes "Have found xxx caches till today", but honestly, have never ever seen such a signature)
- DNF, WRITE_NOTE, WA, NM, OM, NA and stuff like this is no found at all,
   thus increasing [NUMBER] makes of course no sense at all.

   So far, so coincident.

- *BUT* as none of these is a found, *any* [NUMBER] will be wrong anyway ...

Thus I would go with @Lineflyer and leave it as it is, cause for the log types mentioned above the sig must be adjusted manually anyway.

BTW; In some DNFs for example I wrote s/th like "found no. 3456+0" ... perhaps a possibility ...?

**Comment by fm-sys** [comment]
> s/th like "found no. 3456+0" ... perhaps a possibility ...? Not perfect, of course, but at least better than nothing. ;)

I personally like this idea!

Another thing is, if we should really autoinsert the signature for other log types than found? The signature is in most cases designed for found logs, and users who really want to insert the signature also for other found types can still do it manually...

Maybe even set this behavior via an optional setting, if you think some users will not like this "step backwards"

**Comment by alan666notb** [comment]
The first thing I do when logging any type of log other than a 'Find' is to delete the signature.
But, unless it's my own cache, cgeo doesn't know I want to log a DNF until it's too late and the signature has been inserted.

**Comment by fm-sys** [comment]
> cgeo doesn't know I want to log a DNF until it's too late and the signature has been inserted.

We can automatically remove the signature when the logtype is changed and no text changes were made by the user...

**Comment by alan666notb** [comment]
> > cgeo doesn't know I want to log a DNF until it's too late and the signature has been inserted.
> 
> We can automatically remove the signature when the logtype is changed and no text changes were made by the user...

I think that would work well.

**Comment by eddiemuc** [comment]
There are some Feature requests requesting support for multiple log signatures e.g. #6197. Maybe this would help here as well?

**Comment by bekuno** [comment]
> We can automatically remove the signature when the logtype is changed and no text changes were made by the user...

This is too easy. 
We need at least a selection for which log type(s) the log should be displayed.

> There are some Feature requests requesting support for multiple log signatures e.g. #6197. Maybe this would help here as well?

This would be then the full solution.
The log type based switching of the log template is required in any case.

**Comment by MagpieFourtyTwo** [comment]
Multiple sigs is a good idea, but there are plenty of log types, so if you want to make it doing right in all scenarios, you must have one sig per type - means up to 10(!) sigs - and that's a lot of configuration effort for the user. Plus the need to maintain the stuff. And the urge to understand what's happening ...

Moreover I have even now, without thinking about it for too long, already a scenario in mind, where the automatism will fall for sure (writing and immediately uploading a note instead of a found log, to change it to a found later on, when previously made, but not yet uploaded founds have finally been logged - in order to have the correct found count with GC Little Helper on gc.com - doing so with e. g. FTFs or TB drops). So at least with WRITE_NOTE I would like to be in control ... And I'm pretty sure, there are more scenarios ...

And as an automatism, which does not work perfectly fine, or is too complicated to understand or maintain, i. e. leads to more work than it would be without it, is not a good automatism, I would just leave control to the user.

So I would let him decide, which sig he wants to insert in his current special case.

Thus I would suggest to stay with a default sig and perhaps additionally a set of alternate sigs, from which he can manually choose a different one, if necessary.

**Comment by MagpieFourtyTwo** [comment]
While the list of selectable sigs may even contain an entry like ``Remove sig`` ... or a dedicated button, if there's plenty of room for.
Position of a sig list button (like e. g. the one for the log type) could be between the buttons for ``Found it`` (log type) and ``Today`` (log date). These are currently wide enough to treat some space. ;)

With regard to replacement of the current sig: I would not just check for *any* text change done to the entire log window, but instead go through the user defined sigs, expand the used [] templates, and compare the result one by one against the corresponding number of chars at the end of the log text - and if found to be equal, replace this text by the selected one, otherwise just add the new one at the end, cause this one he will insert anyway ...

As for the sig list: I would make it dynamic, so the user can define as many of these as he "needs". And apart from the sig text, he should be able to enter a mnemonic title for each one, which should be displayed in the selection list.

As a different approach I could imagine to just (or even additionally) have user defined text templates, which can be inserted at cursor position, thus anywhere in a text window ... so they can e. g. even build their stuff manually, step by step ... and use this even for creating a context dependent signature.

**Comment by eddiemuc** [comment]
I find the discussion regarding signatures very valuable. I would actually love to have more flexibility there.
 I am not sure, however, whether this is the right issue to discuss this? It seems to me it has become it's own feature discussion by now.

**Comment by MagpieFourtyTwo** [comment]
As the [NUMBER] theme inevitably leads to signature handling anyway, we perhaps should just extend the topic ...?  E. g.:

``[NUMBER] in offline maintenance log was +1 actual - need of more flexible sig handling``

or even change it completely to

``More flexible sig handling``

?

**Comment by fm-sys** [comment]
From my point of view these two topics are totally unrelated. We are discussing:
- what should the number template display if the log type isn't found_it (or something equal)? The previous number, previous number followed by "+0" or maybe ever nothing? This problem will still exist if we are supporting multiple signatures and should therefore be discussed in this issue...
- the feature request of supporting multiple signatures. For this, #6197 is probably the better issue...

**Comment by MagpieFourtyTwo** [comment]
Yep, you're right. And thx for the link!  :)
