### ISSUE TITLE
Unwanted line break in list selection menu

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7905]
**Describe the bug:**
Depending on length of string (language) the menu options at the bottom of the list selection menu might get invisible as a line break occurs.

**To Reproduce:**
See these screenshots in language NL.
In portrait mode the items "Last selection" and "Cancel" are no longer shown. It can be access by scrolling but this is not clearly visible for the user and not nice to use:
![grafik](https://user-images.githubusercontent.com/949669/67266365-6193ac00-f4b0-11e9-8fab-909423fa2bef.png)
In landscape mode its OK on this device:
![grafik](https://user-images.githubusercontent.com/949669/67266429-86881f00-f4b0-11e9-978d-baf9690095e8.png)

**Actual behavior/state after performing these steps:**
Not all menu options are visible

**Expected behavior/state after performing these steps:**
All menu options should be initially visible without need to scroll

**Version of c:geo used:**
2019.09.08

**Is the problem reproducible:**
Yes (on the users device)

**System information:**
```
--- System information ---
Device: T07 (t07_ww, acer)
Android version: 6.0
Android build: Acer_AV0M0_T07_1.022.00_WW_GEN1
c:geo version: 2019.09.08
Google Play services: enabled - 19.2.75 (040306-269183835)
Low power mode: inactive
Compass capabilities: no
Rotation vector sensor: absent
Orientation sensor: absent
Magnetometer & Accelerometer sensor: absent
Direction sensor used: magnetometer & accelerometer
Hide own/found: false
HW acceleration: enabled (default state)
System language: nl_NL
System date format: dd-MM-yy
Debug mode active: no
System internal c:geo dir: /mnt/expand/52ee7083-c630-4e5f-98cb-57a51005d8e6/user/0/cgeo.geocaching (27,5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (2,2 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (2,2 GB free) external non-removable
Database: /mnt/expand/52ee7083-c630-4e5f-98cb-57a51005d8e6/user/0/cgeo.geocaching/databases/data (3,1 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Ingelogd) / PREMIUM
Geocaching.com date format: d-M-yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by moving-bits** [comment]
Root cause seems to lay in changes in the Android themeing - using all caps in button labels, generally putting more padding around some elements, which might add up to just a bit more space than was available. Then the buttons get stacked. But for some reason the button area has a fixed height, which leads to this issue. Have not found any doc mentioning a way to change this :-(

As far as I understand the Android docs, stack overflow articles etc., there is no way to make Android force the three buttons into one line, if the labels get too long. One can set a smaller padding, so that it fits in some more settings, but other attributes do not seem to be settable to a consistent state (gravity, relative width, ellipsize etc.), so cutting out the padding leads to an undesirable state as well. Maybe when switching to AndroidX libs?

So far no solution for this, and I'm not sure if there is one at all for the current setting we're in.

**Comment by moving-bits** [comment]
duplicate of #9879
closing this issue, as the other has more info meanwhile
