### ISSUE TITLE
Mapping large lists on NewMapOSM leads to ANR

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7923]
**Describe the bug:**
A user contacted us with this problem on support mail. Not yet retested, but sounds reasonable as the bug is not there, if he uses "Old Mapsforge V3"

**To Reproduce:**
- Use OSM or offline map
- Have a list with (in this case) approx. 1300 caches (same with 800 caches and slow with 560 caches)
- Map this list
- Map headline appears and map tries to load

**Actual behavior/state after performing these steps:**
c:geo does no longer respond and ANR error occurs

**Expected behavior/state after performing these steps:**
c:geo should work normal.
Its working with old mapsforge V3 as well as with Google maps

**Version of c:geo used:**
2019.10.05

**Is the problem reproducible:**
Yes

**Comment by Lineflyer** [comment]
PQs available on request (to me)

**Comment by moving-bits** [comment]
Probably device specific? Running out of memory?

Just tested with an S III neo (a really slow device according to today's standards) running Android 4.4 - worked fine with a list of ~1700 caches: Displaying the caches took about 7 seconds with NewMap and just a little less with Mapsforge v3, plus additional time for loading the map tiles.

**Comment by Lineflyer** [comment]
mmh...tested with mx (state of art) Galaxy S10 and I get an ANR with 1300 caches already.
@moving-bits Which type of map did you use?

**Comment by moving-bits** [comment]
> @moving-bits Which type of map did you use?

OSM online map in this case

**Comment by moving-bits** [comment]
Just tested on a S10 / Android 9 / offline OSM with Elevate.xml theme and a v5 Germany map:

- A local list of ~1.200 caches: caches are displayed in an instant, map tiles need app. 3 sec until the last one got displayed; viewport area covers app. 35 x 65 km.  
- A global list of ~6.700 caches: takes app. 15 sec until the blue "loading" marker is gone. (Most of the caches are displayed in an instant, only a few coming in the last 10+ secs.) Map is mostly empty, as a map of Germany is active and too small to show (caches are worldwide); hm, title reads "All / 0 caches" in this case (but the correct number in test case a - may this be due to the fact that case b is the "all caches" list?)

Repeating the same with online OSM:
- test case a: app. 9s
- test case b: app. 16s

Retesting with Google Maps:
- test case a: < 2s
- test case b: < 2s, but only one cache shown (wrong viewport for list, but no more zoom out possible) / restricting it to a map of Europe (including 6.600 of the 6.700 caches in this list): blue loading indicator runs for app. 8s

All times are "hand stopped" by counting, so there may be a huge probability for measurement errors :-)

**Comment by Lineflyer** [comment]
@moving-bits 
I think I found the problem while testing with different settings:
The problem appears as soon as you activate the notifications in Settings - Maps. Once activated they seem to drain a lot of performance leasing to ANRs on maps with many caches.

**Comment by moving-bits** [comment]
> @moving-bits
> I think I found the problem while testing with different settings:
> The problem appears as soon as you activate the notifications in Settings - Maps. Once activated they seem to drain a lot of performance leading to ANRs on maps with many caches.

@Lineflyer  Good catch, can reproduce now, at least with the > 6.000 caches list. Will try to look into it over the weekend.

**Comment by Lineflyer** [comment]
> @Lineflyer Good catch, can reproduce now, at least with the > 6.000 caches list. Will try to look into it over the weekend

Wow...I can reproduce a total block of the app already with 600-700 caches. Might be the difference are the amount of waypoints contained in those caches. My list contains only multis mostly with several waypoints each.

**Comment by moving-bits** [comment]
Root cause seems to be the call to `final Set<Waypoint> waypoints = filterWaypoints(baseOverlay.getCacheGeocodes(), true);` in `maps/mapsforge/v6/caches/WaypointsOverlay`, which takes a couple of seconds for each call when using a list of app. 1.600 caches.

@rsudev  Is there a more efficient way to calculate the min distance between any waypoint in current viewport and current position?

**Comment by moving-bits** [comment]
NewMap was fully blocked trying to calculate the min distance two times a second while needing a couple of seconds for each calculating, thus stacking up.

I've a WIP, mostly working (but not fully yet), with two changes:
- Found a different way to retrieve caches & waypoints for calculating their distances, which helps cutting down the time needed to a third or less or so.
- Also implemented a min timespan between the distance calculations to give NewMap a chance to paint anything at all.

There is one issue left with the signal not getting repeated every time. Will try to hunt this down and create a PR after that...
