### ISSUE TITLE
Update Google Play Developer API 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7942]
From Google Play Console:

Wir haben festgestellt, dass du in deiner App eine alte Version der Google Play Developer API verwendest. Ab dem 1. Dezember 2019 sind die Versionen 1 und 2 dieser API nicht mehr verfügbar. Bitte aktualisiere bis dahin auf Version 3. Dies steht nicht im Zusammenhang mit der Einstellung der AIDL/Billing Library. [Weitere Informationen](https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html) 

Translate:
We have seen, that your app uses an old version of the Google Play Developer API. From 01. December 2019 the versions 1 and 2 of this API are no longer available. Please update to version 3 until then. This is not related to the setting of AIDL/Billing Library.  [Further information](https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html) 

No idea, what that means, and what is the impact to us.

**Comment by moving-bits** [comment]
@rsudev @SammysHP @UniQP 
Can someone of you have a look at this, what it means to c:geo, and how to resolve it? Thanks.

**Comment by SammysHP** [comment]
I have no idea what it means.

**Comment by bekuno** [comment]
I could not find references in our code or in the dependencies, also nothing visible in the CI output.
Do we have something integrated in the CI only for the release process to google play?

In the referenced document is to reed:
_Warnings in Play Console
Google Play Console has been displaying warnings since mid-May if we detected that your app was still using version 1 and version 2 endpoints. The message is based on all calls to the API in the last seven days and is refreshed daily. If you see this message, it means calls to the Publishing API version 1 or 2 are referencing your app._
Did we got the message more then this one?

**Comment by Lineflyer** [comment]
No, this was the only warning I have seen ever.

**Comment by Lineflyer** [comment]
Regarding this strange issue:
IMHO we have not taken any action (as we were not able to find out in which way we use the Developer API). However I did neither notice any related problem nor did we receive any other warning. 

Lets close.
