### ISSUE TITLE
Remove "Force to english"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7991]
Since Android 8 the force function does not work anymore (at least on some devices, see #7053) and I consider this outdated anyway.

The background for implementing this was a lack of translated strings or wrongly translated strings, mkaing it hard to use the c:geo in the language defined by the system wide setting. Since we use Crowdin for a long time now, this problem is IMHO no longer existing in a relevant extent.

So I propose to remove this function completely.

**Comment by Lomanic** [comment]
I'm not a fan of this change as I prefer to have cgeo in English with Android in my native language to follow development here and properly submit bug reports.

**Comment by bekuno** [comment]
I am also in favour of solving the problem and thus preserving the language selection and extending it to a general language selection.

**Comment by jonas-koeritz** [comment]
Android does support multiple display languages at once now. This makes this feature obsolote for the purpose of fixing missing translations, the system will automatically find the most preferred available translation of a string for you.
This is also what might have broken this feature...

For the purpose of forcing the app to english for submitting bug reports etc. this feature is still useful and should be working. I would vote in favor of fixing it.

**Comment by jonas-koeritz** [comment]
> I am also in favour of solving the problem and thus preserving the language selection and extending it to a general language selection.

IMO general language selection is not a problem app developers should have to work on as the number of users using c:geo in a language that is not part of their preferred languages list or english should be insignificant.

**Comment by bekuno** [comment]
> Android does support multiple display languages at once now. This makes this feature obsolote for the purpose of fixing missing translations, the system will automatically find the most preferred available translation of a string for you.

I do not really understand what you mean. 
The Android standard is that **apps** _have to_ use the **system** language.
All other configuration is not easy to manage because there is no standard language change mechanism for **apps**. 

> This is also what might have broken this feature...

This is broken because the old used mechanism is no longer supported in the recent Android versions. We had to implement newer methods.
See https://gunhansancar.com/change-language-programmatically-in-android/

I hope this works, my tests based on other web documentation were not successful.

**Comment by jonas-koeritz** [comment]
I'm talking about the multiple locale support launched with Android 7. See https://developer.android.com/guide/topics/resources/multilingual-support for reference.
Users may select more than one locale, with one being their preffered and resources getting prioritized in the selected order.
![Screenshot_20200109-205801](https://user-images.githubusercontent.com/6485387/72100750-76e7dc00-3323-11ea-9d1b-d9e9c864f115.png)

**Comment by MagpieFourtyTwo** [comment]
Although already closed, #8709 shows that this issue is topical.

And apart from personal habits and preferences it would be extremely helpful for our work over here, too, to be able to switch the app to English, as we reference c:geo's topics, menu entries, buttons and stuff in English, too - but because of the lack of this feature we currently in fact are just guessing names and phrases ... thus adding an extra level of difficulty to communication ...

So, any chance, to get this setting working again?

**Comment by moving-bits** [comment]
From following the discussion above I don't think we can do anything about it, as newer Android versions seem to not support this any longer.

For testing and documentation you can use the following workaround:
- install / activate English as additional system language in Android
- when you want to test / document something in c:geo move English to first position, making it the preferred language. Everything in c:geo should now be in English.
- on finishing that work move your preferred system language back to top position

**Comment by MagpieFourtyTwo** [comment]
Ok - good hint. Just did so - and like it. Will most probably stay with English forever. ;)

So I would suggest to *replace* the "Force to English" option by either a text explaining this procedure or (if space may become an issue) a link to a help page which describes it.

While I would add a data consumption warning, cause doing this for the first time seems to download a lot of stuff. Don't really know how much, but it seems to be more the more apps you have installed ... just seen about ten apps, loading language packages ... but there was even more and the system stuff can not even be seen in the Wi-Fi consumption protocols.

**Comment by moving-bits** [comment]
Proposal:
- remove the menu entry for systems starting with Android 8 (as it does not work on those systems anyway)
- add a description on how to change the language to c:geo help, and link from c:geo settings to it

**Comment by fm-sys** [comment]
We could add an entry to directly launch into the system language settings. 

```
Intent i = new Intent(Settings.LOCALE_SETTINGS);
i.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
startActivity(viewIntent);
```

**Comment by MagpieFourtyTwo** [comment]
Sounds good.
Not really what one would expect from an NLS capable app, but since Android allows no other way, it's better than nothing.
And especially *way* better than a non-working menu entry ...  ;)
Perhaps there may additionally be a hint window prior to opening the intent, explaining ...
- why it has to be this way
- that some MB of download may happen in consequence
- that esp. on first usage of this setting it may even be "some" more MBs (esp. for the system apps)
- that finally a reboot will be required
- that after reboot *the whole system* will use the selected language.

**Comment by eddiemuc** [comment]
In theory there are possibilities to overwrite the system locale, but as far as I can google, there is no really "ground support". I found e.g. this:

```Java
@RequiresApi(api = 24)
public static void changeAppLanguage(Context context, Locale setLocale) {
    Resources resources = context.getApplicationContext().getResources();
    DisplayMetrics dm = resources.getDisplayMetrics();
    Configuration config = resources.getConfiguration();
    Locale locale = getLocaleByLanguage(setLocale);
    config.locale = locale;
    if (VERSION.SDK_INT >= 24) {
        LocaleList localeList = new LocaleList(new Locale[]{locale});
        LocaleList.setDefault(localeList);
        config.setLocales(localeList);
        context.getApplicationContext().createConfigurationContext(config);
        Locale.setDefault(locale);
    }
    resources.updateConfiguration(config, dm);
}
```

**Comment by MagpieFourtyTwo** [comment]
And this would apply for the calling app only?

**Comment by eddiemuc** [comment]
Yes. But as far as I see it this is some sort of hack, and I can't tell now how  much work it would be to integrate. I am unsure whether we want to take that "burden" onto us - there might be unwanted side effects, now or in the future.

**Comment by bekuno** [comment]
There are some description and libraries to help implementing this feature.
Some weeks ago a tried some but without success.
I think that I did not find the correct solution.
Here are some sources:
https://developer.android.com/guide/topics/resources/multilingual-support
https://github.com/zeugma-solutions/locale-helper-android
https://gunhansancar.com/change-language-programmatically-in-android/
https://github.com/YarikSOffice/lingver
https://developer.android.com/guide/topics/resources/multilingual-support

**Comment by moving-bits** [comment]
I found a way to change the locale - has to be done in the `onCreate` of several base activities - for a POC see #9532.
