### ISSUE TITLE
Codacy GitHub integration

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#8007]
May name still appears in the comments from Codacy. Can someone please remove and readd the Codacy to GitHub integration?

**Comment by Lineflyer** [comment]
Done. Lets see if it now posts with my name ;)

**Comment by Lineflyer** [comment]
Damn https://github.com/cgeo/cgeo/pull/8002#issuecomment-566018708

**Comment by Lineflyer** [comment]
I filed a support request to codacy.

Their help says, that for public repos the user should be "codacy-bot" but not the user, which has set it up.

**Comment by pstorch** [comment]
But it is not my name anymore 😉 
Thanks 👍

**Comment by Lineflyer** [comment]
:)

**Comment by Lineflyer** [comment]
For reference: https://support.codacy.com/hc/en-us/articles/207280219-GitHub-Integration

**Comment by Lineflyer** [comment]
Here is their answer:

Due to a change in the required permissions to create comment our Codacy-bot is not usable right now meaning that Codacy will create the comments using the user who created the integration in Codacy. While we are trying to fix this, we do not have yet an ETA to resume using the bot.

In the meanwhile, the best workaround for this would be to remove the current integration (Project's settings -> Integrations) and add it again using a generic user instead of your personal user. Afterward, the comments will be made using the generic user instead of your user. 

For me its ok, that my user is used until they fix it.

So lets close here for now.
