### ISSUE TITLE
Wrong log date on geocaching.su

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8017]
I recently stumbled upon a geocaching.su cache, which are rather rare outside Russia.

https://geocaching.su/?pn=101&cid=13790

I used the chance to find and log it, however some questions remain:
This issue:
1. I logged it in c:geo on 21. December 2019 however the website shows 21.12.2013 while in c:geo logbook it shows correct

Additonal questions:
2. I attached a picture but cannot find it with the log despite the upload succeded acc. to c:geo
3. The API does not seem to support sending answers for log questions. Should this be an open feature request or did I miss that option. The log however was accepted but only marked on the website with "No answer". I was able to send the answer later from the web page.

@okainov

**Comment by okainov** [comment]
Congrats with your first SU cache =)

> logged it in c:geo on 21. December 2019 however the website shows 21.12.2013 while in c:geo logbook it shows correct

Could you please attach screenshot? For me it seems correct
![image](https://user-images.githubusercontent.com/918446/71312230-b0b27a80-2428-11ea-9a3c-1aebf99936dd.png)

>2. I attached a picture but cannot find it with the log despite the upload succeded acc. to c:geo

It is a bit tricky, because on SU pictures are not part of the logs, but rather part of so called "photo gallery". You can find it here https://geocaching.su/showmemphotos.php?cid=13790 or by clicking "ФОТОАЛЬБОМ ТАЙНИКА" (literally "Photoalbum of the cache"). 

>3. The API does not seem to support sending answers for log questions. Should this be an open feature request or did I miss that option. The log however was accepted but only marked on the website with "No answer". I was able to send the answer later from the web page.

Open feature, see #7181, I still not sure that current "Log password" is good enough for this purpose...

**Comment by Lineflyer** [comment]
Thanks @okainov for your gratulation and fast answer.

Regarding 1. and this issue:
You can disregard it. For whatever reason the website translator I used from Russian to German changed the date (Google Chrome built-in translator).

Regarding 2.
Indeed a bit tricky, thanks for pointing me to it.

Regarding 3.
I missed to find that one as I forgot to label it with "Connector SU".
