### ISSUE TITLE
Migration of GoTo targets not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8067]
I just smoke tested a release candidate (build from now merged release branch).
Before upgrading from version 2019.12.30 I created 7 different GoTo targets and verified, that they have been stored.

After upgrading to the new RC/Beta however the waypoints of ZZ0 are empty.

**Comment by moving-bits** [comment]
Hm, that had worked during my tests. Will investigate...
Anyway, thanks for catching this!

**Comment by Lineflyer** [comment]
I did not manage to copy the DB-backup from the device. I entered 7 targets in the old menu mixed with N/E or S/W coordinates. Nothing special.

**Comment by moving-bits** [comment]
Sorry, but it's not ready for beta yet. I've stabilized migration itself (PR follows) and found an old bug in settings code (PR follows), but that does not seem to be the root cause of the problem.

Somehow, although the UDC ZZ0 and its waypoints are created and stored to database during migration, #8042 catches, for no apparent reason.

Example workflow:
- Migrate from schema version 77 to 78. (ZZ0 gets created, history waypoints migrated).
- Open "go to" => everything seems to be ok.
- Close c:geo and remove it from memory (via taskmanager).
- Restart c:geo. Open "go to" => ZZ0 waypoints are lost, c:geo tries to recreate UDC ZZ0.

Does anyone have an idea why this happens?

**Comment by moving-bits** [comment]
One idea: might this be due to the fact that the UDC ZZ0 is assigned only to a virtual list, but not a concrete one?

**Comment by Lineflyer** [comment]
This was fixed, but now we deal with other problems related. However this issue was not catched by autoclose.
