### ISSUE TITLE
Google maps open with worldmap

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8068]
There are two reports on support mail from nightly users:
Those users experience since some days, that the Google map opens in world view (max zoom out) when opening the map for a cache.

I was unable to reproduce up to now but I guess this is could be somehow related to https://github.com/cgeo/cgeo/pull/8046

**Comment by moving-bits** [comment]
> I was unable to reproduce up to now but I guess this is could be somehow related to #8046

Another anchor point may be #8034

**Comment by MagpieFourtyTwo** [comment]
Having this issue, too. Can be reproduced as follows:
- show cache on e. g. OSM map, using the compass rose in waypoint list
- switch to Google Satellite view (which then sometimes jumps to a desert, north east of Algeria)
- tap "Back" button to go back to the waypoint list
- use the compass rose again to show the cache on map (which is now Google Sat view)
- et voilà, in six out of ten tries Google Sat shows full zoom
Same happens with the Google Map.

AFAIR this behavior started with introduction of this odd "Automatic Map Rotation" - which is, at least for me, more annoying than helpful, cause it makes the map jump back to the current GPS position every second, no matter if you just moved the map manually ... thus I deactivated it as soon as I got aware of this option. YMMV.

**Comment by MagpieFourtyTwo** [comment]
> Another anchor point may be #8034

Don't think so, as in at least my test cases there were no additional waypoints. And even for an accidentally existing N00 E00 (i. e.) the map area shown would be too big. Moreover the cache's coordinate is still centered, which would not be the case, too, if there are additional waypoints, no matter if from listing or from a previously cached one.

**Comment by moving-bits** [comment]
After some debugging: If the viewport spanned by a cache including its waypoints has the same geopoints for `topLeft` and `bottomRight`, Google Maps zooms to world view. I a cache has no (or no valid) waypoints, the viewport is just a dot (`topLeft` == `bottomRight`), which triggers this error.

**Comment by moving-bits** [comment]
> AFAIR this behavior started with introduction of this odd "Automatic Map Rotation" - which is, at least for me, more annoying than helpful, cause it makes the map jump back to the current GPS position every second, no matter if you just moved the map manually ... 

Does this still happen? There has been a fix for resetting the position in autorotate mode, #8046.

**Comment by MagpieFourtyTwo** [comment]
[...map jumps back to current GPS position every second]
> Does this still happen? There has been a fix for resetting the position in autorotate mode, #8046.

To be honest, I haven't tested it any more, as the only gain of this "feature" seems to be increasing (my) confusion:  Esp. in the woods, where at least I use c:geo the most, Google Street and Sat view are hard to read anyway and it always takes a second or two to orientate on these maps. Esp. sorting out in which direction you're heading is already hard enough in a map pic with just a few anchor points - and if this already hard to read map additionally starts to move in an absolutely unpredictable way (esp. while standing [and trying to orientate] it either doesn't move at all or spins around like a whirligig), it makes it's usage completely impossible and renders this map useless.

So, you can't imagine, how glad I am, that this "feature" can easily be disabled. ;)

Nevertheless I've tried it again, and, yes, the jumping seems to be corrected. However, the whirligig is still there, at least once it has started to rotate at all, as the direction sometimes seems to be nailed - perhaps the signal of the compass or orientation sensor has been damped (a little bit to much) to avoid the a whirligig ...? And, no, it's not a problem of the sensors, as with an OSM map the position arrow moves and rotates perfectly fine.

**Comment by MagpieFourtyTwo** [comment]
Thanks for fixing this - great!

Nevertheless this "AutoZoom" (i. e. showing all defined waypoints of a cache) still renders the map view useless in some (but regrettably not really rare) cases, like e. g. in combination with c:geo's stubborn way of creating completely senseless waypoints from the personal note.

Example? Just create a personal note like this:

```
12-a-c=7	=> a+c=5	=> a=2 / c=3
36-b-d=26	=> b+d=10	=> b=2 / d=8

a.b.c.d@gmx.de
2.2.3.8@gmx.de (don't try, doesn't exist anyway ;) )

Final (doesn't exist, neither):
N48 51.234 E9 01.234
```
From this personal note two waypoints will be created automatically:
1. N48 51.234 E9 01.234 - which is perfectly fine
2. N02 12.000 E3 48.000 - which is *very* obviously *complete* rubbish

Usually you can suppress the automatic generating by putting a colon after the "N" like 
```
Calculation
N:48 51.234+17 E9 01.234-22
```
but in the example below even colons do not help ... :(

So, can we *please* invent a way of suppressing at least these completely senseless waypoints?
Perhaps it would be at least a quick'n dirty workaroud to suppress automatic generation when the extracted waypoint data gives a result which is more than let's say 10 km away from the base coordinates?  I guess, WPs more than 10 km away are rare, and if there is one, the user can create it using copy'n paste?

Which BTW at least for me would be the preferred way anyway, hence it could also be a solution to be able to switch this automatic extraction completely off by a config flag ...?

**Comment by MagpieFourtyTwo** [comment]
P.S.: Once upon a time it was possible to delete automatically generated but unwanted/senseless waypoints from the waypoint list and afterwards they did not re-appear. Sometimes they got re-created after editing the PN again, but most of the times they just stayed away.

But nowadays it's completely impossible to kill them, not even temporarily, they resurrect immediately after deletion.

**Comment by moving-bits** [comment]
@MagpieFourtyTwo   I've created a new issue regarding the suggested improvement for automatic waypoint creation from notes, see #8078

**Comment by MagpieFourtyTwo** [comment]
Thx a lot!  :)

**Comment by MagpieFourtyTwo** [comment]
Haven't found a (more) appropriate issue for my observations regarding this newly invented "Autozoom" thingy - but as they seem to be kind of connected to the stuff over here, I'll just add my observations of this weekend to this thread. If someone knows a better place. please let me know.

As far as I have understood, this "AutoZoom" feature should show all waypoints of a cache ... which seems to be a good idea, at least on first sight. But, most regretfully, on second and third, it is not.  :/

1. If you have solved a mystery (in PN, of course), which uses waypoints all over the world (which can not be deleted, as we all know), as e. g. one with questions about touristic attractions, or place spotting caches, or, to be concrete, stuff like https://coord.info/GC8J6MF ... finally just go out and try to spot the final. Rest assured: This "AutoZoom" feature will drive you crazy. Every single time, you just want to see the final and your way to it, the whole world will be mapped and you will have to zoom in and search for ages ... \*arrrgl\* And, no, using the compass rose of the "Final" waypoint itself is no alternative, as showing the map from this context, will give you no possibility to enable live view.

2. Moreover I don't see the need for this automatism at all, first as this function already existed anyway (just tap on the compass rose at the top of the waypoint list - et voila) and second: why should a click on "Show on map" (i. e. the compass rose on the listing page) show *all* waypoints in a context, where just one coordinate is shown?

3. Even by design I would call it a really bad idea to have two buttons in two different contextes leading to the very same result.

So, I would say it would be a really good idea, to simply remove this "Show all waypoints" AutoZoom stuff from them listing page's compass rose ... 

Thanks for reading - and even more for considering. ;)

**Comment by MagpieFourtyTwo** [comment]
Just an example of what I'm talking about: The screenshot shows the map that appears when I press the listing page's compass rose within the mystery I solved a few minutes ago. And, no, my GPS signal is perfectly fine and the coordinates of the cache are in fact 29.5 km away from my current position (as the bee flies). Now, go and have fun while approaching the final ... zoom, zooom, zooooom, little bee ... :/ :p

![Screenshot_20200120_223502_cgeo geocaching](https://user-images.githubusercontent.com/9889015/72759580-67477d80-3bd6-11ea-88a2-483ec735468c.jpg)

**Comment by Lineflyer** [comment]
That should be solved already and will be contained in next release. I assume you still use 2019.12.30 ?
Try out the beta version if you like.

**Comment by MagpieFourtyTwo** [comment]
Nop, I'm using 2020.01.20-NB-bbe2835 ...
