### ISSUE TITLE
Identify why c:geo is has heavy usage of OSM tiles

### ISSUE THREAD

**Issue by pnorman** [cgeo/cgeo#8149]
From https://github.com/openstreetmap/operations/issues/371#issuecomment-598016057

I'm a backend developer, not an app developer so my tools for investigation are limited.

For reference, the tile usage policy is at https://operations.osmfoundation.org/policies/tiles/

> From your table above I do now see, that we are under the top 5 of tile requests (as far as I understand your table), which I never would have expected...

The table doesn't include all requests, just those without a referer (non-browser requests)
Are you caching tiles? If not, this would inflate your traffic significantly.

Another culprit that I've seen is loading too big an area, but when I loaded the map and cut my network it didn't seem like it was loading too much.

**Comment by mmd-osm** [comment]
In genereal it might be interesting to find out what the main driver for traffic is: is it primarily a large user base where each user requests somewhat reasonable amounts of data - or - if there's a smallish group of power users causing most of the traffic. Maybe this is linked to certain use cases, where users potentially load too much data because they have a different expectation what the app is doing, etc.

**Comment by jakedot** [comment]
@mmd-osm:

> In genereal it might be interesting to find out what the main driver for
> traffic is: is it primarily a large user base where each user requests
> somewhat reasonable amounts of data - or - if there's a smallish group of
> power users causing most of the traffic. Maybe this is linked to certain
> use cases, where users potentially load too much data because they have a
> different expectation what the app is doing, etc.
>
Most power users of c:geo should become aware of the offline maps feature
before they start to use big loads. IIRC, the most load is generated when
very fine zooms are queried. For a geocaching app like c:geo, this is very
common as users want to zoom on a very narrow view around their target, and
so the large userbase of newish users who still use online maps might be a
reason.

>

**Comment by SammysHP** [comment]
Hi @pnorman,

Thanks for the heads-up! These are indeed high numbers, but if you consider the high number of c:geo users, this might not be so much anymore.

Here are some numbers from when we were in contact with the Thunderforest team for our OpenCycleMap usage.

2017-06-19 805,858
2017-06-18 1,674,606
2017-06-17 1,587,374
2017-06-16 1,022,505
2017-06-15 1,129,378
2017-06-14 942,148
2017-06-13 830,638
2017-06-12 774,302
2017-06-11 1,400,706
2017-06-10 1,422,128
2017-06-09 877,258
2017-06-08 821,478
2017-06-07 788,284
2017-06-06 815,728
2017-06-05 1,248,722 

Google Maps is default, followed by OpenStreetMap Carto. Next was OpenCycleMap (which we had to remove) and as you can see even at that place it caused lots of views. So 1,146,725 hits per day seems reasonable. Currently c:geo has 800,000 active installations. You can see (almost) live usage statistics here: https://www.cgeo.org/status

Overall I think these are real numbers caused by our app. :( The high load is something we kept in mind for the whole time and hoped that it was not that high compared to the overall tile usage. Although c:geo supports offline maps via Mapsforge, OSM Carto is easier to setup without preparation and provides more details than Google Maps in many regions. I use it myself when I'm on business trips and forgot to download offline maps of that area.

Not sure how we can proceed in this situation. Back then when we had the issues with Thunderforest we checked all tile providers and none had a pricing model that we could afford with our open-source donations.

**Comment by Lineflyer** [comment]
We should check if and how we make use of tile caching in c:geo.
AFAIR there was some discussion in the past, that it could be improved (or even needs to be implemented).

**Comment by jonas-koeritz** [comment]
We purge tile caches way too often. It might be possible to implement a better solution. Like two separate tile caches for online and offline tiles (so we don't need to purge the online tiles, just the offline ones when the theme changes).

**Comment by pnorman** [comment]
Using a filesystem cache is a very good idea. Besides reducing tile load, it'll reduce bandwidth which can significantly improve battery life.

**Comment by moving-bits** [comment]
If I'm not mistaken, tile caching in NewMap is calling the Mapsforge library,

```
// create a tile cache of suitable size. always initialize it based on the smallest tile size to expect (256 for online tiles)
tileCache = AndroidUtil.createTileCache(this, "mapcache", 256, 1f, this.mapView.getModel().frameBufferModel.getOverdrawFactor());
```

and that's using a file system cache already:

```
public static TileCache createExternalStorageTileCache(Context c,
    String id, int firstLevelSize, int tileSize, boolean persistent) {
    return createExternalStorageTileCache(c.getExternalCacheDir(), id, firstLevelSize, tileSize, persistent);
}
```

**Comment by jonas-koeritz** [comment]
c:geo is calling tileCache.purge() very often, effectively destroying its purpose. But removing the calls breaks the Mapsforge map...at least in my testing.

**Comment by moving-bits** [comment]
As an additional approach to reduce the load on OSM servers let's try to make using OSM offline maps easier to start with.

For a proposal and WIP see #8145.

**Comment by brabl2** [comment]
My user experience is, that c:geo purges the OSM tile cache every time I turn the screen of my phone (xperia xa1, android 8) OFF and ON. This is huge wasting of data in my eyes, it completely destroys the purpose of the cache. I think minority of people is using c:geo in 'always-screen-on' mode.

**Comment by moving-bits** [comment]
> My user experience is, that c:geo purges the OSM tile cache every time I turn OFF and ON the screen of my phone 

Looking at the code I can confirm this. Turning on the screen leads to `onStart()` being called, which does a `initializeLayers()`. This calls `switchTileLayer()`, which, you guess it, purges the `tileCache`.

Maybe some of the guys that originally created the `NewMap` code can remember why `initializeLayers()` is included in `onStart()` instead of e. g. `onCreate()`. @rsudev @pstorch ?

**Comment by Lineflyer** [comment]
As we recently dealt with improving the mapsforge library in the one or other way, I remembered this issue, which touches the topic of more efficiently using the tile cache.

Independently whether this can be analyzed and improved now or later: 
Should we open a dedicated issue for the tile cache improvement or alternatively rename this issue to focus on the tile cache?

**Comment by moving-bits** [comment]
I would propose:
- Describe in this issue the things we have done already to reduce to load on osm.org server, to round up this issue, and then close here.
- Open a separate issue regarding the tile cache issue.

**Comment by pnorman** [comment]
Since this issue was opened, cgeo is no longer top 5 apps by usage, typically in the mid-20s. This is about where I'd expect given cgeo's size.

A filesystem cache would improve things for your users, but #9953 tracks that.
