### ISSUE TITLE
Make filters be able to consider the current cache list's contents

### ISSUE THREAD

**Issue by jakedot** [cgeo/cgeo#8273]
Followup to #5257, #8210 and #8218:

We should extend filters and filter factories (maybe the only usecase, maybe not) to constrain the offered options to filter caches on, e.g.:

- filtering on countries should only offer countries contained in the caches of the current list view
- the above may have the edge case that in search results, etc not saved in the DB, none of the options produce any result!
- if a status (disabled, archived, ...) isn't contained in a list, it can be dropped from the filter selection
- etc.

I think that for sorting of lists only containing events, there is a similar specialization in another menu, maybe a place to start looking.

As @moving-bits suggested, this should probably be implemented by passing a list of Geocache objects to the code generating the filter. The country filter is currently offering all countries of saved caches only.

**Comment by moving-bits** [comment]
Good idea, nearly all filter lists could be reduced by this approach.
Although we would need to check for possible performance issues, when large lists would be scanned for dozens of filters on opening the filter menu.

**Comment by jakedot** [comment]
maybe we could split this up: for saved caches only, it could be done in the database, with just the gccodes, for search results we would need to query in memory I guess.

I already implemented a possible solution for the location in the `DataStore.getStoredLocationsForSet(Set<String> geocodes)` method. Similarly or a generalized approach could be implemented for other filters.

**Comment by jakedot** [comment]
it would need a complete overhaul I guess, we would need filter factories which just put the parent entry into the list and build up the sub entries on clicking the parent - if that's possible. And we need to give the list of current geocaches to the filter factory, so we can sort out unneeded filters. This probably won't be possible for all the different sorts of cache lists, because not all details might be loaded e.g. in search results, and then we might not even be able to offer the whole category aka factory for filtering (no idea if that's the case, but for the sake of an example let's assume that there is no country information in a online search result, then that filter doesn't apply as a whole).

**Comment by eddiemuc** [comment]
New filter now has a capacity going in this direction. You can currently see it in "type" filter and "status" filter: there are numbers behind the options showing how many caches in the list would fulfill criteria.

However, I took a shortcut as of now: these numbers are calculated from the cache list as it was shown before the filtering dialog is opened. This can lead to strange results. For example, asse you filtered a list to only show "Multi" caches. When you open now the filter dialog again, the numbers behind all other cache types will be 0 (because in the current list showing there are of course only Multi caches). How should this be handled?

Things become even more complex when it comes to combining multiple filters. Suppose you have a list with Multi and Traditional caches. Some of both types have a terrain rating of 3, some have not. Let's say you filtered this list for "Multis with terrain 3" and open the filter dialog again. Now, which count should be reflected in the "Traditional" count?
* Only the ones in current filtered view (would be 0)?
* Only traditionals with terrain 3?
* all traditionals in underlying offline list?

**Comment by eddiemuc** [comment]
As there is no feedback, I assume the current implementation is fine.
Can this be closed then?

**Comment by jakedot** [comment]
The original intent of this ticket was not to offer options the list being filtered doesn't have. I think the new system doesn't do this yet? Also, the filter case triggering this ticket was country / region filtering, which isn't implemented yet either.

**Comment by jakedot** [comment]
as for your question regarding which count should be shown, I would say the underlying list, as that would be the result of applying this filter alone - maybe add something like a summary of how many caches will be left after applying all current filters at the top?

It was my assumption that once switching to the new filter system, there would be no more filter stacking on top of each other by filtering the result list again, and you rather change the current filter by adding OR filters?

**Comment by eddiemuc** [comment]
> The original intent of this ticket was not to offer options the list being filtered doesn't have. I think the new system doesn't do this yet? Also, the filter case triggering this ticket was country / region filtering, which isn't implemented yet either.

I thought the country filter is discussed in #8761?

**Comment by moving-bits** [comment]
The original request is not only about country filter, but all filters. Don't know if that's feasible, though, technically and UX-wise.

**Comment by eddiemuc** [comment]
> The original request is not only about country filter, but all filters. Don't know if that's feasible, though, technically and UX-wise.

I guess a filter-by-filter-evaluation might be necessary. Also, depending on filter GUI it might not always be obvious how to "present" results (e.g. how should expected filter results be presented on the slider in a "terrain"-filter?)

**Comment by eddiemuc** [comment]
> as for your question regarding which count should be shown, I would say the underlying list, as that would be the result of applying this filter alone - maybe add something like a summary of how many caches will be left after applying all current filters at the top?

Hm I am currently not sure I understand the request correctly.
* First of all: is this request solely for showing offline cache lists, or is it meant as a general feature (to be applied e.g. also to "map-as-list" or the result of online searches)?
* For offline lists: should the presented items be based on an evaluation of all caches in the selected list, or on the subset of the list which is left over when applying other active filters as well (e.g. when a list is filtered by terrain=3, should the list of countries also include countries from caches in the list with terrain NOT equal to 3?)

> 
> It was my assumption that once switching to the new filter system, there would be no more filter stacking on top of each other by filtering the result list again, and you rather change the current filter by adding OR filters?

With new filter system you can "build up" your own filter out of a large number of criterias. You can also decide whether those criterias should be connected by OR or AND, and you can invert the result in total. Full flexibility to combine filters using AND/OR/NOT is possible by the underlying system, only limitation is the "understandability" of the filter building GUI to the end user.

**Comment by Lineflyer** [comment]
I think we cannot/ should not restrict the filter to only criteria matching the current list.
You can e.g. easily change to another list while the filter is active.

I think an on the fly preview of number of results would be good to allow users to see once the e.g. use a criteria which no cache on the current list fullfills.
Partly this is already existing (e.g. the number behind the cache types).

**Comment by eddiemuc** [comment]
Unfortunately the requirements are still not clear for me.

> I think an on the fly preview of number of results would be good to allow users to see once they e.g. use a criteria which no cache on the current list fullfills.

Do you mean a "total number of results", updated "on the fly" on every filter setting change? And no restriction to selectable choices?


> Partly this is already existing (e.g. the number behind the cache types).

This is not a "prediction" on filter results. It is simply the count of caches per type as present in the current (maybe filtered) list. These numbers tell you how many caches for each type are currently in the list. They don't tell you how many there will be when the new (changed) filter is applied. That would be much more complex to achieve.

(Try this out: take a list and filter it e.g. for Tradis and Multis. Then, open the filter again. You will see that the counts for all cache types except Tradi and Multi are Zero - because they were filtered out before)

**Comment by jakedot** [comment]
with the current state of the refactored filter system, I think this issue can be closed. It was originally intended for the old system and most filters have been improved beyond the scope this issue had.
