### ISSUE TITLE
Brouter route is lost for individual route when resuming map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8303]
2020.05.04-NB

To Reproduce (example case):
- Have brouter installed and configured
- Map a cache which has some waypoints with coordinates
- Use long tap to define a route between several of the waypoints
- Close map to return to cache details
- Map the cache again

Result:
The turn-by-turn route (coming from brouter) is replaced by direct lines between the waypoints

Expected:
Same route as before should be shown

Screenshots:
After defining route
![Screenshot_20200504-210453_cgeo](https://user-images.githubusercontent.com/949669/81003695-8d262480-8e4b-11ea-8544-588f76ed16a3.jpg)

After returning to map
![Screenshot_20200504-210509_cgeo](https://user-images.githubusercontent.com/949669/81003710-93b49c00-8e4b-11ea-8cb2-51e1f638dac4.jpg)

**Comment by moving-bits** [comment]
I've experienced the same, but infrequently so. Don't know the cause - I'm doing parceling and unparceling already. - Need to dug deeper.

**Comment by Lineflyer** [comment]
Its 100% reproducible for me.

**Comment by MagpieFourtyTwo** [comment]
Can reproduce, too. Guess the route is just not recalculated - thus same as in #8304

**Comment by moving-bits** [comment]
I've done a lot of debugging throughout the last days. Route is actually recalculated fine, even when "hopping" between the activities, in different scenarios. The problem is hidden somewhere deeper inside:

On some occurences - and I haven't found out yet what the trigger is - the calls to BRouter lead to a "not connected" message, upon which the standard "direct line" is returned as route calculation. This happens even then when I'm placing a `Routing.connect()` directly in front of route calculation... So it may be some timing issue.

I've been able to fix this for Google Maps by placing the route calculation in the `onMapReady` event - but I've found nothing comparable for `NewMap`.

A different approach could be a callback from BRouter, something like `onBRouterConnected` - have to figure out how this could be accomplished.
