### ISSUE TITLE
Individual route not updated on routing type change

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8304]
2020.05.04-NB

To Reproduce:
- Have brouter installed and configured
- Open live map with some waypoints/caches on it
- Select Menu - Routing - Walking
- Create individual route by long tapping some waypoints/caches
- The appropriate route routed as pedestrian is shown
- Select Menu - Routing - Driving

Result:
Route does not change (still on foot paths, etc. for walking)

Expected:
Route should be redrawn using the newly selected routing type

**Comment by Lineflyer** [comment]
Screenshot initial (correct):
![Screenshot_20200504-211225_cgeo](https://user-images.githubusercontent.com/949669/81004516-d0cd5e00-8e4c-11ea-95c3-4a5dae601ed2.jpg)

Screenshot after type change (wrong):
![Screenshot_20200504-211235_cgeo](https://user-images.githubusercontent.com/949669/81004552-daef5c80-8e4c-11ea-9153-3613138ea5e7.jpg)

Screenshot (Expectation after type change):
![Screenshot_20200504-211254_cgeo](https://user-images.githubusercontent.com/949669/81004573-e5115b00-8e4c-11ea-9191-a7156eb61312.jpg)

**Comment by MagpieFourtyTwo** [comment]
Ähem, I would call this a feature ... as this way you can have two different routing strategies for the navigation route and the individual route ...

As explanation here's my way of working with the individual route:
1. routing to a cache may fail, if position of cache is not reachable by current routing strategy (mostly "Car") - (which was BTW different some time ago: in former times, in this case a route to the nearest reachable point was calculated (and then a bee line for the last, non routeable part), so one could get at least as near to the coords as possible. Since about half a year or so in this case no route will be calculated at all)
2. as workaround I add a [P] on a road nearby (by long tap on map) and let BRouter route to this point (via the [P] waypoint popup's arrow symbol, to still be able to enable "Map Update" to see caches I'm passing by)
3. I switch routing strategy to "Walking", create an individual route from [P] to the cache
4. I switch routing strategy back to "Car"

This way I can happily follow the car's route to my guessed [P] *and* see the further walk way to the cache, thus can adapt the [P] on the fly.

And if I really want to change the routing strategy for an individual route, I just switch the routing strategy and then remove and add a point ...

**Comment by moving-bits** [comment]
I do understand the usefulness in this scenario, but I think the current inconsistency is rather confusing for most people which are not so technical savvy.

**Comment by MagpieFourtyTwo** [comment]
Comprehensible.

Although I am aware of c:geo's KISS aspiration, but nevertheless: What's about two different routing strategies - one for standard routing and one for individual routes? And, to KISS (for "standard users"), perhaps handle them as one until user decides via option to have two, to be able to set them differently? This option my e. g. enable additional menu entries in "Routing" ...?
