### ISSUE TITLE
Display a status flag "leaked/spoiled coordinates" for caches that are included in the "corrected-coords" database

### ISSUE THREAD

**Issue by MZCacheHunter** [cgeo/cgeo#8407]
**Is your feature request related to a problem?**
Unfortunately, some Dutch guy implemented a script and a database for the automated exchange of final coordinates for mystery, multi, letterbox and WIG type of caches.
Because of the highly automated implementation those spoiled coordinates can be easily accessed by every user of this script by a single click.
Source code can be inspected here:

_[redacted]_

This spoiling of the final coordinates is destructive to the motivation of owners to create creative and interesting caches. While it is Groundspeak's responsibility to guard the fun of the game and stamp out this unfair spoiling, we think it's at least to be made visible to the owners of the affected caches and to other users of c:geo as well.

**Describe the solution you'd like**
A status flag or icon "leaked/spoiled coordinates" to be displayed on the cache's page and on overview pages that this cache is an affected cache with spoiled coordinates.
This can easily be implemented as there is a simple webservice that results in a clear status. 
See below.

**Describe alternatives you've considered**
n/a

**Additional context**

_[redacted]_

**Comment by MZCacheHunter** [comment]
Oh, btw - this database contains about 380.000 final coordinates by now and is constantly growing. That's quite significant.
In my home area I could hardly find caches that weren't included already.

**Comment by SammysHP** [comment]
First: I have edited your post to remove all references to the service to not promote it more than necessary.

---

I'm strongly against implementing this. There are several reasons for this:

- It would require an additional network request for every cache, even if not opened directly but only stored, maybe even just shown in a search result or live map.
- This would practically DDoS the server because of the high number of requests.
- This flag is absolutely unnecessary for finding the cache.
- In most cases owners won't see the flag as their caches are hidden in c:geo.
- Why would other cachers be interested in this fact?
- This is not trivial to implement as it touches many parts of c:geo.

Published coordinates are nothing new in the geocaching community. They exist as long as geocaching exists. Personally I don't care about this. I go geocaching to have some fun, it's not a contest or spoiled just because other cachers have cheated.

**Comment by MZCacheHunter** [comment]
I agree with your point "This flag is absolutely unnecessary for finding the cache.". However, not with the argument "Why would other cachers be interested in this fact?".
And if you don't care as you stated, why not pulling this out into the open? Why editing my original post?

Sad, as an owner who put many efforts into interesting and challenging mysteries I'm quite disappointed.

Nevertheless, I consider this feature request closed now.

**Comment by bekuno** [comment]
@MZCacheHunter I understand that you are not amused about the situation.
But - such a marker is a problem in the opposite direction.
Every cacher will see this, and now many people have a direct information that there is a solution and they do not have to solve the mystery. 
Maybe a implementation to present this only for the cache owner on demand could be help them.
But we have no free man power to implement a such special solution. 
And the owner could use the problematic script by himself to check the situation.
