### ISSUE TITLE
Evaluate new location permission with targetSDK

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8458]
While investigating #8457 I noticed, that while asking the user for location permission, the behaviour is different starting with 2020.06.14-NB (so probably related to the change of `targetSDK` or `compileSDK`).

Previously the location permission dialog had three choices:
- Always allow
- Allow while app is being used
- Do not allow

Since 2020.06.14-NB the location permission provides less options:
- Allow while app is being used
- Do not allow

While I guess "Allow while app is being used" should be sufficient for c:geo I have no clue about the definition of "while being used" and what features might fail. This should be investigated.

**Comment by MagpieFourtyTwo** [comment]
Yep, saw this too, while trying to downgrade to yesterday's nightly, was a little bit astonished, but while "going back" (i. e. decreasing apk version numbers, in order to get a version which accepts any of my backups), the three choicer appeared again, so I dismissed it as an android glitch ...

**Comment by bekuno** [comment]
see https://developer.android.com/training/location/background
`If your app targets Android 10 (API level 29) or higher, also check for the ACCESS_BACKGROUND_LOCATION permission. Verify that your app has a feature that requires it.`

**Comment by MagpieFourtyTwo** [comment]
What about the option "Energy Save Mode"?

Having disabled this I would have expected that c:geo still keeps track of my position while running in background, in order to get a quicker fix, as described in the option ... but, ok, history line is not drawn, too, when screen is off ... hmm.

So this option is just to disable GPS while e. g. being in logs page ...?

What about WhereYouGo, when started by c:geo ... will WYG get it's own background location allowance although it's just a c:geo thread (if I understood this correctly)?

**Comment by moving-bits** [comment]
> Having disabled this I would have expected that c:geo still keeps track of my position while running in background resp. when screen is off, in order to get a quicker fix, as described in the option ... but, ok, history line is not drawn, too, when screen is off 

I think this is due to ever increasing restrictions newer Android versions imply on apps in terms of power consumption & running in the background.

IIRC it started with Android 8, that after switching off the screen the app is considered being in background and being called much less frequently for GPS updates etc. See issues about "c:geo stops talking when screen is off".

It's a separate issue with gaining location information in the background, as Android 11 adds an additional barrier because of privacy considerations. (Coming from Google - funny, eyh?)

> What about WhereYouGo, when started by c:geo ... will WYG get it's own background location allowance although it's just a c:geo thread (if I understood this correctly)?

WhereYouGo should have it's own set of permissions.
(BTW: When started from cache detail page, new in release 2020-06-14, it's started as a separate task.)

**Comment by MagpieFourtyTwo** [comment]
> BTW: When started from cache detail page, new in release 2020-06-14, it's started as a separate task

Which is BTW good stuff - although when starting the cartridge from c:geo's listing page, WYG will still launch in c:geo's context - and then #8368 strikes again. Don't really get why this behaves different compared to http links: clicking these guys in a listing invokes Firefox correctly (in an own task) ...?

**Comment by Lineflyer** [comment]
Field test and user experience has shown, that we seemingly do not need "Background location permission" for the current feature set of c:geo. 
This is, what this issue was about. Introducing background tasks, which then would need "Background location permission" is another task and covered by the relevant issue. Therefore closing here.
