### ISSUE TITLE
Limit file types in intents

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8467]
After installing the newer nightlies, my phone offeres "c:geo local file manager" for nearly every file type (e.g. also APK installs).

Sorry, that I did not have time yet to understand why this is needed after all.
What is the purpose of this? Can't we limit it to a certain file type? Is the the use case to open files with it, or just an unwanted side effect?

**Comment by moving-bits** [comment]
> After installing the newer nightlies, my phone offeres "c:geo local file manager" for nearly every file type (e.g. also APK installs).

This is a consequence of #8180 and its implementation with #8183.

> Sorry, that I did not have time yet to understand why this is needed after all.
> What is the purpose of this? 

Reasoning behind this is to ease onboarding for offline maps. For new users of c:geo it's very hard to understand how to find and to download offline map files, and how to integrate that into c:geo.
With the changes of #8183 you can tap on a link from within c:geo, select a map file for download, and after downloading has finished tap on the downloaded file to integrate it into c:geo.
The last step is the reason why c:geo is now offered more frequently for files.

> Can't we limit it to a certain file type? Is the the use case to open files with it, or just an unwanted side effect?

Android does not offer a way to limit this to certain file extensions, only to MIME types. But as "map" files do not have a specific MIME type, the servers do give us unspecific ones (and varying such), which I have to catch all to be able to get c:geo into the line if a user taps on a map file.

This is similar to what we already have for gwc / gwz / zip files, see here: https://github.com/cgeo/cgeo/issues/7663
And some discussion about it: https://github.com/cgeo/cgeo/issues/8180#issuecomment-611165666

OTOH the implementation with #8183 has the wanted side effect, that you can tap on any local map file to integrate it into c:geo.

And alternative and/or extension to this would be to implement #6072/#7529, but nobody has found a way and/or the time to do so yet.

**Comment by Lineflyer** [comment]
I have read those limitations for the intents and hope at least partly understood the problem here.
But anyhow from users perspective (and thinking of the amount of users hitting support mail with questions like "Why is this shown now for all different files") it not reasonable to implement it in that way then.

Additionally for me it does not work. If I click on a valid OSM *.map file, my phone reports "no app installed to open this file type".

My question would be, if it is really worth to have this map import click feature with these side effects? Can't we instead just fix / enhance the scanning for map files in the app?

Else I would suggest we need to handle all cases where files are selected which are not matching and provide appropriate user feedback (this would anyhow not be my favorite solution). Right now if I select to open e.g. a *.apk file the list selection dialog appears, I select a list and get "invalid GPX".

**Comment by MagpieFourtyTwo** [comment]
> Can't we instead just fix / enhance the scanning for map files in the app?

AFAIunderstood, scanning of (all) directories will most probably no longer be an option anyway, regarding the access limitations of the forthcoming constraint to use the Storage Access Framework.

If `GRANT_READ_ACCESS` will implicitly allow access to subdirs, too, it might be an option to ask for read access to e. g. `/external/Locus` and scan it's subdirs ... but this is not really different from asking for access to `/external/Locus/mapsVector` and `.../_themes` right from the start - or am I wrong ...?

**Comment by moving-bits** [comment]
> Else I would suggest we need to handle all cases where files are selected which are not matching and provide appropriate user feedback (this would anyhow not be my favorite solution). Right now if I select to open e.g. a *.apk file the list selection dialog appears, I select a list and get "invalid GPX".

Generally you already get such kind of feedback ("Error reading file or c:geo cannot handle this file type."). Problem with `.APK` files is that they are actually `.ZIP` files, and therefore get forwarded to the `GPXImporter`.

Hm, difficult. - Would be better to implement #6072/#7529, but I have no idea where (or better: how) to start with that.

**Comment by moving-bits** [comment]
> My question would be, if it is really worth to have this map import click feature with these side effects? Can't we instead just fix / enhance the scanning for map files in the app?

@Lineflyer 
So shall we remove the "tap on local/downloaded map file" part (revert this part of #8183) and just keep the download link in settings + adapt the text messages to let the user know to scan for map files after download has finished?

**Comment by Lineflyer** [comment]
Let me first try out this feature to see the handling. Will do it next days.

**Comment by Lineflyer** [comment]
I still think that there must be a possibility for better filtering. e.g. I do use Locus which is offered for a quite narrow set of files, although supporting the same file types in principle. Example: For *.zip I can select Locus as well as c:geo. For *.apk Locus does not appear but c:geo.

So I tend to suggest to drop this whole "c:geo local file manager" concept until we know how to do better.

**Comment by moving-bits** [comment]
> I still think that there must be a possibility for better filtering. 

We independently tried to implement such a thing for c:geo (maps) and WhereYouGo (cartridges), but both came to the same conclusion that there seems to be no way avoiding this side effect, as the servers do not send a meaningful MIME type with those file types, and Android does not allow filtering by extension. We had some discussion about this, but have not found a more narrow solution (eg. see: https://github.com/cgeo/cgeo/issues/8180#issuecomment-611165666).

> e.g. I do use Locus which is offered for a quite narrow set of files, although supporting the same file types in principle. Example: For *.zip I can select Locus as well as c:geo. For *.apk Locus does not appear but c:geo.

That is because `.zip` normally gets some meaningful MIME type applied by the web servers (like `application/zip`) whereas `.map` and `.cartridge` do not. To be able to automatically receive such files, I had to set c:geo to accept all binary files, which includes `.apk` among others.

Locus avoids this by having the websites offer specialized download links starting with `locus-actions:` instead of `https:` - Android can filter on that. That's what is suggested in #6072 for c:geo as well. I don't know if we have the power to make some website owners apply something similar for c:geo - Openandromaps might, mapsforge probably will not.

For now, the new "map downloader" is a first step towards this, but trying to reach a slightly different goal. Instead of addressing the technically savvy people, I try to make onboarding for the non-technical users easier. For details see #8610.

> So I tend to suggest to drop this whole "c:geo local file manager" concept until we know how to do better.

I have reverted those changes (and side effects) with #8617. Looking forward to introducing the new map downloader to c:geo...

**Comment by Lineflyer** [comment]
> Locus avoids this by having the websites offer specialized download links starting with locus-actions: instead of https: - Android can filter on that. That's what is suggested in #6072 for c:geo as well. I don't know if we have the power to make some website owners apply something similar for c:geo - Openandromaps might, mapsforge probably will not.

Maybe you misunderstood, what I was talking about:
- I have two files stored on my device: 1. cgeo.apk downloaded from our server  2. gpx.zip a downloaded pocket query
- I open my default File explorer (system app)
- I click on the *.apk, it offers the system installer and c:geo internal filemanager, I click on the *.zip it offers Locus and c:geo
My question: According to the MIME type theory, I would also expect Locus to be offered for opening the *.APK, but it does not (which is correct)

I have many more similar examples for other file types whereas certain installed apps are (correctly) offered, which are not offered for the types we actually want the c:geo file explorer to target on.

**Comment by moving-bits** [comment]
>       My question: According to the MIME type theory, I would also expect Locus to be offered for opening the *.APK, but it does not (which is correct)

I don't think so. The zip file probably gets associated a MIME type of `application/zip` which both Locus and c:geo filter for, whereas the apk file probably gets no specific MIME type (or some I don't know), so it does not get caught by Locus, but with the broader approach c:geo currently uses.

This gets even worse if you think of, that different web server send different MIME types, and there are many files having no MIME type generally being agreed on. Also I don't know which MIME type gets stored internally when you store the file using USB cable and file manager instead of the Android download manager.

But I would be very happy to be proven otherwise, as a more narrowed way of filtering would be very useful to c:geo. IIRC you are in contact with the owner/developer of Locus. Is there a chance that he shares how he filters files opened locally?

**Comment by Lineflyer** [comment]
@moving-bits As this was reverted for now, shall we close this issue?

**Comment by moving-bits** [comment]
Yes :-)

**Comment by Lineflyer** [comment]
BTW:
I did not contact the Locus author but a friend of mine just stated in a short conversation about this topic, that he used to use `android:pathPattern` to define the file extension for the intent.

**Comment by moving-bits** [comment]
Thanks for crosschecking. We do use `pathPattern` in our `AndroidManifest` already, although with some ugly workaround due to some limitation in the `pathPattern` implementation. I do not know the details anymore - implementing local file manager is quite some time ago ;-) - but I'm pretty sure that I had tested this with '.map' as well.

Probably is simply did not work for files save with the download manager (triggered by download in browser), as that one does not retain the file endings (which I've stumbled upon again while implementing the map downloader, but there's a workaround for this by temporarily storing the filename including extension in c:geo internally).

**Comment by Lineflyer** [comment]
Unless I did not look close enough into your change to the `AndroidManifest` it looks like you removed the `pathPattern` entries we used and also the implemented ugly workaround to catch also files/dirs with `.` in it.

**Comment by Lineflyer** [comment]
Lets just reopen to investigate better implementations for the future.

**Comment by moving-bits** [comment]
> Unless I did not look close enough into your change to the `AndroidManifest` it looks like you removed the `pathPattern` entries we used and also the implemented ugly workaround to catch also files/dirs with `.` in it.

yes, I needed to to also catch files in the `Download` dir which got their file extension removed.

As I mentioned: The new (not yet PR-ed) map downloader has a different approach avoiding this problem:
- Instead of using a browser to trigger the download (which isn't under our control after this)
- I now trigger the Android download manager internally, which gives me a "download reference id" and does a callback as soon as the download has finished.
- The file name still gets mangled with, extension removed etc., but I internally associate the "download reference id" with the filename and do a rename on download completion.

This solutions needs less manual user interaction and is more safe + has less side effects at the same time.

**Comment by Lineflyer** [comment]
OK, understood. Then lets give this approach a try after merging branches.

Still it would not be so bad also to have an intent catching *.map files on the system, to allow clicking on them to use c:geo to move or copy them to the defined map directory. I thought this was the original intention of your implementation (even only as a side effect).

**Comment by moving-bits** [comment]
Ok, I'll keep that in mind when implementing the map downloader after master has been branched to release.

**Comment by moving-bits** [comment]
Regarding this point:

> Still it would not be so bad also to have an intent catching *.map files on the system, to allow clicking on them to use c:geo to move or copy them to the defined map directory.

I'll open a new issue and close this one to allow for easier tracking.
