### ISSUE TITLE
Open links from cache listing in separate task

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8472]
Taken from https://github.com/cgeo/cgeo/issues/8458#issuecomment-646081436 by @MagpieFourtyTwo:

> BTW: When started from cache detail page, new in release 2020-06-14, it's started as a separate task

Which is BTW good stuff - although when starting the cartridge from c:geo's listing page, WYG will still launch in c:geo's context - and then #8368 strikes again. Don't really get why this behaves different compared to http links: clicking these guys in a listing invokes Firefox correctly (in an own task) ...?

**Comment by MagpieFourtyTwo** [comment]
Tested with some WIG links - seems to work. Thx!

**Comment by MagpieFourtyTwo** [comment]
BTW; Recognized some WIGs today, which have no WYG-Launch-Button in the overview page.
Examples: GC1MPVZ, GC356P2, GC5VEYE, GC461KF
First thought was, this may be because (most of) the listings are written in two languages, thus offering two cartridge links, and as c:geo then can't decide which to take, it just displays none at all ... possibly.
But the last one (GC461KF) contains just one cartridge link ... that's where I ran out of theories. ;)
Is there an reason for this or is this a bug?
And if it is a bug, is it still necessary, to correct it, as clicking links in the listing does work now ...?
And, to even go a step further: Could this button possibly be removed anyway ...?
