### ISSUE TITLE
Inform user about missing brouter file

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8562]
I just used Locus to plan a new cycling trip (in fact a rather long one from Düsseldorf to Berlin ;) ). I configured Locus to use the brouter engine to calculate the route.
While in the progress I reached an area not covered by the downloaded routing files in Brouter. Locus seems to recognize this fact and displays a message like "Offline routing files for this area are missing, do you want to download them now?". If the user accepts the brouter app will be opened.

I think, that could be a convenient feature for some users.

So the feature request is:
If brouter is installed but reports that the route cannot be calculated due to missing data (I assume it returns an appropriate status?) inform the user accordingly and ask if he wants to download them and switch to brouter app if the user accepts.

Regarding the implementation we need to think about when to ask and how often to ask. For Locus this action seems only to be triggered once per session and is anyway only active in route planning mode. For c:geo routes are drawn all the time on cache map....so it needs to be properly handled.

**Comment by MagpieFourtyTwo** [comment]
Really good idea, whereas I would go even further:  From my experience with about twenty BRouter installations (counting) plus certainly several hundred recommendations (at least felt ;) ) the routing feature seems to be pretty unknown to the "standard" users.  They in fact are not even aware that this IMO killer feature exists.  Can say so, cause most of them are kind of thrilled when they see c:geo routing on our devices. (BTW: Latest convinced one was really proud of his Garmin, as it was "even able to tell how long the way to walk is" ... until he saw what BRouter was able to do with his c:geo ... since then his Garmin stays in the drawer :) ).

So, why should the menu entries for `Routing` => `Walk`, `Bicycle` and `Car` not be *always* visible, and if the user selects one of these w/o already having BRouter installed, a message will tell him how to do it ...?  As download and installation is in fact a no brainer, this could easily be explained like in a cooking recipe ... just to give it a try:

- Download `BRouter` app from PlayStore
- start `BRouter`, select `Download Manager`, click `I know`
- select the region(s) you want to do routing in
- click `Download` ... wait a bit ... (download is not that big, but kind of slow,
   takes about 5 minutes per segment, so you may have your power supply handy ;) )
- finally just leave the app - and that's it!

This may possibly bring extra awareness to c:geo (as you can even use it as an offline GMaps alternative) - and moreover the effort put into the new map line config possibilities would have been even more worthwhile.  :)

**Comment by fm-sys** [comment]
We have meanwhile implemented BRouter as internal routing service coming with optional automated download of missing routing data. But shouldn't we at least show a toast that the required routing data is missing also for external brouter? Maybe even a snackbar with the action "open BRouter"?

![grafik](https://user-images.githubusercontent.com/64581222/115269564-bd89d000-a13b-11eb-8b8a-9a9e7c0c67d5.png)
https://material.io/components/snackbars

**Comment by moving-bits** [comment]
The actual code for Snackbar could be something like this:
```
Snackbar
    .make(activity.findViewById(android.R.id.content), "Missing routing data. Open BRouter to download?", Snackbar.LENGTH_LONG)
    .setAction("open", v -> {
        final Intent brouter = ProcessUtils.getLaunchIntent(activity.getString(R.string.package_brouter));
        if (brouter != null) {
            brouter.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            activity.startActivity(brouter);
        } else {
            ProcessUtils.openMarket(activity, activity.getString(R.string.package_brouter));
        }
    })
    .show();
```

BUT: How do I get the current Activity (GoogleMapActivity / NewMap) transported to / retrieved in `Routing.calculateRouting()`?


Thus for now I'll only display a toast, see #10435.
