### ISSUE TITLE
Show state "DNF Log" in cache lists and detail page

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8604]
**Is your feature request related to a problem?**
If you log a DNF and save it offline, the blue growny will be shown in cache lists and in the header of the cache's page.  Fine.
But as soon as you have logged your DNF online and (of course) deleted your offline log, the blue guy vanishes and from this point on, the cache (resp. his state) looks as if you've never ever dealt with it.

**Describe the solution you'd like**
Would like to see the DNF visualized in cache lists and header, as well as the DNF state (with date) in the state row, even if the DNF is "just" logged online (and until there will be a Found Log).

**Describe alternatives you've considered**
Currently I additionally save an offline log to keep track of the DNF, but this is pretty error-prone.

**Comment by Lineflyer** [comment]
See #3206 and #6614

**Comment by MagpieFourtyTwo** [comment]
These are pretty old ... about seven years since ... so any chance to get these (back) into development queue?

**Comment by Lineflyer** [comment]
@MagpieFourtyTwo They are in the queue as they are open.  Closing this issue is not meant rude, but I only want to avoid duplicates and concentrate on existing issues (which might already have some discussion in their history).
As often on opensource project we need to wait for someone interested and capable to tackle this feature requests.
