### ISSUE TITLE
Custom "Caches" (or perhaps just one more waypoint-icon)

### ISSUE THREAD

**Issue by Joe-Stoneage** [cgeo/cgeo#8605]
Hi there,

we love c:geo (and yes, we've contributed some bucks therefor), and we found out that there is more than geocaching what could nicely be done with c:geo. One thing is: we love to save "place of interest". At the moment, we have created a "dummy-cache" on gc.com, which is full of waypoints in c:geo. The problem is: we have no unique icon so if we open the map, we see theses waypoints with the usual icons among the waypoints of all other caches - hard to make out what it is: a real waypoint or one of our places of interest.
So, it would be verrrrrrrrrrry nice if one could create dummy-caches inside c:geo (so those created on gc.com may expire after one year and could automatically be deleted), and it would even be nicer if one could set some custom/more icons on waypoints for this caches.

Kind regards, InaUndJoe

**Comment by moving-bits** [comment]
Wish granted :-)

You can create user defined caches by long-tapping on the map at the desired coordinates.

You'll get a "Virtual cache" icon on brown background for each user defined cache (UDC). Otherwise it's similar to a regular cache in that you can create waypoints for a UDC.

(Creating UDC does not work in single cache map, as over there long-tapping on map creates new waypoints for that cache.)

You need to activate this functionality once using settings => map => behavior.

Have fun!

**Comment by Joe-Stoneage** [comment]
Man, this is that great! Thanx for your reply/help/grant :-)

Am Fr., 10. Juli 2020 um 14:15 Uhr schrieb moving-bits <
notifications@github.com>:
