### ISSUE TITLE
List "Internal caches" should be named "User Defined Caches"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8685]
Spin off from #8678 

As also the caches are named like that, we should name their default list (which is the default list where the "Go to" targets are saved to) accordingly "User defined caches"

**Comment by fm-sys** [comment]
Since I don't think that this change brings some real "advantages" I would suggest that it is ok to change only the list name in the strings. If the list already exists, it would not be renamed, but a renaming would probably irritate some users anyway. And an upgrade function that changes the list name on app upgrade would probably be a bit overkill... 
If this simplification is ok i will create a small PR

**Comment by Lineflyer** [comment]
Totally agree. Feel free to submit a PR for the string.
