### ISSUE TITLE
Allow a stored cache to belong to multiple lists

### ISSUE THREAD

**Issue by Bonemaro** [cgeo/cgeo#87]
I have a suggestion.  

My caches are organized in lists like To Do, Events, My Hides, etc.  Every time I import a new GPX file that contains a cache that is in one of my other lists, it pulls that cache out of the list and places it into the Stored list along with the others from that GPX.

Would it be possible to allow importing of a GPX without affecting other stored lists?

Thanks much!  :-D

**Comment by Christian-X** [comment]
I very much like the "label" or "tag" based approach.

I would take it even one step further, and export that label/tag to the personal note for platforms that support this (there is some hassle about updating this field, length limit). 

The benefit would be, that you could add the categories (like "#todo,#dtmatrix,#challengexy,#holiday") on any device and it will sync when updating the personal note. (I'm geocaching in a team with my partner, and we use the personal note extensively to share waypoints and everything).

**Comment by LeXeRLV** [comment]
Hello!
From my opinion it would be fantastic feature, not use only predefined
filter things and use two or three of hash tags or just have cache
different lists at the same time.

-
Ar cieņu,/С уважением,/Best regards,
Dmitry Livmanis
GSM: +371 26544554
E-mail: Dmitry.Livmanis@gmail.com

**Comment by kumy** [comment]
Someone at an event asked me about such a feature, "label" or "tag" would ideally fit his use case.

**Comment by Amorak** [comment]
+1 
For having the same cache in multiple lists.
Not having this makes c:geo rather unfriendly to use.

Consider this use case:
You have a list for the caches in the western Unite States that you need for your year/month placed calendar. There are only a very select few.
You create a PQ/list for caches along a route to an area you are visiting. The route has some of the caches from the year/month list. But, when you import the route, the year/month cashes are removed from that very exclusive list and mixed in with the hundreds of other caches in the route list. Rather frustrating.

I use c:geo exclusively and this is the only major complaint I have about the app.

Thanks,

DJL

**Comment by pstorch** [comment]
I was just curios about the oldest open issue. ;)
I also think it should be possible to put a cache in multiple lists. Same behaviour as Caches on Bookmarklists at geocaching.com.

**Comment by rsudev** [comment]
I think in principle we are all in the same book - but besides the effort required, also the details of how to present this to the user are IMO not final yet.

**Comment by pstorch** [comment]
I'm still curious about this issue and did some analysis.

## Predefined Lists
StoredList.TEMPORARY_LIST_ID = 0 "temporary"
StoredList.STANDARD_LIST_ID = 1 "Stored"
PseudoList.ALL_LIST_ID = 2 "All caches"
PseudoList.NEW_LIST_ID = 3 "Create new list"
PseudoList.HISTORY_LIST_ID = 4 "History"

As far as I can see only the STANDARD_LIST is the only predefined list used in the DB.

## Custom Lists
customListIdOffset = 10
First custom list has _id=1 in cg_lists and reason=11 in cg_caches.

## Current DB Schema
cg_caches.reason 
cg_lists._id

cg_lists._id +10 == cg_caches.reason

## Model Class
cgeo.geocaching.models.Geocache
private int listId = StoredList.TEMPORARY_LIST.id;

## Data Access Class
cgeo.geocaching.storage.DataStore

### Methods / Queries involved
**loadInViewport()**: selects cg_caches where reason >= StoredList.STANDARD_LIST_ID
**cleanIfNeeded()**: deletes cg_caches where reason = 0
**getLists()**: joins cg_lists._id with cg_caches.reason
```
          SELECT l._id as _id, l.title as title, COUNT(c._id) as count
            FROM cg_lists l LEFT OUTER JOIN cg_caches c
            ON l._id + customListIdOffset = c.reason

```
**MOVE_TO_STANDARD_LIST**: UPDATE cg_caches SET reason = StoredList.STANDARD_LIST_ID WHERE reason = ?
**MOVE_TO_LIST**: UPDATE cg_caches SET reason = ? WHERE geocode = ?
**COUNT_CACHES_ON_STANDARD_LIST**: SELECT count(_id) FROM cg_caches WHERE reason = StoredList.STANDARD_LIST_ID
**COUNT_ALL_CACHES**: SELECT count(_id) FROM cg_caches WHERE reason >= StoredList.STANDARD_LIST_ID
**LIST_ID_OF_GEOCODE**: SELECT reason FROM cg_caches WHERE geocode = ?
**LIST_ID_OF_GUID**: SELECT reason FROM cg_caches WHERE guid = ?
**COUNT_TYPE_ALL_LIST**: SELECT COUNT(_id) FROM cg_caches WHERE detailed = 1 AND type = ? AND reason > 0
**COUNT_ALL_TYPES_ALL_LIST**: SELECT COUNT(_id) FROM cg_caches WHERE detailed = 1 AND reason > 0
**COUNT_TYPE_LIST**: SELECT COUNT(_id) FROM cg_caches WHERE detailed = 1 AND type = ? AND reason = ?
**COUNT_ALL_TYPES_LIST**: SELECT COUNT(_id) FROM cg_caches WHERE detailed = 1 AND reason = ?
**QUERY_CACHE_DATA**: SELECT * FROM cg_caches
**dbCreateCaches** = create table cg_caches ... reason integer not null default 0, ...
**index**: create index if not exists in_caches_reason on cg_caches (reason)

**onUpgrade()**:
```
     if (oldVersion > 0) delete from cg_caches where reason = 0
     if (oldVersion < 64) update cg_caches set reason=1 where reason=2

```
**storeIntoDatabase()**: `values.put("reason", cache.getListId());`

**loadBatchOfStoredGeocodes()**: 
```
     select cg_caches where reason 
     if (listId != PseudoList.ALL_LIST.id)
          = Math.max(listId, 1)
     else
          >= StoredList.STANDARD_LIST_ID

```

##Comparison of DB Schemas for Tags
http://tagging.pui.ch/post/37027745720/tags-database-schemas 
http://tagging.pui.ch/post/37027746608/tagsystems-performance-tests

As far as I can see right now I would propose the Toxi variant with a third n:m mapping table:
http://tagging.pui.ch/post/37027745720/tags-database-schemas#toxi

All in all it would be quite some change.

**Comment by Lineflyer** [comment]
Thanks for your deep analysis of the situation.
From (my) users perspective and taking into account your statement

> All in all it would be quite some change.

I would simply suppose a middle way:
When importing a GPX or saving caches in general we could detect if caches are already stored on another list and ask the user how to proceed (keep it and maybe update it on the current list, move and update on the running process).

This will not fulfill the feature request but it would at least make the user aware, about what happens.
Most people contacting us on support do no neccessarily wish to have the cache on more than one list, but don't like it to get moved from the old to the new list in such cases.

**Comment by pstorch** [comment]
As mentioned in some previous comments, the offline_box in the CacheDetailActivity would need some redesign.

![2016-02-18 21 20 31](https://cloud.githubusercontent.com/assets/5598124/13159357/a45c5834-d691-11e5-8d58-70b44ffd04b7.png)
![2016-02-18 21 20 46](https://cloud.githubusercontent.com/assets/5598124/13159360/a8c798de-d691-11e5-895d-951cd84f48c3.png)

The offline state and the lists should be separated, because some buttons affect the Cache, some a specific List.
e.g.
The "Refresh" button works on the Cache independent of a List. 
The "Store" button works initially on the Cache with a Listselection afterwards. Could be kept visible to be able to store the Cache on several Lists.
The "Drop" button could work on the Cache and on a specific List. Either remove the Cache from a List or remove the Cache from all Lists and from the DB.
The "Move" button would work on a specific List. Maybe this button is superfluous.

An Idea could be to simplify the view with "+" and "-" buttons. "+" add the Cache to a List "-" removes it from a List. The last hit on "-" removes the Cache from the DB.

**Comment by pstorch** [comment]
> I would simply suppose a middle way:
> When importing a GPX or saving caches in general we could detect if caches are already stored on another list and ask the user how to proceed

Yes, this could be a first step.

**Comment by caigner** [comment]
As I just experienced the "_one list per cache_" problem, I am motivated to join the discussion.

Right now a geocache can be downloaded and stored on a list. And only on one list.

**My problem:**
If I have a list of "**the best caches in my area**" and a list of "**all the caches in my area**", then the second list will not be complete, because some of the caches will be on the first list. And if I create a third list with "**only caches with D>3 and T<5**' then probably some of the caches on the first list will change to the third list which would be (actually: is) annoying. At least two of my lists would not be complete.

Having lists suggests to the user that he can put caches on them. What else are lists for then, right? And the user (rightly so) assumes that caches stay where he puts them. But he also assumes, when he downloads a PQ that all the newly downloaded caches will end up on the (new) list which the user specifies.

**The solution:**
(I assume that you developers are all familiar with a m:n relationship. So I skip explaining that.) 
Would it be a great difficulty to have a **m:n** relationship between geocaches and lists?
With a m:n relationship a cache can be on more than one list and a list can have more than one caches. First problem solved.

Of course, as already mentioned above, we have to decide what to do, when the user wants to delete a cache. 

I suggest to give the user a notification that the cache is on more than one list and whether he wants to remove it only from the current list (=change the m:n table) or from all lists (=delete it completely). Second problem solved.

Please discuss!
Regards,
Christian

**Comment by SammysHP** [comment]
That's not the problem. The problem is the current implementation which must be changed.

**Comment by Mainah** [comment]
As a user, I would greatly appreciate the effort put into fixing this 4.5yr old issue.
My opinion would be to go with "label" or "tag" terminology and maybe eliminate "lists".

**Comment by caigner** [comment]
I think, for the majority of users (who are not very tech affine) the word "**list**" is more familiar from daily life.

**Comment by MrYaz** [comment]
I agree completely with @caigner regarding the use of the word "**list**" instead of "**tag**" or "**label**". I believe it is much more natural for the majority of users.

**Comment by samueltardieu** [comment]
Please open if you have new ideas about the UI for this "cache on multiple lists" feature, or about the use of tags vs. lists.

**Comment by caigner** [comment]
The UI is good as it is. For "cache on multiple lists" the list UI doesn't have to be changed. It is mainly a matter of how the database stores the relationships between caches and lists.
Just add the notifications I mentioned above (regarding deleting a cache from a list)  and you are done.
