### ISSUE TITLE
Wrong saved date in popup on map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8733]
I noticed this before and we even discussed this briefly in some older issue. AFAIR it is a side effect of merging of data retrieved from the live map to caches stored on the device and was introduced while implementing the new live map parsing:

- Have a cache stored e.g. 20 days ago
- Open the live map and scroll to the position of this cache icon
- Click to open the popup

Result:
- The popup text might state (depending on ?): "Saved a few minutes ago"
- Open details of this cache from popup
- The details show "Saved on the device 20 days ago"

Expected result:
- Live map parsing should not alter the save date shown in popup and also show "Saved on the device 20 days ago"

Obviously the save date shown in the popup does not overwrite the existing date information (as later when you open the cache it is stil the old dat) but somehow a transient value is shown here.

Tested with 2020.07.02 and also current master

**Comment by moving-bits** [comment]
Cache info of the stored cache is somewhat "hidden" by live map info - stored date is just one example for this. Hint / personal note is another example (which is the reason why with activated live map the "hint" button is not shown any longer even if there is hint/personal note data existing in the stored cache). And there may be more.

@jonas-koeritz 
You have been working in the live map area before. Do you have time to look into this?

**Comment by jonas-koeritz** [comment]
This really might be a problem in my code. AFAIK there is only an "updated" field, not a separate field for the time the cache has been stored on the device. The updated field gets set by my code IIRC, this would be wrong in that case.

**Comment by jonas-koeritz** [comment]
> This really might be a problem in my code. AFAIK there is only an "updated" field, not a separate field for the time the cache has been stored on the device. The updated field gets set by my code IIRC, this would be wrong in that case.

I've checked and it doesn't seem to be the case...I'm not setting the updated field :/

The Cache-Popup implementation is really convoluted and very abstract in my opinion. As it "only" serves a single purpose, maybe thes popup could be reworked to be more concise?

**Comment by eddiemuc** [comment]
As part of #11265 I kind of stumbled into this older issue.

I looked into code, and I think that the root culprit here is the ambivalent usage of the "updated" field of a geoache, which contains the timestamp where a cache was last updated. But this field is used in two different ways/interpretations:
* On one hand, it is used to determine when a cache was last stored. That's the main use case
* On the other hand, this field is also updated to current timestamp when for a stored cache new information is loaded from the service (specifically: when cache data is loaded into the Live map). This "update" is however not stored back to the DB later (and also not the maybe new information loaded from service)

The way "update" is used suggests it is meant as the last point this cache was stored to DB. So I suggest to simply remove the setting of this field to current timestamp in  Geocache.gatherMissingInformation. Any objections to this solution? (Note that this is in code since 2011)

I believe there is another issue to update specific cache fields in the DB too in the background when they are loaded via LiveMap. I would like to address this seperately to be honest, it would make this issue too big.

**Comment by eddiemuc** [comment]
Should be fixed with PR #11265
