### ISSUE TITLE
"Store waypoints to PN" does not save all (user maintained) WPs

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8747]
**Describe the bug:**
Predefined waypoints (i. e. added by cache owner when creating the listing) are not saved to personal note when clicking ``Store waypoints`` - which may be considered pretty logical (at first sight), because these are saved in the listing anyway ... one might think. But unfortunately(?) not all of these initially contain coordinates, which in these cases have to be added by the c:geo user ... and as esp. these are in fact the major part of "work" during e. g. a Multi, at least the changed ones should be stored to PN, too ...

BTW: I was a bit astonished, to find this button at the end of the PN - would have expected it at the waypoint list. Perhaps an additional button on the waypoint page would be helpful ...?

Moreover the WPs are saved in a kind of wasteful format like "@\<name> (\<type>) N xx° xx,xxx - E xxx° xx,xxx'". But as the length of the comment is still limited (on the server) and some more lengthy Multis sometimes really stretch this limit, I would prefer a more compact format (as well as I would highly prefer "Stage x" over "Station eines Multi-Caches x", but this is a different theme ;) ). In fact I guess, the \<type> will not be of any interest to John Average (esp. as there is no legend of types). And the "@" and at least the separating "-" (resp. dot) in-between the coordinate components are not really needed. As for me, I even strip the degree and minute signs, as well as the blanks and leading zeros (e. g. in "E 008") as these are not needed, too, but this is possibly a question of taste ... and the \<----> lines can be omitted, too, I would say ...

**Comment by Lineflyer** [comment]
> In fact I guess, the <type> will not be of any interest to John Average

While we can for sure try to shorten some info, we cannot ommit things like the <type> as it has to be possible to restore it completely from the PN (what is already implemented in addition with the recent PR). 

BTW:
I really appreciate your comprehensive and constructive feedback. As an improvement proposal: Please feel free to open an issue for each topic you describe. I would prefer to have several specific isssues for each problem or improvement step over a single issue with a collection of proposals/bugs. While this might sound strange at first, it is much easier to discuss and solve each of them in the later discussion without losing the overview.
So this issue is dedicated to "storing predefined but user modifided waypoints" (which is IMHO a valid issue) lets take the other topics (More compact format, UI representation of this function) into dedicated issues please. :)

**Comment by MagpieFourtyTwo** [comment]
>  as it has to be possible to restore it completely from the PN

Ok - wasn't aware of that. Good idea, BTW, as at least the waypoint description will not be exported to the GPX, AFAIK.

> open an issue for each topic 

Would have done it anyway - if it turns out to be reasonable. Talked about that with @moving-bits, too: If I do not immediately open a separate issue for every single thought I have (and, believe me, i have *plenty* of them ;) ), this is not meant to be offensive or because I'm lazy, but just to first get aware of what esp. the one already being in the context thinks about it.  If he agrees, I open an issue ... although most of the times you have been faster than me when it came to opening ...  ;)

This over here is a good example: If I would have opened an issue for stripping the data of WPs stored to PN down to min, this just would have been for trash, polluting the "real" issue list. But over here we can keep the circle small, thus not bothering the rest of the world.  :)

**Comment by eddiemuc** [comment]
Hello,
let me apologize in case I did or do not yet follow correctly the formal/informal conventions for working in the c:geo project, since I am quite new to it. I promise I will try to learn and become better.

@MagpieFourtyTwo your remarks regarding the waypoint format are all valid and I would happily discuss them. In short, I tried to find a compromise between a short format but maintaining existing waypoint functionality of the PN at the same time. (ok, the coordinate format could have been shortened easily, I overlooked that...). 

But I understand I understand this issue should focus on  "storing predefined but user modifided waypoint". 
The challenge with this is not so much writing info to the PN (that is, in fact, very easy), but to parse it out again in case you freshly load the cache from provider (not previously stored). This is because parsing algorithm from PN uses the waypoint coordinate as the "waypoint identifier" which for our case has two effects for predefined waypoints without coordinate:
* information for a predefined waypoint without a coordinate could not be parsed back to the correct waypoint from PN (how to find correct waypoint?)
* in case predefined waypoint was assigned a coordinate by user and info stored to PN, how to find the correct predefined waypoint when cache is freshly loaded from provider (because then the waypoint has no coordinate on it)?
Only solution option I could think of was using the waypoint NAME as identifier in that case, but this may clash with user-defined waypoints of the same name. So the be on the safe side we would have to add a flag to textual description whether waypoint is user-defined or not. This could work, but more clutter in PN. (Also I don't know whether predefined waypoint names are always unique)

**Comment by moving-bits** [comment]
> let me apologize in case I did or do not yet follow correctly the formal/informal conventions for working in the c:geo project, since I am quite new to it. I promise I will try to learn and become better.

No worries, I think @Lineflyer's comment was more into the direction of @MagpieFourtyTwo, but only to make it easier for everybody to track things, and to see, what is still open and what's closed.

But anyway, every feedback and every contribution is very welcomed, may it be testing, coding, documentation etc.

**Comment by MagpieFourtyTwo** [comment]
> information for a predefined waypoint without a coordinate could not be parsed back to the correct waypoint from PN (how to find correct waypoint?)

In fact, the names of WPs do not have to be unique. When creating a listing, you can even use the same name for all of them (sometimes they all are named "Virtual Stage", cause this is the default). BUT, there is a so called "Prefix", consisting of two letters, which is unique. And even if the CO enters the same Prefix in all his predefined WPs and ignores the inline warning, GS forces the Prefixes to uniqueness without further notice. And although I currently do not see this Prefix in c:geo, it can possibly be used to at least clearly identify the (correct) predefined WP.

BTW: In c:geo you can use the same name multiple times, too, so the name alone appears to be not really sufficient anyway. In fact, even the coordinates are not unique (e. g. S1 and Parking Lot are sometimes on the same coordinates). But, it at least sounds pretty unlikely (not to say "senseless") to me, to create two different WPs with the same name *and* same coordinates, so I would use a combination of these two (plus Prefix for predefined ones, if possible), to get it at least as unique as possible.

As for the difference between user- and predefined WPs ... it does not really matter, I would say.  Cause most of the times a predefined WP with editable coords will initially be empty anyway. BTW: Even with c:geo you can create WPs with empty coords. So if you have to restore a WP from PN and there already is a WP defined *with the same name but empty coords* - bingo.  ;) Just set the coords and everything is fine.  ;)

And if there already is a WP with the same name but different coord, I would just create a new WP with a suffix in it's name, which makes clear that it came with the import (resp. restore) from PN.

**Comment by rsudev** [comment]
Each WP has a unique 'geocode' composed out of the prefix and the trailer of the gc-code of its cache. We create a prefix for user-defined waypoints internally. So this geocode (or the prefix) should be the unique id linking the waypoint information together.
You might also want consider the (rare) case, that the coordinates of a predefined waypoint change on the website.

**Comment by eddiemuc** [comment]
> Each WP has a unique 'geocode' composed out of the prefix and the trailer of the gc-code of its cache. We create a prefix for user-defined waypoints internally. So this geocode (or the prefix) should be the unique id linking the waypoint information together.
> You might also want consider the (rare) case, that the coordinates of a predefined waypoint change on the website.

HI @rsudev, thanks, I didn't knew that. This is possible to use. 

With this new information, my proposal would be as follows:
* Storing user-defined waypoints as today using the pattern `@ <name> (<typeid>) <coordinate> "<user note>"` (user note only if it is not empty, as today)
* Storing predefined waypoints as follows: `@[<prefix>] <coordinate> "<user note>" (user noteonly if it is not empty)
(this is assuming we cannot edit names of predefined waypoints, but only coordinate and user note -> is this correct?)
* predefined waypoints without a coordinate use some special token instead of the coordinate, maybe Nxx xx.xxx Exx xx.xxx or something like that (parsing this correctly might be the hardest part of coding this issue :-))

That way we can differentiate user-defined waypoints from predefined waypoints in text (`@[xxx]`means predefined, only `@` means user-defined) and parsing can restore information directly.
Parsing for user-defined WPs would continue to use coordinate as its 'id' (like today), while predefined WPs use the `<prefix>`
Downside is that, as far as I know, the `<prefix>` is not used anywhere else in the GUI, so users might be puzzled to see this "strange id" in their PN. We could of course add the waypoint name to the predefined text too, but this will take up some chars of the PN.

@MagpieFourtyTwo, would this be an acceptable solution?

**Comment by Lineflyer** [comment]
@MagpieFourtyTwo 
Sorry for offtopic:
I could not find out any means to contact you via PN. Would you mind sending us a contact info to support@cgeo.org or to the mail adress associated with my github commits (gc [at] droescher.eu)? Nothing bad, just I want to ask something.

**Comment by MagpieFourtyTwo** [comment]
> users might be puzzled to see this "strange id" in their PN. 

I would try to keep confusion to a minimum - even the current notification already led to questions, as my "end user" over here ;) was completely clueless regarding the string format of the stored WPs. This will most probably not get better, if the notation differs from entry to entry ... ;)

While I still think, neither name nor coordinates are really appropriate identifiers, as they are not unique. Perhaps this "better ID", @moving-bits mentioned in #8759, can possibly be used? With such an ID both can probably be formatted the same?

Esp. as I don't see the need to distinguish between these two, anyway. Correct me if I'm mistaken, but in terms of important info, they are pretty the same, aren't they? Both have a name, coordinate, and a note (resp. two, as the predefined WPs have a second (user editable) one, but the not-editable does not need to be saved, anyway, IMHO). So saving this data seems to need no distinction.

And when it comes to restoring: With a unique ID (or at least a combination of name and coord, as same name *and* same coordinate is pretty pointless) this should be possible, too, without knowing if it's predefined or not - only difference (I see right now) is, that predefined WPs have some write protected fields ...

Or do I miss something (because of my half-knowledge ;) ).

BTW: Would be great if the button for ``Store Waypoints`` could go to the left side (or at least away from the way more frequently used other two), if possible, cause where it is right now, it sometimes gets pressed accidentally (as this weekend's experience showed), messing up the PN (if you don't want to have this list), or - even worse, if you previously saved the list - overwriting the changes made in the "real" WPs till you pressed the ``Store Waypoints`` last time.

Moreover it would be great if one can see, if the button press will store data from WP list to PN or vice versa (i. e. that on press data in "real" WPs will be overwritten by data from PN. as happened once to me).

**Comment by MagpieFourtyTwo** [comment]
Just seen: Uploading the
`<----->`
`...`
`</----->`
stuff to gc.com does not work correctly, as the end marker, i. e. the last line, will be stripped on it's way to the server.
My first assumption was, that gc.com possibly tries to remove or still interpretes stuff that looks like HTML tags (as it sometimes does in logs), but the end marker can be added manually and is then shown without problems.  So there's possibly s/th on c:geo's side, hindering the upload ...?

**Comment by Lineflyer** [comment]
> My first assumption was, that gc.com possibly tries to remove or still interpretes stuff that looks like HTML tags (as it sometimes does in logs), but the end marker can be added manually and is then shown without problems. So there's possibly s/th on c:geo's side, hindering the upload ...?

Strange...I tested it on some caches and did not have this problem.
However it needs to be investigated. Please always open dedicated issues for independent problems...like this one. Else we might miss a bug if we fix the original issue and close it.

**Comment by eddiemuc** [comment]
With #8817 , list will also contain listing waypoints where user edited either the coordinate (when it was empty before) or added a user note. In contrast to user-defined waypoints, these waypoints will be referenced via their prefix

**Comment by MagpieFourtyTwo** [comment]
Great! Thanks!

As for the tag lenghts: let's just wait and see how it works out. As the stored data is still human readable, thus editable, one can adapt it to personal needs anyway.
