### ISSUE TITLE
Integrate Adventure Lab Caches into c:geo

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#8792]
**Is your feature request related to a problem?**
For a while now Groundspeak has issued its Adventure Lab App, and over time it seems more and more Lab Caches are issued. It is frustrating for me to use a second App besides c:geo to get aware about those caches. 

**Describe the solution you'd like**
In a first step it would be nice if c:geo could Just Display available Lab Caches and their Stations on its maps, lists and search results - maybe only with a link to the Adventure Lab App.
If possible, in next step These Caches can be integrated in a deeper way.

**Describe alternatives you've considered**
Do nothing and accept to use different apps.

**Additional context**
I don't currently know how to Access the Adventure Lab information from outside the app and whether this is allowed or not. This might become a killer argument - but since c:geo never used the official GC API we should n't have a general problem with accessing another API (provided it is legally allowed of course)
![Screenshot_20200812-193411.jpg](https://user-images.githubusercontent.com/6909759/90047856-e61b1980-dcd2-11ea-8f13-a847fefaad90.jpg)

**Comment by Narrat** [comment]
Did they change API an such? Because last time this was asked it was considered impossible
https://github.com/cgeo/cgeo/issues/8433

**Comment by eddiemuc** [comment]
I die not see the previous issue, I guess I can close this one as a duplicate.
Just one question: the Groundspeak App needs to use some (undocumented) API too to communicate with the Server. Is there any way to "hijack" this?

**Comment by Lomanic** [comment]
It's fairly easy to reverse engineer a private API from an Android app: static analysis of the apk (decompiling it), HTTP requests interception with mitmproxy or similar or even code injection at runtime. Does the cgeo project want to go this route is the real question.

**Comment by SammysHP** [comment]
And we would need keys to use the API. It would be really hard to keep such a hack working over time.

**Comment by eddiemuc** [comment]
> It's fairly easy to reverse engineer a private API from an Android app: static analysis of the apk (decompiling it), HTTP requests interception with mitmproxy or similar or even code injection at runtime. Does the cgeo project want to go this route is the real question.

As far as I understand it, cgeo chose to go this way a long time ago by not using the official Groundspeak API for accessing geocaching.com and parsing HTML instead :-)

But missing key might indeed be a problem

**Comment by Lineflyer** [comment]
I would not recommend to start any new approach of parsing any pages or triggering an unoffical API. So my recommendation would be to refrain from trying to implement Adventure Labs into c:geo.
Besides that, displaying them would lead to the users expectation to advance it into full support, which is too much IMHO.

Maybe it changes sometime in the future if they might decide to make them available for third party via API and c:geo at some point in future might finally find a good agreement to use the API.

So I clearly vote for "no" here.

**Comment by Lomanic** [comment]
> It would be really hard to keep such a hack working over time

Looks simpler than scraping a regularly changing site to me: the API has to be stable because there are clients (apps) deployed on many phones, some may not upgrade the app.

> we would need keys to use the API

Not if cgeo uses an official key (that's one of the points of reverse engineering the app), but, again, I'm not sure this is the path the cgeo project wants to take.

**Comment by eddiemuc** [comment]
Is there a way to make some sort of "official request" from c:geo to Groundspeak whether integrating this into c:geo would be supported by them? (maybe by getting some sort of API doc or a Key). Or was this already done in the past?
@Lineflyer you usually know these things...

Without Groundspeak knowing and accepting such Integration into c:geo I wouldn't proceed.

**Comment by moving-bits** [comment]
I'm also voting for "no" here for the time being.

GC HQ's priority would be to switch c:geo to their official API for regular caching, which we have looked into some time ago, but found that API way too restricted - not technically, but in terms what basic members are allowed to do - limitations like "download full description of two caches per day" or "see only traditional and multi caches" (IIRC). Also this API is exclusive, meaning that if you use this API you are not allowed to use any different way of accessing their data. (Restrictions may have changed since the last time I had looked at them.) - Besides that, nobody of our team has found the time (or focus the available time) on implementing the API yet.

We had started some talking to GC HQ about their API about 1 1/2 - 2 years ago and they had signalled some willingness to discuss issues then, but without having the time to implement this, we have postponed further discussion.

At least at the time I'd looked into the API it did not include anything about Adventure Lab Caches (IIRC), but I'm pretty sure that using the official API (and only that) would be a prerequisite.

**Comment by SammysHP** [comment]
Aren't these Adventure Caches only for the official app?

**Comment by Lineflyer** [comment]
> Aren't these Adventure Caches only for the official app?

Even more limited. Its a dedicated app.

**Comment by bekuno** [comment]
As Lineflyer stated - Adventure Caches are `exclusively` useable with this app. There is no official api at all.
We should let them as is for now.

**Comment by SammysHP** [comment]
Just a quick heads up: Seems like it is not possible to create new ALC anymore and it is unsure how the service continues.

**Comment by moving-bits** [comment]
> Just a quick heads up: Seems like it is not possible to create new ALC anymore and it is unsure how the service continues.

Do you have some reference for this?

AFAIK, rollout of ALC has been done in waves in the past, by invitations sent by HQ to individual cache owners. (And to event hosts for mega and giga events.) Those invitations gave you a certain time frame in which you were able to create to ALC.

But maybe we'll get an update on this during Bryan's intro at the CacheCon this Saturday.

**Comment by bekuno** [comment]
I have an not yet activated Adventure credit.
I tried now: I can create a new adventure so far, there is no message to vorbid it, the "create" button is active.
(Did not hit them)

**Comment by SammysHP** [comment]
There was a short discussion at Geoclub that previous invitations stay valid for a few more weeks, but no new invitations were send for some time.

**Comment by Lineflyer** [comment]
> CacheCon this Saturday.

CacheCon? Enlighten me!

**Comment by moving-bits** [comment]
A virtual conference around geocaching, see https://geocachetalk.com/wwcc21/
Starting 10:00 am CST / 17:00 CET.
