### ISSUE TITLE
C:geo User Guide: convert to open wiki / enable documentation of waypoint parsing

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#8806]
**Is your feature request related to a problem?**
Currently a special account is needed to maintain the c:geo user guide. In this guide documentation of waypoint parsing is missing. Only a few people are currently able to maintain this.

**Describe the solution you'd like**
* short-term solution: create user guide edit account for @eddiemuc  :-)
* Long-term solution: convert user guide into an open wiki so community can maintain it

**Additional context**
This is a "reminder issue" as requested by @Lineflyer

**Comment by Lineflyer** [comment]
@eddiemuc  
I created an admin account for you on the system.
The system is hosted at https://cgeo.droescher.eu with reverse proxy running on https://manual.cgeo.org
If you have problems logging in via manual.cgeo.org try the original domain.

Feel free to take a look around and adapt whatever you like.

I do miss time to take care of the system after initially creating and completely filling it (aprox. 1 year ago).
Since then I only adapted a few things. Some ToDo and feature ideas (such as have a content backup on Github) are listed in the  [issues of our website repo](https://github.com/cgeo/cgeo.github.io/issues).

Feel also free to enable use self registration, but please report back changes for information or further discussion to this issue please.

**Comment by Lineflyer** [comment]
@eddiemuc You should have received a registration mail from the system.

**Comment by Lineflyer** [comment]
I noted some HowTo for translation here: https://cgeo.droescher.eu/en/translation
English language is master for the "Outdated warning". So you should always translate/change English first.

**Comment by Lineflyer** [comment]
BTW: Lets continue in this issue please: https://github.com/cgeo/cgeo.github.io/issues/226

**Comment by eddiemuc** [comment]
> @eddiemuc You should have received a registration mail from the system.

I did receive it, thanks a lot
