### ISSUE TITLE
TextUtilsTest uses unchecked or unsafe operations

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8833]
since PR #8608 this problem occures at our CI:

~~~
> Task :main:compileBasicDebugAndroidTestJavaWithJavac
Note: /home/jenkins/slave/workspace/cgeo pull request/tests/src-android/cgeo/geocaching/utils/TextUtilsTest.java uses unchecked or unsafe operations.
~~~

@eddiemuc please have a look at this problem.

**Comment by bekuno** [comment]
see assertThatListIsEqual

Possible heap pollution from parameterized vararg type 
 Inspection info: Reports all methods with variable arity which can be annotated as @SafeVarargs. 
  @SafeVarargs annotation suppresses unchecked warnings about parameterized array creation at call sites.

**Comment by eddiemuc** [comment]
Fixed.

@bekuno: Is there something like a checklist what to perform locally before creating PR so one is sure that CI rules are fulfilled? I currently do:
* Execute local Unit tests
* Execute instrumented Android-Tests
* Execute Checkstyle with c:geo-settings

Really checking Android Studio warnings is nearly impossible in Android-instrumented tests because screen is polluted with "unused method" and "test method should not be static" warnings..

Anything else necessary?

**Comment by bekuno** [comment]
@eddiemuc 
In AS I use the c:geo tests and the AS lint results.
In the commit dialog is a area "before Commit". There I checked the points "performe Code analyses".
When this shows results then I control these points.
If necessary or something unclear the I call gradlew in the AS terminal (without parameters it shows the cgeoHelp task).
Don´t forget to configure java, e.g. `set JAVA_HOME=D:\Program Files\Android\Android Studio\jre`.

**Comment by moving-bits** [comment]
Since from within AS I tend to forget to call CheckStyle for every changed file, I have integrated CheckStyle as git hook into the commit routine.

(Or at least I had this working, until some changes from either AS 4.0 or the latest update for the programming language I use for integration have crashed this. => Need to investigate...)

**Comment by eddiemuc** [comment]
> In AS I use the c:geo tests and the AS lint results.

@bekuno where in AS can I find the lint results? (or maybe filter on them, as many code files fi1les are overcrowded with warning messages from my AS default settings so it's hard for me to find the really useful things) Sorry if this is a dumb question...

**Comment by bekuno** [comment]
> @bekuno where in AS can I find the lint results? (or maybe filter on them, as many code files fi1les are overcrowded with warning messages from my AS default settings so it's hard for me to find the really useful things) Sorry if this is a dumb question...

@eddiemuc Please check in the settings that "Editor -> Inspections" uses the project profile. There you can also change the settings. You have results as marker on the editor right hand side. And you can run "Analyze -> Inspect code".
