### ISSUE TITLE
New Developer Cheat Sheet

### ISSUE THREAD

**Issue by baiti** [cgeo/cgeo#8873]
This issue is used to collaboratively work on a "cheat sheet" for new developers  on how to accomplish some basic procedural workflows on github, specifically as it is related to c'geo development

The cheat sheet will be factored into the already existing Wiki structure.

**Comment by Narrat** [comment]
One suggestion from my side is to keep git and github separatly documented. The latter is a service and as such could be replaced (gitea, gitlab are other players). Which behave differently and can alter workflows.
Just mentioning it, because I had some run-ins where the way github does things influenced the actual usage of git which caused problems elsewhere.

**Comment by bekuno** [comment]
> One suggestion from my side is to keep git and github separatly documented.

c:geo code is at github.
So I would say we can write all in one document. But we have differentiate the work locally (git) and web (github).

**Comment by Narrat** [comment]
Yes, it is. And it is extremely unlikely for it to move, but it isn't impossible. Therefore I tried to cover such a case.
But the separation of those two is fine enough.

**Comment by baiti** [comment]
it was indeed a major source of confusion for me over the last few days to understand what runs where. What added to the confuscion was that on the client side there wasn't only the git on the commandline but in addition what has been integrated into the Android Studio under "VCS".

My current way of doing things would be using the git client on the commandline almost exclusively, perhaps with the exception of resosolving conflicts. Android Studio seems to do a good job in that respect.

**Comment by baiti** [comment]
What I'm struggling more at this time is that the Wiki source files don't seem to be part of what I fork and clone. So I don't know how to add new content / new pages.

**Comment by Lineflyer** [comment]
The Wiki is a Github feature and not contained in a repo. 
AFAIR it should be editable to anyone with a Github account, but I might be wrong.

**Comment by Lineflyer** [comment]
Addon:
I was wrong. Default settings restricts it to collaborators of the repo. 
I just enabled access for all Github users. If we have misuse we need to find another solution. Anyway there should not be any permanante damage in this case as we can recover earlier versions.

**Comment by baiti** [comment]
> The Wiki is a Github feature and not contained in a repo.
> AFAIR it should be editable to anyone with a Github account, but I might be wrong.

I tried to edit the README.md ... which is sort of the starting base to link into the Wiki pages. README.md is indeed in the repo. let me try with regular Wiki pages, we can always put in links into README.md later.

**Comment by bekuno** [comment]
There is an "clone the wiki" below the table of contents.

**Comment by baiti** [comment]
Have added a page. Check it out to see if it is appropriately scoped:

https://github.com/cgeo/cgeo/wiki/Getting-the-Source

I wanted to link to this page from within the README.md where that reads:

Get the source
Fork the project source code, make changes to your clone and create a pull request afterwards.

**Comment by moving-bits** [comment]
Before diving too deep into this please have a look at the existing wiki pages first, especially the one @eddiemuc had linked to - there is already much content available. We can use those as a base and see if we need to extend or split up things.

**Comment by bekuno** [comment]
I beautified the site a bit.
Please for now do not change the readme.
As moving bit said - we should consolidate the infos at first.

**Comment by Narrat** [comment]
Is there a policy in place where everyone uses its own fork for changes? Just asking because Members could theoretically push branches to this repo.

As for infos that should be covered.. my suggestions:
- Clone repos
- Add/remove remotes
- Fetch sources
- Merge changes
- Branches
  - Create/Delete branches (`git branch -c master <branchname>` and `git branch -d/-D`)
  - Working with those (`git checkout/switch`)
  - Follow upstream main branch/es (`git status` will show if there is a possible conflict or out of date)
  - keep those up to date (`git rebase/merge/pull`)
  - resolve conflicts (manually, `git mergetool` and additional methods (AS))
  - Something went wrong:
    - Interactive rebase
    - Cherry-pick
    - Reset (soft and hard reset)
- File handling
  - e.g. restoring an indexed file which got deleted or discard changes (`git checkout/restore`)
- Push
- Using the webservice (Github)
  - Creating PRs
- Additional stuff:
  - Hooks (automating stuff, checking if basic stuff is done right and such)

Some of the above is covered as I could read on the older existing wiki page. Although there is stuff that could be rewritten/enhanced.

**Comment by moving-bits** [comment]
> Is there a policy in place where everyone uses its own fork for changes? Just asking because Members could theoretically push branches to this repo.

Best practice when working on c:geo source code & resources is to use your own fork, create a feature branch over there, and prepare a PR from that.

Although technically core team members have the credentials to push directly to the c:geo repo we rarely do this (except for updating the changelog, merging branches or resolving hiccups).

**Comment by Narrat** [comment]
> Best practice when working on c:geo source code & resources is to use your own fork, create a feature branch over there, and prepare a PR from that.
> 

Sure, no other way around if the contributor isn't a member.

> Although technically core team members have the credentials to push directly to the c:geo repo we rarely do this (except for updating the changelog, merging branches or resolving hiccups).

But reading this I'm not sure if we are on the same page?
Direct pushing to the main branches (in this case master, release and legacy) is surely not the best thing to do if there are more than one contributors. But feature branches and the creation of PRs would still be the same. But maybe in the past it was the best  way to avoid the cluttering of the main repo with countless WIP branches?

And to make sure: I'm just asking out of curiosity. In no way I want to suggest to change the current setup. But this had me wondering for quite a while and I'm kinda interested in the various different setups projects use to coordinate their work. Grew historically is therefore just fine for an answer :D

**Comment by bekuno** [comment]
@Narrat 
Every developer has (normally) to use his own fork to prepare PR.
Maybe in the past there were the situation that such "quick and dirty" process was used. (e.g. as mistake, for quick reation without a development environment, ...). You are right, at least the used branches should be deleted after closing a PR.
But this was not more in the last years.
And you should note, that the team member change over the years.

**Comment by Narrat** [comment]
> And you should note, that the team member change over the years.

Right, this is a very good point.

**Comment by eddiemuc** [comment]
I integrated my share into https://github.com/cgeo/cgeo/wiki/Working-on-c:geo-for-git-beginners

**Comment by baiti** [comment]
veeeeeeery good! You have a good touch at how things work. This helps a lot. I will review it in more thoroughly and get back to you with feedback.

This can completely replace the page I recently created and linked into the TOC

**Comment by eddiemuc** [comment]
> veeeeeeery good! You have a good touch at how things work. This helps a lot. 

Thanks a lot for the nice feedback. The page was already there before me, so credit also goes to all the people creating and enhancing it in the past.

**Comment by UniQP** [comment]
I did some cleanups and fixed the link on the wiki start page.

**Comment by Narrat** [comment]
Some notes regarding the current state (no edits from me, as I'm only involved with c:geo as a normal user).

To avoid switching to the branch you want to use a base for your work, you can use `git branch -c master my_branch_name` followed by the `switch`
`pull` = `fetch` + `merge` or if the rebase option is used `fetch` + `rebase`. Just mentioning this as I read e.g. one step using fetch and the following step involves `pull` again, whereas `merge/rebase` would suffice. 
If you want to rebase your current checked out feature branch with the current upstream master you could also do `rebase upstream/master` (Mentioning this, because the same is used in the part about resolving conflicts). IMO "Refreshing the local environment" should include the rebase part (as it almost does). The paragraph about "Rebasing a branch and handling merge conflicts" should only be about resolving said conflicts. Which should include Way 3: `git mergetool`. Best inserted before the manual way described as Way 2.
Personally I avoid the use of `commit -a`. Instead the somewhat longer, but safer route of `add` + `commit`. But that really depends on personal preference. That said I would switch around the three points in `commit your changes locally`: First explain the formal way via `add` and at last mention the partial shortcut with `commit -a`. And in general if using options that are not immediately clear: explain said option or list short and long option.
If working with branches und pushing those to another repo, `fetch --prune` and `branch --merged` can be handy to keep track which branches can be removed or got removed.

**Comment by Lineflyer** [comment]
Can this be closed or is there some ongoing work (on this repo or Wiki) behind that?

**Comment by moving-bits** [comment]
> Can this be closed or is there some ongoing work (on this repo or Wiki) behind that?

AFAICS this can be closed. If there's need for additional discussion we should open a separate (discussion) issue.
