### ISSUE TITLE
Open geochecker attempts to open locus not website 

### ISSUE THREAD

**Issue by bluepanther51** [cgeo/cgeo#8891]
The link on the cache page and the menu option, both open locum map, not the che ker on geocaching.com.

**Comment by fm-sys** [comment]
@bluepanther51 Could you please show us an example and explain which steps you did to reproduce this (or is it at all reproducible)?

**Comment by bluepanther51** [comment]
For cache GC8XEQC when I click on the link

geocaching.com coordinate checker available via browser
<https://coord.info/GC8XEQC>. It attempts to open locus not the link.
Trying the link under the 3 dots open geocheckerndoesnthe same.

May be a config error, but it was working on previous release, and I have
made no changes to locus.

**Comment by Lineflyer** [comment]
It seems you set up to open links like "https://coord.info/GC8XEQC" with Locus by default. As this defaults applies system wide, it will of course also open Locus at this point. 

Please go to you system settings - Apps - and reset the default values for "open with" for Locus.

Question to the developers:
I have seen other apps being able to directly trigger the default browser app at such actions instead of going through the normal "intent flow".
Does anyone know how this can be achieved? IMHO this would be useful for this case and even more for "open in browser" as this has currently a high potential to open c:geo again (which is 100% undesired behaviour as people come from c:geo) if it is setup as default for these links.

**Comment by bluepanther51** [comment]
Geocaching4locus seems to have been the culprit.  Uninstalled both locus
apps.  It is now working fine.

Thanks.

**Comment by fm-sys** [comment]
> I have seen other apps being able to directly trigger the default browser app at such actions instead of going through the normal "intent flow".
Does anyone know how this can be achieved? 

Let's use #6680 to track this...
