### ISSUE TITLE
"Map download" menu entry blank (with GM and GS)

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#8893]
**Describe the bug:**
In the Map menu (while displaying the Map) you can choose to download an offline map.
This looks pretty fine while using an offline map,
but when you're using Google Map or Google Sat, the slot, where the download entry should be, is just empty.
Nevertheless, it can be clicked and starts to (try to) download maps ...

**To Reproduce:**
1. Open map page with Google Map or Google Sat view
2. Click on 'Map' menu
3. Scroll down to last slot ... it's empty
4. click it ... map download procedure starts

**Expected behavior/state after performing these steps:**
The slot should either be labeled correctly (as map download seems to work anyway), or completely be removed.

**Version of c:geo used:**
2020.08.27-NB-422e2ae

**Is the problem reproducible:**
Yes

**Comment by moving-bits** [comment]
Strange. It's being shown here in both modes:

![image](https://user-images.githubusercontent.com/3754370/91630948-0c7ccc80-e9d6-11ea-8a73-c69bca9dd69d.png)

**Comment by fm-sys** [comment]
I can verify the bug exists:
![Screenshot_20200829_090658_cgeo geocaching](https://user-images.githubusercontent.com/64581222/91631080-2539b200-e9d7-11ea-826c-a528905195fb.jpg)

**Comment by moving-bits** [comment]
@fm-sys 
Can you set a breakpoint at line 85 in `maps/MapProviderFactory` and debug into it?

```
parentMenu.add(Menu.NONE, R.id.menu_download_offlinemap, mapSources.size() + 1, R.string.downloadmap_title);
```

**Comment by MagpieFourtyTwo** [comment]
Possibly depends on Dark Mode?

**Comment by moving-bits** [comment]
> Possibly depends on Dark Mode?

It does work here in both modes. That's why I need to get more info on it from someone experiencing that problem, either system info (API level etc.) and/or by throwing it into the debugger and seeing what's going on.

**Comment by fm-sys** [comment]
Probably it is related to #7587, but I hadn't time to debug into it yet

**Comment by fm-sys** [comment]
Here is a log file where I switched from Mapsforge to GMap and then started the Offline Map downloader. Unfortunately I can't debug it with android studio because I have no api keys for google maps (yet)... 

[logcat_2020-08-30_19-32.txt](https://github.com/cgeo/cgeo/files/5147226/logcat_2020-08-30_19-32.txt)

**Comment by moving-bits** [comment]
@fm-sys 
Thanks for creating the Logcat.
Google Maps activity seems to be around lines 430-480, but alas I cannot find any reason for the menu entry not displaying its text. I think I need to add some more debugging info to the source area in question, so that you can run that APK on your machine and create another log.

As for the "no GM keys": As long as the map window opens and the menu text does not show up, this should be fine for debugging in this case, as the core map functionality should not be needed here.

**Comment by moving-bits** [comment]
I've created a test PR (#8918) to see if a different method of grouping the elements helps.

It seems to be impossible to define an item statically at the end of a dynamically populated menu item list :-(

But: If it's ok to have the menu item for "Download offline map" at the top of the map sources list, then there would be an easy solution for the problem, as then we could add this menu item statically, and add the different map sources dynamically below that item.
