### ISSUE TITLE
Enhance signature number template 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#8951]
check if some logs are newer as the cache-log you are logging and if it's the case ignore them. 

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/8947#issuecomment-687153512_

**Comment by MagpieFourtyTwo** [comment]
Hmm ... don't know if I fully understood your intention, but do you want to decrement the automatically inserted [NUMBER] value by the count of caches which (may) have been logged *after* the one which is going to be logged right now (i. e. retrospectively) ...?

Don't want to curb your enthusiasm, but do you think the effort put into this will really pay out?
Perhaps you would like to consider what came into my mind by reading your post:
1. if there are (apart from caches with younger dates) some already logged caches with the *same* date as the newly logged one,
   how to distinguish (without exact time of log), which one was before or after the newly logged one ...?
2. given there are one or more already logged caches with dates *after* the one currently logged,
   a value of [NUMBER] decreased by this count, may even result in the correct number (given that 1. is not the case)
   but then this calculated value for [NUMBER], which will be inserted into the new (retrospective) log,
   will now exist twice (or even more) ... and all consecutive previously inserted [NUMBER]s will be wrong, too.

So, if one logs retrospectively, someone has to clean the mess manually, anyway,
and that's why I don't get why to put effort into an automatism that can already by design not work correctly ...?

**Comment by fm-sys** [comment]
Agreed.

The actual thought was to fix the wrong found number if someone is reinserting the signature when there are already newer offline cache logs. But this users can also use the legacy number template introduced yesterday...

**Comment by fm-sys** [comment]
Since it would lead to more bugs than it solves, I'll close this now...
