### ISSUE TITLE
What is the image title prefix?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8970]
Out on vacation I tried the new logging sheet with its image feature.

I however got no clue what the "Image title prefix" is. It does not seem to be used on upload.

I am afraid many people will confuse it with the title as it is shown very prominent. If its only informative, why not use the title here?

**Comment by eddiemuc** [comment]
This prefix is used as title for images where the user does not enter an explicit title.
I expected this question. Shall I remove the field? Then a default (from strings.xml) will be used for empty titles

**Comment by Lineflyer** [comment]
Mmh...why not enter the title right there and use the next picture dialog only for the subtitle?

For this to make sense we should then also remove the add picture menu itself and fully rely on the new graphical UI....how about this?

**Comment by eddiemuc** [comment]
Let me double-check so I fully understand what you mean.

> Mmh...why not enter the title right there and use the next picture dialog only for the subtitle?

Do you mean that user should enter title directly in the image list on the main log dialog (instead of the picture dialog)? Or am I misunderstanding this?

> 
> For this to make sense we should then also remove the add picture menu itself and fully rely on the new graphical UI....how about this?

Do you mean removal of the "add image" option in the three-dot-menu or something else?

I am unsure on how much the options for adding title and description to images are really used, I don't use them at all myself and thus they seem to me too "prominently featured" in c:geo.  I initially thought about placing a image-from-camera icon directly on the log dialog too and also enable image multi-selection in the add-img-from-device option, also moving everything to the main log dialog (e.g. scaling) to allow multiple image selection for the not-interested-in-adding-title-or-description use case without ever going to the image dialog. I also considered not showing these informations on the main log dialog (just an image thumb). But this seemed too much of a breaking change with "feeled" c:geo GUI conventions to me without having a discussion first.
What would be your opinion on these things (goes also to other interested people)?

**Comment by SammysHP** [comment]
At least a title field should be kept. Don't know how many people use descriptions, but I vote for keeping it as well.

**Comment by eddiemuc** [comment]
> At least a title field should be kept. Don't know how many people use descriptions, but I vote for keeping it as well. 

Don't worry, I never meant to remove any of the two. Just want to allow a "fast edit path"

**Comment by eddiemuc** [comment]
To honor the original request I suggest removing the title prefix completely for now. If that's all right, I will do that.

For the other thing I have an idea but will open separate issue for it

**Comment by fm-sys** [comment]
I finally understand the "image title prefix" (also it took a while) and I think it is quite useful, even more in combination with #8978. So I vote for keeping it, if we skip the image-dialog by default...

**Comment by eddiemuc** [comment]
> I finally understand the "image title prefix" (also it took a while) and I think it is quite useful, even more in combination with #8978. So I vote for keeping it, if we skip the image-dialog by default...

Of course it is also ok for me to keep it :-) I have to agree that the meaning of this field is hard to understand though. In case we keep it: are there any ideas on how to make the purpose "more obvious" to the user? (because I have none unfortunately)

**Comment by Lineflyer** [comment]
My proposal some posts above was like:
In the current solution we could just make the prefix field the same as the title field. So whatever is entered just shows up in both fields. 

However the proposal you made in the other issue to add a new file chooser is even more meaningful.

**Comment by eddiemuc** [comment]
> My proposal some posts above was like:
> In the current solution we could just make the prefix field the same as the title field. So whatever is entered just shows up in both fields.

Which field are you referring to as "title field" here? Sorry for my slow understanding.

**Comment by fm-sys** [comment]
> Which field are you referring to as "title field" here? Sorry for my slow understanding.

Probably the "Caption" field at the edit image dialog...

**Comment by Lineflyer** [comment]
> Probably the "Caption" field at the edit image dialog...

Yes, the one which is named "Überschrift" in german.

**Comment by Lineflyer** [comment]
After reading through the comments and trying it out again, I think the prefix field should be removed as long as we have the image dialog behind it where users can enter a title.
if later we decide to remove the separate image dialog (where user can enter title and description) we should of course introduce such fields in the logging dialog. But for now I think it only confuses the user.

would that be OK?

**Comment by eddiemuc** [comment]
> would that be OK?

yes :-)

**Comment by eddiemuc** [comment]
PR #9034 will remove log title prefix from gui
