### ISSUE TITLE
Found cache not marked found after logging from popup

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9046]
This might be a duplicate as this is no new bug IMHO, but I could not find a similar issue although I think it is already known.

Scenario:
- Open live map
- Click on cache to open popup
- Click on popup "three-dot" -> Log visit
- Compose found log and send log to server
- Return to live map

Result:
- Cache is still shown (as unfound)
- Only after leaving/ starting the live map the cache is correctly hidden

Expected result:
- Cache status should be updated on map (and maybe even filtered out it "hide found" is active) directly after logging

**Comment by geocachermgo** [comment]
See comment of @MagpieFourtyTwo at #9012

**Comment by MagpieFourtyTwo** [comment]
Isn't this the same with logging a cache while being in ``Logbook``, then sending it to the server ... and on return to the ``Logbook`` you still have to refresh the offline copy in order to see the real log ...?

Maybe, the issue you're having in mind is a really old one (about four to five years)? Once upon a time, logging from popup failed completely and esp. offline logs have not even be saved when leaving the log edit window by back key ...? This at least was the scenario that led to my habit to always log from ``Logbook`` and leaving the log edit window by ``Menu`` => ``Save Offline``.

**Comment by MagpieFourtyTwo** [comment]
> See comment of @MagpieFourtyTwo at #9012

This is in fact a different scenario, as when logging through popup and immediately returning to the initial map, you're in fact going back to the very same instance of the map, thus the map should indeed be "able" to know that s/th might have happened to the cache, hence "she" should refresh it, for safety's sake.

**Comment by Lineflyer** [comment]
Reconfirmed by a user and retested in my emulator.
Bug is still present in current `master` and reproducible.
