### ISSUE TITLE
disable "Forward" menu for user defined geocache

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9095]
I can choose several targets for forwarding a geocache.
Most of them are empty if chosen:
Text editor, Signal messenger, Notes, Browser, google translate
If I choose my mail client, I get "Geocache ZZ<xyz> <title>" as subject.
I'd like to suggest to also put something out as text or reduce the target programs to mail programs
edit: changed GC to ZZ

**Comment by moving-bits** [comment]
Can you provide some more detail, please: Where in c:geo you are, what are you doing to forward a cache etc., maybe a screenshot.

**Comment by geocachermgo** [comment]
I open the geocache, eg from a list or map the use the menu (see orange arrow)
![IMG_20200929_202600](https://user-images.githubusercontent.com/43813636/94600480-386bc600-0292-11eb-82cd-15cb383a3124.jpg)
This leads to the menu being shown, where I choose forward
![IMG_20200929_202419](https://user-images.githubusercontent.com/43813636/94600633-723ccc80-0292-11eb-84fb-54caec57fd58.jpg)
this gives a selection of ways to forward:
![IMG_20200929_202344](https://user-images.githubusercontent.com/43813636/94600732-9e584d80-0292-11eb-88a1-0edd430582ca.jpg)
If I chose the text editor or one of the above mentioned programs nothing was forwarded.
With the cache from the pictures it works.

Yesterday I tried it with a user defined cache.
To the text file, the GC Link https://coord.info/GCCC88 is created. Which is not possible for a user defined cache. Do you think we should have a substitute for a user defined cache or shall I simple close the issue?

**Comment by Lineflyer** [comment]
> Do you think we should have a substitute for a user defined cache or shall I simple close the issue?

We should disable the share menu for user defined caches. Forwarding (a link) will never work. Users can export it to a GPX instead.

**Comment by moving-bits** [comment]
@geocachermgo 
Thanks for providing additional info and screenshots. I have to admit that I did not know that function and probably never have used it so far...

Therefore I went to have a look at the source code:
The "share" function tries to use the `ActionProvider` from the menu entry (not sure what this is), and if it cannot find one, it creates its own intent of type `text/plain` with cache title and cache URL in a separate field.
It depends on the receiving app what this will lead to.
For user-defined cache there is no URL, so in that case it might lead to cache title only.

Anyway, I'm still unsure what this issue is about:
- only cache title for user-defined caches, or
- apps reacting different on the transmitted data?

Extra observation: For the "user-defined cache" use case I see that apps are responding in different ways to it:
- Samsung Notes creates a new note, displaying the cache title,
- whereas WhatsApp complains about an empty note

(so WhatsApp seems to recognize the `Intent.EXTRA_TEXT` only, whereas Samsung Notes additionally listens to the `Intent.EXTRA_SUBJECT` part of the intent)

Not sure if we can do much about that part, except maybe putting the cache title into `Intent.EXTRA_TEXT` if there's no URL.

**Comment by geocachermgo** [comment]
I also used it for the first time and was expecting something closer to the export function (e.g. the coodinates included).
That the forward is empty should be changed IMHO:
I think there a 3 possibilities:
1) As Lars suggested, block "forward" for user defined caches
2) Put something equivalent to the link in the Intent.EXTRA_TEXT like "Local cache"
3) As you suggested putting the title additionally in the Intent.EXTRA_TEXT

**Comment by moving-bits** [comment]
> I think there a 3 possibilities:

As there is no link equivalent for user-defined caches I would vote for solutions 1 or 3. But as the title of a user-defined cache alone probably is not of much use, I'll prepare a PR for solution 1.

**Comment by Lineflyer** [comment]
Well: Its a share menu to share the content you are seeing. In case of a UDC this makes no sense as there is nothing shareable beside the name (which is more about C&P)
So, Solution 1.
