### ISSUE TITLE
EXIF location info from cache/log images no longer indicated

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9182]
**Describe the bug:**
Reported on support mail but not yet validated (as I do not find a matching example cache/log yet).

**To Reproduce:**
1. Open cache details of a cache
2. Swipe to gallery of this cache
3. Pictures which contain exif location info should have a watermark (compass rose) on the lower right and the contect menu should offer extraction of a waypoint for these coords

**Actual behavior/state after performing these steps:**
The user claims, that the watermark and the ability to extract coords is now missing

**Expected behavior/state after performing these steps:**
Should work as before.

**Version of c:geo used:**
2020.10.04

**Is the problem reproducible:**
I did not yet find a cache which used to have such an image in logbook or on cache page, therefore I could not check.
The user also does not find anything, but that might be caused by the problem itself

**Additional context:**
It might also be, that gc.com now strips this info for all images?

**Comment by eddiemuc** [comment]
Yet another c:geo feature I never knew existed...

I found the feature in the code, so if you find a cache with EXIF coordinate information this should still work. However this might be hard to find these days...

Quick internet search found this: https://forums.geocaching.com/GC/index.php?/topic/350572-how-can-i-keep-exif-informations/ 
According to this, stripping away EXIF information was done by gc.com since 2018. Thus you would need to find a cache where either log image or cache owner image contains EXIT with coordinate info in them.
I found cache GC7 (very old!), there is one log entry with image in it which contains EXIF info. Alas, no coordinate info in it. But there might be some others...

**Comment by geocachermgo** [comment]
Still works for me. Example (spoiler picture): GC 2PC BB (geocode separated against search engines).
Yet another c:geo feature I never knew existed...

**Comment by Lineflyer** [comment]
@geocachermgo 
Thanks for finding an example and I can confirm its working as intended.
So the user might "only" have the problem, that he e.g. expects EXIF for an own image but it gets stripped off during upload.
Will inform him accordingly.

**Comment by eddiemuc** [comment]
Found one too: GCM4J3 (just in case we need examples for this in the future)
