### ISSUE TITLE
Resolution of added picture is not changed

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9204]
I wrote a log and added a picture. There was a low resulution preset (315x?).
A picture of the low resolution was created in the cgeo dir.
When I then edited the resulution to a higher value, it had no influence.
Can someone confirm, that changing the resoluion will not create a new image?
If this is true, there should be message: increase of resolution after adding is impossible, please delete and add again.

**Comment by eddiemuc** [comment]
I can confirm that resolution of images is only scaled "downwards", never "upwards". I believe this was always the case. I assume the reason is that it does not make much sense to "upscale" an image (it will only make the image "fuzzier" and not re-add any lost precision, because the original image is gone after downscaling)

**Comment by geocachermgo** [comment]
The original picture has 2500x4000.
But the copy in the cgeo was reduced to 315x512.
Then I wanted to change this to a higher resulution
This was not possible, since the copy in the cgeo dir) was already reduced.
Maybe it was my fault and I should have chosen the resolution before selecting the picture.
This is not intuitive if you going from top to bottom.

**Comment by fm-sys** [comment]
We should store a copy of the *original* image in the c:geo dir and do the scaling while upload, shouldn't we? 
The scaling itself is probably quite fast (ms) while sending a log takes some seconds anyway and disk usage isn't a problem nowadays, so this is the right way of going IMHO...

**Comment by eddiemuc** [comment]
The original way of adding images via menu entry (and selecting scaling/noscaling there) is still available and untouched (apart from exif data getting stripped away). You can use it when you want to keep in full control of the scaling. But upscaling after downscaling was never possible in c:geo and would be a new feature request imho.

I suggested in the original issue to add a third image button for this, especially for people wanting to keep in control. This can still be done. What do you think?

**Comment by fm-sys** [comment]
> But upscaling after downscaling was never possible in c:geo and would be a new feature request imho.

Just because it has always been like this, does not mean that it has to stay like it is. Scaling the images while upload shouldn't be an extensive change, so why wasting time with implementing a warning message for it? 
> I suggested in the original issue to add a third image button for this, especially for people wanting to keep in control.

I did not really understand the use case of this third button. For most users it would be rather confusing and all other can make use of the action bar entry...

**Comment by eddiemuc** [comment]
> > But upscaling after downscaling was never possible in c:geo and would be a new feature request imho.
> 
> Just because it has always been like this, does not mean that it has to stay like it is. Scaling the images while upload shouldn't be an extensive change, so why wasting time with implementing a warning message for it?

Absolutely! I just stated that this would be a feature request and not a bug. Maybe "Perform image scaling for log images on upload only" or something like this? (we can even reuse this issue for it)

If this is the feature wanted, I would have some detailling questions:
* Do you want to give the user control over which scaling is used for upload? 
  * SHould this control be available on a per-image-base, a per-log-base, a c:geo-global-base (e.g. via Settings) or hardcoded
  * What would be the default value? Should it be different for different services (gc.com, oc, ...)?
  * Depending on the above answers, how would you expect this to be visualized in GUI?
* Do you want in turn remove the user's possibility to set scaling directly on image-selection (as he/she has today) and always store untouched original images until the user uploads the log?
  * Note: this would result in drastic raise of image storage space required as of today...
* Today, each image is already modified on-save for removing EXIF. This process dramatically reduces image sizes even when keeping scale, so I assume the Android libraries we use is doing more than just removing EXIF under-the-hood. Would you also want to give the user more control here (keeping "raw" original image all the time including EXIF until upload)? Should the user also be able to choose "upload original image data" if he/she wants to? How would you handle this in GUI?
* If we do scaling on upload only, we can't show the user in advance how big the size of the image will be at upload (because we only know this after scaling of course). Is that ok?

**Comment by fm-sys** [comment]
> Today, each image is already modified on-save for removing EXIF. This process dramatically reduces image sizes even when keeping scale, so I assume the Android libraries we use is doing more than just removing EXIF under-the-hood. Would you also want to give the user more control here (keeping "raw" original image all the time including EXIF until upload)?

As we decided to always remove the EXIF we can leave it like it is imho.
I would even go one step further and remove the "no scaling option" so the pictures should be stored with the maximal supported scaling in the data dir. Maybe we can extend the resolution-selection-list to 2048 px or whatever gc's maximum is. 

> If we do scaling on upload only, we can't show the user in advance how big the size of the image will be at upload (because we only know this after scaling of course). Is that ok?

Imho yes...

> Do you want to give the user control over which scaling is used for upload? 

I would leave it like it is and just store the selected scaling in the database in a new column in `cg_logs_offline_images`

> What would be the default value?

Imho the same as today (1024 px). Additionally, if necessary a settings option for selecting a different default scale under settings > logging

**Comment by eddiemuc** [comment]
Update: regarding the "dramatic reducing of image size on EXIF removal": I took a peek in the code, and I found out that the routine also:
* stores the resulting image with a hard-coded quality rate of 75%
* somehow also reduces the "sample size" (this is hard to understand, but my impression is that current code somehow downsamples multiple times here... I am alas not an expert for the image tooling)

So, additional question is whether you want to give the user control not only for scaling but maybe also for JPEG compression parameters and maybe this "sampling" thing (which I don't quite understand myself)? All questions from above would apply to this as well of course (set on global/ind.-log/per-image-level, how to handle this in GUI etc)

Here is the code reference if you want to dig in deeper into current implementation:

https://github.com/cgeo/cgeo/blob/d528da71d52ee4aa6a79e44937519bb20a417c54/main/src/cgeo/geocaching/utils/ImageUtils.java#L191-L229

**Comment by fm-sys** [comment]
> So, additional question is whether you want to give the user control not only for scaling but maybe also for JPEG compression parameters and maybe this "sampling" thing (which I don't quite understand myself)?

Why should we confuse our users with things, we do not understand ourselves? We should change as much as necessary but as little as possible. JPEG compressing is working fine, and we do not have negative feedback due to it. Or to express it even more dramatically: Nobody has ever noticed it! So never change a running system ;-)

**Comment by eddiemuc** [comment]
> > So, additional question is whether you want to give the user control not only for scaling but maybe also for JPEG compression parameters and maybe this "sampling" thing (which I don't quite understand myself)?
> 
> Why should we confuse our users with things, we do not understand ourselves? We should change as much as necessary but as little as possible. JPEG compressing is working fine, and we do not have negative feedback due to it. Or to express it even more dramatically: Nobody has ever noticed it! So never change a running system ;-)

Well, there is one new thing about that: previous to my change to enforce EXIF removal, the user had the chance to just leave the original, untouched, unmodified "raw" image for upload (by selecting "no scaling" in the old image dialog). This is now changed since I implemented "forced" removal of EXIF information which in turn also is doing the things above. I can remove the "forced" EXIF removal" easily of course to revert to the behaviour of c:geo before if this is wanted.

This issue is about scaling of course, but unfortunately c:geo code mangles these things together. Lots of refactoring work waiting for motivated developers here :-)

**Comment by geocachermgo** [comment]
Interesting info. Is there a difference between adding picture via the image symbol or via menu?
Or is the (75% + no Exif) operation done in both cases.

What I was complaing about was that if you use the image symbol you get the resolution of the last picture  and if you try to increase that, its not working without info. 

So from my side a small solution would be to grey out the higher resolutions if you edit a picture that is already in the cgeo dir.
At the moment the camera and picture button include "will be reduced to the last used resolution (which we don't show) and that cannot be increased later."
That fine for user who uses always the same resolution.
The others can use the menu and modify the resolution therr and use the button afterwards.
Other option: Show the resolution right to the buttons and make it changable there.

**Comment by eddiemuc** [comment]
> Interesting info. Is there a difference between adding picture via the image symbol or via menu?
> Or is the (75% + no Exif) operation done in both cases.

This is done in both cases

**Comment by moving-bits** [comment]
+1 for storing the selected image(s) as originals until starting the upload, and only then resizing and stripping EXIF data. I would not introduce new special options like selecting "JPEG compression factor" etc.

**Comment by Lineflyer** [comment]
@eddiemuc 
This is solved meanwhile, isn't it?

**Comment by eddiemuc** [comment]
Yes this can be closed
