### ISSUE TITLE
Individual route: Calculate route from current position

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9281]
I'm frequently using the "individual route" feature on my trips. For this I connect all caches/waypoints to be visited into an individual route, and by that the length of this route gets displayed in the upper right corner.

What I'm missing, though, while being on such a tour, is the actual remaining distance from my current position.
Normally I remove a cache/waypoint from my route as soon as I've visited it. The route gets recalculated for the remaining points. But the the part from my current position to the next point of my route is missing in both routing and distance.

If I do not delete the last visited point directly, but only when reaching the next point of my route, I still have the routing, but the distance does not get updated along the way until I remove that point.

Current workaround is
- to delete last visited point as soon as I've been there, and
- set the next point of my route as new routing target.

(which does work, but is pretty cumbersome on tours with many caches/waypoints)

What I would like to see is an option (in the "individual route" menu) to do this step automatically for me, so always set the first entry of my individual route as routing target on every route change (if option is activated).

**Comment by MagpieFourtyTwo** [comment]
Just played a bit with the new ``Set as target automatically`` option - nice feature.
And after a while I even understood what is meant with the words ``Set as target automatically`` ... ;)

Ok, BSF: The wording may be seen as "pretty clear" - but only *if you already (and fully) know what will happen*.
To me, at least, it was not really obvious that this results in a "standard" route from my current position to the first point of the individual route - not even talking of the intention to steadily remove (visited) points from the individual route in order to keep things of the "standard" route going, i. e. move it's routing target automatically.
But IMHO the user needs theses info in order to efficiently work with this option.

In fact, I would add a text box with some explanations, which may perhaps appear when setting the option.
It may explain in short what will happen (e. g. "a standard route to the start of the individual route") and how to proceed to work with it (e. g. "it's target will automatically be changed to the next point of the individual route, as soon as you remove the currently first point of the individual route (e. g. cause you have just visited it)").

And perhaps the explanation box could even have a checkbox like IIRC the info box for the "count + \<offline logs>" has, like "[_] Do not show again" or alike ...?

Nevertheless, one last question: How can I get rid of the route to the route ...?
Would have expected that the "standard" route will disappear as soon as the individual route has no points anymore. Or has been cleared.  But the "automatic" route stays until I remove/clear all points *and* leave and re-enter the map ... is this intended?

**Comment by moving-bits** [comment]
@MagpieFourtyTwo 
Thanks for your feedback. Yes, it's always difficult to find a short & precise description. Do you have a suggestions how to rephrase the menu label to make it easier to understand?

Regarding the one-time message: I would use this medium with caution, only for very important messages. Offline counter has been such a type, IMHO, as the extra counter is clearly visible and potentially pretty confusing, if you don't know what's going on in the background. - I don't think that this applies to this function. I would propose to describe the new menu entry in our very nice & handy online documentation instead.

**Comment by MagpieFourtyTwo** [comment]
Thought about a short and "grippy" phrase, but had no idea so far. What I considered to be more clear is "Always route to start of individual route" - but this is even longer ...  :/ Can there perhaps be a "two line option" in the menu?

BTW: Had a really hard time this evening, while struggling to get rid of a seemingly wrong (and extremely stubborn) route.

First it seemed to me, as if this was just a remainder of yesterday's cache searches, as the map just showed this last visited cache, plus the route to it. So I first just re-started Live Map. But even on the next start and entering Live Map via c:geo's main screen, just this single cache was there ... plus the mentioned seemingly stubborn route. So I removed c:geo from Recent Apps ... to no avail. \*grr* In fact this looked like a weird c:geo bug ...

Took a while until I realized the reason:  The ``Set as target automatically`` option was still activated - *and* there was an individual route which was unfortunately "invisible", as it consisted of just one single position: This last cache. Even harder to spot, as even clearing the individual route seemed to change nothing at all ... which all in all I would consider a scenario, where Joe Average will most probably become *really* desperate. And eventually (hopefully) talks to @Lineflyer (if not just kicks the app) ...  ;)

So, how to explain that this option will lead to a situation where on every call of Live Map you will just see this cache and esp. a route to it, resp. to the "invisible" route ...?

While things will get even harder, if there is a longer time lag between setting (resp. playing with) this option and using an individual route next time ... or even creating an individual route by accident, without even recognizing what you've done (e. g. by tapping a cache a little bit too long) ... cause while "creating" an individual route, you don't necessarily see the option's state ... but nevertheless you will get this (seemingly) extremely stubborn route ... without knowing how to get rid of it ...

In fact, in this (not *that* unlikely) scenario you currently even need kind of a workflow to be able to use c:geo "normally" again:
1. clear individual route
2. deactivate ``Set as target automatically``
3. leave and re-enter Live Map

After having gone this stony road tonight, I would strongly suggest to implement a "Fall Back Strategy" that gives a chance to esp. inexperienced users, to get back to a "normal" state ... or maybe by displaying a warning toast when Live Map is entered with an active "Automatic route" (e. g. "Automatic routing to the start of your individual is active - unset option `Set as target automatically`` to clear it.").

Moreover I would even more suggest to let the "Automatic route" vanish immediately, as soon as the `Set as target automatically`` option is unset.

**Comment by moving-bits** [comment]
> BTW: Had a really hard time this evening, while struggling to get rid of a seemingly wrong (and extremely stubborn) route.

I'm sorry for that, should have warned you that unsetting a target is not possible yet. This is true for a manually chosen target as well, but there simply closing and re-opening the map helps, which is cumbersome, but works.

Current workaround would be
- to unset the "set as target automatically"
- and close/re-open the map.

Anyway, I'll work on a solution to reset the target.

**Comment by MagpieFourtyTwo** [comment]
> I'm sorry for that

No need for. Was a valuable experience and I've learned something. And not only how to get out of a route to a route.  ;)

Admittedly, I suddenly found myself caught in a situation, like similar ones I have seen a lot of people in the past been trapped in, sometimes without even having the smallest idea, how they could *not* have managed to get out there on their own ... and in fact the answer is stunningly easy: You just have to know how. Solution is always easy, if you only know how. ;)

But oftenly we - as the more experienced users (without wanting to appear arrogant) or even developers - forget that most of the people out there do *not* have the knowledge, cause they do not work on a daily basis with the tools, we are using day after day until all this so called "basic" knowledge becomes *that* natural ... that we don't even think about it.

So, in fact, this experience re-grounded me again a bit. Thus: Thx 4 the ride! :) 

And, most hopefully, you find an easy way out for the users - and it would of course be even better if my experience may help, so I did not struggle for nothing.  ;)

**Comment by MagpieFourtyTwo** [comment]
BTW: Was just made aware again of something I had already suggested half a year ago: See #8138
Perhaps these (or s/th like such) semitransparent icons can be used to show the ``Route to Route`` setting more prominent?

**Comment by moving-bits** [comment]
> BTW: Was just made aware again of something I had already suggested half a year ago: See #8138
> Perhaps these (or s/th like such) semitransparent icons can be used to show the `Route to Route` setting more prominent?

Thanks for bringing up this idea, I did not have that on my mind anymore. I would argue not to use that much of precious map space to present a set of toggles, but the idea of a "hide" dialog which does not close after each tap is still nice, and maybe we find place on the map to bring up this dialog without having to use a submenu.

Regarding the "clear target": I've implemented a PR which resets the target if the "auto-target" option for individual route is cleared as well as when the individual route loses its last route item. This is done automatically "under the hood".

Would you suggest to put an explicit "clear target" menu entry into the "hide" menu/dialog? This would clear the "auto-target" from individual route, resetting that option, as well as clear a manually chosen target. Or do you have a different place for such a menu entry in mind? Or don't need an explicit menu entry at all?

**Comment by eddiemuc** [comment]
>  I would argue not to use that much of precious map space to present a set of toggles

The discussion whether it is worth to give up a bit of map space to present a c:geo function ore prominently/easy to use seems to pop up frequently. Maybe a more general solution could solve this discussion once and for all. I looked (as so often) how Locus is doing this, and here the user can define by him/herself individually which function toggles should be placed on the upper and right side of the map display. Transferring this idea to c:geo, we could e.g. make the different distance views, cache title display as well as the different shoe/hide toggles make available as configurable icons. Other shortcuts from menu can be made available too (e.g. type of routing, toggle actualization etc). 
However I assume that would be a bigger thing.

**Comment by MagpieFourtyTwo** [comment]
> I looked (as so often) how Locus is doing this, and here the user can define by him/herself individually which function toggles should be placed on the upper and right side of the map display. 

Good idea. Would *really* like it.
Although I have to admit that it took a while to become friends with these *really* prominent panels.

Break-through happened (and I'm pretty sure, @moving-bits will love this, too), when I got aware that all these panels can be hidden completely. ;)  And what I like best: They (re-)appear on double click on the map.  And you can decide for each panel (top, right, bottom) if it should always be visible or just appear on this double click.  And whether they will appear and stay on change of portrait to landscape mode (or vice versa).

On first sight this sounds a bit complex, but it's pretty intuitive and self-explanatory, once you've had a glance at the settings, which BTW all have a short explanation text - which I really like, too.  Moreover these are "set & forget" options, so you configure your interface once, and then just work with it.  Really like such possibilities to adjust an interface to my needs.

Admittedly, this would of course be a small regression with regard to zooming, cause you lose the double-tap-to-zoom, but to be honest: With [+/-] buttons and pinch&zoom there would still be two possibilities to zoom, which should be sufficient.

**Comment by MagpieFourtyTwo** [comment]
> the idea of a "hide" dialog which does not close after each tap is still nice

This was in fact what I was asked yesterday evening by a c:geo user.

>  I've implemented a PR which resets the target if the "auto-target" option for individual route is cleared as well as when the individual route loses its last route item.

Great. This will avoid at least the biggest problems, I guess.

> Would you suggest to put an explicit "clear target" menu entry into the "hide" menu/dialog? This would clear the "auto-target" from individual route, resetting that option, as well as clear a manually chosen target. Or do you have a different place for such a menu entry in mind? Or don't need an explicit menu entry at all?

A "put me to a state where I can work normally again" button is always a good idea, esp. when a user would need several steps to get rid of the consequences of (seemingly) just one single, a little bit too long tap ... so, yes, would support such an entry. And I would say, an entry in the menu would be sufficient. Nevertheless I would like to see a toast each time the map is opened with such a potentially "stubborn" route, which points me to the possibility to use this menu entry (or to reset the ``Set as target automatically`` toggle).

**Comment by MagpieFourtyTwo** [comment]
Had another seemingly "stubborn" scenario this weekend: While driving to the planned cache, let's call it "GC1", everything seemed to be fine, route to it was displayed properly, and everything was running smooth. But then ...
- I saw another cache GC2 on the map, worth visiting, that was a little off our route
- so I opened it's map popup, clicked ``Details``, checked GC2's details ...
  - clicked the ``Route to`` symbol (which brought me back to map),
  - then tapped the ``Center map on my position`` button ...
  - and felt fine.
- what I did not realize right then (c:geo never ever made a problem with regard to changing the routing target, so I did not check *that* deep): The route had not changed at all. What was add. hard to see, as GC2 was a) still far away, thus not on currently displayed map segment and b) not *that* off-route, that a major route change was to be expected, so everything seemed to be fine.
- as there was still plenty of spare time, I checked for another "by-catch" GC3, which was even more off-route, so I again changed route, via map popup => ``Details`` => ``Route to`` => ``Center on my position``
- but this time I wanted to see in which order we should visit GC2 and GC3, so *now* I checked the route and realized for the first time that it remained unchanged, it was still pointing to GC1.
- so I again tried to change the route to one of the "by-catches" (via popup ... rest as above) ... but to no avail, c:geo ignored my demands to change the route completely.

Took a second until I realized what has happened:
- ``[X] Automatic route to target`` was still activated
  Remark: Usually I would suppose such an option as a "set & forget" - but this one must *really* be handled with care, yet
- an individual route seemed to exist
  most probably consisting of just one point (GC1), as around GC1 there was nothing to see in the map, which could have reminded me of this "potential risk" ;)

Most probably these two were remnants from the tour plannings from the day before (which is in fact the only logical explanation I have right now).

What made things harder to find out:
- no individual route was shown on map at all
- even after clearing the most probably existing individual route, the route remained to point to GC1,
  so most probably the consecutive changes of route target to GC2 and afterwards GC3 have been ignored completely
 - clearing the individual route did not reset the ``Automatic routing`` target

Questions arising:
- Does an individual route consisting of just one point make any sense at all?
  And this not just because of the problems it makes with ``Automatic route to target``, but what could the intention of such a crippled route be, which can not be achieved with a "normal" route resp. map view of this cache?
  FFS: Perhaps an individual route consisting of just one point should be cleared at least on every fresh (re)start of c:geo?
- What if ...
   a) ``Automatically route to target`` is set,
   b) an individual route exists *and*
   c) the user decides to *manually* route to a different point?
   My opinion: Manual user interaction has to be prioritized, no matter which hidden setting may interfere or which automatism would suggest to do things in a different way. And *if* there are reasons to reject a user input (and sometimes there are of course *plenty* of them ;) ) the program should inform the user *that* and additionally *why* it will ignore his master's wish. Or at least ask ``Do you really want to ...`` but never ever just silently ignore an input and just go on, doing things as it likes.
   FFS: Should ``Automatic route to target`` be implicitly deactivated as soon as the user sets a route target manually ...?

**Comment by moving-bits** [comment]
> Had another seemingly "stubborn" scenario this weekend: While driving to the planned cache, let's call it "GC1", everything seemed to be fine, route to it was displayed properly, and everything was running smooth. But then ...
> * I saw another cache GC2 on the map, worth visiting, that was a little off our route
> * so I opened it's map popup, clicked `Details`, checked GC2's details ...
>   * clicked the `Route to` symbol (which brought me back to map),

Adding a cache/waypoint to an individual route is done only by long-tapping on its icon in the map.

The "set target" button in cache popup (only available when coming from OSM) sets the current navigation target to the selected cache. Nothing gets changed in the individual route by that.

> Took a second until I realized what has happened:
> * `[X] Automatic route to target` was still activated

This is unrelated to not adding caches/waypoints to your individual route.

But I agree, manually setting a navigation target should overrule an automatically set one. I created #9473 for that.

> Does an individual route consisting of just one point make any sense at all?

Not really, if it stays at that. It's just an intermediate step while creating a longer route.

> FFS: Perhaps an individual route consisting of just one point should be cleared at least on every fresh (re)start of c:geo?

Wouldn't do that, because it might be your standard starting point for route, eg homezone.

> * What if ...
>       a) `Automatically route to target` is set,
>       b) an individual route exists _and_
>       c) the user decides to _manually_ route to a different point?
> [...]
> FFS: Should `Automatic route to target` be implicitly deactivated as soon as the user sets a route target manually ...?

See #9473 - it automatically disables "auto-target" in this case, and you'll get a notice extra for free :-)

**Comment by MagpieFourtyTwo** [comment]
> Adding a cache/waypoint to an individual route is done only by long-tapping on its icon in the map.

Yes, I know - and extending the individual route was not my intention at all.
Just wanted to replace the (seemingly) "normal" routing target by a new one.
In fact I did not even know by this time, that an individual route was involved into my problem.
But this doesn't matter at all, cause the message "manually setting a navigation target should overrule an automatically set one" has arrived anyway. ;)

> and you'll get a notice extra for free :-)

Very kind - I like to be informed - thx a lot!  ;)

**Comment by moving-bits** [comment]
@MagpieFourtyTwo 
Not sure if anything's left open here after having implemented #9425, #9473 and #9505 (except activating it for Google Maps as well, which requires #9492 to be merged first). Except that: Can we close this issue?

**Comment by MagpieFourtyTwo** [comment]
In fact there was no situation anymore, where I got stuck. Seems as if it has become quite intuitive now and can most probably be understood by average users, too. AFAICS the most error-prone scenarios are covered ... looks good. Good work, BTW!

Right now there is just one wish open: As I would consider "automatically route to individual route" as a really critical routing and map option, as it may influence the routing result even more than the routing style, I still would like to see an ``[_] Always route to individual route (if exists)`` or alike in the "Quick settings" popup of the map, as mentioned in in https://github.com/cgeo/cgeo/issues/8138#issuecomment-737571005 - but this may better be discussed over there, I suppose.

If you agree, we can safely close this one, and let daily work decide over future changes, I would say. ;)

**Comment by moving-bits** [comment]
Ok, I've created separate issues as reminder to myself, closing this one now.
