### ISSUE TITLE
Wrong points in Position History

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9360]
![IMG_20201109_135745](https://user-images.githubusercontent.com/43813636/98544670-9c6faa00-2294-11eb-965c-b0d5fc5759b9.jpg)
**Describe the bug:**
In the track there are sporadical points with exactly the home coodinates and elevation 0.
I found this points after a break in the recording.

**To Reproduce:**
1.  Record history and switch phone off for some minutes several times.
Check gpx file for "ele>0.00"

**Version of c:geo used:**
Nightly from 7.11.20

**Is the problem reproducible:**
Yes

**Additional context:**
Diagram was made by http://utrack.crempa.net/

**Comment by fm-sys** [comment]
This is cause the home coordinates don't have the elevation info. But you are right, the home  coordinates shouldn't appear in the history track at all.

**Comment by moving-bits** [comment]
A couple of questions come to my mind from this short discussion:

Is it the home coordinates not to be included, or coordinates without elevation info, or coordinates below a certain degree of certainty? (IMHO it's the last, if at all)

But if excluding the home coordinates: By what radius? Because if you only exclude the home coordinates, track would start 1m apart from that (or something like that). But how to decide which radius would be fine for the users? (Personally, I would like to see the track starting as soon as I switch on GPS & c:geo, even if I'm still at home. And actually, I have not entered my exact home coordinates in the platform, so c:geo doesn't even know my home coordinates...)

OTOH, if excluding a point when having no elevation info: Do we always get an elevation info if we receive a GPS signal? Or may there be edge cases? And what if someone values a consecutive track higher than a missing elevation info for some point?

c:geo is not primarily a tool for track and elevation recording. It's mainly about geocaching, then track recording for your caching trip, and then, as a free extra, recording elevation. So - IMHO - if you need exact elevation info, you'll either need to do some post-processing, or you'll have to use a tool specialized for this task.

I would leave track recording as is, or maybe look whether we skip coordinates whose certainty is below a desired level. (Haven't checked whether we're doing something like that already.)

**Comment by Lomanic** [comment]
I'm quite sure this is an artifact of an issue that was already reported (#9097): when the GPS is not enabled or cgeo cannot get coordinates from satellites when GPS is enabled, it defaults to the "home coordinates". These coordinates are obtained not from cgeo config but GC.com.

I already suggested excluding home coordinates from drawn in the history line https://github.com/cgeo/cgeo/issues/9097#issuecomment-701266895, it was chosen to add a timestamp to the points instead.

> But if excluding the home coordinates: By what radius? Because if you only exclude the home coordinates, track would start 1m apart from that (or something like that).

From my understanding of how cgeo works (just looking at its behavior), we are talking about a case where there's no GPS fix or GPS is disabled, so cgeo "emulates" being at those coordinates, so the current position is _exactly_ at the home coordinates, there's no need for a radius.

**Comment by MagpieFourtyTwo** [comment]
IMO: Instead of defaulting to the home coords (thus perhaps performing a 3000 km time warp within the fraction of a second, just to use the wormhole again in the very next second), c::geo should just stay where it was at the last "real" reading. Cause this position is way more likely the correct one (or at least nearer to reality) than home.

**Comment by geocachermgo** [comment]
> I'm quite sure this is an artifact of an issue that was already reported (#9097): when the GPS is not enabled or cgeo cannot get coordinates from satellites when GPS is enabled, it defaults to the "home coordinates". These coordinates are obtained not from cgeo config but GC.com.
> 
My gc home coodinates are not exactly at home. The star problem of #9097 was caused by being at home and having a gps fix there and that problem is still there.
![Screenshot_2020-11-12-06-25-22-884_cgeo geocaching](https://user-images.githubusercontent.com/43813636/98899600-25166200-24b0-11eb-9817-ef44ed8bb406.jpg)
The problem #9360 is that the position history includes points where I have not been.
Dirty solution could be to exclude the point exactly at the gc home coordinates (maybe including ele=0).
Clear solution would be to check if we have a real location or a replacment by the gc home coodinates before writing that point to the track.
If I'm not logged in with GC but other provider: Do they all provide home coordinates?
Does every (GC) user has home coordinates?
What is the elevation written if the GPS has lateral fix but no height (never observed this)?
I remember a feature ("write point only if gps accuracy is better than adjustable threshold") but can't remember where. I thought it was in Locus but could not find it there.
Despite the artificial gc home coordinates cgeo handles the start quite well. But this may be caused by the time distance of the track points being bigger than my device bringing down the acccuracy.

**Comment by eddiemuc** [comment]
I suggest the following steps to handle this:
* As @Lomanic already suggested many times: only add coordinate to trail history if it is from a real GPS measurement (e.g. don't add default home location if it is used when GOS not available)
* Cut into different trails strictly by time, not by distance. Suggestion: when two measurements are more than 1 hour apart, consider it a different trail.
* Don't record obvious outliers with regards to GPS lat/lon, e.g. when traveling time between two consecutive points would suggest traveling speed more than 300km/h, or other means of outlier detection
* When elevation 0 is reported, smooth it in between former and later reported elevations

**Comment by geocachermgo** [comment]
I fully agree with 1) and 2). 
Regarding 3) Why exclude normal Autobahn speed? ;-)
Regarding 4) Can we distinguish betwen having no elevation and having elevation 0?
I would not spend too much effort in smoothing, interpolation, outlier identification. I think omitting not measured points is enough from the recording side.
Then I'd prefer putting the deviation 
<hdop> xsd:decimal </hdop> [0..1] ?
<vdop> xsd:decimal </vdop> [0..1] ?
<pdop> xsd:decimal </pdop> [0..1] ?
in the recording instead of trying to improve the track.

**Comment by moving-bits** [comment]
@geocachermgo 
I've created PR #9415 which attempts to skip points coming from so called `HOME_PROVIDER` (last known home location from geocaching services) or `INITIAL_PROVIDER` (default location in Paris, used as last resort). Can you cross-check if this works for you, based on build APK, or do you need this merged into a nightly for testing?

**Comment by geocachermgo** [comment]
I can also check with the build apk even if nightly is easier (pictures kept and GMaps working)
Am I right that the build is not yet available?
@MagpieFourtyTwo : is there a way to keep the pictures when deinstalling c:geo? Rename dir before deinstall and puttin it again in place when installing again?

**Comment by MagpieFourtyTwo** [comment]
> is there a way to keep the pictures when deinstalling c:geo

Never thought about that, cause reloading the pics seems to be no problem at all. In fact a while ago (to be more precise: with a mobile with way less storage memory available than today) I even deleted c:geo's pic folder completely, as it occupied a lot of space.

Nevertheless, did some tests right now, and, yes, seems as if the cache pics keep their (seemingly unique) name over different installations, so saving the folder ``/Android/data/cgeo.geocaching/files/GeocacheData `` prior to uninstalling and copy it back after re-installing c:geo seems to bring the pics back, too, without reloading the cache (disabled WLAN and data to check this).
BTW: If - after copying back the GeocacheData folder - you still get the red X (for "pic not found"), just remove c:geo from memory and restart it, then the pics should be there as before.

**Comment by moving-bits** [comment]
> I can also check with the build apk even if nightly is easier (pictures kept and GMaps working)

never mind, it's included in the currently nightly for testing for possible side-effects

**Comment by geocachermgo** [comment]
I realized this and tested today. Looks very good, no home position, no hight=0, no Paris in the track I recorded today. Only negative thing is that there a sometimes speed peaks (e.g 4s 18m=16km/h) at the beginning of a new recording after a break. But I would no do anything about that. Thanks for the fix!
