### ISSUE TITLE
[Nightly] Extend Super-Sized routing distance display

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#9367]
**Is your feature request related to a problem?**
Just checked out the new #9282 "Super-Size routing distance" feature - and really like it. Great idea!
Nevertheless was a bit disappointed, cause - contrary to the promising title - "SuSi" ;) unfortunately does not show the *routing* distance, but just the bee line's length (aka "straight distance").
So, how about extending it to display the *real* routing distance, too (as the title already pretended)?

As tapping one of the two (resp. up to three) different (small) distance display areas to activate SuSi is most probably way too fiddly, esp. in the initially described scenario, the "activation area" should be extend to all displayed distance value fields and then it possibly can just cycle through the distances, i. e. ...
1. tap on (small) bee line's length, routing distance or length of ind. route => SuSi straight distance
2. tap on SuSi straight distance => if routing is active, then show SuSi routing distance, else switch SuSi off
3. tap on SuSi routing distance => switch SuSi off

Length of individual route may safely be ignored here, as it does not change at all, thus has no influence on driving, anyway.

And, last but not least, to distinguish which distance SuSi is currently showing, she maybe even display the symbols from straight distance resp. routing distance.

**Comment by moving-bits** [comment]
> Nevertheless was a bit disappointed, cause - contrary to the promising title - "SuSi" ;) unfortunately does not show the _routing_ distance, but just the bee line's length (aka "straight distance").

Actually it shows the first displayed navigation target distance. If you have enabled the option to show both bee line's length and calculated route's length, the bee line's length is shown, otherwise the calculated route's length.

But anyway, I like the idea of cycling through the up-to-three states, will give it a try :-)

**Comment by MagpieFourtyTwo** [comment]
Great. Nevertheless, I would skip individual route length, as IMO it's not a valuable information while driving.

**Comment by moving-bits** [comment]
> Great. Nevertheless, I would skip individual route length, as IMO it's not a valuable information while driving.

Yes, at least not until #9281 is implemented - will therefore skip this for now.

**Comment by moving-bits** [comment]
One tiny implementation detail:

We have up to three distances, let's call them distance1, distance2, distance3 (the last one being the individual route's distance). The (up to) three of them are display in tiny windows in the top right corner.

Now: If distance1 is displayed as super-size: Shall the tiny distance1 be skipped, and only distance2 and distance3 be displayed (And similar for distance2)? - Or shall the (up to) three tiny windows always stay visible?

Pro for "always stay": Less visual noise/change when switching the supersize views.
Pro for "hide": Then only up to two small windows would be visible, and thus the individual route's distance should still be visible beneath the super-sized distance, otherwise the infos overlap:

![image](https://user-images.githubusercontent.com/3754370/98986348-13bb6d00-2525-11eb-81b0-1ee3647ea57c.png)

**Comment by MagpieFourtyTwo** [comment]
My vote: Most definitely for "hide*, for two reasons:
1. The one you already mentioned (readability of the third)
2. You don't have to think about which is which, cause
     one is SuSi, so the other one must be ... the other one. ;)

**Comment by moving-bits** [comment]
Well, here we are: #9372
