### ISSUE TITLE
Supersized routed distance to big

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9380]
If I supersize the routed distance the string is cut of (probably as the routed graphic in front consumes more space.
Not OK:

![grafik](https://user-images.githubusercontent.com/949669/99153405-a0daff00-26a8-11eb-94cb-073d6a8c2b05.png)

OK:
![grafik](https://user-images.githubusercontent.com/949669/99153414-b2bca200-26a8-11eb-85be-009846ec768a.png)

**Comment by MagpieFourtyTwo** [comment]
The fix was necessary, no question, but most regretfully the distance of individual route is no longer readable anymore now, which was one reason for hiding the distance field which is currently super sized. I guess this is a consequence of the smaller font and the resulting lower line height ...? If so, we possibly need a minimum line height?

**Comment by Lineflyer** [comment]
mmh. We could just show the supersize box below the small distances? How about that?

**Comment by moving-bits** [comment]
Additionally, we could put the remaining up-to-two small distances into the same line if supersizing is active. This would consume less vertical screen estate and avoid an "empty" screen space at the top left.
(But we need to check if this would fit into one line with the cache title in OSM maps.)

Or we could align the individual route distance info to the bottom right of the supersize window, thus getting more unused space due to line spacing.

**Comment by MagpieFourtyTwo** [comment]
Currently the SuSi stuff seems to be centered ...? At least there is plenty of free space on the left side. So what about left aligning it?  Or at least putting it a little bit more to the left?  Half of the m of "km" would already be sufficient, I guess.

**Comment by MagpieFourtyTwo** [comment]
> we could put the remaining up-to-two small distances into the same line if supersizing is active
Would not like this, as it would reduce space for the cache name.
BTW: Why is the name not displayed in GM?
Hmm, just tried the SuSi stuff with GM for the very first time - and it seems to not really work:
Showing SuSi seems to work only if you hit the symbol part of the distance area filed
and toggling through the distances always needs a couple of taps ...
Seems to be an update problem ... if I e. g. tap the distance area, SuSi is not shown immediately,
but if I then leace the map and re-open it, SuSi is there.
Same applies to toggling: Tap ... nothing happens ... leave and re-enter the map => distance value is toggled.
Same for you?  If so, we should open a new issue, I guess ...

**Comment by MagpieFourtyTwo** [comment]
Ah, now: Tapping a distance field area => nothing happens ...
now either wait a while  ... (sometimes SuSi appears resp. changes after a few seconds)
or move the map, then SuSi is updated immediately.
