### ISSUE TITLE
Copy of waypoint to clipboard

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9407]
If I put a waypoint xyz into the clipboard and paste it to another cache the name is not "xyz" but "copy of xyz".

I would like to suggest the the name is not expanded when transferred via clipboard.

**Comment by Narrat** [comment]
And one purely cosmetic thing: Maybe the captions of the buttons for the confirmation dialog that follows the pasting of a custom waypoint could be changed? From `Cancel/Ok` to `No/Yes`? Fits imo better the asked question.

**Comment by Lineflyer** [comment]
> I would like to suggest the the name is not expanded when transferred via clipboard.

Would be more logical indeed as users might prefer a 1:1 copy.
The only downside I can imagine is, that after pasting it into the same cache there will be two with the same name. But for this we have the dedicated "duplicate waypoint" function.

> And one purely cosmetic thing: Maybe the captions of the buttons for the confirmation dialog that follows the pasting of a custom waypoint could be changed? From Cancel/Ok to No/Yes? Fits imo better the asked question.

What dialog are you referring to? I do not get a dialog on pasting a waypoint but its just pasted.

**Comment by Narrat** [comment]
Only appears with waypoints which don't originally belong to any cache. Like manually added stages for multis.
![Screenshot_20201122-140741](https://user-images.githubusercontent.com/2787518/99908104-e0c16800-2ce0-11eb-977b-289f9113c9e4.png)

**Comment by moving-bits** [comment]
> Only appears with waypoints which don't originally belong to any cache. Like manually added stages for multis. And a feature I personally dislike, but I suppose it's there for a reason.

This is to move waypoints from one cache to another (instead of just copy). Naturally this is allowed for user-created waypoints only.

**Comment by moving-bits** [comment]
Regarding the button labels: 

In our `Dialogs` library we have a set of standard dialogs. The one used in this case is labelled `confirmYesNo(...)`, so you would expect to have buttons labelled `Yes` and `No`. If you look into the source of this dialog, it's using the Android string resources named `android.R.string.yes` and `android.R.string.no` which I would have expected to be `Yes` and `No` for English - but they aren't! They are set to `OK` and `Cancel` instead...

I can change this in our `Dialogs` library to fixed constants `Yes` and `No` (which then would have to be translated) for the `confirmYesNo(...)` dialogs. This would change all dialogs based on that to use `Yes` and `No` instead of `OK` and `Confirm` - which probably is what the original authors wanted them to be anyway, but never have been yet.

I'll prepare a PR for this. We should keep an eye on our dialog boxes whether `Yes`/`No` is ok or `OK`/`Cancel` fits better.
