### ISSUE TITLE
Webview - No other browser option if Chrome installed

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9419]
**Describe the bug:**
In the menu "open in browser" from cache only Chrome is offered.

**To Reproduce:**
1. Go to a cache page
2. Click on menu
3. Chose  "open in browser"

**Actual behavior/state after performing these steps:**
Only Chrome is offered

**Expected behavior/state after performing these steps:**
Chrome and Firefox should be offerend. This happens when I open (via long click) the menu of a single log with the menu item open in browser there. 

**Version of c:geo used:**
2020.11.21-NB-612de32

**Is the problem reproducible:**
Yes 

Maybe connected to #6680  ?

**Comment by fm-sys** [comment]
For sure this is caused by fixing #6680 (#8943)

@geocachermgo Could you please post a screenshot of what is shown exactly after selecting "open in browser"? Are you  using chrome beta or the normal version? And which browser is selected as default browser? Sorry for that many questions, but these info's are necessary for trying to reproduce it...

**Comment by geocachermgo** [comment]
Sequence open cache:
![IMG_20201121_163813](https://user-images.githubusercontent.com/43813636/99881175-688f6f80-2c18-11eb-9e4d-922b84c2a976.jpg)
![Screenshot_2020-11-21-16-36-42-652_com android chrome](https://user-images.githubusercontent.com/43813636/99881159-4b5aa100-2c18-11eb-9c5d-027e1d17bbea.jpg)

Opening a log looks like 
![IMG_20201121_163907](https://user-images.githubusercontent.com/43813636/99881241-e18ec700-2c18-11eb-8e04-22fb4dad634a.jpg)

![Screenshot_2020-11-21-16-37-05-378_android](https://user-images.githubusercontent.com/43813636/99881153-3ed64880-2c18-11eb-9eab-e14381fec34a.jpg)

I do not use Chrome at all. Since its bloatware I cannot deinstall it.
If have not chosen a default browser.

**Comment by Lineflyer** [comment]
I think the problem is, that we start the webview (as chrome is installed) but in this case it has never been configured/used so the "first start dialog" of chrome is shown instead of the webview.
That might happen to quite some users as - as mentioned by @geocachermgo it is preinstalled on many devices as bloatware.
This will block open in other browsers.

How about keeping the "Open in Browser" menu untouched (as in current release) and offer the webview in some dedicated menu or other clever UI solution to separate those functions.

**Comment by fm-sys** [comment]
I totally understand, that chrome shouldn't always be launched without a chooser or something like that. 

On the one hand a second dedicated menu item would help here, on the other hand the overflow menus in cgeo are already way to long. 

So what about adding a settings option for it (with custom tabs *deactivated* as default)? That would even give us the possibility to use custom tabs at all other places where we have the "open in browser" action if it is explicitly requested by the user...

**Comment by Lineflyer** [comment]
> So what about adding a settings option for it (with custom tabs deactivated as default)? That would even give us the possibility to use custom tabs at all other places where we have the "open in browser" action if it is explicitly requested by the user...

That is probably the easiest possibility and better to offer to different "Open In Browser" items.
But I would rather call such menu item "Use Chrome webview" instead of "custom tab".

**Comment by fm-sys** [comment]
> But I would rather call such menu item "Use Chrome webview" instead of "custom tab"

Totally agree! Names and descriptions should always be written in a way, that everyone can understand them also without development background...
