### ISSUE TITLE
Store images as personal note for a cache

### ISSUE THREAD

**Issue by la9xfa** [cgeo/cgeo#9432]
Would be nice to store images as personal note to a cache, not only text.

**Comment by moving-bits** [comment]
While we cannot store images to the personal note (as it is text-only), our new image gallery will allow to upload user-defined images. New image gallery is marked experimental for now and available in developer versions or after explicitly activating it in released builds.

Therefore closing this issue here.

**Comment by eddiemuc** [comment]
There is still issue #13252 which requests storage of uploaded image names and such in personal note.
