### ISSUE TITLE
Color ratings to make them easier to read

### ISSUE THREAD

**Issue by Savvasun** [cgeo/cgeo#9449]
### Color difficulty and terrain ratings based on their value to quickly see how hard the cache is.

This would make looking for caches quicker and easier on the eye.

A good **solution** would be checking the value of each rating and coloring them **green to red** (low to high rating, respectively.)

**Comment by SammysHP** [comment]
> A good solution would be checking the value of each rating and coloring them green to red (low to high rating, respectively.)

Except for color blind people. ;)

**Comment by Lineflyer** [comment]
Of course we could give the stars we use different colors but IMHO this would make the overall design look even worse. My opinion.
I think already now users can easily recognize the ratings by the red stars in contrast to grey stars.

**Comment by eddiemuc** [comment]
Question: is this about a change in cache lists or should this happen also on the live map (by coloring the cache symbols somehow)?

**Comment by Lineflyer** [comment]
Please let us not put more information into the cache icons on map.
On one hand they are overfreighted already on the other hand we do not have ratings for unsaved caches received on map AFAIK.

**Comment by moving-bits** [comment]
> Please let us not put more information into the cache icons on map.

Fully agreed.

> [...] on the other hand we do not have ratings for unsaved caches received on map AFAIK.

Are you speaking of GCVote rating (which we do not have without downloading the cache) or the D/T rating? For the latter we do have the info on the live map popup, without the need to download the cache first.

**Comment by Lineflyer** [comment]
> Are you speaking of GCVote rating (which we do not have without downloading the cache) or the D/T rating? For the latter we do have the info on the live map popup, without the need to download the cache first.

Oh, you are right. Still I wont encourage to implement this info into the icon.

**Comment by moving-bits** [comment]
BTW: Such a marker could be implemented manually by creating lists like "D/T > 3" etc., assigning a list marker to it, and copying the relevant caches into those lists. Then you'll see the appropriate colored dots on the map's cache icons. (That's a workaround I use for marking caches where I need special equipment for, eg. a ladder)

**Comment by MagpieFourtyTwo** [comment]
@moving-bits: How did you manage to get an insight into my c:geo usage ...?  :O
;)

**Comment by Lineflyer** [comment]
@Savvasun 

Can you please answer the question of @eddiemuc :
> Question: is this about a change in cache lists or should this happen also on the live map (by coloring the cache symbols somehow)?

**Comment by MagpieFourtyTwo** [comment]
> This would make looking for caches quicker and easier on the eye.
> A good solution would be checking the value of each rating and coloring them green to red (low to high rating, respectively.)

Sorry, but I fully disagree.

Reasons:
1. users do not even get, what the already existing background coloring of the Favo/TB field means.
   Which is BTW even harder to understand, as the ``Sort`` by ``Rating`` does not work properly,
   making even right guessing guys unsecure if this does really represent the GCvote rating.
2. Coloring e. g. T1 green and T5 red seems to suggest that every T5er is harder than anything,
   which is a serious misjudgment occasionally, as e. g. Biltema or ladder caches,
   which de facto have to be listed as T5 (on gc.com) cause you need equipment,
   but in fact they are *way* easier than most T4 or T4.5 in the very most cases,
   thus it's effectively impossible to base a classification of "hardness" on T-rating.
3. Same applies to D-rating, esp. since there are more and more Biltema caches - which are oftenly listed as D4.5
4. greed and red are hard to see for about 10 % of men, thus distinguish with these colors is not a good idea at all
5. Coloring in map; would most probably render the list marker useless.
6. Coloring in lists: if background should be colored, this would most probably collide with light and dark theming,
   and if just the text should be colored ... see 4. Moreover a different text color would reduce contrast and readability
7. at gc.com there are 9 T and 9 D ratings - thus 81 shades between green and red? Who should distinguish these?
   And even 9 per rating would be hard to see. Moreover no chance for guys of point 4. ...

IMO the currently available possibilities are completely sufficient, as you can a) filter and b) sort for D as well as for T.
And save results to different lists, as you like.  And you can mark this list with a color of your choice,
which may even be used to colorize the caches yourself by D/T rating.

Moreover, once the range filters, discussed in #9081, move in, all this will not be needed anymore anyway.
And if range filters are even combinable ...

**Comment by moving-bits** [comment]
With having the current works on the new filtering system in mind I propose to close this issue (as we will have range filters etc.).

**Comment by moving-bits** [comment]
Let's close this issue as we have
- the new filtering system by which you can filter caches according to your choice,
- and we have the option to add a D/T rating marker to the cache symbol (see settings => map => d/t rating in cache symbols)

meanwhile.
