### ISSUE TITLE
make "Start backup" a real button

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9486]
There still was the suggestion of @alan666notb to make the ``Start backup`` text more prominent ...

While I would suggest the same for ``Start restore`` and ``Restore a different backup``, too,
cause for a not knowing user it's not really obvious that theses texts are in fact buttons ...
(to be honest, I stumbled upon this, too, when I used the new dialog for the first trime, 
although I already was *really* experienced in performing backups ... ;) ).

_Originally posted by @MagpieFourtyTwo in https://github.com/cgeo/cgeo/issues/9104#issuecomment-737192373_

---

I started working on it, but it is not that simple how it might look like. First I have tried to use the "normal" c:geo button style, but just adding a working button to a preference screen is already a hard challenge. Up to now I haven't got it running at all...  :-/

So if someone else wants to dive into it, it would be very welcome!

**Comment by moving-bits** [comment]
Do we really need a preference screen for backup / restore?
If not, we could implement that screen as a regular activity with any layout we like.

**Comment by Lineflyer** [comment]
I would leave it in the preferences for now as I do not see a real advantage.

**Comment by moving-bits** [comment]
We have two different aspects:
- placement in UI - it's located in the main screen's three-dot menu, close to "settings" menu entry - no need to change, IMHO
- technical implementation: Backup/Restore is technically based on preferences, though I do not see the technical need for that, but we have a couple of limitations because of that inheritance

**Comment by MagpieFourtyTwo** [comment]
Ok - seems as if this FR is way more problematic than I would have expected.
Moreover other "Pseudo-Texts" like e. g. the config "buttons" for ``Services``, ``Select Map Source`` or ``Navigation Menu`` in fact "lack" visibility in the very same way, thus one can even call this c:geo's way of doing it.  ;)

So, if it's ok for @alan666notb I would suggest to just drop the idea ...

**Comment by alan666notb** [comment]
Looking at the other menus you mentioned, maybe the problem is just that the "Start backup" text doesn't have an underline. All the other buttons in other menus have separators above and below them.

The "Restore a different backup" would need one too.

**Comment by MagpieFourtyTwo** [comment]
Admittedly, the separation line confused me, too, at least in the beginning,  ;)
This is, because it seems to be not really consistent. And seems to follows some kind of "reverse logic":
So it separates topics (like in main settings menu) as well as subtopics (like in the Services list),
but does *not* separate the last subtopic from the (headline of the) next topic.
Moreover it is used as underline for the main topic headers ...
which in fact strengthens the impression, that the last subtopic is missing it's line, so the last subtopic looks a bit lost ...

**Comment by moving-bits** [comment]
Found a solution for "real" buttons in preferences, see #9530.

(A possible alternative would be to move backup/restore out of `preferences.xml` and create a regular activity with its own activity layout for it.)
