### ISSUE TITLE
Map settings pop-up too large

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9540]
In my emulator the map settings pop-up isn't fully usable. I assume that quite some users will have the same problem...

As a solution, the pop-up could be made scrollable.

![grafik](https://user-images.githubusercontent.com/64581222/102131966-483b8500-3e53-11eb-87f8-6d9573b42874.png)

**Comment by Lineflyer** [comment]
In one of my test devices I have the related problem, that due to the size of the window its unintuitive to close it as it fills the whole screen. So I am unable to dismiss it by clicking outside but have to use the back key.

Once its scrollable...how about adding an OK as well

**Comment by MagpieFourtyTwo** [comment]
Scrollable and [OK] button would of course be a workaround, but IMO do not really comply with the intention of the popup, which should provide *quick* access to oftenly used settings: If you first have to scroll and then click [OK], the advantage against the menu is lost, IMO. So I would prefer a different solution ... at least where it's possible ...

What came to my mind first was, that the symbols and text in the screenshot posted above seem to be really big. So would it be possible to resize them, to make the whole popup cover just let's say 80 % of the vertical size screen?  To avoid at least scrolling?

OTOH there would still be the possibility to switch to a two column layout, with only significant text per entry ...?

**Comment by bekuno** [comment]
> Once its scrollable...how about adding an OK as well

How about adding a close symbol in the headline like in the `add waypoint` dialog?

One additional idea - how about change the 3 buttons for `use compact icons` to a single 3 state button? (Yes, then you have to click one more sometimes)

**Comment by geocachermgo** [comment]
It ia possible to place the radio buttons for "compact icons" and "routing" right of the text so its only only line?

**Comment by geocachermgo** [comment]
If we have 3 colums if checkboxes we could also group
Caches _______ Own/found ☑ disabled ☐ archived ☐
waypoints ____  Original ☑ Parking ☐ Visited ☐
track _____ History ☑ GPX ☐

**Comment by moving-bits** [comment]
> Once its scrollable...how about adding an OK as well

As this is needed only if the screen is already to crowded, I would not put an extra button at the end of the list (neither in the scrollable part nor in the non-scrollable part), but put a "Close" button as icon in the actionbar (as we already have in other popups/views).

**Comment by moving-bits** [comment]
> If you first have to scroll and then click [OK], the advantage against the menu is lost, IMO. 

Even with a "Close" or "OK" button, closing the dialog using back button or clicking elsewhere on the map (if visible) would/should still be possible.

> What came to my mind first was, that the symbols and text in the screenshot posted above seem to be really big.

The screenshots above may be a bit deceiving. My "regular screenshots" are made from a HD resolution emulated device, scaled to 33%, whereas the screenshots above are made from a low-res emulated device intentionally, and scaled by 50%.

> OTOH there would still be the possibility to switch to a two column layout, with only significant text per entry ...?

I tried to avoid this so far, as it would include quite a bit of manual positioning the elements (or so I thought), and the solution we have has worked so far. I will investigate how to populate a two (actually: four, with the icons) column layout programmatically and have it consistent in the layout.

**Comment by moving-bits** [comment]
> How about adding a close symbol in the headline like in the `add waypoint` dialog?

Yes, sounds good.

> One additional idea - how about change the 3 buttons for `use compact icons` to a single 3 state button? (Yes, then you have to click one more sometimes)

Is there some official Android UI element for this?

**Comment by moving-bits** [comment]
> If we have 3 colums of checkboxes we could also group
> caches _______ Own/found ☑ disabled ☐ archived ☐
> waypoints ____ Original ☑ Parking ☐ Visited ☐
> track __________ History ☑ GPX ☐

(We had this discussion already in the related issue.)
Generelly this would be a nice idea, but with the text labels needed there would not be enough space for a four-column layout. In the related issue there is a screenshot for a two-column variant, which may be feasible.

**Comment by bekuno** [comment]
> > One additional idea - how about change the 3 buttons for `use compact icons` to a single 3 state button? (Yes, then you have to click one more sometimes)
> 
> Is there some official Android UI element for this?

Don´t know. Problay not.
Possible solution could be like
https://stackoverflow.com/questions/16511535/creating-a-three-states-checkbox-on-android/40939367#40939367

**Comment by Lineflyer** [comment]
> As this is needed only if the screen is already to crowded, I would not put an extra button at the end of the list (neither in the scrollable part nor in the non-scrollable part), but put a "Close" button as icon in the actionbar (as we already have in other popups/views).

OK, I have to admit that my proposal for an "OK" button was a bit to fast. IMHO its fine for users also if the settings occupy the whole screen as they can still use the back button.

**Comment by moving-bits** [comment]
Reopening this issue as a reminder to myself, as further steps have to be taken.

**Comment by moving-bits** [comment]
Not much progress on a two column layout yet, even after several attempts and some hours spent on it:

I have not been able yet to find a way for setting a two column `RelativeLayout` programmatically.

So I tried hard-coding it (just for the purpose to see whether this works at all). So far I've come up with this:
![image](https://user-images.githubusercontent.com/3754370/102657241-a202be80-4175-11eb-993a-9cbab4adc70f.png)

Quite not ready, IMHO:
- too crowded (IMHO) - maybe some dividers would help (eg: between the caches section and the waypoint section), but that would cost space as well
- have not found a way to align the second column entries to each other - see the "archived" not being aligned to "visited"
- vertical alignment doesn't work any longer, since everything is just in a `RelativeLayout` instead of each line being able to vertically center
- having to hard-code all this is not nice...

So if no one has some nice idea how to do this in a more elegant and more efficient way, I would stop my efforts here for now and stay with the dialog as-is.

**Comment by moving-bits** [comment]
How about this: (a)
- don't use any symbols for the "show" entries
- only use checkboxes 
- for compact icons / routing: try, whether checkboxes help, or stay with buttons

Would look something like this:

Show caches
[ ] own/found [ ] disabled [ ] archived
Show waypoints
[ ] original [ ] parking [ ] visited
Show other
[ ] circles [ ] direction
Use compact symbols
( ) on ( ) auto ( ) off
Routing
( ) straight ( ) walk ( ) bike ( ) car
[ ] auto target individual route

---

Or how about this (b):
- as above, but make "show caches" and "show waypoints" two-columned

|Show caches|Show waypoints|
|--|--|
|[ ] own/found|[ ] original|
|[ ] disabled|[ ] parking|
|[ ] archived|[ ] visited|

(would still be four lines for that part instead of six, but gives the text a bit more space)

**Comment by moving-bits** [comment]
With the dialog now being scrollable (#9541) and having a back button in the title for easier closing (#9626) I propose to close this issue. Any objections?

**Comment by Lineflyer** [comment]
No objection,

**Comment by Lineflyer** [comment]
Let me reopen this one.
The above mentioned two fixes (scrollable quick settings and back button) have been applied to `master` only.
We should backport them to `release` as well, so that they will be contained in upcoming RC and in first release containing the quick settings.

**Comment by moving-bits** [comment]
I've prepared a PR for this, cherry-picking those commits not yet on `release` branch.

**Comment by moving-bits** [comment]
As it's included in current release we can close here.
