### ISSUE TITLE
Navigation icon hidden in overflow menu

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9569]
Report form support mail:
Since the last update I do no longer see the icon in the top bar for navigation (arrow with point). Before the last update compass icon, the navigate icon and the three-dot-icon have been shown.
Same also on the map, where I can no longer see the layer icon to change the map source directly.

Comment Lineflyer:
I am wondering if we changed anything with respect to the menu parameters for the different options (I mean those options like "ShowIfRoom", etc.). 
Aditionally I am wondering (in general as I can also see it on my phone) about the large gap between the back arrow and the cache type icon. This is wasted space, isn't it?

Thats how it looks for the user:
![Screenshot_20201221-115812_cgeo](https://user-images.githubusercontent.com/949669/102890921-8d684400-445d-11eb-9474-04cf2d0e433b.jpg)
![Screenshot_20201221-115823_cgeo](https://user-images.githubusercontent.com/949669/102890919-8ccfad80-445d-11eb-847d-ebd7b17d2cb8.jpg)

System information:
```
--- System information ---
Device: SM-G970F (beyond0lteeea, samsung)
Android version: 10
Android build: QP1A.190711.020.G970FXXS9DTK9
c:geo version: 2020.12.03
Google Play services: disabled - 20.47.13 (120408-344095733)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found archived
Hide waypoints: -
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (63,8 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (63,8 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (63,8 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (264,5 MB) on system internal storage
GPX import path: /storage/emulated/0/cgeo/gpx
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/3733-3132/Mapsforge/National
Map render theme path: /storage/3733-3132/Mapsforge/Themes/Elevate4/Elements.xml
Live map mode: true
Global filter: display all caches
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: dd.MM.yyyy
Installed c:geo plugins:  none
BRouter connection available: false
--- End of system information ---
```

I asked the user to try in portrait mode, which proofs, that the menu architecture works normal:
![Screenshot_20201221-211152_cgeo](https://user-images.githubusercontent.com/949669/102891024-ca343b00-445d-11eb-8b4c-cc35972c67b4.jpg)

**Comment by fm-sys** [comment]
Maybe the new release is unrelated and he just had changed the system front size setting? The font size looks at least larger than default...

**Comment by Lineflyer** [comment]
I did also ask that, but the user said he did not change it. I asked the user to simply reboot and check again.

**Comment by MagpieFourtyTwo** [comment]
Maybe it's a device specific thing, but I would also assume he changed display or font settings.  Perhaps w/o even knowing.  Maybe he has applied a new design ....?  Or perhaps just needs to reboot.  Had this the other day, when fonts turned wild - and a reboot "cured" it.

Background: Following [inside digital](https://www.inside-digital.de/handys/samsung-galaxy-s10e) the SM-G970F (aka S10e) has a display resolution of 1.080 x 2.280 pixel, which is pretty much the same as my [P30 Pro](https://www.inside-digital.de/handys/huawei-p30-pro) has (1.080 x 2.340 Pixel).

But even if I set my "Display size" to "Normal" (is usually set to "Small", while "Font Size" is always set to "Normal" anyway), thus getting a *really* big font, I can over here see even less of the first example's name ("ges..."), but *both* icons, i. e. Nav *and* Nav Tool. And the attributes fit all in one row and I have to set "Display size" to "Big", in order to get a line break ...

Second example: If I display it, there is a way bigger gap between GC code and Nav Tool icon. In fact, the closing bracket of the GC code does barely reach the is middle of the screen.

BTW: As display size will perhaps become an issue with e. g. the new Quick settings menu, it may perhaps be a good idea to add the screen resolution and settings for "Font size" and "Display size" to the "System Information" (if available)?

BTW 2: Just stumbled upon a different thing: After switching the phone off and on again several times and changing orientation from portrait to landscape a few times, I even get the icon for "Log Visit" and "Toggle talking" (in the Details page!) - and, wonder waht? No cache title anymore ... ;) Which could not be changed by switching to landscape and back again, but only by leaving the cache listing and re-opening the cache. So, in fact, I just have observed just the opposite of the OP's problem.  ;)

**Comment by Lineflyer** [comment]
Lets close here as the user did  not follow up and there has been no other report. Anyway a lot changed.
