### ISSUE TITLE
UTF16-LE filed note files cannot be uploaded (manually) to GC.com

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9686]
With the fix for #7404 we changed the file encoding from UTF16-BE to UTF-16LE.

We have tested this change so far:
- Automatic upload to gc.com still works normal
- Users confirmed, that #7404 (not possible to import to GSAK) is fixed

But:
As I wondered about the comment in another issue (https://github.com/cgeo/cgeo/issues/9640#issuecomment-754785250), that files need to be UTF16-BE to work, I tused the field note text file from cgeo/fieldnote and try to upload it manually via the website of geocaching.com I get the response "Could not find new drafts to upload." 

Why is that? IMHO we use the very same website to upload from c:geo.

**Comment by Lineflyer** [comment]
Can someone test that and confirm. 
Its really strange. I cant even open the fieldnote.txt normally in my PCs text editor (PS pad) as it opens in hex view. PS pad should be able to deal with any byte order.

**Comment by moving-bits** [comment]
From retesting:

- Created an offline log within c:geo and did an export fieldnote
- Fired up gc.com in a browser and did a "upload draft" for the new file

=> worked without problems

BUT:
- When I tried to upload a second file for the same cache, gc.com displays an error "Could not find new drafts to upload.".
- When I reload the uploaded file from step 1, it even warns me that I will not be able to upload another draft for this cache.

So it looks that this is intentional (even if it looks dump to me, IMHO).

**Comment by Lineflyer** [comment]
OK, then lets not block any release because of that.
I will for sure retest it more carefully and we might also get some user feedback in case this is a real issue.
Still users have the workaround to just use the c:geo upload.

**Comment by SammysHP** [comment]
In the past there was an option at geocaching.com "Ignore logs before xxxxxxx" when youuupload field notes that was checked by default.

**Comment by Lineflyer** [comment]
Today I tested again a manual upload. This time no failure. So lets assume it was my testing mistake or something unreproducible.
