### ISSUE TITLE
Jenkins IRC bot not reacting properly to commands

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9749]
Since a long time (>1 year) the Jenkins ircbot (plugin to Jenkins) has a problem:
- It reports the build outcomes as desired
- It however does no respond to any defined commands such as ˋ!!helpˋ. It does however respond to unknown commands (such as ˋ!!kjhdfjkˋ) with a (correct) error message

What I tried to debug:
- Plugins for IRC and instant-messaging have been bumped to newest version
- On Jenkins we seem to use a bouncer on localhost to connect the plugin to the IRC channel. I altered the setting to let the bot connect directly. This worked but resulted in exact same faulty behavior.
- I changed the prefix from ˋ!!ˋ to something else. The faulty behavior remained with the new prefix.
- I tried different charsets (UTF-8 default). But as assumed (only relevant for outputs not inputs) nothing changed

On the internet I found the issue:
https://issues.jenkins.io/browse/JENKINS-35179

Sadly the report is old and without solution. However the plugin itself seems maintained, but I don't know where to report such issue.

**Comment by eddiemuc** [comment]
I agree that it would be useful to have a developer chat option available, and I appreciate that @Lineflyer proposes sort of a restart for this.

But since the old IRC way seems to make problems and it is kind of a restart anyway: wouldn't this be a good point to switch to a more modern tool than IRC?

My suggestion would be Gitter (due to its deep Integration with GitHub): https://gitter.im/

What do you say?

**Comment by SammysHP** [comment]
IMHO IRC is modern enough, widely supported and well tested. And we use it since 2012. ;)

**Comment by Lineflyer** [comment]
I took a look into Gitter but and it has some advantages but I somehow love the simplicity of IRC as well.
I remember we gave Gitter a try some years but at that time most people were in advantage of IRC:

I am open to new solutions but it should at least offer the CI integration we had/have on IRC.

**Comment by eddiemuc** [comment]
Hm for someone new to it (like me) IRC is not simple at all. Actually it seems to me rather complicated when compared to actual chat solutions. Or I did not find a good client yet (tried Revolution IRC), any recommendations?

CI integration with Gitter should be rather simple since it has a full-fledged REST API.

But since not much seems to happen in the chats anyway (neither Gitter mir IRC), maybe this is all not very important.

**Comment by Narrat** [comment]
Why complicated? It is different that you need to connect to a specific server before you can join rooms/channels (on that server) But after this hurdle it should fairly straight forward.
Just asking for Android recommendations?

**Comment by Lineflyer** [comment]
no longer needed.
