### ISSUE TITLE
[SAF] Permission dialog repeatedly shown on startup

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9781]
Using 2021.01.11-NBSAF1-fb73c43:

- After updating to the initial SAF version the "Grant access for data storage" dialog shows up
- I selected DEFAULT with no copy/move (not needed anyway in the default case)
- Toast shown "Folder set to `/storage/emulated/0/cgeo (Default)`"
- Use c:geo normally
- End c:geo and remove from memory
- Start c:geo

Result:
- Grant access dialog shown again

Can be repeated on each start of c:geo.

**Comment by eddiemuc** [comment]
This is as it is currently implemented. Startup dialog will (or let's say **should**, given your other finding with GPX) disappear once you select a user-defined dir for base.

The default dir is a File-based dir, pointing to today's standard dir. I left the option to select "default" for base-dir so in case of migration problems the user has the chance to set it back and start again. This behaviour can be discussed of course.

**Comment by Lineflyer** [comment]
OK, I thought "Default" refers to trigger the SAF process but use the default folder as base. But it instead uses the legacy access.

I have to think a bit about a suitable process here e.g. in case of migration problems.

**Comment by fm-sys** [comment]
Maybe we can rename "Default" to "remind me later" to make clear that this is only a temporary suppression...

**Comment by eddiemuc** [comment]
Just for clarification: the "change folder" dialog is currently not designed specifically for migration scenario. 

It is specified in a "generic" way suitable for all public folder change actions. All of the public folders are in principal user-definable (but for some there is no such option in settings), and all of them have a default-value to use in case the user does not (want to) specify a user-defined value or the user-defined dir is not accessible. For "base" folder, this default value is the legacy value "/cgeo" (and if this is not accessible it falls back to "Documents"/cgeo, and if this is not accessible it falls back to an internal dir). For all other folders this default value is "(base-dir/(folder-name)" e.g. "(base-dir)/logfiles" for LOGFILES folder.

This can all be questioned of course, also the design of the dialog can of course be changed. But I tried not to make too many special functionality "just" for migration because this is really hard to test and also somehow "lost code" (only used one time).

**Comment by Lineflyer** [comment]
> Maybe we can rename "Default" to "remind me later" to make clear that this is only a temporary suppression...

In fact there is no difference right now between "Default" and "Cancel" in this particular dialog, or am I wrong?

**Comment by eddiemuc** [comment]
> In fact there is no difference right now between "Default" and "Cancel" in this particular dialog, or am I wrong?

Hm, you are right, never thought of that: when you open the change dialog for a folder which is currently set to default, then providing "Default" as a selection value makes not too much sense. Should I leave out this choice in this case?

**Comment by moving-bits** [comment]
> Should I leave out this choice in this case?

Probably, to avoid confusion

**Comment by Lineflyer** [comment]
> Should I leave out this choice in this case?

I also think so, because (thats why I opened the issue) users might assume that default just finishes the SAF-selection and everything is done using some kind of default setup which is not the case (and cannot be the case due to the nature of SAF requiring the user to explicitly confirm to select a folder).

However: "Cancel" and "Select folder" as options should do the job.

**Comment by eddiemuc** [comment]
Fixed and pushed to storage_framework

**Comment by eddiemuc** [comment]
Small "process question": can I close these SAF-issues once they are fixed on `storage_framework `or shall they stay open until `storage_framework ` is merged to `master`?

**Comment by Lineflyer** [comment]
Theoretically you could already close them. But lets keep this one open, I will retest it and then close.

**Comment by Lineflyer** [comment]
Works now as expected. Thanks @eddiemuc
