### ISSUE TITLE
User defined lanuage "en" set after upgrade

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9787]
We had three cases on support mail where people from UK stated, that they do now see the american date format (M/D/Y) in c:geo despite the european (D/M/Y) which they had seen before.

The sysinfos typically look like this:
```
--- System information ---
Device: SM-A515F (a51nseea, samsung)
Android version: 10
Android build: QP1A.190711.020.A515FXXU4CTJ1
c:geo version: 2021.01.10
Google Play services: enabled - 20.47.14 (120400-349456378)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en / user-defined language: en
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (70.5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (70.5 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (70.5 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (13.0 MB) on system internal storage
Last backup: Jan 11, 16:37
GPX import path: /storage/emulated/0/cgeo/gpx
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/emulated/0/cgeo
Map render theme path:
Live map mode: true
Global filter: display all caches
Sailfish OS detected: false
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd MMM yy
Installed c:geo plugins:  none
BRouter connection available: true
--- End of system information ---
```
I asked the user to set the language to "system default", that user replied:
For some reason no language was selected at all, not even default. I have now set to default and all is fine.

**Comment by Lineflyer** [comment]
Side note: Its a known fact, that when users in the past used the "Force English" setting c:geo then also used the american date format.
So the main point here is, why something else than system-default is active after upgrading. 
@moving-bits Is any setting migration involved here?

**Comment by moving-bits** [comment]
For reference: language switching is based on `settings/Settings.java`:

```
public static Locale getApplicationLocale() {
    final String selectedLanguage = getUserLanguage();
    return StringUtils.isNotBlank(selectedLanguage) ? new Locale(selectedLanguage, "") : Locale.getDefault();
}

public static String getUserLanguage() {
    return getString(R.string.pref_selected_language, Settings.getBoolean(R.string.old_pref_useenglish, false) ? "en" : "");
}
```

So it checks the setting referenced by `R.string.pref_selected_language`, which is either empty (= default) or contains a language identifier like `de`.
This preference is not yet set when starting c:geo in the new release, so it defaults to `Settings.getBoolean(R.string.old_pref_useenglish, false) ? "en" : ""`, which is checking the old setting for "use english" and returning either "en" if it's set and true, or "" otherwise.
=> Should be fine, IMHO.

I guess those people had "use english" activated, so c:geo now applies a `Locale("en")`.
Maybe the current way c:geo realizes the language switch has other implications than the old way, eg. setting to `Locale("en")` may imply a US-like date format instead of leaving it unchanged or imply European-based?
=> Will have to check in the code in more detail in the evening.

**Comment by moving-bits** [comment]
From reading a bunch of docs it seems to me that `setLocale("en")` defaults to `setLocale("en", "US")`.
(For reference: `setLocale(...)` in Java is `setLocale(language, country)` (and other variants).

Possible solutions (untested yet, will try in the next days):
- either for each language offer the different available countries for manual selection
- try do get the system-selected country and see, if a combination of selected language and system-selected country is available as locale, and if so, select it

**Comment by fm-sys** [comment]
is en-DE for example a valid language code? If yes, we should IMHO set the country always to the users system country while the language is selectable...

**Comment by Lineflyer** [comment]
Just a short comment regarding the priority of this issue:
It can be easily resolved by verifying the language selection and set it back to system-default. Both users confirmed, that this solved their problem and c:geo followed their system date format settings afterwards.

So if this is only something transient or maybe even device specific I am perfectly fine with closing this issue.

**Comment by moving-bits** [comment]
> is en-DE for example a valid language code? If yes, we should IMHO set the country always to the users system country while the language is selectable...

I did a quick test in the emulator:
- System is configured to use German as default language, and date/time formatting according to language default.
- Set custom language in c:geo to "en"
- Adapted the source to use the chosen `language` as first parameter to a new locale, but use `country` and `variant` codes from the current locale default.

This resulted in a `en_DE` locale code. But still the date formatting changed to `Sat, 20/03/2021` (event listing in cache list), whereas without a custom language it was displayed as 'Sa, 20.03.2021'.

So that light approach (a one-liner) sadly does not work.

**Comment by moving-bits** [comment]
> is en-DE for example a valid language code? If yes, we should IMHO set the country always to the users system country while the language is selectable...

`en_DE` is actually available, at least according to Apache Commons `LanguageUtils.countriesByLanguage("en")`, but setting this value for locale still has no impact on the way c:geo displays numbers or days in the `CacheListActivity`.

Haven't dived more deeply into this due to being low prio.

**Comment by MagpieFourtyTwo** [comment]
Same applies BTW to the date which replaces the ``[DATE]`` macro in the logging template: Although app language is ``en`` and Android's country is set to ``Germany``, the date in the log will be s/th like ``May, 06 2021``.

At least right after c:geo had started from scratch, cause after a while (esp. if mobile was in sleep mode) the translations get mixed up between ``en`` and ``de`` (i. e. ``Details`` page remains to be in ``en``, apart from the ``Stored in device xx minutes ago`` which will be German then, while ``Logbook`` will completely switch to German, as well as ``Friends/Own logs``) - but as soon as this "language mixup" has started, the date for ``[DATE]`` will be ``06. Mai 2021`` then ...

**Comment by moving-bits** [comment]
Still relevant? 
(with migration of language settings being more than a year old by now, so most users are using our current way of setting program language)

**Comment by moving-bits** [comment]
closing this stale issue, as it refers to the original migration, which is more than a year ago. Any other possible issues regarding language inconsistencies should get their own separate issues.
