### ISSUE TITLE
Can not select folder to restore external backup

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#9850]
**Describe the bug:**
I want to test on my test device with a saved backup from another device.
With the file manager it is only possible to select the given internal user path (`/data/user/0/cgeo.geocaching/`), but no external storage (`/storage/emulated/0/`). 

**To Reproduce:**
1. Try to "restore a different backup"  
2. The initilal path is `/data/user/0/cgeo.geocaching/`

**Actual behavior/state after performing these steps:**
Only the users internal storage in accessible.

**Expected behavior/state after performing these steps:**
A possibility for acessing the external storage.

**Version of c:geo used:**
2021.01.24-NB

**Is the problem reproducible:**
Yes

**Comment by bekuno** [comment]
One solution could be a button "restore external backup" which starts with the external path.
This should be also the right place for a restore from the start assistent.

**Comment by eddiemuc** [comment]
Behaviour of this will need to change significantly with SAF. Is it possible to postpone this issue until then?

**Comment by fm-sys** [comment]
This is a new issue introduced by the installation wizard, which is also tracked in #9700. In this issue we decided to fix it with  #9720 implicitly when we have merged SAF to master.

**Comment by fm-sys** [comment]
> One solution could be a button "restore external backup" which starts with the external path.

Backups are *always* external. Otherwise they would be deleted when uninstalling the app. If you skip the backup section in the installation wizard, and restore the backup manually afterwards, the chooser will use the correct path...

**Comment by bekuno** [comment]
> Backups are _always_ external. Otherwise they would be deleted when uninstalling the app. If you skip the backup section in the installation wizard, and restore the backup manually afterwards, the chooser will use the correct path...

My test backup was deleted after reinstalling (nightly replaced by PR).
And I could not copy the backup from the other device in the default path (see above).

**Comment by Lineflyer** [comment]
For me the initial folder is `/storage/emulated/0/cgeo/backup` when selecting the "restore from other location". Everything normal.

**Comment by Lineflyer** [comment]
@bekuno What you experienced is the result of  #7366. You need to restart c:geo after granting file permissions to have the correct path.

**Comment by moving-bits** [comment]
Hm, this is a bit confusing:
- `externalPublicCgeoDirectory` is set to the first available folder directly on startup, which is the internal folder, if no rights are granted. => ok
- Using our internal `PermissionHandler` the `externalPublicCgeoDirectory` should be reset after granting storage access (by calling `resetExternalPublicCgeoDirectory`), so that the next request should be able to reach the external folder. => ok
- In the wizard I had not used our `PermissionHandler` but called the method directly. => bad ;-)
- That's why I thought the problem described in this issue occurs (and is actually related to the installation wizard. Problem is: Even if I use our `PermissionHandler`, the external public dir does NOT get reset, the callback is never called... => bad!
- I'll need to investigate further. For now, to be able to release, I've included a workaround by calling the `resetExternalPublicCgeoDirectory` method manually on requesting the storage permission.

PR is on it's way, but I'll leave this issue here open to investigate further what's going on behind the scenes.
