### ISSUE TITLE
Downgradable versions are ignored while restoring backup

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9863]
>>    The "Start Restore" worked, except that I am now getting "Expected version is 90, backup has version 93". Bummer!
>
>Version 90 and 93 should be compatible. Is it only a warning and c:geo continues to work with that version, or will it break?
(The latter would be an error, AFAICS.)
>
>(Compatibility of current nightly db version (93) should reach back into the mid-eighties, ever since we introduced the extra routines for backward-compatibility, and we carefully designed the changes following that version to not break this.)

I think this is a bug, which I also experienced before. DB version downgrade does only work when the DB is already active - not while restoring a backup. Therefore, it's currently impossible to restore a higher DB version...

_See also https://github.com/cgeo/cgeo/commit/b424f1b21f598887903d2877c564750a0e890701#commitcomment-46369011_

**Comment by moving-bits** [comment]
Found the root cause: `DataStore.versionsAreCompatible` checked against the currently opened database, which fails when trying to restore a backup after a fresh (re-)install, as the current db is empty in this case. It needs to check against the backup db we are trying to open. => I'm preparing a PR for it.
