### ISSUE TITLE
SAF migration: Mixed up offline map list (not alphabetically)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9870]
Taken from https://github.com/cgeo/cgeo/issues/9606#issuecomment-767478209 by @MagpieFourtyTwo 

After I at least restored the vector map folder, I ended up with a completely scrambled Offline Map list, which should be sorted alphabetically, again. ;)

**Comment by MagpieFourtyTwo** [comment]
Thx 4 the issue! ;)

**Comment by moving-bits** [comment]
PR is on the way...

**Comment by MagpieFourtyTwo** [comment]
Thx a lot for this quickie!  ;)

While "quick" may not be understood in terms of "was quick to do" but for "quick reaction".  ;))

**Comment by MagpieFourtyTwo** [comment]
Just tested - way better than before.
But most regretfully not the same like before ... cause right now underscores are sorted to the end of the list.
Before the SAF change, they were at the beginning ... that's why I name the maps used the most like ``_ DE BaWü Vosges``.
Can you perhaps change this to the old sort order?

**Comment by moving-bits** [comment]
Need to check how to. Currently I'm using the regular built-in string comparison rules.

**Comment by Lineflyer** [comment]
> Need to check how to. 

According to @MagpieFourtyTwo it worked as he described before...so maybe whatever method was previously used should be reused....but I guess its not so easy.

**Comment by moving-bits** [comment]
> but I guess its not so easy.

sadly, no, at least AFAICS, as the list of available map files comes from a different source now.

**Comment by MagpieFourtyTwo** [comment]
> Need to check how to. Currently I'm using the regular built-in string comparison rules.

Strange - as all android explorers I know sort "_" before letters ...

Ah, "string comparison" - so this one perhaps uses ASCII char code as sort criterion?
Cause in ASCII "\_" (95) comes in fact after "Z" (90).
Tried to verify with lowercase letters (as "a" is ASCII 97), but to no avail, as the Map list output function seems to uppercase all first letters.
However - I would assume, the old routine did not use an ASCII based string compare but a dedicated sort function ...?
As all the file explorers come to the same result (with "\_" before letters of any kind), I would assume there is a system routine for sort ...

**Comment by moving-bits** [comment]
After implementing my own collator for the fun of it (ahem...) found the right solution by applying the same specialized collator we'd used in the pre-SAF setting, just in this case applied to a `ImmutablePair<String, Uri>` instead of a simple `String`. Solution is easy, just needed some learning curve... \*sigh\*

**Comment by MagpieFourtyTwo** [comment]
Great! Thx! :)
