### ISSUE TITLE
Have "Refresh" available again via cache menu

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9880]
After discussion and clarification with two beta users (2021.01.24-RC) both have somehow valid arguments to have "refresh" available in the cache menu, e.g.:

> If I read the logbook of a cache and notice, that the newest log entry is rather old I went to the menu and could refresh it right away. No I have to swipe back to the details page, refresh, wait and swipe to logbook again.

> I have activated the setting to open new caches with the last selected page which is most likely for me not the details page. So now I have either to deactivate this setting to have the possibility to easily refresh the data or I need to swipe forth or back (depending on where I start) to finally be able to refresh the information.

These are IMHO reasonable use cases (which might affect more users), so we should consider to have the refresh option back in the menu.

BTW:
Both users stated that save/delete are rather unlikely for them to be used from the menu. For those they are fine with using the icons. Their only concern was refreshing.

**Comment by fm-sys** [comment]
We could also use a "swipe to refresh layout" like used in some browsers. Basically this is even easier than need to go to the menu. IIRC there even was a issue about introducing such a layout...? 

OK. I have found it, see #8888. Funny number BTW, where actually, quite a lot of numbers are in some form special... No matter!

If this alternative is deemed good, I could do the implementation.

**Comment by SammysHP** [comment]
> We could also use a "swipe to refresh layout" like used in some browsers.

Only if it is possible to abort the refresh (and without data loss). Refreshing a cache is not a fast and cheap operation. Often enough (in other apps) I swipe down and notice that I'm already at the top and the refresh cycle starts.

**Comment by Lineflyer** [comment]
On some apps I use I have seen a high threshold for pull down refresh (meaning you need to pull down a lot before it is triggered). Maybe this could prevent accidental scrolling refresh?

**Comment by SammysHP** [comment]
Yes, that helps. Maybe one third of the screen and only when released so that you have a chance to swipe in the other direction to not trigger a refresh. I've seen that in some apps and think I never had a problem with it. Most noticeably were apps that either have a really short distance or start the action automatically once the threshold was reached without waiting for the release.

**Comment by Lineflyer** [comment]
> If this alternative is deemed good, I could do the implementation.

Should we then short-term put Refresh back into the menu (on `release`) and agree on implementing #8888 (on `master` and in this step remove the menu entry then again?

**Comment by fm-sys** [comment]
Implementing the `SwipeRefreshLayout `turns out to be rather complex. Remember, we can't forget: We have a `ScrollView `in a `ViewPager `in a `SwipeRefreshLayout `which all of them must not negatively influence each other. After some setbacks I have now after a few hours an already quite presentable result. 

The question is whether we want to do a second beta and how long we want to wait with the release. The change should definitely not go untested to all users (the details page is after all the core function of c:geo!). However, if we do a second beta, it could also go straight into beta without the temporary quick fix after a few cross tests on different devices...

**Comment by fm-sys** [comment]
OK, my work is done, and hopefully I did not break anything. It's currently targeted to master, but I can easily retarget it to release, if you think that makes sense...

**Comment by bekuno** [comment]
> Should we then short-term put Refresh back into the menu (on release) and agree on implementing #8888 (on master and in this step remove the menu entry then again?

I personally would go in this way.
We have more time to polish and maybe use it on another places.

**Comment by fm-sys** [comment]
> > Should we then short-term put Refresh back into the menu (on release) and agree on implementing #8888 (on master and in this step remove the menu entry then again?
> 
> I personally would go in this way.
> We have more time to polish and maybe use it on another places.

We can merge it to master first and then decide whether we want to create a quick fix for release or cherry pick the commit... What do you think?

**Comment by moving-bits** [comment]
Nice addition, thanks!

> What do you think?

IMHO let's merge it to master first, test it in the nightlies in parallel to current beta phase, and if it works out well we can include it in release by cherry-picking, otherwise refine it on master.

**Comment by wolverine007** [comment]
Pull-down seems to be a feasible solution for refreshing the logs 👌🏻, was also searching today for the refresh menu entry...

If pulling down is to irritating for the user, what about double clicking the cache title or dragging the title bar down?

**Comment by Lineflyer** [comment]
More and more beta users contacting us missing the refresh item in the menu.
I suggest to put it back there anyway (later than additionally to the pull-to-refresh).

**Comment by fm-sys** [comment]
IMHO the pull to refresh is a full and even easier/faster replacement for the menu item, so I don't see a real reason for supporting 3 ways of refreshing a cache in parallel. The menu was way too large, which definitely affects efficiency. There is no suitable subcategory for refreshing and adding it directly would disturb the menu, which is so tidy at the moment.

Since the cache menu has been restructured anyway and users need to get used to it, now is the best time to replace "refresh" by the pull down gesture

**Comment by bekuno** [comment]
We are already in a release phase.  This is a problem of this beta release.
I think we should revert to the menu entry first and not introduce new changes.

We can later make a little feature / bug fix release where the change to the gesture is implemented.

**Comment by moving-bits** [comment]
"Pull to refresh" is merged to `master`, let's try it out there.
I'll create a PR for `release` to bring the "refresh" menu entry back temporarily.
Then we can decide to either release with "refresh" menu entry still there (= no change compared to current release), or with the new "pull to refresh" logic (by cherry-picking it to `release`).

But even if we decide to release with "refresh" still included, we should change this to "pull to refresh" with the next release (positive tests assumed), to keep the cache details menu clean.
