### ISSUE TITLE
Wizard: Skip first screen for migration

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9948]
I just installed todays nightly (on a device, where I not yet activated SAF).
It came up with the "Welcome to c:geo" screen and only on selecting "Next" the real SAF part comes up.

The welcome screen might be unexpected for existing users after an upgrade and might make them select "Skip" instead. How about skipping this screen as well and directly starting with the following page?

**Comment by moving-bits** [comment]
Or shall we use a "migration info" screen instead, something like

Welcome to c:geo migration
(some explanation about Android storage permission changes)

Since we can possibly have several pages for SAF folder migration (base, map, theme, gpx, ...), it's useful to explain the general change upfront, and the specific setting on the following pages.

**Comment by fm-sys** [comment]
Sounds good. Although we should rather explain what needs to be done from user perspective and not why... 

Nearly all users don't know what "SAF" is and are probably not interested to get a crash course how android internally works - they just want _that_ it works.

**Comment by eddiemuc** [comment]
Is there really nothing in the wizard which might also be useful in updates (rather than new installations) except for the SAF stuff?

If no I would simply leave out the initial welcome screen for update migration part

If yes I would just make a different "first Page" for it to use for upgrades ("welcome to the new version of c:geo. There are some exciting new feature which requires your attention", something like this)

**Comment by moving-bits** [comment]
Implemented a proposal with #9956 (see screenshot over there), closing here for now.
