### ISSUE TITLE
Picture not attached to log when rotation involved

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9973]
Found in 2021.02.06-NB, Samsung S20, Android 11:

- Hold phone in portrait mode
- Start logging a cache
- Write you log
- Typ icon to attach a new photo from Camera
- After camera has been opened, turn your phone to landscape mode (to make a nicer photo :) )
- Take the picture and confirm

Result:
You will return to c:geo logging view (now in landscape mode) but there is no photo attached

This happens as soon as the screen orientation of the logging view before and after invoking the camera is different.
Only if you return to the same screen orientation in the logging view, where you left it, it is working normal.

**Comment by eddiemuc** [comment]
Note to self wrt the cause of this:
ImageActivityHelper is in case of rotation change recreated from scratch during intent. Due to this is looses its internal state, sepcifically "runningIntents" is cleared. When intent comes to a result, no matching "runningIntents" is found, thus operation is abrted

To correct this:
* `ImageActivityHelper `must be redesigned to be able to store and return its state in some `Parceable ` structure. It must also provide a constructor where this state can be passed to reconstruct it on new creation
* `ImageListFragment `must store this state in its `onSaveInstanceState` method (method is not yet there, must be created) and recreate `ImageActivityHelper `with previously stored state in `onViewCreated`

**Comment by fm-sys** [comment]
Or set in the manifest, to handle config changes of rotation and size manually. Then the activity shouldn't be recreated. However, I do not know whether this has other negative impacts.

**Comment by eddiemuc** [comment]
@fm-sys that's a nice suggestion to circumvent this.

But I would in any case consider this a design error done by myself when creating `ImageActivityHelper `and `ImageListFragment` in the past:  I clearly forgot to handle "savedState" cases correctly as it is requested by Android Framework. And the error @Lineflyer found is just one result of this, there might be more not working correctly which was just not found yet..

**Comment by eddiemuc** [comment]
This is not as easy as I thought first, because the `ImageActivityHelper `stores callbacks (lambdas) to use when selection has finished. In the case described above, however, these lambdas point to e.g. an instances of  `ImageListFragment `which does not exist any more (was recreated by Android as a result of the orientation change).

Unless I want to restrict this to usage of static method reference lambdas somehow I have to find something else to use here than lambdas I feat. Damn and I like them so much...

**Comment by eddiemuc** [comment]
Notes to self:

I think I have to pass the activity class as well some callback reference object as parameters to callback. This reference object can then be changed to point to the actual instance referenced.

E.g. 
* constructor: ImageActivityHelper(Activity activity, T callbackReference);  (when called, T can be set to "this")
* callback of type: Action2<T, Image>
* implementation of a callback then uses T to interact (**not** "this")
* Instances of Action2<T, Image> must be serializable or better Parceable

This may work, need to think about this some more...

**Comment by eddiemuc** [comment]
More notes to self:
* After some googling: serialization of lambdas is not really a good and stable idea.
* CHECK: ContentStorageActivityHelper might actually have the same problem (test if folder select aborts when changing device orientation during intent)
 
New Idea: initialile ImageActivityHelper with a callback object which handles all callbacks:
* (constr) `ImageActivityHelper(Activity activity, Parceable initialState, Consumer<Integer, List<Image>> callbackHandler)`
   * "`initialState`" is an optional/nullable state object created by call to "getState()"
   * "`callbackHandler`" gets a REQUEST_CODE (cameraselect, storageselect or storagemultiselect) and the Image list returned. If not a multiselect, there will only be one image filled
* get-methods (e.g. `getImageFromStorage`) loose the callback parameter (replaced by the "callbackHanlder" above)
* new method "`getState`()" returns the current state of the helper as a Parceable

* state of `ImageActivityHelper` may not contain any callbacks any more, `callbackHandler `is used for that 

`ImageListFragment` and `ImageSelectActivity `must be adapted to save/restore helpers state and to put their callbacks all into the new 

Downside: callback logic is then not anymore in same place as select-calling-logic (same as in activity with onActivityResult method). I guess we have to live with that.

**Comment by eddiemuc** [comment]
PR #10104 fixes this. Note that although this error also occurs in release, I would rather prefer to have this fix not on release branch. Reason is that it involves a larger change in the underlying code design, and this should be severly tested (through nigthlies and beta) before it goes to production. Hope that's fine.
